#!/usr/bin/env python3
"""Spike-only generator: emits `benches/spike/benches/match_tables.rs`, a
hand-shaped `match id => Some(&TABLE.tags[i])` for IFD_EXIF_MAIN and
IFD_CANON_MAIN (what "compile the table to a native jump table" would look
like), plus the tag-id sequences the pinned ExifTool reports for the two
probe files (`-H -a -G1 -s`) so the bench can replay a realistic lookup mix.

Never wired into the build; run by hand:
    python3 tools/exiftool-tables/spike/gen_match.py
"""
import os, re, subprocess, sys

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..", ".."))
SRC = os.path.join(ROOT, "src", "exiftool_tables", "ifd_tables.rs")
OUT = os.path.join(ROOT, "benches", "spike", "benches", "match_tables.rs")
EXIFTOOL = os.environ.get("OXIDEX_PINNED_EXIFTOOL", "/tmp/oxidex-exiftool-cache/exiftool") + "/exiftool"
CORPUS = os.path.dirname(EXIFTOOL) + "/t/images"

src = open(SRC).read()
starts = [(m.start(), m.group(1)) for m in re.finditer(r"pub static (IFD_\w+): IfdTable", src)]

def ids_of(table):
    for i, (pos, name) in enumerate(starts):
        if name == table:
            end = starts[i + 1][0] if i + 1 < len(starts) else len(src)
            body = src[pos:end]
            # `tags: &[ ... ]` precedes `variants:`; ids inside it, in order.
            tags = body[body.index("tags: &["): body.index("variants:")]
            return [int(x, 16) for x in re.findall(r"IfdTag \{\s*id: (0x[0-9a-fA-F]+)", tags)]
    raise SystemExit(f"{table} not found")

def probe_dirs(file):
    """(directory name, [ids]) for every IFD-style directory ExifTool -v2
    walks, plus the count of IFD entries in total. BinaryData directories
    (ProcessBinaryData: field iteration, no id lookup) are excluded."""
    out = subprocess.run([EXIFTOOL, "-v2", os.path.join(CORPUS, file)],
                         capture_output=True, text=True, check=True).stdout
    stack, dirs = [], []
    for line in out.splitlines():
        m = re.match(r"^\s*((?:\| )*)\+ \[(\w+) directory(?:, (\d+) bytes| with (\d+) entries)\]", line)
        if m:
            depth = len(m.group(1)) // 2
            del stack[depth:]
            stack.append((m.group(2), []))
            dirs.append(stack[-1])
            continue
        m = re.match(r"^\s*((?:\| )*)\s*- Tag (0x[0-9a-fA-F]{4})", line)
        if m and stack:
            depth = len(m.group(1)) // 2  # a tag sits one level under its directory
            del stack[depth:]
            stack[-1][1].append(int(m.group(2), 16))
    return [(n, ids) for n, ids in dirs if n != "BinaryData"]

def probe_ids(file, names):
    return [i for n, ids in probe_dirs(file) if n in names for i in ids]

def probe_total(file):
    return sum(len(ids) for _, ids in probe_dirs(file))

def emit_match(fn, table, ids):
    lines = [f"pub fn {fn}(id: u16) -> Option<&'static IfdTag> {{", "    match id {"]
    for i, id_ in enumerate(ids):
        lines.append(f"        0x{id_:04x} => Some(&{table}.tags[{i}]),")
    lines += ["        _ => None,", "    }", "}"]
    return "\n".join(lines)

def emit_slice(name, ids):
    body = ", ".join(f"0x{i:04x}" for i in ids)
    return f"pub const {name}: &[u16] = &[{body}];"

exif = ids_of("IFD_EXIF_MAIN")
canon = ids_of("IFD_CANON_MAIN")
assert exif == sorted(exif) and canon == sorted(canon), "tables must be id-sorted"

canon_jpg_exif = probe_ids("Canon.jpg", {"IFD0", "ExifIFD", "IFD1", "InteropIFD"})
canon_jpg_canon = probe_ids("Canon.jpg", {"MakerNotes"})
nef_exif = probe_ids("Nikon.nef", {"IFD0", "ExifIFD", "IFD1", "SubIFD", "SubIFD1", "SubIFD2", "InteropIFD"})
canon_jpg_total = probe_total("Canon.jpg")
nef_total = probe_total("Nikon.nef")
print("dirs Canon.jpg:", [(n, len(i)) for n, i in probe_dirs("Canon.jpg")], file=sys.stderr)
print("dirs Nikon.nef:", [(n, len(i)) for n, i in probe_dirs("Nikon.nef")], file=sys.stderr)

with open(OUT, "w") as f:
    f.write("// GENERATED by tools/exiftool-tables/spike/gen_match.py -- spike only.\n")
    f.write("#![allow(dead_code, clippy::all)]\n")
    f.write("use oxidex::exiftool_tables::ifd_schema::IfdTag;\n")
    f.write("use oxidex::exiftool_tables::ifd_tables::{IFD_CANON_MAIN, IFD_EXIF_MAIN};\n\n")
    f.write(emit_match("exif_main_match", "IFD_EXIF_MAIN", exif) + "\n\n")
    f.write(emit_match("canon_main_match", "IFD_CANON_MAIN", canon) + "\n\n")
    f.write("/// Exif::Main ids ExifTool 13.59 reports for t/images/Canon.jpg (IFD0/ExifIFD/IFD1/InteropIFD).\n")
    f.write(emit_slice("CANON_JPG_EXIF_IDS", canon_jpg_exif) + "\n")
    f.write("/// Canon::Main ids ExifTool 13.59 reports for t/images/Canon.jpg (group1 Canon).\n")
    f.write(emit_slice("CANON_JPG_CANON_IDS", canon_jpg_canon) + "\n")
    f.write("/// Exif::Main ids ExifTool 13.59 reports for t/images/Nikon.nef (all TIFF IFDs).\n")
    f.write(emit_slice("NIKON_NEF_EXIF_IDS", nef_exif) + "\n")
    f.write(f"/// Total IFD entries (id lookups) ExifTool -v2 walks, BinaryData directories excluded.\npub const CANON_JPG_TOTAL_IFD_ENTRIES: usize = {canon_jpg_total};\npub const NIKON_NEF_TOTAL_IFD_ENTRIES: usize = {nef_total};\n")
print(f"exif_main={len(exif)} canon_main={len(canon)} canon_jpg_exif={len(canon_jpg_exif)} "
      f"canon_jpg_canon={len(canon_jpg_canon)} nef_exif={len(nef_exif)} canon_total={canon_jpg_total} nef_total={nef_total} -> {OUT}", file=sys.stderr)
