// @generated by tools/exiftool-tables/convinv_rust_codegen.py.
// Inactive helper; no public writer admission.
#![allow(dead_code, unused_imports)]
use crate::writers::generated_convinv::ConvInvRecipe;
pub(crate) const CONV_INV_RECIPE: Option<ConvInvRecipe> = Some(ConvInvRecipe {
    default_type: "PrintConv",
    error_separator: " for ",
});
