// @generated by tools/exiftool-tables/checkexif_rust_codegen.py.
// Inactive source-derived CheckExif composition; no writer route.
#![allow(dead_code, unused_imports)]
use crate::writers::generated_checkexif::{
    CheckExifRecipe, MissingFormat, Selector, SelectorSource, SourceTable,
};
use crate::writers::generated_scalar::{Comparison, ScalarCheckRecipe};
pub(crate) const CHECK_EXIF_RECIPES: &[CheckExifRecipe] = &[CheckExifRecipe {
    source_tables: &[
        SourceTable {
            module: "Apple",
            table: "Main",
            full_name: "Image::ExifTool::Apple::Main",
        },
        SourceTable {
            module: "Canon",
            table: "Main",
            full_name: "Image::ExifTool::Canon::Main",
        },
        SourceTable {
            module: "CanonCustom",
            table: "Functions2",
            full_name: "Image::ExifTool::CanonCustom::Functions2",
        },
        SourceTable {
            module: "Casio",
            table: "Main",
            full_name: "Image::ExifTool::Casio::Main",
        },
        SourceTable {
            module: "Casio",
            table: "Type2",
            full_name: "Image::ExifTool::Casio::Type2",
        },
        SourceTable {
            module: "DJI",
            table: "Main",
            full_name: "Image::ExifTool::DJI::Main",
        },
        SourceTable {
            module: "Exif",
            table: "Main",
            full_name: "Image::ExifTool::Exif::Main",
        },
        SourceTable {
            module: "FLIR",
            table: "Main",
            full_name: "Image::ExifTool::FLIR::Main",
        },
        SourceTable {
            module: "FujiFilm",
            table: "Main",
            full_name: "Image::ExifTool::FujiFilm::Main",
        },
        SourceTable {
            module: "GE",
            table: "Main",
            full_name: "Image::ExifTool::GE::Main",
        },
        SourceTable {
            module: "GPS",
            table: "Main",
            full_name: "Image::ExifTool::GPS::Main",
        },
        SourceTable {
            module: "JVC",
            table: "Main",
            full_name: "Image::ExifTool::JVC::Main",
        },
        SourceTable {
            module: "Kodak",
            table: "CameraInfo",
            full_name: "Image::ExifTool::Kodak::CameraInfo",
        },
        SourceTable {
            module: "Kodak",
            table: "IFD",
            full_name: "Image::ExifTool::Kodak::IFD",
        },
        SourceTable {
            module: "Kodak",
            table: "KDC_IFD",
            full_name: "Image::ExifTool::Kodak::KDC_IFD",
        },
        SourceTable {
            module: "Kodak",
            table: "Meta",
            full_name: "Image::ExifTool::Kodak::Meta",
        },
        SourceTable {
            module: "Kodak",
            table: "SubIFD0",
            full_name: "Image::ExifTool::Kodak::SubIFD0",
        },
        SourceTable {
            module: "Kodak",
            table: "SubIFD1",
            full_name: "Image::ExifTool::Kodak::SubIFD1",
        },
        SourceTable {
            module: "Kodak",
            table: "SubIFD2",
            full_name: "Image::ExifTool::Kodak::SubIFD2",
        },
        SourceTable {
            module: "Kodak",
            table: "SubIFD3",
            full_name: "Image::ExifTool::Kodak::SubIFD3",
        },
        SourceTable {
            module: "Kodak",
            table: "SubIFD4",
            full_name: "Image::ExifTool::Kodak::SubIFD4",
        },
        SourceTable {
            module: "Kodak",
            table: "SubIFD5",
            full_name: "Image::ExifTool::Kodak::SubIFD5",
        },
        SourceTable {
            module: "Kodak",
            table: "SubIFD6",
            full_name: "Image::ExifTool::Kodak::SubIFD6",
        },
        SourceTable {
            module: "Kodak",
            table: "Type10",
            full_name: "Image::ExifTool::Kodak::Type10",
        },
        SourceTable {
            module: "Kodak",
            table: "Type8",
            full_name: "Image::ExifTool::Kodak::Type8",
        },
        SourceTable {
            module: "Minolta",
            table: "Main",
            full_name: "Image::ExifTool::Minolta::Main",
        },
        SourceTable {
            module: "Motorola",
            table: "Main",
            full_name: "Image::ExifTool::Motorola::Main",
        },
        SourceTable {
            module: "Nikon",
            table: "Main",
            full_name: "Image::ExifTool::Nikon::Main",
        },
        SourceTable {
            module: "Nikon",
            table: "PreviewIFD",
            full_name: "Image::ExifTool::Nikon::PreviewIFD",
        },
        SourceTable {
            module: "Nikon",
            table: "Scan",
            full_name: "Image::ExifTool::Nikon::Scan",
        },
        SourceTable {
            module: "Nikon",
            table: "Type2",
            full_name: "Image::ExifTool::Nikon::Type2",
        },
        SourceTable {
            module: "NikonCapture",
            table: "Main",
            full_name: "Image::ExifTool::NikonCapture::Main",
        },
        SourceTable {
            module: "Nintendo",
            table: "Main",
            full_name: "Image::ExifTool::Nintendo::Main",
        },
        SourceTable {
            module: "Olympus",
            table: "CameraSettings",
            full_name: "Image::ExifTool::Olympus::CameraSettings",
        },
        SourceTable {
            module: "Olympus",
            table: "Equipment",
            full_name: "Image::ExifTool::Olympus::Equipment",
        },
        SourceTable {
            module: "Olympus",
            table: "FETags",
            full_name: "Image::ExifTool::Olympus::FETags",
        },
        SourceTable {
            module: "Olympus",
            table: "FocusInfo",
            full_name: "Image::ExifTool::Olympus::FocusInfo",
        },
        SourceTable {
            module: "Olympus",
            table: "ImageProcessing",
            full_name: "Image::ExifTool::Olympus::ImageProcessing",
        },
        SourceTable {
            module: "Olympus",
            table: "Main",
            full_name: "Image::ExifTool::Olympus::Main",
        },
        SourceTable {
            module: "Olympus",
            table: "RawDevSubIFD",
            full_name: "Image::ExifTool::Olympus::RawDevSubIFD",
        },
        SourceTable {
            module: "Olympus",
            table: "RawDevelopment",
            full_name: "Image::ExifTool::Olympus::RawDevelopment",
        },
        SourceTable {
            module: "Olympus",
            table: "RawDevelopment2",
            full_name: "Image::ExifTool::Olympus::RawDevelopment2",
        },
        SourceTable {
            module: "Olympus",
            table: "RawInfo",
            full_name: "Image::ExifTool::Olympus::RawInfo",
        },
        SourceTable {
            module: "Olympus",
            table: "UnknownInfo",
            full_name: "Image::ExifTool::Olympus::UnknownInfo",
        },
        SourceTable {
            module: "Panasonic",
            table: "Leica2",
            full_name: "Image::ExifTool::Panasonic::Leica2",
        },
        SourceTable {
            module: "Panasonic",
            table: "Leica3",
            full_name: "Image::ExifTool::Panasonic::Leica3",
        },
        SourceTable {
            module: "Panasonic",
            table: "Leica4",
            full_name: "Image::ExifTool::Panasonic::Leica4",
        },
        SourceTable {
            module: "Panasonic",
            table: "Leica5",
            full_name: "Image::ExifTool::Panasonic::Leica5",
        },
        SourceTable {
            module: "Panasonic",
            table: "Leica6",
            full_name: "Image::ExifTool::Panasonic::Leica6",
        },
        SourceTable {
            module: "Panasonic",
            table: "Leica9",
            full_name: "Image::ExifTool::Panasonic::Leica9",
        },
        SourceTable {
            module: "Panasonic",
            table: "Main",
            full_name: "Image::ExifTool::Panasonic::Main",
        },
        SourceTable {
            module: "Panasonic",
            table: "Subdir",
            full_name: "Image::ExifTool::Panasonic::Subdir",
        },
        SourceTable {
            module: "PanasonicRaw",
            table: "Main",
            full_name: "Image::ExifTool::PanasonicRaw::Main",
        },
        SourceTable {
            module: "Pentax",
            table: "Main",
            full_name: "Image::ExifTool::Pentax::Main",
        },
        SourceTable {
            module: "Pentax",
            table: "Type2",
            full_name: "Image::ExifTool::Pentax::Type2",
        },
        SourceTable {
            module: "PhaseOne",
            table: "Main",
            full_name: "Image::ExifTool::PhaseOne::Main",
        },
        SourceTable {
            module: "PhaseOne",
            table: "SensorCalibration",
            full_name: "Image::ExifTool::PhaseOne::SensorCalibration",
        },
        SourceTable {
            module: "Ricoh",
            table: "Main",
            full_name: "Image::ExifTool::Ricoh::Main",
        },
        SourceTable {
            module: "Ricoh",
            table: "Subdir",
            full_name: "Image::ExifTool::Ricoh::Subdir",
        },
        SourceTable {
            module: "Ricoh",
            table: "ThetaSubdir",
            full_name: "Image::ExifTool::Ricoh::ThetaSubdir",
        },
        SourceTable {
            module: "Samsung",
            table: "Type2",
            full_name: "Image::ExifTool::Samsung::Type2",
        },
        SourceTable {
            module: "Sanyo",
            table: "Main",
            full_name: "Image::ExifTool::Sanyo::Main",
        },
        SourceTable {
            module: "Sigma",
            table: "Main",
            full_name: "Image::ExifTool::Sigma::Main",
        },
        SourceTable {
            module: "Sony",
            table: "Ericsson",
            full_name: "Image::ExifTool::Sony::Ericsson",
        },
        SourceTable {
            module: "Sony",
            table: "Main",
            full_name: "Image::ExifTool::Sony::Main",
        },
        SourceTable {
            module: "Sony",
            table: "SR2DataIFD",
            full_name: "Image::ExifTool::Sony::SR2DataIFD",
        },
        SourceTable {
            module: "Sony",
            table: "SR2SubIFD",
            full_name: "Image::ExifTool::Sony::SR2SubIFD",
        },
        SourceTable {
            module: "SonyIDC",
            table: "Main",
            full_name: "Image::ExifTool::SonyIDC::Main",
        },
        SourceTable {
            module: "Unknown",
            table: "Main",
            full_name: "Image::ExifTool::Unknown::Main",
        },
    ],
    format_selectors: &[
        Selector {
            source: SelectorSource::Tag,
            property: "Format",
        },
        Selector {
            source: SelectorSource::Tag,
            property: "Writable",
        },
        Selector {
            source: SelectorSource::Table,
            property: "WRITABLE",
        },
    ],
    missing_format: MissingFormat {
        equals_literal: "1",
        group_source: Selector {
            source: SelectorSource::TagGroup,
            property: "0",
        },
        maker_notes_literal: "MakerNotes",
        other_error: "No writable format",
    },
    count_selector: Selector {
        source: SelectorSource::Tag,
        property: "Count",
    },
    check_value: ScalarCheckRecipe {
        formats: ["string", "undef"],
        positive_count_operator: Comparison::Gt,
        positive_count_bound: 0,
        first_format: "string",
        first_limit_operator: Comparison::Ge,
        first_error: "String too long",
        second_limit_operator: Comparison::Gt,
        second_error: "Data too long",
        padding_operator: Comparison::Lt,
        padding_character: 0,
    },
}];
