// @generated by fresh_jpeg_byte_order_codegen.py; selected native executable operands only.

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub(crate) enum FreshJpegExifByteOrder {
    LittleEndian,
    BigEndian,
}

pub(crate) struct FreshJpegByteOrderRecipe {
    pub selected: FreshJpegExifByteOrder,
    pub set_preferred_source_sha256: &'static str,
    pub set_preferred_body_sha256: &'static str,
    pub set_byte_order_source_sha256: &'static str,
    pub set_byte_order_body_sha256: &'static str,
    pub get_byte_order_source_sha256: &'static str,
    pub get_byte_order_body_sha256: &'static str,
    pub caller_source_sha256: &'static str,
    pub caller_body_sha256: &'static str,
    pub closure_sha256: &'static str,
    pub writer_capture_closure_sha256: &'static str,
    pub writer_read_capture_closure_sha256: &'static str,
    pub exiftool_version: &'static str,
    pub perl_version: &'static str,
}

pub(crate) struct FreshJpegByteOrderInputs<'a> {
    pub byte_order_option: Option<&'a str>,
    pub exif_byte_order: Option<&'a str>,
    pub maker_note_byte_order: Option<&'a str>,
}

pub(crate) const FRESH_JPEG_BYTE_ORDER: FreshJpegByteOrderRecipe = FreshJpegByteOrderRecipe {
    selected: FreshJpegExifByteOrder::BigEndian,
    set_preferred_source_sha256: "cfe916df77f7b37a4fc62e22f0c03de93ca727f0fa22a155ad0eecf95c050d44",
    set_preferred_body_sha256: "38f17b07e63cced6fe77dfea11a0ff9df13a581a1d7e0c0dc6f9a89f3a963306",
    set_byte_order_source_sha256: "95fa4ec3cc3603866dd6e37bfe52ad019ff50a23bbd5cc87ce40f949cf49a508",
    set_byte_order_body_sha256: "b09a10c46f0800e2a2d1bc8cde1269fa205300e62f0d5bf7358d6a57ac2c8d4d",
    get_byte_order_source_sha256: "95fa4ec3cc3603866dd6e37bfe52ad019ff50a23bbd5cc87ce40f949cf49a508",
    get_byte_order_body_sha256: "6045c2f82e71eee2140a96c2c0327da020dc694fec0383a454637735f57e7153",
    caller_source_sha256: "95fa4ec3cc3603866dd6e37bfe52ad019ff50a23bbd5cc87ce40f949cf49a508",
    caller_body_sha256: "c6766768697bfb125e34269852979e9c697b0ab64476c4e2359528cca28a3692",
    closure_sha256: "e16edd3a6040e869351d13ca1239eca9f171a87573191146645bd3fbb8be6620",
    writer_capture_closure_sha256: "89d8caff32ee063df5afd01336ad0d53d0a73d6da1dc08a0b470fe2bc35ae756",
    writer_read_capture_closure_sha256: "b43f05195e4a72e4e2043419c27f31f99861c949eb268de619c750ded901a32d",
    exiftool_version: "13.59",
    perl_version: "5.038002",
};

pub(crate) fn fresh_jpeg_byte_order(
    recipe: &FreshJpegByteOrderRecipe,
    inputs: FreshJpegByteOrderInputs<'_>,
) -> Result<FreshJpegExifByteOrder, &'static str> {
    if inputs.byte_order_option.is_some()
        || inputs.exif_byte_order.is_some()
        || inputs.maker_note_byte_order.is_some()
    {
        return Err("fresh JPEG byte-order override is outside the generated native branch");
    }
    Ok(recipe.selected)
}
