// @generated by raw_jfif_codegen.py from selected native executable/table facts.
use crate::writers::raw_segment_properties::{RawByteOrder, RawField, RawSegmentRecipe};
pub(crate) const RAW_JFIF: RawSegmentRecipe = RawSegmentRecipe {
    source_core_sha256: "95fa4ec3cc3603866dd6e37bfe52ad019ff50a23bbd5cc87ce40f949cf49a508",
    source_writer_sha256: "cfe916df77f7b37a4fc62e22f0c03de93ca727f0fa22a155ad0eecf95c050d44",
    marker: 224,
    signature: &[74, 70, 73, 70, 0],
    skip: 5,
    byte_order: RawByteOrder::Big,
    fields: &[
        RawField {
            property: "JFIFResolutionUnit",
            offset: 2,
            width: 1,
        },
        RawField {
            property: "JFIFXResolution",
            offset: 3,
            width: 2,
        },
        RawField {
            property: "JFIFYResolution",
            offset: 5,
            width: 2,
        },
    ],
};
