// @generated by tools/exiftool-tables/sanitize_rust_codegen.py.
// Inactive helper; capability validation occurs during generation.
#![allow(dead_code, unused_imports)]
use crate::writers::generated_sanitize::{EncodingPrimitive, SanitizeRecipe};
pub(crate) const SANITIZE_RECIPE: Option<SanitizeRecipe> = Some(SanitizeRecipe {
    perl_version: 5038002,
    downgrade_at_or_after: 5006000,
    manual_pack_before: 5010000,
    encode_hangs_guard: true,
    encoding: EncodingPrimitive::Utf8,
});
