// @generated by tools/exiftool-tables/scalar_helper_codegen.py.
// Source-derived helper operands; no public tag or writer admission.
#![allow(dead_code, unused_imports)]
use crate::writers::generated_scalar::{Comparison, ScalarCheckRecipe, ScalarWriteRecipe};

pub(crate) const CHECK_VALUE: Option<ScalarCheckRecipe> = Some(ScalarCheckRecipe {
    formats: ["string", "undef"],

    positive_count_operator: Comparison::Gt,

    positive_count_bound: 0,

    first_format: "string",

    first_limit_operator: Comparison::Ge,

    first_error: "String too long",

    second_limit_operator: Comparison::Gt,

    second_error: "Data too long",

    padding_operator: Comparison::Lt,

    padding_character: 0,
});

pub(crate) const CHECK_VALUE_PROVENANCE: &str = "{\"actual_name\": \"Image::ExifTool::CheckValue\", \"body_sha256\": \"30460d5f4bb56fce39ef411a19595eb2aa77ad99282a5bcbdc6b735242c24956\", \"dependencies\": [{\"binding\": \"Image::ExifTool::IsFloat\", \"fact\": {\"actual_name\": \"Image::ExifTool::IsFloat\", \"body_sha256\": \"0a55b27b2b165b3bc43fa97f4b4efbb3d3114734c1fd76b1765ddaec96532015\", \"dependencies\": [], \"requested_binding\": null, \"source_file\": \"Image/ExifTool.pm\", \"source_sha256\": \"95fa4ec3cc3603866dd6e37bfe52ad019ff50a23bbd5cc87ce40f949cf49a508\"}}, {\"binding\": \"Image::ExifTool::IsHex\", \"fact\": {\"actual_name\": \"Image::ExifTool::IsHex\", \"body_sha256\": \"79755a02b4648a6bd56cdbf318b7064b6f6f5f2b5e553648eaf2a9c528cca81e\", \"dependencies\": [], \"requested_binding\": null, \"source_file\": \"Image/ExifTool.pm\", \"source_sha256\": \"95fa4ec3cc3603866dd6e37bfe52ad019ff50a23bbd5cc87ce40f949cf49a508\"}}, {\"binding\": \"Image::ExifTool::IsInt\", \"fact\": {\"actual_name\": \"Image::ExifTool::IsInt\", \"body_sha256\": \"2fa127fbeffa5d459927879babad932c9040a30fc69775744d3ba570c3f7acec\", \"dependencies\": [], \"requested_binding\": null, \"source_file\": \"Image/ExifTool.pm\", \"source_sha256\": \"95fa4ec3cc3603866dd6e37bfe52ad019ff50a23bbd5cc87ce40f949cf49a508\"}}], \"requested_binding\": \"Image::ExifTool::CheckValue\", \"source_file\": \"Image/ExifTool/Writer.pl\", \"source_sha256\": \"cfe916df77f7b37a4fc62e22f0c03de93ca727f0fa22a155ad0eecf95c050d44\"}";

pub(crate) const WRITE_VALUE: Option<ScalarWriteRecipe> = Some(ScalarWriteRecipe {
    formats: ["string", "undef"],

    terminated_format: "string",

    count_positive_operator: Comparison::Gt,

    count_positive_bound: 0,

    diff_negative_operator: Comparison::Lt,

    terminator: 0,
});

pub(crate) const WRITE_VALUE_PROVENANCE: &str = "{\"actual_name\": \"Image::ExifTool::WriteValue\", \"body_sha256\": \"4b72f386df682e76ca7dd0262bd89bdfa10f9e964042777e6b5f7009f2de3c0a\", \"dependencies\": [{\"binding\": \"Image::ExifTool::IsFloat\", \"fact\": {\"actual_name\": \"Image::ExifTool::IsFloat\", \"body_sha256\": \"0a55b27b2b165b3bc43fa97f4b4efbb3d3114734c1fd76b1765ddaec96532015\", \"dependencies\": [], \"requested_binding\": null, \"source_file\": \"Image/ExifTool.pm\", \"source_sha256\": \"95fa4ec3cc3603866dd6e37bfe52ad019ff50a23bbd5cc87ce40f949cf49a508\"}}, {\"binding\": \"Image::ExifTool::IsHex\", \"fact\": {\"actual_name\": \"Image::ExifTool::IsHex\", \"body_sha256\": \"79755a02b4648a6bd56cdbf318b7064b6f6f5f2b5e553648eaf2a9c528cca81e\", \"dependencies\": [], \"requested_binding\": null, \"source_file\": \"Image/ExifTool.pm\", \"source_sha256\": \"95fa4ec3cc3603866dd6e37bfe52ad019ff50a23bbd5cc87ce40f949cf49a508\"}}, {\"binding\": \"Image::ExifTool::IsInt\", \"fact\": {\"actual_name\": \"Image::ExifTool::IsInt\", \"body_sha256\": \"2fa127fbeffa5d459927879babad932c9040a30fc69775744d3ba570c3f7acec\", \"dependencies\": [], \"requested_binding\": null, \"source_file\": \"Image/ExifTool.pm\", \"source_sha256\": \"95fa4ec3cc3603866dd6e37bfe52ad019ff50a23bbd5cc87ce40f949cf49a508\"}}, {\"binding\": \"Image::ExifTool::IsRational\", \"fact\": {\"actual_name\": \"Image::ExifTool::IsRational\", \"body_sha256\": \"ecfabc808b12990e7c72603f11c23cab462d4d52b29f88fe9a521d2ef4574356\", \"dependencies\": [], \"requested_binding\": null, \"source_file\": \"Image/ExifTool.pm\", \"source_sha256\": \"95fa4ec3cc3603866dd6e37bfe52ad019ff50a23bbd5cc87ce40f949cf49a508\"}}], \"requested_binding\": \"Image::ExifTool::WriteValue\", \"source_file\": \"Image/ExifTool/Writer.pl\", \"source_sha256\": \"cfe916df77f7b37a4fc62e22f0c03de93ca727f0fa22a155ad0eecf95c050d44\"}";
