// @generated by mandatory_defaults_codegen.py; source-captured in the tier-1 regeneration transaction.
use crate::writers::mandatory_defaults_runtime::{DefaultEncoding, JfifAssignment, MandatoryCleanup, MandatoryDefault, MandatoryDirectory, MandatoryRecipe, MandatoryValue, SurvivorEncoding};
const DIRECTORY_0: &[MandatoryDefault] = &[
MandatoryDefault { tag_id: 0x9000, value: MandatoryValue::Text("0232") },
MandatoryDefault { tag_id: 0x9101, value: MandatoryValue::Text("1 2 3 0") },
MandatoryDefault { tag_id: 0xa001, value: MandatoryValue::Integer(65535) },
];
const DIRECTORY_1: &[MandatoryDefault] = &[
MandatoryDefault { tag_id: 0x0000, value: MandatoryValue::Text("2 3 0 0") },
];
const DIRECTORY_2: &[MandatoryDefault] = &[
MandatoryDefault { tag_id: 0x0213, value: MandatoryValue::Integer(1) },
];
const DIRECTORY_3: &[MandatoryDefault] = &[
MandatoryDefault { tag_id: 0x0103, value: MandatoryValue::Integer(6) },
MandatoryDefault { tag_id: 0x011a, value: MandatoryValue::Integer(72) },
MandatoryDefault { tag_id: 0x011b, value: MandatoryValue::Integer(72) },
MandatoryDefault { tag_id: 0x0128, value: MandatoryValue::Integer(2) },
];
const DIRECTORY_4: &[MandatoryDefault] = &[
MandatoryDefault { tag_id: 0x0002, value: MandatoryValue::Text("0100") },
];
const DIRECTORIES: &[MandatoryDirectory] = &[
MandatoryDirectory { directory: "ExifIFD", defaults: DIRECTORY_0 },
MandatoryDirectory { directory: "GPS", defaults: DIRECTORY_1 },
MandatoryDirectory { directory: "IFD0", defaults: DIRECTORY_2 },
MandatoryDirectory { directory: "IFD1", defaults: DIRECTORY_3 },
MandatoryDirectory { directory: "InteropIFD", defaults: DIRECTORY_4 },
];
const JFIF_ASSIGNMENTS: &[JfifAssignment] = &[
JfifAssignment { tag_id: 0x011a, property: "JFIFXResolution", adjustment: 0 },
JfifAssignment { tag_id: 0x011b, property: "JFIFYResolution", adjustment: 0 },
JfifAssignment { tag_id: 0x0128, property: "JFIFResolutionUnit", adjustment: 1 },
];
const ENCODINGS: &[DefaultEncoding] = &[
DefaultEncoding { tag_id: 0x0103, format_name: "int16u", tiff_type: 3 },
DefaultEncoding { tag_id: 0x011a, format_name: "rational64u", tiff_type: 5 },
DefaultEncoding { tag_id: 0x011b, format_name: "rational64u", tiff_type: 5 },
DefaultEncoding { tag_id: 0x0128, format_name: "int16u", tiff_type: 3 },
DefaultEncoding { tag_id: 0x0213, format_name: "int16u", tiff_type: 3 },
];
const SURVIVOR_ENCODINGS: &[SurvivorEncoding] = &[
SurvivorEncoding { format_name: "int16u", tiff_type: 3, width: 2, operation: "write_value_scalar" },
SurvivorEncoding { format_name: "int32u", tiff_type: 4, width: 4, operation: "write_value_scalar" },
SurvivorEncoding { format_name: "rational64u", tiff_type: 5, width: 8, operation: "write_value_scalar" },
];
pub(crate) const MANDATORY_DEFAULTS: MandatoryRecipe = MandatoryRecipe { writer_source_file: "Image/ExifTool/WriteExif.pl", writer_source_sha256: "7ea2e8af8f17ebfef5979146bdc6b793392f39da9fc3ea15c6ba0326e1321533", core_source_sha256: "95fa4ec3cc3603866dd6e37bfe52ad019ff50a23bbd5cc87ce40f949cf49a508", exif_source_sha256: "8a0475c0ff67b2401db22df10c781f2f1e54276dd441affa1a8be3f42a5f7d22", write_value_source_sha256: "cfe916df77f7b37a4fc62e22f0c03de93ca727f0fa22a155ad0eecf95c050d44", perl_version: "v5.38.2", no_mandatory_guard: true, directories: DIRECTORIES, jfif_directory: "IFD0", jfif_probe: "JFIFYResolution", jfif_assignments: JFIF_ASSIGNMENTS, encodings: ENCODINGS, survivor_encodings: SURVIVOR_ENCODINGS, cleanup: MandatoryCleanup { all_mandatory: true, no_next_ifd: true, entry_count_shrinks_or_new: true, omit_empty_ifd1: true } };
