// @generated by png_shift_contract.py from selected ExifTool source.
// png SHA-256: 69a54cfc08cb67e210158c148ab439fbdd3f9a021e362b1379a1e080c2c7a0f5
// shortcuts SHA-256: ca795f420517162cd80b776795b50d5cf0317851530bda1cbca133a38ce8362d
// write_png SHA-256: 21f83b39cfd05422ba219e911a88506bb17c7c8d733aa14377fad461d7093a31
// writer SHA-256: cfe916df77f7b37a4fc62e22f0c03de93ca727f0fa22a155ad0eecf95c050d44
pub(crate) const PNG_ABSENT_CREATE_DATE_SHIFT_LITERAL: bool = false;
