// @generated by fresh_jpeg_byte_order_codegen.py; selected native executable operands only.

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub(crate) enum FreshJpegExifByteOrder {
    LittleEndian,
    BigEndian,
}

pub(crate) struct FreshJpegByteOrderRecipe {
    pub selected: FreshJpegExifByteOrder,
    pub set_preferred_source_sha256: &'static str,
    pub set_preferred_body_sha256: &'static str,
    pub caller_source_sha256: &'static str,
    pub caller_body_sha256: &'static str,
    pub closure_sha256: &'static str,
    pub writer_capture_closure_sha256: &'static str,
    pub writer_read_capture_closure_sha256: &'static str,
    pub exiftool_version: &'static str,
    pub perl_version: &'static str,
}

pub(crate) struct FreshJpegByteOrderInputs<'a> {
    pub byte_order_option: Option<&'a str>,
    pub exif_byte_order: Option<&'a str>,
    pub maker_note_byte_order: Option<&'a str>,
}

pub(crate) const FRESH_JPEG_BYTE_ORDER: FreshJpegByteOrderRecipe = FreshJpegByteOrderRecipe {
    selected: FreshJpegExifByteOrder::BigEndian,
    set_preferred_source_sha256: "cfe916df77f7b37a4fc62e22f0c03de93ca727f0fa22a155ad0eecf95c050d44",
    set_preferred_body_sha256: "38f17b07e63cced6fe77dfea11a0ff9df13a581a1d7e0c0dc6f9a89f3a963306",
    caller_source_sha256: "95fa4ec3cc3603866dd6e37bfe52ad019ff50a23bbd5cc87ce40f949cf49a508",
    caller_body_sha256: "c6766768697bfb125e34269852979e9c697b0ab64476c4e2359528cca28a3692",
    closure_sha256: "e16edd3a6040e869351d13ca1239eca9f171a87573191146645bd3fbb8be6620",
    writer_capture_closure_sha256:
        "31b7505048d163e716b258da6a680183927291cc40708b74a32619def62944fc",
    writer_read_capture_closure_sha256:
        "44e1835bb0f8ec909831cd79487298b43f71f65132ec8e16e41891e9e5f846ac",
    exiftool_version: "13.59",
    perl_version: "5.038002",
};

pub(crate) fn fresh_jpeg_byte_order(
    recipe: &FreshJpegByteOrderRecipe,
    inputs: FreshJpegByteOrderInputs<'_>,
) -> Result<FreshJpegExifByteOrder, &'static str> {
    if inputs.byte_order_option.is_some()
        || inputs.exif_byte_order.is_some()
        || inputs.maker_note_byte_order.is_some()
    {
        return Err("fresh JPEG byte-order override is outside the generated native branch");
    }
    Ok(recipe.selected)
}
