// GENERATED by tools/exiftool-tables/makernote_offset_pairs.py from pinned
// ExifTool 13.59: every `IsOffset` tag of every loaded table with the length
// tag it pairs with. Do not edit; re-run the generator (`write`), and
// `test_makernote_offset_pairs.py` checks it against the pinned tree.

/// `(offset tag, length tag)` names: an `IsOffset` tag and its `OffsetPair`
/// (or, in a ProcessBinaryData table without one, the same table's
/// `<stem>Length`/`ByteCount`/`ByteCounts`/`Size`).
pub(crate) const OFFSET_PAIRS: &[(&str, &str)] = &[
    // Image::ExifTool::Exif::Main
    ("AlphaOffset", "AlphaByteCount"),
    // Image::ExifTool::Exif::Main
    ("FreeOffsets", "FreeByteCounts"),
    // Image::ExifTool::Sony::HiddenInfo
    ("HiddenDataOffset", "HiddenDataLength"),
    // Image::ExifTool::SonyIDC::Main
    ("IDCPreviewStart", "IDCPreviewLength"),
    // Image::ExifTool::Exif::Main
    ("ImageOffset", "ImageByteCount"),
    // Image::ExifTool::Exif::Main
    ("JpgFromRawStart", "JpgFromRawLength"),
    // Image::ExifTool::Exif::Main
    ("JpgFromRawStart", "OtherImageLength"),
    // Image::ExifTool::Exif::Main
    ("JpgFromRawStart", "PreviewImageLength"),
    // Image::ExifTool::Exif::Main
    ("JpgFromRawStart", "PreviewJXLLength"),
    // Image::ExifTool::Exif::Main
    ("JpgFromRawStart", "StripByteCounts"),
    // Image::ExifTool::Exif::Main
    ("JpgFromRawStart", "ThumbnailLength"),
    // Image::ExifTool::MPF::MPImage
    ("MPImageStart", "MPImageLength"),
    // Image::ExifTool::Exif::Main
    ("OtherImageStart", "JpgFromRawLength"),
    // Image::ExifTool::Exif::Main
    ("OtherImageStart", "OtherImageLength"),
    // Image::ExifTool::Exif::Main
    ("OtherImageStart", "PreviewImageLength"),
    // Image::ExifTool::Exif::Main
    ("OtherImageStart", "PreviewJXLLength"),
    // Image::ExifTool::Exif::Main
    ("OtherImageStart", "StripByteCounts"),
    // Image::ExifTool::Exif::Main
    ("OtherImageStart", "ThumbnailLength"),
    // Image::ExifTool::Exif::Main
    ("PreviewImageStart", "JpgFromRawLength"),
    // Image::ExifTool::Exif::Main
    ("PreviewImageStart", "OtherImageLength"),
    // Image::ExifTool::Canon::PreviewImageInfo, Image::ExifTool::Casio::Type2, Image::ExifTool::Exif::Main, Image::ExifTool::Minolta::Main, Image::ExifTool::Nikon::PreviewIFD, Image::ExifTool::Olympus::CameraSettings, Image::ExifTool::Olympus::Main, Image::ExifTool::Pentax::Main, Image::ExifTool::Ricoh::ImageInfo, Image::ExifTool::Samsung::Main, Image::ExifTool::Sigma::Main, Image::ExifTool::Sony::Ericsson
    ("PreviewImageStart", "PreviewImageLength"),
    // Image::ExifTool::Exif::Main
    ("PreviewImageStart", "PreviewJXLLength"),
    // Image::ExifTool::Exif::Main
    ("PreviewImageStart", "StripByteCounts"),
    // Image::ExifTool::Exif::Main
    ("PreviewImageStart", "ThumbnailLength"),
    // Image::ExifTool::Exif::Main
    ("PreviewJXLStart", "JpgFromRawLength"),
    // Image::ExifTool::Exif::Main
    ("PreviewJXLStart", "OtherImageLength"),
    // Image::ExifTool::Exif::Main
    ("PreviewJXLStart", "PreviewImageLength"),
    // Image::ExifTool::Exif::Main
    ("PreviewJXLStart", "PreviewJXLLength"),
    // Image::ExifTool::Exif::Main
    ("PreviewJXLStart", "StripByteCounts"),
    // Image::ExifTool::PanasonicRaw::Main
    ("RawDataOffset", "StripByteCounts"),
    // Image::ExifTool::Exif::Main
    ("SamsungRawPointersOffset", "SamsungRawPointersLength"),
    // Image::ExifTool::Exif::Main
    ("StripOffsets", "JpgFromRawLength"),
    // Image::ExifTool::Exif::Main
    ("StripOffsets", "OtherImageLength"),
    // Image::ExifTool::Exif::Main
    ("StripOffsets", "PreviewImageLength"),
    // Image::ExifTool::Exif::Main
    ("StripOffsets", "PreviewJXLLength"),
    // Image::ExifTool::Exif::Main, Image::ExifTool::FujiFilm::IFD, Image::ExifTool::PanasonicRaw::Main
    ("StripOffsets", "StripByteCounts"),
    // Image::ExifTool::Exif::Main
    ("ThumbnailOffset", "JpgFromRawLength"),
    // Image::ExifTool::Exif::Main
    ("ThumbnailOffset", "OtherImageLength"),
    // Image::ExifTool::Exif::Main
    ("ThumbnailOffset", "PreviewImageLength"),
    // Image::ExifTool::Exif::Main, Image::ExifTool::Olympus::Thumbnail, Image::ExifTool::Samsung::Thumbnail, Image::ExifTool::Samsung::Thumbnail2, Image::ExifTool::Sanyo::Thumbnail
    ("ThumbnailOffset", "ThumbnailLength"),
    // Image::ExifTool::Exif::Main
    ("TileOffsets", "TileByteCounts"),
];

/// `IsOffset` tags with no length tag at all.
pub(crate) const UNPAIRED_OFFSETS: &[&str] = &[
    "A100DataOffset",
    "JPEGACTables",
    "JPEGDCTables",
    "JPEGQTables",
    "OriginalDecisionDataOffset",
    "SharedData",
];
