//! InfiRay IJPEG binary-data tables, GENERATED by
//! `scripts/gen_infiray_tables.pl` from ExifTool's in-memory
//! `%Image::ExifTool::InfiRay::*` hashes. Do not edit by hand.
//!
//! Source: ExifTool 13.59. Every `ExifTool.pm:` and
//! `InfiRay.pm:` line number below is a line of THAT release; they move
//! between releases.
//!
//! Every `name` below is proven to appear literally in ExifTool's
//! `InfiRay.pm`; the trailing comment on each row is the line it came from.
//! The generator aborts rather than guessing at an unknown `Format`, an
//! unknown `PrintConv` expression, a `PrintConv` hash or code ref, or an
//! unrecognised APPn dispatch gate.
//!
//! The output is already rustfmt-stable: regenerating and running
//! `cargo fmt` leaves the file byte-identical.
//!
//! The tables declare no `FORMAT`, so ExifTool's `ProcessBinaryData` default
//! of `int8u` applies and the numeric keys are plain byte offsets.

/// One field of an InfiRay binary-data record.
#[derive(Debug, Clone, Copy)]
pub(crate) struct Field {
    /// Byte offset of the field within the record.
    pub offset: usize,
    /// ExifTool tag name.
    pub name: &'static str,
    /// ExifTool `Format`, absent meaning the table's `int8u` default.
    pub format: Fmt,
    /// Element count from `Format`'s `[n]` suffix, else 1.
    pub count: usize,
    /// ExifTool `PrintConv`, or [`Conv::Raw`] when the table declares none.
    pub conv: Conv,
}

/// The ExifTool formats these tables use.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum Fmt {
    Int8u,
    Int8s,
    Int16u,
    Int16s,
    Int32u,
    Int32s,
    Int64u,
    Float,
    Str,
}

/// The `PrintConv` expressions these tables use (`InfiRay.pm:21-24`).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum Conv {
    /// No `PrintConv`: ExifTool prints the raw value.
    Raw,
    /// `sprintf("%.2f", $val)`
    Float2,
    /// `sprintf("%.1f %%", $val * 100)`
    Percent,
    /// `sprintf("%.2f m", $val)`
    Meters,
    /// `sprintf("%.2f C", $val)`
    Celsius,
}

/// The APP2 Version header carries its own signature and no length
/// gate (`ExifTool.pm:7991`: `$$segDataPt =~ /^....IJPEG\0/s`),
/// so the ten signature bytes are the only minimum.
pub(crate) const VERSION_MIN_LENGTH: usize = 10;

/// `%Image::ExifTool::InfiRay::Version` -- JPEG APP2, 22 fields.
#[rustfmt::skip]
pub(crate) static VERSION: &[Field] = &[
    Field { offset: 0x000, name: "IJPEGVersion", format: Fmt::Int8u, count: 4, conv: Conv::Raw }, // InfiRay.pm:35
    Field { offset: 0x00c, name: "IJPEGOrgType", format: Fmt::Int8u, count: 1, conv: Conv::Raw }, // InfiRay.pm:37
    Field { offset: 0x00d, name: "IJPEGDispType", format: Fmt::Int8u, count: 1, conv: Conv::Raw }, // InfiRay.pm:38
    Field { offset: 0x00e, name: "IJPEGRotate", format: Fmt::Int8u, count: 1, conv: Conv::Raw }, // InfiRay.pm:39
    Field { offset: 0x00f, name: "IJPEGMirrorFlip", format: Fmt::Int8u, count: 1, conv: Conv::Raw }, // InfiRay.pm:40
    Field { offset: 0x010, name: "ImageColorSwitchable", format: Fmt::Int8u, count: 1, conv: Conv::Raw }, // InfiRay.pm:41
    Field { offset: 0x011, name: "ThermalColorPalette", format: Fmt::Int16u, count: 1, conv: Conv::Raw }, // InfiRay.pm:42
    Field { offset: 0x020, name: "IRDataSize", format: Fmt::Int64u, count: 1, conv: Conv::Raw }, // InfiRay.pm:43
    Field { offset: 0x028, name: "IRDataFormat", format: Fmt::Int16u, count: 1, conv: Conv::Raw }, // InfiRay.pm:44
    Field { offset: 0x02a, name: "IRImageWidth", format: Fmt::Int16u, count: 1, conv: Conv::Raw }, // InfiRay.pm:45
    Field { offset: 0x02c, name: "IRImageHeight", format: Fmt::Int16u, count: 1, conv: Conv::Raw }, // InfiRay.pm:46
    Field { offset: 0x02e, name: "IRImageBpp", format: Fmt::Int8u, count: 1, conv: Conv::Raw }, // InfiRay.pm:47
    Field { offset: 0x030, name: "TempDataSize", format: Fmt::Int64u, count: 1, conv: Conv::Raw }, // InfiRay.pm:48
    Field { offset: 0x038, name: "TempDataFormat", format: Fmt::Int16u, count: 1, conv: Conv::Raw }, // InfiRay.pm:49
    Field { offset: 0x03a, name: "TempImageWidth", format: Fmt::Int16u, count: 1, conv: Conv::Raw }, // InfiRay.pm:50
    Field { offset: 0x03c, name: "TempImageHeight", format: Fmt::Int16u, count: 1, conv: Conv::Raw }, // InfiRay.pm:51
    Field { offset: 0x03e, name: "TempImageBpp", format: Fmt::Int8u, count: 1, conv: Conv::Raw }, // InfiRay.pm:52
    Field { offset: 0x040, name: "VisibleDataSize", format: Fmt::Int64u, count: 1, conv: Conv::Raw }, // InfiRay.pm:53
    Field { offset: 0x048, name: "VisibleDataFormat", format: Fmt::Int16u, count: 1, conv: Conv::Raw }, // InfiRay.pm:54
    Field { offset: 0x04a, name: "VisibleImageWidth", format: Fmt::Int16u, count: 1, conv: Conv::Raw }, // InfiRay.pm:55
    Field { offset: 0x04c, name: "VisibleImageHeight", format: Fmt::Int16u, count: 1, conv: Conv::Raw }, // InfiRay.pm:56
    Field { offset: 0x04e, name: "VisibleImageBpp", format: Fmt::Int8u, count: 1, conv: Conv::Raw }, // InfiRay.pm:57
];

/// Minimum APP4 payload before ExifTool reads an InfiRay Factory
/// record (`ExifTool.pm:8111`: `$$self{HasIJPEG} and $length >= 120`).
pub(crate) const FACTORY_MIN_LENGTH: usize = 120;

/// `%Image::ExifTool::InfiRay::Factory` -- JPEG APP4, 20 fields.
#[rustfmt::skip]
pub(crate) static FACTORY: &[Field] = &[
    Field { offset: 0x000, name: "IJPEGTempVersion", format: Fmt::Int8u, count: 4, conv: Conv::Raw }, // InfiRay.pm:69
    Field { offset: 0x004, name: "FactDefEmissivity", format: Fmt::Int8s, count: 1, conv: Conv::Raw }, // InfiRay.pm:70
    Field { offset: 0x005, name: "FactDefTau", format: Fmt::Int8s, count: 1, conv: Conv::Raw }, // InfiRay.pm:71
    Field { offset: 0x006, name: "FactDefTa", format: Fmt::Int16s, count: 1, conv: Conv::Raw }, // InfiRay.pm:72
    Field { offset: 0x008, name: "FactDefTu", format: Fmt::Int16s, count: 1, conv: Conv::Raw }, // InfiRay.pm:73
    Field { offset: 0x00a, name: "FactDefDist", format: Fmt::Int16s, count: 1, conv: Conv::Raw }, // InfiRay.pm:74
    Field { offset: 0x00c, name: "FactDefA0", format: Fmt::Int32s, count: 1, conv: Conv::Raw }, // InfiRay.pm:75
    Field { offset: 0x010, name: "FactDefB0", format: Fmt::Int32s, count: 1, conv: Conv::Raw }, // InfiRay.pm:76
    Field { offset: 0x014, name: "FactDefA1", format: Fmt::Int32s, count: 1, conv: Conv::Raw }, // InfiRay.pm:77
    Field { offset: 0x018, name: "FactDefB1", format: Fmt::Int32s, count: 1, conv: Conv::Raw }, // InfiRay.pm:78
    Field { offset: 0x01c, name: "FactDefP0", format: Fmt::Int32s, count: 1, conv: Conv::Raw }, // InfiRay.pm:79
    Field { offset: 0x020, name: "FactDefP1", format: Fmt::Int32s, count: 1, conv: Conv::Raw }, // InfiRay.pm:80
    Field { offset: 0x024, name: "FactDefP2", format: Fmt::Int32s, count: 1, conv: Conv::Raw }, // InfiRay.pm:81
    Field { offset: 0x044, name: "FactRelSensorTemp", format: Fmt::Int16s, count: 1, conv: Conv::Raw }, // InfiRay.pm:82
    Field { offset: 0x046, name: "FactRelShutterTemp", format: Fmt::Int16s, count: 1, conv: Conv::Raw }, // InfiRay.pm:83
    Field { offset: 0x048, name: "FactRelLensTemp", format: Fmt::Int16s, count: 1, conv: Conv::Raw }, // InfiRay.pm:84
    Field { offset: 0x064, name: "FactStatusGain", format: Fmt::Int8s, count: 1, conv: Conv::Raw }, // InfiRay.pm:85
    Field { offset: 0x065, name: "FactStatusEnvOK", format: Fmt::Int8s, count: 1, conv: Conv::Raw }, // InfiRay.pm:86
    Field { offset: 0x066, name: "FactStatusDistOK", format: Fmt::Int8s, count: 1, conv: Conv::Raw }, // InfiRay.pm:87
    Field { offset: 0x067, name: "FactStatusTempMap", format: Fmt::Int8s, count: 1, conv: Conv::Raw }, // InfiRay.pm:88
];

/// Minimum APP5 payload before ExifTool reads an InfiRay Picture
/// record (`ExifTool.pm:8142`: `$$self{HasIJPEG} and $length >= 38`).
pub(crate) const PICTURE_MIN_LENGTH: usize = 38;

/// `%Image::ExifTool::InfiRay::Picture` -- JPEG APP5, 10 fields.
#[rustfmt::skip]
pub(crate) static PICTURE: &[Field] = &[
    Field { offset: 0x000, name: "EnvironmentTemp", format: Fmt::Float, count: 1, conv: Conv::Celsius }, // InfiRay.pm:101
    Field { offset: 0x004, name: "Distance", format: Fmt::Float, count: 1, conv: Conv::Meters }, // InfiRay.pm:102
    Field { offset: 0x008, name: "Emissivity", format: Fmt::Float, count: 1, conv: Conv::Float2 }, // InfiRay.pm:103
    Field { offset: 0x00c, name: "Humidity", format: Fmt::Float, count: 1, conv: Conv::Percent }, // InfiRay.pm:104
    Field { offset: 0x010, name: "ReferenceTemp", format: Fmt::Float, count: 1, conv: Conv::Celsius }, // InfiRay.pm:105
    Field { offset: 0x020, name: "TempUnit", format: Fmt::Int8u, count: 1, conv: Conv::Raw }, // InfiRay.pm:106
    Field { offset: 0x021, name: "ShowCenterTemp", format: Fmt::Int8u, count: 1, conv: Conv::Raw }, // InfiRay.pm:107
    Field { offset: 0x022, name: "ShowMaxTemp", format: Fmt::Int8u, count: 1, conv: Conv::Raw }, // InfiRay.pm:108
    Field { offset: 0x023, name: "ShowMinTemp", format: Fmt::Int8u, count: 1, conv: Conv::Raw }, // InfiRay.pm:109
    Field { offset: 0x024, name: "TempMeasureCount", format: Fmt::Int16u, count: 1, conv: Conv::Raw }, // InfiRay.pm:110
];

/// Minimum APP6 payload before ExifTool reads an InfiRay MixMode
/// record (`ExifTool.pm:8186`: `$$self{HasIJPEG} and $length >= 129`).
pub(crate) const MIX_MODE_MIN_LENGTH: usize = 129;

/// `%Image::ExifTool::InfiRay::MixMode` -- JPEG APP6, 4 fields.
#[rustfmt::skip]
pub(crate) static MIX_MODE: &[Field] = &[
    Field { offset: 0x000, name: "MixMode", format: Fmt::Int8u, count: 1, conv: Conv::Raw }, // InfiRay.pm:123
    Field { offset: 0x001, name: "FusionIntensity", format: Fmt::Float, count: 1, conv: Conv::Percent }, // InfiRay.pm:124
    Field { offset: 0x005, name: "OffsetAdjustment", format: Fmt::Float, count: 1, conv: Conv::Raw }, // InfiRay.pm:125
    Field { offset: 0x009, name: "CorrectionAsix", format: Fmt::Float, count: 30, conv: Conv::Raw }, // InfiRay.pm:126
];

/// Minimum APP7 payload before ExifTool reads an InfiRay OpMode
/// record (`ExifTool.pm:8238`: `$$self{HasIJPEG} and $length >= 32`).
pub(crate) const OP_MODE_MIN_LENGTH: usize = 32;

/// `%Image::ExifTool::InfiRay::OpMode` -- JPEG APP7, 6 fields.
#[rustfmt::skip]
pub(crate) static OP_MODE: &[Field] = &[
    Field { offset: 0x000, name: "WorkingMode", format: Fmt::Int8u, count: 1, conv: Conv::Raw }, // InfiRay.pm:140
    Field { offset: 0x001, name: "IntegralTime", format: Fmt::Int32u, count: 1, conv: Conv::Raw }, // InfiRay.pm:141
    Field { offset: 0x005, name: "IntegratTimeHdr", format: Fmt::Int32u, count: 1, conv: Conv::Raw }, // InfiRay.pm:142
    Field { offset: 0x009, name: "GainStable", format: Fmt::Int8u, count: 1, conv: Conv::Raw }, // InfiRay.pm:143
    Field { offset: 0x00a, name: "TempControlEnable", format: Fmt::Int8u, count: 1, conv: Conv::Raw }, // InfiRay.pm:144
    Field { offset: 0x00b, name: "DeviceTemp", format: Fmt::Float, count: 1, conv: Conv::Celsius }, // InfiRay.pm:145
];

/// Minimum APP8 payload before ExifTool reads an InfiRay Isothermal
/// record (`ExifTool.pm:8251`: `$$self{HasIJPEG} and $length >= 32`).
pub(crate) const ISOTHERMAL_MIN_LENGTH: usize = 32;

/// `%Image::ExifTool::InfiRay::Isothermal` -- JPEG APP8, 4 fields.
#[rustfmt::skip]
pub(crate) static ISOTHERMAL: &[Field] = &[
    Field { offset: 0x000, name: "IsothermalMax", format: Fmt::Float, count: 1, conv: Conv::Raw }, // InfiRay.pm:160
    Field { offset: 0x004, name: "IsothermalMin", format: Fmt::Float, count: 1, conv: Conv::Raw }, // InfiRay.pm:161
    Field { offset: 0x008, name: "ChromaBarMax", format: Fmt::Float, count: 1, conv: Conv::Raw }, // InfiRay.pm:162
    Field { offset: 0x00c, name: "ChromaBarMin", format: Fmt::Float, count: 1, conv: Conv::Raw }, // InfiRay.pm:163
];

/// Minimum APP9 payload before ExifTool reads an InfiRay Sensor
/// record (`ExifTool.pm:8270`: `$$self{HasIJPEG} and $length >= 768`).
pub(crate) const SENSOR_MIN_LENGTH: usize = 768;

/// `%Image::ExifTool::InfiRay::Sensor` -- JPEG APP9, 14 fields.
#[rustfmt::skip]
pub(crate) static SENSOR: &[Field] = &[
    Field { offset: 0x000, name: "IRSensorManufacturer", format: Fmt::Str, count: 12, conv: Conv::Raw }, // InfiRay.pm:175
    Field { offset: 0x040, name: "IRSensorName", format: Fmt::Str, count: 12, conv: Conv::Raw }, // InfiRay.pm:176
    Field { offset: 0x080, name: "IRSensorPartNumber", format: Fmt::Str, count: 32, conv: Conv::Raw }, // InfiRay.pm:177
    Field { offset: 0x0c0, name: "IRSensorSerialNumber", format: Fmt::Str, count: 32, conv: Conv::Raw }, // InfiRay.pm:178
    Field { offset: 0x100, name: "IRSensorFirmware", format: Fmt::Str, count: 12, conv: Conv::Raw }, // InfiRay.pm:179
    Field { offset: 0x140, name: "IRSensorAperture", format: Fmt::Float, count: 1, conv: Conv::Float2 }, // InfiRay.pm:180
    Field { offset: 0x144, name: "IRFocalLength", format: Fmt::Float, count: 1, conv: Conv::Float2 }, // InfiRay.pm:181
    Field { offset: 0x180, name: "VisibleSensorManufacturer", format: Fmt::Str, count: 12, conv: Conv::Raw }, // InfiRay.pm:182
    Field { offset: 0x1c0, name: "VisibleSensorName", format: Fmt::Str, count: 12, conv: Conv::Raw }, // InfiRay.pm:183
    Field { offset: 0x200, name: "VisibleSensorPartNumber", format: Fmt::Str, count: 32, conv: Conv::Raw }, // InfiRay.pm:184
    Field { offset: 0x240, name: "VisibleSensorSerialNumber", format: Fmt::Str, count: 32, conv: Conv::Raw }, // InfiRay.pm:185
    Field { offset: 0x280, name: "VisibleSensorFirmware", format: Fmt::Str, count: 12, conv: Conv::Raw }, // InfiRay.pm:186
    Field { offset: 0x2c0, name: "VisibleSensorAperture", format: Fmt::Float, count: 1, conv: Conv::Raw }, // InfiRay.pm:187
    Field { offset: 0x2c4, name: "VisibleFocalLength", format: Fmt::Float, count: 1, conv: Conv::Raw }, // InfiRay.pm:188
];

/// Total fields across every generated table.
#[cfg(test)]
pub(crate) const GENERATED_FIELD_COUNT: usize = 80;
