// @generated by tools/exiftool-tables/quicktime_userdata_specs.py; DO NOT EDIT.
use super::generated_itemlist_specs::{EnumOperand, ItemListSpec, SourceFormat};
#[derive(Clone, Copy, Debug)]
#[rustfmt::skip]
pub(crate) struct UserDataSpec { pub data: ItemListSpec, pub priority: u8 }
pub(crate) const AUTO_DECODE_MAX_BYTES: usize = 65536;
pub(crate) const COPYRIGHT_PREFIX: u8 = 169;
#[rustfmt::skip]
pub(crate) static USERDATA_SPECS: &[UserDataSpec] = &[
    UserDataSpec { data: ItemListSpec { raw_fourcc: [0x41, 0x6c, 0x6c, 0x46], name: "PlayAllFrames", group: "UserData", group0: "QuickTime", source_format: SourceFormat::Unsigned(8), safe_enum_operands: &[] }, priority: 1 },
    UserDataSpec { data: ItemListSpec { raw_fourcc: [0x43, 0x4e, 0x43, 0x56], name: "CompressorVersion", group: "UserData", group0: "QuickTime", source_format: SourceFormat::String, safe_enum_operands: &[] }, priority: 1 },
    UserDataSpec { data: ItemListSpec { raw_fourcc: [0x43, 0x4e, 0x46, 0x56], name: "FirmwareVersion", group: "UserData", group0: "QuickTime", source_format: SourceFormat::String, safe_enum_operands: &[] }, priority: 1 },
    UserDataSpec { data: ItemListSpec { raw_fourcc: [0x43, 0x4e, 0x4d, 0x4e], name: "Model", group: "UserData", group0: "QuickTime", source_format: SourceFormat::String, safe_enum_operands: &[] }, priority: 0 },
    UserDataSpec { data: ItemListSpec { raw_fourcc: [0x4c, 0x4f, 0x4f, 0x50], name: "LoopStyle", group: "UserData", group0: "QuickTime", source_format: SourceFormat::Unsigned(32), safe_enum_operands: &[EnumOperand { raw: "1", rendered: "Normal" }, EnumOperand { raw: "2", rendered: "Palindromic" }] }, priority: 1 },
    UserDataSpec { data: ItemListSpec { raw_fourcc: [0x53, 0x65, 0x6c, 0x4f], name: "PlaySelection", group: "UserData", group0: "QuickTime", source_format: SourceFormat::Unsigned(8), safe_enum_operands: &[] }, priority: 1 },
    UserDataSpec { data: ItemListSpec { raw_fourcc: [0x57, 0x4c, 0x4f, 0x43], name: "WindowLocation", group: "UserData", group0: "QuickTime", source_format: SourceFormat::Unsigned(16), safe_enum_operands: &[] }, priority: 1 },
    UserDataSpec { data: ItemListSpec { raw_fourcc: [0x61, 0x6e, 0x67, 0x6c], name: "CameraAngle", group: "UserData", group0: "QuickTime", source_format: SourceFormat::String, safe_enum_operands: &[] }, priority: 1 },
    UserDataSpec { data: ItemListSpec { raw_fourcc: [0x63, 0x6c, 0x66, 0x6e], name: "ClipFileName", group: "UserData", group0: "QuickTime", source_format: SourceFormat::String, safe_enum_operands: &[] }, priority: 1 },
    UserDataSpec { data: ItemListSpec { raw_fourcc: [0x63, 0x6c, 0x69, 0x64], name: "ClipID", group: "UserData", group0: "QuickTime", source_format: SourceFormat::String, safe_enum_operands: &[] }, priority: 1 },
    UserDataSpec { data: ItemListSpec { raw_fourcc: [0x63, 0x6d, 0x69, 0x64], name: "CameraID", group: "UserData", group0: "QuickTime", source_format: SourceFormat::String, safe_enum_operands: &[] }, priority: 1 },
    UserDataSpec { data: ItemListSpec { raw_fourcc: [0x63, 0x6d, 0x6e, 0x6d], name: "Model", group: "UserData", group0: "QuickTime", source_format: SourceFormat::String, safe_enum_operands: &[] }, priority: 0 },
    UserDataSpec { data: ItemListSpec { raw_fourcc: [0x72, 0x65, 0x65, 0x6c], name: "ReelName", group: "UserData", group0: "QuickTime", source_format: SourceFormat::String, safe_enum_operands: &[] }, priority: 1 },
    UserDataSpec { data: ItemListSpec { raw_fourcc: [0x73, 0x63, 0x65, 0x6e], name: "Scene", group: "UserData", group0: "QuickTime", source_format: SourceFormat::String, safe_enum_operands: &[] }, priority: 1 },
    UserDataSpec { data: ItemListSpec { raw_fourcc: [0x73, 0x68, 0x6f, 0x74], name: "ShotName", group: "UserData", group0: "QuickTime", source_format: SourceFormat::String, safe_enum_operands: &[] }, priority: 1 },
    UserDataSpec { data: ItemListSpec { raw_fourcc: [0x73, 0x6c, 0x6e, 0x6f], name: "SerialNumber", group: "UserData", group0: "QuickTime", source_format: SourceFormat::String, safe_enum_operands: &[] }, priority: 1 },
    UserDataSpec { data: ItemListSpec { raw_fourcc: [0xa9, 0x6d, 0x64, 0x6c], name: "Model", group: "UserData", group0: "QuickTime", source_format: SourceFormat::String, safe_enum_operands: &[] }, priority: 0 },
];
#[rustfmt::skip]
pub(crate) static SINGLE_BYTE_MAP: &[u32; 256] = &[
    0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15,
    16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
    32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
    48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
    64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79,
    80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95,
    96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111,
    112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127,
    196, 197, 199, 201, 209, 214, 220, 225, 224, 226, 228, 227, 229, 231, 233, 232,
    234, 235, 237, 236, 238, 239, 241, 243, 242, 244, 246, 245, 250, 249, 251, 252,
    8224, 176, 162, 163, 167, 8226, 182, 223, 174, 169, 8482, 180, 168, 8800, 198, 216,
    8734, 177, 8804, 8805, 165, 181, 8706, 8721, 8719, 960, 8747, 170, 186, 937, 230, 248,
    191, 161, 172, 8730, 402, 8776, 8710, 171, 187, 8230, 160, 192, 195, 213, 338, 339,
    8211, 8212, 8220, 8221, 8216, 8217, 247, 9674, 255, 376, 8260, 8364, 8249, 8250, 64257, 64258,
    8225, 183, 8218, 8222, 8240, 194, 202, 193, 203, 200, 205, 206, 207, 204, 211, 212,
    63743, 210, 218, 219, 217, 305, 710, 732, 175, 728, 729, 730, 184, 733, 731, 711,
];
