// @generated by tools/exiftool-tables/quicktime_protocol_caps.py; DO NOT EDIT.
pub(crate) const IMPLICIT_INT64: bool = true;
pub(crate) const SHORTEN_EXPLICIT_WIDTH: bool = true;
pub(crate) const MDTA_STRIP_GENERIC_COM: bool = true;
pub(crate) const MDTA_RETRY_FULL_KEY: bool = true;
pub(crate) const MDAT_SIZE_TAG: &str = "QuickTime:MediaDataSize";
pub(crate) const MDAT_OFFSET_TAG: &str = "QuickTime:MediaDataOffset";
