//! File-type identification tables, generated from ExifTool's own hashes.
//!
//! DO NOT EDIT. Regenerate with `just regen-tables`.
//!
//! `MAGIC` is in ExifTool's test order and must stay that way: ExifTool takes
//! the first pattern that matches, and several patterns overlap.

/// (file type, byte regex anchored at the start of the file).
pub static MAGIC: &[(&str, &str)] = &[
    ("JPEG", "(?s-u)^\\xff\\xd8\\xff"),
    ("EXV", "(?s-u)^\\xff\\x01Exiv2"),
    ("CRW", "(?s-u)^(II|MM).{4}HEAP(CCDR|JPGM)"),
    ("DR4", "(?s-u)^IIII[\\x04|\\x05]\\x00\\x04\\x00"),
    ("TIFF", "(?s-u)^(II|MM)"),
    ("GIF", "(?s-u)^GIF8[79]a"),
    ("MRW", "(?s-u)^\\x00MR[MI]"),
    ("RAF", "(?s-u)^FUJIFILM"),
    ("X3F", "(?s-u)^FOVb"),
    (
        "JP2",
        "(?s-u)^(\\x00\\x00\\x00\\x0cjP(  |\\x1a\\x1a)\\x0d\\x0a\\x87\\x0a|\\xff\\x4f\\xff\\x51\\x00)",
    ),
    ("PNG", "(?s-u)^(\\x89P|\\x8aM|\\x8bJ)NG\\r\\n\\x1a\\n"),
    ("MIE", "(?s-u)^~[\\x10\\x18]\\x04.0MIE"),
    ("MIFF", "(?s-u)^id=ImageMagick"),
    ("PS", "(?s-u)^(%!PS|%!Ad|\\xc5\\xd0\\xd3\\xc6)"),
    ("PDF", "(?s-u)^\\s*%PDF-\\d+\\.\\d+"),
    ("PSD", "(?s-u)^8BPS\\x00[\\x01\\x02]"),
    (
        "XMP",
        "(?s-u)^\\x00{0,3}(\\xfe\\xff|\\xff\\xfe|\\xef\\xbb\\xbf)?\\x00{0,3}\\s*<",
    ),
    ("BMP", "(?s-u)^BM"),
    ("WPG", "(?s-u)^\\xff\\x57\\x50\\x43"),
    ("BPG", "(?s-u)^BPG\\xfb"),
    ("PPM", "(?s-u)^P[1-6]\\s+"),
    ("RIFF", "(?s-u)^(RIFF|LA0[234]|OFR |LPAC|wvpk|RF64)"),
    ("AIFF", "(?s-u)^(FORM....AIF[FC]|AT&TFORM)"),
    (
        "ASF",
        "(?s-u)^\\x30\\x26\\xb2\\x75\\x8e\\x66\\xcf\\x11\\xa6\\xd9\\x00\\xaa\\x00\\x62\\xce\\x6c",
    ),
    (
        "MOV",
        "(?s-u)^.{4}(free|skip|wide|ftyp|pnot|PICT|pict|moov|mdat|junk|uuid)",
    ),
    ("MPEG", "(?s-u)^\\x00\\x00\\x01[\\xb0-\\xbf]"),
    ("Real", "(?s-u)^(\\.RMF|\\.ra\\xfd|pnm://|rtsp://|http://)"),
    ("SWF", "(?s-u)^[FC]WS[^\\x00]"),
    ("PSP", "(?s-u)^Paint Shop Pro Image File\\x0a\\x1a\\x00{5}"),
    ("FLV", "(?s-u)^FLV\\x01"),
    ("OGG", "(?s-u)^(OggS|ID3)"),
    ("FLAC", "(?s-u)^(fLaC|ID3)"),
    ("APE", "(?s-u)^(MAC |APETAGEX|ID3)"),
    ("MPC", "(?s-u)^(MP\\+|ID3)"),
    ("MKV", "(?s-u)^\\x1a\\x45\\xdf\\xa3"),
    (
        "MXF",
        "(?s-u)^\\x06\\x0e\\x2b\\x34\\x02\\x05\\x01\\x01\\x0d\\x01\\x02",
    ),
    ("DV", "(?s-u)^\\x1f\\x07\\x00[\\x3f\\xbf]"),
    ("PMP", "(?s-u)^.{8}\\x00{3}\\x7c.{112}\\xff\\xd8\\xff\\xdb"),
    (
        "IND",
        "(?s-u)^\\x06\\x06\\xed\\xf5\\xd8\\x1d\\x46\\xe5\\xbd\\x31\\xef\\xe7\\xfe\\x74\\xb7\\x1d",
    ),
    ("PGF", "(?s-u)^PGF"),
    (
        "ICC",
        "(?s-u)^.{12}(scnr|mntr|prtr|link|spac|abst|nmcl|nkpf|cenc|mid |mlnk|mvis)(XYZ |Lab |Luv |YCbr|Yxy |RGB |GRAY|HSV |HLS |CMYK|CMY |[2-9A-F]CLR|nc..|\\x00{4}){2}",
    ),
    ("ITC", "(?s-u)^.{4}itch"),
    ("FLIR", "(?s-u)^[AF]FF\\x00"),
    ("FLIF", "(?s-u)^FLIF[0-\\x6f][0-2]"),
    ("FPF", "(?s-u)^FPF Public Image Format\\x00"),
    ("LFP", "(?s-u)^\\x89LFP\\x0d\\x0a\\x1a\\x0a"),
    (
        "HTML",
        "(?s-u)^(\\xef\\xbb\\xbf)?\\s*(?i)<(!DOCTYPE\\s+HTML|HTML|\\?xml)",
    ),
    ("VRD", "(?s-u)^CANON OPTIONAL DATA\\x00"),
    ("RTF", "(?s-u)^[\\n\\r]*\\{[\\n\\r]*\\\\rtf"),
    ("FITS", "(?s-u)^SIMPLE  = {20}T"),
    ("XISF", "(?s-u)^XISF0100"),
    ("XCF", "(?s-u)^gimp xcf "),
    ("DSS", "(?s-u)^(\\x02dss|\\x03ds2)"),
    ("QTIF", "(?s-u)^.{4}(idsc|idat|iicc)"),
    ("FPX", "(?s-u)^\\xd0\\xcf\\x11\\xe0\\xa1\\xb1\\x1a\\xe1"),
    ("PICT", "(?s-u)^(.{10}|.{522})(\\x11\\x01|\\x00\\x11)"),
    ("ZIP", "(?s-u)^PK\\x03\\x04"),
    ("GZIP", "(?s-u)^\\x1f\\x8b\\x08"),
    ("PLIST", "(?s-u)^(bplist0|\\s*<|\\xfe\\xff\\x00)"),
    ("RAR", "(?s-u)^Rar!\\x1a\\x07\\x01?\\x00"),
    ("BZ2", "(?s-u)^BZh[1-9]\\x31\\x41\\x59\\x26\\x53\\x59"),
    ("CZI", "(?s-u)^ZISRAWFILE\\x00{6}"),
    ("TAR", "(?s-u)^.{257}ustar(  )?\\x00"),
    (
        "EXE",
        "(?s-u)^(MZ|\\xca\\xfe\\xba\\xbe|\\xfe\\xed\\xfa[\\xce\\xcf]|[\\xce\\xcf]\\xfa\\xed\\xfe|Joy!peff|\\x7fELF|#!\\s*/\\S*bin/|!<arch>\\x0a)",
    ),
    ("EXR", "(?s-u)^\\x76\\x2f\\x31\\x01"),
    ("HDR", "(?s-u)^#\\?(RADIANCE|RGBE)\\x0a"),
    (
        "CHM",
        "(?s-u)^ITSF.{20}\\x10\\xfd\\x01\\x7c\\xaa\\x7b\\xd0\\x11\\x9e\\x0c\\x00\\xa0\\xc9\\x22\\xe6\\xec",
    ),
    (
        "LNK",
        "(?s-u)^.{4}\\x01\\x14\\x02\\x00{5}\\xc0\\x00{6}\\x46",
    ),
    (
        "WMF",
        "(?s-u)^(\\xd7\\xcd\\xc6\\x9a\\x00\\x00|\\x01\\x00\\x09\\x00\\x00\\x03)",
    ),
    ("AVC", "(?s-u)^\\+A\\+V\\+C\\+"),
    ("DEX", "(?s-u)^dex\\x0a035\\x00"),
    ("DPX", "(?s-u)^(SDPX|XPDS)"),
    ("RAW", "(?s-u)^(.{25}ARECOYK|II|MM)"),
    (
        "Font",
        "(?s-u)^((\\x00\\x01\\x00\\x00|OTTO|true|typ1)[\\x00\\x01]|ttcf\\x00[\\x01\\x02]\\x00\\x00|\\x00[\\x01\\x02]|(.{6})?%!(PS-(AdobeFont-|Bitstream )|FontType1-)|Start(Comp|Master)?FontMetrics|wOF[F2])",
    ),
    ("JUMBF", "(?s-u)^.{4}jumb\\x00.{3}jumd"),
    ("RSRC", "(?s-u)^(....)?\\x00\\x00\\x01\\x00"),
    ("M2TS", "(?s-u)^(....)?\\x47"),
    (
        "MacOS",
        "(?s-u)^\\x00\\x05\\x16\\x07\\x00.\\x00\\x00Mac OS X        ",
    ),
    ("PHP", "(?s-u)^<\\?php\\s"),
    (
        "PCX",
        "(?s-u)^\\x0a[\\x00-\\x05]\\x01[\\x01\\x02\\x04\\x08].{64}[\\x00-\\x02]",
    ),
    ("DCX", "(?s-u)^\\xb1\\x68\\xde\\x3a"),
    ("DWF", "(?s-u)^\\(DWF V\\d"),
    ("DWG", "(?s-u)^AC10\\d{2}\\x00"),
    ("DXF", "(?s-u)^\\s*0\\s+\\x00?\\s*SECTION\\s+2\\s+HEADER"),
    (
        "WTV",
        "(?s-u)^\\xb7\\xd8\\x00\\x20\\x37\\x49\\xda\\x11\\xa6\\x4e\\x00\\x07\\xe9\\x5e\\xad\\x8d",
    ),
    ("Torrent", "(?s-u)^d\\d+:\\w+"),
    ("VCard", "(?s-u)^(?i)BEGIN:(VCARD|VCALENDAR|VNOTE)\\r\\n"),
    ("LRI", "(?s-u)^LELR \\x00"),
    ("R3D", "(?s-u)^\\x00\\x00..RED(1|2)"),
    ("AA", "(?s-u)^.{4}\\x57\\x90\\x75\\x36"),
    (
        "PDB",
        "(?s-u)^.{60}(\\.pdfADBE|TEXtREAd|BVokBDIC|DB99DBOS|PNRdPPrs|DataPPrs|vIMGView|PmDBPmDB|InfoINDB|ToGoToGo|SDocSilX|JbDbJBas|JfDbJFil|DATALSdb|Mdb1Mdb1|BOOKMOBI|DataPlkr|DataSprd|SM01SMem|TEXtTlDc|InfoTlIf|DataTlMl|DataTlPt|dataTDBP|TdatTide|ToRaTRPW|zTXTGPlm|BDOCWrdS)",
    ),
    (
        "MRC",
        "(?s-u)^.{64}[\\x01\\x02\\x03]\\x00\\x00\\x00[\\x01\\x02\\x03]\\x00\\x00\\x00[\\x01\\x02\\x03]\\x00\\x00\\x00.{132}MAP[\\x00 ](\\x44\\x44|\\x44\\x41|\\x11\\x11)\\x00\\x00",
    ),
    ("LIF", "(?s-u)^\\x70\\x00{3}.{4}\\x2a.{4}<\\x00"),
    (
        "JXL",
        "(?s-u)^(\\xff\\x0a|\\x00\\x00\\x00\\x0cJXL \\x0d\\x0a......ftypjxl )",
    ),
    ("MOI", "(?s-u)^V6"),
    (
        "ALIAS",
        "(?s-u)^book\\x00\\x00\\x00\\x00mark\\x00\\x00\\x00\\x00",
    ),
    (
        "PCAP",
        "(?s-u)^\\xa1\\xb2(\\xc3\\xd4|\\x3c\\x4d)\\x00.\\x00.|(\\xd4\\xc3|\\x4d\\x3c)\\xb2\\xa1.\\x00.\\x00|\\x0a\\x0d\\x0d\\x0a.{4}(\\x1a\\x2b\\x3c\\x4d|\\x4d\\x3c\\x2b\\x1a)|GMBU\\x00\\x02",
    ),
    (
        "JSON",
        "(?s-u)^(\\xef\\xbb\\xbf)?\\s*(\\[\\s*)?\\{\\s*\"[^\"]*\"\\s*:",
    ),
    (
        "DICOM",
        "(?s-u)^(.{128}DICM|\\x00[\\x02\\x04\\x06\\x08]\\x00[\\x00-\\x20]|[\\x02\\x04\\x06\\x08]\\x00[\\x00-\\x20]\\x00)",
    ),
    ("NKA", "(?s-u)^NIKONADJ"),
    ("ICO", "(?s-u)^\\x00\\x00[\\x01\\x02]\\x00[^0]\\x00"),
    (
        "TXT",
        "(?s-u)^(\\xff\\xfe|(\\x00\\x00)?\\xfe\\xff|(\\xef\\xbb\\xbf)?[\\x07-\\x0d\\x20-\\x7e\\x80-\\xfe]*$)",
    ),
    ("AAC", "(?s-u)^\\xff[\\xf0\\xf1]"),
    ("BTF", "(?s-u)^(II\\x2b\\x00|MM\\x00\\x2b)"),
    ("DOCX", "(?s-u)^PK\\x03\\x04"),
    ("EPS", "(?s-u)^(%!PS|%!Ad|\\xc5\\xd0\\xd3\\xc6)"),
    ("EXIF", "(?s-u)^(II\\x2a\\x00|MM\\x00\\x2a)"),
    ("ORF", "(?s-u)^(II|MM)"),
    ("PFM", "(?s-u)^P[Ff]\\x0a\\d+ \\d+\\x0a[-+0-9.]+\\x0a"),
    ("RWZ", "(?s-u)^rawzor"),
];

/// Lowercase extension -> (`FileType`, formats that can process it).
///
/// Aliases are already resolved. The formats come from `%fileTypeLookup`'s
/// arrayref and are what `MAGIC` is keyed by; the file type is the resolved
/// key, which is what ExifTool reports.
pub static EXT_TO_TYPE: &[(&str, &str, &[&str])] = &[
    ("360", "360", &["MOV"]),
    ("3fr", "3FR", &["TIFF"]),
    ("3g2", "3G2", &["MOV"]),
    ("3gp", "3GP", &["MOV"]),
    ("3gp2", "3G2", &["MOV"]),
    ("3gpp", "3GP", &["MOV"]),
    ("7z", "7Z", &["7Z"]),
    ("a", "A", &["EXE"]),
    ("aa", "AA", &["AA"]),
    ("aac", "AAC", &["AAC"]),
    ("aae", "AAE", &["PLIST"]),
    ("aax", "AAX", &["MOV"]),
    ("acfm", "ACFM", &["Font"]),
    ("acr", "ACR", &["DICOM"]),
    ("afm", "AFM", &["Font"]),
    ("ai", "AI", &["PDF", "PS"]),
    ("aif", "AIFF", &["AIFF"]),
    ("aifc", "AIFC", &["AIFF"]),
    ("aiff", "AIFF", &["AIFF"]),
    ("ait", "AI", &["PDF", "PS"]),
    ("alias", "ALIAS", &["ALIAS"]),
    ("amfm", "AMFM", &["Font"]),
    ("ape", "APE", &["APE"]),
    ("apng", "APNG", &["PNG"]),
    ("arq", "ARQ", &["TIFF"]),
    ("arw", "ARW", &["TIFF"]),
    ("asf", "ASF", &["ASF"]),
    ("avc", "AVC", &["AVC"]),
    ("avi", "AVI", &["RIFF"]),
    ("avif", "AVIF", &["MOV"]),
    ("azw", "MOBI", &["PDB"]),
    ("azw3", "MOBI", &["PDB"]),
    ("bmp", "BMP", &["BMP"]),
    ("bpg", "BPG", &["BPG"]),
    ("btf", "BTF", &["BTF"]),
    ("bz2", "BZ2", &["BZ2"]),
    ("c2pa", "C2PA", &["JUMBF"]),
    ("cap", "PCAP", &["PCAP"]),
    ("chm", "CHM", &["CHM"]),
    ("ciff", "CIFF", &["CRW"]),
    ("cos", "COS", &["COS"]),
    ("cr2", "CR2", &["TIFF"]),
    ("cr3", "CR3", &["MOV"]),
    ("crm", "CRM", &["MOV"]),
    ("crw", "CRW", &["CRW"]),
    ("cs1", "CS1", &["PSD"]),
    ("csv", "CSV", &["TXT"]),
    ("cur", "CUR", &["ICO"]),
    ("czi", "CZI", &["CZI"]),
    ("dc3", "DICOM", &["DICOM"]),
    ("dcm", "DICOM", &["DICOM"]),
    ("dcp", "DCP", &["TIFF"]),
    ("dcr", "DCR", &["TIFF"]),
    ("dcx", "DCX", &["DCX"]),
    ("dex", "DEX", &["DEX"]),
    ("dfont", "DFONT", &["Font"]),
    ("dib", "DIB", &["BMP"]),
    ("dic", "DICOM", &["DICOM"]),
    ("dicm", "DICM", &["DICOM"]),
    ("dir", "DIR", &["DIR"]),
    ("divx", "DIVX", &["ASF"]),
    ("djv", "DJVU", &["AIFF"]),
    ("djvu", "DJVU", &["AIFF"]),
    ("dll", "DLL", &["EXE"]),
    ("dng", "DNG", &["TIFF"]),
    ("doc", "DOC", &["FPX"]),
    ("docm", "DOCM", &["ZIP", "FPX"]),
    ("docx", "DOCX", &["ZIP", "FPX"]),
    ("dot", "DOT", &["FPX"]),
    ("dotm", "DOTM", &["ZIP", "FPX"]),
    ("dotx", "DOTX", &["ZIP", "FPX"]),
    ("dpx", "DPX", &["DPX"]),
    ("dr4", "DR4", &["DR4"]),
    ("ds2", "DS2", &["DSS"]),
    ("dss", "DSS", &["DSS"]),
    ("dv", "DV", &["DV"]),
    ("dvb", "DVB", &["MOV"]),
    ("dvr-ms", "DVR-MS", &["ASF"]),
    ("dwf", "DWF", &["DWF"]),
    ("dwg", "DWG", &["DWG"]),
    ("dxf", "DXF", &["DXF"]),
    ("dylib", "DYLIB", &["EXE"]),
    ("eip", "EIP", &["ZIP"]),
    ("eps", "EPS", &["EPS"]),
    ("eps2", "EPS", &["EPS"]),
    ("eps3", "EPS", &["EPS"]),
    ("epsf", "EPS", &["EPS"]),
    ("epub", "EPUB", &["ZIP"]),
    ("erf", "ERF", &["TIFF"]),
    ("exe", "EXE", &["EXE"]),
    ("exif", "EXIF", &["EXIF"]),
    ("exr", "EXR", &["EXR"]),
    ("exv", "EXV", &["EXV"]),
    ("f4a", "F4A", &["MOV"]),
    ("f4b", "F4B", &["MOV"]),
    ("f4p", "F4P", &["MOV"]),
    ("f4v", "F4V", &["MOV"]),
    ("fff", "FFF", &["TIFF", "FLIR"]),
    ("fit", "FITS", &["FITS"]),
    ("fits", "FITS", &["FITS"]),
    ("fla", "FLA", &["FPX"]),
    ("flac", "FLAC", &["FLAC"]),
    ("flif", "FLIF", &["FLIF"]),
    ("flir", "FLIR", &["FLIR"]),
    ("flv", "FLV", &["FLV"]),
    ("fpf", "FPF", &["FPF"]),
    ("fpx", "FPX", &["FPX"]),
    ("gif", "GIF", &["GIF"]),
    ("glv", "GLV", &["MOV"]),
    ("gpr", "GPR", &["TIFF"]),
    ("gz", "GZIP", &["GZIP"]),
    ("gzip", "GZIP", &["GZIP"]),
    ("hdp", "HDP", &["TIFF"]),
    ("hdr", "HDR", &["HDR"]),
    ("heic", "HEIC", &["MOV"]),
    ("heif", "HEIF", &["MOV"]),
    ("hif", "HEIF", &["MOV"]),
    ("htm", "HTML", &["HTML"]),
    ("html", "HTML", &["HTML"]),
    ("ical", "VCard", &["VCard"]),
    ("icc", "ICC", &["ICC"]),
    ("icm", "ICC", &["ICC"]),
    ("ico", "ICO", &["ICO"]),
    ("ics", "ICS", &["VCard"]),
    ("idml", "IDML", &["ZIP"]),
    ("iiq", "IIQ", &["TIFF"]),
    ("ind", "IND", &["IND"]),
    ("indd", "INDD", &["IND"]),
    ("indt", "INDT", &["IND"]),
    ("insp", "INSP", &["JPEG"]),
    ("insv", "INSV", &["MOV"]),
    ("inx", "INX", &["XMP"]),
    ("iso", "ISO", &["ISO"]),
    ("itc", "ITC", &["ITC"]),
    ("j2c", "J2C", &["JP2"]),
    ("j2k", "J2C", &["JP2"]),
    ("jng", "JNG", &["PNG"]),
    ("jp2", "JP2", &["JP2"]),
    ("jpc", "J2C", &["JP2"]),
    ("jpe", "JPEG", &["JPEG"]),
    ("jpeg", "JPEG", &["JPEG"]),
    ("jpf", "JP2", &["JP2"]),
    ("jpg", "JPEG", &["JPEG"]),
    ("jph", "JPH", &["JP2"]),
    ("jpm", "JPM", &["JP2"]),
    ("jps", "JPS", &["JPEG"]),
    ("jpx", "JPX", &["JP2"]),
    ("json", "JSON", &["JSON"]),
    ("jumbf", "JUMBF", &["JUMBF"]),
    ("jxl", "JXL", &["JXL"]),
    ("jxr", "JXR", &["TIFF"]),
    ("k25", "K25", &["TIFF"]),
    ("kdc", "KDC", &["TIFF"]),
    ("key", "KEY", &["ZIP"]),
    ("kth", "KTH", &["ZIP"]),
    ("la", "LA", &["RIFF"]),
    ("lfp", "LFP", &["LFP"]),
    ("lfr", "LFP", &["LFP"]),
    ("lif", "LIF", &["LIF"]),
    ("lnk", "LNK", &["LNK"]),
    ("lri", "LRI", &["LRI"]),
    ("lrv", "LRV", &["MOV"]),
    ("m2t", "M2TS", &["M2TS"]),
    ("m2ts", "M2TS", &["M2TS"]),
    ("m2v", "M2V", &["MPEG"]),
    ("m4a", "M4A", &["MOV"]),
    ("m4b", "M4B", &["MOV"]),
    ("m4p", "M4P", &["MOV"]),
    ("m4v", "M4V", &["MOV"]),
    ("macos", "MacOS", &["MacOS"]),
    ("max", "MAX", &["FPX"]),
    ("mef", "MEF", &["TIFF"]),
    ("mie", "MIE", &["MIE"]),
    ("mif", "MIFF", &["MIFF"]),
    ("miff", "MIFF", &["MIFF"]),
    ("mka", "MKA", &["MKV"]),
    ("mks", "MKS", &["MKV"]),
    ("mkv", "MKV", &["MKV"]),
    ("mng", "MNG", &["PNG"]),
    ("mobi", "MOBI", &["PDB"]),
    ("modd", "MODD", &["PLIST"]),
    ("moi", "MOI", &["MOI"]),
    ("mos", "MOS", &["TIFF"]),
    ("mov", "MOV", &["MOV"]),
    ("mp3", "MP3", &["MP3"]),
    ("mp4", "MP4", &["MOV"]),
    ("mpc", "MPC", &["MPC"]),
    ("mpeg", "MPEG", &["MPEG"]),
    ("mpg", "MPEG", &["MPEG"]),
    ("mpo", "MPO", &["JPEG"]),
    ("mqv", "MQV", &["MOV"]),
    ("mrc", "MRC", &["MRC"]),
    ("mrw", "MRW", &["MRW"]),
    ("mts", "M2TS", &["M2TS"]),
    ("mxf", "MXF", &["MXF"]),
    ("nef", "NEF", &["TIFF"]),
    ("newer", "COS", &["COS"]),
    ("nka", "NKA", &["NKA"]),
    ("nksc", "NKSC", &["XMP"]),
    ("nmbtemplate", "NMBTEMPLATE", &["ZIP"]),
    ("nrw", "NRW", &["TIFF"]),
    ("numbers", "NUMBERS", &["ZIP"]),
    ("nxd", "NXD", &["XMP"]),
    ("o", "O", &["EXE"]),
    ("odb", "ODB", &["ZIP"]),
    ("odc", "ODC", &["ZIP"]),
    ("odf", "ODF", &["ZIP"]),
    ("odg", "ODG", &["ZIP"]),
    ("odi", "ODI", &["ZIP"]),
    ("odp", "ODP", &["ZIP"]),
    ("ods", "ODS", &["ZIP"]),
    ("odt", "ODT", &["ZIP"]),
    ("ofr", "OFR", &["RIFF"]),
    ("ogg", "OGG", &["OGG"]),
    ("ogv", "OGV", &["OGG"]),
    ("onp", "ONP", &["JSON"]),
    ("opus", "OPUS", &["OGG"]),
    ("orf", "ORF", &["ORF"]),
    ("ori", "ORF", &["ORF"]),
    ("otf", "OTF", &["Font"]),
    ("pac", "PAC", &["RIFF"]),
    ("pages", "PAGES", &["ZIP"]),
    ("pbm", "PBM", &["PPM"]),
    ("pcap", "PCAP", &["PCAP"]),
    ("pcapng", "PCAPNG", &["PCAP"]),
    ("pcd", "PCD", &["PCD"]),
    ("pct", "PICT", &["PICT"]),
    ("pcx", "PCX", &["PCX"]),
    ("pdb", "PDB", &["PDB"]),
    ("pdf", "PDF", &["PDF"]),
    ("pef", "PEF", &["TIFF"]),
    ("pfa", "PFA", &["Font"]),
    ("pfb", "PFB", &["Font"]),
    ("pfm", "PFM", &["Font", "PFM"]),
    ("pgf", "PGF", &["PGF"]),
    ("pgm", "PGM", &["PPM"]),
    ("php", "PHP", &["PHP"]),
    ("php3", "PHP", &["PHP"]),
    ("php4", "PHP", &["PHP"]),
    ("php5", "PHP", &["PHP"]),
    ("phps", "PHP", &["PHP"]),
    ("phtml", "PHP", &["PHP"]),
    ("pict", "PICT", &["PICT"]),
    ("plist", "PLIST", &["PLIST"]),
    ("pmp", "PMP", &["PMP"]),
    ("png", "PNG", &["PNG"]),
    ("pot", "POT", &["FPX"]),
    ("potm", "POTM", &["ZIP", "FPX"]),
    ("potx", "POTX", &["ZIP", "FPX"]),
    ("ppam", "PPAM", &["ZIP", "FPX"]),
    ("ppax", "PPAX", &["ZIP", "FPX"]),
    ("ppm", "PPM", &["PPM"]),
    ("pps", "PPS", &["FPX"]),
    ("ppsm", "PPSM", &["ZIP", "FPX"]),
    ("ppsx", "PPSX", &["ZIP", "FPX"]),
    ("ppt", "PPT", &["FPX"]),
    ("pptm", "PPTM", &["ZIP", "FPX"]),
    ("pptx", "PPTX", &["ZIP", "FPX"]),
    ("prc", "PRC", &["PDB"]),
    ("ps", "PS", &["PS"]),
    ("ps2", "PS", &["PS"]),
    ("ps3", "PS", &["PS"]),
    ("psb", "PSB", &["PSD"]),
    ("psd", "PSD", &["PSD"]),
    ("psdt", "PSDT", &["PSD"]),
    ("psp", "PSP", &["PSP"]),
    ("pspframe", "PSP", &["PSP"]),
    ("pspimage", "PSP", &["PSP"]),
    ("pspshape", "PSP", &["PSP"]),
    ("psptube", "PSP", &["PSP"]),
    ("qif", "QTIF", &["QTIF"]),
    ("qt", "MOV", &["MOV"]),
    ("qti", "QTIF", &["QTIF"]),
    ("qtif", "QTIF", &["QTIF"]),
    ("r3d", "R3D", &["R3D"]),
    ("ra", "RA", &["Real"]),
    ("raf", "RAF", &["RAF"]),
    ("ram", "RAM", &["Real"]),
    ("rar", "RAR", &["RAR"]),
    ("raw", "RAW", &["RAW", "TIFF"]),
    ("rif", "RIFF", &["RIFF"]),
    ("riff", "RIFF", &["RIFF"]),
    ("rm", "RM", &["Real"]),
    ("rmvb", "RMVB", &["Real"]),
    ("rpm", "RPM", &["Real"]),
    ("rsrc", "RSRC", &["RSRC"]),
    ("rtf", "RTF", &["RTF"]),
    ("rv", "RV", &["Real"]),
    ("rw2", "RW2", &["TIFF"]),
    ("rwl", "RWL", &["TIFF"]),
    ("rwz", "RWZ", &["RWZ"]),
    ("seq", "SEQ", &["FLIR"]),
    ("sketch", "SKETCH", &["ZIP"]),
    ("so", "SO", &["EXE"]),
    ("sr2", "SR2", &["TIFF"]),
    ("srf", "SRF", &["TIFF"]),
    ("srw", "SRW", &["TIFF"]),
    ("svg", "SVG", &["XMP"]),
    ("swf", "SWF", &["SWF"]),
    ("tar", "TAR", &["TAR"]),
    ("thm", "THM", &["JPEG"]),
    ("thmx", "THMX", &["ZIP", "FPX"]),
    ("tif", "TIFF", &["TIFF"]),
    ("tiff", "TIFF", &["TIFF"]),
    ("torrent", "Torrent", &["Torrent"]),
    ("ts", "M2TS", &["M2TS"]),
    ("ttc", "TTC", &["Font"]),
    ("ttf", "TTF", &["Font"]),
    ("tub", "PSP", &["PSP"]),
    ("txt", "TXT", &["TXT"]),
    ("vcard", "VCard", &["VCard"]),
    ("vcf", "VCard", &["VCard"]),
    ("vnt", "VNT", &["FPX", "VCard"]),
    ("vob", "VOB", &["MPEG"]),
    ("vrd", "VRD", &["VRD"]),
    ("vsd", "VSD", &["FPX"]),
    ("wav", "WAV", &["RIFF"]),
    ("wdp", "WDP", &["TIFF"]),
    ("webm", "WEBM", &["MKV"]),
    ("webp", "WEBP", &["RIFF"]),
    ("wma", "WMA", &["ASF"]),
    ("wmf", "WMF", &["WMF"]),
    ("wmv", "WMV", &["ASF"]),
    ("woff", "WOFF", &["Font"]),
    ("woff2", "WOFF2", &["Font"]),
    ("wpg", "WPG", &["WPG"]),
    ("wtv", "WTV", &["WTV"]),
    ("wv", "WV", &["RIFF"]),
    ("x3f", "X3F", &["X3F"]),
    ("xcf", "XCF", &["XCF"]),
    ("xhtml", "XHTML", &["HTML"]),
    ("xisf", "XISF", &["XISF"]),
    ("xla", "XLA", &["FPX"]),
    ("xlam", "XLAM", &["ZIP", "FPX"]),
    ("xls", "XLS", &["FPX"]),
    ("xlsb", "XLSB", &["ZIP", "FPX"]),
    ("xlsm", "XLSM", &["ZIP", "FPX"]),
    ("xlsx", "XLSX", &["ZIP", "FPX"]),
    ("xlt", "XLT", &["FPX"]),
    ("xltm", "XLTM", &["ZIP", "FPX"]),
    ("xltx", "XLTX", &["ZIP", "FPX"]),
    ("xmp", "XMP", &["XMP"]),
    ("zip", "ZIP", &["ZIP"]),
];

/// File type -> MIME type.
pub static MIME_TYPE: &[(&str, &str)] = &[
    ("3FR", "image/x-hasselblad-3fr"),
    ("7Z", "application/x-7z-compressed"),
    ("AA", "audio/audible"),
    ("AAC", "audio/aac"),
    ("AAE", "application/vnd.apple.photos"),
    ("AI", "application/vnd.adobe.illustrator"),
    ("AIFF", "audio/x-aiff"),
    ("ALIAS", "application/x-macos"),
    ("APE", "audio/x-monkeys-audio"),
    ("APNG", "image/apng"),
    ("ARW", "image/x-sony-arw"),
    ("ASF", "video/x-ms-asf"),
    ("BMP", "image/bmp"),
    ("BPG", "image/bpg"),
    ("BTF", "image/x-tiff-big"),
    ("BZ2", "application/bzip2"),
    ("C2PA", "application/c2pa"),
    ("CHM", "application/x-chm"),
    ("COS", "application/octet-stream"),
    ("CR2", "image/x-canon-cr2"),
    ("CR3", "image/x-canon-cr3"),
    ("CRM", "video/x-canon-crm"),
    ("CRW", "image/x-canon-crw"),
    ("CSV", "text/csv"),
    ("CUR", "image/x-cursor"),
    ("CZI", "image/x-zeiss-czi"),
    ("Canon 1D RAW", "image/x-raw"),
    ("DCP", "application/octet-stream"),
    ("DCR", "image/x-kodak-dcr"),
    ("DCX", "image/dcx"),
    ("DEX", "application/octet-stream"),
    ("DFONT", "application/x-dfont"),
    ("DICOM", "application/dicom"),
    ("DIVX", "video/divx"),
    ("DJVU", "image/vnd.djvu"),
    ("DNG", "image/x-adobe-dng"),
    ("DOC", "application/msword"),
    ("DOCM", "application/vnd.ms-word.document.macroEnabled.12"),
    (
        "DOCX",
        "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    ),
    ("DOT", "application/msword"),
    (
        "DOTM",
        "application/vnd.ms-word.template.macroEnabledTemplate",
    ),
    (
        "DOTX",
        "application/vnd.openxmlformats-officedocument.wordprocessingml.template",
    ),
    ("DPX", "image/x-dpx"),
    ("DR4", "application/octet-stream"),
    ("DS2", "audio/x-ds2"),
    ("DSS", "audio/x-dss"),
    ("DV", "video/x-dv"),
    ("DVR-MS", "video/x-ms-dvr"),
    ("DWF", "model/vnd.dwf"),
    ("DWG", "image/vnd.dwg"),
    ("DXF", "application/dxf"),
    ("EIP", "application/x-captureone"),
    ("EPS", "application/postscript"),
    ("ERF", "image/x-epson-erf"),
    ("EXE", "application/octet-stream"),
    ("EXR", "image/x-exr"),
    ("EXV", "image/x-exv"),
    ("FFF", "image/x-hasselblad-fff"),
    ("FITS", "image/fits"),
    ("FLA", "application/vnd.adobe.fla"),
    ("FLAC", "audio/flac"),
    ("FLIF", "image/flif"),
    ("FLIR", "image/x-flir-fff"),
    ("FLV", "video/x-flv"),
    ("FPF", "image/x-flir-fpf"),
    ("FPX", "image/vnd.fpx"),
    ("Font", "application/x-font-type1"),
    ("GIF", "image/gif"),
    ("GPR", "image/x-gopro-gpr"),
    ("GZIP", "application/x-gzip"),
    ("HDP", "image/vnd.ms-photo"),
    ("HDR", "image/vnd.radiance"),
    ("HTML", "text/html"),
    ("ICC", "application/vnd.iccprofile"),
    ("ICO", "image/x-icon"),
    ("ICS", "text/calendar"),
    ("IDML", "application/vnd.adobe.indesign-idml-package"),
    ("IIQ", "image/x-raw"),
    ("IND", "application/x-indesign"),
    ("INX", "application/x-indesign-interchange"),
    ("ISO", "application/x-iso9660-image"),
    ("ITC", "application/itunes"),
    ("J2C", "image/x-j2c"),
    ("JNG", "image/jng"),
    ("JP2", "image/jp2"),
    ("JPEG", "image/jpeg"),
    ("JPH", "image/jph"),
    ("JPM", "image/jpm"),
    ("JPS", "image/x-jps"),
    ("JPX", "image/jpx"),
    ("JSON", "application/json"),
    ("JUMBF", "application/octet-stream"),
    ("JXL", "image/jxl"),
    ("JXR", "image/jxr"),
    ("K25", "image/x-kodak-k25"),
    ("KDC", "image/x-kodak-kdc"),
    ("KEY", "application/x-iwork-keynote-sffkey"),
    ("LFP", "image/x-lytro-lfp"),
    ("LIF", "image/x-lif"),
    ("LNK", "application/octet-stream"),
    ("LRI", "image/x-light-lri"),
    ("M2T", "video/mpeg"),
    ("M2TS", "video/m2ts"),
    ("MAX", "application/x-3ds"),
    ("MEF", "image/x-mamiya-mef"),
    ("MIE", "application/x-mie"),
    ("MIFF", "application/x-magick-image"),
    ("MKA", "audio/x-matroska"),
    ("MKS", "application/x-matroska"),
    ("MKV", "video/x-matroska"),
    ("MNG", "video/mng"),
    ("MOBI", "application/x-mobipocket-ebook"),
    ("MOI", "application/octet-stream"),
    ("MOS", "image/x-raw"),
    ("MOV", "video/quicktime"),
    ("MP3", "audio/mpeg"),
    ("MP4", "video/mp4"),
    ("MPC", "audio/x-musepack"),
    ("MPEG", "video/mpeg"),
    ("MRC", "image/x-mrc"),
    ("MRW", "image/x-minolta-mrw"),
    ("MXF", "application/mxf"),
    ("NEF", "image/x-nikon-nef"),
    ("NKSC", "application/x-nikon-nxstudio"),
    ("NRW", "image/x-nikon-nrw"),
    ("NUMBERS", "application/x-iwork-numbers-sffnumbers"),
    ("ODB", "application/vnd.oasis.opendocument.database"),
    ("ODC", "application/vnd.oasis.opendocument.chart"),
    ("ODF", "application/vnd.oasis.opendocument.formula"),
    ("ODG", "application/vnd.oasis.opendocument.graphics"),
    ("ODI", "application/vnd.oasis.opendocument.image"),
    ("ODP", "application/vnd.oasis.opendocument.presentation"),
    ("ODS", "application/vnd.oasis.opendocument.spreadsheet"),
    ("ODT", "application/vnd.oasis.opendocument.text"),
    ("OGG", "audio/ogg"),
    ("OGV", "video/ogg"),
    ("ONP", "application/on1"),
    ("ORF", "image/x-olympus-orf"),
    ("OTF", "application/font-otf"),
    ("PAGES", "application/x-iwork-pages-sffpages"),
    ("PBM", "image/x-portable-bitmap"),
    ("PCAP", "application/vnd.tcpdump.pcap"),
    ("PCD", "image/x-photo-cd"),
    ("PCX", "image/pcx"),
    ("PDB", "application/vnd.palm"),
    ("PDF", "application/pdf"),
    ("PEF", "image/x-pentax-pef"),
    ("PFA", "application/x-font-type1"),
    ("PFM", "image/x-pfm"),
    ("PGF", "image/pgf"),
    ("PGM", "image/x-portable-graymap"),
    ("PHP", "application/x-httpd-php"),
    ("PICT", "image/pict"),
    ("PLIST", "application/xml"),
    ("PMP", "image/x-sony-pmp"),
    ("PNG", "image/png"),
    ("POT", "application/vnd.ms-powerpoint"),
    (
        "POTM",
        "application/vnd.ms-powerpoint.template.macroEnabled.12",
    ),
    (
        "POTX",
        "application/vnd.openxmlformats-officedocument.presentationml.template",
    ),
    (
        "PPAM",
        "application/vnd.ms-powerpoint.addin.macroEnabled.12",
    ),
    (
        "PPAX",
        "application/vnd.openxmlformats-officedocument.presentationml.addin",
    ),
    ("PPM", "image/x-portable-pixmap"),
    ("PPS", "application/vnd.ms-powerpoint"),
    (
        "PPSM",
        "application/vnd.ms-powerpoint.slideshow.macroEnabled.12",
    ),
    (
        "PPSX",
        "application/vnd.openxmlformats-officedocument.presentationml.slideshow",
    ),
    ("PPT", "application/vnd.ms-powerpoint"),
    (
        "PPTM",
        "application/vnd.ms-powerpoint.presentation.macroEnabled.12",
    ),
    (
        "PPTX",
        "application/vnd.openxmlformats-officedocument.presentationml.presentation",
    ),
    ("PS", "application/postscript"),
    ("PSD", "application/vnd.adobe.photoshop"),
    ("PSP", "image/x-paintshoppro"),
    ("QTIF", "image/x-quicktime"),
    ("R3D", "video/x-red-r3d"),
    ("RA", "audio/x-pn-realaudio"),
    ("RAF", "image/x-fujifilm-raf"),
    ("RAM", "audio/x-pn-realaudio"),
    ("RAR", "application/x-rar-compressed"),
    ("RAW", "image/x-raw"),
    ("RM", "application/vnd.rn-realmedia"),
    ("RMVB", "application/vnd.rn-realmedia-vbr"),
    ("RPM", "audio/x-pn-realaudio-plugin"),
    ("RSRC", "application/ResEdit"),
    ("RTF", "text/rtf"),
    ("RV", "video/vnd.rn-realvideo"),
    ("RW2", "image/x-panasonic-rw2"),
    ("RWL", "image/x-leica-rwl"),
    ("RWZ", "image/x-rawzor"),
    ("SEQ", "image/x-flir-seq"),
    ("SKETCH", "application/sketch"),
    ("SR2", "image/x-sony-sr2"),
    ("SRF", "image/x-sony-srf"),
    ("SRW", "image/x-samsung-srw"),
    ("SVG", "image/svg+xml"),
    ("SWF", "application/x-shockwave-flash"),
    ("TAR", "application/x-tar"),
    ("THMX", "application/vnd.ms-officetheme"),
    ("TIFF", "image/tiff"),
    ("TTC", "application/font-ttf"),
    ("TTF", "application/font-ttf"),
    ("TXT", "text/plain"),
    ("Torrent", "application/x-bittorrent"),
    ("VCard", "text/vcard"),
    ("VRD", "application/octet-stream"),
    ("VSD", "application/x-visio"),
    ("WDP", "image/vnd.ms-photo"),
    ("WEBM", "video/webm"),
    ("WMA", "audio/x-ms-wma"),
    ("WMF", "application/x-wmf"),
    ("WMV", "video/x-ms-wmv"),
    ("WPG", "image/x-wpg"),
    ("WTV", "video/x-ms-wtv"),
    ("X3F", "image/x-sigma-x3f"),
    ("XCF", "image/x-xcf"),
    ("XISF", "image/x-xisf"),
    ("XLA", "application/vnd.ms-excel"),
    ("XLAM", "application/vnd.ms-excel.addin.macroEnabled.12"),
    ("XLS", "application/vnd.ms-excel"),
    (
        "XLSB",
        "application/vnd.ms-excel.sheet.binary.macroEnabled.12",
    ),
    ("XLSM", "application/vnd.ms-excel.sheet.macroEnabled.12"),
    (
        "XLSX",
        "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    ),
    ("XLT", "application/vnd.ms-excel"),
    ("XLTM", "application/vnd.ms-excel.template.macroEnabled.12"),
    (
        "XLTX",
        "application/vnd.openxmlformats-officedocument.spreadsheetml.template",
    ),
    ("XML", "application/xml"),
    ("XMP", "application/rdf+xml"),
    ("ZIP", "application/zip"),
];

/// File type -> preferred extension, where it differs from the lowercased type.
///
/// ExifTool keeps this as a lexical hash, so it is sliced out of ExifTool.pm
/// and eval'd rather than read from the symbol table. Without it DICOM reports
/// its extension as `dicom` instead of `dcm`.
pub static FILE_TYPE_EXT: &[(&str, &str)] = &[
    ("Canon 1D RAW", "tif"),
    ("DICOM", "dcm"),
    ("FLIR", "fff"),
    ("GZIP", "gz"),
    ("JPEG", "jpg"),
    ("M2TS", "mts"),
    ("MPEG", "mpg"),
    ("TIFF", "tif"),
    ("VCard", "vcf"),
];
