//! ExifTool `Casio` ProcessBinaryData tables, generated from ExifTool
//! 13.59's own Perl hashes -- one file per module; `mod.rs` beside this
//! file is the hub that declares and re-exports it.
//!
//! DO NOT EDIT. Regenerate with `just regen-tables` (see `mod.rs`).

#![allow(clippy::unreadable_literal, clippy::too_many_lines, unused_parens)]

// Everything a table literal names -- the schema types, `ExprId`, the
// `cond`/`subdir`/`ifd_schema` imports -- is in scope in the hub, and a glob
// import of the parent module brings its private imports along (RFC 1560).
#[allow(unused_imports)]
use super::*;

/// `Image::ExifTool::Casio::AVI` -- 1 fields,
/// 0 `_variants` groups (Step 23).
/// Generated from ExifTool's in-memory tag table. Do not edit by hand.
pub static CASIO_AVI: BinaryTable = BinaryTable {
    module: "Casio",
    table: "AVI",
    group0: "MakerNotes",
    group1: "Casio",
    group2: "Camera",
    first_entry: 0,
    default_format: Fmt::Int8u,
    offsets_sound_until: None,
    priority: None,
    gate_a: GateA { blocked_by: &[] },
    fields: &[Field {
        index: 0,
        sub: None,
        name: "Software",
        format: Some(Fmt::RemainderString),
        count: 1,
        mask: None,
        condition: None,
        raw_conv: None,
        omitted: Omitted::NONE,
        value_conv: None,
        print_conv: PrintConv::None,
        subdir: None,
        hook: &[],
        groups: TagGroups::NONE,
    }],
    variants: &[],
};

/// `Image::ExifTool::Casio::FaceInfo1` -- 12 fields,
/// 0 `_variants` groups (Step 23).
/// Generated from ExifTool's in-memory tag table. Do not edit by hand.
pub static CASIO_FACEINFO1: BinaryTable = BinaryTable {
    module: "Casio",
    table: "FaceInfo1",
    group0: "MakerNotes",
    group1: "Casio",
    group2: "Image",
    first_entry: 0,
    default_format: Fmt::Int8u,
    offsets_sound_until: None,
    priority: None,
    gate_a: GateA { blocked_by: &[] },
    fields: &[
        Field {
            index: 0,
            sub: None,
            name: "FacesDetected",
            format: None,
            count: 1,
            mask: None,
            condition: None,
            raw_conv: Some(RawConvEffect::SetMember {
                member: "FacesDetected",
            }),
            omitted: Omitted {
                value_conv: false,
                raw_conv: true,
                condition: false,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 1,
            sub: None,
            name: "FaceDetectFrameSize",
            format: Some(Fmt::Int16u),
            count: 2,
            mask: None,
            condition: Some(Cond::MemberCmp {
                member: "FacesDetected",
                op: CmpOp::Ge,
                value: 1,
            }),
            raw_conv: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: false,
                condition: true,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 13,
            sub: None,
            name: "Face1Position",
            format: Some(Fmt::Int16u),
            count: 4,
            mask: None,
            condition: Some(Cond::MemberCmp {
                member: "FacesDetected",
                op: CmpOp::Ge,
                value: 1,
            }),
            raw_conv: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: false,
                condition: true,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 124,
            sub: None,
            name: "Face2Position",
            format: Some(Fmt::Int16u),
            count: 4,
            mask: None,
            condition: Some(Cond::MemberCmp {
                member: "FacesDetected",
                op: CmpOp::Ge,
                value: 2,
            }),
            raw_conv: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: false,
                condition: true,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 235,
            sub: None,
            name: "Face3Position",
            format: Some(Fmt::Int16u),
            count: 4,
            mask: None,
            condition: Some(Cond::MemberCmp {
                member: "FacesDetected",
                op: CmpOp::Ge,
                value: 3,
            }),
            raw_conv: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: false,
                condition: true,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 346,
            sub: None,
            name: "Face4Position",
            format: Some(Fmt::Int16u),
            count: 4,
            mask: None,
            condition: Some(Cond::MemberCmp {
                member: "FacesDetected",
                op: CmpOp::Ge,
                value: 4,
            }),
            raw_conv: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: false,
                condition: true,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 457,
            sub: None,
            name: "Face5Position",
            format: Some(Fmt::Int16u),
            count: 4,
            mask: None,
            condition: Some(Cond::MemberCmp {
                member: "FacesDetected",
                op: CmpOp::Ge,
                value: 5,
            }),
            raw_conv: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: false,
                condition: true,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 568,
            sub: None,
            name: "Face6Position",
            format: Some(Fmt::Int16u),
            count: 4,
            mask: None,
            condition: Some(Cond::MemberCmp {
                member: "FacesDetected",
                op: CmpOp::Ge,
                value: 6,
            }),
            raw_conv: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: false,
                condition: true,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 679,
            sub: None,
            name: "Face7Position",
            format: Some(Fmt::Int16u),
            count: 4,
            mask: None,
            condition: Some(Cond::MemberCmp {
                member: "FacesDetected",
                op: CmpOp::Ge,
                value: 7,
            }),
            raw_conv: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: false,
                condition: true,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 790,
            sub: None,
            name: "Face8Position",
            format: Some(Fmt::Int16u),
            count: 4,
            mask: None,
            condition: Some(Cond::MemberCmp {
                member: "FacesDetected",
                op: CmpOp::Ge,
                value: 8,
            }),
            raw_conv: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: false,
                condition: true,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 901,
            sub: None,
            name: "Face9Position",
            format: Some(Fmt::Int16u),
            count: 4,
            mask: None,
            condition: Some(Cond::MemberCmp {
                member: "FacesDetected",
                op: CmpOp::Ge,
                value: 9,
            }),
            raw_conv: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: false,
                condition: true,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 1012,
            sub: None,
            name: "Face10Position",
            format: Some(Fmt::Int16u),
            count: 4,
            mask: None,
            condition: Some(Cond::MemberCmp {
                member: "FacesDetected",
                op: CmpOp::Ge,
                value: 10,
            }),
            raw_conv: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: false,
                condition: true,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
    ],
    variants: &[],
};

/// `Image::ExifTool::Casio::FaceInfo2` -- 13 fields,
/// 0 `_variants` groups (Step 23).
/// Generated from ExifTool's in-memory tag table. Do not edit by hand.
pub static CASIO_FACEINFO2: BinaryTable = BinaryTable {
    module: "Casio",
    table: "FaceInfo2",
    group0: "MakerNotes",
    group1: "Casio",
    group2: "Image",
    first_entry: 0,
    default_format: Fmt::Int8u,
    offsets_sound_until: None,
    priority: None,
    gate_a: GateA { blocked_by: &[] },
    fields: &[
        Field {
            index: 2,
            sub: None,
            name: "FacesDetected",
            format: None,
            count: 1,
            mask: None,
            condition: None,
            raw_conv: Some(RawConvEffect::SetMember {
                member: "FacesDetected",
            }),
            omitted: Omitted {
                value_conv: false,
                raw_conv: true,
                condition: false,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 4,
            sub: None,
            name: "FaceDetectFrameSize",
            format: Some(Fmt::Int16u),
            count: 2,
            mask: None,
            condition: Some(Cond::MemberCmp {
                member: "FacesDetected",
                op: CmpOp::Ge,
                value: 1,
            }),
            raw_conv: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: false,
                condition: true,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 8,
            sub: None,
            name: "FaceOrientation",
            format: None,
            count: 1,
            mask: None,
            condition: Some(Cond::MemberCmp {
                member: "FacesDetected",
                op: CmpOp::Ge,
                value: 1,
            }),
            raw_conv: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: false,
                condition: true,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[
                (0, "Horizontal (normal)"),
                (1, "Rotate 90 CW"),
                (2, "Rotate 270 CW"),
                (3, "Rotate 180"),
            ]),
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 24,
            sub: None,
            name: "Face1Position",
            format: Some(Fmt::Int16u),
            count: 4,
            mask: None,
            condition: Some(Cond::MemberCmp {
                member: "FacesDetected",
                op: CmpOp::Ge,
                value: 1,
            }),
            raw_conv: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: false,
                condition: true,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 76,
            sub: None,
            name: "Face2Position",
            format: Some(Fmt::Int16u),
            count: 4,
            mask: None,
            condition: Some(Cond::MemberCmp {
                member: "FacesDetected",
                op: CmpOp::Ge,
                value: 2,
            }),
            raw_conv: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: false,
                condition: true,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 128,
            sub: None,
            name: "Face3Position",
            format: Some(Fmt::Int16u),
            count: 4,
            mask: None,
            condition: Some(Cond::MemberCmp {
                member: "FacesDetected",
                op: CmpOp::Ge,
                value: 3,
            }),
            raw_conv: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: false,
                condition: true,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 180,
            sub: None,
            name: "Face4Position",
            format: Some(Fmt::Int16u),
            count: 4,
            mask: None,
            condition: Some(Cond::MemberCmp {
                member: "FacesDetected",
                op: CmpOp::Ge,
                value: 4,
            }),
            raw_conv: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: false,
                condition: true,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 232,
            sub: None,
            name: "Face5Position",
            format: Some(Fmt::Int16u),
            count: 4,
            mask: None,
            condition: Some(Cond::MemberCmp {
                member: "FacesDetected",
                op: CmpOp::Ge,
                value: 5,
            }),
            raw_conv: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: false,
                condition: true,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 284,
            sub: None,
            name: "Face6Position",
            format: Some(Fmt::Int16u),
            count: 4,
            mask: None,
            condition: Some(Cond::MemberCmp {
                member: "FacesDetected",
                op: CmpOp::Ge,
                value: 6,
            }),
            raw_conv: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: false,
                condition: true,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 336,
            sub: None,
            name: "Face7Position",
            format: Some(Fmt::Int16u),
            count: 4,
            mask: None,
            condition: Some(Cond::MemberCmp {
                member: "FacesDetected",
                op: CmpOp::Ge,
                value: 7,
            }),
            raw_conv: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: false,
                condition: true,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 388,
            sub: None,
            name: "Face8Position",
            format: Some(Fmt::Int16u),
            count: 4,
            mask: None,
            condition: Some(Cond::MemberCmp {
                member: "FacesDetected",
                op: CmpOp::Ge,
                value: 8,
            }),
            raw_conv: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: false,
                condition: true,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 440,
            sub: None,
            name: "Face9Position",
            format: Some(Fmt::Int16u),
            count: 4,
            mask: None,
            condition: Some(Cond::MemberCmp {
                member: "FacesDetected",
                op: CmpOp::Ge,
                value: 9,
            }),
            raw_conv: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: false,
                condition: true,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 492,
            sub: None,
            name: "Face10Position",
            format: Some(Fmt::Int16u),
            count: 4,
            mask: None,
            condition: Some(Cond::MemberCmp {
                member: "FacesDetected",
                op: CmpOp::Ge,
                value: 10,
            }),
            raw_conv: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: false,
                condition: true,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
    ],
    variants: &[],
};

/// `Image::ExifTool::Casio::QVCI` -- 5 fields,
/// 0 `_variants` groups (Step 23).
/// Generated from ExifTool's in-memory tag table. Do not edit by hand.
pub static CASIO_QVCI: BinaryTable = BinaryTable {
    module: "Casio",
    table: "QVCI",
    group0: "MakerNotes",
    group1: "Casio",
    group2: "Camera",
    first_entry: 0,
    default_format: Fmt::Int8u,
    offsets_sound_until: None,
    priority: None,
    gate_a: GateA { blocked_by: &[] },
    fields: &[
        Field {
            index: 44,
            sub: None,
            name: "CasioQuality",
            format: None,
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[
                (1, "Economy"),
                (2, "Normal"),
                (3, "Fine"),
                (4, "Super Fine"),
            ]),
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 77,
            sub: None,
            name: "DateTimeOriginal",
            format: Some(Fmt::Str(20)),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted {
                value_conv: true,
                raw_conv: false,
                condition: false,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            value_conv: None,
            print_conv: PrintConv::Expr(ExprId::SelfConvertDateTimeVal7455B8),
            subdir: None,
            hook: &[],
            groups: TagGroups {
                g0: None,
                g1: None,
                g2: Some("Time"),
            },
        },
        Field {
            index: 98,
            sub: None,
            name: "ModelType",
            format: Some(Fmt::Str(7)),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 114,
            sub: None,
            name: "ManufactureIndex",
            format: Some(Fmt::Str(9)),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 124,
            sub: None,
            name: "ManufactureCode",
            format: Some(Fmt::Str(9)),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
    ],
    variants: &[],
};
