//! ExifTool `EXE` ProcessBinaryData tables, generated from ExifTool
//! 13.59's own Perl hashes -- one file per module; `mod.rs` beside this
//! file is the hub that declares and re-exports it.
//!
//! DO NOT EDIT. Regenerate with `just regen-tables` (see `mod.rs`).

#![allow(clippy::unreadable_literal, clippy::too_many_lines, unused_parens)]

// Everything a table literal names -- the schema types, `ExprId`, the
// `cond`/`subdir`/`ifd_schema` imports -- is in scope in the hub, and a glob
// import of the parent module brings its private imports along (RFC 1560).
#[allow(unused_imports)]
use super::*;

/// `Image::ExifTool::EXE::AR` -- 1 fields,
/// 0 `_variants` groups (Step 23).
/// Generated from ExifTool's in-memory tag table. Do not edit by hand.
pub static EXE_AR: BinaryTable = BinaryTable {
    module: "EXE",
    table: "AR",
    group0: "EXE",
    group1: "EXE",
    group2: "Other",
    first_entry: 0,
    default_format: Fmt::Int8u,
    offsets_sound_until: None,
    priority: None,
    gate_a: GateA { blocked_by: &[] },
    fields: &[Field {
        index: 16,
        sub: None,
        name: "CreateDate",
        format: Some(Fmt::Str(12)),
        count: 1,
        mask: None,
        condition: None,
        raw_conv: None,
        omitted: Omitted {
            value_conv: true,
            raw_conv: false,
            condition: false,
            hook: false,
            subdirectory: false,
            print_conv: false,
        },
        value_conv: None,
        print_conv: PrintConv::Expr(ExprId::SelfConvertDateTimeVal7455B8),
        subdir: None,
        hook: &[],
        groups: TagGroups {
            g0: None,
            g1: None,
            g2: Some("Time"),
        },
    }],
    variants: &[],
};

/// `Image::ExifTool::EXE::CHM` -- 2 fields,
/// 0 `_variants` groups (Step 23).
/// Generated from ExifTool's in-memory tag table. Do not edit by hand.
pub static EXE_CHM: BinaryTable = BinaryTable {
    module: "EXE",
    table: "CHM",
    group0: "EXE",
    group1: "EXE",
    group2: "Other",
    first_entry: 0,
    default_format: Fmt::Int32u,
    offsets_sound_until: None,
    priority: None,
    gate_a: GateA { blocked_by: &[] },
    fields: &[
        Field {
            index: 1,
            sub: None,
            name: "CHMVersion",
            format: None,
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 5,
            sub: None,
            name: "LanguageCode",
            format: None,
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: Some(ExprId::Sprintf4XVal9AA0DB),
            print_conv: PrintConv::StrEnum(&[
                ("0000", "Neutral"),
                ("007F", "Invariant"),
                ("0400", "Process default"),
                ("0401", "Arabic"),
                ("0402", "Bulgarian"),
                ("0403", "Catalan"),
                ("0404", "Chinese (Traditional)"),
                ("0405", "Czech"),
                ("0406", "Danish"),
                ("0407", "German"),
                ("0408", "Greek"),
                ("0409", "English (U.S.)"),
                ("040A", "Spanish (Castilian)"),
                ("040B", "Finnish"),
                ("040C", "French"),
                ("040D", "Hebrew"),
                ("040E", "Hungarian"),
                ("040F", "Icelandic"),
                ("0410", "Italian"),
                ("0411", "Japanese"),
                ("0412", "Korean"),
                ("0413", "Dutch"),
                ("0414", "Norwegian (Bokml)"),
                ("0415", "Polish"),
                ("0416", "Portuguese (Brazilian)"),
                ("0417", "Rhaeto-Romanic"),
                ("0418", "Romanian"),
                ("0419", "Russian"),
                ("041A", "Croato-Serbian (Latin)"),
                ("041B", "Slovak"),
                ("041C", "Albanian"),
                ("041D", "Swedish"),
                ("041E", "Thai"),
                ("041F", "Turkish"),
                ("0420", "Urdu"),
                ("0421", "Indonesian"),
                ("0422", "Ukrainian"),
                ("0423", "Belarusian"),
                ("0424", "Slovenian"),
                ("0425", "Estonian"),
                ("0426", "Latvian"),
                ("0427", "Lithuanian"),
                ("0428", "Maori"),
                ("0429", "Farsi"),
                ("042a", "Vietnamese"),
                ("042b", "Armenian"),
                ("042c", "Azeri"),
                ("042d", "Basque"),
                ("042e", "Sorbian"),
                ("042f", "Macedonian"),
                ("0430", "Sutu"),
                ("0431", "Tsonga"),
                ("0432", "Tswana"),
                ("0433", "Venda"),
                ("0434", "Xhosa"),
                ("0435", "Zulu"),
                ("0436", "Afrikaans"),
                ("0437", "Georgian"),
                ("0438", "Faeroese"),
                ("0439", "Hindi"),
                ("043a", "Maltese"),
                ("043b", "Saami"),
                ("043c", "Gaelic"),
                ("043e", "Malay"),
                ("043f", "Kazak"),
                ("0440", "Kyrgyz"),
                ("0441", "Swahili"),
                ("0443", "Uzbek"),
                ("0444", "Tatar"),
                ("0445", "Bengali"),
                ("0446", "Punjabi"),
                ("0447", "Gujarati"),
                ("0448", "Oriya"),
                ("0449", "Tamil"),
                ("044a", "Telugu"),
                ("044b", "Kannada"),
                ("044c", "Malayalam"),
                ("044d", "Assamese"),
                ("044e", "Marathi"),
                ("044f", "Sanskrit"),
                ("0450", "Mongolian"),
                ("0456", "Galician"),
                ("0457", "Konkani"),
                ("0458", "Manipuri"),
                ("0459", "Sindhi"),
                ("045a", "Syriac"),
                ("0460", "Kashmiri"),
                ("0461", "Nepali"),
                ("0465", "Divehi"),
                ("047f", "Invariant"),
                ("048f", "Esperanto"),
                ("0490", "Walon"),
                ("0491", "Cornish"),
                ("0492", "Welsh"),
                ("0493", "Breton"),
                ("0800", "Neutral 2"),
                ("0804", "Chinese (Simplified)"),
                ("0807", "German (Swiss)"),
                ("0809", "English (British)"),
                ("080A", "Spanish (Mexican)"),
                ("080C", "French (Belgian)"),
                ("0810", "Italian (Swiss)"),
                ("0813", "Dutch (Belgian)"),
                ("0814", "Norwegian (Nynorsk)"),
                ("0816", "Portuguese"),
                ("081A", "Serbo-Croatian (Cyrillic)"),
                ("0C07", "German (Austrian)"),
                ("0C09", "English (Australian)"),
                ("0C0A", "Spanish (Modern)"),
                ("0C0C", "French (Canadian)"),
                ("1009", "English (Canadian)"),
                ("100C", "French (Swiss)"),
            ]),
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
    ],
    variants: &[],
};

/// `Image::ExifTool::EXE::DebugNB10` -- 4 fields,
/// 0 `_variants` groups (Step 23).
/// Generated from ExifTool's in-memory tag table. Do not edit by hand.
pub static EXE_DEBUGNB10: BinaryTable = BinaryTable {
    module: "EXE",
    table: "DebugNB10",
    group0: "EXE",
    group1: "EXE",
    group2: "Other",
    first_entry: 0,
    default_format: Fmt::Int8u,
    offsets_sound_until: None,
    priority: None,
    gate_a: GateA { blocked_by: &[] },
    fields: &[
        Field {
            index: 0,
            sub: None,
            name: "PDBModifyDate",
            format: Some(Fmt::Int32u),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: Some(ExprId::ConvertUnixTimeVal15C09AC),
            print_conv: PrintConv::Expr(ExprId::SelfConvertDateTimeVal7455B8),
            subdir: None,
            hook: &[],
            groups: TagGroups {
                g0: Some("EXE"),
                g1: Some("EXE"),
                g2: Some("Time"),
            },
        },
        Field {
            index: 8,
            sub: None,
            name: "PDBCreateDate",
            format: Some(Fmt::Int32u),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: Some(ExprId::ConvertUnixTimeVal15C09AC),
            print_conv: PrintConv::Expr(ExprId::SelfConvertDateTimeVal7455B8),
            subdir: None,
            hook: &[],
            groups: TagGroups {
                g0: Some("EXE"),
                g1: Some("EXE"),
                g2: Some("Time"),
            },
        },
        Field {
            index: 12,
            sub: None,
            name: "PDBAge",
            format: Some(Fmt::Int32u),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 16,
            sub: None,
            name: "PDBFileName",
            format: Some(Fmt::RemainderString),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
    ],
    variants: &[],
};

/// `Image::ExifTool::EXE::DebugRSDS` -- 3 fields,
/// 0 `_variants` groups (Step 23).
/// Generated from ExifTool's in-memory tag table. Do not edit by hand.
pub static EXE_DEBUGRSDS: BinaryTable = BinaryTable {
    module: "EXE",
    table: "DebugRSDS",
    group0: "EXE",
    group1: "EXE",
    group2: "Other",
    first_entry: 0,
    default_format: Fmt::Int8u,
    offsets_sound_until: None,
    priority: None,
    gate_a: GateA { blocked_by: &[] },
    fields: &[
        Field {
            index: 0,
            sub: None,
            name: "PDBModifyDate",
            format: Some(Fmt::Int32u),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: Some(ExprId::ConvertUnixTimeVal15C09AC),
            print_conv: PrintConv::Expr(ExprId::SelfConvertDateTimeVal7455B8),
            subdir: None,
            hook: &[],
            groups: TagGroups {
                g0: Some("EXE"),
                g1: Some("EXE"),
                g2: Some("Time"),
            },
        },
        Field {
            index: 20,
            sub: None,
            name: "PDBAge",
            format: Some(Fmt::Int32u),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 24,
            sub: None,
            name: "PDBFileName",
            format: Some(Fmt::RemainderString),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
    ],
    variants: &[],
};

/// `Image::ExifTool::EXE::ELF` -- 4 fields,
/// 0 `_variants` groups (Step 23).
/// Generated from ExifTool's in-memory tag table. Do not edit by hand.
pub static EXE_ELF: BinaryTable = BinaryTable {
    module: "EXE",
    table: "ELF",
    group0: "EXE",
    group1: "EXE",
    group2: "Other",
    first_entry: 0,
    default_format: Fmt::Int8u,
    offsets_sound_until: None,
    priority: None,
    gate_a: GateA { blocked_by: &[] },
    fields: &[
        Field {
            index: 4,
            sub: None,
            name: "CPUArchitecture",
            format: None,
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[(1, "32 bit"), (2, "64 bit")]),
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 5,
            sub: None,
            name: "CPUByteOrder",
            format: None,
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[(1, "Little endian"), (2, "Big endian")]),
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 16,
            sub: None,
            name: "ObjectFileType",
            format: Some(Fmt::Int16u),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[
                (0, "None"),
                (1, "Relocatable file"),
                (2, "Executable file"),
                (3, "Shared object file"),
                (4, "Core file"),
            ]),
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 18,
            sub: None,
            name: "CPUType",
            format: Some(Fmt::Int16u),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[
                (0, "None"),
                (1, "AT&T WE 32100"),
                (2, "SPARC"),
                (3, "i386"),
                (4, "Motorola 68000"),
                (5, "Motorola 88000"),
                (6, "i486"),
                (7, "i860"),
                (8, "MIPS R3000"),
                (9, "IBM System/370"),
                (10, "MIPS R4000"),
                (15, "HP PA-RISC"),
                (18, "Sun v8plus"),
                (19, "Intel 80960"),
                (20, "PowerPC"),
                (21, "PowerPC 64-bit"),
                (22, "IBM S/390"),
                (23, "Cell BE SPU"),
                (36, "NEC V800"),
                (37, "Fujitsu FR20"),
                (38, "TRW RH-32"),
                (39, "Motorola RCE"),
                (40, "Arm (up to Armv7/AArch32)"),
                (41, "Digital Alpha"),
                (42, "SuperH"),
                (43, "SPARC v9 64-bit"),
                (44, "Siemens TriCore"),
                (45, "Argonaut RISC Core"),
                (46, "Renesas H8/300,300H,H8S"),
                (47, "Hitachi H8/300H"),
                (48, "Hitachi H8S"),
                (49, "Hitachi H8/500"),
                (50, "HP/Intel IA-64"),
                (51, "Stanford MIPS-X"),
                (52, "Motorola ColdFire"),
                (53, "Motorola M68HC12"),
                (54, "Fujitsu MMA Multimedia Accelerator"),
                (55, "Siemens PCP"),
                (56, "Sony nCPU embedded RISC processor"),
                (57, "Denso NDR1 microprocessor"),
                (58, "Motorola Star*Core processor"),
                (59, "Toyota ME16 processor"),
                (60, "STMicroelectronics ST100 processor"),
                (61, "Advanced Logic Corp. TinyJ embedded processor family"),
                (62, "AMD x86-64"),
                (63, "Sony DSP Processor"),
                (64, "Digital Equipment Corp. PDP-10"),
                (65, "Digital Equipment Corp. PDP-11"),
                (66, "Siemens FX66 microcontroller"),
                (67, "STMicroelectronics ST9+ 8/16 bit microcontroller"),
                (68, "STMicroelectronics ST7 8-bit microcontroller"),
                (69, "Motorola MC68HC16 Microcontroller"),
                (70, "Motorola MC68HC11 Microcontroller"),
                (71, "Motorola MC68HC08 Microcontroller"),
                (72, "Motorola MC68HC05 Microcontroller"),
                (73, "Silicon Graphics SVx"),
                (74, "STMicroelectronics ST19 8-bit microcontroller"),
                (75, "Digital VAX"),
                (76, "Axis Communications 32-bit embedded processor"),
                (77, "Infineon Technologies 32-bit embedded processor"),
                (78, "Element 14 64-bit DSP Processor"),
                (79, "LSI Logic 16-bit DSP Processor"),
                (87, "NEC v850"),
                (88, "Renesas M32R"),
                (140, "TMS320C6000 Family"),
                (175, "MCST Elbrus e2k"),
                (183, "Arm 64-bits (Armv8/AArch64)"),
                (220, "Zilog Z80"),
                (243, "RISC-V"),
                (247, "Berkeley Packet Filter"),
                (257, "WDC 65C816"),
                (21569, "Fujitsu FR-V"),
                (36902, "Alpha"),
                (36929, "m32r (old)"),
                (36992, "v850 (old)"),
                (41872, "S/390 (old)"),
            ]),
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
    ],
    variants: &[],
};

/// `Image::ExifTool::EXE::Main` -- 13 fields,
/// 0 `_variants` groups (Step 23).
/// Generated from ExifTool's in-memory tag table. Do not edit by hand.
pub static EXE_MAIN: BinaryTable = BinaryTable {
    module: "EXE",
    table: "Main",
    group0: "EXE",
    group1: "EXE",
    group2: "Other",
    first_entry: 0,
    default_format: Fmt::Int16u,
    offsets_sound_until: None,
    priority: None,
    gate_a: GateA { blocked_by: &[] },
    fields: &[
        Field {
            index: 0,
            sub: None,
            name: "MachineType",
            format: None,
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::PartialEnumInt {
                exact: &[
                    (0, "Unknown"),
                    (1, "Target host"),
                    (332, "Intel 386 or later, and compatibles"),
                    (333, "Intel i860"),
                    (354, "MIPS R3000"),
                    (358, "MIPS little endian (R4000)"),
                    (360, "MIPS R10000"),
                    (361, "MIPS little endian WCI v2"),
                    (387, "Alpha AXP (old)"),
                    (388, "Alpha AXP"),
                    (418, "Hitachi SH3"),
                    (419, "Hitachi SH3 DSP"),
                    (420, "Hitachi SH3E"),
                    (422, "Hitachi SH4"),
                    (424, "Hitachi SH5"),
                    (448, "ARM little endian"),
                    (450, "Thumb"),
                    (452, "Thumb 2 little endian"),
                    (467, "Matsushita AM33"),
                    (496, "PowerPC little endian"),
                    (497, "PowerPC with floating point support"),
                    (512, "Intel IA64"),
                    (614, "MIPS16"),
                    (616, "Motorola 68000 series"),
                    (644, "Alpha AXP 64-bit"),
                    (870, "MIPS with FPU"),
                    (1126, "MIPS16 with FPU"),
                    (1312, "Infineon Tricore"),
                    (3311, "CEF"),
                    (3772, "EFI Byte Code"),
                    (14948, "Compiled Hybrid PE"),
                    (20530, "RISC-V 32-bit"),
                    (20580, "RISC-V 64-bit"),
                    (20776, "RISC-V 128-bit"),
                    (25138, "LoongArch 32-bit"),
                    (25188, "LoongArch 64-bit"),
                    (34404, "AMD AMD64"),
                    (36929, "Mitsubishi M32R little endian"),
                    (43620, "ARM64 little endian"),
                    (49390, "clr pure MSIL"),
                    (60448, "Dotnet 0xEC20"),
                ],
                other: None,
                print_hex: true,
            },
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 2,
            sub: None,
            name: "TimeStamp",
            format: Some(Fmt::Int32u),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: Some(ExprId::ConvertUnixTimeVal15C09AC),
            print_conv: PrintConv::Expr(ExprId::SelfConvertDateTimeVal7455B8),
            subdir: None,
            hook: &[],
            groups: TagGroups {
                g0: Some("EXE"),
                g1: Some("EXE"),
                g2: Some("Time"),
            },
        },
        Field {
            index: 9,
            sub: None,
            name: "ImageFileCharacteristics",
            format: None,
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::Bitmask {
                exact: &[],
                bits: &[
                    (0, "No relocs"),
                    (1, "Executable"),
                    (2, "No line numbers"),
                    (3, "No symbols"),
                    (4, "Aggressive working-set trim"),
                    (5, "Large address aware"),
                    (7, "Bytes reversed lo"),
                    (8, "32-bit"),
                    (9, "No debug"),
                    (10, "Removable run from swap"),
                    (11, "Net run from swap"),
                    (12, "System file"),
                    (13, "DLL"),
                    (14, "Uniprocessor only"),
                    (15, "Bytes reversed hi"),
                ],
            },
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 10,
            sub: None,
            name: "PEType",
            format: None,
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::PartialEnumInt {
                exact: &[(263, "ROM Image"), (267, "PE32"), (523, "PE32+")],
                other: None,
                print_hex: true,
            },
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 11,
            sub: None,
            name: "LinkerVersion",
            format: Some(Fmt::Int8u),
            count: 2,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted {
                value_conv: true,
                raw_conv: false,
                condition: false,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 12,
            sub: None,
            name: "CodeSize",
            format: Some(Fmt::Int32u),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 14,
            sub: None,
            name: "InitializedDataSize",
            format: Some(Fmt::Int32u),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 16,
            sub: None,
            name: "UninitializedDataSize",
            format: Some(Fmt::Int32u),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 18,
            sub: None,
            name: "EntryPoint",
            format: Some(Fmt::Int32u),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::Expr(ExprId::Sprintf0x4xVal4F789C),
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 30,
            sub: None,
            name: "OSVersion",
            format: Some(Fmt::Int16u),
            count: 2,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted {
                value_conv: true,
                raw_conv: false,
                condition: false,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 32,
            sub: None,
            name: "ImageVersion",
            format: Some(Fmt::Int16u),
            count: 2,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted {
                value_conv: true,
                raw_conv: false,
                condition: false,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 34,
            sub: None,
            name: "SubsystemVersion",
            format: Some(Fmt::Int16u),
            count: 2,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted {
                value_conv: true,
                raw_conv: false,
                condition: false,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 44,
            sub: None,
            name: "Subsystem",
            format: None,
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[
                (0, "Unknown"),
                (1, "Native"),
                (2, "Windows GUI"),
                (3, "Windows command line"),
                (5, "OS/2 command line"),
                (7, "POSIX command line"),
                (9, "Windows CE GUI"),
                (10, "EFI application"),
                (11, "EFI boot service"),
                (12, "EFI runtime driver"),
                (13, "EFI ROM"),
                (14, "XBOX"),
            ]),
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
    ],
    variants: &[],
};

/// `Image::ExifTool::EXE::PEF` -- 3 fields,
/// 0 `_variants` groups (Step 23).
/// Generated from ExifTool's in-memory tag table. Do not edit by hand.
pub static EXE_PEF: BinaryTable = BinaryTable {
    module: "EXE",
    table: "PEF",
    group0: "EXE",
    group1: "EXE",
    group2: "Other",
    first_entry: 0,
    default_format: Fmt::Int32u,
    offsets_sound_until: None,
    priority: None,
    gate_a: GateA { blocked_by: &[] },
    fields: &[
        Field {
            index: 2,
            sub: None,
            name: "CPUArchitecture",
            format: Some(Fmt::Undef(4)),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::StrEnum(&[("m68k", "68000"), ("pwpc", "PowerPC")]),
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 3,
            sub: None,
            name: "PEFVersion",
            format: None,
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 4,
            sub: None,
            name: "TimeStamp",
            format: None,
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: Some(ExprId::ConvertUnixTimeVal6636517243600B0FEDA),
            print_conv: PrintConv::Expr(ExprId::SelfConvertDateTimeVal7455B8),
            subdir: None,
            hook: &[],
            groups: TagGroups {
                g0: None,
                g1: None,
                g2: Some("Time"),
            },
        },
    ],
    variants: &[],
};

/// `Image::ExifTool::EXE::PEVersion` -- 7 fields,
/// 0 `_variants` groups (Step 23).
/// Generated from ExifTool's in-memory tag table. Do not edit by hand.
pub static EXE_PEVERSION: BinaryTable = BinaryTable {
    module: "EXE",
    table: "PEVersion",
    group0: "EXE",
    group1: "EXE",
    group2: "Other",
    first_entry: 0,
    default_format: Fmt::Int32u,
    offsets_sound_until: None,
    priority: None,
    gate_a: GateA { blocked_by: &[] },
    fields: &[
        Field {
            index: 2,
            sub: None,
            name: "FileVersionNumber",
            format: Some(Fmt::Int16u),
            count: 4,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: Some(ExprId::MyASplitValA1A0A3A230645B),
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 4,
            sub: None,
            name: "ProductVersionNumber",
            format: Some(Fmt::Int16u),
            count: 4,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: Some(ExprId::MyASplitValA1A0A3A230645B),
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 6,
            sub: None,
            name: "FileFlagsMask",
            format: None,
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::Expr(ExprId::Sprintf0x4xVal8F8283),
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 7,
            sub: None,
            name: "FileFlags",
            format: None,
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::Bitmask {
                exact: &[],
                bits: &[
                    (0, "Debug"),
                    (1, "Pre-release"),
                    (2, "Patched"),
                    (3, "Private build"),
                    (4, "Info inferred"),
                    (5, "Special build"),
                ],
            },
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 8,
            sub: None,
            name: "FileOS",
            format: None,
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::PartialEnumInt {
                exact: &[
                    (1, "Win16"),
                    (2, "PM-16"),
                    (3, "PM-32"),
                    (4, "Win32"),
                    (65536, "DOS"),
                    (65537, "Windows 16-bit"),
                    (65540, "Windows 32-bit"),
                    (131072, "OS/2 16-bit"),
                    (131074, "OS/2 16-bit PM-16"),
                    (196608, "OS/2 32-bit"),
                    (196611, "OS/2 32-bit PM-32"),
                    (262144, "Windows NT"),
                    (262148, "Windows NT 32-bit"),
                ],
                other: None,
                print_hex: true,
            },
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 9,
            sub: None,
            name: "ObjectFileType",
            format: None,
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[
                (0, "Unknown"),
                (1, "Executable application"),
                (2, "Dynamic link library"),
                (3, "Driver"),
                (4, "Font"),
                (5, "VxD"),
                (7, "Static library"),
            ]),
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 10,
            sub: None,
            name: "FileSubtype",
            format: None,
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
    ],
    variants: &[],
};
