//! ExifTool `FLAC` ProcessBinaryData tables, generated from ExifTool
//! 13.59's own Perl hashes -- one file per module; `mod.rs` beside this
//! file is the hub that declares and re-exports it.
//!
//! DO NOT EDIT. Regenerate with `just regen-tables` (see `mod.rs`).

#![allow(clippy::unreadable_literal, clippy::too_many_lines, unused_parens)]

// Everything a table literal names -- the schema types, `ExprId`, the
// `cond`/`subdir`/`ifd_schema` imports -- is in scope in the hub, and a glob
// import of the parent module brings its private imports along (RFC 1560).
#[allow(unused_imports)]
use super::*;

/// `Image::ExifTool::FLAC::Picture` -- 8 fields,
/// 0 `_variants` groups (Step 23).
/// Generated from ExifTool's in-memory tag table. Do not edit by hand.
pub static FLAC_PICTURE: BinaryTable = BinaryTable {
    module: "FLAC",
    table: "Picture",
    group0: "FLAC",
    group1: "FLAC",
    group2: "Image",
    first_entry: 0,
    default_format: Fmt::Int32u,
    offsets_sound_until: Some(1),
    priority: None,
    gate_a: GateA {
        blocked_by: &[
            ("tag_fmt_unsupported", 1),
            ("tag_var_format", 2),
            ("offsets_sound_until", 1),
        ],
    },
    fields: &[
        Field {
            index: 0,
            sub: None,
            name: "PictureType",
            format: None,
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[
                (0, "Other"),
                (1, "32x32 PNG Icon"),
                (2, "Other Icon"),
                (3, "Front Cover"),
                (4, "Back Cover"),
                (5, "Leaflet"),
                (6, "Media"),
                (7, "Lead Artist"),
                (8, "Artist"),
                (9, "Conductor"),
                (10, "Band"),
                (11, "Composer"),
                (12, "Lyricist"),
                (13, "Recording Studio or Location"),
                (14, "Recording Session"),
                (15, "Performance"),
                (16, "Capture from Movie or Video"),
                (17, "Bright(ly) Colored Fish"),
                (18, "Illustration"),
                (19, "Band Logo"),
                (20, "Publisher Logo"),
            ]),
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 1,
            sub: None,
            name: "PictureMIMEType",
            format: Some(Fmt::Var(VarFmt {
                spelling: "var_pstr32",
                kind: VarKind::PStr32,
            })),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 2,
            sub: None,
            name: "PictureDescription",
            format: Some(Fmt::Var(VarFmt {
                spelling: "var_pstr32",
                kind: VarKind::PStr32,
            })),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted {
                value_conv: true,
                raw_conv: false,
                condition: false,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 3,
            sub: None,
            name: "PictureWidth",
            format: None,
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 4,
            sub: None,
            name: "PictureHeight",
            format: None,
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 5,
            sub: None,
            name: "PictureBitsPerPixel",
            format: None,
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 6,
            sub: None,
            name: "PictureIndexedColors",
            format: None,
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 7,
            sub: None,
            name: "PictureLength",
            format: None,
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
    ],
    variants: &[],
};
