//! ExifTool `FujiFilm` ProcessBinaryData tables, generated from ExifTool
//! 13.59's own Perl hashes -- one file per module; `mod.rs` beside this
//! file is the hub that declares and re-exports it.
//!
//! DO NOT EDIT. Regenerate with `just regen-tables` (see `mod.rs`).

#![allow(clippy::unreadable_literal, clippy::too_many_lines, unused_parens)]

// Everything a table literal names -- the schema types, `ExprId`, the
// `cond`/`subdir`/`ifd_schema` imports -- is in scope in the hub, and a glob
// import of the parent module brings its private imports along (RFC 1560).
#[allow(unused_imports)]
use super::*;

/// `Image::ExifTool::FujiFilm::AFCSettings` -- 4 fields,
/// 0 `_variants` groups (Step 23).
/// Generated from ExifTool's in-memory tag table. Do not edit by hand.
pub static FUJIFILM_AFCSETTINGS: BinaryTable = BinaryTable {
    module: "FujiFilm",
    table: "AFCSettings",
    group0: "MakerNotes",
    group1: "FujiFilm",
    group2: "Camera",
    first_entry: 0,
    default_format: Fmt::Int32u,
    offsets_sound_until: None,
    priority: None,
    gate_a: GateA {
        blocked_by: &[("other_unregistered", 1)],
    },
    fields: &[
        Field {
            index: 0,
            sub: None,
            name: "AF-CSetting",
            format: None,
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 0,
            sub: Some(1),
            name: "AF-CTrackingSensitivity",
            format: None,
            count: 1,
            mask: Some(Mask {
                bits: 0xf,
                shift: 0,
            }),
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 0,
            sub: Some(2),
            name: "AF-CSpeedTrackingSensitivity",
            format: None,
            count: 1,
            mask: Some(Mask {
                bits: 0xf0,
                shift: 4,
            }),
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 0,
            sub: Some(3),
            name: "AF-CZoneAreaSwitching",
            format: None,
            count: 1,
            mask: Some(Mask {
                bits: 0xf00,
                shift: 8,
            }),
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[(0, "Front"), (1, "Auto"), (2, "Center")]),
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
    ],
    variants: &[],
};

/// `Image::ExifTool::FujiFilm::DriveSettings` -- 2 fields,
/// 0 `_variants` groups (Step 23).
/// Generated from ExifTool's in-memory tag table. Do not edit by hand.
pub static FUJIFILM_DRIVESETTINGS: BinaryTable = BinaryTable {
    module: "FujiFilm",
    table: "DriveSettings",
    group0: "MakerNotes",
    group1: "FujiFilm",
    group2: "Camera",
    first_entry: 0,
    default_format: Fmt::Int32u,
    offsets_sound_until: None,
    priority: None,
    gate_a: GateA {
        blocked_by: &[("other_unregistered", 1)],
    },
    fields: &[
        Field {
            index: 0,
            sub: Some(1),
            name: "DriveMode",
            format: None,
            count: 1,
            mask: Some(Mask {
                bits: 0xff,
                shift: 0,
            }),
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[
                (0, "Single"),
                (1, "Continuous Low"),
                (2, "Continuous High"),
            ]),
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 0,
            sub: Some(2),
            name: "DriveSpeed",
            format: None,
            count: 1,
            mask: Some(Mask {
                bits: 0xff000000,
                shift: 24,
            }),
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
    ],
    variants: &[],
};

/// `Image::ExifTool::FujiFilm::FFMV` -- 1 fields,
/// 0 `_variants` groups (Step 23).
/// Generated from ExifTool's in-memory tag table. Do not edit by hand.
pub static FUJIFILM_FFMV: BinaryTable = BinaryTable {
    module: "FujiFilm",
    table: "FFMV",
    group0: "MakerNotes",
    group1: "FujiFilm",
    group2: "Camera",
    first_entry: 0,
    default_format: Fmt::Int8u,
    offsets_sound_until: None,
    priority: None,
    gate_a: GateA { blocked_by: &[] },
    fields: &[Field {
        index: 0,
        sub: None,
        name: "MovieStreamName",
        format: Some(Fmt::Str(34)),
        count: 1,
        mask: None,
        condition: None,
        raw_conv: None,
        omitted: Omitted::NONE,
        value_conv: None,
        print_conv: PrintConv::None,
        subdir: None,
        hook: &[],
        groups: TagGroups::NONE,
    }],
    variants: &[],
};

/// `Image::ExifTool::FujiFilm::FocusSettings` -- 5 fields,
/// 0 `_variants` groups (Step 23).
/// Generated from ExifTool's in-memory tag table. Do not edit by hand.
pub static FUJIFILM_FOCUSSETTINGS: BinaryTable = BinaryTable {
    module: "FujiFilm",
    table: "FocusSettings",
    group0: "MakerNotes",
    group1: "FujiFilm",
    group2: "Camera",
    first_entry: 0,
    default_format: Fmt::Int32u,
    offsets_sound_until: None,
    priority: None,
    gate_a: GateA {
        blocked_by: &[("other_unregistered", 1)],
    },
    fields: &[
        Field {
            index: 0,
            sub: Some(1),
            name: "FocusMode2",
            format: None,
            count: 1,
            mask: Some(Mask {
                bits: 0xf,
                shift: 0,
            }),
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[(0, "AF-M"), (1, "AF-S"), (2, "AF-C")]),
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 0,
            sub: Some(2),
            name: "PreAF",
            format: None,
            count: 1,
            mask: Some(Mask {
                bits: 0xf0,
                shift: 4,
            }),
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[(0, "Off"), (1, "On")]),
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 0,
            sub: Some(3),
            name: "AFAreaMode",
            format: None,
            count: 1,
            mask: Some(Mask {
                bits: 0xf00,
                shift: 8,
            }),
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[
                (0, "Single Point"),
                (1, "Zone"),
                (2, "Wide/Tracking"),
            ]),
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 0,
            sub: Some(4),
            name: "AFAreaPointSize",
            format: None,
            count: 1,
            mask: Some(Mask {
                bits: 0xf000,
                shift: 12,
            }),
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::PartialEnumInt {
                exact: &[(0, "n/a")],
                other: Some(OtherId::Identity),
                print_hex: false,
            },
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 0,
            sub: Some(5),
            name: "AFAreaZoneSize",
            format: None,
            count: 1,
            mask: Some(Mask {
                bits: 0xff0000,
                shift: 16,
            }),
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
    ],
    variants: &[],
};

/// `Image::ExifTool::FujiFilm::MOV` -- 5 fields,
/// 0 `_variants` groups (Step 23).
/// Generated from ExifTool's in-memory tag table. Do not edit by hand.
pub static FUJIFILM_MOV: BinaryTable = BinaryTable {
    module: "FujiFilm",
    table: "MOV",
    group0: "MakerNotes",
    group1: "FujiFilm",
    group2: "Camera",
    first_entry: 0,
    default_format: Fmt::Int8u,
    offsets_sound_until: None,
    priority: None,
    gate_a: GateA { blocked_by: &[] },
    fields: &[
        Field {
            index: 0,
            sub: None,
            name: "Make",
            format: Some(Fmt::Str(24)),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 24,
            sub: None,
            name: "Model",
            format: Some(Fmt::Str(16)),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 46,
            sub: None,
            name: "ExposureTime",
            format: Some(Fmt::Int32u),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: Some(ExprId::Val1Val04C21ED),
            print_conv: PrintConv::Expr(ExprId::ImageExifToolExifPrintExposureTimeVal6037F3),
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 50,
            sub: None,
            name: "FNumber",
            format: Some(Fmt::Rational64u),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::Expr(ExprId::Sprintf1fVal2C65CD),
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 58,
            sub: None,
            name: "ExposureCompensation",
            format: Some(Fmt::Rational64s),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::Expr(ExprId::ValSprintf1fVal0892CDF),
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
    ],
    variants: &[],
};

/// `Image::ExifTool::FujiFilm::PrioritySettings` -- 2 fields,
/// 0 `_variants` groups (Step 23).
/// Generated from ExifTool's in-memory tag table. Do not edit by hand.
pub static FUJIFILM_PRIORITYSETTINGS: BinaryTable = BinaryTable {
    module: "FujiFilm",
    table: "PrioritySettings",
    group0: "MakerNotes",
    group1: "FujiFilm",
    group2: "Camera",
    first_entry: 0,
    default_format: Fmt::Int16u,
    offsets_sound_until: None,
    priority: None,
    gate_a: GateA { blocked_by: &[] },
    fields: &[
        Field {
            index: 0,
            sub: Some(1),
            name: "AF-SPriority",
            format: None,
            count: 1,
            mask: Some(Mask {
                bits: 0xf,
                shift: 0,
            }),
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[(1, "Release"), (2, "Focus")]),
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 0,
            sub: Some(2),
            name: "AF-CPriority",
            format: None,
            count: 1,
            mask: Some(Mask {
                bits: 0xf0,
                shift: 4,
            }),
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[(1, "Release"), (2, "Focus")]),
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
    ],
    variants: &[],
};

/// `Image::ExifTool::FujiFilm::RAFData` -- 2 fields,
/// 2 `_variants` groups (Step 23).
/// Generated from ExifTool's in-memory tag table. Do not edit by hand.
pub static FUJIFILM_RAFDATA: BinaryTable = BinaryTable {
    module: "FujiFilm",
    table: "RAFData",
    group0: "MakerNotes",
    group1: "FujiFilm",
    group2: "Camera",
    first_entry: 0,
    default_format: Fmt::Int8u,
    offsets_sound_until: None,
    priority: None,
    gate_a: GateA { blocked_by: &[] },
    fields: &[
        Field {
            index: 0,
            sub: None,
            name: "RawImageWidth",
            format: Some(Fmt::Int32u),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted {
                value_conv: true,
                raw_conv: true,
                condition: false,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 12,
            sub: None,
            name: "RawImageHeight",
            format: Some(Fmt::Int32u),
            count: 1,
            mask: None,
            condition: Some(Cond::MemberTruthy {
                member: "FujiHeight",
                negate: true,
            }),
            raw_conv: None,
            omitted: Omitted {
                value_conv: true,
                raw_conv: false,
                condition: true,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
    ],
    variants: &[
        VariantGroup {
            index: 4,
            sub: None,
            alternatives: &[
                (
                    Cond::MemberTruthy {
                        member: "FujiWidth",
                        negate: true,
                    },
                    Field {
                        index: 4,
                        sub: None,
                        name: "RawImageWidth",
                        format: Some(Fmt::Int32u),
                        count: 1,
                        mask: None,
                        condition: Some(Cond::MemberTruthy {
                            member: "FujiWidth",
                            negate: true,
                        }),
                        raw_conv: None,
                        omitted: Omitted {
                            value_conv: true,
                            raw_conv: true,
                            condition: false,
                            hook: false,
                            subdirectory: false,
                            print_conv: false,
                        },
                        value_conv: None,
                        print_conv: PrintConv::None,
                        subdir: None,
                        hook: &[],
                        groups: TagGroups::NONE,
                    },
                ),
                (
                    Cond::Always,
                    Field {
                        index: 4,
                        sub: None,
                        name: "RawImageHeight",
                        format: Some(Fmt::Int32u),
                        count: 1,
                        mask: None,
                        condition: None,
                        raw_conv: Some(RawConvEffect::SetMember {
                            member: "FujiHeight",
                        }),
                        omitted: Omitted {
                            value_conv: true,
                            raw_conv: true,
                            condition: false,
                            hook: false,
                            subdirectory: false,
                            print_conv: false,
                        },
                        value_conv: None,
                        print_conv: PrintConv::None,
                        subdir: None,
                        hook: &[],
                        groups: TagGroups::NONE,
                    },
                ),
            ],
        },
        VariantGroup {
            index: 8,
            sub: None,
            alternatives: &[
                (
                    Cond::MemberTruthy {
                        member: "FujiWidth",
                        negate: true,
                    },
                    Field {
                        index: 8,
                        sub: None,
                        name: "RawImageWidth",
                        format: Some(Fmt::Int32u),
                        count: 1,
                        mask: None,
                        condition: Some(Cond::MemberTruthy {
                            member: "FujiWidth",
                            negate: true,
                        }),
                        raw_conv: None,
                        omitted: Omitted {
                            value_conv: true,
                            raw_conv: true,
                            condition: false,
                            hook: false,
                            subdirectory: false,
                            print_conv: false,
                        },
                        value_conv: None,
                        print_conv: PrintConv::None,
                        subdir: None,
                        hook: &[],
                        groups: TagGroups::NONE,
                    },
                ),
                (
                    Cond::MemberTruthy {
                        member: "FujiHeight",
                        negate: true,
                    },
                    Field {
                        index: 8,
                        sub: None,
                        name: "RawImageHeight",
                        format: Some(Fmt::Int32u),
                        count: 1,
                        mask: None,
                        condition: Some(Cond::MemberTruthy {
                            member: "FujiHeight",
                            negate: true,
                        }),
                        raw_conv: Some(RawConvEffect::SetMember {
                            member: "FujiHeight",
                        }),
                        omitted: Omitted {
                            value_conv: true,
                            raw_conv: true,
                            condition: false,
                            hook: false,
                            subdirectory: false,
                            print_conv: false,
                        },
                        value_conv: None,
                        print_conv: PrintConv::None,
                        subdir: None,
                        hook: &[],
                        groups: TagGroups::NONE,
                    },
                ),
            ],
        },
    ],
};

/// `Image::ExifTool::FujiFilm::RAFHeader` -- 2 fields,
/// 0 `_variants` groups (Step 23).
/// Generated from ExifTool's in-memory tag table. Do not edit by hand.
pub static FUJIFILM_RAFHEADER: BinaryTable = BinaryTable {
    module: "FujiFilm",
    table: "RAFHeader",
    group0: "RAF",
    group1: "RAF",
    group2: "Image",
    first_entry: 0,
    default_format: Fmt::Int8u,
    offsets_sound_until: None,
    priority: None,
    gate_a: GateA { blocked_by: &[] },
    fields: &[
        Field {
            index: 60,
            sub: None,
            name: "FirmwareVersion",
            format: Some(Fmt::Undef(4)),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 108,
            sub: None,
            name: "RAFCompression",
            format: Some(Fmt::Int32u),
            count: 1,
            mask: None,
            condition: Some(Cond::ValPtRegex {
                pattern: "^\\x00\\x00\\x00",
                negate: false,
            }),
            raw_conv: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: false,
                condition: true,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[(0, "Uncompressed"), (2, "Lossless"), (3, "Lossy")]),
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
    ],
    variants: &[],
};
