//! ExifTool `ICC_Profile` ProcessBinaryData tables, generated from ExifTool
//! 13.59's own Perl hashes -- one file per module; `mod.rs` beside this
//! file is the hub that declares and re-exports it.
//!
//! DO NOT EDIT. Regenerate with `just regen-tables` (see `mod.rs`).

#![allow(clippy::unreadable_literal, clippy::too_many_lines, unused_parens)]

// Everything a table literal names -- the schema types, `ExprId`, the
// `cond`/`subdir`/`ifd_schema` imports -- is in scope in the hub, and a glob
// import of the parent module brings its private imports along (RFC 1560).
#[allow(unused_imports)]
use super::*;

/// `Image::ExifTool::ICC_Profile::Chromaticity` -- 6 fields,
/// 0 `_variants` groups (Step 23).
/// Generated from ExifTool's in-memory tag table. Do not edit by hand.
pub static ICC_PROFILE_CHROMATICITY: BinaryTable = BinaryTable {
    module: "ICC_Profile",
    table: "Chromaticity",
    group0: "ICC_Profile",
    group1: "ICC-chrm",
    group2: "Image",
    first_entry: 0,
    default_format: Fmt::Int8u,
    offsets_sound_until: None,
    priority: None,
    gate_a: GateA { blocked_by: &[] },
    fields: &[
        Field {
            index: 8,
            sub: None,
            name: "ChromaticityChannels",
            format: Some(Fmt::Int16u),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 10,
            sub: None,
            name: "ChromaticityColorant",
            format: Some(Fmt::Int16u),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[
                (0, "Unknown"),
                (1, "ITU-R BT.709"),
                (2, "SMPTE RP145-1994"),
                (3, "EBU Tech.3213-E"),
                (4, "P22"),
            ]),
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 12,
            sub: None,
            name: "ChromaticityChannel1",
            format: Some(Fmt::Fixed32u),
            count: 2,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 20,
            sub: None,
            name: "ChromaticityChannel2",
            format: Some(Fmt::Fixed32u),
            count: 2,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 28,
            sub: None,
            name: "ChromaticityChannel3",
            format: Some(Fmt::Fixed32u),
            count: 2,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 36,
            sub: None,
            name: "ChromaticityChannel4",
            format: Some(Fmt::Fixed32u),
            count: 2,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
    ],
    variants: &[],
};

/// `Image::ExifTool::ICC_Profile::ColorRep` -- 4 fields,
/// 0 `_variants` groups (Step 23).
/// Generated from ExifTool's in-memory tag table. Do not edit by hand.
pub static ICC_PROFILE_COLORREP: BinaryTable = BinaryTable {
    module: "ICC_Profile",
    table: "ColorRep",
    group0: "ICC_Profile",
    group1: "ICC-cicp",
    group2: "Image",
    first_entry: 0,
    default_format: Fmt::Int8u,
    offsets_sound_until: None,
    priority: None,
    gate_a: GateA { blocked_by: &[] },
    fields: &[
        Field {
            index: 8,
            sub: None,
            name: "ColorPrimaries",
            format: None,
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[
                (1, "BT.709"),
                (2, "Unspecified"),
                (4, "BT.470 System M (historical)"),
                (5, "BT.470 System B, G (historical)"),
                (6, "BT.601"),
                (7, "SMPTE 240"),
                (8, "Generic film (color filters using illuminant C)"),
                (9, "BT.2020, BT.2100"),
                (10, "SMPTE 428 (CIE 1931 XYZ)"),
                (11, "SMPTE RP 431-2"),
                (12, "SMPTE EG 432-1"),
                (22, "EBU Tech. 3213-E"),
            ]),
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 9,
            sub: None,
            name: "TransferCharacteristics",
            format: None,
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[
                (0, "For future use (0)"),
                (1, "BT.709"),
                (2, "Unspecified"),
                (3, "For future use (3)"),
                (4, "BT.470 System M (historical)"),
                (5, "BT.470 System B, G (historical)"),
                (6, "BT.601"),
                (7, "SMPTE 240 M"),
                (8, "Linear"),
                (9, "Logarithmic (100 : 1 range)"),
                (10, "Logarithmic (100 * Sqrt(10) : 1 range)"),
                (11, "IEC 61966-2-4"),
                (12, "BT.1361"),
                (13, "sRGB or sYCC"),
                (14, "BT.2020 10-bit systems"),
                (15, "BT.2020 12-bit systems"),
                (16, "SMPTE ST 2084, ITU BT.2100 PQ"),
                (17, "SMPTE ST 428"),
                (18, "BT.2100 HLG, ARIB STD-B67"),
            ]),
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 10,
            sub: None,
            name: "MatrixCoefficients",
            format: None,
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[
                (0, "Identity matrix"),
                (1, "BT.709"),
                (2, "Unspecified"),
                (3, "For future use (3)"),
                (4, "US FCC 73.628"),
                (5, "BT.470 System B, G (historical)"),
                (6, "BT.601"),
                (7, "SMPTE 240 M"),
                (8, "YCgCo"),
                (9, "BT.2020 non-constant luminance, BT.2100 YCbCr"),
                (10, "BT.2020 constant luminance"),
                (11, "SMPTE ST 2085 YDzDx"),
                (12, "Chromaticity-derived non-constant luminance"),
                (13, "Chromaticity-derived constant luminance"),
                (14, "BT.2100 ICtCp"),
            ]),
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 11,
            sub: None,
            name: "VideoFullRangeFlag",
            format: None,
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[(0, "Limited"), (1, "Full")]),
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
    ],
    variants: &[],
};

/// `Image::ExifTool::ICC_Profile::ColorantTable` -- 7 fields,
/// 0 `_variants` groups (Step 23).
/// Generated from ExifTool's in-memory tag table. Do not edit by hand.
pub static ICC_PROFILE_COLORANTTABLE: BinaryTable = BinaryTable {
    module: "ICC_Profile",
    table: "ColorantTable",
    group0: "ICC_Profile",
    group1: "ICC-clrt",
    group2: "Image",
    first_entry: 0,
    default_format: Fmt::Int8u,
    offsets_sound_until: None,
    priority: None,
    gate_a: GateA { blocked_by: &[] },
    fields: &[
        Field {
            index: 8,
            sub: None,
            name: "ColorantCount",
            format: Some(Fmt::Int32u),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 12,
            sub: None,
            name: "Colorant1Name",
            format: Some(Fmt::Str(32)),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 44,
            sub: None,
            name: "Colorant1Coordinates",
            format: Some(Fmt::Int16u),
            count: 3,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 50,
            sub: None,
            name: "Colorant2Name",
            format: Some(Fmt::Str(32)),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 82,
            sub: None,
            name: "Colorant2Coordinates",
            format: Some(Fmt::Int16u),
            count: 3,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 88,
            sub: None,
            name: "Colorant3Name",
            format: Some(Fmt::Str(32)),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 120,
            sub: None,
            name: "Colorant3Coordinates",
            format: Some(Fmt::Int16u),
            count: 3,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
    ],
    variants: &[],
};

/// `Image::ExifTool::ICC_Profile::Header` -- 16 fields,
/// 0 `_variants` groups (Step 23).
/// Generated from ExifTool's in-memory tag table. Do not edit by hand.
pub static ICC_PROFILE_HEADER: BinaryTable = BinaryTable {
    module: "ICC_Profile",
    table: "Header",
    group0: "ICC_Profile",
    group1: "ICC-header",
    group2: "Image",
    first_entry: 0,
    default_format: Fmt::Int8u,
    offsets_sound_until: None,
    priority: None,
    gate_a: GateA { blocked_by: &[] },
    fields: &[
        Field {
            index: 4,
            sub: None,
            name: "ProfileCMMType",
            format: Some(Fmt::Str(4)),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::StrEnum(&[
                ("", ""),
                ("4d2p", "Erdt Systems GmbH & Co KG"),
                ("AAMA", "Aamazing Technologies, Inc."),
                ("ACER", "Acer Peripherals"),
                ("ACLT", "Acolyte Color Research"),
                ("ACTI", "Actix Systems, Inc."),
                ("ADAR", "Adara Technology, Inc."),
                ("ADBE", "Adobe Systems Inc."),
                ("ADI ", "ADI Systems, Inc."),
                ("AGFA", "Agfa Graphics N.V."),
                ("ALMD", "Alps Electric USA, Inc."),
                ("ALPS", "Alps Electric USA, Inc."),
                ("ALWN", "Alwan Color Expertise"),
                ("AMTI", "Amiable Technologies, Inc."),
                ("AOC ", "AOC International (U.S.A), Ltd."),
                ("APAG", "Apago"),
                ("APPL", "Apple Computer Inc."),
                ("AST ", "AST"),
                ("AT&T", "AT&T Computer Systems"),
                ("BAEL", "BARBIERI electronic"),
                ("BRCO", "Barco NV"),
                ("BRKP", "Breakpoint Pty Limited"),
                ("BROT", "Brother Industries, LTD"),
                ("BULL", "Bull"),
                ("BUS ", "Bus Computer Systems"),
                ("C-IT", "C-Itoh"),
                ("CAMR", "Intel Corporation"),
                ("CANO", "Canon, Inc. (Canon Development Americas, Inc.)"),
                ("CARR", "Carroll Touch"),
                ("CASI", "Casio Computer Co., Ltd."),
                ("CBUS", "Colorbus PL"),
                ("CEL ", "Crossfield"),
                ("CELx", "Crossfield"),
                ("CGS ", "CGS Publishing Technologies International GmbH"),
                ("CHM ", "Rochester Robotics"),
                ("CIGL", "Colour Imaging Group, London"),
                ("CITI", "Citizen"),
                ("CL00", "Candela, Ltd."),
                ("CLIQ", "Color IQ"),
                ("CMCO", "Chromaco, Inc."),
                ("CMiX", "CHROMiX"),
                ("COLO", "Colorgraphic Communications Corporation"),
                ("COMP", "COMPAQ Computer Corporation"),
                ("COMp", "Compeq USA/Focus Technology"),
                ("CONR", "Conrac Display Products"),
                ("CORD", "Cordata Technologies, Inc."),
                ("CPQ ", "Compaq Computer Corporation"),
                ("CPRO", "ColorPro"),
                ("CRN ", "Cornerstone"),
                ("CTX ", "CTX International, Inc."),
                ("CVIS", "ColorVision"),
                ("CWC ", "Fujitsu Laboratories, Ltd."),
                ("DARI", "Darius Technology, Ltd."),
                ("DATA", "Dataproducts"),
                ("DCP ", "Dry Creek Photo"),
                (
                    "DCRC",
                    "Digital Contents Resource Center, Chung-Ang University",
                ),
                ("DELL", "Dell Computer Corporation"),
                ("DIC ", "Dainippon Ink and Chemicals"),
                ("DICO", "Diconix"),
                ("DIGI", "Digital"),
                ("DL&C", "Digital Light & Color"),
                ("DPLG", "Doppelganger, LLC"),
                ("DS  ", "Dainippon Screen"),
                ("DSOL", "DOOSOL"),
                ("DUPN", "DuPont"),
                ("EPSO", "Epson"),
                ("ESKO", "Esko-Graphics"),
                (
                    "ETRI",
                    "Electronics and Telecommunications Research Institute",
                ),
                ("EVER", "Everex Systems, Inc."),
                ("EXAC", "ExactCODE GmbH"),
                ("Eizo", "EIZO NANAO CORPORATION"),
                ("FALC", "Falco Data Products, Inc."),
                ("FF  ", "Fuji Photo Film Co.,LTD"),
                ("FFEI", "FujiFilm Electronic Imaging, Ltd."),
                ("FNRD", "fnord software"),
                ("FORA", "Fora, Inc."),
                ("FORE", "Forefront Technology Corporation"),
                ("FP  ", "Fujitsu"),
                ("FPA ", "WayTech Development, Inc."),
                ("FUJI", "Fujitsu"),
                ("FX  ", "Fuji Xerox Co., Ltd."),
                ("GCC ", "GCC Technologies, Inc."),
                ("GGSL", "Global Graphics Software Limited"),
                ("GMB ", "Gretagmacbeth"),
                ("GMG ", "GMG GmbH & Co. KG"),
                ("GOLD", "GoldStar Technology, Inc."),
                ("GOOG", "Google"),
                ("GPRT", "Giantprint Pty Ltd"),
                ("GTMB", "Gretagmacbeth"),
                ("GVC ", "WayTech Development, Inc."),
                ("GW2K", "Sony Corporation"),
                ("HCI ", "HCI"),
                ("HDM ", "Heidelberger Druckmaschinen AG"),
                ("HERM", "Hermes"),
                ("HITA", "Hitachi America, Ltd."),
                ("HP  ", "Hewlett-Packard"),
                ("HTC ", "Hitachi, Ltd."),
                ("HiTi", "HiTi Digital, Inc."),
                ("IBM ", "IBM Corporation"),
                ("IDNT", "Scitex Corporation, Ltd."),
                ("IEC ", "Hewlett-Packard"),
                ("IIYA", "Iiyama North America, Inc."),
                ("IKEG", "Ikegami Electronics, Inc."),
                ("IMAG", "Image Systems Corporation"),
                ("IMI ", "Ingram Micro, Inc."),
                ("INTC", "Intel Corporation"),
                ("INTL", "N/A (INTL)"),
                ("INTR", "Intra Electronics USA, Inc."),
                ("IOCO", "Iocomm International Technology Corporation"),
                ("IPS ", "InfoPrint Solutions Company"),
                ("IRIS", "Scitex Corporation, Ltd."),
                ("ISL ", "Ichikawa Soft Laboratory"),
                ("ITNL", "N/A (ITNL)"),
                ("IVM ", "IVM"),
                ("IWAT", "Iwatsu Electric Co., Ltd."),
                ("Idnt", "Scitex Corporation, Ltd."),
                ("Inca", "Inca Digital Printers Ltd."),
                ("Iris", "Scitex Corporation, Ltd."),
                ("JPEG", "Joint Photographic Experts Group"),
                ("JSFT", "Jetsoft Development"),
                ("JVC ", "JVC Information Products Co."),
                ("KART", "Scitex Corporation, Ltd."),
                ("KFC ", "KFC Computek Components Corporation"),
                ("KLH ", "KLH Computers"),
                ("KMHD", "Konica Minolta Holdings, Inc."),
                ("KNCA", "Konica Corporation"),
                ("KODA", "Kodak"),
                ("KYOC", "Kyocera"),
                ("Kart", "Scitex Corporation, Ltd."),
                ("LCAG", "Leica Camera AG"),
                ("LCCD", "Leeds Colour"),
                ("LDAK", "Left Dakota"),
                ("LEAD", "Leading Technology, Inc."),
                ("LEXM", "Lexmark International, Inc."),
                ("LINK", "Link Computer, Inc."),
                ("LINO", "Linotronic"),
                ("LITE", "Lite-On, Inc."),
                ("Leaf", "Leaf"),
                ("Lino", "Linotronic"),
                ("MAGC", "Mag Computronic (USA) Inc."),
                ("MAGI", "MAG Innovision, Inc."),
                ("MANN", "Mannesmann"),
                ("MICN", "Micron Technology, Inc."),
                ("MICR", "Microtek"),
                ("MICV", "Microvitec, Inc."),
                ("MINO", "Minolta"),
                ("MITS", "Mitsubishi Electronics America, Inc."),
                ("MITs", "Mitsuba Corporation"),
                ("MNLT", "Minolta"),
                ("MODG", "Modgraph, Inc."),
                ("MONI", "Monitronix, Inc."),
                ("MONS", "Monaco Systems Inc."),
                ("MORS", "Morse Technology, Inc."),
                ("MOTI", "Motive Systems"),
                ("MSFT", "Microsoft Corporation"),
                ("MUTO", "MUTOH INDUSTRIES LTD."),
                ("Mits", "Mitsubishi Electric Corporation Kyoto Works"),
                ("NANA", "NANAO USA Corporation"),
                ("NEC ", "NEC Corporation"),
                ("NEXP", "NexPress Solutions LLC"),
                ("NISS", "Nissei Sangyo America, Ltd."),
                ("NKON", "Nikon Corporation"),
                ("NONE", "none"),
                ("OCE ", "Oce Technologies B.V."),
                ("OCEC", "OceColor"),
                ("OKI ", "Oki"),
                ("OKID", "Okidata"),
                ("OKIP", "Okidata"),
                ("OLIV", "Olivetti"),
                ("OLYM", "OLYMPUS OPTICAL CO., LTD"),
                ("ONYX", "Onyx Graphics"),
                ("OPTI", "Optiquest"),
                ("PACK", "Packard Bell"),
                ("PANA", "Matsushita Electric Industrial Co., Ltd."),
                ("PANT", "Pantone, Inc."),
                ("PBN ", "Packard Bell"),
                ("PFU ", "PFU Limited"),
                ("PHIL", "Philips Consumer Electronics Co."),
                ("PNTX", "HOYA Corporation PENTAX Imaging Systems Division"),
                ("POne", "Phase One A/S"),
                ("PREM", "Premier Computer Innovations"),
                ("PRIN", "Princeton Graphic Systems"),
                ("PRIP", "Princeton Publishing Labs"),
                ("QLUX", "Hong Kong"),
                ("QMS ", "QMS, Inc."),
                ("QPCD", "QPcard AB"),
                ("QUAD", "QuadLaser"),
                ("QUME", "Qume Corporation"),
                ("RADI", "Radius, Inc."),
                ("RDDx", "Integrated Color Solutions, Inc."),
                ("RDG ", "Roland DG Corporation"),
                ("REDM", "REDMS Group, Inc."),
                ("RELI", "Relisys"),
                ("RGMS", "Rolf Gierling Multitools"),
                ("RICO", "Ricoh Corporation"),
                ("RNLD", "Edmund Ronald"),
                ("ROYA", "Royal"),
                ("RPC ", "Ricoh Printing Systems,Ltd."),
                ("RTL ", "Royal Information Electronics Co., Ltd."),
                ("SAMP", "Sampo Corporation of America"),
                ("SAMS", "Samsung, Inc."),
                ("SANT", "Jaime Santana Pomares"),
                ("SCIT", "Scitex Corporation, Ltd."),
                ("SCRN", "Dainippon Screen"),
                ("SDP ", "Scitex Corporation, Ltd."),
                ("SEC ", "SAMSUNG ELECTRONICS CO.,LTD"),
                ("SEIK", "Seiko Instruments U.S.A., Inc."),
                ("SEIk", "Seikosha"),
                ("SGUY", "ScanGuy.com"),
                ("SHAR", "Sharp Laboratories"),
                ("SICC", "International Color Consortium"),
                ("SONY", "SONY Corporation"),
                ("SPCL", "SpectraCal"),
                ("STAR", "Star"),
                ("STC ", "Sampo Technology Corporation"),
                ("Scit", "Scitex Corporation, Ltd."),
                ("Sdp ", "Scitex Corporation, Ltd."),
                ("Sony", "Sony Corporation"),
                ("TALO", "Talon Technology Corporation"),
                ("TAND", "Tandy"),
                ("TATU", "Tatung Co. of America, Inc."),
                ("TAXA", "TAXAN America, Inc."),
                ("TDS ", "Tokyo Denshi Sekei K.K."),
                ("TECO", "TECO Information Systems, Inc."),
                ("TEGR", "Tegra"),
                ("TEKT", "Tektronix, Inc."),
                ("TI  ", "Texas Instruments"),
                ("TMKR", "TypeMaker Ltd."),
                ("TOSB", "TOSHIBA corp."),
                ("TOSH", "Toshiba, Inc."),
                ("TOTK", "TOTOKU ELECTRIC Co., LTD"),
                ("TRIU", "Triumph"),
                ("TSBT", "TOSHIBA TEC CORPORATION"),
                ("TTX ", "TTX Computer Products, Inc."),
                ("TVM ", "TVM Professional Monitor Corporation"),
                ("TW  ", "TW Casper Corporation"),
                ("ULSX", "Ulead Systems"),
                ("UNIS", "Unisys"),
                ("UTZF", "Utz Fehlau & Sohn"),
                ("VARI", "Varityper"),
                ("VIEW", "Viewsonic"),
                ("VISL", "Visual communication"),
                ("VIVO", "Vivo Mobile Communication Co., Ltd"),
                ("WANG", "Wang"),
                ("WLBR", "Wilbur Imaging"),
                ("WTG2", "Ware To Go"),
                ("WYSE", "WYSE Technology"),
                ("XERX", "Xerox Corporation"),
                ("XM  ", "Xiaomi"),
                ("XRIT", "X-Rite"),
                ("Z123", "Lavanya's test Company"),
                ("ZRAN", "Zoran Corporation"),
                ("Zebr", "Zebra Technologies Inc"),
                ("appl", "Apple Computer Inc."),
                ("bICC", "basICColor GmbH"),
                ("berg", "bergdesign incorporated"),
                ("ceyd", "Integrated Color Solutions, Inc."),
                ("clsp", "MacDermid ColorSpan, Inc."),
                ("ds  ", "Dainippon Screen"),
                ("dupn", "DuPont"),
                ("ffei", "FujiFilm Electronic Imaging, Ltd."),
                ("flux", "FluxData Corporation"),
                ("iris", "Scitex Corporation, Ltd."),
                ("kart", "Scitex Corporation, Ltd."),
                ("lcms", "Little CMS"),
                ("lino", "Linotronic"),
                ("none", "none"),
                ("ob4d", "Erdt Systems GmbH & Co KG"),
                ("obic", "Medigraph GmbH"),
                ("quby", "Qubyx Sarl"),
                ("scit", "Scitex Corporation, Ltd."),
                ("scrn", "Dainippon Screen"),
                ("sdp ", "Scitex Corporation, Ltd."),
                ("siwi", "SIWI GRAFIKA CORPORATION"),
                ("yxym", "YxyMaster GmbH"),
            ]),
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 8,
            sub: None,
            name: "ProfileVersion",
            format: Some(Fmt::Int16s),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::Expr(ExprId::Val8Val0xf04Val0x0fB1E493),
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 12,
            sub: None,
            name: "ProfileClass",
            format: Some(Fmt::Str(4)),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::StrEnum(&[
                ("abst", "Abstract Profile"),
                ("cenc", "ColorEncodingSpace Profile"),
                ("link", "DeviceLink Profile"),
                ("mid ", "MultiplexIdentification Profile"),
                ("mlnk", "MultiplexLink Profile"),
                ("mntr", "Display Device Profile"),
                ("mvis", "MultiplexVisualization Profile"),
                ("nkpf", "Nikon Input Device Profile (NON-STANDARD!)"),
                ("nmcl", "NamedColor Profile"),
                ("prtr", "Output Device Profile"),
                ("scnr", "Input Device Profile"),
                ("spac", "ColorSpace Conversion Profile"),
            ]),
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 16,
            sub: None,
            name: "ColorSpaceData",
            format: Some(Fmt::Str(4)),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 20,
            sub: None,
            name: "ProfileConnectionSpace",
            format: Some(Fmt::Str(4)),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 24,
            sub: None,
            name: "ProfileDateTime",
            format: Some(Fmt::Int16u),
            count: 6,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: Some(ExprId::Sprintf4d2d2d2d2d2dSplitValF089FB),
            print_conv: PrintConv::Expr(ExprId::SelfConvertDateTimeVal7455B8),
            subdir: None,
            hook: &[],
            groups: TagGroups {
                g0: None,
                g1: None,
                g2: Some("Time"),
            },
        },
        Field {
            index: 36,
            sub: None,
            name: "ProfileFileSignature",
            format: Some(Fmt::Str(4)),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 40,
            sub: None,
            name: "PrimaryPlatform",
            format: Some(Fmt::Str(4)),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::StrEnum(&[
                ("APPL", "Apple Computer Inc."),
                ("MSFT", "Microsoft Corporation"),
                ("SGI ", "Silicon Graphics Inc."),
                ("SUNW", "Sun Microsystems Inc."),
                ("TGNT", "Taligent Inc."),
            ]),
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 44,
            sub: None,
            name: "CMMFlags",
            format: Some(Fmt::Int32u),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::Expr(ExprId::Val0x01EmbeddedNotEmbeddedVal0x02NotInde359A41),
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 48,
            sub: None,
            name: "DeviceManufacturer",
            format: Some(Fmt::Str(4)),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::StrEnum(&[
                ("", ""),
                ("4d2p", "Erdt Systems GmbH & Co KG"),
                ("AAMA", "Aamazing Technologies, Inc."),
                ("ACER", "Acer Peripherals"),
                ("ACLT", "Acolyte Color Research"),
                ("ACTI", "Actix Systems, Inc."),
                ("ADAR", "Adara Technology, Inc."),
                ("ADBE", "Adobe Systems Inc."),
                ("ADI ", "ADI Systems, Inc."),
                ("AGFA", "Agfa Graphics N.V."),
                ("ALMD", "Alps Electric USA, Inc."),
                ("ALPS", "Alps Electric USA, Inc."),
                ("ALWN", "Alwan Color Expertise"),
                ("AMTI", "Amiable Technologies, Inc."),
                ("AOC ", "AOC International (U.S.A), Ltd."),
                ("APAG", "Apago"),
                ("APPL", "Apple Computer Inc."),
                ("AST ", "AST"),
                ("AT&T", "AT&T Computer Systems"),
                ("BAEL", "BARBIERI electronic"),
                ("BRCO", "Barco NV"),
                ("BRKP", "Breakpoint Pty Limited"),
                ("BROT", "Brother Industries, LTD"),
                ("BULL", "Bull"),
                ("BUS ", "Bus Computer Systems"),
                ("C-IT", "C-Itoh"),
                ("CAMR", "Intel Corporation"),
                ("CANO", "Canon, Inc. (Canon Development Americas, Inc.)"),
                ("CARR", "Carroll Touch"),
                ("CASI", "Casio Computer Co., Ltd."),
                ("CBUS", "Colorbus PL"),
                ("CEL ", "Crossfield"),
                ("CELx", "Crossfield"),
                ("CGS ", "CGS Publishing Technologies International GmbH"),
                ("CHM ", "Rochester Robotics"),
                ("CIGL", "Colour Imaging Group, London"),
                ("CITI", "Citizen"),
                ("CL00", "Candela, Ltd."),
                ("CLIQ", "Color IQ"),
                ("CMCO", "Chromaco, Inc."),
                ("CMiX", "CHROMiX"),
                ("COLO", "Colorgraphic Communications Corporation"),
                ("COMP", "COMPAQ Computer Corporation"),
                ("COMp", "Compeq USA/Focus Technology"),
                ("CONR", "Conrac Display Products"),
                ("CORD", "Cordata Technologies, Inc."),
                ("CPQ ", "Compaq Computer Corporation"),
                ("CPRO", "ColorPro"),
                ("CRN ", "Cornerstone"),
                ("CTX ", "CTX International, Inc."),
                ("CVIS", "ColorVision"),
                ("CWC ", "Fujitsu Laboratories, Ltd."),
                ("DARI", "Darius Technology, Ltd."),
                ("DATA", "Dataproducts"),
                ("DCP ", "Dry Creek Photo"),
                (
                    "DCRC",
                    "Digital Contents Resource Center, Chung-Ang University",
                ),
                ("DELL", "Dell Computer Corporation"),
                ("DIC ", "Dainippon Ink and Chemicals"),
                ("DICO", "Diconix"),
                ("DIGI", "Digital"),
                ("DL&C", "Digital Light & Color"),
                ("DPLG", "Doppelganger, LLC"),
                ("DS  ", "Dainippon Screen"),
                ("DSOL", "DOOSOL"),
                ("DUPN", "DuPont"),
                ("EPSO", "Epson"),
                ("ESKO", "Esko-Graphics"),
                (
                    "ETRI",
                    "Electronics and Telecommunications Research Institute",
                ),
                ("EVER", "Everex Systems, Inc."),
                ("EXAC", "ExactCODE GmbH"),
                ("Eizo", "EIZO NANAO CORPORATION"),
                ("FALC", "Falco Data Products, Inc."),
                ("FF  ", "Fuji Photo Film Co.,LTD"),
                ("FFEI", "FujiFilm Electronic Imaging, Ltd."),
                ("FNRD", "fnord software"),
                ("FORA", "Fora, Inc."),
                ("FORE", "Forefront Technology Corporation"),
                ("FP  ", "Fujitsu"),
                ("FPA ", "WayTech Development, Inc."),
                ("FUJI", "Fujitsu"),
                ("FX  ", "Fuji Xerox Co., Ltd."),
                ("GCC ", "GCC Technologies, Inc."),
                ("GGSL", "Global Graphics Software Limited"),
                ("GMB ", "Gretagmacbeth"),
                ("GMG ", "GMG GmbH & Co. KG"),
                ("GOLD", "GoldStar Technology, Inc."),
                ("GOOG", "Google"),
                ("GPRT", "Giantprint Pty Ltd"),
                ("GTMB", "Gretagmacbeth"),
                ("GVC ", "WayTech Development, Inc."),
                ("GW2K", "Sony Corporation"),
                ("HCI ", "HCI"),
                ("HDM ", "Heidelberger Druckmaschinen AG"),
                ("HERM", "Hermes"),
                ("HITA", "Hitachi America, Ltd."),
                ("HP  ", "Hewlett-Packard"),
                ("HTC ", "Hitachi, Ltd."),
                ("HiTi", "HiTi Digital, Inc."),
                ("IBM ", "IBM Corporation"),
                ("IDNT", "Scitex Corporation, Ltd."),
                ("IEC ", "Hewlett-Packard"),
                ("IIYA", "Iiyama North America, Inc."),
                ("IKEG", "Ikegami Electronics, Inc."),
                ("IMAG", "Image Systems Corporation"),
                ("IMI ", "Ingram Micro, Inc."),
                ("INTC", "Intel Corporation"),
                ("INTL", "N/A (INTL)"),
                ("INTR", "Intra Electronics USA, Inc."),
                ("IOCO", "Iocomm International Technology Corporation"),
                ("IPS ", "InfoPrint Solutions Company"),
                ("IRIS", "Scitex Corporation, Ltd."),
                ("ISL ", "Ichikawa Soft Laboratory"),
                ("ITNL", "N/A (ITNL)"),
                ("IVM ", "IVM"),
                ("IWAT", "Iwatsu Electric Co., Ltd."),
                ("Idnt", "Scitex Corporation, Ltd."),
                ("Inca", "Inca Digital Printers Ltd."),
                ("Iris", "Scitex Corporation, Ltd."),
                ("JPEG", "Joint Photographic Experts Group"),
                ("JSFT", "Jetsoft Development"),
                ("JVC ", "JVC Information Products Co."),
                ("KART", "Scitex Corporation, Ltd."),
                ("KFC ", "KFC Computek Components Corporation"),
                ("KLH ", "KLH Computers"),
                ("KMHD", "Konica Minolta Holdings, Inc."),
                ("KNCA", "Konica Corporation"),
                ("KODA", "Kodak"),
                ("KYOC", "Kyocera"),
                ("Kart", "Scitex Corporation, Ltd."),
                ("LCAG", "Leica Camera AG"),
                ("LCCD", "Leeds Colour"),
                ("LDAK", "Left Dakota"),
                ("LEAD", "Leading Technology, Inc."),
                ("LEXM", "Lexmark International, Inc."),
                ("LINK", "Link Computer, Inc."),
                ("LINO", "Linotronic"),
                ("LITE", "Lite-On, Inc."),
                ("Leaf", "Leaf"),
                ("Lino", "Linotronic"),
                ("MAGC", "Mag Computronic (USA) Inc."),
                ("MAGI", "MAG Innovision, Inc."),
                ("MANN", "Mannesmann"),
                ("MICN", "Micron Technology, Inc."),
                ("MICR", "Microtek"),
                ("MICV", "Microvitec, Inc."),
                ("MINO", "Minolta"),
                ("MITS", "Mitsubishi Electronics America, Inc."),
                ("MITs", "Mitsuba Corporation"),
                ("MNLT", "Minolta"),
                ("MODG", "Modgraph, Inc."),
                ("MONI", "Monitronix, Inc."),
                ("MONS", "Monaco Systems Inc."),
                ("MORS", "Morse Technology, Inc."),
                ("MOTI", "Motive Systems"),
                ("MSFT", "Microsoft Corporation"),
                ("MUTO", "MUTOH INDUSTRIES LTD."),
                ("Mits", "Mitsubishi Electric Corporation Kyoto Works"),
                ("NANA", "NANAO USA Corporation"),
                ("NEC ", "NEC Corporation"),
                ("NEXP", "NexPress Solutions LLC"),
                ("NISS", "Nissei Sangyo America, Ltd."),
                ("NKON", "Nikon Corporation"),
                ("NONE", "none"),
                ("OCE ", "Oce Technologies B.V."),
                ("OCEC", "OceColor"),
                ("OKI ", "Oki"),
                ("OKID", "Okidata"),
                ("OKIP", "Okidata"),
                ("OLIV", "Olivetti"),
                ("OLYM", "OLYMPUS OPTICAL CO., LTD"),
                ("ONYX", "Onyx Graphics"),
                ("OPTI", "Optiquest"),
                ("PACK", "Packard Bell"),
                ("PANA", "Matsushita Electric Industrial Co., Ltd."),
                ("PANT", "Pantone, Inc."),
                ("PBN ", "Packard Bell"),
                ("PFU ", "PFU Limited"),
                ("PHIL", "Philips Consumer Electronics Co."),
                ("PNTX", "HOYA Corporation PENTAX Imaging Systems Division"),
                ("POne", "Phase One A/S"),
                ("PREM", "Premier Computer Innovations"),
                ("PRIN", "Princeton Graphic Systems"),
                ("PRIP", "Princeton Publishing Labs"),
                ("QLUX", "Hong Kong"),
                ("QMS ", "QMS, Inc."),
                ("QPCD", "QPcard AB"),
                ("QUAD", "QuadLaser"),
                ("QUME", "Qume Corporation"),
                ("RADI", "Radius, Inc."),
                ("RDDx", "Integrated Color Solutions, Inc."),
                ("RDG ", "Roland DG Corporation"),
                ("REDM", "REDMS Group, Inc."),
                ("RELI", "Relisys"),
                ("RGMS", "Rolf Gierling Multitools"),
                ("RICO", "Ricoh Corporation"),
                ("RNLD", "Edmund Ronald"),
                ("ROYA", "Royal"),
                ("RPC ", "Ricoh Printing Systems,Ltd."),
                ("RTL ", "Royal Information Electronics Co., Ltd."),
                ("SAMP", "Sampo Corporation of America"),
                ("SAMS", "Samsung, Inc."),
                ("SANT", "Jaime Santana Pomares"),
                ("SCIT", "Scitex Corporation, Ltd."),
                ("SCRN", "Dainippon Screen"),
                ("SDP ", "Scitex Corporation, Ltd."),
                ("SEC ", "SAMSUNG ELECTRONICS CO.,LTD"),
                ("SEIK", "Seiko Instruments U.S.A., Inc."),
                ("SEIk", "Seikosha"),
                ("SGUY", "ScanGuy.com"),
                ("SHAR", "Sharp Laboratories"),
                ("SICC", "International Color Consortium"),
                ("SONY", "SONY Corporation"),
                ("SPCL", "SpectraCal"),
                ("STAR", "Star"),
                ("STC ", "Sampo Technology Corporation"),
                ("Scit", "Scitex Corporation, Ltd."),
                ("Sdp ", "Scitex Corporation, Ltd."),
                ("Sony", "Sony Corporation"),
                ("TALO", "Talon Technology Corporation"),
                ("TAND", "Tandy"),
                ("TATU", "Tatung Co. of America, Inc."),
                ("TAXA", "TAXAN America, Inc."),
                ("TDS ", "Tokyo Denshi Sekei K.K."),
                ("TECO", "TECO Information Systems, Inc."),
                ("TEGR", "Tegra"),
                ("TEKT", "Tektronix, Inc."),
                ("TI  ", "Texas Instruments"),
                ("TMKR", "TypeMaker Ltd."),
                ("TOSB", "TOSHIBA corp."),
                ("TOSH", "Toshiba, Inc."),
                ("TOTK", "TOTOKU ELECTRIC Co., LTD"),
                ("TRIU", "Triumph"),
                ("TSBT", "TOSHIBA TEC CORPORATION"),
                ("TTX ", "TTX Computer Products, Inc."),
                ("TVM ", "TVM Professional Monitor Corporation"),
                ("TW  ", "TW Casper Corporation"),
                ("ULSX", "Ulead Systems"),
                ("UNIS", "Unisys"),
                ("UTZF", "Utz Fehlau & Sohn"),
                ("VARI", "Varityper"),
                ("VIEW", "Viewsonic"),
                ("VISL", "Visual communication"),
                ("VIVO", "Vivo Mobile Communication Co., Ltd"),
                ("WANG", "Wang"),
                ("WLBR", "Wilbur Imaging"),
                ("WTG2", "Ware To Go"),
                ("WYSE", "WYSE Technology"),
                ("XERX", "Xerox Corporation"),
                ("XM  ", "Xiaomi"),
                ("XRIT", "X-Rite"),
                ("Z123", "Lavanya's test Company"),
                ("ZRAN", "Zoran Corporation"),
                ("Zebr", "Zebra Technologies Inc"),
                ("appl", "Apple Computer Inc."),
                ("bICC", "basICColor GmbH"),
                ("berg", "bergdesign incorporated"),
                ("ceyd", "Integrated Color Solutions, Inc."),
                ("clsp", "MacDermid ColorSpan, Inc."),
                ("ds  ", "Dainippon Screen"),
                ("dupn", "DuPont"),
                ("ffei", "FujiFilm Electronic Imaging, Ltd."),
                ("flux", "FluxData Corporation"),
                ("iris", "Scitex Corporation, Ltd."),
                ("kart", "Scitex Corporation, Ltd."),
                ("lcms", "Little CMS"),
                ("lino", "Linotronic"),
                ("none", "none"),
                ("ob4d", "Erdt Systems GmbH & Co KG"),
                ("obic", "Medigraph GmbH"),
                ("quby", "Qubyx Sarl"),
                ("scit", "Scitex Corporation, Ltd."),
                ("scrn", "Dainippon Screen"),
                ("sdp ", "Scitex Corporation, Ltd."),
                ("siwi", "SIWI GRAFIKA CORPORATION"),
                ("yxym", "YxyMaster GmbH"),
            ]),
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 52,
            sub: None,
            name: "DeviceModel",
            format: Some(Fmt::Str(4)),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 56,
            sub: None,
            name: "DeviceAttributes",
            format: Some(Fmt::Int32u),
            count: 2,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::Expr(ExprId::MyVSplitValV10x01TransparencyReflectiveV791352),
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 64,
            sub: None,
            name: "RenderingIntent",
            format: Some(Fmt::Int32u),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[
                (0, "Perceptual"),
                (1, "Media-Relative Colorimetric"),
                (2, "Saturation"),
                (3, "ICC-Absolute Colorimetric"),
            ]),
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 68,
            sub: None,
            name: "ConnectionSpaceIlluminant",
            format: Some(Fmt::Fixed32s),
            count: 3,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 80,
            sub: None,
            name: "ProfileCreator",
            format: Some(Fmt::Str(4)),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::StrEnum(&[
                ("", ""),
                ("4d2p", "Erdt Systems GmbH & Co KG"),
                ("AAMA", "Aamazing Technologies, Inc."),
                ("ACER", "Acer Peripherals"),
                ("ACLT", "Acolyte Color Research"),
                ("ACTI", "Actix Systems, Inc."),
                ("ADAR", "Adara Technology, Inc."),
                ("ADBE", "Adobe Systems Inc."),
                ("ADI ", "ADI Systems, Inc."),
                ("AGFA", "Agfa Graphics N.V."),
                ("ALMD", "Alps Electric USA, Inc."),
                ("ALPS", "Alps Electric USA, Inc."),
                ("ALWN", "Alwan Color Expertise"),
                ("AMTI", "Amiable Technologies, Inc."),
                ("AOC ", "AOC International (U.S.A), Ltd."),
                ("APAG", "Apago"),
                ("APPL", "Apple Computer Inc."),
                ("AST ", "AST"),
                ("AT&T", "AT&T Computer Systems"),
                ("BAEL", "BARBIERI electronic"),
                ("BRCO", "Barco NV"),
                ("BRKP", "Breakpoint Pty Limited"),
                ("BROT", "Brother Industries, LTD"),
                ("BULL", "Bull"),
                ("BUS ", "Bus Computer Systems"),
                ("C-IT", "C-Itoh"),
                ("CAMR", "Intel Corporation"),
                ("CANO", "Canon, Inc. (Canon Development Americas, Inc.)"),
                ("CARR", "Carroll Touch"),
                ("CASI", "Casio Computer Co., Ltd."),
                ("CBUS", "Colorbus PL"),
                ("CEL ", "Crossfield"),
                ("CELx", "Crossfield"),
                ("CGS ", "CGS Publishing Technologies International GmbH"),
                ("CHM ", "Rochester Robotics"),
                ("CIGL", "Colour Imaging Group, London"),
                ("CITI", "Citizen"),
                ("CL00", "Candela, Ltd."),
                ("CLIQ", "Color IQ"),
                ("CMCO", "Chromaco, Inc."),
                ("CMiX", "CHROMiX"),
                ("COLO", "Colorgraphic Communications Corporation"),
                ("COMP", "COMPAQ Computer Corporation"),
                ("COMp", "Compeq USA/Focus Technology"),
                ("CONR", "Conrac Display Products"),
                ("CORD", "Cordata Technologies, Inc."),
                ("CPQ ", "Compaq Computer Corporation"),
                ("CPRO", "ColorPro"),
                ("CRN ", "Cornerstone"),
                ("CTX ", "CTX International, Inc."),
                ("CVIS", "ColorVision"),
                ("CWC ", "Fujitsu Laboratories, Ltd."),
                ("DARI", "Darius Technology, Ltd."),
                ("DATA", "Dataproducts"),
                ("DCP ", "Dry Creek Photo"),
                (
                    "DCRC",
                    "Digital Contents Resource Center, Chung-Ang University",
                ),
                ("DELL", "Dell Computer Corporation"),
                ("DIC ", "Dainippon Ink and Chemicals"),
                ("DICO", "Diconix"),
                ("DIGI", "Digital"),
                ("DL&C", "Digital Light & Color"),
                ("DPLG", "Doppelganger, LLC"),
                ("DS  ", "Dainippon Screen"),
                ("DSOL", "DOOSOL"),
                ("DUPN", "DuPont"),
                ("EPSO", "Epson"),
                ("ESKO", "Esko-Graphics"),
                (
                    "ETRI",
                    "Electronics and Telecommunications Research Institute",
                ),
                ("EVER", "Everex Systems, Inc."),
                ("EXAC", "ExactCODE GmbH"),
                ("Eizo", "EIZO NANAO CORPORATION"),
                ("FALC", "Falco Data Products, Inc."),
                ("FF  ", "Fuji Photo Film Co.,LTD"),
                ("FFEI", "FujiFilm Electronic Imaging, Ltd."),
                ("FNRD", "fnord software"),
                ("FORA", "Fora, Inc."),
                ("FORE", "Forefront Technology Corporation"),
                ("FP  ", "Fujitsu"),
                ("FPA ", "WayTech Development, Inc."),
                ("FUJI", "Fujitsu"),
                ("FX  ", "Fuji Xerox Co., Ltd."),
                ("GCC ", "GCC Technologies, Inc."),
                ("GGSL", "Global Graphics Software Limited"),
                ("GMB ", "Gretagmacbeth"),
                ("GMG ", "GMG GmbH & Co. KG"),
                ("GOLD", "GoldStar Technology, Inc."),
                ("GOOG", "Google"),
                ("GPRT", "Giantprint Pty Ltd"),
                ("GTMB", "Gretagmacbeth"),
                ("GVC ", "WayTech Development, Inc."),
                ("GW2K", "Sony Corporation"),
                ("HCI ", "HCI"),
                ("HDM ", "Heidelberger Druckmaschinen AG"),
                ("HERM", "Hermes"),
                ("HITA", "Hitachi America, Ltd."),
                ("HP  ", "Hewlett-Packard"),
                ("HTC ", "Hitachi, Ltd."),
                ("HiTi", "HiTi Digital, Inc."),
                ("IBM ", "IBM Corporation"),
                ("IDNT", "Scitex Corporation, Ltd."),
                ("IEC ", "Hewlett-Packard"),
                ("IIYA", "Iiyama North America, Inc."),
                ("IKEG", "Ikegami Electronics, Inc."),
                ("IMAG", "Image Systems Corporation"),
                ("IMI ", "Ingram Micro, Inc."),
                ("INTC", "Intel Corporation"),
                ("INTL", "N/A (INTL)"),
                ("INTR", "Intra Electronics USA, Inc."),
                ("IOCO", "Iocomm International Technology Corporation"),
                ("IPS ", "InfoPrint Solutions Company"),
                ("IRIS", "Scitex Corporation, Ltd."),
                ("ISL ", "Ichikawa Soft Laboratory"),
                ("ITNL", "N/A (ITNL)"),
                ("IVM ", "IVM"),
                ("IWAT", "Iwatsu Electric Co., Ltd."),
                ("Idnt", "Scitex Corporation, Ltd."),
                ("Inca", "Inca Digital Printers Ltd."),
                ("Iris", "Scitex Corporation, Ltd."),
                ("JPEG", "Joint Photographic Experts Group"),
                ("JSFT", "Jetsoft Development"),
                ("JVC ", "JVC Information Products Co."),
                ("KART", "Scitex Corporation, Ltd."),
                ("KFC ", "KFC Computek Components Corporation"),
                ("KLH ", "KLH Computers"),
                ("KMHD", "Konica Minolta Holdings, Inc."),
                ("KNCA", "Konica Corporation"),
                ("KODA", "Kodak"),
                ("KYOC", "Kyocera"),
                ("Kart", "Scitex Corporation, Ltd."),
                ("LCAG", "Leica Camera AG"),
                ("LCCD", "Leeds Colour"),
                ("LDAK", "Left Dakota"),
                ("LEAD", "Leading Technology, Inc."),
                ("LEXM", "Lexmark International, Inc."),
                ("LINK", "Link Computer, Inc."),
                ("LINO", "Linotronic"),
                ("LITE", "Lite-On, Inc."),
                ("Leaf", "Leaf"),
                ("Lino", "Linotronic"),
                ("MAGC", "Mag Computronic (USA) Inc."),
                ("MAGI", "MAG Innovision, Inc."),
                ("MANN", "Mannesmann"),
                ("MICN", "Micron Technology, Inc."),
                ("MICR", "Microtek"),
                ("MICV", "Microvitec, Inc."),
                ("MINO", "Minolta"),
                ("MITS", "Mitsubishi Electronics America, Inc."),
                ("MITs", "Mitsuba Corporation"),
                ("MNLT", "Minolta"),
                ("MODG", "Modgraph, Inc."),
                ("MONI", "Monitronix, Inc."),
                ("MONS", "Monaco Systems Inc."),
                ("MORS", "Morse Technology, Inc."),
                ("MOTI", "Motive Systems"),
                ("MSFT", "Microsoft Corporation"),
                ("MUTO", "MUTOH INDUSTRIES LTD."),
                ("Mits", "Mitsubishi Electric Corporation Kyoto Works"),
                ("NANA", "NANAO USA Corporation"),
                ("NEC ", "NEC Corporation"),
                ("NEXP", "NexPress Solutions LLC"),
                ("NISS", "Nissei Sangyo America, Ltd."),
                ("NKON", "Nikon Corporation"),
                ("NONE", "none"),
                ("OCE ", "Oce Technologies B.V."),
                ("OCEC", "OceColor"),
                ("OKI ", "Oki"),
                ("OKID", "Okidata"),
                ("OKIP", "Okidata"),
                ("OLIV", "Olivetti"),
                ("OLYM", "OLYMPUS OPTICAL CO., LTD"),
                ("ONYX", "Onyx Graphics"),
                ("OPTI", "Optiquest"),
                ("PACK", "Packard Bell"),
                ("PANA", "Matsushita Electric Industrial Co., Ltd."),
                ("PANT", "Pantone, Inc."),
                ("PBN ", "Packard Bell"),
                ("PFU ", "PFU Limited"),
                ("PHIL", "Philips Consumer Electronics Co."),
                ("PNTX", "HOYA Corporation PENTAX Imaging Systems Division"),
                ("POne", "Phase One A/S"),
                ("PREM", "Premier Computer Innovations"),
                ("PRIN", "Princeton Graphic Systems"),
                ("PRIP", "Princeton Publishing Labs"),
                ("QLUX", "Hong Kong"),
                ("QMS ", "QMS, Inc."),
                ("QPCD", "QPcard AB"),
                ("QUAD", "QuadLaser"),
                ("QUME", "Qume Corporation"),
                ("RADI", "Radius, Inc."),
                ("RDDx", "Integrated Color Solutions, Inc."),
                ("RDG ", "Roland DG Corporation"),
                ("REDM", "REDMS Group, Inc."),
                ("RELI", "Relisys"),
                ("RGMS", "Rolf Gierling Multitools"),
                ("RICO", "Ricoh Corporation"),
                ("RNLD", "Edmund Ronald"),
                ("ROYA", "Royal"),
                ("RPC ", "Ricoh Printing Systems,Ltd."),
                ("RTL ", "Royal Information Electronics Co., Ltd."),
                ("SAMP", "Sampo Corporation of America"),
                ("SAMS", "Samsung, Inc."),
                ("SANT", "Jaime Santana Pomares"),
                ("SCIT", "Scitex Corporation, Ltd."),
                ("SCRN", "Dainippon Screen"),
                ("SDP ", "Scitex Corporation, Ltd."),
                ("SEC ", "SAMSUNG ELECTRONICS CO.,LTD"),
                ("SEIK", "Seiko Instruments U.S.A., Inc."),
                ("SEIk", "Seikosha"),
                ("SGUY", "ScanGuy.com"),
                ("SHAR", "Sharp Laboratories"),
                ("SICC", "International Color Consortium"),
                ("SONY", "SONY Corporation"),
                ("SPCL", "SpectraCal"),
                ("STAR", "Star"),
                ("STC ", "Sampo Technology Corporation"),
                ("Scit", "Scitex Corporation, Ltd."),
                ("Sdp ", "Scitex Corporation, Ltd."),
                ("Sony", "Sony Corporation"),
                ("TALO", "Talon Technology Corporation"),
                ("TAND", "Tandy"),
                ("TATU", "Tatung Co. of America, Inc."),
                ("TAXA", "TAXAN America, Inc."),
                ("TDS ", "Tokyo Denshi Sekei K.K."),
                ("TECO", "TECO Information Systems, Inc."),
                ("TEGR", "Tegra"),
                ("TEKT", "Tektronix, Inc."),
                ("TI  ", "Texas Instruments"),
                ("TMKR", "TypeMaker Ltd."),
                ("TOSB", "TOSHIBA corp."),
                ("TOSH", "Toshiba, Inc."),
                ("TOTK", "TOTOKU ELECTRIC Co., LTD"),
                ("TRIU", "Triumph"),
                ("TSBT", "TOSHIBA TEC CORPORATION"),
                ("TTX ", "TTX Computer Products, Inc."),
                ("TVM ", "TVM Professional Monitor Corporation"),
                ("TW  ", "TW Casper Corporation"),
                ("ULSX", "Ulead Systems"),
                ("UNIS", "Unisys"),
                ("UTZF", "Utz Fehlau & Sohn"),
                ("VARI", "Varityper"),
                ("VIEW", "Viewsonic"),
                ("VISL", "Visual communication"),
                ("VIVO", "Vivo Mobile Communication Co., Ltd"),
                ("WANG", "Wang"),
                ("WLBR", "Wilbur Imaging"),
                ("WTG2", "Ware To Go"),
                ("WYSE", "WYSE Technology"),
                ("XERX", "Xerox Corporation"),
                ("XM  ", "Xiaomi"),
                ("XRIT", "X-Rite"),
                ("Z123", "Lavanya's test Company"),
                ("ZRAN", "Zoran Corporation"),
                ("Zebr", "Zebra Technologies Inc"),
                ("appl", "Apple Computer Inc."),
                ("bICC", "basICColor GmbH"),
                ("berg", "bergdesign incorporated"),
                ("ceyd", "Integrated Color Solutions, Inc."),
                ("clsp", "MacDermid ColorSpan, Inc."),
                ("ds  ", "Dainippon Screen"),
                ("dupn", "DuPont"),
                ("ffei", "FujiFilm Electronic Imaging, Ltd."),
                ("flux", "FluxData Corporation"),
                ("iris", "Scitex Corporation, Ltd."),
                ("kart", "Scitex Corporation, Ltd."),
                ("lcms", "Little CMS"),
                ("lino", "Linotronic"),
                ("none", "none"),
                ("ob4d", "Erdt Systems GmbH & Co KG"),
                ("obic", "Medigraph GmbH"),
                ("quby", "Qubyx Sarl"),
                ("scit", "Scitex Corporation, Ltd."),
                ("scrn", "Dainippon Screen"),
                ("sdp ", "Scitex Corporation, Ltd."),
                ("siwi", "SIWI GRAFIKA CORPORATION"),
                ("yxym", "YxyMaster GmbH"),
            ]),
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 84,
            sub: None,
            name: "ProfileID",
            format: Some(Fmt::Int8u),
            count: 16,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::Expr(ExprId::ImageExifToolICCProfileHexIDVal9E9FB2),
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
    ],
    variants: &[],
};

/// `Image::ExifTool::ICC_Profile::Measurement` -- 5 fields,
/// 0 `_variants` groups (Step 23).
/// Generated from ExifTool's in-memory tag table. Do not edit by hand.
pub static ICC_PROFILE_MEASUREMENT: BinaryTable = BinaryTable {
    module: "ICC_Profile",
    table: "Measurement",
    group0: "ICC_Profile",
    group1: "ICC-meas",
    group2: "Image",
    first_entry: 0,
    default_format: Fmt::Int8u,
    offsets_sound_until: None,
    priority: None,
    gate_a: GateA {
        blocked_by: &[("expr_unsupported", 1)],
    },
    fields: &[
        Field {
            index: 8,
            sub: None,
            name: "MeasurementObserver",
            format: Some(Fmt::Int32u),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[(1, "CIE 1931"), (2, "CIE 1964")]),
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 12,
            sub: None,
            name: "MeasurementBacking",
            format: Some(Fmt::Fixed32s),
            count: 3,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 24,
            sub: None,
            name: "MeasurementGeometry",
            format: Some(Fmt::Int32u),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[
                (0, "Unknown"),
                (1, "0/45 or 45/0"),
                (2, "0/d or d/0"),
            ]),
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 28,
            sub: None,
            name: "MeasurementFlare",
            format: Some(Fmt::Fixed32u),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 32,
            sub: None,
            name: "MeasurementIlluminant",
            format: Some(Fmt::Int32u),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[
                (1, "D50"),
                (2, "D65"),
                (3, "D93"),
                (4, "F2"),
                (5, "D55"),
                (6, "A"),
                (7, "Equi-Power (E)"),
                (8, "F8"),
            ]),
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
    ],
    variants: &[],
};

/// `Image::ExifTool::ICC_Profile::ViewingConditions` -- 3 fields,
/// 0 `_variants` groups (Step 23).
/// Generated from ExifTool's in-memory tag table. Do not edit by hand.
pub static ICC_PROFILE_VIEWINGCONDITIONS: BinaryTable = BinaryTable {
    module: "ICC_Profile",
    table: "ViewingConditions",
    group0: "ICC_Profile",
    group1: "ICC-view",
    group2: "Image",
    first_entry: 0,
    default_format: Fmt::Int8u,
    offsets_sound_until: None,
    priority: None,
    gate_a: GateA { blocked_by: &[] },
    fields: &[
        Field {
            index: 8,
            sub: None,
            name: "ViewingCondIlluminant",
            format: Some(Fmt::Fixed32s),
            count: 3,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 20,
            sub: None,
            name: "ViewingCondSurround",
            format: Some(Fmt::Fixed32s),
            count: 3,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 32,
            sub: None,
            name: "ViewingCondIlluminantType",
            format: Some(Fmt::Int32u),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[
                (1, "D50"),
                (2, "D65"),
                (3, "D93"),
                (4, "F2"),
                (5, "D55"),
                (6, "A"),
                (7, "Equi-Power (E)"),
                (8, "F8"),
            ]),
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
    ],
    variants: &[],
};
