//! ExifTool `ICO` ProcessBinaryData tables, generated from ExifTool
//! 13.59's own Perl hashes -- one file per module; `mod.rs` beside this
//! file is the hub that declares and re-exports it.
//!
//! DO NOT EDIT. Regenerate with `just regen-tables` (see `mod.rs`).

#![allow(clippy::unreadable_literal, clippy::too_many_lines, unused_parens)]

// Everything a table literal names -- the schema types, `ExprId`, the
// `cond`/`subdir`/`ifd_schema` imports -- is in scope in the hub, and a glob
// import of the parent module brings its private imports along (RFC 1560).
#[allow(unused_imports)]
use super::*;

/// `Image::ExifTool::ICO::IconDir` -- 4 fields,
/// 2 `_variants` groups (Step 23).
/// Generated from ExifTool's in-memory tag table. Do not edit by hand.
pub static ICO_ICONDIR: BinaryTable = BinaryTable {
    module: "ICO",
    table: "IconDir",
    group0: "File",
    group1: "File",
    group2: "Image",
    first_entry: 0,
    default_format: Fmt::Int8u,
    offsets_sound_until: None,
    priority: None,
    gate_a: GateA { blocked_by: &[] },
    fields: &[
        Field {
            index: 0,
            sub: None,
            name: "ImageWidth",
            format: None,
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted {
                value_conv: true,
                raw_conv: false,
                condition: false,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 1,
            sub: None,
            name: "ImageHeight",
            format: None,
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted {
                value_conv: true,
                raw_conv: false,
                condition: false,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 2,
            sub: None,
            name: "NumColors",
            format: None,
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 8,
            sub: None,
            name: "ImageLength",
            format: Some(Fmt::Int32u),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
    ],
    variants: &[
        VariantGroup {
            index: 4,
            sub: None,
            alternatives: &[
                (
                    Cond::MemberStrEq {
                        member: "FileType",
                        value: "ICO",
                        negate: false,
                    },
                    Field {
                        index: 4,
                        sub: None,
                        name: "ColorPlanes",
                        format: Some(Fmt::Int16u),
                        count: 1,
                        mask: None,
                        condition: Some(Cond::MemberStrEq {
                            member: "FileType",
                            value: "ICO",
                            negate: false,
                        }),
                        raw_conv: None,
                        omitted: Omitted::NONE,
                        value_conv: None,
                        print_conv: PrintConv::None,
                        subdir: None,
                        hook: &[],
                        groups: TagGroups::NONE,
                    },
                ),
                (
                    Cond::Always,
                    Field {
                        index: 4,
                        sub: None,
                        name: "HotspotX",
                        format: Some(Fmt::Int16u),
                        count: 1,
                        mask: None,
                        condition: None,
                        raw_conv: None,
                        omitted: Omitted::NONE,
                        value_conv: None,
                        print_conv: PrintConv::None,
                        subdir: None,
                        hook: &[],
                        groups: TagGroups::NONE,
                    },
                ),
            ],
        },
        VariantGroup {
            index: 6,
            sub: None,
            alternatives: &[
                (
                    Cond::MemberStrEq {
                        member: "FileType",
                        value: "ICO",
                        negate: false,
                    },
                    Field {
                        index: 6,
                        sub: None,
                        name: "BitsPerPixel",
                        format: Some(Fmt::Int16u),
                        count: 1,
                        mask: None,
                        condition: Some(Cond::MemberStrEq {
                            member: "FileType",
                            value: "ICO",
                            negate: false,
                        }),
                        raw_conv: None,
                        omitted: Omitted::NONE,
                        value_conv: None,
                        print_conv: PrintConv::None,
                        subdir: None,
                        hook: &[],
                        groups: TagGroups::NONE,
                    },
                ),
                (
                    Cond::Always,
                    Field {
                        index: 6,
                        sub: None,
                        name: "HotspotY",
                        format: Some(Fmt::Int16u),
                        count: 1,
                        mask: None,
                        condition: None,
                        raw_conv: None,
                        omitted: Omitted::NONE,
                        value_conv: None,
                        print_conv: PrintConv::None,
                        subdir: None,
                        hook: &[],
                        groups: TagGroups::NONE,
                    },
                ),
            ],
        },
    ],
};

/// `Image::ExifTool::ICO::Main` -- 3 fields,
/// 0 `_variants` groups (Step 23).
/// Generated from ExifTool's in-memory tag table. Do not edit by hand.
pub static ICO_MAIN: BinaryTable = BinaryTable {
    module: "ICO",
    table: "Main",
    group0: "File",
    group1: "File",
    group2: "Image",
    first_entry: 0,
    default_format: Fmt::Int8u,
    offsets_sound_until: None,
    priority: None,
    gate_a: GateA { blocked_by: &[] },
    fields: &[
        Field {
            index: 2,
            sub: None,
            name: "ImageType",
            format: Some(Fmt::Int16u),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[(1, "Icon"), (2, "Cursor")]),
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 4,
            sub: None,
            name: "ImageCount",
            format: Some(Fmt::Int16u),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: Some(RawConvEffect::SetMember {
                member: "ImageCount",
            }),
            omitted: Omitted {
                value_conv: false,
                raw_conv: true,
                condition: false,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 6,
            sub: None,
            name: "IconDir",
            format: None,
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: false,
                condition: false,
                hook: false,
                subdirectory: true,
                print_conv: false,
            },
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: Some(SubdirEdge {
                module: "ICO",
                table: "IconDir",
                start: Start::FieldRelative(0),
                base: None,
                byte_order: None,
                validate: false,
            }),
            hook: &[],
            groups: TagGroups::NONE,
        },
    ],
    variants: &[],
};
