//! ExifTool `ID3` ProcessBinaryData tables, generated from ExifTool
//! 13.59's own Perl hashes -- one file per module; `mod.rs` beside this
//! file is the hub that declares and re-exports it.
//!
//! DO NOT EDIT. Regenerate with `just regen-tables` (see `mod.rs`).

#![allow(clippy::unreadable_literal, clippy::too_many_lines, unused_parens)]

// Everything a table literal names -- the schema types, `ExprId`, the
// `cond`/`subdir`/`ifd_schema` imports -- is in scope in the hub, and a glob
// import of the parent module brings its private imports along (RFC 1560).
#[allow(unused_imports)]
use super::*;

/// `Image::ExifTool::ID3::v1` -- 7 fields,
/// 0 `_variants` groups (Step 23).
/// Generated from ExifTool's in-memory tag table. Do not edit by hand.
pub static ID3_V1: BinaryTable = BinaryTable {
    module: "ID3",
    table: "v1",
    group0: "ID3",
    group1: "ID3v1",
    group2: "Audio",
    first_entry: 0,
    default_format: Fmt::Int8u,
    offsets_sound_until: None,
    priority: Some(0),
    gate_a: GateA { blocked_by: &[] },
    fields: &[
        Field {
            index: 3,
            sub: None,
            name: "Title",
            format: Some(Fmt::Str(30)),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted {
                value_conv: true,
                raw_conv: false,
                condition: false,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 33,
            sub: None,
            name: "Artist",
            format: Some(Fmt::Str(30)),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted {
                value_conv: true,
                raw_conv: false,
                condition: false,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups {
                g0: None,
                g1: None,
                g2: Some("Author"),
            },
        },
        Field {
            index: 63,
            sub: None,
            name: "Album",
            format: Some(Fmt::Str(30)),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted {
                value_conv: true,
                raw_conv: false,
                condition: false,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 93,
            sub: None,
            name: "Year",
            format: Some(Fmt::Str(4)),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups {
                g0: None,
                g1: None,
                g2: Some("Time"),
            },
        },
        Field {
            index: 97,
            sub: None,
            name: "Comment",
            format: Some(Fmt::Str(30)),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted {
                value_conv: true,
                raw_conv: false,
                condition: false,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 125,
            sub: None,
            name: "Track",
            format: Some(Fmt::Int8u),
            count: 2,
            mask: None,
            condition: None,
            raw_conv: Some(RawConvEffect::ValueLocal),
            omitted: Omitted {
                value_conv: false,
                raw_conv: true,
                condition: false,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 127,
            sub: None,
            name: "Genre",
            format: Some(Fmt::Int8u),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::StrEnum(&[
                ("0", "Blues"),
                ("1", "Classic Rock"),
                ("10", "New Age"),
                ("100", "Humour"),
                ("101", "Speech"),
                ("102", "Chanson"),
                ("103", "Opera"),
                ("104", "Chamber Music"),
                ("105", "Sonata"),
                ("106", "Symphony"),
                ("107", "Booty Bass"),
                ("108", "Primus"),
                ("109", "Porn Groove"),
                ("11", "Oldies"),
                ("110", "Satire"),
                ("111", "Slow Jam"),
                ("112", "Club"),
                ("113", "Tango"),
                ("114", "Samba"),
                ("115", "Folklore"),
                ("116", "Ballad"),
                ("117", "Power Ballad"),
                ("118", "Rhythmic Soul"),
                ("119", "Freestyle"),
                ("12", "Other"),
                ("120", "Duet"),
                ("121", "Punk Rock"),
                ("122", "Drum Solo"),
                ("123", "A Cappella"),
                ("124", "Euro-House"),
                ("125", "Dance Hall"),
                ("126", "Goa"),
                ("127", "Drum & Bass"),
                ("128", "Club-House"),
                ("129", "Hardcore"),
                ("13", "Pop"),
                ("130", "Terror"),
                ("131", "Indie"),
                ("132", "BritPop"),
                ("133", "Afro-Punk"),
                ("134", "Polsk Punk"),
                ("135", "Beat"),
                ("136", "Christian Gangsta Rap"),
                ("137", "Heavy Metal"),
                ("138", "Black Metal"),
                ("139", "Crossover"),
                ("14", "R&B"),
                ("140", "Contemporary Christian"),
                ("141", "Christian Rock"),
                ("142", "Merengue"),
                ("143", "Salsa"),
                ("144", "Thrash Metal"),
                ("145", "Anime"),
                ("146", "JPop"),
                ("147", "Synthpop"),
                ("148", "Abstract"),
                ("149", "Art Rock"),
                ("15", "Rap"),
                ("150", "Baroque"),
                ("151", "Bhangra"),
                ("152", "Big Beat"),
                ("153", "Breakbeat"),
                ("154", "Chillout"),
                ("155", "Downtempo"),
                ("156", "Dub"),
                ("157", "EBM"),
                ("158", "Eclectic"),
                ("159", "Electro"),
                ("16", "Reggae"),
                ("160", "Electroclash"),
                ("161", "Emo"),
                ("162", "Experimental"),
                ("163", "Garage"),
                ("164", "Global"),
                ("165", "IDM"),
                ("166", "Illbient"),
                ("167", "Industro-Goth"),
                ("168", "Jam Band"),
                ("169", "Krautrock"),
                ("17", "Rock"),
                ("170", "Leftfield"),
                ("171", "Lounge"),
                ("172", "Math Rock"),
                ("173", "New Romantic"),
                ("174", "Nu-Breakz"),
                ("175", "Post-Punk"),
                ("176", "Post-Rock"),
                ("177", "Psytrance"),
                ("178", "Shoegaze"),
                ("179", "Space Rock"),
                ("18", "Techno"),
                ("180", "Trop Rock"),
                ("181", "World Music"),
                ("182", "Neoclassical"),
                ("183", "Audiobook"),
                ("184", "Audio Theatre"),
                ("185", "Neue Deutsche Welle"),
                ("186", "Podcast"),
                ("187", "Indie Rock"),
                ("188", "G-Funk"),
                ("189", "Dubstep"),
                ("19", "Industrial"),
                ("190", "Garage Rock"),
                ("191", "Psybient"),
                ("2", "Country"),
                ("20", "Alternative"),
                ("21", "Ska"),
                ("22", "Death Metal"),
                ("23", "Pranks"),
                ("24", "Soundtrack"),
                ("25", "Euro-Techno"),
                ("255", "None"),
                ("26", "Ambient"),
                ("27", "Trip-Hop"),
                ("28", "Vocal"),
                ("29", "Jazz+Funk"),
                ("3", "Dance"),
                ("30", "Fusion"),
                ("31", "Trance"),
                ("32", "Classical"),
                ("33", "Instrumental"),
                ("34", "Acid"),
                ("35", "House"),
                ("36", "Game"),
                ("37", "Sound Clip"),
                ("38", "Gospel"),
                ("39", "Noise"),
                ("4", "Disco"),
                ("40", "Alt. Rock"),
                ("41", "Bass"),
                ("42", "Soul"),
                ("43", "Punk"),
                ("44", "Space"),
                ("45", "Meditative"),
                ("46", "Instrumental Pop"),
                ("47", "Instrumental Rock"),
                ("48", "Ethnic"),
                ("49", "Gothic"),
                ("5", "Funk"),
                ("50", "Darkwave"),
                ("51", "Techno-Industrial"),
                ("52", "Electronic"),
                ("53", "Pop-Folk"),
                ("54", "Eurodance"),
                ("55", "Dream"),
                ("56", "Southern Rock"),
                ("57", "Comedy"),
                ("58", "Cult"),
                ("59", "Gangsta Rap"),
                ("6", "Grunge"),
                ("60", "Top 40"),
                ("61", "Christian Rap"),
                ("62", "Pop/Funk"),
                ("63", "Jungle"),
                ("64", "Native American"),
                ("65", "Cabaret"),
                ("66", "New Wave"),
                ("67", "Psychedelic"),
                ("68", "Rave"),
                ("69", "Showtunes"),
                ("7", "Hip-Hop"),
                ("70", "Trailer"),
                ("71", "Lo-Fi"),
                ("72", "Tribal"),
                ("73", "Acid Punk"),
                ("74", "Acid Jazz"),
                ("75", "Polka"),
                ("76", "Retro"),
                ("77", "Musical"),
                ("78", "Rock & Roll"),
                ("79", "Hard Rock"),
                ("8", "Jazz"),
                ("80", "Folk"),
                ("81", "Folk-Rock"),
                ("82", "National Folk"),
                ("83", "Swing"),
                ("84", "Fast-Fusion"),
                ("85", "Bebop"),
                ("86", "Latin"),
                ("87", "Revival"),
                ("88", "Celtic"),
                ("89", "Bluegrass"),
                ("9", "Metal"),
                ("90", "Avantgarde"),
                ("91", "Gothic Rock"),
                ("92", "Progressive Rock"),
                ("93", "Psychedelic Rock"),
                ("94", "Symphonic Rock"),
                ("95", "Slow Rock"),
                ("96", "Big Band"),
                ("97", "Chorus"),
                ("98", "Easy Listening"),
                ("99", "Acoustic"),
                ("CR", "Cover"),
                ("RX", "Remix"),
            ]),
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
    ],
    variants: &[],
};

/// `Image::ExifTool::ID3::v1_Enh` -- 7 fields,
/// 0 `_variants` groups (Step 23).
/// Generated from ExifTool's in-memory tag table. Do not edit by hand.
pub static ID3_V1_ENH: BinaryTable = BinaryTable {
    module: "ID3",
    table: "v1_Enh",
    group0: "ID3",
    group1: "ID3v1_Enh",
    group2: "Audio",
    first_entry: 0,
    default_format: Fmt::Int8u,
    offsets_sound_until: None,
    priority: Some(0),
    gate_a: GateA { blocked_by: &[] },
    fields: &[
        Field {
            index: 4,
            sub: None,
            name: "Title2",
            format: Some(Fmt::Str(60)),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted {
                value_conv: true,
                raw_conv: false,
                condition: false,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 64,
            sub: None,
            name: "Artist2",
            format: Some(Fmt::Str(60)),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted {
                value_conv: true,
                raw_conv: false,
                condition: false,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups {
                g0: None,
                g1: None,
                g2: Some("Author"),
            },
        },
        Field {
            index: 124,
            sub: None,
            name: "Album2",
            format: Some(Fmt::Str(60)),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted {
                value_conv: true,
                raw_conv: false,
                condition: false,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 184,
            sub: None,
            name: "Speed",
            format: Some(Fmt::Int8u),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[
                (1, "Slow"),
                (2, "Medium"),
                (3, "Fast"),
                (4, "Hardcore"),
            ]),
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 185,
            sub: None,
            name: "Genre",
            format: Some(Fmt::Str(30)),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted {
                value_conv: true,
                raw_conv: false,
                condition: false,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 215,
            sub: None,
            name: "StartTime",
            format: Some(Fmt::Str(6)),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 221,
            sub: None,
            name: "EndTime",
            format: Some(Fmt::Str(6)),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
    ],
    variants: &[],
};
