//! ExifTool `Jpeg2000` ProcessBinaryData tables, generated from ExifTool
//! 13.59's own Perl hashes -- one file per module; `mod.rs` beside this
//! file is the hub that declares and re-exports it.
//!
//! DO NOT EDIT. Regenerate with `just regen-tables` (see `mod.rs`).

#![allow(clippy::unreadable_literal, clippy::too_many_lines, unused_parens)]

// Everything a table literal names -- the schema types, `ExprId`, the
// `cond`/`subdir`/`ifd_schema` imports -- is in scope in the hub, and a glob
// import of the parent module brings its private imports along (RFC 1560).
#[allow(unused_imports)]
use super::*;

/// `Image::ExifTool::Jpeg2000::CaptureResolution` -- 4 fields,
/// 0 `_variants` groups (Step 23).
/// Generated from ExifTool's in-memory tag table. Do not edit by hand.
pub static JPEG2000_CAPTURERESOLUTION: BinaryTable = BinaryTable {
    module: "Jpeg2000",
    table: "CaptureResolution",
    group0: "Jpeg2000",
    group1: "Jpeg2000",
    group2: "Image",
    first_entry: 0,
    default_format: Fmt::Int8s,
    offsets_sound_until: None,
    priority: None,
    gate_a: GateA { blocked_by: &[] },
    fields: &[
        Field {
            index: 0,
            sub: None,
            name: "CaptureYResolution",
            format: Some(Fmt::Rational32u),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 4,
            sub: None,
            name: "CaptureXResolution",
            format: Some(Fmt::Rational32u),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 8,
            sub: None,
            name: "CaptureYResolutionUnit",
            format: None,
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[
                (-3, "km"),
                (-2, "100 m"),
                (-1, "10 m"),
                (0, "m"),
                (1, "10 cm"),
                (2, "cm"),
                (3, "mm"),
                (4, "0.1 mm"),
                (5, "0.01 mm"),
                (6, "um"),
            ]),
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 9,
            sub: None,
            name: "CaptureXResolutionUnit",
            format: None,
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[
                (-3, "km"),
                (-2, "100 m"),
                (-1, "10 m"),
                (0, "m"),
                (1, "10 cm"),
                (2, "cm"),
                (3, "mm"),
                (4, "0.1 mm"),
                (5, "0.01 mm"),
                (6, "um"),
            ]),
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
    ],
    variants: &[],
};

/// `Image::ExifTool::Jpeg2000::ColorSpec` -- 3 fields,
/// 0 `_variants` groups (Step 23).
/// Generated from ExifTool's in-memory tag table. Do not edit by hand.
pub static JPEG2000_COLORSPEC: BinaryTable = BinaryTable {
    module: "Jpeg2000",
    table: "ColorSpec",
    group0: "Jpeg2000",
    group1: "Jpeg2000",
    group2: "Image",
    first_entry: 0,
    default_format: Fmt::Int8s,
    offsets_sound_until: None,
    priority: None,
    gate_a: GateA {
        blocked_by: &[
            ("tag_variant_field_unsupported", 1),
            ("tag_variant_skipped", 1),
        ],
    },
    fields: &[
        Field {
            index: 0,
            sub: None,
            name: "ColorSpecMethod",
            format: None,
            count: 1,
            mask: None,
            condition: None,
            raw_conv: Some(RawConvEffect::SetMember {
                member: "ColorSpecMethod",
            }),
            omitted: Omitted {
                value_conv: false,
                raw_conv: true,
                condition: false,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[
                (1, "Enumerated"),
                (2, "Restricted ICC"),
                (3, "Any ICC"),
                (4, "Vendor Color"),
            ]),
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 1,
            sub: None,
            name: "ColorSpecPrecedence",
            format: None,
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 2,
            sub: None,
            name: "ColorSpecApproximation",
            format: None,
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[
                (0, "Not Specified"),
                (1, "Accurate"),
                (2, "Exceptional Quality"),
                (3, "Reasonable Quality"),
                (4, "Poor Quality"),
            ]),
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
    ],
    variants: &[],
};

/// `Image::ExifTool::Jpeg2000::DisplayResolution` -- 4 fields,
/// 0 `_variants` groups (Step 23).
/// Generated from ExifTool's in-memory tag table. Do not edit by hand.
pub static JPEG2000_DISPLAYRESOLUTION: BinaryTable = BinaryTable {
    module: "Jpeg2000",
    table: "DisplayResolution",
    group0: "Jpeg2000",
    group1: "Jpeg2000",
    group2: "Image",
    first_entry: 0,
    default_format: Fmt::Int8s,
    offsets_sound_until: None,
    priority: None,
    gate_a: GateA { blocked_by: &[] },
    fields: &[
        Field {
            index: 0,
            sub: None,
            name: "DisplayYResolution",
            format: Some(Fmt::Rational32u),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 4,
            sub: None,
            name: "DisplayXResolution",
            format: Some(Fmt::Rational32u),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 8,
            sub: None,
            name: "DisplayYResolutionUnit",
            format: None,
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[
                (-3, "km"),
                (-2, "100 m"),
                (-1, "10 m"),
                (0, "m"),
                (1, "10 cm"),
                (2, "cm"),
                (3, "mm"),
                (4, "0.1 mm"),
                (5, "0.01 mm"),
                (6, "um"),
            ]),
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 9,
            sub: None,
            name: "DisplayXResolutionUnit",
            format: None,
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[
                (-3, "km"),
                (-2, "100 m"),
                (-1, "10 m"),
                (0, "m"),
                (1, "10 cm"),
                (2, "cm"),
                (3, "mm"),
                (4, "0.1 mm"),
                (5, "0.01 mm"),
                (6, "um"),
            ]),
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
    ],
    variants: &[],
};

/// `Image::ExifTool::Jpeg2000::FileType` -- 2 fields,
/// 0 `_variants` groups (Step 23).
/// Generated from ExifTool's in-memory tag table. Do not edit by hand.
pub static JPEG2000_FILETYPE: BinaryTable = BinaryTable {
    module: "Jpeg2000",
    table: "FileType",
    group0: "Jpeg2000",
    group1: "Jpeg2000",
    group2: "Video",
    first_entry: 0,
    default_format: Fmt::Int32u,
    offsets_sound_until: None,
    priority: None,
    gate_a: GateA {
        blocked_by: &[("tag_fmt_unsupported", 1)],
    },
    fields: &[
        Field {
            index: 0,
            sub: None,
            name: "MajorBrand",
            format: Some(Fmt::Undef(4)),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::StrEnum(&[
                ("jp2 ", "JPEG 2000 Image (.JP2)"),
                ("jph ", "High-throughput JPEG 2000 (.JPH)"),
                ("jpm ", "JPEG 2000 Compound Image (.JPM)"),
                ("jpx ", "JPEG 2000 with extensions (.JPX)"),
                ("jxl ", "JPEG XL Image (.JXL)"),
            ]),
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 1,
            sub: None,
            name: "MinorVersion",
            format: Some(Fmt::Undef(4)),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted {
                value_conv: true,
                raw_conv: false,
                condition: false,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
    ],
    variants: &[],
};

/// `Image::ExifTool::Jpeg2000::ImageHeader` -- 5 fields,
/// 0 `_variants` groups (Step 23).
/// Generated from ExifTool's in-memory tag table. Do not edit by hand.
pub static JPEG2000_IMAGEHEADER: BinaryTable = BinaryTable {
    module: "Jpeg2000",
    table: "ImageHeader",
    group0: "Jpeg2000",
    group1: "Jpeg2000",
    group2: "Image",
    first_entry: 0,
    default_format: Fmt::Int8u,
    offsets_sound_until: None,
    priority: None,
    gate_a: GateA {
        blocked_by: &[("expr_unsupported", 1)],
    },
    fields: &[
        Field {
            index: 0,
            sub: None,
            name: "ImageHeight",
            format: Some(Fmt::Int32u),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 4,
            sub: None,
            name: "ImageWidth",
            format: Some(Fmt::Int32u),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 8,
            sub: None,
            name: "NumberOfComponents",
            format: Some(Fmt::Int16u),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 10,
            sub: None,
            name: "BitsPerComponent",
            format: None,
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 11,
            sub: None,
            name: "Compression",
            format: None,
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[
                (0, "Uncompressed"),
                (1, "Modified Huffman"),
                (2, "Modified READ"),
                (3, "Modified Modified READ"),
                (4, "JBIG"),
                (5, "JPEG"),
                (6, "JPEG-LS"),
                (7, "JPEG 2000"),
                (8, "JBIG2"),
            ]),
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
    ],
    variants: &[],
};
