//! ExifTool `KyoceraRaw` ProcessBinaryData tables, generated from ExifTool
//! 13.59's own Perl hashes -- one file per module; `mod.rs` beside this
//! file is the hub that declares and re-exports it.
//!
//! DO NOT EDIT. Regenerate with `just regen-tables` (see `mod.rs`).

#![allow(clippy::unreadable_literal, clippy::too_many_lines, unused_parens)]

// Everything a table literal names -- the schema types, `ExprId`, the
// `cond`/`subdir`/`ifd_schema` imports -- is in scope in the hub, and a glob
// import of the parent module brings its private imports along (RFC 1560).
#[allow(unused_imports)]
use super::*;

/// `Image::ExifTool::KyoceraRaw::Main` -- 11 fields,
/// 0 `_variants` groups (Step 23).
/// Generated from ExifTool's in-memory tag table. Do not edit by hand.
pub static KYOCERARAW_MAIN: BinaryTable = BinaryTable {
    module: "KyoceraRaw",
    table: "Main",
    group0: "MakerNotes",
    group1: "KyoceraRaw",
    group2: "Camera",
    first_entry: 0,
    default_format: Fmt::Int8u,
    offsets_sound_until: None,
    priority: None,
    gate_a: GateA { blocked_by: &[] },
    fields: &[
        Field {
            index: 1,
            sub: None,
            name: "FirmwareVersion",
            format: Some(Fmt::Str(10)),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted {
                value_conv: true,
                raw_conv: false,
                condition: false,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 12,
            sub: None,
            name: "Model",
            format: Some(Fmt::Str(12)),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted {
                value_conv: true,
                raw_conv: false,
                condition: false,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 25,
            sub: None,
            name: "Make",
            format: Some(Fmt::Str(7)),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted {
                value_conv: true,
                raw_conv: false,
                condition: false,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 33,
            sub: None,
            name: "DateTimeOriginal",
            format: Some(Fmt::Str(20)),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted {
                value_conv: true,
                raw_conv: false,
                condition: false,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            value_conv: None,
            print_conv: PrintConv::Expr(ExprId::SelfConvertDateTimeVal7455B8),
            subdir: None,
            hook: &[],
            groups: TagGroups {
                g0: None,
                g1: None,
                g2: Some("Time"),
            },
        },
        Field {
            index: 52,
            sub: None,
            name: "ISO",
            format: Some(Fmt::Int32u),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[
                (7, "25"),
                (8, "32"),
                (9, "40"),
                (10, "50"),
                (11, "64"),
                (12, "80"),
                (13, "100"),
                (14, "125"),
                (15, "160"),
                (16, "200"),
                (17, "250"),
                (18, "320"),
                (19, "400"),
            ]),
            subdir: None,
            hook: &[],
            groups: TagGroups {
                g0: None,
                g1: None,
                g2: Some("Image"),
            },
        },
        Field {
            index: 56,
            sub: None,
            name: "ExposureTime",
            format: Some(Fmt::Int32u),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: Some(ExprId::E2Val816000BBEF9E),
            print_conv: PrintConv::Expr(ExprId::ImageExifToolExifPrintExposureTimeVal6037F3),
            subdir: None,
            hook: &[],
            groups: TagGroups {
                g0: None,
                g1: None,
                g2: Some("Image"),
            },
        },
        Field {
            index: 60,
            sub: None,
            name: "WB_RGGBLevels",
            format: Some(Fmt::Int32u),
            count: 4,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups {
                g0: None,
                g1: None,
                g2: Some("Image"),
            },
        },
        Field {
            index: 88,
            sub: None,
            name: "FNumber",
            format: Some(Fmt::Int32u),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: Some(ExprId::E2Val16E52048),
            print_conv: PrintConv::Expr(ExprId::Sprintf2gVal8ABE8F),
            subdir: None,
            hook: &[],
            groups: TagGroups {
                g0: None,
                g1: None,
                g2: Some("Image"),
            },
        },
        Field {
            index: 104,
            sub: None,
            name: "MaxAperture",
            format: Some(Fmt::Int32u),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: Some(ExprId::E2Val16E52048),
            print_conv: PrintConv::Expr(ExprId::Sprintf2gVal8ABE8F),
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 112,
            sub: None,
            name: "FocalLength",
            format: Some(Fmt::Int32u),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::Expr(ExprId::ValMm18ABDF),
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 124,
            sub: None,
            name: "Lens",
            format: Some(Fmt::Str(32)),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
    ],
    variants: &[],
};
