//! ExifTool `MinoltaRaw` ProcessBinaryData tables, generated from ExifTool
//! 13.59's own Perl hashes -- one file per module; `mod.rs` beside this
//! file is the hub that declares and re-exports it.
//!
//! DO NOT EDIT. Regenerate with `just regen-tables` (see `mod.rs`).

#![allow(clippy::unreadable_literal, clippy::too_many_lines, unused_parens)]

// Everything a table literal names -- the schema types, `ExprId`, the
// `cond`/`subdir`/`ifd_schema` imports -- is in scope in the hub, and a glob
// import of the parent module brings its private imports along (RFC 1560).
#[allow(unused_imports)]
use super::*;

/// `Image::ExifTool::MinoltaRaw::PRD` -- 9 fields,
/// 0 `_variants` groups (Step 23).
/// Generated from ExifTool's in-memory tag table. Do not edit by hand.
pub static MINOLTARAW_PRD: BinaryTable = BinaryTable {
    module: "MinoltaRaw",
    table: "PRD",
    group0: "MakerNotes",
    group1: "MinoltaRaw",
    group2: "Camera",
    first_entry: 0,
    default_format: Fmt::Int8u,
    offsets_sound_until: None,
    priority: None,
    gate_a: GateA { blocked_by: &[] },
    fields: &[
        Field {
            index: 0,
            sub: None,
            name: "FirmwareID",
            format: Some(Fmt::Str(8)),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: true,
                condition: false,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 8,
            sub: None,
            name: "SensorHeight",
            format: Some(Fmt::Int16u),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 10,
            sub: None,
            name: "SensorWidth",
            format: Some(Fmt::Int16u),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 12,
            sub: None,
            name: "ImageHeight",
            format: Some(Fmt::Int16u),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 14,
            sub: None,
            name: "ImageWidth",
            format: Some(Fmt::Int16u),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 16,
            sub: None,
            name: "RawDepth",
            format: Some(Fmt::Int8u),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 17,
            sub: None,
            name: "BitDepth",
            format: Some(Fmt::Int8u),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 18,
            sub: None,
            name: "StorageMethod",
            format: Some(Fmt::Int8u),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[(82, "Padded"), (89, "Linear")]),
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 23,
            sub: None,
            name: "BayerPattern",
            format: Some(Fmt::Int8u),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[(1, "RGGB"), (4, "GBRG")]),
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
    ],
    variants: &[],
};

/// `Image::ExifTool::MinoltaRaw::RIF` -- 27 fields,
/// 1 `_variants` groups (Step 23).
/// Generated from ExifTool's in-memory tag table. Do not edit by hand.
pub static MINOLTARAW_RIF: BinaryTable = BinaryTable {
    module: "MinoltaRaw",
    table: "RIF",
    group0: "MakerNotes",
    group1: "MinoltaRaw",
    group2: "Image",
    first_entry: 0,
    default_format: Fmt::Int8u,
    offsets_sound_until: None,
    priority: None,
    gate_a: GateA {
        blocked_by: &[("expr_unsupported", 1), ("other_unregistered", 1)],
    },
    fields: &[
        Field {
            index: 1,
            sub: None,
            name: "Saturation",
            format: Some(Fmt::Int8s),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 2,
            sub: None,
            name: "Contrast",
            format: Some(Fmt::Int8s),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 3,
            sub: None,
            name: "Sharpness",
            format: Some(Fmt::Int8s),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 4,
            sub: None,
            name: "WBMode",
            format: None,
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 5,
            sub: None,
            name: "ProgramMode",
            format: None,
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[
                (0, "None"),
                (1, "Portrait"),
                (2, "Text"),
                (3, "Night Portrait"),
                (4, "Sunset"),
                (5, "Sports"),
            ]),
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 6,
            sub: None,
            name: "ISOSetting",
            format: None,
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: true,
                condition: false,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 8,
            sub: None,
            name: "WB_RBLevelsTungsten",
            format: Some(Fmt::Int16u),
            count: 2,
            mask: None,
            condition: Some(Cond::Or(
                &Cond::MemberStrEq {
                    member: "Model",
                    value: "DSLR-A100",
                    negate: false,
                },
                &Cond::MemberTruthy {
                    member: "MinoltaPRD",
                    negate: false,
                },
            )),
            raw_conv: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: false,
                condition: true,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 12,
            sub: None,
            name: "WB_RBLevelsDaylight",
            format: Some(Fmt::Int16u),
            count: 2,
            mask: None,
            condition: Some(Cond::Or(
                &Cond::MemberStrEq {
                    member: "Model",
                    value: "DSLR-A100",
                    negate: false,
                },
                &Cond::MemberTruthy {
                    member: "MinoltaPRD",
                    negate: false,
                },
            )),
            raw_conv: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: false,
                condition: true,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 16,
            sub: None,
            name: "WB_RBLevelsCloudy",
            format: Some(Fmt::Int16u),
            count: 2,
            mask: None,
            condition: Some(Cond::Or(
                &Cond::MemberStrEq {
                    member: "Model",
                    value: "DSLR-A100",
                    negate: false,
                },
                &Cond::MemberTruthy {
                    member: "MinoltaPRD",
                    negate: false,
                },
            )),
            raw_conv: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: false,
                condition: true,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 20,
            sub: None,
            name: "WB_RBLevelsCoolWhiteF",
            format: Some(Fmt::Int16u),
            count: 2,
            mask: None,
            condition: Some(Cond::Or(
                &Cond::MemberStrEq {
                    member: "Model",
                    value: "DSLR-A100",
                    negate: false,
                },
                &Cond::MemberTruthy {
                    member: "MinoltaPRD",
                    negate: false,
                },
            )),
            raw_conv: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: false,
                condition: true,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 24,
            sub: None,
            name: "WB_RBLevelsFlash",
            format: Some(Fmt::Int16u),
            count: 2,
            mask: None,
            condition: Some(Cond::Or(
                &Cond::MemberStrEq {
                    member: "Model",
                    value: "DSLR-A100",
                    negate: false,
                },
                &Cond::MemberTruthy {
                    member: "MinoltaPRD",
                    negate: false,
                },
            )),
            raw_conv: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: false,
                condition: true,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 28,
            sub: None,
            name: "WB_RBLevelsCustom",
            format: Some(Fmt::Int16u),
            count: 2,
            mask: None,
            condition: Some(Cond::Or(
                &Cond::MemberStrEq {
                    member: "Model",
                    value: "DSLR-A100",
                    negate: false,
                },
                &Cond::MemberTruthy {
                    member: "MinoltaPRD",
                    negate: false,
                },
            )),
            raw_conv: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: false,
                condition: true,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 32,
            sub: None,
            name: "WB_RBLevelsShade",
            format: Some(Fmt::Int16u),
            count: 2,
            mask: None,
            condition: Some(Cond::MemberStrEq {
                member: "Model",
                value: "DSLR-A100",
                negate: false,
            }),
            raw_conv: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: false,
                condition: true,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 36,
            sub: None,
            name: "WB_RBLevelsDaylightF",
            format: Some(Fmt::Int16u),
            count: 2,
            mask: None,
            condition: Some(Cond::MemberStrEq {
                member: "Model",
                value: "DSLR-A100",
                negate: false,
            }),
            raw_conv: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: false,
                condition: true,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 40,
            sub: None,
            name: "WB_RBLevelsDayWhiteF",
            format: Some(Fmt::Int16u),
            count: 2,
            mask: None,
            condition: Some(Cond::MemberStrEq {
                member: "Model",
                value: "DSLR-A100",
                negate: false,
            }),
            raw_conv: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: false,
                condition: true,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 44,
            sub: None,
            name: "WB_RBLevelsWhiteF",
            format: Some(Fmt::Int16u),
            count: 2,
            mask: None,
            condition: Some(Cond::MemberStrEq {
                member: "Model",
                value: "DSLR-A100",
                negate: false,
            }),
            raw_conv: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: false,
                condition: true,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 56,
            sub: None,
            name: "ColorFilter",
            format: Some(Fmt::Int8s),
            count: 1,
            mask: None,
            condition: Some(Cond::MemberRegex {
                member: "Make",
                pattern: "^SONY",
                ignore_case: false,
                negate: true,
            }),
            raw_conv: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: false,
                condition: true,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 57,
            sub: None,
            name: "BWFilter",
            format: None,
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 58,
            sub: None,
            name: "ZoneMatching",
            format: None,
            count: 1,
            mask: None,
            condition: Some(Cond::MemberRegex {
                member: "Make",
                pattern: "^SONY",
                ignore_case: false,
                negate: true,
            }),
            raw_conv: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: false,
                condition: true,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[
                (0, "ISO Setting Used"),
                (1, "High Key"),
                (2, "Low Key"),
            ]),
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 59,
            sub: None,
            name: "Hue",
            format: Some(Fmt::Int8s),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 60,
            sub: None,
            name: "ColorTemperature",
            format: None,
            count: 1,
            mask: None,
            condition: Some(Cond::MemberRegex {
                member: "Make",
                pattern: "^SONY",
                ignore_case: false,
                negate: true,
            }),
            raw_conv: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: false,
                condition: true,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            value_conv: Some(ExprId::Val1008BA43F),
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 74,
            sub: None,
            name: "ZoneMatching",
            format: None,
            count: 1,
            mask: None,
            condition: Some(Cond::MemberRegex {
                member: "Make",
                pattern: "^SONY",
                ignore_case: false,
                negate: false,
            }),
            raw_conv: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: false,
                condition: true,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[
                (0, "ISO Setting Used"),
                (1, "High Key"),
                (2, "Low Key"),
            ]),
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 76,
            sub: None,
            name: "ColorTemperature",
            format: None,
            count: 1,
            mask: None,
            condition: Some(Cond::MemberStrEq {
                member: "Model",
                value: "DSLR-A100",
                negate: false,
            }),
            raw_conv: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: false,
                condition: true,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            value_conv: Some(ExprId::Val1008BA43F),
            print_conv: PrintConv::Expr(ExprId::ValValAutoFAE0CC),
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 77,
            sub: None,
            name: "ColorFilter",
            format: None,
            count: 1,
            mask: None,
            condition: Some(Cond::MemberStrEq {
                member: "Model",
                value: "DSLR-A100",
                negate: false,
            }),
            raw_conv: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: false,
                condition: true,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 78,
            sub: None,
            name: "ColorTemperature",
            format: None,
            count: 1,
            mask: None,
            condition: Some(Cond::MemberRegex {
                member: "Model",
                pattern: "^DSLR-A(200|700)$",
                ignore_case: false,
                negate: false,
            }),
            raw_conv: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: false,
                condition: true,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            value_conv: Some(ExprId::Val1008BA43F),
            print_conv: PrintConv::Expr(ExprId::ValValAutoFAE0CC),
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 79,
            sub: None,
            name: "ColorFilter",
            format: None,
            count: 1,
            mask: None,
            condition: Some(Cond::MemberRegex {
                member: "Model",
                pattern: "^DSLR-A(200|700)$",
                ignore_case: false,
                negate: false,
            }),
            raw_conv: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: false,
                condition: true,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 80,
            sub: None,
            name: "RawDataLength",
            format: Some(Fmt::Int32u),
            count: 1,
            mask: None,
            condition: Some(Cond::MemberStrEq {
                member: "Model",
                value: "DSLR-A100",
                negate: false,
            }),
            raw_conv: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: false,
                condition: true,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
    ],
    variants: &[VariantGroup {
        index: 7,
        sub: None,
        alternatives: &[
            (
                Cond::MemberRegex {
                    member: "Make",
                    pattern: "^SONY",
                    ignore_case: false,
                    negate: true,
                },
                Field {
                    index: 7,
                    sub: None,
                    name: "ColorMode",
                    format: None,
                    count: 1,
                    mask: None,
                    condition: Some(Cond::MemberRegex {
                        member: "Make",
                        pattern: "^SONY",
                        ignore_case: false,
                        negate: true,
                    }),
                    raw_conv: None,
                    omitted: Omitted::NONE,
                    value_conv: None,
                    print_conv: PrintConv::IntEnum(&[
                        (0, "Natural color"),
                        (1, "Black & White"),
                        (2, "Vivid color"),
                        (3, "Solarization"),
                        (4, "Adobe RGB"),
                        (5, "Sepia"),
                        (9, "Natural"),
                        (12, "Portrait"),
                        (13, "Natural sRGB"),
                        (14, "Natural+ sRGB"),
                        (15, "Landscape"),
                        (16, "Evening"),
                        (17, "Night Scene"),
                        (18, "Night Portrait"),
                        (132, "Embed Adobe RGB"),
                    ]),
                    subdir: None,
                    hook: &[],
                    groups: TagGroups::NONE,
                },
            ),
            (
                Cond::MemberStrEq {
                    member: "Model",
                    value: "DSLR-A100",
                    negate: false,
                },
                Field {
                    index: 7,
                    sub: None,
                    name: "ColorMode",
                    format: None,
                    count: 1,
                    mask: None,
                    condition: Some(Cond::MemberStrEq {
                        member: "Model",
                        value: "DSLR-A100",
                        negate: false,
                    }),
                    raw_conv: None,
                    omitted: Omitted::NONE,
                    value_conv: None,
                    print_conv: PrintConv::PartialEnumInt {
                        exact: &[
                            (0, "Standard"),
                            (1, "Vivid"),
                            (2, "Portrait"),
                            (3, "Landscape"),
                            (4, "Sunset"),
                            (5, "Night View/Portrait"),
                            (6, "B&W"),
                            (7, "Adobe RGB"),
                            (12, "Neutral"),
                            (13, "Clear"),
                            (14, "Deep"),
                            (15, "Light"),
                            (16, "Autumn Leaves"),
                            (17, "Sepia"),
                            (18, "FL"),
                            (19, "Vivid 2"),
                            (20, "IN"),
                            (21, "SH"),
                            (22, "FL2"),
                            (23, "FL3"),
                            (100, "Neutral"),
                            (101, "Clear"),
                            (102, "Deep"),
                            (103, "Light"),
                            (104, "Night View"),
                            (105, "Autumn Leaves"),
                            (255, "Off"),
                            (4294967295, "n/a"),
                        ],
                        other: None,
                        print_hex: true,
                    },
                    subdir: None,
                    hook: &[],
                    groups: TagGroups::NONE,
                },
            ),
        ],
    }],
};

/// `Image::ExifTool::MinoltaRaw::WBG` -- 1 fields,
/// 1 `_variants` groups (Step 23).
/// Generated from ExifTool's in-memory tag table. Do not edit by hand.
pub static MINOLTARAW_WBG: BinaryTable = BinaryTable {
    module: "MinoltaRaw",
    table: "WBG",
    group0: "MakerNotes",
    group1: "MinoltaRaw",
    group2: "Camera",
    first_entry: 0,
    default_format: Fmt::Int8u,
    offsets_sound_until: None,
    priority: None,
    gate_a: GateA { blocked_by: &[] },
    fields: &[Field {
        index: 0,
        sub: None,
        name: "WBScale",
        format: Some(Fmt::Int8u),
        count: 4,
        mask: None,
        condition: None,
        raw_conv: None,
        omitted: Omitted::NONE,
        value_conv: None,
        print_conv: PrintConv::None,
        subdir: None,
        hook: &[],
        groups: TagGroups::NONE,
    }],
    variants: &[VariantGroup {
        index: 4,
        sub: None,
        alternatives: &[
            (
                Cond::MemberRegex {
                    member: "Model",
                    pattern: "DiMAGE A200\\b",
                    ignore_case: false,
                    negate: false,
                },
                Field {
                    index: 4,
                    sub: None,
                    name: "WB_GBRGLevels",
                    format: Some(Fmt::Int16u),
                    count: 4,
                    mask: None,
                    condition: Some(Cond::MemberRegex {
                        member: "Model",
                        pattern: "DiMAGE A200\\b",
                        ignore_case: false,
                        negate: false,
                    }),
                    raw_conv: None,
                    omitted: Omitted::NONE,
                    value_conv: None,
                    print_conv: PrintConv::None,
                    subdir: None,
                    hook: &[],
                    groups: TagGroups::NONE,
                },
            ),
            (
                Cond::Always,
                Field {
                    index: 4,
                    sub: None,
                    name: "WB_RGGBLevels",
                    format: Some(Fmt::Int16u),
                    count: 4,
                    mask: None,
                    condition: None,
                    raw_conv: None,
                    omitted: Omitted::NONE,
                    value_conv: None,
                    print_conv: PrintConv::None,
                    subdir: None,
                    hook: &[],
                    groups: TagGroups::NONE,
                },
            ),
        ],
    }],
};
