//! ExifTool `MOI` ProcessBinaryData tables, generated from ExifTool
//! 13.59's own Perl hashes -- one file per module; `mod.rs` beside this
//! file is the hub that declares and re-exports it.
//!
//! DO NOT EDIT. Regenerate with `just regen-tables` (see `mod.rs`).

#![allow(clippy::unreadable_literal, clippy::too_many_lines, unused_parens)]

// Everything a table literal names -- the schema types, `ExprId`, the
// `cond`/`subdir`/`ifd_schema` imports -- is in scope in the hub, and a glob
// import of the parent module brings its private imports along (RFC 1560).
#[allow(unused_imports)]
use super::*;

/// `Image::ExifTool::MOI::Main` -- 7 fields,
/// 0 `_variants` groups (Step 23).
/// Generated from ExifTool's in-memory tag table. Do not edit by hand.
pub static MOI_MAIN: BinaryTable = BinaryTable {
    module: "MOI",
    table: "Main",
    group0: "MOI",
    group1: "MOI",
    group2: "Video",
    first_entry: 0,
    default_format: Fmt::Int8u,
    offsets_sound_until: None,
    priority: None,
    gate_a: GateA {
        blocked_by: &[("expr_unsupported", 1)],
    },
    fields: &[
        Field {
            index: 0,
            sub: None,
            name: "MOIVersion",
            format: Some(Fmt::Str(2)),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 6,
            sub: None,
            name: "DateTimeOriginal",
            format: Some(Fmt::Undef(8)),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted {
                value_conv: true,
                raw_conv: false,
                condition: false,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups {
                g0: None,
                g1: None,
                g2: Some("Time"),
            },
        },
        Field {
            index: 14,
            sub: None,
            name: "Duration",
            format: Some(Fmt::Int32u),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: Some(ExprId::Val1000F42638),
            print_conv: PrintConv::Expr(ExprId::ConvertDurationVal90FB81),
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 128,
            sub: None,
            name: "AspectRatio",
            format: Some(Fmt::Int8u),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 132,
            sub: None,
            name: "AudioCodec",
            format: Some(Fmt::Int16u),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::PartialEnumInt {
                exact: &[(193, "AC3"), (16385, "MPEG")],
                other: None,
                print_hex: true,
            },
            subdir: None,
            hook: &[],
            groups: TagGroups {
                g0: None,
                g1: None,
                g2: Some("Audio"),
            },
        },
        Field {
            index: 134,
            sub: None,
            name: "AudioBitrate",
            format: Some(Fmt::Int8u),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: Some(ExprId::Val16000480000430C5),
            print_conv: PrintConv::Expr(ExprId::ConvertBitrateVal792F69),
            subdir: None,
            hook: &[],
            groups: TagGroups {
                g0: None,
                g1: None,
                g2: Some("Audio"),
            },
        },
        Field {
            index: 218,
            sub: None,
            name: "VideoBitrate",
            format: Some(Fmt::Int16u),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted {
                value_conv: true,
                raw_conv: false,
                condition: false,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            value_conv: None,
            print_conv: PrintConv::Expr(ExprId::ConvertBitrateVal792F69),
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
    ],
    variants: &[],
};
