//! ExifTool `MPF` ProcessBinaryData tables, generated from ExifTool
//! 13.59's own Perl hashes -- one file per module; `mod.rs` beside this
//! file is the hub that declares and re-exports it.
//!
//! DO NOT EDIT. Regenerate with `just regen-tables` (see `mod.rs`).

#![allow(clippy::unreadable_literal, clippy::too_many_lines, unused_parens)]

// Everything a table literal names -- the schema types, `ExprId`, the
// `cond`/`subdir`/`ifd_schema` imports -- is in scope in the hub, and a glob
// import of the parent module brings its private imports along (RFC 1560).
#[allow(unused_imports)]
use super::*;

/// `Image::ExifTool::MPF::MPImage` -- 7 fields,
/// 0 `_variants` groups (Step 23).
/// Generated from ExifTool's in-memory tag table. Do not edit by hand.
pub static MPF_MPIMAGE: BinaryTable = BinaryTable {
    module: "MPF",
    table: "MPImage",
    group0: "MPF",
    group1: "MPImage",
    group2: "Image",
    first_entry: 0,
    default_format: Fmt::Int8u,
    offsets_sound_until: None,
    priority: None,
    gate_a: GateA { blocked_by: &[] },
    fields: &[
        Field {
            index: 0,
            sub: Some(1),
            name: "MPImageFlags",
            format: Some(Fmt::Int32u),
            count: 1,
            mask: Some(Mask {
                bits: 0xf8000000,
                shift: 27,
            }),
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::Bitmask {
                exact: &[],
                bits: &[
                    (2, "Representative image"),
                    (3, "Dependent child image"),
                    (4, "Dependent parent image"),
                ],
            },
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 0,
            sub: Some(2),
            name: "MPImageFormat",
            format: Some(Fmt::Int32u),
            count: 1,
            mask: Some(Mask {
                bits: 0x7000000,
                shift: 24,
            }),
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[(0, "JPEG")]),
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 0,
            sub: Some(3),
            name: "MPImageType",
            format: Some(Fmt::Int32u),
            count: 1,
            mask: Some(Mask {
                bits: 0xffffff,
                shift: 0,
            }),
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::PartialEnumInt {
                exact: &[
                    (0, "Undefined"),
                    (65537, "Large Thumbnail (VGA equivalent)"),
                    (65538, "Large Thumbnail (full HD equivalent)"),
                    (65539, "Large Thumbnail (4K equivalent)"),
                    (65540, "Large Thumbnail (8K equivalent)"),
                    (65541, "Large Thumbnail (16K equivalent)"),
                    (131073, "Multi-frame Panorama"),
                    (131074, "Multi-frame Disparity"),
                    (131075, "Multi-angle"),
                    (196608, "Baseline MP Primary Image"),
                    (262144, "Original Preservation Image"),
                    (327680, "Gain Map Image"),
                ],
                other: None,
                print_hex: true,
            },
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 4,
            sub: None,
            name: "MPImageLength",
            format: Some(Fmt::Int32u),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 8,
            sub: None,
            name: "MPImageStart",
            format: Some(Fmt::Int32u),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 12,
            sub: None,
            name: "DependentImage1EntryNumber",
            format: Some(Fmt::Int16u),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 14,
            sub: None,
            name: "DependentImage2EntryNumber",
            format: Some(Fmt::Int16u),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
    ],
    variants: &[],
};
