//! ExifTool `PanasonicRaw` ProcessBinaryData tables, generated from ExifTool
//! 13.59's own Perl hashes -- one file per module; `mod.rs` beside this
//! file is the hub that declares and re-exports it.
//!
//! DO NOT EDIT. Regenerate with `just regen-tables` (see `mod.rs`).

#![allow(clippy::unreadable_literal, clippy::too_many_lines, unused_parens)]

// Everything a table literal names -- the schema types, `ExprId`, the
// `cond`/`subdir`/`ifd_schema` imports -- is in scope in the hub, and a glob
// import of the parent module brings its private imports along (RFC 1560).
#[allow(unused_imports)]
use super::*;

/// `Image::ExifTool::PanasonicRaw::WBInfo` -- 15 fields,
/// 0 `_variants` groups (Step 23).
/// Generated from ExifTool's in-memory tag table. Do not edit by hand.
pub static PANASONICRAW_WBINFO: BinaryTable = BinaryTable {
    module: "PanasonicRaw",
    table: "WBInfo",
    group0: "PanasonicRaw",
    group1: "PanasonicRaw",
    group2: "Other",
    first_entry: 0,
    default_format: Fmt::Int16u,
    offsets_sound_until: None,
    priority: None,
    gate_a: GateA { blocked_by: &[] },
    fields: &[
        Field {
            index: 0,
            sub: None,
            name: "NumWBEntries",
            format: None,
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 1,
            sub: None,
            name: "WBType1",
            format: None,
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[
                (0, "Unknown"),
                (1, "Daylight"),
                (2, "Fluorescent"),
                (3, "Tungsten (Incandescent)"),
                (4, "Flash"),
                (9, "Fine Weather"),
                (10, "Cloudy"),
                (11, "Shade"),
                (12, "Daylight Fluorescent"),
                (13, "Day White Fluorescent"),
                (14, "Cool White Fluorescent"),
                (15, "White Fluorescent"),
                (16, "Warm White Fluorescent"),
                (17, "Standard Light A"),
                (18, "Standard Light B"),
                (19, "Standard Light C"),
                (20, "D55"),
                (21, "D65"),
                (22, "D75"),
                (23, "D50"),
                (24, "ISO Studio Tungsten"),
                (25, "Daylight"),
                (26, "Day White"),
                (27, "Cool White"),
                (28, "White"),
                (29, "Warm White"),
                (30, "Daylight LED"),
                (31, "Day White LED"),
                (32, "Cool White LED"),
                (33, "White LED"),
                (34, "Warm White LED"),
                (255, "Other"),
            ]),
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 2,
            sub: None,
            name: "WB_RBLevels1",
            format: Some(Fmt::Int16u),
            count: 2,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 4,
            sub: None,
            name: "WBType2",
            format: None,
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[
                (0, "Unknown"),
                (1, "Daylight"),
                (2, "Fluorescent"),
                (3, "Tungsten (Incandescent)"),
                (4, "Flash"),
                (9, "Fine Weather"),
                (10, "Cloudy"),
                (11, "Shade"),
                (12, "Daylight Fluorescent"),
                (13, "Day White Fluorescent"),
                (14, "Cool White Fluorescent"),
                (15, "White Fluorescent"),
                (16, "Warm White Fluorescent"),
                (17, "Standard Light A"),
                (18, "Standard Light B"),
                (19, "Standard Light C"),
                (20, "D55"),
                (21, "D65"),
                (22, "D75"),
                (23, "D50"),
                (24, "ISO Studio Tungsten"),
                (25, "Daylight"),
                (26, "Day White"),
                (27, "Cool White"),
                (28, "White"),
                (29, "Warm White"),
                (30, "Daylight LED"),
                (31, "Day White LED"),
                (32, "Cool White LED"),
                (33, "White LED"),
                (34, "Warm White LED"),
                (255, "Other"),
            ]),
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 5,
            sub: None,
            name: "WB_RBLevels2",
            format: Some(Fmt::Int16u),
            count: 2,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 7,
            sub: None,
            name: "WBType3",
            format: None,
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[
                (0, "Unknown"),
                (1, "Daylight"),
                (2, "Fluorescent"),
                (3, "Tungsten (Incandescent)"),
                (4, "Flash"),
                (9, "Fine Weather"),
                (10, "Cloudy"),
                (11, "Shade"),
                (12, "Daylight Fluorescent"),
                (13, "Day White Fluorescent"),
                (14, "Cool White Fluorescent"),
                (15, "White Fluorescent"),
                (16, "Warm White Fluorescent"),
                (17, "Standard Light A"),
                (18, "Standard Light B"),
                (19, "Standard Light C"),
                (20, "D55"),
                (21, "D65"),
                (22, "D75"),
                (23, "D50"),
                (24, "ISO Studio Tungsten"),
                (25, "Daylight"),
                (26, "Day White"),
                (27, "Cool White"),
                (28, "White"),
                (29, "Warm White"),
                (30, "Daylight LED"),
                (31, "Day White LED"),
                (32, "Cool White LED"),
                (33, "White LED"),
                (34, "Warm White LED"),
                (255, "Other"),
            ]),
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 8,
            sub: None,
            name: "WB_RBLevels3",
            format: Some(Fmt::Int16u),
            count: 2,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 10,
            sub: None,
            name: "WBType4",
            format: None,
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[
                (0, "Unknown"),
                (1, "Daylight"),
                (2, "Fluorescent"),
                (3, "Tungsten (Incandescent)"),
                (4, "Flash"),
                (9, "Fine Weather"),
                (10, "Cloudy"),
                (11, "Shade"),
                (12, "Daylight Fluorescent"),
                (13, "Day White Fluorescent"),
                (14, "Cool White Fluorescent"),
                (15, "White Fluorescent"),
                (16, "Warm White Fluorescent"),
                (17, "Standard Light A"),
                (18, "Standard Light B"),
                (19, "Standard Light C"),
                (20, "D55"),
                (21, "D65"),
                (22, "D75"),
                (23, "D50"),
                (24, "ISO Studio Tungsten"),
                (25, "Daylight"),
                (26, "Day White"),
                (27, "Cool White"),
                (28, "White"),
                (29, "Warm White"),
                (30, "Daylight LED"),
                (31, "Day White LED"),
                (32, "Cool White LED"),
                (33, "White LED"),
                (34, "Warm White LED"),
                (255, "Other"),
            ]),
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 11,
            sub: None,
            name: "WB_RBLevels4",
            format: Some(Fmt::Int16u),
            count: 2,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 13,
            sub: None,
            name: "WBType5",
            format: None,
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[
                (0, "Unknown"),
                (1, "Daylight"),
                (2, "Fluorescent"),
                (3, "Tungsten (Incandescent)"),
                (4, "Flash"),
                (9, "Fine Weather"),
                (10, "Cloudy"),
                (11, "Shade"),
                (12, "Daylight Fluorescent"),
                (13, "Day White Fluorescent"),
                (14, "Cool White Fluorescent"),
                (15, "White Fluorescent"),
                (16, "Warm White Fluorescent"),
                (17, "Standard Light A"),
                (18, "Standard Light B"),
                (19, "Standard Light C"),
                (20, "D55"),
                (21, "D65"),
                (22, "D75"),
                (23, "D50"),
                (24, "ISO Studio Tungsten"),
                (25, "Daylight"),
                (26, "Day White"),
                (27, "Cool White"),
                (28, "White"),
                (29, "Warm White"),
                (30, "Daylight LED"),
                (31, "Day White LED"),
                (32, "Cool White LED"),
                (33, "White LED"),
                (34, "Warm White LED"),
                (255, "Other"),
            ]),
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 14,
            sub: None,
            name: "WB_RBLevels5",
            format: Some(Fmt::Int16u),
            count: 2,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 16,
            sub: None,
            name: "WBType6",
            format: None,
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[
                (0, "Unknown"),
                (1, "Daylight"),
                (2, "Fluorescent"),
                (3, "Tungsten (Incandescent)"),
                (4, "Flash"),
                (9, "Fine Weather"),
                (10, "Cloudy"),
                (11, "Shade"),
                (12, "Daylight Fluorescent"),
                (13, "Day White Fluorescent"),
                (14, "Cool White Fluorescent"),
                (15, "White Fluorescent"),
                (16, "Warm White Fluorescent"),
                (17, "Standard Light A"),
                (18, "Standard Light B"),
                (19, "Standard Light C"),
                (20, "D55"),
                (21, "D65"),
                (22, "D75"),
                (23, "D50"),
                (24, "ISO Studio Tungsten"),
                (25, "Daylight"),
                (26, "Day White"),
                (27, "Cool White"),
                (28, "White"),
                (29, "Warm White"),
                (30, "Daylight LED"),
                (31, "Day White LED"),
                (32, "Cool White LED"),
                (33, "White LED"),
                (34, "Warm White LED"),
                (255, "Other"),
            ]),
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 17,
            sub: None,
            name: "WB_RBLevels6",
            format: Some(Fmt::Int16u),
            count: 2,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 19,
            sub: None,
            name: "WBType7",
            format: None,
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[
                (0, "Unknown"),
                (1, "Daylight"),
                (2, "Fluorescent"),
                (3, "Tungsten (Incandescent)"),
                (4, "Flash"),
                (9, "Fine Weather"),
                (10, "Cloudy"),
                (11, "Shade"),
                (12, "Daylight Fluorescent"),
                (13, "Day White Fluorescent"),
                (14, "Cool White Fluorescent"),
                (15, "White Fluorescent"),
                (16, "Warm White Fluorescent"),
                (17, "Standard Light A"),
                (18, "Standard Light B"),
                (19, "Standard Light C"),
                (20, "D55"),
                (21, "D65"),
                (22, "D75"),
                (23, "D50"),
                (24, "ISO Studio Tungsten"),
                (25, "Daylight"),
                (26, "Day White"),
                (27, "Cool White"),
                (28, "White"),
                (29, "Warm White"),
                (30, "Daylight LED"),
                (31, "Day White LED"),
                (32, "Cool White LED"),
                (33, "White LED"),
                (34, "Warm White LED"),
                (255, "Other"),
            ]),
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 20,
            sub: None,
            name: "WB_RBLevels7",
            format: Some(Fmt::Int16u),
            count: 2,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
    ],
    variants: &[],
};

/// `Image::ExifTool::PanasonicRaw::WBInfo2` -- 15 fields,
/// 0 `_variants` groups (Step 23).
/// Generated from ExifTool's in-memory tag table. Do not edit by hand.
pub static PANASONICRAW_WBINFO2: BinaryTable = BinaryTable {
    module: "PanasonicRaw",
    table: "WBInfo2",
    group0: "PanasonicRaw",
    group1: "PanasonicRaw",
    group2: "Other",
    first_entry: 0,
    default_format: Fmt::Int16u,
    offsets_sound_until: None,
    priority: None,
    gate_a: GateA { blocked_by: &[] },
    fields: &[
        Field {
            index: 0,
            sub: None,
            name: "NumWBEntries",
            format: None,
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 1,
            sub: None,
            name: "WBType1",
            format: None,
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[
                (0, "Unknown"),
                (1, "Daylight"),
                (2, "Fluorescent"),
                (3, "Tungsten (Incandescent)"),
                (4, "Flash"),
                (9, "Fine Weather"),
                (10, "Cloudy"),
                (11, "Shade"),
                (12, "Daylight Fluorescent"),
                (13, "Day White Fluorescent"),
                (14, "Cool White Fluorescent"),
                (15, "White Fluorescent"),
                (16, "Warm White Fluorescent"),
                (17, "Standard Light A"),
                (18, "Standard Light B"),
                (19, "Standard Light C"),
                (20, "D55"),
                (21, "D65"),
                (22, "D75"),
                (23, "D50"),
                (24, "ISO Studio Tungsten"),
                (25, "Daylight"),
                (26, "Day White"),
                (27, "Cool White"),
                (28, "White"),
                (29, "Warm White"),
                (30, "Daylight LED"),
                (31, "Day White LED"),
                (32, "Cool White LED"),
                (33, "White LED"),
                (34, "Warm White LED"),
                (255, "Other"),
            ]),
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 2,
            sub: None,
            name: "WB_RGBLevels1",
            format: Some(Fmt::Int16u),
            count: 3,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 5,
            sub: None,
            name: "WBType2",
            format: None,
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[
                (0, "Unknown"),
                (1, "Daylight"),
                (2, "Fluorescent"),
                (3, "Tungsten (Incandescent)"),
                (4, "Flash"),
                (9, "Fine Weather"),
                (10, "Cloudy"),
                (11, "Shade"),
                (12, "Daylight Fluorescent"),
                (13, "Day White Fluorescent"),
                (14, "Cool White Fluorescent"),
                (15, "White Fluorescent"),
                (16, "Warm White Fluorescent"),
                (17, "Standard Light A"),
                (18, "Standard Light B"),
                (19, "Standard Light C"),
                (20, "D55"),
                (21, "D65"),
                (22, "D75"),
                (23, "D50"),
                (24, "ISO Studio Tungsten"),
                (25, "Daylight"),
                (26, "Day White"),
                (27, "Cool White"),
                (28, "White"),
                (29, "Warm White"),
                (30, "Daylight LED"),
                (31, "Day White LED"),
                (32, "Cool White LED"),
                (33, "White LED"),
                (34, "Warm White LED"),
                (255, "Other"),
            ]),
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 6,
            sub: None,
            name: "WB_RGBLevels2",
            format: Some(Fmt::Int16u),
            count: 3,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 9,
            sub: None,
            name: "WBType3",
            format: None,
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[
                (0, "Unknown"),
                (1, "Daylight"),
                (2, "Fluorescent"),
                (3, "Tungsten (Incandescent)"),
                (4, "Flash"),
                (9, "Fine Weather"),
                (10, "Cloudy"),
                (11, "Shade"),
                (12, "Daylight Fluorescent"),
                (13, "Day White Fluorescent"),
                (14, "Cool White Fluorescent"),
                (15, "White Fluorescent"),
                (16, "Warm White Fluorescent"),
                (17, "Standard Light A"),
                (18, "Standard Light B"),
                (19, "Standard Light C"),
                (20, "D55"),
                (21, "D65"),
                (22, "D75"),
                (23, "D50"),
                (24, "ISO Studio Tungsten"),
                (25, "Daylight"),
                (26, "Day White"),
                (27, "Cool White"),
                (28, "White"),
                (29, "Warm White"),
                (30, "Daylight LED"),
                (31, "Day White LED"),
                (32, "Cool White LED"),
                (33, "White LED"),
                (34, "Warm White LED"),
                (255, "Other"),
            ]),
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 10,
            sub: None,
            name: "WB_RGBLevels3",
            format: Some(Fmt::Int16u),
            count: 3,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 13,
            sub: None,
            name: "WBType4",
            format: None,
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[
                (0, "Unknown"),
                (1, "Daylight"),
                (2, "Fluorescent"),
                (3, "Tungsten (Incandescent)"),
                (4, "Flash"),
                (9, "Fine Weather"),
                (10, "Cloudy"),
                (11, "Shade"),
                (12, "Daylight Fluorescent"),
                (13, "Day White Fluorescent"),
                (14, "Cool White Fluorescent"),
                (15, "White Fluorescent"),
                (16, "Warm White Fluorescent"),
                (17, "Standard Light A"),
                (18, "Standard Light B"),
                (19, "Standard Light C"),
                (20, "D55"),
                (21, "D65"),
                (22, "D75"),
                (23, "D50"),
                (24, "ISO Studio Tungsten"),
                (25, "Daylight"),
                (26, "Day White"),
                (27, "Cool White"),
                (28, "White"),
                (29, "Warm White"),
                (30, "Daylight LED"),
                (31, "Day White LED"),
                (32, "Cool White LED"),
                (33, "White LED"),
                (34, "Warm White LED"),
                (255, "Other"),
            ]),
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 14,
            sub: None,
            name: "WB_RGBLevels4",
            format: Some(Fmt::Int16u),
            count: 3,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 17,
            sub: None,
            name: "WBType5",
            format: None,
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[
                (0, "Unknown"),
                (1, "Daylight"),
                (2, "Fluorescent"),
                (3, "Tungsten (Incandescent)"),
                (4, "Flash"),
                (9, "Fine Weather"),
                (10, "Cloudy"),
                (11, "Shade"),
                (12, "Daylight Fluorescent"),
                (13, "Day White Fluorescent"),
                (14, "Cool White Fluorescent"),
                (15, "White Fluorescent"),
                (16, "Warm White Fluorescent"),
                (17, "Standard Light A"),
                (18, "Standard Light B"),
                (19, "Standard Light C"),
                (20, "D55"),
                (21, "D65"),
                (22, "D75"),
                (23, "D50"),
                (24, "ISO Studio Tungsten"),
                (25, "Daylight"),
                (26, "Day White"),
                (27, "Cool White"),
                (28, "White"),
                (29, "Warm White"),
                (30, "Daylight LED"),
                (31, "Day White LED"),
                (32, "Cool White LED"),
                (33, "White LED"),
                (34, "Warm White LED"),
                (255, "Other"),
            ]),
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 18,
            sub: None,
            name: "WB_RGBLevels5",
            format: Some(Fmt::Int16u),
            count: 3,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 21,
            sub: None,
            name: "WBType6",
            format: None,
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[
                (0, "Unknown"),
                (1, "Daylight"),
                (2, "Fluorescent"),
                (3, "Tungsten (Incandescent)"),
                (4, "Flash"),
                (9, "Fine Weather"),
                (10, "Cloudy"),
                (11, "Shade"),
                (12, "Daylight Fluorescent"),
                (13, "Day White Fluorescent"),
                (14, "Cool White Fluorescent"),
                (15, "White Fluorescent"),
                (16, "Warm White Fluorescent"),
                (17, "Standard Light A"),
                (18, "Standard Light B"),
                (19, "Standard Light C"),
                (20, "D55"),
                (21, "D65"),
                (22, "D75"),
                (23, "D50"),
                (24, "ISO Studio Tungsten"),
                (25, "Daylight"),
                (26, "Day White"),
                (27, "Cool White"),
                (28, "White"),
                (29, "Warm White"),
                (30, "Daylight LED"),
                (31, "Day White LED"),
                (32, "Cool White LED"),
                (33, "White LED"),
                (34, "Warm White LED"),
                (255, "Other"),
            ]),
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 22,
            sub: None,
            name: "WB_RGBLevels6",
            format: Some(Fmt::Int16u),
            count: 3,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 25,
            sub: None,
            name: "WBType7",
            format: None,
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[
                (0, "Unknown"),
                (1, "Daylight"),
                (2, "Fluorescent"),
                (3, "Tungsten (Incandescent)"),
                (4, "Flash"),
                (9, "Fine Weather"),
                (10, "Cloudy"),
                (11, "Shade"),
                (12, "Daylight Fluorescent"),
                (13, "Day White Fluorescent"),
                (14, "Cool White Fluorescent"),
                (15, "White Fluorescent"),
                (16, "Warm White Fluorescent"),
                (17, "Standard Light A"),
                (18, "Standard Light B"),
                (19, "Standard Light C"),
                (20, "D55"),
                (21, "D65"),
                (22, "D75"),
                (23, "D50"),
                (24, "ISO Studio Tungsten"),
                (25, "Daylight"),
                (26, "Day White"),
                (27, "Cool White"),
                (28, "White"),
                (29, "Warm White"),
                (30, "Daylight LED"),
                (31, "Day White LED"),
                (32, "Cool White LED"),
                (33, "White LED"),
                (34, "Warm White LED"),
                (255, "Other"),
            ]),
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 26,
            sub: None,
            name: "WB_RGBLevels7",
            format: Some(Fmt::Int16u),
            count: 3,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
    ],
    variants: &[],
};
