//! ExifTool `Panasonic` ProcessBinaryData tables, generated from ExifTool
//! 13.59's own Perl hashes -- one file per module; `mod.rs` beside this
//! file is the hub that declares and re-exports it.
//!
//! DO NOT EDIT. Regenerate with `just regen-tables` (see `mod.rs`).

#![allow(clippy::unreadable_literal, clippy::too_many_lines, unused_parens)]

// Everything a table literal names -- the schema types, `ExprId`, the
// `cond`/`subdir`/`ifd_schema` imports -- is in scope in the hub, and a glob
// import of the parent module brings its private imports along (RFC 1560).
#[allow(unused_imports)]
use super::*;

/// `Image::ExifTool::Panasonic::Data1` -- 1 fields,
/// 0 `_variants` groups (Step 23).
/// Generated from ExifTool's in-memory tag table. Do not edit by hand.
pub static PANASONIC_DATA1: BinaryTable = BinaryTable {
    module: "Panasonic",
    table: "Data1",
    group0: "MakerNotes",
    group1: "Leica",
    group2: "Camera",
    first_entry: 0,
    default_format: Fmt::Int8u,
    offsets_sound_until: None,
    priority: None,
    gate_a: GateA {
        blocked_by: &[("other_unregistered", 1)],
    },
    fields: &[Field {
        index: 22,
        sub: None,
        name: "LensType",
        format: Some(Fmt::Int32u),
        count: 1,
        mask: None,
        condition: None,
        raw_conv: None,
        omitted: Omitted::NONE,
        value_conv: Some(ExprId::Val20xffffVal0x333B0CB),
        print_conv: PrintConv::None,
        subdir: None,
        hook: &[],
        groups: TagGroups::NONE,
    }],
    variants: &[],
};

/// `Image::ExifTool::Panasonic::FaceDetInfo` -- 6 fields,
/// 0 `_variants` groups (Step 23).
/// Generated from ExifTool's in-memory tag table. Do not edit by hand.
pub static PANASONIC_FACEDETINFO: BinaryTable = BinaryTable {
    module: "Panasonic",
    table: "FaceDetInfo",
    group0: "MakerNotes",
    group1: "Panasonic",
    group2: "Image",
    first_entry: 0,
    default_format: Fmt::Int16u,
    offsets_sound_until: None,
    priority: None,
    gate_a: GateA { blocked_by: &[] },
    fields: &[
        Field {
            index: 0,
            sub: None,
            name: "NumFacePositions",
            format: Some(Fmt::Int16u),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: Some(RawConvEffect::SetMember {
                member: "NumFacePositions",
            }),
            omitted: Omitted {
                value_conv: false,
                raw_conv: true,
                condition: false,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 1,
            sub: None,
            name: "Face1Position",
            format: Some(Fmt::Int16u),
            count: 4,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: true,
                condition: false,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 5,
            sub: None,
            name: "Face2Position",
            format: Some(Fmt::Int16u),
            count: 4,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: true,
                condition: false,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 9,
            sub: None,
            name: "Face3Position",
            format: Some(Fmt::Int16u),
            count: 4,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: true,
                condition: false,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 13,
            sub: None,
            name: "Face4Position",
            format: Some(Fmt::Int16u),
            count: 4,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: true,
                condition: false,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 17,
            sub: None,
            name: "Face5Position",
            format: Some(Fmt::Int16u),
            count: 4,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: true,
                condition: false,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
    ],
    variants: &[],
};

/// `Image::ExifTool::Panasonic::FaceRecInfo` -- 10 fields,
/// 0 `_variants` groups (Step 23).
/// Generated from ExifTool's in-memory tag table. Do not edit by hand.
pub static PANASONIC_FACERECINFO: BinaryTable = BinaryTable {
    module: "Panasonic",
    table: "FaceRecInfo",
    group0: "MakerNotes",
    group1: "Panasonic",
    group2: "Image",
    first_entry: 0,
    default_format: Fmt::Int8u,
    offsets_sound_until: None,
    priority: None,
    gate_a: GateA { blocked_by: &[] },
    fields: &[
        Field {
            index: 0,
            sub: None,
            name: "FacesRecognized",
            format: Some(Fmt::Int16u),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: Some(RawConvEffect::SetMember {
                member: "FacesRecognized",
            }),
            omitted: Omitted {
                value_conv: false,
                raw_conv: true,
                condition: false,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 4,
            sub: None,
            name: "RecognizedFace1Name",
            format: Some(Fmt::Str(20)),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: true,
                condition: false,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 24,
            sub: None,
            name: "RecognizedFace1Position",
            format: Some(Fmt::Int16u),
            count: 4,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: true,
                condition: false,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 32,
            sub: None,
            name: "RecognizedFace1Age",
            format: Some(Fmt::Str(20)),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: true,
                condition: false,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 52,
            sub: None,
            name: "RecognizedFace2Name",
            format: Some(Fmt::Str(20)),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: true,
                condition: false,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 72,
            sub: None,
            name: "RecognizedFace2Position",
            format: Some(Fmt::Int16u),
            count: 4,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: true,
                condition: false,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 80,
            sub: None,
            name: "RecognizedFace2Age",
            format: Some(Fmt::Str(20)),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: true,
                condition: false,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 100,
            sub: None,
            name: "RecognizedFace3Name",
            format: Some(Fmt::Str(20)),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: true,
                condition: false,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 120,
            sub: None,
            name: "RecognizedFace3Position",
            format: Some(Fmt::Int16u),
            count: 4,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: true,
                condition: false,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 128,
            sub: None,
            name: "RecognizedFace3Age",
            format: Some(Fmt::Str(20)),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: true,
                condition: false,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
    ],
    variants: &[],
};

/// `Image::ExifTool::Panasonic::FocusInfo` -- 2 fields,
/// 0 `_variants` groups (Step 23).
/// Generated from ExifTool's in-memory tag table. Do not edit by hand.
pub static PANASONIC_FOCUSINFO: BinaryTable = BinaryTable {
    module: "Panasonic",
    table: "FocusInfo",
    group0: "MakerNotes",
    group1: "Leica",
    group2: "Camera",
    first_entry: 0,
    default_format: Fmt::Int16u,
    offsets_sound_until: None,
    priority: None,
    gate_a: GateA { blocked_by: &[] },
    fields: &[
        Field {
            index: 0,
            sub: None,
            name: "FocusDistance",
            format: None,
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: Some(ExprId::Val1000F42638),
            print_conv: PrintConv::Expr(ExprId::Val65535ValMInf7F039B),
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 1,
            sub: None,
            name: "FocalLength",
            format: None,
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: true,
                condition: false,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            value_conv: Some(ExprId::Val1000F42638),
            print_conv: PrintConv::Expr(ExprId::Sprintf1fMmVal03B2CA),
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
    ],
    variants: &[],
};

/// `Image::ExifTool::Panasonic::PANA` -- 19 fields,
/// 0 `_variants` groups (Step 23).
/// Generated from ExifTool's in-memory tag table. Do not edit by hand.
pub static PANASONIC_PANA: BinaryTable = BinaryTable {
    module: "Panasonic",
    table: "PANA",
    group0: "MakerNotes",
    group1: "Panasonic",
    group2: "Image",
    first_entry: 0,
    default_format: Fmt::Int8u,
    offsets_sound_until: None,
    priority: None,
    gate_a: GateA {
        blocked_by: &[
            ("subdir_refused_processproc", 4),
            ("tag_fmt_unsupported", 4),
        ],
    },
    fields: &[
        Field {
            index: 0,
            sub: None,
            name: "Make",
            format: Some(Fmt::Str(22)),
            count: 1,
            mask: None,
            condition: Some(Cond::ValPtRegex {
                pattern: "^(LEICA|Panasonic)",
                negate: false,
            }),
            raw_conv: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: true,
                condition: true,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups {
                g0: None,
                g1: None,
                g2: Some("Camera"),
            },
        },
        Field {
            index: 4,
            sub: None,
            name: "Model",
            format: Some(Fmt::Str(16)),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: Some(RawConvEffect::SetMember { member: "Model" }),
            omitted: Omitted {
                value_conv: false,
                raw_conv: true,
                condition: true,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups {
                g0: None,
                g1: None,
                g2: Some("Camera"),
            },
        },
        Field {
            index: 12,
            sub: None,
            name: "Model",
            format: Some(Fmt::Str(16)),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: Some(RawConvEffect::SetMember { member: "Model" }),
            omitted: Omitted {
                value_conv: false,
                raw_conv: true,
                condition: true,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups {
                g0: None,
                g1: None,
                g2: Some("Camera"),
            },
        },
        Field {
            index: 22,
            sub: None,
            name: "Model",
            format: Some(Fmt::Str(30)),
            count: 1,
            mask: None,
            condition: Some(Cond::MemberTruthy {
                member: "LeicaLEIC",
                negate: false,
            }),
            raw_conv: Some(RawConvEffect::SetMember { member: "Model" }),
            omitted: Omitted {
                value_conv: false,
                raw_conv: true,
                condition: true,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups {
                g0: None,
                g1: None,
                g2: Some("Camera"),
            },
        },
        Field {
            index: 52,
            sub: None,
            name: "Version1",
            format: Some(Fmt::Str(14)),
            count: 1,
            mask: None,
            condition: Some(Cond::MemberTruthy {
                member: "LeicaLEIC",
                negate: false,
            }),
            raw_conv: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: false,
                condition: true,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 62,
            sub: None,
            name: "Version2",
            format: Some(Fmt::Str(14)),
            count: 1,
            mask: None,
            condition: Some(Cond::MemberTruthy {
                member: "LeicaLEIC",
                negate: false,
            }),
            raw_conv: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: false,
                condition: true,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 80,
            sub: None,
            name: "MakerNoteLeica5",
            format: None,
            count: 1,
            mask: None,
            condition: Some(Cond::MemberTruthy {
                member: "LeicaLEIC",
                negate: false,
            }),
            raw_conv: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: false,
                condition: true,
                hook: false,
                subdirectory: true,
                print_conv: false,
            },
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 88,
            sub: None,
            name: "ThumbnailWidth",
            format: Some(Fmt::Int16u),
            count: 1,
            mask: None,
            condition: Some(Cond::MemberCmp {
                member: "ThumbType",
                op: CmpOp::Eq,
                value: 1,
            }),
            raw_conv: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: false,
                condition: true,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 90,
            sub: None,
            name: "ThumbnailHeight",
            format: Some(Fmt::Int16u),
            count: 1,
            mask: None,
            condition: Some(Cond::MemberCmp {
                member: "ThumbType",
                op: CmpOp::Eq,
                value: 1,
            }),
            raw_conv: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: false,
                condition: true,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 92,
            sub: None,
            name: "ThumbnailImage",
            format: Some(Fmt::Undef(16384)),
            count: 1,
            mask: None,
            condition: Some(Cond::MemberCmp {
                member: "ThumbType",
                op: CmpOp::Eq,
                value: 1,
            }),
            raw_conv: None,
            omitted: Omitted {
                value_conv: true,
                raw_conv: false,
                condition: true,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups {
                g0: None,
                g1: None,
                g2: Some("Preview"),
            },
        },
        Field {
            index: 1334,
            sub: None,
            name: "ThumbnailWidth",
            format: Some(Fmt::Int32uRev),
            count: 1,
            mask: None,
            condition: Some(Cond::MemberCmp {
                member: "ThumbType",
                op: CmpOp::Eq,
                value: 2,
            }),
            raw_conv: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: false,
                condition: true,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 1338,
            sub: None,
            name: "ThumbnailHeight",
            format: Some(Fmt::Int32uRev),
            count: 1,
            mask: None,
            condition: Some(Cond::MemberCmp {
                member: "ThumbType",
                op: CmpOp::Eq,
                value: 2,
            }),
            raw_conv: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: false,
                condition: true,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 1342,
            sub: None,
            name: "ThumbnailLength",
            format: Some(Fmt::Int32uRev),
            count: 1,
            mask: None,
            condition: Some(Cond::MemberCmp {
                member: "ThumbType",
                op: CmpOp::Eq,
                value: 2,
            }),
            raw_conv: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: false,
                condition: true,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 1358,
            sub: None,
            name: "ThumbnailWidth",
            format: Some(Fmt::Int32uRev),
            count: 1,
            mask: None,
            condition: Some(Cond::MemberCmp {
                member: "ThumbType",
                op: CmpOp::Eq,
                value: 3,
            }),
            raw_conv: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: false,
                condition: true,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 1362,
            sub: None,
            name: "ThumbnailHeight",
            format: Some(Fmt::Int32uRev),
            count: 1,
            mask: None,
            condition: Some(Cond::MemberCmp {
                member: "ThumbType",
                op: CmpOp::Eq,
                value: 3,
            }),
            raw_conv: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: false,
                condition: true,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 1366,
            sub: None,
            name: "ThumbnailLength",
            format: Some(Fmt::Int32uRev),
            count: 1,
            mask: None,
            condition: Some(Cond::MemberCmp {
                member: "ThumbType",
                op: CmpOp::Eq,
                value: 3,
            }),
            raw_conv: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: false,
                condition: true,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 16488,
            sub: None,
            name: "ExifData",
            format: None,
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: false,
                condition: true,
                hook: false,
                subdirectory: true,
                print_conv: false,
            },
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 16512,
            sub: None,
            name: "ExifData",
            format: None,
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: false,
                condition: true,
                hook: false,
                subdirectory: true,
                print_conv: false,
            },
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 2097280,
            sub: None,
            name: "ExifData",
            format: None,
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: false,
                condition: true,
                hook: false,
                subdirectory: true,
                print_conv: false,
            },
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
    ],
    variants: &[],
};

/// `Image::ExifTool::Panasonic::SerialInfo` -- 1 fields,
/// 0 `_variants` groups (Step 23).
/// Generated from ExifTool's in-memory tag table. Do not edit by hand.
pub static PANASONIC_SERIALINFO: BinaryTable = BinaryTable {
    module: "Panasonic",
    table: "SerialInfo",
    group0: "MakerNotes",
    group1: "Leica",
    group2: "Camera",
    first_entry: 0,
    default_format: Fmt::Int8u,
    offsets_sound_until: None,
    priority: None,
    gate_a: GateA { blocked_by: &[] },
    fields: &[Field {
        index: 4,
        sub: None,
        name: "SerialNumber",
        format: Some(Fmt::Str(8)),
        count: 1,
        mask: None,
        condition: None,
        raw_conv: None,
        omitted: Omitted::NONE,
        value_conv: None,
        print_conv: PrintConv::None,
        subdir: None,
        hook: &[],
        groups: TagGroups::NONE,
    }],
    variants: &[],
};

/// `Image::ExifTool::Panasonic::ShotInfo` -- 1 fields,
/// 0 `_variants` groups (Step 23).
/// Generated from ExifTool's in-memory tag table. Do not edit by hand.
pub static PANASONIC_SHOTINFO: BinaryTable = BinaryTable {
    module: "Panasonic",
    table: "ShotInfo",
    group0: "MakerNotes",
    group1: "Leica",
    group2: "Camera",
    first_entry: 0,
    default_format: Fmt::Int8u,
    offsets_sound_until: None,
    priority: None,
    gate_a: GateA { blocked_by: &[] },
    fields: &[Field {
        index: 0,
        sub: None,
        name: "FileIndex",
        format: Some(Fmt::Int16u),
        count: 1,
        mask: None,
        condition: None,
        raw_conv: None,
        omitted: Omitted::NONE,
        value_conv: None,
        print_conv: PrintConv::None,
        subdir: None,
        hook: &[],
        groups: TagGroups::NONE,
    }],
    variants: &[],
};

/// `Image::ExifTool::Panasonic::TimeInfo` -- 2 fields,
/// 0 `_variants` groups (Step 23).
/// Generated from ExifTool's in-memory tag table. Do not edit by hand.
pub static PANASONIC_TIMEINFO: BinaryTable = BinaryTable {
    module: "Panasonic",
    table: "TimeInfo",
    group0: "MakerNotes",
    group1: "Panasonic",
    group2: "Image",
    first_entry: 0,
    default_format: Fmt::Int8u,
    offsets_sound_until: None,
    priority: None,
    gate_a: GateA { blocked_by: &[] },
    fields: &[
        Field {
            index: 0,
            sub: None,
            name: "PanasonicDateTime",
            format: Some(Fmt::Undef(8)),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted {
                value_conv: true,
                raw_conv: true,
                condition: false,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups {
                g0: None,
                g1: None,
                g2: Some("Time"),
            },
        },
        Field {
            index: 16,
            sub: None,
            name: "TimeLapseShotNumber",
            format: Some(Fmt::Int32u),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
    ],
    variants: &[],
};

/// `Image::ExifTool::Panasonic::Type2` -- 2 fields,
/// 0 `_variants` groups (Step 23).
/// Generated from ExifTool's in-memory tag table. Do not edit by hand.
pub static PANASONIC_TYPE2: BinaryTable = BinaryTable {
    module: "Panasonic",
    table: "Type2",
    group0: "MakerNotes",
    group1: "Panasonic",
    group2: "Image",
    first_entry: 0,
    default_format: Fmt::Int16u,
    offsets_sound_until: None,
    priority: None,
    gate_a: GateA { blocked_by: &[] },
    fields: &[
        Field {
            index: 0,
            sub: None,
            name: "MakerNoteType",
            format: Some(Fmt::Str(4)),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 3,
            sub: None,
            name: "Gain",
            format: None,
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
    ],
    variants: &[],
};
