//! ExifTool `Parrot` ProcessBinaryData tables, generated from ExifTool
//! 13.59's own Perl hashes -- one file per module; `mod.rs` beside this
//! file is the hub that declares and re-exports it.
//!
//! DO NOT EDIT. Regenerate with `just regen-tables` (see `mod.rs`).

#![allow(clippy::unreadable_literal, clippy::too_many_lines, unused_parens)]

// Everything a table literal names -- the schema types, `ExprId`, the
// `cond`/`subdir`/`ifd_schema` imports -- is in scope in the hub, and a glob
// import of the parent module brings its private imports along (RFC 1560).
#[allow(unused_imports)]
use super::*;

/// `Image::ExifTool::Parrot::ARCoreAccel` -- 1 fields,
/// 0 `_variants` groups (Step 23).
/// Generated from ExifTool's in-memory tag table. Do not edit by hand.
pub static PARROT_ARCOREACCEL: BinaryTable = BinaryTable {
    module: "Parrot",
    table: "ARCoreAccel",
    group0: "Parrot",
    group1: "Parrot",
    group2: "Location",
    first_entry: 0,
    default_format: Fmt::Int8u,
    offsets_sound_until: None,
    priority: None,
    gate_a: GateA { blocked_by: &[] },
    fields: &[Field {
        index: 5,
        sub: None,
        name: "Accelerometer",
        format: Some(Fmt::Undef(14)),
        count: 1,
        mask: None,
        condition: None,
        raw_conv: None,
        omitted: Omitted {
            value_conv: false,
            raw_conv: true,
            condition: false,
            hook: false,
            subdirectory: false,
            print_conv: false,
        },
        value_conv: None,
        print_conv: PrintConv::None,
        subdir: None,
        hook: &[],
        groups: TagGroups::NONE,
    }],
    variants: &[],
};

/// `Image::ExifTool::Parrot::ARCoreAccel0` -- 1 fields,
/// 0 `_variants` groups (Step 23).
/// Generated from ExifTool's in-memory tag table. Do not edit by hand.
pub static PARROT_ARCOREACCEL0: BinaryTable = BinaryTable {
    module: "Parrot",
    table: "ARCoreAccel0",
    group0: "Parrot",
    group1: "Parrot",
    group2: "Location",
    first_entry: 0,
    default_format: Fmt::Int8u,
    offsets_sound_until: None,
    priority: None,
    gate_a: GateA { blocked_by: &[] },
    fields: &[Field {
        index: 9,
        sub: None,
        name: "Accelerometer",
        format: Some(Fmt::Undef(14)),
        count: 1,
        mask: None,
        condition: None,
        raw_conv: None,
        omitted: Omitted {
            value_conv: false,
            raw_conv: true,
            condition: false,
            hook: false,
            subdirectory: false,
            print_conv: false,
        },
        value_conv: None,
        print_conv: PrintConv::None,
        subdir: None,
        hook: &[],
        groups: TagGroups::NONE,
    }],
    variants: &[],
};

/// `Image::ExifTool::Parrot::ARCoreGyro` -- 1 fields,
/// 0 `_variants` groups (Step 23).
/// Generated from ExifTool's in-memory tag table. Do not edit by hand.
pub static PARROT_ARCOREGYRO: BinaryTable = BinaryTable {
    module: "Parrot",
    table: "ARCoreGyro",
    group0: "Parrot",
    group1: "Parrot",
    group2: "Location",
    first_entry: 0,
    default_format: Fmt::Int8u,
    offsets_sound_until: None,
    priority: None,
    gate_a: GateA { blocked_by: &[] },
    fields: &[Field {
        index: 5,
        sub: None,
        name: "Gyroscope",
        format: Some(Fmt::Undef(14)),
        count: 1,
        mask: None,
        condition: None,
        raw_conv: None,
        omitted: Omitted {
            value_conv: false,
            raw_conv: true,
            condition: false,
            hook: false,
            subdirectory: false,
            print_conv: false,
        },
        value_conv: None,
        print_conv: PrintConv::None,
        subdir: None,
        hook: &[],
        groups: TagGroups::NONE,
    }],
    variants: &[],
};

/// `Image::ExifTool::Parrot::ARCoreGyro0` -- 1 fields,
/// 0 `_variants` groups (Step 23).
/// Generated from ExifTool's in-memory tag table. Do not edit by hand.
pub static PARROT_ARCOREGYRO0: BinaryTable = BinaryTable {
    module: "Parrot",
    table: "ARCoreGyro0",
    group0: "Parrot",
    group1: "Parrot",
    group2: "Location",
    first_entry: 0,
    default_format: Fmt::Int8u,
    offsets_sound_until: None,
    priority: None,
    gate_a: GateA { blocked_by: &[] },
    fields: &[Field {
        index: 9,
        sub: None,
        name: "Gyroscope",
        format: Some(Fmt::Undef(14)),
        count: 1,
        mask: None,
        condition: None,
        raw_conv: None,
        omitted: Omitted {
            value_conv: false,
            raw_conv: true,
            condition: false,
            hook: false,
            subdirectory: false,
            print_conv: false,
        },
        value_conv: None,
        print_conv: PrintConv::None,
        subdir: None,
        hook: &[],
        groups: TagGroups::NONE,
    }],
    variants: &[],
};

/// `Image::ExifTool::Parrot::Automation` -- 8 fields,
/// 0 `_variants` groups (Step 23).
/// Generated from ExifTool's in-memory tag table. Do not edit by hand.
pub static PARROT_AUTOMATION: BinaryTable = BinaryTable {
    module: "Parrot",
    table: "Automation",
    group0: "Parrot",
    group1: "Parrot",
    group2: "Location",
    first_entry: 0,
    default_format: Fmt::Int8u,
    offsets_sound_until: None,
    priority: None,
    gate_a: GateA { blocked_by: &[] },
    fields: &[
        Field {
            index: 4,
            sub: None,
            name: "GPSFramingLatitude",
            format: Some(Fmt::Int32s),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: Some(ExprId::Val0x4000006256DE),
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 8,
            sub: None,
            name: "GPSFramingLongitude",
            format: Some(Fmt::Int32s),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: Some(ExprId::Val0x4000006256DE),
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 12,
            sub: None,
            name: "GPSFramingAltitude",
            format: Some(Fmt::Int32s),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: Some(ExprId::Val0x100007EF43A),
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 16,
            sub: None,
            name: "GPSDestLatitude",
            format: Some(Fmt::Int32s),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: Some(ExprId::Val0x4000006256DE),
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 20,
            sub: None,
            name: "GPSDestLongitude",
            format: Some(Fmt::Int32s),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: Some(ExprId::Val0x4000006256DE),
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 24,
            sub: None,
            name: "GPSDestAltitude",
            format: Some(Fmt::Int32s),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: Some(ExprId::Val0x100007EF43A),
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 28,
            sub: None,
            name: "AutomationAnimation",
            format: None,
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[
                (0, "None"),
                (1, "Orbit"),
                (2, "Boomerang"),
                (3, "Parabola"),
                (4, "Dolly Slide"),
                (5, "Dolly Zoom"),
                (6, "Reveal Vertical"),
                (7, "Reveal Horizontal"),
                (8, "Candle"),
                (9, "Flip Front"),
                (10, "Flip Back"),
                (11, "Flip Left"),
                (12, "Flip Right"),
                (13, "Twist Up"),
                (14, "Position Twist Up"),
            ]),
            subdir: None,
            hook: &[],
            groups: TagGroups {
                g0: None,
                g1: None,
                g2: Some("Device"),
            },
        },
        Field {
            index: 29,
            sub: None,
            name: "AutomationFlags",
            format: None,
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::Bitmask {
                exact: &[],
                bits: &[
                    (0, "Follow-me enabled"),
                    (1, "Look-at-me enabled"),
                    (2, "Angle locked"),
                ],
            },
            subdir: None,
            hook: &[],
            groups: TagGroups {
                g0: None,
                g1: None,
                g2: Some("Device"),
            },
        },
    ],
    variants: &[],
};

/// `Image::ExifTool::Parrot::FollowMe` -- 5 fields,
/// 0 `_variants` groups (Step 23).
/// Generated from ExifTool's in-memory tag table. Do not edit by hand.
pub static PARROT_FOLLOWME: BinaryTable = BinaryTable {
    module: "Parrot",
    table: "FollowMe",
    group0: "Parrot",
    group1: "Parrot",
    group2: "Location",
    first_entry: 0,
    default_format: Fmt::Int8u,
    offsets_sound_until: None,
    priority: None,
    gate_a: GateA { blocked_by: &[] },
    fields: &[
        Field {
            index: 4,
            sub: None,
            name: "GPSTargetLatitude",
            format: Some(Fmt::Int32s),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: Some(ExprId::Val0x4000006256DE),
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 8,
            sub: None,
            name: "GPSTargetLongitude",
            format: Some(Fmt::Int32s),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: Some(ExprId::Val0x4000006256DE),
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 12,
            sub: None,
            name: "GPSTargetAltitude",
            format: Some(Fmt::Int32s),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: Some(ExprId::Val0x100007EF43A),
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 16,
            sub: None,
            name: "Follow-meMode",
            format: None,
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::Bitmask {
                exact: &[],
                bits: &[
                    (0, "Follow-me enabled"),
                    (1, "Follow-me"),
                    (2, "Angle locked"),
                ],
            },
            subdir: None,
            hook: &[],
            groups: TagGroups {
                g0: None,
                g1: None,
                g2: Some("Device"),
            },
        },
        Field {
            index: 17,
            sub: None,
            name: "Follow-meAnimation",
            format: None,
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[
                (0, "None"),
                (1, "Orbit"),
                (2, "Boomerang"),
                (3, "Parabola"),
                (4, "Zenith"),
            ]),
            subdir: None,
            hook: &[],
            groups: TagGroups {
                g0: None,
                g1: None,
                g2: Some("Device"),
            },
        },
    ],
    variants: &[],
};

/// `Image::ExifTool::Parrot::TimeStamp` -- 1 fields,
/// 0 `_variants` groups (Step 23).
/// Generated from ExifTool's in-memory tag table. Do not edit by hand.
pub static PARROT_TIMESTAMP: BinaryTable = BinaryTable {
    module: "Parrot",
    table: "TimeStamp",
    group0: "Parrot",
    group1: "Parrot",
    group2: "Time",
    first_entry: 0,
    default_format: Fmt::Int8u,
    offsets_sound_until: None,
    priority: None,
    gate_a: GateA { blocked_by: &[] },
    fields: &[Field {
        index: 4,
        sub: None,
        name: "TimeStamp",
        format: Some(Fmt::Int64u),
        count: 1,
        mask: None,
        condition: None,
        raw_conv: None,
        omitted: Omitted::NONE,
        value_conv: Some(ExprId::Val1e6EF7EB9),
        print_conv: PrintConv::None,
        subdir: None,
        hook: &[],
        groups: TagGroups::NONE,
    }],
    variants: &[],
};

/// `Image::ExifTool::Parrot::V1` -- 23 fields,
/// 0 `_variants` groups (Step 23).
/// Generated from ExifTool's in-memory tag table. Do not edit by hand.
pub static PARROT_V1: BinaryTable = BinaryTable {
    module: "Parrot",
    table: "V1",
    group0: "Parrot",
    group1: "Parrot",
    group2: "Location",
    first_entry: 0,
    default_format: Fmt::Int8u,
    offsets_sound_until: None,
    priority: None,
    gate_a: GateA { blocked_by: &[] },
    fields: &[
        Field {
            index: 4,
            sub: None,
            name: "DroneYaw",
            format: Some(Fmt::Int16s),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: Some(ExprId::Val0x10001803141598CFB34),
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 6,
            sub: None,
            name: "DronePitch",
            format: Some(Fmt::Int16s),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: Some(ExprId::Val0x10001803141598CFB34),
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 8,
            sub: None,
            name: "DroneRoll",
            format: Some(Fmt::Int16s),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: Some(ExprId::Val0x10001803141598CFB34),
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 10,
            sub: None,
            name: "CameraPan",
            format: Some(Fmt::Int16s),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: Some(ExprId::Val0x10001803141598CFB34),
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 12,
            sub: None,
            name: "CameraTilt",
            format: Some(Fmt::Int16s),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: Some(ExprId::Val0x10001803141598CFB34),
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 14,
            sub: None,
            name: "FrameView",
            format: Some(Fmt::Int16s),
            count: 4,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: Some(ExprId::MyASplitVal0x1000ForeachAA9B3760),
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 22,
            sub: None,
            name: "ExposureTime",
            format: Some(Fmt::Int16s),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: Some(ExprId::Val0x1001000B95BCC),
            print_conv: PrintConv::Expr(ExprId::ImageExifToolExifPrintExposureTimeVal6037F3),
            subdir: None,
            hook: &[],
            groups: TagGroups {
                g0: None,
                g1: None,
                g2: Some("Camera"),
            },
        },
        Field {
            index: 24,
            sub: None,
            name: "ISO",
            format: Some(Fmt::Int16s),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups {
                g0: None,
                g1: None,
                g2: Some("Camera"),
            },
        },
        Field {
            index: 26,
            sub: None,
            name: "WifiRSSI",
            format: Some(Fmt::Int8s),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::Expr(ExprId::ValDBm64BBA9),
            subdir: None,
            hook: &[],
            groups: TagGroups {
                g0: None,
                g1: None,
                g2: Some("Device"),
            },
        },
        Field {
            index: 27,
            sub: None,
            name: "Battery",
            format: None,
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::Expr(ExprId::Val22FAFA),
            subdir: None,
            hook: &[],
            groups: TagGroups {
                g0: None,
                g1: None,
                g2: Some("Device"),
            },
        },
        Field {
            index: 28,
            sub: None,
            name: "GPSLatitude",
            format: Some(Fmt::Int32s),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: Some(ExprId::Val0x1000009D3013),
            print_conv: PrintConv::Expr(ExprId::ImageExifToolGPSToDMSSelfVal1N224F39),
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 32,
            sub: None,
            name: "GPSLongitude",
            format: Some(Fmt::Int32s),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: Some(ExprId::Val0x1000009D3013),
            print_conv: PrintConv::Expr(ExprId::ImageExifToolGPSToDMSSelfVal1E4009F1),
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 36,
            sub: None,
            name: "GPSAltitude",
            format: Some(Fmt::Int32s),
            count: 1,
            mask: Some(Mask {
                bits: 0xffffff00,
                shift: 8,
            }),
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: Some(ExprId::Val0x10099B9B6),
            print_conv: PrintConv::Expr(ExprId::Sprintf3fMVal40374B),
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 36,
            sub: Some(1),
            name: "GPSSatellites",
            format: Some(Fmt::Int32s),
            count: 1,
            mask: Some(Mask {
                bits: 0xff,
                shift: 0,
            }),
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 40,
            sub: None,
            name: "AltitudeFromTakeOff",
            format: Some(Fmt::Int32s),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: Some(ExprId::Val0x100007EF43A),
            print_conv: PrintConv::Expr(ExprId::Sprintf3fMVal40374B),
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 44,
            sub: None,
            name: "DistanceFromHome",
            format: Some(Fmt::Int32u),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: Some(ExprId::Val0x100007EF43A),
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 48,
            sub: None,
            name: "SpeedX",
            format: Some(Fmt::Int16s),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: Some(ExprId::Val0x10099B9B6),
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 50,
            sub: None,
            name: "SpeedY",
            format: Some(Fmt::Int16s),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: Some(ExprId::Val0x10099B9B6),
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 52,
            sub: None,
            name: "SpeedZ",
            format: Some(Fmt::Int16s),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: Some(ExprId::Val0x10099B9B6),
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 54,
            sub: None,
            name: "Binning",
            format: None,
            count: 1,
            mask: Some(Mask {
                bits: 0x80,
                shift: 7,
            }),
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups {
                g0: None,
                g1: None,
                g2: Some("Device"),
            },
        },
        Field {
            index: 54,
            sub: Some(1),
            name: "FlyingState",
            format: None,
            count: 1,
            mask: Some(Mask {
                bits: 0x7f,
                shift: 0,
            }),
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[
                (0, "Landed"),
                (1, "Taking Off"),
                (2, "Hovering"),
                (3, "Flying"),
                (4, "Landing"),
                (5, "Emergency"),
            ]),
            subdir: None,
            hook: &[],
            groups: TagGroups {
                g0: None,
                g1: None,
                g2: Some("Device"),
            },
        },
        Field {
            index: 55,
            sub: None,
            name: "Animation",
            format: None,
            count: 1,
            mask: Some(Mask {
                bits: 0x80,
                shift: 7,
            }),
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups {
                g0: None,
                g1: None,
                g2: Some("Device"),
            },
        },
        Field {
            index: 55,
            sub: Some(1),
            name: "PilotingMode",
            format: None,
            count: 1,
            mask: Some(Mask {
                bits: 0x7f,
                shift: 0,
            }),
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[
                (0, "Manual"),
                (1, "Return Home"),
                (2, "Flight Plan"),
                (3, "Follow Me"),
            ]),
            subdir: None,
            hook: &[],
            groups: TagGroups {
                g0: None,
                g1: None,
                g2: Some("Device"),
            },
        },
    ],
    variants: &[],
};

/// `Image::ExifTool::Parrot::V2` -- 21 fields,
/// 0 `_variants` groups (Step 23).
/// Generated from ExifTool's in-memory tag table. Do not edit by hand.
pub static PARROT_V2: BinaryTable = BinaryTable {
    module: "Parrot",
    table: "V2",
    group0: "Parrot",
    group1: "Parrot",
    group2: "Other",
    first_entry: 0,
    default_format: Fmt::Int8u,
    offsets_sound_until: None,
    priority: None,
    gate_a: GateA {
        blocked_by: &[("tag_bad_index", 1)],
    },
    fields: &[
        Field {
            index: 4,
            sub: None,
            name: "Elevation",
            format: Some(Fmt::Int32s),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: Some(ExprId::Val0x100007EF43A),
            print_conv: PrintConv::Expr(ExprId::Sprintf3fMVal40374B),
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 8,
            sub: None,
            name: "GPSLatitude",
            format: Some(Fmt::Int32s),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: Some(ExprId::Val0x4000006256DE),
            print_conv: PrintConv::Expr(ExprId::ImageExifToolGPSToDMSSelfVal1N224F39),
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 12,
            sub: None,
            name: "GPSLongitude",
            format: Some(Fmt::Int32s),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: Some(ExprId::Val0x4000006256DE),
            print_conv: PrintConv::Expr(ExprId::ImageExifToolGPSToDMSSelfVal1E4009F1),
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 16,
            sub: None,
            name: "GPSAltitude",
            format: Some(Fmt::Int32s),
            count: 1,
            mask: Some(Mask {
                bits: 0xffffff00,
                shift: 8,
            }),
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: Some(ExprId::Val0x10099B9B6),
            print_conv: PrintConv::Expr(ExprId::Sprintf3fMVal40374B),
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 16,
            sub: Some(1),
            name: "GPSSatellites",
            format: Some(Fmt::Int32s),
            count: 1,
            mask: Some(Mask {
                bits: 0xff,
                shift: 0,
            }),
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 20,
            sub: None,
            name: "GPSVelocityNorth",
            format: Some(Fmt::Int16s),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: Some(ExprId::Val0x10099B9B6),
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 22,
            sub: None,
            name: "GPSVelocityEast",
            format: Some(Fmt::Int16s),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: Some(ExprId::Val0x10099B9B6),
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 24,
            sub: None,
            name: "GPSVelocityDown",
            format: Some(Fmt::Int16s),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: Some(ExprId::Val0x10099B9B6),
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 26,
            sub: None,
            name: "AirSpeed",
            format: Some(Fmt::Int16s),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: true,
                condition: false,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            value_conv: Some(ExprId::Val0x10099B9B6),
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 28,
            sub: None,
            name: "DroneQuaternion",
            format: Some(Fmt::Int16s),
            count: 4,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: Some(ExprId::MyASplitVal0x4000ForeachAAFCC564),
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 36,
            sub: None,
            name: "FrameView",
            format: Some(Fmt::Int16s),
            count: 4,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: Some(ExprId::MyASplitVal0x4000ForeachAAFCC564),
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 44,
            sub: None,
            name: "CameraPan",
            format: Some(Fmt::Int16s),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: Some(ExprId::Val0x10001803141598CFB34),
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 46,
            sub: None,
            name: "CameraTilt",
            format: Some(Fmt::Int16s),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: Some(ExprId::Val0x10001803141598CFB34),
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 48,
            sub: None,
            name: "ExposureTime",
            format: Some(Fmt::Int16u),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: Some(ExprId::Val0x1001000B95BCC),
            print_conv: PrintConv::Expr(ExprId::ImageExifToolExifPrintExposureTimeVal6037F3),
            subdir: None,
            hook: &[],
            groups: TagGroups {
                g0: None,
                g1: None,
                g2: Some("Camera"),
            },
        },
        Field {
            index: 50,
            sub: None,
            name: "ISO",
            format: Some(Fmt::Int16u),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups {
                g0: None,
                g1: None,
                g2: Some("Camera"),
            },
        },
        Field {
            index: 52,
            sub: None,
            name: "Binning",
            format: None,
            count: 1,
            mask: Some(Mask {
                bits: 0x80,
                shift: 7,
            }),
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups {
                g0: None,
                g1: None,
                g2: Some("Device"),
            },
        },
        Field {
            index: 52,
            sub: Some(1),
            name: "FlyingState",
            format: None,
            count: 1,
            mask: Some(Mask {
                bits: 0x7f,
                shift: 0,
            }),
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[
                (0, "Landed"),
                (1, "Taking Off"),
                (2, "Hovering"),
                (3, "Flying"),
                (4, "Landing"),
                (5, "Emergency"),
                (6, "User Takeoff"),
                (7, "Motor Ramping"),
                (8, "Emergency Landing"),
            ]),
            subdir: None,
            hook: &[],
            groups: TagGroups {
                g0: None,
                g1: None,
                g2: Some("Device"),
            },
        },
        Field {
            index: 53,
            sub: None,
            name: "Animation",
            format: None,
            count: 1,
            mask: Some(Mask {
                bits: 0x80,
                shift: 7,
            }),
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups {
                g0: None,
                g1: None,
                g2: Some("Device"),
            },
        },
        Field {
            index: 53,
            sub: Some(1),
            name: "PilotingMode",
            format: None,
            count: 1,
            mask: Some(Mask {
                bits: 0x7f,
                shift: 0,
            }),
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[
                (0, "Manual"),
                (1, "Return Home"),
                (2, "Flight Plan"),
                (3, "Follow Me / Tracking"),
                (4, "Magic Carpet"),
                (5, "Move To"),
            ]),
            subdir: None,
            hook: &[],
            groups: TagGroups {
                g0: None,
                g1: None,
                g2: Some("Device"),
            },
        },
        Field {
            index: 54,
            sub: None,
            name: "WifiRSSI",
            format: Some(Fmt::Int8s),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::Expr(ExprId::ValDBm64BBA9),
            subdir: None,
            hook: &[],
            groups: TagGroups {
                g0: None,
                g1: None,
                g2: Some("Device"),
            },
        },
        Field {
            index: 55,
            sub: None,
            name: "Battery",
            format: None,
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::Expr(ExprId::Val22FAFA),
            subdir: None,
            hook: &[],
            groups: TagGroups {
                g0: None,
                g1: None,
                g2: Some("Device"),
            },
        },
    ],
    variants: &[],
};

/// `Image::ExifTool::Parrot::V3` -- 25 fields,
/// 0 `_variants` groups (Step 23).
/// Generated from ExifTool's in-memory tag table. Do not edit by hand.
pub static PARROT_V3: BinaryTable = BinaryTable {
    module: "Parrot",
    table: "V3",
    group0: "Parrot",
    group1: "Parrot",
    group2: "Location",
    first_entry: 0,
    default_format: Fmt::Int8u,
    offsets_sound_until: None,
    priority: None,
    gate_a: GateA { blocked_by: &[] },
    fields: &[
        Field {
            index: 4,
            sub: None,
            name: "Elevation",
            format: Some(Fmt::Int32s),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: Some(ExprId::Val0x100007EF43A),
            print_conv: PrintConv::Expr(ExprId::Sprintf3fMVal40374B),
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 8,
            sub: None,
            name: "GPSLatitude",
            format: Some(Fmt::Int32s),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: Some(ExprId::Val0x4000006256DE),
            print_conv: PrintConv::Expr(ExprId::ImageExifToolGPSToDMSSelfVal1N224F39),
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 12,
            sub: None,
            name: "GPSLongitude",
            format: Some(Fmt::Int32s),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: Some(ExprId::Val0x4000006256DE),
            print_conv: PrintConv::Expr(ExprId::ImageExifToolGPSToDMSSelfVal1E4009F1),
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 16,
            sub: None,
            name: "GPSAltitude",
            format: Some(Fmt::Int32s),
            count: 1,
            mask: Some(Mask {
                bits: 0xffffff00,
                shift: 8,
            }),
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: Some(ExprId::Val0x10099B9B6),
            print_conv: PrintConv::Expr(ExprId::Sprintf3fMVal40374B),
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 16,
            sub: Some(1),
            name: "GPSSatellites",
            format: Some(Fmt::Int32s),
            count: 1,
            mask: Some(Mask {
                bits: 0xff,
                shift: 0,
            }),
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 20,
            sub: None,
            name: "GPSVelocityNorth",
            format: Some(Fmt::Int16s),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: Some(ExprId::Val0x10099B9B6),
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 22,
            sub: None,
            name: "GPSVelocityEast",
            format: Some(Fmt::Int16s),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: Some(ExprId::Val0x10099B9B6),
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 24,
            sub: None,
            name: "GPSVelocityDown",
            format: Some(Fmt::Int16s),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: Some(ExprId::Val0x10099B9B6),
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 26,
            sub: None,
            name: "AirSpeed",
            format: Some(Fmt::Int16s),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: true,
                condition: false,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            value_conv: Some(ExprId::Val0x10099B9B6),
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 28,
            sub: None,
            name: "DroneQuaternion",
            format: Some(Fmt::Int16s),
            count: 4,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: Some(ExprId::MyASplitVal0x4000ForeachAAFCC564),
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 36,
            sub: None,
            name: "FrameBaseView",
            format: Some(Fmt::Int16s),
            count: 4,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: Some(ExprId::MyASplitVal0x4000ForeachAAFCC564),
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 44,
            sub: None,
            name: "FrameView",
            format: Some(Fmt::Int16s),
            count: 4,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: Some(ExprId::MyASplitVal0x4000ForeachAAFCC564),
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 52,
            sub: None,
            name: "ExposureTime",
            format: Some(Fmt::Int16u),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: Some(ExprId::Val0x1001000B95BCC),
            print_conv: PrintConv::Expr(ExprId::ImageExifToolExifPrintExposureTimeVal6037F3),
            subdir: None,
            hook: &[],
            groups: TagGroups {
                g0: None,
                g1: None,
                g2: Some("Camera"),
            },
        },
        Field {
            index: 54,
            sub: None,
            name: "ISO",
            format: Some(Fmt::Int16u),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups {
                g0: None,
                g1: None,
                g2: Some("Camera"),
            },
        },
        Field {
            index: 56,
            sub: None,
            name: "RedBalance",
            format: Some(Fmt::Int16u),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: Some(ExprId::Val0x4000600D34),
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups {
                g0: None,
                g1: None,
                g2: Some("Camera"),
            },
        },
        Field {
            index: 58,
            sub: None,
            name: "BlueBalance",
            format: Some(Fmt::Int16u),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: Some(ExprId::Val0x4000600D34),
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups {
                g0: None,
                g1: None,
                g2: Some("Camera"),
            },
        },
        Field {
            index: 60,
            sub: None,
            name: "FOV",
            format: Some(Fmt::Int16u),
            count: 2,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: Some(ExprId::MyASplitVal0x100ForeachAA28176B),
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups {
                g0: None,
                g1: None,
                g2: Some("Image"),
            },
        },
        Field {
            index: 64,
            sub: None,
            name: "LinkGoodput",
            format: Some(Fmt::Int32u),
            count: 1,
            mask: Some(Mask {
                bits: 0xffffff00,
                shift: 8,
            }),
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::Expr(ExprId::ValKbitSA388E2),
            subdir: None,
            hook: &[],
            groups: TagGroups {
                g0: None,
                g1: None,
                g2: Some("Device"),
            },
        },
        Field {
            index: 64,
            sub: Some(1),
            name: "LinkQuality",
            format: Some(Fmt::Int32u),
            count: 1,
            mask: Some(Mask {
                bits: 0xff,
                shift: 0,
            }),
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups {
                g0: None,
                g1: None,
                g2: Some("Device"),
            },
        },
        Field {
            index: 68,
            sub: None,
            name: "WifiRSSI",
            format: Some(Fmt::Int8s),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::Expr(ExprId::ValDBm64BBA9),
            subdir: None,
            hook: &[],
            groups: TagGroups {
                g0: None,
                g1: None,
                g2: Some("Device"),
            },
        },
        Field {
            index: 69,
            sub: None,
            name: "Battery",
            format: None,
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::Expr(ExprId::Val22FAFA),
            subdir: None,
            hook: &[],
            groups: TagGroups {
                g0: None,
                g1: None,
                g2: Some("Device"),
            },
        },
        Field {
            index: 70,
            sub: None,
            name: "Binning",
            format: None,
            count: 1,
            mask: Some(Mask {
                bits: 0x80,
                shift: 7,
            }),
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups {
                g0: None,
                g1: None,
                g2: Some("Device"),
            },
        },
        Field {
            index: 70,
            sub: Some(1),
            name: "FlyingState",
            format: None,
            count: 1,
            mask: Some(Mask {
                bits: 0x7f,
                shift: 0,
            }),
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[
                (0, "Landed"),
                (1, "Taking Off"),
                (2, "Hovering"),
                (3, "Flying"),
                (4, "Landing"),
                (5, "Emergency"),
                (6, "User Takeoff"),
                (7, "Motor Ramping"),
                (8, "Emergency Landing"),
            ]),
            subdir: None,
            hook: &[],
            groups: TagGroups {
                g0: None,
                g1: None,
                g2: Some("Device"),
            },
        },
        Field {
            index: 71,
            sub: None,
            name: "Animation",
            format: None,
            count: 1,
            mask: Some(Mask {
                bits: 0x80,
                shift: 7,
            }),
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups {
                g0: None,
                g1: None,
                g2: Some("Device"),
            },
        },
        Field {
            index: 71,
            sub: Some(1),
            name: "PilotingMode",
            format: None,
            count: 1,
            mask: Some(Mask {
                bits: 0x7f,
                shift: 0,
            }),
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[
                (0, "Manual"),
                (1, "Return Home"),
                (2, "Flight Plan"),
                (3, "Follow Me / Tracking"),
                (4, "Magic Carpet"),
                (5, "Move To"),
            ]),
            subdir: None,
            hook: &[],
            groups: TagGroups {
                g0: None,
                g1: None,
                g2: Some("Device"),
            },
        },
    ],
    variants: &[],
};
