//! ExifTool `RIFF` ProcessBinaryData tables, generated from ExifTool
//! 13.59's own Perl hashes -- one file per module; `mod.rs` beside this
//! file is the hub that declares and re-exports it.
//!
//! DO NOT EDIT. Regenerate with `just regen-tables` (see `mod.rs`).

#![allow(clippy::unreadable_literal, clippy::too_many_lines, unused_parens)]

// Everything a table literal names -- the schema types, `ExprId`, the
// `cond`/`subdir`/`ifd_schema` imports -- is in scope in the hub, and a glob
// import of the parent module brings its private imports along (RFC 1560).
#[allow(unused_imports)]
use super::*;

/// `Image::ExifTool::RIFF::ALPH` -- 3 fields,
/// 0 `_variants` groups (Step 23).
/// Generated from ExifTool's in-memory tag table. Do not edit by hand.
pub static RIFF_ALPH: BinaryTable = BinaryTable {
    module: "RIFF",
    table: "ALPH",
    group0: "RIFF",
    group1: "RIFF",
    group2: "Image",
    first_entry: 0,
    default_format: Fmt::Int8u,
    offsets_sound_until: None,
    priority: None,
    gate_a: GateA { blocked_by: &[] },
    fields: &[
        Field {
            index: 0,
            sub: None,
            name: "AlphaPreprocessing",
            format: None,
            count: 1,
            mask: Some(Mask {
                bits: 0x3,
                shift: 0,
            }),
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[(0, "none"), (1, "Level Reduction")]),
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 0,
            sub: Some(1),
            name: "AlphaFiltering",
            format: None,
            count: 1,
            mask: Some(Mask {
                bits: 0x3,
                shift: 0,
            }),
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[
                (0, "none"),
                (1, "Horizontal"),
                (2, "Vertical"),
                (3, "Gradient"),
            ]),
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 0,
            sub: Some(2),
            name: "AlphaCompression",
            format: None,
            count: 1,
            mask: Some(Mask {
                bits: 0x3,
                shift: 0,
            }),
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[(0, "none"), (1, "Lossless")]),
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
    ],
    variants: &[],
};

/// `Image::ExifTool::RIFF::ANIM` -- 2 fields,
/// 0 `_variants` groups (Step 23).
/// Generated from ExifTool's in-memory tag table. Do not edit by hand.
pub static RIFF_ANIM: BinaryTable = BinaryTable {
    module: "RIFF",
    table: "ANIM",
    group0: "RIFF",
    group1: "RIFF",
    group2: "Image",
    first_entry: 0,
    default_format: Fmt::Int8u,
    offsets_sound_until: None,
    priority: None,
    gate_a: GateA {
        blocked_by: &[("expr_unsupported", 1)],
    },
    fields: &[
        Field {
            index: 0,
            sub: None,
            name: "BackgroundColor",
            format: Some(Fmt::Int8u),
            count: 4,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 4,
            sub: None,
            name: "AnimationLoopCount",
            format: None,
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
    ],
    variants: &[],
};

/// `Image::ExifTool::RIFF::ANMF` -- 1 fields,
/// 0 `_variants` groups (Step 23).
/// Generated from ExifTool's in-memory tag table. Do not edit by hand.
pub static RIFF_ANMF: BinaryTable = BinaryTable {
    module: "RIFF",
    table: "ANMF",
    group0: "RIFF",
    group1: "RIFF",
    group2: "Image",
    first_entry: 0,
    default_format: Fmt::Int8u,
    offsets_sound_until: None,
    priority: None,
    gate_a: GateA { blocked_by: &[] },
    fields: &[Field {
        index: 12,
        sub: None,
        name: "Duration",
        format: Some(Fmt::Int32u),
        count: 1,
        mask: None,
        condition: None,
        raw_conv: None,
        omitted: Omitted {
            value_conv: false,
            raw_conv: true,
            condition: false,
            hook: false,
            subdirectory: false,
            print_conv: false,
        },
        value_conv: Some(ExprId::Val1000F42638),
        print_conv: PrintConv::Expr(ExprId::ConvertDurationVal90FB81),
        subdir: None,
        hook: &[],
        groups: TagGroups::NONE,
    }],
    variants: &[],
};

/// `Image::ExifTool::RIFF::AVIHeader` -- 6 fields,
/// 0 `_variants` groups (Step 23).
/// Generated from ExifTool's in-memory tag table. Do not edit by hand.
pub static RIFF_AVIHEADER: BinaryTable = BinaryTable {
    module: "RIFF",
    table: "AVIHeader",
    group0: "RIFF",
    group1: "RIFF",
    group2: "Video",
    first_entry: 0,
    default_format: Fmt::Int32u,
    offsets_sound_until: None,
    priority: None,
    gate_a: GateA {
        blocked_by: &[("expr_unsupported", 1)],
    },
    fields: &[
        Field {
            index: 0,
            sub: None,
            name: "FrameRate",
            format: None,
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: true,
                condition: false,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            value_conv: None,
            print_conv: PrintConv::Expr(ExprId::IntVal10000510006E64E7),
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 1,
            sub: None,
            name: "MaxDataRate",
            format: None,
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 4,
            sub: None,
            name: "FrameCount",
            format: None,
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 6,
            sub: None,
            name: "StreamCount",
            format: None,
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 8,
            sub: None,
            name: "ImageWidth",
            format: None,
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 9,
            sub: None,
            name: "ImageHeight",
            format: None,
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
    ],
    variants: &[],
};

/// `Image::ExifTool::RIFF::Acidizer` -- 5 fields,
/// 0 `_variants` groups (Step 23).
/// Generated from ExifTool's in-memory tag table. Do not edit by hand.
pub static RIFF_ACIDIZER: BinaryTable = BinaryTable {
    module: "RIFF",
    table: "Acidizer",
    group0: "RIFF",
    group1: "RIFF",
    group2: "Audio",
    first_entry: 0,
    default_format: Fmt::Int8u,
    offsets_sound_until: None,
    priority: None,
    gate_a: GateA {
        blocked_by: &[("expr_unsupported", 1)],
    },
    fields: &[
        Field {
            index: 0,
            sub: None,
            name: "AcidizerFlags",
            format: Some(Fmt::Int32u),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::Bitmask {
                exact: &[],
                bits: &[
                    (0, "One shot"),
                    (1, "Root note set"),
                    (2, "Stretch"),
                    (3, "Disk-based"),
                    (4, "High octave"),
                ],
            },
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 4,
            sub: None,
            name: "RootNote",
            format: Some(Fmt::Int16u),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[
                (48, "C"),
                (49, "C#"),
                (50, "D"),
                (51, "D#"),
                (52, "E"),
                (53, "F"),
                (54, "F#"),
                (55, "G"),
                (56, "G#"),
                (57, "A"),
                (58, "A#"),
                (59, "B"),
                (60, "High C"),
                (61, "High C#"),
                (62, "High D"),
                (63, "High D#"),
                (64, "High E"),
                (65, "High F"),
                (66, "High F#"),
                (67, "High G"),
                (68, "High G#"),
                (69, "High A"),
                (70, "High A#"),
                (71, "High B"),
            ]),
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 12,
            sub: None,
            name: "Beats",
            format: Some(Fmt::Int32u),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 16,
            sub: None,
            name: "Meter",
            format: Some(Fmt::Int16u),
            count: 2,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 20,
            sub: None,
            name: "Tempo",
            format: Some(Fmt::Float),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
    ],
    variants: &[],
};

/// `Image::ExifTool::RIFF::AudioFormat` -- 5 fields,
/// 0 `_variants` groups (Step 23).
/// Generated from ExifTool's in-memory tag table. Do not edit by hand.
pub static RIFF_AUDIOFORMAT: BinaryTable = BinaryTable {
    module: "RIFF",
    table: "AudioFormat",
    group0: "RIFF",
    group1: "RIFF",
    group2: "Audio",
    first_entry: 0,
    default_format: Fmt::Int16u,
    offsets_sound_until: None,
    priority: None,
    gate_a: GateA { blocked_by: &[] },
    fields: &[
        Field {
            index: 0,
            sub: None,
            name: "Encoding",
            format: None,
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::PartialEnumInt {
                exact: &[
                    (1, "Microsoft PCM"),
                    (2, "Microsoft ADPCM"),
                    (3, "Microsoft IEEE float"),
                    (4, "Compaq VSELP"),
                    (5, "IBM CVSD"),
                    (6, "Microsoft a-Law"),
                    (7, "Microsoft u-Law"),
                    (8, "Microsoft DTS"),
                    (9, "DRM"),
                    (10, "WMA 9 Speech"),
                    (11, "Microsoft Windows Media RT Voice"),
                    (16, "OKI-ADPCM"),
                    (17, "Intel IMA/DVI-ADPCM"),
                    (18, "Videologic Mediaspace ADPCM"),
                    (19, "Sierra ADPCM"),
                    (20, "Antex G.723 ADPCM"),
                    (21, "DSP Solutions DIGISTD"),
                    (22, "DSP Solutions DIGIFIX"),
                    (23, "Dialoic OKI ADPCM"),
                    (24, "Media Vision ADPCM"),
                    (25, "HP CU"),
                    (26, "HP Dynamic Voice"),
                    (32, "Yamaha ADPCM"),
                    (33, "SONARC Speech Compression"),
                    (34, "DSP Group True Speech"),
                    (35, "Echo Speech Corp."),
                    (36, "Virtual Music Audiofile AF36"),
                    (37, "Audio Processing Tech."),
                    (38, "Virtual Music Audiofile AF10"),
                    (39, "Aculab Prosody 1612"),
                    (40, "Merging Tech. LRC"),
                    (48, "Dolby AC2"),
                    (49, "Microsoft GSM610"),
                    (50, "MSN Audio"),
                    (51, "Antex ADPCME"),
                    (52, "Control Resources VQLPC"),
                    (53, "DSP Solutions DIGIREAL"),
                    (54, "DSP Solutions DIGIADPCM"),
                    (55, "Control Resources CR10"),
                    (56, "Natural MicroSystems VBX ADPCM"),
                    (57, "Crystal Semiconductor IMA ADPCM"),
                    (58, "Echo Speech ECHOSC3"),
                    (59, "Rockwell ADPCM"),
                    (60, "Rockwell DIGITALK"),
                    (61, "Xebec Multimedia"),
                    (64, "Antex G.721 ADPCM"),
                    (65, "Antex G.728 CELP"),
                    (66, "Microsoft MSG723"),
                    (67, "IBM AVC ADPCM"),
                    (69, "ITU-T G.726"),
                    (80, "Microsoft MPEG"),
                    (81, "RT23 or PAC"),
                    (82, "InSoft RT24"),
                    (83, "InSoft PAC"),
                    (85, "MP3"),
                    (89, "Cirrus"),
                    (96, "Cirrus Logic"),
                    (97, "ESS Tech. PCM"),
                    (98, "Voxware Inc."),
                    (99, "Canopus ATRAC"),
                    (100, "APICOM G.726 ADPCM"),
                    (101, "APICOM G.722 ADPCM"),
                    (102, "Microsoft DSAT"),
                    (103, "Microsoft DSAT DISPLAY"),
                    (105, "Voxware Byte Aligned"),
                    (112, "Voxware AC8"),
                    (113, "Voxware AC10"),
                    (114, "Voxware AC16"),
                    (115, "Voxware AC20"),
                    (116, "Voxware MetaVoice"),
                    (117, "Voxware MetaSound"),
                    (118, "Voxware RT29HW"),
                    (119, "Voxware VR12"),
                    (120, "Voxware VR18"),
                    (121, "Voxware TQ40"),
                    (122, "Voxware SC3"),
                    (123, "Voxware SC3"),
                    (128, "Soundsoft"),
                    (129, "Voxware TQ60"),
                    (130, "Microsoft MSRT24"),
                    (131, "AT&T G.729A"),
                    (132, "Motion Pixels MVI MV12"),
                    (133, "DataFusion G.726"),
                    (134, "DataFusion GSM610"),
                    (136, "Iterated Systems Audio"),
                    (137, "Onlive"),
                    (138, "Multitude, Inc. FT SX20"),
                    (139, "Infocom ITS A/S G.721 ADPCM"),
                    (140, "Convedia G729"),
                    (141, "Not specified congruency, Inc."),
                    (145, "Siemens SBC24"),
                    (146, "Sonic Foundry Dolby AC3 APDIF"),
                    (147, "MediaSonic G.723"),
                    (148, "Aculab Prosody 8kbps"),
                    (151, "ZyXEL ADPCM"),
                    (152, "Philips LPCBB"),
                    (153, "Studer Professional Audio Packed"),
                    (160, "Malden PhonyTalk"),
                    (161, "Racal Recorder GSM"),
                    (162, "Racal Recorder G720.a"),
                    (163, "Racal G723.1"),
                    (164, "Racal Tetra ACELP"),
                    (176, "NEC AAC NEC Corporation"),
                    (255, "AAC"),
                    (256, "Rhetorex ADPCM"),
                    (257, "IBM u-Law"),
                    (258, "IBM a-Law"),
                    (259, "IBM ADPCM"),
                    (273, "Vivo G.723"),
                    (274, "Vivo Siren"),
                    (288, "Philips Speech Processing CELP"),
                    (289, "Philips Speech Processing GRUNDIG"),
                    (291, "Digital G.723"),
                    (293, "Sanyo LD ADPCM"),
                    (304, "Sipro Lab ACEPLNET"),
                    (305, "Sipro Lab ACELP4800"),
                    (306, "Sipro Lab ACELP8V3"),
                    (307, "Sipro Lab G.729"),
                    (308, "Sipro Lab G.729A"),
                    (309, "Sipro Lab Kelvin"),
                    (310, "VoiceAge AMR"),
                    (320, "Dictaphone G.726 ADPCM"),
                    (336, "Qualcomm PureVoice"),
                    (337, "Qualcomm HalfRate"),
                    (341, "Ring Zero Systems TUBGSM"),
                    (352, "Microsoft Audio1"),
                    (
                        353,
                        "Windows Media Audio V2 V7 V8 V9 / DivX audio (WMA) / Alex AC3 Audio",
                    ),
                    (354, "Windows Media Audio Professional V9"),
                    (355, "Windows Media Audio Lossless V9"),
                    (356, "WMA Pro over S/PDIF"),
                    (368, "UNISYS NAP ADPCM"),
                    (369, "UNISYS NAP ULAW"),
                    (370, "UNISYS NAP ALAW"),
                    (371, "UNISYS NAP 16K"),
                    (372, "MM SYCOM ACM SYC008 SyCom Technologies"),
                    (373, "MM SYCOM ACM SYC701 G726L SyCom Technologies"),
                    (374, "MM SYCOM ACM SYC701 CELP54 SyCom Technologies"),
                    (375, "MM SYCOM ACM SYC701 CELP68 SyCom Technologies"),
                    (376, "Knowledge Adventure ADPCM"),
                    (384, "Fraunhofer IIS MPEG2AAC"),
                    (400, "Digital Theater Systems DTS DS"),
                    (512, "Creative Labs ADPCM"),
                    (514, "Creative Labs FASTSPEECH8"),
                    (515, "Creative Labs FASTSPEECH10"),
                    (528, "UHER ADPCM"),
                    (533, "Ulead DV ACM"),
                    (534, "Ulead DV ACM"),
                    (544, "Quarterdeck Corp."),
                    (560, "I-Link VC"),
                    (576, "Aureal Semiconductor Raw Sport"),
                    (577, "ESST AC3"),
                    (592, "Interactive Products HSX"),
                    (593, "Interactive Products RPELP"),
                    (608, "Consistent CS2"),
                    (624, "Sony SCX"),
                    (625, "Sony SCY"),
                    (626, "Sony ATRAC3"),
                    (627, "Sony SPC"),
                    (640, "TELUM Telum Inc."),
                    (641, "TELUMIA Telum Inc."),
                    (645, "Norcom Voice Systems ADPCM"),
                    (768, "Fujitsu FM TOWNS SND"),
                    (769, "Fujitsu (not specified)"),
                    (770, "Fujitsu (not specified)"),
                    (771, "Fujitsu (not specified)"),
                    (772, "Fujitsu (not specified)"),
                    (773, "Fujitsu (not specified)"),
                    (774, "Fujitsu (not specified)"),
                    (775, "Fujitsu (not specified)"),
                    (776, "Fujitsu (not specified)"),
                    (848, "Micronas Semiconductors, Inc. Development"),
                    (849, "Micronas Semiconductors, Inc. CELP833"),
                    (1024, "Brooktree Digital"),
                    (1025, "Intel Music Coder (IMC)"),
                    (1026, "Ligos Indeo Audio"),
                    (1104, "QDesign Music"),
                    (1280, "On2 VP7 On2 Technologies"),
                    (1281, "On2 VP6 On2 Technologies"),
                    (1664, "AT&T VME VMPCM"),
                    (1665, "AT&T TCP"),
                    (1792, "YMPEG Alpha (dummy for MPEG-2 compressor)"),
                    (2222, "ClearJump LiteWave (lossless)"),
                    (4096, "Olivetti GSM"),
                    (4097, "Olivetti ADPCM"),
                    (4098, "Olivetti CELP"),
                    (4099, "Olivetti SBC"),
                    (4100, "Olivetti OPR"),
                    (4352, "Lernout & Hauspie"),
                    (4353, "Lernout & Hauspie CELP codec"),
                    (4354, "Lernout & Hauspie SBC codec"),
                    (4355, "Lernout & Hauspie SBC codec"),
                    (4356, "Lernout & Hauspie SBC codec"),
                    (5120, "Norris Comm. Inc."),
                    (5121, "ISIAudio"),
                    (5376, "AT&T Soundspace Music Compression"),
                    (6172, "VoxWare RT24 speech codec"),
                    (6174, "Lucent elemedia AX24000P Music codec"),
                    (6513, "Sonic Foundry LOSSLESS"),
                    (6521, "Innings Telecom Inc. ADPCM"),
                    (7175, "Lucent SX8300P speech codec"),
                    (7180, "Lucent SX5363S G.723 compliant codec"),
                    (7939, "CUseeMe DigiTalk (ex-Rocwell)"),
                    (8132, "NCT Soft ALF2CD ACM"),
                    (8192, "FAST Multimedia DVM"),
                    (8193, "Dolby DTS (Digital Theater System)"),
                    (8194, "RealAudio 1 / 2 14.4"),
                    (8195, "RealAudio 1 / 2 28.8"),
                    (8196, "RealAudio G2 / 8 Cook (low bitrate)"),
                    (8197, "RealAudio 3 / 4 / 5 Music (DNET)"),
                    (8198, "RealAudio 10 AAC (RAAC)"),
                    (8199, "RealAudio 10 AAC+ (RACP)"),
                    (9472, "Reserved range to 0x2600 Microsoft"),
                    (
                        13075,
                        "makeAVIS (ffvfw fake AVI sound from AviSynth scripts)",
                    ),
                    (16707, "Divio MPEG-4 AAC audio"),
                    (16897, "Nokia adaptive multirate"),
                    (16963, "Divio G726 Divio, Inc."),
                    (17228, "LEAD Speech"),
                    (22092, "LEAD Vorbis"),
                    (22358, "WavPack Audio"),
                    (26447, "Ogg Vorbis (mode 1)"),
                    (26448, "Ogg Vorbis (mode 2)"),
                    (26449, "Ogg Vorbis (mode 3)"),
                    (26479, "Ogg Vorbis (mode 1+)"),
                    (26480, "Ogg Vorbis (mode 2+)"),
                    (26481, "Ogg Vorbis (mode 3+)"),
                    (28672, "3COM NBX 3Com Corporation"),
                    (28781, "FAAD AAC"),
                    (31265, "GSM-AMR (CBR, no SID)"),
                    (31266, "GSM-AMR (VBR, including SID)"),
                    (41216, "Comverse Infosys Ltd. G723 1"),
                    (41217, "Comverse Infosys Ltd. AVQSBC"),
                    (41218, "Comverse Infosys Ltd. OLDSBC"),
                    (41219, "Symbol Technologies G729A"),
                    (41220, "VoiceAge AMR WB VoiceAge Corporation"),
                    (41221, "Ingenient Technologies Inc. G726"),
                    (41222, "ISO/MPEG-4 advanced audio Coding"),
                    (41223, "Encore Software Ltd G726"),
                    (41225, "Speex ACM Codec xiph.org"),
                    (57260, "DebugMode SonicFoundry Vegas FrameServer ACM Codec"),
                    (59144, "Unknown -"),
                    (61868, "Free Lossless Audio Codec FLAC"),
                    (65534, "Extensible"),
                    (65535, "Development"),
                ],
                other: None,
                print_hex: true,
            },
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 1,
            sub: None,
            name: "NumChannels",
            format: None,
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 2,
            sub: None,
            name: "SampleRate",
            format: Some(Fmt::Int32u),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 4,
            sub: None,
            name: "AvgBytesPerSec",
            format: Some(Fmt::Int32u),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 7,
            sub: None,
            name: "BitsPerSample",
            format: None,
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
    ],
    variants: &[],
};

/// `Image::ExifTool::RIFF::BroadcastExt` -- 7 fields,
/// 0 `_variants` groups (Step 23).
/// Generated from ExifTool's in-memory tag table. Do not edit by hand.
pub static RIFF_BROADCASTEXT: BinaryTable = BinaryTable {
    module: "RIFF",
    table: "BroadcastExt",
    group0: "RIFF",
    group1: "RIFF",
    group2: "Audio",
    first_entry: 0,
    default_format: Fmt::Int8u,
    offsets_sound_until: None,
    priority: None,
    gate_a: GateA {
        blocked_by: &[("tag_fmt_unsupported", 1)],
    },
    fields: &[
        Field {
            index: 0,
            sub: None,
            name: "Description",
            format: Some(Fmt::Str(256)),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 256,
            sub: None,
            name: "Originator",
            format: Some(Fmt::Str(32)),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 288,
            sub: None,
            name: "OriginatorReference",
            format: Some(Fmt::Str(32)),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 320,
            sub: None,
            name: "DateTimeOriginal",
            format: Some(Fmt::Str(18)),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted {
                value_conv: true,
                raw_conv: false,
                condition: false,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            value_conv: None,
            print_conv: PrintConv::Expr(ExprId::SelfConvertDateTimeVal7455B8),
            subdir: None,
            hook: &[],
            groups: TagGroups {
                g0: None,
                g1: None,
                g2: Some("Time"),
            },
        },
        Field {
            index: 338,
            sub: None,
            name: "TimeReference",
            format: Some(Fmt::Int32u),
            count: 2,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: Some(ExprId::MyVSplitValV0V1429496729629D062),
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 346,
            sub: None,
            name: "BWFVersion",
            format: Some(Fmt::Int16u),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 348,
            sub: None,
            name: "BWF_UMID",
            format: Some(Fmt::Undef(64)),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted {
                value_conv: true,
                raw_conv: false,
                condition: false,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
    ],
    variants: &[],
};

/// `Image::ExifTool::RIFF::CSET` -- 4 fields,
/// 0 `_variants` groups (Step 23).
/// Generated from ExifTool's in-memory tag table. Do not edit by hand.
pub static RIFF_CSET: BinaryTable = BinaryTable {
    module: "RIFF",
    table: "CSET",
    group0: "RIFF",
    group1: "RIFF",
    group2: "Other",
    first_entry: 0,
    default_format: Fmt::Int16u,
    offsets_sound_until: None,
    priority: None,
    gate_a: GateA { blocked_by: &[] },
    fields: &[
        Field {
            index: 0,
            sub: None,
            name: "CodePage",
            format: None,
            count: 1,
            mask: None,
            condition: None,
            raw_conv: Some(RawConvEffect::SetMember { member: "CodePage" }),
            omitted: Omitted {
                value_conv: false,
                raw_conv: true,
                condition: false,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 1,
            sub: None,
            name: "CountryCode",
            format: None,
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 2,
            sub: None,
            name: "LanguageCode",
            format: None,
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 3,
            sub: None,
            name: "Dialect",
            format: None,
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
    ],
    variants: &[],
};

/// `Image::ExifTool::RIFF::DS64` -- 3 fields,
/// 0 `_variants` groups (Step 23).
/// Generated from ExifTool's in-memory tag table. Do not edit by hand.
pub static RIFF_DS64: BinaryTable = BinaryTable {
    module: "RIFF",
    table: "DS64",
    group0: "RIFF",
    group1: "RIFF",
    group2: "Audio",
    first_entry: 0,
    default_format: Fmt::Int64u,
    offsets_sound_until: None,
    priority: None,
    gate_a: GateA { blocked_by: &[] },
    fields: &[
        Field {
            index: 0,
            sub: None,
            name: "RIFFSize64",
            format: None,
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::Expr(ExprId::ImageExifToolConvertFileSizeValB52C73),
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 1,
            sub: None,
            name: "DataSize64",
            format: None,
            count: 1,
            mask: None,
            condition: None,
            raw_conv: Some(RawConvEffect::SetMember {
                member: "DataSize64",
            }),
            omitted: Omitted {
                value_conv: false,
                raw_conv: true,
                condition: false,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            value_conv: None,
            print_conv: PrintConv::Expr(ExprId::ImageExifToolConvertFileSizeValB52C73),
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 2,
            sub: None,
            name: "NumberOfSamples64",
            format: None,
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
    ],
    variants: &[],
};

/// `Image::ExifTool::RIFF::ExtAVIHdr` -- 1 fields,
/// 0 `_variants` groups (Step 23).
/// Generated from ExifTool's in-memory tag table. Do not edit by hand.
pub static RIFF_EXTAVIHDR: BinaryTable = BinaryTable {
    module: "RIFF",
    table: "ExtAVIHdr",
    group0: "RIFF",
    group1: "RIFF",
    group2: "Video",
    first_entry: 0,
    default_format: Fmt::Int32u,
    offsets_sound_until: None,
    priority: None,
    gate_a: GateA { blocked_by: &[] },
    fields: &[Field {
        index: 0,
        sub: None,
        name: "TotalFrameCount",
        format: None,
        count: 1,
        mask: None,
        condition: None,
        raw_conv: None,
        omitted: Omitted::NONE,
        value_conv: None,
        print_conv: PrintConv::None,
        subdir: None,
        hook: &[],
        groups: TagGroups::NONE,
    }],
    variants: &[],
};

/// `Image::ExifTool::RIFF::Instrument` -- 7 fields,
/// 0 `_variants` groups (Step 23).
/// Generated from ExifTool's in-memory tag table. Do not edit by hand.
pub static RIFF_INSTRUMENT: BinaryTable = BinaryTable {
    module: "RIFF",
    table: "Instrument",
    group0: "RIFF",
    group1: "RIFF",
    group2: "Audio",
    first_entry: 0,
    default_format: Fmt::Int8s,
    offsets_sound_until: None,
    priority: None,
    gate_a: GateA { blocked_by: &[] },
    fields: &[
        Field {
            index: 0,
            sub: None,
            name: "UnshiftedNote",
            format: None,
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 1,
            sub: None,
            name: "FineTune",
            format: None,
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 2,
            sub: None,
            name: "Gain",
            format: None,
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 3,
            sub: None,
            name: "LowNote",
            format: None,
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 4,
            sub: None,
            name: "HighNote",
            format: None,
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 5,
            sub: None,
            name: "LowVelocity",
            format: None,
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 6,
            sub: None,
            name: "HighVelocity",
            format: None,
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
    ],
    variants: &[],
};

/// `Image::ExifTool::RIFF::Sampler` -- 9 fields,
/// 0 `_variants` groups (Step 23).
/// Generated from ExifTool's in-memory tag table. Do not edit by hand.
pub static RIFF_SAMPLER: BinaryTable = BinaryTable {
    module: "RIFF",
    table: "Sampler",
    group0: "RIFF",
    group1: "RIFF",
    group2: "Audio",
    first_entry: 0,
    default_format: Fmt::Int32u,
    offsets_sound_until: None,
    priority: None,
    gate_a: GateA {
        blocked_by: &[("tag_fmt_unsupported", 1)],
    },
    fields: &[
        Field {
            index: 0,
            sub: None,
            name: "Manufacturer",
            format: None,
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 1,
            sub: None,
            name: "Product",
            format: None,
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 2,
            sub: None,
            name: "SamplePeriod",
            format: None,
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 3,
            sub: None,
            name: "MIDIUnityNote",
            format: None,
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 4,
            sub: None,
            name: "MIDIPitchFraction",
            format: None,
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 5,
            sub: None,
            name: "SMPTEFormat",
            format: None,
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[
                (0, "none"),
                (24, "24 fps"),
                (25, "25 fps"),
                (29, "29 fps"),
                (30, "30 fps"),
            ]),
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 6,
            sub: None,
            name: "SMPTEOffset",
            format: None,
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted {
                value_conv: true,
                raw_conv: false,
                condition: false,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 7,
            sub: None,
            name: "NumSampleLoops",
            format: None,
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 8,
            sub: None,
            name: "SamplerDataLen",
            format: None,
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
    ],
    variants: &[],
};

/// `Image::ExifTool::RIFF::StreamHeader` -- 3 fields,
/// 3 `_variants` groups (Step 23).
/// Generated from ExifTool's in-memory tag table. Do not edit by hand.
pub static RIFF_STREAMHEADER: BinaryTable = BinaryTable {
    module: "RIFF",
    table: "StreamHeader",
    group0: "RIFF",
    group1: "RIFF",
    group2: "Video",
    first_entry: 0,
    default_format: Fmt::Int32u,
    offsets_sound_until: None,
    priority: Some(0),
    gate_a: GateA {
        blocked_by: &[("expr_unsupported", 1)],
    },
    fields: &[
        Field {
            index: 0,
            sub: None,
            name: "StreamType",
            format: Some(Fmt::Str(4)),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: true,
                condition: false,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            value_conv: None,
            print_conv: PrintConv::StrEnum(&[
                ("auds", "Audio"),
                ("iavs", "Interleaved Audio+Video"),
                ("mids", "MIDI"),
                ("txts", "Text"),
                ("vids", "Video"),
            ]),
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 10,
            sub: None,
            name: "Quality",
            format: None,
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 11,
            sub: None,
            name: "SampleSize",
            format: None,
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::Expr(ExprId::ValValByteVal1SVariable093433),
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
    ],
    variants: &[
        VariantGroup {
            index: 1,
            sub: None,
            alternatives: &[
                (
                    Cond::MemberStrEq {
                        member: "RIFFStreamType",
                        value: "auds",
                        negate: false,
                    },
                    Field {
                        index: 1,
                        sub: None,
                        name: "AudioCodec",
                        format: Some(Fmt::Str(4)),
                        count: 1,
                        mask: None,
                        condition: Some(Cond::MemberStrEq {
                            member: "RIFFStreamType",
                            value: "auds",
                            negate: false,
                        }),
                        raw_conv: None,
                        omitted: Omitted {
                            value_conv: false,
                            raw_conv: true,
                            condition: false,
                            hook: false,
                            subdirectory: false,
                            print_conv: false,
                        },
                        value_conv: None,
                        print_conv: PrintConv::None,
                        subdir: None,
                        hook: &[],
                        groups: TagGroups::NONE,
                    },
                ),
                (
                    Cond::MemberStrEq {
                        member: "RIFFStreamType",
                        value: "vids",
                        negate: false,
                    },
                    Field {
                        index: 1,
                        sub: None,
                        name: "VideoCodec",
                        format: Some(Fmt::Str(4)),
                        count: 1,
                        mask: None,
                        condition: Some(Cond::MemberStrEq {
                            member: "RIFFStreamType",
                            value: "vids",
                            negate: false,
                        }),
                        raw_conv: None,
                        omitted: Omitted {
                            value_conv: false,
                            raw_conv: true,
                            condition: false,
                            hook: false,
                            subdirectory: false,
                            print_conv: false,
                        },
                        value_conv: None,
                        print_conv: PrintConv::None,
                        subdir: None,
                        hook: &[],
                        groups: TagGroups::NONE,
                    },
                ),
                (
                    Cond::Always,
                    Field {
                        index: 1,
                        sub: None,
                        name: "Codec",
                        format: Some(Fmt::Str(4)),
                        count: 1,
                        mask: None,
                        condition: None,
                        raw_conv: None,
                        omitted: Omitted {
                            value_conv: false,
                            raw_conv: true,
                            condition: false,
                            hook: false,
                            subdirectory: false,
                            print_conv: false,
                        },
                        value_conv: None,
                        print_conv: PrintConv::None,
                        subdir: None,
                        hook: &[],
                        groups: TagGroups::NONE,
                    },
                ),
            ],
        },
        VariantGroup {
            index: 5,
            sub: None,
            alternatives: &[
                (
                    Cond::MemberStrEq {
                        member: "RIFFStreamType",
                        value: "auds",
                        negate: false,
                    },
                    Field {
                        index: 5,
                        sub: None,
                        name: "AudioSampleRate",
                        format: Some(Fmt::Rational64u),
                        count: 1,
                        mask: None,
                        condition: Some(Cond::MemberStrEq {
                            member: "RIFFStreamType",
                            value: "auds",
                            negate: false,
                        }),
                        raw_conv: None,
                        omitted: Omitted::NONE,
                        value_conv: Some(ExprId::Val1Val0EAB507),
                        print_conv: PrintConv::Expr(ExprId::IntVal100051005DA1FC),
                        subdir: None,
                        hook: &[],
                        groups: TagGroups::NONE,
                    },
                ),
                (
                    Cond::MemberStrEq {
                        member: "RIFFStreamType",
                        value: "vids",
                        negate: false,
                    },
                    Field {
                        index: 5,
                        sub: None,
                        name: "VideoFrameRate",
                        format: Some(Fmt::Rational64u),
                        count: 1,
                        mask: None,
                        condition: Some(Cond::MemberStrEq {
                            member: "RIFFStreamType",
                            value: "vids",
                            negate: false,
                        }),
                        raw_conv: None,
                        omitted: Omitted {
                            value_conv: false,
                            raw_conv: true,
                            condition: false,
                            hook: false,
                            subdirectory: false,
                            print_conv: false,
                        },
                        value_conv: None,
                        print_conv: PrintConv::Expr(ExprId::IntVal10000510006E64E7),
                        subdir: None,
                        hook: &[],
                        groups: TagGroups::NONE,
                    },
                ),
                (
                    Cond::Always,
                    Field {
                        index: 5,
                        sub: None,
                        name: "StreamSampleRate",
                        format: Some(Fmt::Rational64u),
                        count: 1,
                        mask: None,
                        condition: None,
                        raw_conv: None,
                        omitted: Omitted::NONE,
                        value_conv: Some(ExprId::Val1Val0EAB507),
                        print_conv: PrintConv::Expr(ExprId::IntVal10000510006E64E7),
                        subdir: None,
                        hook: &[],
                        groups: TagGroups::NONE,
                    },
                ),
            ],
        },
        VariantGroup {
            index: 8,
            sub: None,
            alternatives: &[
                (
                    Cond::MemberStrEq {
                        member: "RIFFStreamType",
                        value: "auds",
                        negate: false,
                    },
                    Field {
                        index: 8,
                        sub: None,
                        name: "AudioSampleCount",
                        format: None,
                        count: 1,
                        mask: None,
                        condition: Some(Cond::MemberStrEq {
                            member: "RIFFStreamType",
                            value: "auds",
                            negate: false,
                        }),
                        raw_conv: None,
                        omitted: Omitted::NONE,
                        value_conv: None,
                        print_conv: PrintConv::None,
                        subdir: None,
                        hook: &[],
                        groups: TagGroups::NONE,
                    },
                ),
                (
                    Cond::MemberStrEq {
                        member: "RIFFStreamType",
                        value: "vids",
                        negate: false,
                    },
                    Field {
                        index: 8,
                        sub: None,
                        name: "VideoFrameCount",
                        format: None,
                        count: 1,
                        mask: None,
                        condition: Some(Cond::MemberStrEq {
                            member: "RIFFStreamType",
                            value: "vids",
                            negate: false,
                        }),
                        raw_conv: None,
                        omitted: Omitted::NONE,
                        value_conv: None,
                        print_conv: PrintConv::None,
                        subdir: None,
                        hook: &[],
                        groups: TagGroups::NONE,
                    },
                ),
                (
                    Cond::Always,
                    Field {
                        index: 8,
                        sub: None,
                        name: "StreamSampleCount",
                        format: None,
                        count: 1,
                        mask: None,
                        condition: None,
                        raw_conv: None,
                        omitted: Omitted::NONE,
                        value_conv: None,
                        print_conv: PrintConv::None,
                        subdir: None,
                        hook: &[],
                        groups: TagGroups::NONE,
                    },
                ),
            ],
        },
    ],
};

/// `Image::ExifTool::RIFF::UserText` -- 6 fields,
/// 0 `_variants` groups (Step 23).
/// Generated from ExifTool's in-memory tag table. Do not edit by hand.
pub static RIFF_USERTEXT: BinaryTable = BinaryTable {
    module: "RIFF",
    table: "UserText",
    group0: "RIFF",
    group1: "RIFF",
    group2: "Location",
    first_entry: 0,
    default_format: Fmt::Int8u,
    offsets_sound_until: None,
    priority: None,
    gate_a: GateA { blocked_by: &[] },
    fields: &[
        Field {
            index: 28,
            sub: None,
            name: "GPSAltitude",
            format: Some(Fmt::Int32u),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: Some(ExprId::Val100C7AB9),
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 40,
            sub: None,
            name: "Accelerometer",
            format: Some(Fmt::Float),
            count: 3,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 56,
            sub: None,
            name: "GPSSpeed",
            format: Some(Fmt::Float),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 60,
            sub: None,
            name: "GPSLatitude",
            format: Some(Fmt::Float),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted {
                value_conv: true,
                raw_conv: false,
                condition: false,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            value_conv: None,
            print_conv: PrintConv::Expr(ExprId::ImageExifToolGPSToDMSSelfVal1N224F39),
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 64,
            sub: None,
            name: "GPSLongitude",
            format: Some(Fmt::Float),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted {
                value_conv: true,
                raw_conv: false,
                condition: false,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            value_conv: None,
            print_conv: PrintConv::Expr(ExprId::ImageExifToolGPSToDMSSelfVal1E4009F1),
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 68,
            sub: None,
            name: "GPSDateTime",
            format: Some(Fmt::Int32u),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: Some(ExprId::ConvertUnixTimeValDA256D),
            print_conv: PrintConv::Expr(ExprId::SelfConvertDateTimeVal7455B8),
            subdir: None,
            hook: &[],
            groups: TagGroups {
                g0: None,
                g1: None,
                g2: Some("Time"),
            },
        },
    ],
    variants: &[],
};

/// `Image::ExifTool::RIFF::VP8` -- 5 fields,
/// 0 `_variants` groups (Step 23).
/// Generated from ExifTool's in-memory tag table. Do not edit by hand.
pub static RIFF_VP8: BinaryTable = BinaryTable {
    module: "RIFF",
    table: "VP8",
    group0: "RIFF",
    group1: "RIFF",
    group2: "Image",
    first_entry: 0,
    default_format: Fmt::Int8u,
    offsets_sound_until: None,
    priority: None,
    gate_a: GateA { blocked_by: &[] },
    fields: &[
        Field {
            index: 0,
            sub: None,
            name: "VP8Version",
            format: None,
            count: 1,
            mask: Some(Mask {
                bits: 0xe,
                shift: 1,
            }),
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[
                (0, "0 (bicubic reconstruction, normal loop)"),
                (1, "1 (bilinear reconstruction, simple loop)"),
                (2, "2 (bilinear reconstruction, no loop)"),
                (3, "3 (no reconstruction, no loop)"),
            ]),
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 6,
            sub: None,
            name: "ImageWidth",
            format: Some(Fmt::Int16u),
            count: 1,
            mask: Some(Mask {
                bits: 0x3fff,
                shift: 0,
            }),
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 6,
            sub: Some(1),
            name: "HorizontalScale",
            format: Some(Fmt::Int16u),
            count: 1,
            mask: Some(Mask {
                bits: 0xc000,
                shift: 14,
            }),
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 8,
            sub: None,
            name: "ImageHeight",
            format: Some(Fmt::Int16u),
            count: 1,
            mask: Some(Mask {
                bits: 0x3fff,
                shift: 0,
            }),
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 8,
            sub: Some(1),
            name: "VerticalScale",
            format: Some(Fmt::Int16u),
            count: 1,
            mask: Some(Mask {
                bits: 0xc000,
                shift: 14,
            }),
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
    ],
    variants: &[],
};

/// `Image::ExifTool::RIFF::VP8L` -- 3 fields,
/// 0 `_variants` groups (Step 23).
/// Generated from ExifTool's in-memory tag table. Do not edit by hand.
pub static RIFF_VP8L: BinaryTable = BinaryTable {
    module: "RIFF",
    table: "VP8L",
    group0: "RIFF",
    group1: "RIFF",
    group2: "Image",
    first_entry: 0,
    default_format: Fmt::Int8u,
    offsets_sound_until: None,
    priority: None,
    gate_a: GateA { blocked_by: &[] },
    fields: &[
        Field {
            index: 1,
            sub: None,
            name: "ImageWidth",
            format: Some(Fmt::Int16u),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: true,
                condition: false,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            value_conv: Some(ExprId::Val0x3fff120ED1F),
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 2,
            sub: None,
            name: "ImageHeight",
            format: Some(Fmt::Int32u),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: Some(ExprId::Val60x3fff1C52B04),
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 4,
            sub: None,
            name: "AlphaIsUsed",
            format: None,
            count: 1,
            mask: Some(Mask {
                bits: 0x10,
                shift: 4,
            }),
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[(0, "No"), (1, "Yes")]),
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
    ],
    variants: &[],
};

/// `Image::ExifTool::RIFF::VP8X` -- 3 fields,
/// 0 `_variants` groups (Step 23).
/// Generated from ExifTool's in-memory tag table. Do not edit by hand.
pub static RIFF_VP8X: BinaryTable = BinaryTable {
    module: "RIFF",
    table: "VP8X",
    group0: "RIFF",
    group1: "RIFF",
    group2: "Image",
    first_entry: 0,
    default_format: Fmt::Int8u,
    offsets_sound_until: None,
    priority: None,
    gate_a: GateA { blocked_by: &[] },
    fields: &[
        Field {
            index: 0,
            sub: None,
            name: "WebP_Flags",
            format: Some(Fmt::Int32u),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::Bitmask {
                exact: &[],
                bits: &[
                    (1, "Animation"),
                    (2, "XMP"),
                    (3, "EXIF"),
                    (4, "Alpha"),
                    (5, "ICC Profile"),
                ],
            },
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 4,
            sub: None,
            name: "ImageWidth",
            format: Some(Fmt::Int32u),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: Some(ExprId::Val0xffffff1B4CCCB),
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 6,
            sub: None,
            name: "ImageHeight",
            format: Some(Fmt::Int32u),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: Some(ExprId::Val818B8D53),
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
    ],
    variants: &[],
};
