//! ExifTool `ZIP` ProcessBinaryData tables, generated from ExifTool
//! 13.59's own Perl hashes -- one file per module; `mod.rs` beside this
//! file is the hub that declares and re-exports it.
//!
//! DO NOT EDIT. Regenerate with `just regen-tables` (see `mod.rs`).

#![allow(clippy::unreadable_literal, clippy::too_many_lines, unused_parens)]

// Everything a table literal names -- the schema types, `ExprId`, the
// `cond`/`subdir`/`ifd_schema` imports -- is in scope in the hub, and a glob
// import of the parent module brings its private imports along (RFC 1560).
#[allow(unused_imports)]
use super::*;

/// `Image::ExifTool::ZIP::GZIP` -- 7 fields,
/// 0 `_variants` groups (Step 23).
/// Generated from ExifTool's in-memory tag table. Do not edit by hand.
pub static ZIP_GZIP: BinaryTable = BinaryTable {
    module: "ZIP",
    table: "GZIP",
    group0: "ZIP",
    group1: "ZIP",
    group2: "Other",
    first_entry: 0,
    default_format: Fmt::Int8u,
    offsets_sound_until: None,
    priority: None,
    gate_a: GateA { blocked_by: &[] },
    fields: &[
        Field {
            index: 2,
            sub: None,
            name: "Compression",
            format: None,
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[(8, "Deflated")]),
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 3,
            sub: None,
            name: "Flags",
            format: None,
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::Bitmask {
                exact: &[],
                bits: &[
                    (0, "Text"),
                    (1, "CRC16"),
                    (2, "ExtraFields"),
                    (3, "FileName"),
                    (4, "Comment"),
                ],
            },
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 4,
            sub: None,
            name: "ModifyDate",
            format: Some(Fmt::Int32u),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: Some(ExprId::ConvertUnixTimeVal15C09AC),
            print_conv: PrintConv::Expr(ExprId::SelfConvertDateTimeVal7455B8),
            subdir: None,
            hook: &[],
            groups: TagGroups {
                g0: None,
                g1: None,
                g2: Some("Time"),
            },
        },
        Field {
            index: 8,
            sub: None,
            name: "ExtraFlags",
            format: None,
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[
                (0, "(none)"),
                (2, "Maximum Compression"),
                (4, "Fastest Algorithm"),
            ]),
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 9,
            sub: None,
            name: "OperatingSystem",
            format: None,
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[
                (0, "FAT filesystem (MS-DOS, OS/2, NT/Win32)"),
                (1, "Amiga"),
                (2, "VMS (or OpenVMS)"),
                (3, "Unix"),
                (4, "VM/CMS"),
                (5, "Atari TOS"),
                (6, "HPFS filesystem (OS/2, NT)"),
                (7, "Macintosh"),
                (8, "Z-System"),
                (9, "CP/M"),
                (10, "TOPS-20"),
                (11, "NTFS filesystem (NT)"),
                (12, "QDOS"),
                (13, "Acorn RISCOS"),
                (255, "unknown"),
            ]),
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 10,
            sub: None,
            name: "ArchivedFileName",
            format: None,
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 11,
            sub: None,
            name: "Comment",
            format: None,
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
    ],
    variants: &[],
};

/// `Image::ExifTool::ZIP::Main` -- 8 fields,
/// 0 `_variants` groups (Step 23).
/// Generated from ExifTool's in-memory tag table. Do not edit by hand.
pub static ZIP_MAIN: BinaryTable = BinaryTable {
    module: "ZIP",
    table: "Main",
    group0: "ZIP",
    group1: "ZIP",
    group2: "Other",
    first_entry: 0,
    default_format: Fmt::Int16u,
    offsets_sound_until: None,
    priority: None,
    gate_a: GateA {
        blocked_by: &[("tag_fmt_unsupported", 1)],
    },
    fields: &[
        Field {
            index: 2,
            sub: None,
            name: "ZipRequiredVersion",
            format: None,
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 3,
            sub: None,
            name: "ZipBitFlag",
            format: None,
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::Expr(ExprId::ValSprintf0x4xValValB81079),
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 4,
            sub: None,
            name: "ZipCompression",
            format: None,
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[
                (0, "None"),
                (1, "Shrunk"),
                (2, "Reduced with compression factor 1"),
                (3, "Reduced with compression factor 2"),
                (4, "Reduced with compression factor 3"),
                (5, "Reduced with compression factor 4"),
                (6, "Imploded"),
                (7, "Tokenized"),
                (8, "Deflated"),
                (9, "Enhanced Deflate using Deflate64(tm)"),
                (10, "Imploded (old IBM TERSE)"),
                (12, "BZIP2"),
                (14, "LZMA (EFS)"),
                (18, "IBM TERSE (new)"),
                (19, "IBM LZ77 z Architecture (PFS)"),
                (96, "JPEG recompressed"),
                (97, "WavPack compressed"),
                (98, "PPMd version I, Rev 1"),
            ]),
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 5,
            sub: None,
            name: "ZipModifyDate",
            format: Some(Fmt::Int32u),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted {
                value_conv: true,
                raw_conv: false,
                condition: false,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups {
                g0: None,
                g1: None,
                g2: Some("Time"),
            },
        },
        Field {
            index: 7,
            sub: None,
            name: "ZipCRC",
            format: Some(Fmt::Int32u),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::Expr(ExprId::Sprintf0x8xValF8EB3E),
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 9,
            sub: None,
            name: "ZipCompressedSize",
            format: Some(Fmt::Int32u),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 11,
            sub: None,
            name: "ZipUncompressedSize",
            format: Some(Fmt::Int32u),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 13,
            sub: None,
            name: "ZipFileNameLength",
            format: None,
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: true,
                condition: false,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
    ],
    variants: &[],
};

/// `Image::ExifTool::ZIP::RAR` -- 6 fields,
/// 0 `_variants` groups (Step 23).
/// Generated from ExifTool's in-memory tag table. Do not edit by hand.
pub static ZIP_RAR: BinaryTable = BinaryTable {
    module: "ZIP",
    table: "RAR",
    group0: "ZIP",
    group1: "ZIP",
    group2: "Other",
    first_entry: 0,
    default_format: Fmt::Int8u,
    offsets_sound_until: None,
    priority: None,
    gate_a: GateA {
        blocked_by: &[("tag_fmt_unsupported", 1)],
    },
    fields: &[
        Field {
            index: 0,
            sub: None,
            name: "CompressedSize",
            format: Some(Fmt::Int32u),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 4,
            sub: None,
            name: "UncompressedSize",
            format: Some(Fmt::Int32u),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 8,
            sub: None,
            name: "OperatingSystem",
            format: None,
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[
                (0, "MS-DOS"),
                (1, "OS/2"),
                (2, "Win32"),
                (3, "Unix"),
            ]),
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 13,
            sub: None,
            name: "ModifyDate",
            format: Some(Fmt::Int32u),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted {
                value_conv: true,
                raw_conv: false,
                condition: false,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups {
                g0: None,
                g1: None,
                g2: Some("Time"),
            },
        },
        Field {
            index: 18,
            sub: None,
            name: "PackingMethod",
            format: None,
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted::NONE,
            value_conv: None,
            print_conv: PrintConv::PartialEnumInt {
                exact: &[
                    (48, "Stored"),
                    (49, "Fastest"),
                    (50, "Fast"),
                    (51, "Normal"),
                    (52, "Good Compression"),
                    (53, "Best Compression"),
                ],
                other: None,
                print_hex: true,
            },
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
        Field {
            index: 19,
            sub: None,
            name: "FileNameLength",
            format: Some(Fmt::Int16u),
            count: 1,
            mask: None,
            condition: None,
            raw_conv: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: true,
                condition: false,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
            hook: &[],
            groups: TagGroups::NONE,
        },
    ],
    variants: &[],
};
