//! Generated serial-directory facts; no reader or route is activated by this file.
use super::*;
pub static SERIAL_CANON_AFINFO: SerialTable = SerialTable {
    module: "Canon",
    table: "AFInfo",
    group0: "MakerNotes",
    group1: "Canon",
    group2: "Camera",
    default_format: Fmt::Int16u,
    processor: SerialProcessorFacts {
        name: "Image::ExifTool::Canon::ProcessSerialData",
        source_file: "Image/ExifTool/Canon.pm",
        source_sha256: "d22b110e7b2e1af2d6e59bb97db97a04ffc2bfd1ba7d078d380ae60fbc70bbba",
        source_body_sha256: "ab5cb31e06a991a02f5569f1c008303c0505d28caf7ae2ec044aeede9c9f999c",
    },
    gate_a: GateA { blocked_by: &[] },
    entries: &[
        SerialEntry {
            serial_index: 0,
            alternatives: &[SerialTag {
                name: "NumAFPoints",
                format: SerialFormat {
                    format: Fmt::Int16u,
                    count: SerialCount::Fixed { value: 1 },
                },
                condition: None,
                flags: IfdFlags::NONE,
                raw_conv: None,
                omitted: Omitted::NONE,
                value_conv: None,
                print_conv: SerialPrintConv::None,
                groups: TagGroups::NONE,
            }],
        },
        SerialEntry {
            serial_index: 1,
            alternatives: &[SerialTag {
                name: "ValidAFPoints",
                format: SerialFormat {
                    format: Fmt::Int16u,
                    count: SerialCount::Fixed { value: 1 },
                },
                condition: None,
                flags: IfdFlags::NONE,
                raw_conv: None,
                omitted: Omitted::NONE,
                value_conv: None,
                print_conv: SerialPrintConv::None,
                groups: TagGroups::NONE,
            }],
        },
        SerialEntry {
            serial_index: 2,
            alternatives: &[SerialTag {
                name: "CanonImageWidth",
                format: SerialFormat {
                    format: Fmt::Int16u,
                    count: SerialCount::Fixed { value: 1 },
                },
                condition: None,
                flags: IfdFlags::NONE,
                raw_conv: None,
                omitted: Omitted::NONE,
                value_conv: None,
                print_conv: SerialPrintConv::None,
                groups: TagGroups {
                    g0: None,
                    g1: None,
                    g2: Some("Image"),
                },
            }],
        },
        SerialEntry {
            serial_index: 3,
            alternatives: &[SerialTag {
                name: "CanonImageHeight",
                format: SerialFormat {
                    format: Fmt::Int16u,
                    count: SerialCount::Fixed { value: 1 },
                },
                condition: None,
                flags: IfdFlags::NONE,
                raw_conv: None,
                omitted: Omitted::NONE,
                value_conv: None,
                print_conv: SerialPrintConv::None,
                groups: TagGroups {
                    g0: None,
                    g1: None,
                    g2: Some("Image"),
                },
            }],
        },
        SerialEntry {
            serial_index: 4,
            alternatives: &[SerialTag {
                name: "AFImageWidth",
                format: SerialFormat {
                    format: Fmt::Int16u,
                    count: SerialCount::Fixed { value: 1 },
                },
                condition: None,
                flags: IfdFlags::NONE,
                raw_conv: None,
                omitted: Omitted::NONE,
                value_conv: None,
                print_conv: SerialPrintConv::None,
                groups: TagGroups::NONE,
            }],
        },
        SerialEntry {
            serial_index: 5,
            alternatives: &[SerialTag {
                name: "AFImageHeight",
                format: SerialFormat {
                    format: Fmt::Int16u,
                    count: SerialCount::Fixed { value: 1 },
                },
                condition: None,
                flags: IfdFlags::NONE,
                raw_conv: None,
                omitted: Omitted::NONE,
                value_conv: None,
                print_conv: SerialPrintConv::None,
                groups: TagGroups::NONE,
            }],
        },
        SerialEntry {
            serial_index: 6,
            alternatives: &[SerialTag {
                name: "AFAreaWidth",
                format: SerialFormat {
                    format: Fmt::Int16u,
                    count: SerialCount::Fixed { value: 1 },
                },
                condition: None,
                flags: IfdFlags::NONE,
                raw_conv: None,
                omitted: Omitted::NONE,
                value_conv: None,
                print_conv: SerialPrintConv::None,
                groups: TagGroups::NONE,
            }],
        },
        SerialEntry {
            serial_index: 7,
            alternatives: &[SerialTag {
                name: "AFAreaHeight",
                format: SerialFormat {
                    format: Fmt::Int16u,
                    count: SerialCount::Fixed { value: 1 },
                },
                condition: None,
                flags: IfdFlags::NONE,
                raw_conv: None,
                omitted: Omitted::NONE,
                value_conv: None,
                print_conv: SerialPrintConv::None,
                groups: TagGroups::NONE,
            }],
        },
        SerialEntry {
            serial_index: 8,
            alternatives: &[SerialTag {
                name: "AFAreaXPositions",
                format: SerialFormat {
                    format: Fmt::Int16s,
                    count: SerialCount::PriorRaw { serial_index: 0 },
                },
                condition: None,
                flags: IfdFlags::NONE,
                raw_conv: None,
                omitted: Omitted::NONE,
                value_conv: None,
                print_conv: SerialPrintConv::None,
                groups: TagGroups::NONE,
            }],
        },
        SerialEntry {
            serial_index: 9,
            alternatives: &[SerialTag {
                name: "AFAreaYPositions",
                format: SerialFormat {
                    format: Fmt::Int16s,
                    count: SerialCount::PriorRaw { serial_index: 0 },
                },
                condition: None,
                flags: IfdFlags::NONE,
                raw_conv: None,
                omitted: Omitted::NONE,
                value_conv: None,
                print_conv: SerialPrintConv::None,
                groups: TagGroups::NONE,
            }],
        },
        SerialEntry {
            serial_index: 10,
            alternatives: &[SerialTag {
                name: "AFPointsInFocus",
                format: SerialFormat {
                    format: Fmt::Int16s,
                    count: SerialCount::FloorDivPriorRaw {
                        serial_index: 0,
                        add: 15,
                        divisor: 16,
                        trailing_add: 0,
                    },
                },
                condition: None,
                flags: IfdFlags::NONE,
                raw_conv: None,
                omitted: Omitted::NONE,
                value_conv: None,
                print_conv: SerialPrintConv::DecodeBitsWords { bits_per_word: 16 },
                groups: TagGroups::NONE,
            }],
        },
        SerialEntry {
            serial_index: 11,
            alternatives: &[
                SerialTag {
                    name: "PrimaryAFPoint",
                    format: SerialFormat {
                        format: Fmt::Int16u,
                        count: SerialCount::Fixed { value: 1 },
                    },
                    condition: Some(SerialCondition {
                        cond: Cond::And(
                            &Cond::MemberRegex {
                                member: "Model",
                                pattern: "EOS",
                                ignore_case: false,
                                negate: true,
                            },
                            &Cond::Or(
                                &Cond::MemberTruthy {
                                    member: "AFInfoCount",
                                    negate: true,
                                },
                                &Cond::MemberCmp {
                                    member: "AFInfoCount",
                                    op: CmpOp::Ne,
                                    value: 36,
                                },
                            ),
                        ),
                        missing_member: SerialMissingMember::EmptyStringForStringOps,
                    }),
                    flags: IfdFlags::NONE,
                    raw_conv: None,
                    omitted: Omitted::NONE,
                    value_conv: None,
                    print_conv: SerialPrintConv::None,
                    groups: TagGroups::NONE,
                },
                SerialTag {
                    name: "Canon_AFInfo_0x000b",
                    format: SerialFormat {
                        format: Fmt::Int16u,
                        count: SerialCount::Fixed { value: 8 },
                    },
                    condition: Some(SerialCondition {
                        cond: Cond::MemberRegex {
                            member: "Model",
                            pattern: "EOS",
                            ignore_case: false,
                            negate: true,
                        },
                        missing_member: SerialMissingMember::EmptyStringForStringOps,
                    }),
                    flags: IfdFlags {
                        unknown: true,
                        binary: false,
                        list: false,
                        protected: false,
                        avoid: false,
                        priority: None,
                    },
                    raw_conv: None,
                    omitted: Omitted::NONE,
                    value_conv: None,
                    print_conv: SerialPrintConv::None,
                    groups: TagGroups::NONE,
                },
            ],
        },
        SerialEntry {
            serial_index: 12,
            alternatives: &[SerialTag {
                name: "PrimaryAFPoint",
                format: SerialFormat {
                    format: Fmt::Int16u,
                    count: SerialCount::Fixed { value: 1 },
                },
                condition: None,
                flags: IfdFlags::NONE,
                raw_conv: None,
                omitted: Omitted::NONE,
                value_conv: None,
                print_conv: SerialPrintConv::None,
                groups: TagGroups::NONE,
            }],
        },
    ],
};
pub static SERIAL_CANON_AFINFO2: SerialTable = SerialTable {
    module: "Canon",
    table: "AFInfo2",
    group0: "MakerNotes",
    group1: "Canon",
    group2: "Camera",
    default_format: Fmt::Int16u,
    processor: SerialProcessorFacts {
        name: "Image::ExifTool::Canon::ProcessSerialData",
        source_file: "Image/ExifTool/Canon.pm",
        source_sha256: "d22b110e7b2e1af2d6e59bb97db97a04ffc2bfd1ba7d078d380ae60fbc70bbba",
        source_body_sha256: "ab5cb31e06a991a02f5569f1c008303c0505d28caf7ae2ec044aeede9c9f999c",
    },
    gate_a: GateA { blocked_by: &[] },
    entries: &[
        SerialEntry {
            serial_index: 0,
            alternatives: &[SerialTag {
                name: "AFInfoSize",
                format: SerialFormat {
                    format: Fmt::Int16u,
                    count: SerialCount::Fixed { value: 1 },
                },
                condition: None,
                flags: IfdFlags {
                    unknown: true,
                    binary: false,
                    list: false,
                    protected: false,
                    avoid: false,
                    priority: None,
                },
                raw_conv: None,
                omitted: Omitted::NONE,
                value_conv: None,
                print_conv: SerialPrintConv::None,
                groups: TagGroups::NONE,
            }],
        },
        SerialEntry {
            serial_index: 1,
            alternatives: &[SerialTag {
                name: "AFAreaMode",
                format: SerialFormat {
                    format: Fmt::Int16u,
                    count: SerialCount::Fixed { value: 1 },
                },
                condition: None,
                flags: IfdFlags::NONE,
                raw_conv: None,
                omitted: Omitted::NONE,
                value_conv: None,
                print_conv: SerialPrintConv::Shared(PrintConv::IntEnum(&[
                    (0, "Off (Manual Focus)"),
                    (1, "AF Point Expansion (surround)"),
                    (2, "Single-point AF"),
                    (4, "Auto"),
                    (5, "Face Detect AF"),
                    (6, "Face + Tracking"),
                    (7, "Zone AF"),
                    (8, "AF Point Expansion (4 point)"),
                    (9, "Spot AF"),
                    (10, "AF Point Expansion (8 point)"),
                    (11, "Flexizone Multi (49 point)"),
                    (12, "Flexizone Multi (9 point)"),
                    (13, "Flexizone Single"),
                    (14, "Large Zone AF"),
                    (16, "Large Zone AF (vertical)"),
                    (17, "Large Zone AF (horizontal)"),
                    (19, "Flexible Zone AF 1"),
                    (20, "Flexible Zone AF 2"),
                    (21, "Flexible Zone AF 3"),
                    (22, "Whole Area AF"),
                ])),
                groups: TagGroups::NONE,
            }],
        },
        SerialEntry {
            serial_index: 2,
            alternatives: &[SerialTag {
                name: "NumAFPoints",
                format: SerialFormat {
                    format: Fmt::Int16u,
                    count: SerialCount::Fixed { value: 1 },
                },
                condition: None,
                flags: IfdFlags::NONE,
                raw_conv: Some(RawConvEffect::SetMember {
                    member: "NumAFPoints",
                }),
                omitted: Omitted::NONE,
                value_conv: None,
                print_conv: SerialPrintConv::None,
                groups: TagGroups::NONE,
            }],
        },
        SerialEntry {
            serial_index: 3,
            alternatives: &[SerialTag {
                name: "ValidAFPoints",
                format: SerialFormat {
                    format: Fmt::Int16u,
                    count: SerialCount::Fixed { value: 1 },
                },
                condition: None,
                flags: IfdFlags::NONE,
                raw_conv: None,
                omitted: Omitted::NONE,
                value_conv: None,
                print_conv: SerialPrintConv::None,
                groups: TagGroups::NONE,
            }],
        },
        SerialEntry {
            serial_index: 4,
            alternatives: &[SerialTag {
                name: "CanonImageWidth",
                format: SerialFormat {
                    format: Fmt::Int16u,
                    count: SerialCount::Fixed { value: 1 },
                },
                condition: None,
                flags: IfdFlags::NONE,
                raw_conv: None,
                omitted: Omitted::NONE,
                value_conv: None,
                print_conv: SerialPrintConv::None,
                groups: TagGroups {
                    g0: None,
                    g1: None,
                    g2: Some("Image"),
                },
            }],
        },
        SerialEntry {
            serial_index: 5,
            alternatives: &[SerialTag {
                name: "CanonImageHeight",
                format: SerialFormat {
                    format: Fmt::Int16u,
                    count: SerialCount::Fixed { value: 1 },
                },
                condition: None,
                flags: IfdFlags::NONE,
                raw_conv: None,
                omitted: Omitted::NONE,
                value_conv: None,
                print_conv: SerialPrintConv::None,
                groups: TagGroups {
                    g0: None,
                    g1: None,
                    g2: Some("Image"),
                },
            }],
        },
        SerialEntry {
            serial_index: 6,
            alternatives: &[SerialTag {
                name: "AFImageWidth",
                format: SerialFormat {
                    format: Fmt::Int16u,
                    count: SerialCount::Fixed { value: 1 },
                },
                condition: None,
                flags: IfdFlags::NONE,
                raw_conv: None,
                omitted: Omitted::NONE,
                value_conv: None,
                print_conv: SerialPrintConv::None,
                groups: TagGroups::NONE,
            }],
        },
        SerialEntry {
            serial_index: 7,
            alternatives: &[SerialTag {
                name: "AFImageHeight",
                format: SerialFormat {
                    format: Fmt::Int16u,
                    count: SerialCount::Fixed { value: 1 },
                },
                condition: None,
                flags: IfdFlags::NONE,
                raw_conv: None,
                omitted: Omitted::NONE,
                value_conv: None,
                print_conv: SerialPrintConv::None,
                groups: TagGroups::NONE,
            }],
        },
        SerialEntry {
            serial_index: 8,
            alternatives: &[SerialTag {
                name: "AFAreaWidths",
                format: SerialFormat {
                    format: Fmt::Int16s,
                    count: SerialCount::PriorRaw { serial_index: 2 },
                },
                condition: None,
                flags: IfdFlags::NONE,
                raw_conv: None,
                omitted: Omitted::NONE,
                value_conv: None,
                print_conv: SerialPrintConv::None,
                groups: TagGroups::NONE,
            }],
        },
        SerialEntry {
            serial_index: 9,
            alternatives: &[SerialTag {
                name: "AFAreaHeights",
                format: SerialFormat {
                    format: Fmt::Int16s,
                    count: SerialCount::PriorRaw { serial_index: 2 },
                },
                condition: None,
                flags: IfdFlags::NONE,
                raw_conv: None,
                omitted: Omitted::NONE,
                value_conv: None,
                print_conv: SerialPrintConv::None,
                groups: TagGroups::NONE,
            }],
        },
        SerialEntry {
            serial_index: 10,
            alternatives: &[SerialTag {
                name: "AFAreaXPositions",
                format: SerialFormat {
                    format: Fmt::Int16s,
                    count: SerialCount::PriorRaw { serial_index: 2 },
                },
                condition: None,
                flags: IfdFlags::NONE,
                raw_conv: None,
                omitted: Omitted::NONE,
                value_conv: None,
                print_conv: SerialPrintConv::None,
                groups: TagGroups::NONE,
            }],
        },
        SerialEntry {
            serial_index: 11,
            alternatives: &[SerialTag {
                name: "AFAreaYPositions",
                format: SerialFormat {
                    format: Fmt::Int16s,
                    count: SerialCount::PriorRaw { serial_index: 2 },
                },
                condition: None,
                flags: IfdFlags::NONE,
                raw_conv: None,
                omitted: Omitted::NONE,
                value_conv: None,
                print_conv: SerialPrintConv::None,
                groups: TagGroups::NONE,
            }],
        },
        SerialEntry {
            serial_index: 12,
            alternatives: &[SerialTag {
                name: "AFPointsInFocus",
                format: SerialFormat {
                    format: Fmt::Int16s,
                    count: SerialCount::FloorDivPriorRaw {
                        serial_index: 2,
                        add: 15,
                        divisor: 16,
                        trailing_add: 0,
                    },
                },
                condition: None,
                flags: IfdFlags::NONE,
                raw_conv: None,
                omitted: Omitted::NONE,
                value_conv: None,
                print_conv: SerialPrintConv::DecodeBitsWords { bits_per_word: 16 },
                groups: TagGroups::NONE,
            }],
        },
        SerialEntry {
            serial_index: 13,
            alternatives: &[
                SerialTag {
                    name: "AFPointsSelected",
                    format: SerialFormat {
                        format: Fmt::Int16s,
                        count: SerialCount::FloorDivPriorRaw {
                            serial_index: 2,
                            add: 15,
                            divisor: 16,
                            trailing_add: 0,
                        },
                    },
                    condition: Some(SerialCondition {
                        cond: Cond::MemberRegex {
                            member: "Model",
                            pattern: "EOS",
                            ignore_case: false,
                            negate: false,
                        },
                        missing_member: SerialMissingMember::EmptyStringForStringOps,
                    }),
                    flags: IfdFlags::NONE,
                    raw_conv: None,
                    omitted: Omitted::NONE,
                    value_conv: None,
                    print_conv: SerialPrintConv::DecodeBitsWords { bits_per_word: 16 },
                    groups: TagGroups::NONE,
                },
                SerialTag {
                    name: "Canon_AFInfo2_0x000d",
                    format: SerialFormat {
                        format: Fmt::Int16s,
                        count: SerialCount::FloorDivPriorRaw {
                            serial_index: 2,
                            add: 15,
                            divisor: 16,
                            trailing_add: 1,
                        },
                    },
                    condition: None,
                    flags: IfdFlags {
                        unknown: true,
                        binary: false,
                        list: false,
                        protected: false,
                        avoid: false,
                        priority: None,
                    },
                    raw_conv: None,
                    omitted: Omitted::NONE,
                    value_conv: None,
                    print_conv: SerialPrintConv::None,
                    groups: TagGroups::NONE,
                },
            ],
        },
        SerialEntry {
            serial_index: 14,
            alternatives: &[SerialTag {
                name: "PrimaryAFPoint",
                format: SerialFormat {
                    format: Fmt::Int16u,
                    count: SerialCount::Fixed { value: 1 },
                },
                condition: Some(SerialCondition {
                    cond: Cond::And(
                        &Cond::MemberRegex {
                            member: "Model",
                            pattern: "EOS",
                            ignore_case: false,
                            negate: true,
                        },
                        &Cond::MemberTruthy {
                            member: "AFInfo3",
                            negate: true,
                        },
                    ),
                    missing_member: SerialMissingMember::EmptyStringForStringOps,
                }),
                flags: IfdFlags::NONE,
                raw_conv: None,
                omitted: Omitted::NONE,
                value_conv: None,
                print_conv: SerialPrintConv::None,
                groups: TagGroups::NONE,
            }],
        },
    ],
};
pub static SERIAL_REAL_AUDIOV3: SerialTable = SerialTable {
    module: "Real",
    table: "AudioV3",
    group0: "Real",
    group1: "Real-RA3",
    group2: "Audio",
    default_format: Fmt::Int8u,
    processor: SerialProcessorFacts {
        name: "Image::ExifTool::Canon::ProcessSerialData",
        source_file: "Image/ExifTool/Canon.pm",
        source_sha256: "d22b110e7b2e1af2d6e59bb97db97a04ffc2bfd1ba7d078d380ae60fbc70bbba",
        source_body_sha256: "ab5cb31e06a991a02f5569f1c008303c0505d28caf7ae2ec044aeede9c9f999c",
    },
    gate_a: GateA { blocked_by: &[] },
    entries: &[
        SerialEntry {
            serial_index: 0,
            alternatives: &[SerialTag {
                name: "Channels",
                format: SerialFormat {
                    format: Fmt::Int16u,
                    count: SerialCount::Fixed { value: 1 },
                },
                condition: None,
                flags: IfdFlags::NONE,
                raw_conv: None,
                omitted: Omitted::NONE,
                value_conv: None,
                print_conv: SerialPrintConv::None,
                groups: TagGroups::NONE,
            }],
        },
        SerialEntry {
            serial_index: 1,
            alternatives: &[SerialTag {
                name: "Unknown",
                format: SerialFormat {
                    format: Fmt::Int16u,
                    count: SerialCount::Fixed { value: 3 },
                },
                condition: None,
                flags: IfdFlags {
                    unknown: true,
                    binary: false,
                    list: false,
                    protected: false,
                    avoid: false,
                    priority: None,
                },
                raw_conv: None,
                omitted: Omitted::NONE,
                value_conv: None,
                print_conv: SerialPrintConv::None,
                groups: TagGroups::NONE,
            }],
        },
        SerialEntry {
            serial_index: 2,
            alternatives: &[SerialTag {
                name: "BytesPerMinute",
                format: SerialFormat {
                    format: Fmt::Int16u,
                    count: SerialCount::Fixed { value: 1 },
                },
                condition: None,
                flags: IfdFlags::NONE,
                raw_conv: None,
                omitted: Omitted::NONE,
                value_conv: None,
                print_conv: SerialPrintConv::None,
                groups: TagGroups::NONE,
            }],
        },
        SerialEntry {
            serial_index: 3,
            alternatives: &[SerialTag {
                name: "AudioBytes",
                format: SerialFormat {
                    format: Fmt::Int32u,
                    count: SerialCount::Fixed { value: 1 },
                },
                condition: None,
                flags: IfdFlags::NONE,
                raw_conv: None,
                omitted: Omitted::NONE,
                value_conv: None,
                print_conv: SerialPrintConv::None,
                groups: TagGroups::NONE,
            }],
        },
        SerialEntry {
            serial_index: 4,
            alternatives: &[SerialTag {
                name: "TitleLen",
                format: SerialFormat {
                    format: Fmt::Int8u,
                    count: SerialCount::Fixed { value: 1 },
                },
                condition: None,
                flags: IfdFlags {
                    unknown: true,
                    binary: false,
                    list: false,
                    protected: false,
                    avoid: false,
                    priority: None,
                },
                raw_conv: None,
                omitted: Omitted::NONE,
                value_conv: None,
                print_conv: SerialPrintConv::None,
                groups: TagGroups::NONE,
            }],
        },
        SerialEntry {
            serial_index: 5,
            alternatives: &[SerialTag {
                name: "Title",
                format: SerialFormat {
                    format: Fmt::Str(1),
                    count: SerialCount::PriorRaw { serial_index: 4 },
                },
                condition: None,
                flags: IfdFlags::NONE,
                raw_conv: None,
                omitted: Omitted::NONE,
                value_conv: None,
                print_conv: SerialPrintConv::None,
                groups: TagGroups::NONE,
            }],
        },
        SerialEntry {
            serial_index: 6,
            alternatives: &[SerialTag {
                name: "ArtistLen",
                format: SerialFormat {
                    format: Fmt::Int8u,
                    count: SerialCount::Fixed { value: 1 },
                },
                condition: None,
                flags: IfdFlags {
                    unknown: true,
                    binary: false,
                    list: false,
                    protected: false,
                    avoid: false,
                    priority: None,
                },
                raw_conv: None,
                omitted: Omitted::NONE,
                value_conv: None,
                print_conv: SerialPrintConv::None,
                groups: TagGroups::NONE,
            }],
        },
        SerialEntry {
            serial_index: 7,
            alternatives: &[SerialTag {
                name: "Artist",
                format: SerialFormat {
                    format: Fmt::Str(1),
                    count: SerialCount::PriorRaw { serial_index: 6 },
                },
                condition: None,
                flags: IfdFlags::NONE,
                raw_conv: None,
                omitted: Omitted::NONE,
                value_conv: None,
                print_conv: SerialPrintConv::None,
                groups: TagGroups {
                    g0: None,
                    g1: None,
                    g2: Some("Author"),
                },
            }],
        },
        SerialEntry {
            serial_index: 8,
            alternatives: &[SerialTag {
                name: "CopyrightLen",
                format: SerialFormat {
                    format: Fmt::Int8u,
                    count: SerialCount::Fixed { value: 1 },
                },
                condition: None,
                flags: IfdFlags {
                    unknown: true,
                    binary: false,
                    list: false,
                    protected: false,
                    avoid: false,
                    priority: None,
                },
                raw_conv: None,
                omitted: Omitted::NONE,
                value_conv: None,
                print_conv: SerialPrintConv::None,
                groups: TagGroups::NONE,
            }],
        },
        SerialEntry {
            serial_index: 9,
            alternatives: &[SerialTag {
                name: "Copyright",
                format: SerialFormat {
                    format: Fmt::Str(1),
                    count: SerialCount::PriorRaw { serial_index: 8 },
                },
                condition: None,
                flags: IfdFlags::NONE,
                raw_conv: None,
                omitted: Omitted::NONE,
                value_conv: None,
                print_conv: SerialPrintConv::None,
                groups: TagGroups {
                    g0: None,
                    g1: None,
                    g2: Some("Author"),
                },
            }],
        },
        SerialEntry {
            serial_index: 10,
            alternatives: &[SerialTag {
                name: "CommentLen",
                format: SerialFormat {
                    format: Fmt::Int8u,
                    count: SerialCount::Fixed { value: 1 },
                },
                condition: None,
                flags: IfdFlags {
                    unknown: true,
                    binary: false,
                    list: false,
                    protected: false,
                    avoid: false,
                    priority: None,
                },
                raw_conv: None,
                omitted: Omitted::NONE,
                value_conv: None,
                print_conv: SerialPrintConv::None,
                groups: TagGroups::NONE,
            }],
        },
        SerialEntry {
            serial_index: 11,
            alternatives: &[SerialTag {
                name: "Comment",
                format: SerialFormat {
                    format: Fmt::Str(1),
                    count: SerialCount::PriorRaw { serial_index: 10 },
                },
                condition: None,
                flags: IfdFlags::NONE,
                raw_conv: None,
                omitted: Omitted::NONE,
                value_conv: None,
                print_conv: SerialPrintConv::None,
                groups: TagGroups::NONE,
            }],
        },
    ],
};
pub static SERIAL_REAL_AUDIOV4: SerialTable = SerialTable {
    module: "Real",
    table: "AudioV4",
    group0: "Real",
    group1: "Real-RA4",
    group2: "Audio",
    default_format: Fmt::Int16u,
    processor: SerialProcessorFacts {
        name: "Image::ExifTool::Canon::ProcessSerialData",
        source_file: "Image/ExifTool/Canon.pm",
        source_sha256: "d22b110e7b2e1af2d6e59bb97db97a04ffc2bfd1ba7d078d380ae60fbc70bbba",
        source_body_sha256: "ab5cb31e06a991a02f5569f1c008303c0505d28caf7ae2ec044aeede9c9f999c",
    },
    gate_a: GateA { blocked_by: &[] },
    entries: &[
        SerialEntry {
            serial_index: 0,
            alternatives: &[SerialTag {
                name: "FourCC1",
                format: SerialFormat {
                    format: Fmt::Undef(1),
                    count: SerialCount::Fixed { value: 4 },
                },
                condition: None,
                flags: IfdFlags {
                    unknown: true,
                    binary: false,
                    list: false,
                    protected: false,
                    avoid: false,
                    priority: None,
                },
                raw_conv: None,
                omitted: Omitted::NONE,
                value_conv: None,
                print_conv: SerialPrintConv::None,
                groups: TagGroups::NONE,
            }],
        },
        SerialEntry {
            serial_index: 1,
            alternatives: &[SerialTag {
                name: "AudioFileSize",
                format: SerialFormat {
                    format: Fmt::Int32u,
                    count: SerialCount::Fixed { value: 1 },
                },
                condition: None,
                flags: IfdFlags {
                    unknown: true,
                    binary: false,
                    list: false,
                    protected: false,
                    avoid: false,
                    priority: None,
                },
                raw_conv: None,
                omitted: Omitted::NONE,
                value_conv: None,
                print_conv: SerialPrintConv::None,
                groups: TagGroups::NONE,
            }],
        },
        SerialEntry {
            serial_index: 2,
            alternatives: &[SerialTag {
                name: "Version2",
                format: SerialFormat {
                    format: Fmt::Int16u,
                    count: SerialCount::Fixed { value: 1 },
                },
                condition: None,
                flags: IfdFlags {
                    unknown: true,
                    binary: false,
                    list: false,
                    protected: false,
                    avoid: false,
                    priority: None,
                },
                raw_conv: None,
                omitted: Omitted::NONE,
                value_conv: None,
                print_conv: SerialPrintConv::None,
                groups: TagGroups::NONE,
            }],
        },
        SerialEntry {
            serial_index: 3,
            alternatives: &[SerialTag {
                name: "HeaderSize",
                format: SerialFormat {
                    format: Fmt::Int32u,
                    count: SerialCount::Fixed { value: 1 },
                },
                condition: None,
                flags: IfdFlags {
                    unknown: true,
                    binary: false,
                    list: false,
                    protected: false,
                    avoid: false,
                    priority: None,
                },
                raw_conv: None,
                omitted: Omitted::NONE,
                value_conv: None,
                print_conv: SerialPrintConv::None,
                groups: TagGroups::NONE,
            }],
        },
        SerialEntry {
            serial_index: 4,
            alternatives: &[SerialTag {
                name: "CodecFlavorID",
                format: SerialFormat {
                    format: Fmt::Int16u,
                    count: SerialCount::Fixed { value: 1 },
                },
                condition: None,
                flags: IfdFlags {
                    unknown: true,
                    binary: false,
                    list: false,
                    protected: false,
                    avoid: false,
                    priority: None,
                },
                raw_conv: None,
                omitted: Omitted::NONE,
                value_conv: None,
                print_conv: SerialPrintConv::None,
                groups: TagGroups::NONE,
            }],
        },
        SerialEntry {
            serial_index: 5,
            alternatives: &[SerialTag {
                name: "CodedFrameSize",
                format: SerialFormat {
                    format: Fmt::Int32u,
                    count: SerialCount::Fixed { value: 1 },
                },
                condition: None,
                flags: IfdFlags {
                    unknown: true,
                    binary: false,
                    list: false,
                    protected: false,
                    avoid: false,
                    priority: None,
                },
                raw_conv: None,
                omitted: Omitted::NONE,
                value_conv: None,
                print_conv: SerialPrintConv::None,
                groups: TagGroups::NONE,
            }],
        },
        SerialEntry {
            serial_index: 6,
            alternatives: &[SerialTag {
                name: "AudioBytes",
                format: SerialFormat {
                    format: Fmt::Int32u,
                    count: SerialCount::Fixed { value: 1 },
                },
                condition: None,
                flags: IfdFlags::NONE,
                raw_conv: None,
                omitted: Omitted::NONE,
                value_conv: None,
                print_conv: SerialPrintConv::None,
                groups: TagGroups::NONE,
            }],
        },
        SerialEntry {
            serial_index: 7,
            alternatives: &[SerialTag {
                name: "BytesPerMinute",
                format: SerialFormat {
                    format: Fmt::Int32u,
                    count: SerialCount::Fixed { value: 1 },
                },
                condition: None,
                flags: IfdFlags::NONE,
                raw_conv: None,
                omitted: Omitted::NONE,
                value_conv: None,
                print_conv: SerialPrintConv::None,
                groups: TagGroups::NONE,
            }],
        },
        SerialEntry {
            serial_index: 8,
            alternatives: &[SerialTag {
                name: "Unknown",
                format: SerialFormat {
                    format: Fmt::Int32u,
                    count: SerialCount::Fixed { value: 1 },
                },
                condition: None,
                flags: IfdFlags {
                    unknown: true,
                    binary: false,
                    list: false,
                    protected: false,
                    avoid: false,
                    priority: None,
                },
                raw_conv: None,
                omitted: Omitted::NONE,
                value_conv: None,
                print_conv: SerialPrintConv::None,
                groups: TagGroups::NONE,
            }],
        },
        SerialEntry {
            serial_index: 9,
            alternatives: &[SerialTag {
                name: "SubPacketH",
                format: SerialFormat {
                    format: Fmt::Int16u,
                    count: SerialCount::Fixed { value: 1 },
                },
                condition: None,
                flags: IfdFlags {
                    unknown: true,
                    binary: false,
                    list: false,
                    protected: false,
                    avoid: false,
                    priority: None,
                },
                raw_conv: None,
                omitted: Omitted::NONE,
                value_conv: None,
                print_conv: SerialPrintConv::None,
                groups: TagGroups::NONE,
            }],
        },
        SerialEntry {
            serial_index: 10,
            alternatives: &[SerialTag {
                name: "AudioFrameSize",
                format: SerialFormat {
                    format: Fmt::Int16u,
                    count: SerialCount::Fixed { value: 1 },
                },
                condition: None,
                flags: IfdFlags::NONE,
                raw_conv: None,
                omitted: Omitted::NONE,
                value_conv: None,
                print_conv: SerialPrintConv::None,
                groups: TagGroups::NONE,
            }],
        },
        SerialEntry {
            serial_index: 11,
            alternatives: &[SerialTag {
                name: "SubPacketSize",
                format: SerialFormat {
                    format: Fmt::Int16u,
                    count: SerialCount::Fixed { value: 1 },
                },
                condition: None,
                flags: IfdFlags {
                    unknown: true,
                    binary: false,
                    list: false,
                    protected: false,
                    avoid: false,
                    priority: None,
                },
                raw_conv: None,
                omitted: Omitted::NONE,
                value_conv: None,
                print_conv: SerialPrintConv::None,
                groups: TagGroups::NONE,
            }],
        },
        SerialEntry {
            serial_index: 12,
            alternatives: &[SerialTag {
                name: "Unknown",
                format: SerialFormat {
                    format: Fmt::Int16u,
                    count: SerialCount::Fixed { value: 1 },
                },
                condition: None,
                flags: IfdFlags {
                    unknown: true,
                    binary: false,
                    list: false,
                    protected: false,
                    avoid: false,
                    priority: None,
                },
                raw_conv: None,
                omitted: Omitted::NONE,
                value_conv: None,
                print_conv: SerialPrintConv::None,
                groups: TagGroups::NONE,
            }],
        },
        SerialEntry {
            serial_index: 13,
            alternatives: &[SerialTag {
                name: "SampleRate",
                format: SerialFormat {
                    format: Fmt::Int16u,
                    count: SerialCount::Fixed { value: 1 },
                },
                condition: None,
                flags: IfdFlags::NONE,
                raw_conv: None,
                omitted: Omitted::NONE,
                value_conv: None,
                print_conv: SerialPrintConv::None,
                groups: TagGroups::NONE,
            }],
        },
        SerialEntry {
            serial_index: 14,
            alternatives: &[SerialTag {
                name: "Unknown",
                format: SerialFormat {
                    format: Fmt::Int16u,
                    count: SerialCount::Fixed { value: 1 },
                },
                condition: None,
                flags: IfdFlags {
                    unknown: true,
                    binary: false,
                    list: false,
                    protected: false,
                    avoid: false,
                    priority: None,
                },
                raw_conv: None,
                omitted: Omitted::NONE,
                value_conv: None,
                print_conv: SerialPrintConv::None,
                groups: TagGroups::NONE,
            }],
        },
        SerialEntry {
            serial_index: 15,
            alternatives: &[SerialTag {
                name: "BitsPerSample",
                format: SerialFormat {
                    format: Fmt::Int16u,
                    count: SerialCount::Fixed { value: 1 },
                },
                condition: None,
                flags: IfdFlags::NONE,
                raw_conv: None,
                omitted: Omitted::NONE,
                value_conv: None,
                print_conv: SerialPrintConv::None,
                groups: TagGroups::NONE,
            }],
        },
        SerialEntry {
            serial_index: 16,
            alternatives: &[SerialTag {
                name: "Channels",
                format: SerialFormat {
                    format: Fmt::Int16u,
                    count: SerialCount::Fixed { value: 1 },
                },
                condition: None,
                flags: IfdFlags::NONE,
                raw_conv: None,
                omitted: Omitted::NONE,
                value_conv: None,
                print_conv: SerialPrintConv::None,
                groups: TagGroups::NONE,
            }],
        },
        SerialEntry {
            serial_index: 17,
            alternatives: &[SerialTag {
                name: "FourCC2Len",
                format: SerialFormat {
                    format: Fmt::Int8u,
                    count: SerialCount::Fixed { value: 1 },
                },
                condition: None,
                flags: IfdFlags {
                    unknown: true,
                    binary: false,
                    list: false,
                    protected: false,
                    avoid: false,
                    priority: None,
                },
                raw_conv: None,
                omitted: Omitted::NONE,
                value_conv: None,
                print_conv: SerialPrintConv::None,
                groups: TagGroups::NONE,
            }],
        },
        SerialEntry {
            serial_index: 18,
            alternatives: &[SerialTag {
                name: "FourCC2",
                format: SerialFormat {
                    format: Fmt::Undef(1),
                    count: SerialCount::Fixed { value: 4 },
                },
                condition: None,
                flags: IfdFlags {
                    unknown: true,
                    binary: false,
                    list: false,
                    protected: false,
                    avoid: false,
                    priority: None,
                },
                raw_conv: None,
                omitted: Omitted::NONE,
                value_conv: None,
                print_conv: SerialPrintConv::None,
                groups: TagGroups::NONE,
            }],
        },
        SerialEntry {
            serial_index: 19,
            alternatives: &[SerialTag {
                name: "FourCC3Len",
                format: SerialFormat {
                    format: Fmt::Int8u,
                    count: SerialCount::Fixed { value: 1 },
                },
                condition: None,
                flags: IfdFlags {
                    unknown: true,
                    binary: false,
                    list: false,
                    protected: false,
                    avoid: false,
                    priority: None,
                },
                raw_conv: None,
                omitted: Omitted::NONE,
                value_conv: None,
                print_conv: SerialPrintConv::None,
                groups: TagGroups::NONE,
            }],
        },
        SerialEntry {
            serial_index: 20,
            alternatives: &[SerialTag {
                name: "FourCC3",
                format: SerialFormat {
                    format: Fmt::Undef(1),
                    count: SerialCount::Fixed { value: 4 },
                },
                condition: None,
                flags: IfdFlags {
                    unknown: true,
                    binary: false,
                    list: false,
                    protected: false,
                    avoid: false,
                    priority: None,
                },
                raw_conv: None,
                omitted: Omitted::NONE,
                value_conv: None,
                print_conv: SerialPrintConv::None,
                groups: TagGroups::NONE,
            }],
        },
        SerialEntry {
            serial_index: 21,
            alternatives: &[SerialTag {
                name: "Unknown",
                format: SerialFormat {
                    format: Fmt::Int8u,
                    count: SerialCount::Fixed { value: 1 },
                },
                condition: None,
                flags: IfdFlags {
                    unknown: true,
                    binary: false,
                    list: false,
                    protected: false,
                    avoid: false,
                    priority: None,
                },
                raw_conv: None,
                omitted: Omitted::NONE,
                value_conv: None,
                print_conv: SerialPrintConv::None,
                groups: TagGroups::NONE,
            }],
        },
        SerialEntry {
            serial_index: 22,
            alternatives: &[SerialTag {
                name: "Unknown",
                format: SerialFormat {
                    format: Fmt::Int16u,
                    count: SerialCount::Fixed { value: 1 },
                },
                condition: None,
                flags: IfdFlags {
                    unknown: true,
                    binary: false,
                    list: false,
                    protected: false,
                    avoid: false,
                    priority: None,
                },
                raw_conv: None,
                omitted: Omitted::NONE,
                value_conv: None,
                print_conv: SerialPrintConv::None,
                groups: TagGroups::NONE,
            }],
        },
        SerialEntry {
            serial_index: 23,
            alternatives: &[SerialTag {
                name: "TitleLen",
                format: SerialFormat {
                    format: Fmt::Int8u,
                    count: SerialCount::Fixed { value: 1 },
                },
                condition: None,
                flags: IfdFlags {
                    unknown: true,
                    binary: false,
                    list: false,
                    protected: false,
                    avoid: false,
                    priority: None,
                },
                raw_conv: None,
                omitted: Omitted::NONE,
                value_conv: None,
                print_conv: SerialPrintConv::None,
                groups: TagGroups::NONE,
            }],
        },
        SerialEntry {
            serial_index: 24,
            alternatives: &[SerialTag {
                name: "Title",
                format: SerialFormat {
                    format: Fmt::Str(1),
                    count: SerialCount::PriorRaw { serial_index: 23 },
                },
                condition: None,
                flags: IfdFlags::NONE,
                raw_conv: None,
                omitted: Omitted::NONE,
                value_conv: None,
                print_conv: SerialPrintConv::None,
                groups: TagGroups::NONE,
            }],
        },
        SerialEntry {
            serial_index: 25,
            alternatives: &[SerialTag {
                name: "ArtistLen",
                format: SerialFormat {
                    format: Fmt::Int8u,
                    count: SerialCount::Fixed { value: 1 },
                },
                condition: None,
                flags: IfdFlags {
                    unknown: true,
                    binary: false,
                    list: false,
                    protected: false,
                    avoid: false,
                    priority: None,
                },
                raw_conv: None,
                omitted: Omitted::NONE,
                value_conv: None,
                print_conv: SerialPrintConv::None,
                groups: TagGroups::NONE,
            }],
        },
        SerialEntry {
            serial_index: 26,
            alternatives: &[SerialTag {
                name: "Artist",
                format: SerialFormat {
                    format: Fmt::Str(1),
                    count: SerialCount::PriorRaw { serial_index: 25 },
                },
                condition: None,
                flags: IfdFlags::NONE,
                raw_conv: None,
                omitted: Omitted::NONE,
                value_conv: None,
                print_conv: SerialPrintConv::None,
                groups: TagGroups {
                    g0: None,
                    g1: None,
                    g2: Some("Author"),
                },
            }],
        },
        SerialEntry {
            serial_index: 27,
            alternatives: &[SerialTag {
                name: "CopyrightLen",
                format: SerialFormat {
                    format: Fmt::Int8u,
                    count: SerialCount::Fixed { value: 1 },
                },
                condition: None,
                flags: IfdFlags {
                    unknown: true,
                    binary: false,
                    list: false,
                    protected: false,
                    avoid: false,
                    priority: None,
                },
                raw_conv: None,
                omitted: Omitted::NONE,
                value_conv: None,
                print_conv: SerialPrintConv::None,
                groups: TagGroups::NONE,
            }],
        },
        SerialEntry {
            serial_index: 28,
            alternatives: &[SerialTag {
                name: "Copyright",
                format: SerialFormat {
                    format: Fmt::Str(1),
                    count: SerialCount::PriorRaw { serial_index: 27 },
                },
                condition: None,
                flags: IfdFlags::NONE,
                raw_conv: None,
                omitted: Omitted::NONE,
                value_conv: None,
                print_conv: SerialPrintConv::None,
                groups: TagGroups {
                    g0: None,
                    g1: None,
                    g2: Some("Author"),
                },
            }],
        },
        SerialEntry {
            serial_index: 29,
            alternatives: &[SerialTag {
                name: "CommentLen",
                format: SerialFormat {
                    format: Fmt::Int8u,
                    count: SerialCount::Fixed { value: 1 },
                },
                condition: None,
                flags: IfdFlags {
                    unknown: true,
                    binary: false,
                    list: false,
                    protected: false,
                    avoid: false,
                    priority: None,
                },
                raw_conv: None,
                omitted: Omitted::NONE,
                value_conv: None,
                print_conv: SerialPrintConv::None,
                groups: TagGroups::NONE,
            }],
        },
        SerialEntry {
            serial_index: 30,
            alternatives: &[SerialTag {
                name: "Comment",
                format: SerialFormat {
                    format: Fmt::Str(1),
                    count: SerialCount::PriorRaw { serial_index: 29 },
                },
                condition: None,
                flags: IfdFlags::NONE,
                raw_conv: None,
                omitted: Omitted::NONE,
                value_conv: None,
                print_conv: SerialPrintConv::None,
                groups: TagGroups::NONE,
            }],
        },
    ],
};
pub static SERIAL_REAL_AUDIOV5: SerialTable = SerialTable {
    module: "Real",
    table: "AudioV5",
    group0: "Real",
    group1: "Real-RA5",
    group2: "Audio",
    default_format: Fmt::Int16u,
    processor: SerialProcessorFacts {
        name: "Image::ExifTool::Canon::ProcessSerialData",
        source_file: "Image/ExifTool/Canon.pm",
        source_sha256: "d22b110e7b2e1af2d6e59bb97db97a04ffc2bfd1ba7d078d380ae60fbc70bbba",
        source_body_sha256: "ab5cb31e06a991a02f5569f1c008303c0505d28caf7ae2ec044aeede9c9f999c",
    },
    gate_a: GateA { blocked_by: &[] },
    entries: &[
        SerialEntry {
            serial_index: 0,
            alternatives: &[SerialTag {
                name: "FourCC1",
                format: SerialFormat {
                    format: Fmt::Undef(1),
                    count: SerialCount::Fixed { value: 4 },
                },
                condition: None,
                flags: IfdFlags {
                    unknown: true,
                    binary: false,
                    list: false,
                    protected: false,
                    avoid: false,
                    priority: None,
                },
                raw_conv: None,
                omitted: Omitted::NONE,
                value_conv: None,
                print_conv: SerialPrintConv::None,
                groups: TagGroups::NONE,
            }],
        },
        SerialEntry {
            serial_index: 1,
            alternatives: &[SerialTag {
                name: "AudioFileSize",
                format: SerialFormat {
                    format: Fmt::Int32u,
                    count: SerialCount::Fixed { value: 1 },
                },
                condition: None,
                flags: IfdFlags {
                    unknown: true,
                    binary: false,
                    list: false,
                    protected: false,
                    avoid: false,
                    priority: None,
                },
                raw_conv: None,
                omitted: Omitted::NONE,
                value_conv: None,
                print_conv: SerialPrintConv::None,
                groups: TagGroups::NONE,
            }],
        },
        SerialEntry {
            serial_index: 2,
            alternatives: &[SerialTag {
                name: "Version2",
                format: SerialFormat {
                    format: Fmt::Int16u,
                    count: SerialCount::Fixed { value: 1 },
                },
                condition: None,
                flags: IfdFlags {
                    unknown: true,
                    binary: false,
                    list: false,
                    protected: false,
                    avoid: false,
                    priority: None,
                },
                raw_conv: None,
                omitted: Omitted::NONE,
                value_conv: None,
                print_conv: SerialPrintConv::None,
                groups: TagGroups::NONE,
            }],
        },
        SerialEntry {
            serial_index: 3,
            alternatives: &[SerialTag {
                name: "HeaderSize",
                format: SerialFormat {
                    format: Fmt::Int32u,
                    count: SerialCount::Fixed { value: 1 },
                },
                condition: None,
                flags: IfdFlags {
                    unknown: true,
                    binary: false,
                    list: false,
                    protected: false,
                    avoid: false,
                    priority: None,
                },
                raw_conv: None,
                omitted: Omitted::NONE,
                value_conv: None,
                print_conv: SerialPrintConv::None,
                groups: TagGroups::NONE,
            }],
        },
        SerialEntry {
            serial_index: 4,
            alternatives: &[SerialTag {
                name: "CodecFlavorID",
                format: SerialFormat {
                    format: Fmt::Int16u,
                    count: SerialCount::Fixed { value: 1 },
                },
                condition: None,
                flags: IfdFlags {
                    unknown: true,
                    binary: false,
                    list: false,
                    protected: false,
                    avoid: false,
                    priority: None,
                },
                raw_conv: None,
                omitted: Omitted::NONE,
                value_conv: None,
                print_conv: SerialPrintConv::None,
                groups: TagGroups::NONE,
            }],
        },
        SerialEntry {
            serial_index: 5,
            alternatives: &[SerialTag {
                name: "CodedFrameSize",
                format: SerialFormat {
                    format: Fmt::Int32u,
                    count: SerialCount::Fixed { value: 1 },
                },
                condition: None,
                flags: IfdFlags {
                    unknown: true,
                    binary: false,
                    list: false,
                    protected: false,
                    avoid: false,
                    priority: None,
                },
                raw_conv: None,
                omitted: Omitted::NONE,
                value_conv: None,
                print_conv: SerialPrintConv::None,
                groups: TagGroups::NONE,
            }],
        },
        SerialEntry {
            serial_index: 6,
            alternatives: &[SerialTag {
                name: "AudioBytes",
                format: SerialFormat {
                    format: Fmt::Int32u,
                    count: SerialCount::Fixed { value: 1 },
                },
                condition: None,
                flags: IfdFlags::NONE,
                raw_conv: None,
                omitted: Omitted::NONE,
                value_conv: None,
                print_conv: SerialPrintConv::None,
                groups: TagGroups::NONE,
            }],
        },
        SerialEntry {
            serial_index: 7,
            alternatives: &[SerialTag {
                name: "BytesPerMinute",
                format: SerialFormat {
                    format: Fmt::Int32u,
                    count: SerialCount::Fixed { value: 1 },
                },
                condition: None,
                flags: IfdFlags::NONE,
                raw_conv: None,
                omitted: Omitted::NONE,
                value_conv: None,
                print_conv: SerialPrintConv::None,
                groups: TagGroups::NONE,
            }],
        },
        SerialEntry {
            serial_index: 8,
            alternatives: &[SerialTag {
                name: "Unknown",
                format: SerialFormat {
                    format: Fmt::Int32u,
                    count: SerialCount::Fixed { value: 1 },
                },
                condition: None,
                flags: IfdFlags {
                    unknown: true,
                    binary: false,
                    list: false,
                    protected: false,
                    avoid: false,
                    priority: None,
                },
                raw_conv: None,
                omitted: Omitted::NONE,
                value_conv: None,
                print_conv: SerialPrintConv::None,
                groups: TagGroups::NONE,
            }],
        },
        SerialEntry {
            serial_index: 9,
            alternatives: &[SerialTag {
                name: "SubPacketH",
                format: SerialFormat {
                    format: Fmt::Int16u,
                    count: SerialCount::Fixed { value: 1 },
                },
                condition: None,
                flags: IfdFlags {
                    unknown: true,
                    binary: false,
                    list: false,
                    protected: false,
                    avoid: false,
                    priority: None,
                },
                raw_conv: None,
                omitted: Omitted::NONE,
                value_conv: None,
                print_conv: SerialPrintConv::None,
                groups: TagGroups::NONE,
            }],
        },
        SerialEntry {
            serial_index: 10,
            alternatives: &[SerialTag {
                name: "FrameSize",
                format: SerialFormat {
                    format: Fmt::Int16u,
                    count: SerialCount::Fixed { value: 1 },
                },
                condition: None,
                flags: IfdFlags {
                    unknown: true,
                    binary: false,
                    list: false,
                    protected: false,
                    avoid: false,
                    priority: None,
                },
                raw_conv: None,
                omitted: Omitted::NONE,
                value_conv: None,
                print_conv: SerialPrintConv::None,
                groups: TagGroups::NONE,
            }],
        },
        SerialEntry {
            serial_index: 11,
            alternatives: &[SerialTag {
                name: "SubPacketSize",
                format: SerialFormat {
                    format: Fmt::Int16u,
                    count: SerialCount::Fixed { value: 1 },
                },
                condition: None,
                flags: IfdFlags {
                    unknown: true,
                    binary: false,
                    list: false,
                    protected: false,
                    avoid: false,
                    priority: None,
                },
                raw_conv: None,
                omitted: Omitted::NONE,
                value_conv: None,
                print_conv: SerialPrintConv::None,
                groups: TagGroups::NONE,
            }],
        },
        SerialEntry {
            serial_index: 12,
            alternatives: &[SerialTag {
                name: "SampleRate",
                format: SerialFormat {
                    format: Fmt::Int16u,
                    count: SerialCount::Fixed { value: 1 },
                },
                condition: None,
                flags: IfdFlags::NONE,
                raw_conv: None,
                omitted: Omitted::NONE,
                value_conv: None,
                print_conv: SerialPrintConv::None,
                groups: TagGroups::NONE,
            }],
        },
        SerialEntry {
            serial_index: 13,
            alternatives: &[SerialTag {
                name: "SampleRate2",
                format: SerialFormat {
                    format: Fmt::Int16u,
                    count: SerialCount::Fixed { value: 1 },
                },
                condition: None,
                flags: IfdFlags {
                    unknown: true,
                    binary: false,
                    list: false,
                    protected: false,
                    avoid: false,
                    priority: None,
                },
                raw_conv: None,
                omitted: Omitted::NONE,
                value_conv: None,
                print_conv: SerialPrintConv::None,
                groups: TagGroups::NONE,
            }],
        },
        SerialEntry {
            serial_index: 14,
            alternatives: &[SerialTag {
                name: "BitsPerSample",
                format: SerialFormat {
                    format: Fmt::Int32u,
                    count: SerialCount::Fixed { value: 1 },
                },
                condition: None,
                flags: IfdFlags::NONE,
                raw_conv: None,
                omitted: Omitted::NONE,
                value_conv: None,
                print_conv: SerialPrintConv::None,
                groups: TagGroups::NONE,
            }],
        },
        SerialEntry {
            serial_index: 15,
            alternatives: &[SerialTag {
                name: "Channels",
                format: SerialFormat {
                    format: Fmt::Int16u,
                    count: SerialCount::Fixed { value: 1 },
                },
                condition: None,
                flags: IfdFlags::NONE,
                raw_conv: None,
                omitted: Omitted::NONE,
                value_conv: None,
                print_conv: SerialPrintConv::None,
                groups: TagGroups::NONE,
            }],
        },
        SerialEntry {
            serial_index: 16,
            alternatives: &[SerialTag {
                name: "Genr",
                format: SerialFormat {
                    format: Fmt::Int32u,
                    count: SerialCount::Fixed { value: 1 },
                },
                condition: None,
                flags: IfdFlags {
                    unknown: true,
                    binary: false,
                    list: false,
                    protected: false,
                    avoid: false,
                    priority: None,
                },
                raw_conv: None,
                omitted: Omitted::NONE,
                value_conv: None,
                print_conv: SerialPrintConv::None,
                groups: TagGroups::NONE,
            }],
        },
        SerialEntry {
            serial_index: 17,
            alternatives: &[SerialTag {
                name: "FourCC3",
                format: SerialFormat {
                    format: Fmt::Undef(1),
                    count: SerialCount::Fixed { value: 4 },
                },
                condition: None,
                flags: IfdFlags {
                    unknown: true,
                    binary: false,
                    list: false,
                    protected: false,
                    avoid: false,
                    priority: None,
                },
                raw_conv: None,
                omitted: Omitted::NONE,
                value_conv: None,
                print_conv: SerialPrintConv::None,
                groups: TagGroups::NONE,
            }],
        },
    ],
};
pub static SERIAL_REAL_CONTENTDESCR: SerialTable = SerialTable {
    module: "Real",
    table: "ContentDescr",
    group0: "Real",
    group1: "Real-CONT",
    group2: "Video",
    default_format: Fmt::Int16u,
    processor: SerialProcessorFacts {
        name: "Image::ExifTool::Canon::ProcessSerialData",
        source_file: "Image/ExifTool/Canon.pm",
        source_sha256: "d22b110e7b2e1af2d6e59bb97db97a04ffc2bfd1ba7d078d380ae60fbc70bbba",
        source_body_sha256: "ab5cb31e06a991a02f5569f1c008303c0505d28caf7ae2ec044aeede9c9f999c",
    },
    gate_a: GateA { blocked_by: &[] },
    entries: &[
        SerialEntry {
            serial_index: 0,
            alternatives: &[SerialTag {
                name: "TitleLen",
                format: SerialFormat {
                    format: Fmt::Int16u,
                    count: SerialCount::Fixed { value: 1 },
                },
                condition: None,
                flags: IfdFlags {
                    unknown: true,
                    binary: false,
                    list: false,
                    protected: false,
                    avoid: false,
                    priority: None,
                },
                raw_conv: None,
                omitted: Omitted::NONE,
                value_conv: None,
                print_conv: SerialPrintConv::None,
                groups: TagGroups::NONE,
            }],
        },
        SerialEntry {
            serial_index: 1,
            alternatives: &[SerialTag {
                name: "Title",
                format: SerialFormat {
                    format: Fmt::Str(1),
                    count: SerialCount::PriorRaw { serial_index: 0 },
                },
                condition: None,
                flags: IfdFlags::NONE,
                raw_conv: None,
                omitted: Omitted::NONE,
                value_conv: None,
                print_conv: SerialPrintConv::None,
                groups: TagGroups::NONE,
            }],
        },
        SerialEntry {
            serial_index: 2,
            alternatives: &[SerialTag {
                name: "AuthorLen",
                format: SerialFormat {
                    format: Fmt::Int16u,
                    count: SerialCount::Fixed { value: 1 },
                },
                condition: None,
                flags: IfdFlags {
                    unknown: true,
                    binary: false,
                    list: false,
                    protected: false,
                    avoid: false,
                    priority: None,
                },
                raw_conv: None,
                omitted: Omitted::NONE,
                value_conv: None,
                print_conv: SerialPrintConv::None,
                groups: TagGroups::NONE,
            }],
        },
        SerialEntry {
            serial_index: 3,
            alternatives: &[SerialTag {
                name: "Author",
                format: SerialFormat {
                    format: Fmt::Str(1),
                    count: SerialCount::PriorRaw { serial_index: 2 },
                },
                condition: None,
                flags: IfdFlags::NONE,
                raw_conv: None,
                omitted: Omitted::NONE,
                value_conv: None,
                print_conv: SerialPrintConv::None,
                groups: TagGroups {
                    g0: None,
                    g1: None,
                    g2: Some("Author"),
                },
            }],
        },
        SerialEntry {
            serial_index: 4,
            alternatives: &[SerialTag {
                name: "CopyrightLen",
                format: SerialFormat {
                    format: Fmt::Int16u,
                    count: SerialCount::Fixed { value: 1 },
                },
                condition: None,
                flags: IfdFlags {
                    unknown: true,
                    binary: false,
                    list: false,
                    protected: false,
                    avoid: false,
                    priority: None,
                },
                raw_conv: None,
                omitted: Omitted::NONE,
                value_conv: None,
                print_conv: SerialPrintConv::None,
                groups: TagGroups::NONE,
            }],
        },
        SerialEntry {
            serial_index: 5,
            alternatives: &[SerialTag {
                name: "Copyright",
                format: SerialFormat {
                    format: Fmt::Str(1),
                    count: SerialCount::PriorRaw { serial_index: 4 },
                },
                condition: None,
                flags: IfdFlags::NONE,
                raw_conv: None,
                omitted: Omitted::NONE,
                value_conv: None,
                print_conv: SerialPrintConv::None,
                groups: TagGroups {
                    g0: None,
                    g1: None,
                    g2: Some("Author"),
                },
            }],
        },
        SerialEntry {
            serial_index: 6,
            alternatives: &[SerialTag {
                name: "CommentLen",
                format: SerialFormat {
                    format: Fmt::Int16u,
                    count: SerialCount::Fixed { value: 1 },
                },
                condition: None,
                flags: IfdFlags {
                    unknown: true,
                    binary: false,
                    list: false,
                    protected: false,
                    avoid: false,
                    priority: None,
                },
                raw_conv: None,
                omitted: Omitted::NONE,
                value_conv: None,
                print_conv: SerialPrintConv::None,
                groups: TagGroups::NONE,
            }],
        },
        SerialEntry {
            serial_index: 7,
            alternatives: &[SerialTag {
                name: "Comment",
                format: SerialFormat {
                    format: Fmt::Str(1),
                    count: SerialCount::PriorRaw { serial_index: 6 },
                },
                condition: None,
                flags: IfdFlags::NONE,
                raw_conv: None,
                omitted: Omitted::NONE,
                value_conv: None,
                print_conv: SerialPrintConv::None,
                groups: TagGroups::NONE,
            }],
        },
    ],
};
pub static SERIAL_REAL_MEDIAPROPS: SerialTable = SerialTable {
    module: "Real",
    table: "MediaProps",
    group0: "Real",
    group1: "Real-MDPR",
    group2: "Video",
    default_format: Fmt::Int32u,
    processor: SerialProcessorFacts {
        name: "Image::ExifTool::Canon::ProcessSerialData",
        source_file: "Image/ExifTool/Canon.pm",
        source_sha256: "d22b110e7b2e1af2d6e59bb97db97a04ffc2bfd1ba7d078d380ae60fbc70bbba",
        source_body_sha256: "ab5cb31e06a991a02f5569f1c008303c0505d28caf7ae2ec044aeede9c9f999c",
    },
    gate_a: GateA {
        blocked_by: &[
            ("serial_emitter_format", 1),
            ("serial_print_conv_expr", 4),
            ("serial_row_shape", 1),
            ("serial_table_priority", 1),
            ("serial_value_conv", 2),
        ],
    },
    entries: &[
        SerialEntry {
            serial_index: 0,
            alternatives: &[SerialTag {
                name: "StreamNumber",
                format: SerialFormat {
                    format: Fmt::Int16u,
                    count: SerialCount::Fixed { value: 1 },
                },
                condition: None,
                flags: IfdFlags::NONE,
                raw_conv: None,
                omitted: Omitted::NONE,
                value_conv: None,
                print_conv: SerialPrintConv::None,
                groups: TagGroups::NONE,
            }],
        },
        SerialEntry {
            serial_index: 3,
            alternatives: &[SerialTag {
                name: "StreamMaxPacketSize",
                format: SerialFormat {
                    format: Fmt::Int32u,
                    count: SerialCount::Fixed { value: 1 },
                },
                condition: None,
                flags: IfdFlags::NONE,
                raw_conv: None,
                omitted: Omitted::NONE,
                value_conv: None,
                print_conv: SerialPrintConv::None,
                groups: TagGroups::NONE,
            }],
        },
        SerialEntry {
            serial_index: 4,
            alternatives: &[SerialTag {
                name: "StreamAvgPacketSize",
                format: SerialFormat {
                    format: Fmt::Int32u,
                    count: SerialCount::Fixed { value: 1 },
                },
                condition: None,
                flags: IfdFlags::NONE,
                raw_conv: None,
                omitted: Omitted::NONE,
                value_conv: None,
                print_conv: SerialPrintConv::None,
                groups: TagGroups::NONE,
            }],
        },
        SerialEntry {
            serial_index: 5,
            alternatives: &[SerialTag {
                name: "StreamStartTime",
                format: SerialFormat {
                    format: Fmt::Int32u,
                    count: SerialCount::Fixed { value: 1 },
                },
                condition: None,
                flags: IfdFlags::NONE,
                raw_conv: None,
                omitted: Omitted::NONE,
                value_conv: None,
                print_conv: SerialPrintConv::None,
                groups: TagGroups::NONE,
            }],
        },
        SerialEntry {
            serial_index: 8,
            alternatives: &[SerialTag {
                name: "StreamNameLen",
                format: SerialFormat {
                    format: Fmt::Int8u,
                    count: SerialCount::Fixed { value: 1 },
                },
                condition: None,
                flags: IfdFlags {
                    unknown: true,
                    binary: false,
                    list: false,
                    protected: false,
                    avoid: false,
                    priority: None,
                },
                raw_conv: None,
                omitted: Omitted::NONE,
                value_conv: None,
                print_conv: SerialPrintConv::None,
                groups: TagGroups::NONE,
            }],
        },
        SerialEntry {
            serial_index: 9,
            alternatives: &[SerialTag {
                name: "StreamName",
                format: SerialFormat {
                    format: Fmt::Str(1),
                    count: SerialCount::PriorRaw { serial_index: 8 },
                },
                condition: None,
                flags: IfdFlags::NONE,
                raw_conv: None,
                omitted: Omitted::NONE,
                value_conv: None,
                print_conv: SerialPrintConv::None,
                groups: TagGroups::NONE,
            }],
        },
        SerialEntry {
            serial_index: 10,
            alternatives: &[SerialTag {
                name: "StreamMimeLen",
                format: SerialFormat {
                    format: Fmt::Int8u,
                    count: SerialCount::Fixed { value: 1 },
                },
                condition: None,
                flags: IfdFlags {
                    unknown: true,
                    binary: false,
                    list: false,
                    protected: false,
                    avoid: false,
                    priority: None,
                },
                raw_conv: None,
                omitted: Omitted::NONE,
                value_conv: None,
                print_conv: SerialPrintConv::None,
                groups: TagGroups::NONE,
            }],
        },
        SerialEntry {
            serial_index: 11,
            alternatives: &[SerialTag {
                name: "StreamMimeType",
                format: SerialFormat {
                    format: Fmt::Str(1),
                    count: SerialCount::PriorRaw { serial_index: 10 },
                },
                condition: None,
                flags: IfdFlags::NONE,
                raw_conv: Some(RawConvEffect::SetMember {
                    member: "RealStreamMime",
                }),
                omitted: Omitted::NONE,
                value_conv: None,
                print_conv: SerialPrintConv::None,
                groups: TagGroups::NONE,
            }],
        },
        SerialEntry {
            serial_index: 12,
            alternatives: &[SerialTag {
                name: "FileInfoLen",
                format: SerialFormat {
                    format: Fmt::Int32u,
                    count: SerialCount::Fixed { value: 1 },
                },
                condition: None,
                flags: IfdFlags {
                    unknown: true,
                    binary: false,
                    list: false,
                    protected: false,
                    avoid: false,
                    priority: None,
                },
                raw_conv: None,
                omitted: Omitted::NONE,
                value_conv: None,
                print_conv: SerialPrintConv::None,
                groups: TagGroups::NONE,
            }],
        },
        SerialEntry {
            serial_index: 13,
            alternatives: &[SerialTag {
                name: "FileInfoLen2",
                format: SerialFormat {
                    format: Fmt::Int32u,
                    count: SerialCount::Fixed { value: 1 },
                },
                condition: Some(SerialCondition {
                    cond: Cond::MemberStrEq {
                        member: "RealStreamMime",
                        value: "logical-fileinfo",
                        negate: false,
                    },
                    missing_member: SerialMissingMember::EmptyStringForStringOps,
                }),
                flags: IfdFlags {
                    unknown: true,
                    binary: false,
                    list: false,
                    protected: false,
                    avoid: false,
                    priority: None,
                },
                raw_conv: None,
                omitted: Omitted::NONE,
                value_conv: None,
                print_conv: SerialPrintConv::None,
                groups: TagGroups::NONE,
            }],
        },
        SerialEntry {
            serial_index: 14,
            alternatives: &[SerialTag {
                name: "FileInfoVersion",
                format: SerialFormat {
                    format: Fmt::Int16u,
                    count: SerialCount::Fixed { value: 1 },
                },
                condition: None,
                flags: IfdFlags::NONE,
                raw_conv: None,
                omitted: Omitted::NONE,
                value_conv: None,
                print_conv: SerialPrintConv::None,
                groups: TagGroups::NONE,
            }],
        },
        SerialEntry {
            serial_index: 15,
            alternatives: &[SerialTag {
                name: "PhysicalStreams",
                format: SerialFormat {
                    format: Fmt::Int16u,
                    count: SerialCount::Fixed { value: 1 },
                },
                condition: None,
                flags: IfdFlags {
                    unknown: true,
                    binary: false,
                    list: false,
                    protected: false,
                    avoid: false,
                    priority: None,
                },
                raw_conv: None,
                omitted: Omitted::NONE,
                value_conv: None,
                print_conv: SerialPrintConv::None,
                groups: TagGroups::NONE,
            }],
        },
        SerialEntry {
            serial_index: 16,
            alternatives: &[SerialTag {
                name: "PhysicalStreamNumbers",
                format: SerialFormat {
                    format: Fmt::Int16u,
                    count: SerialCount::PriorRaw { serial_index: 15 },
                },
                condition: None,
                flags: IfdFlags {
                    unknown: true,
                    binary: false,
                    list: false,
                    protected: false,
                    avoid: false,
                    priority: None,
                },
                raw_conv: None,
                omitted: Omitted::NONE,
                value_conv: None,
                print_conv: SerialPrintConv::None,
                groups: TagGroups::NONE,
            }],
        },
        SerialEntry {
            serial_index: 17,
            alternatives: &[SerialTag {
                name: "DataOffsets",
                format: SerialFormat {
                    format: Fmt::Int32u,
                    count: SerialCount::PriorRaw { serial_index: 15 },
                },
                condition: None,
                flags: IfdFlags {
                    unknown: true,
                    binary: false,
                    list: false,
                    protected: false,
                    avoid: false,
                    priority: None,
                },
                raw_conv: None,
                omitted: Omitted::NONE,
                value_conv: None,
                print_conv: SerialPrintConv::None,
                groups: TagGroups::NONE,
            }],
        },
        SerialEntry {
            serial_index: 18,
            alternatives: &[SerialTag {
                name: "NumRules",
                format: SerialFormat {
                    format: Fmt::Int16u,
                    count: SerialCount::Fixed { value: 1 },
                },
                condition: None,
                flags: IfdFlags {
                    unknown: true,
                    binary: false,
                    list: false,
                    protected: false,
                    avoid: false,
                    priority: None,
                },
                raw_conv: None,
                omitted: Omitted::NONE,
                value_conv: None,
                print_conv: SerialPrintConv::None,
                groups: TagGroups::NONE,
            }],
        },
        SerialEntry {
            serial_index: 19,
            alternatives: &[SerialTag {
                name: "PhysicalStreamNumberMap",
                format: SerialFormat {
                    format: Fmt::Int16u,
                    count: SerialCount::PriorRaw { serial_index: 18 },
                },
                condition: None,
                flags: IfdFlags {
                    unknown: true,
                    binary: false,
                    list: false,
                    protected: false,
                    avoid: false,
                    priority: None,
                },
                raw_conv: None,
                omitted: Omitted::NONE,
                value_conv: None,
                print_conv: SerialPrintConv::None,
                groups: TagGroups::NONE,
            }],
        },
        SerialEntry {
            serial_index: 20,
            alternatives: &[SerialTag {
                name: "NumProperties",
                format: SerialFormat {
                    format: Fmt::Int16u,
                    count: SerialCount::Fixed { value: 1 },
                },
                condition: None,
                flags: IfdFlags {
                    unknown: true,
                    binary: false,
                    list: false,
                    protected: false,
                    avoid: false,
                    priority: None,
                },
                raw_conv: None,
                omitted: Omitted::NONE,
                value_conv: None,
                print_conv: SerialPrintConv::None,
                groups: TagGroups::NONE,
            }],
        },
    ],
};
pub static SERIAL_REAL_PROPERTIES: SerialTable = SerialTable {
    module: "Real",
    table: "Properties",
    group0: "Real",
    group1: "Real-PROP",
    group2: "Video",
    default_format: Fmt::Int32u,
    processor: SerialProcessorFacts {
        name: "Image::ExifTool::Canon::ProcessSerialData",
        source_file: "Image/ExifTool/Canon.pm",
        source_sha256: "d22b110e7b2e1af2d6e59bb97db97a04ffc2bfd1ba7d078d380ae60fbc70bbba",
        source_body_sha256: "ab5cb31e06a991a02f5569f1c008303c0505d28caf7ae2ec044aeede9c9f999c",
    },
    gate_a: GateA {
        blocked_by: &[
            ("serial_print_conv", 1),
            ("serial_print_conv_expr", 4),
            ("serial_value_conv", 2),
        ],
    },
    entries: &[
        SerialEntry {
            serial_index: 2,
            alternatives: &[SerialTag {
                name: "MaxPacketSize",
                format: SerialFormat {
                    format: Fmt::Int32u,
                    count: SerialCount::Fixed { value: 1 },
                },
                condition: None,
                flags: IfdFlags::NONE,
                raw_conv: None,
                omitted: Omitted::NONE,
                value_conv: None,
                print_conv: SerialPrintConv::None,
                groups: TagGroups::NONE,
            }],
        },
        SerialEntry {
            serial_index: 3,
            alternatives: &[SerialTag {
                name: "AvgPacketSize",
                format: SerialFormat {
                    format: Fmt::Int32u,
                    count: SerialCount::Fixed { value: 1 },
                },
                condition: None,
                flags: IfdFlags::NONE,
                raw_conv: None,
                omitted: Omitted::NONE,
                value_conv: None,
                print_conv: SerialPrintConv::None,
                groups: TagGroups::NONE,
            }],
        },
        SerialEntry {
            serial_index: 4,
            alternatives: &[SerialTag {
                name: "NumPackets",
                format: SerialFormat {
                    format: Fmt::Int32u,
                    count: SerialCount::Fixed { value: 1 },
                },
                condition: None,
                flags: IfdFlags::NONE,
                raw_conv: None,
                omitted: Omitted::NONE,
                value_conv: None,
                print_conv: SerialPrintConv::None,
                groups: TagGroups::NONE,
            }],
        },
        SerialEntry {
            serial_index: 7,
            alternatives: &[SerialTag {
                name: "IndexOffset",
                format: SerialFormat {
                    format: Fmt::Int32u,
                    count: SerialCount::Fixed { value: 1 },
                },
                condition: None,
                flags: IfdFlags {
                    unknown: true,
                    binary: false,
                    list: false,
                    protected: false,
                    avoid: false,
                    priority: None,
                },
                raw_conv: None,
                omitted: Omitted::NONE,
                value_conv: None,
                print_conv: SerialPrintConv::None,
                groups: TagGroups::NONE,
            }],
        },
        SerialEntry {
            serial_index: 8,
            alternatives: &[SerialTag {
                name: "DataOffset",
                format: SerialFormat {
                    format: Fmt::Int32u,
                    count: SerialCount::Fixed { value: 1 },
                },
                condition: None,
                flags: IfdFlags {
                    unknown: true,
                    binary: false,
                    list: false,
                    protected: false,
                    avoid: false,
                    priority: None,
                },
                raw_conv: None,
                omitted: Omitted::NONE,
                value_conv: None,
                print_conv: SerialPrintConv::None,
                groups: TagGroups::NONE,
            }],
        },
        SerialEntry {
            serial_index: 9,
            alternatives: &[SerialTag {
                name: "NumStreams",
                format: SerialFormat {
                    format: Fmt::Int16u,
                    count: SerialCount::Fixed { value: 1 },
                },
                condition: None,
                flags: IfdFlags::NONE,
                raw_conv: None,
                omitted: Omitted::NONE,
                value_conv: None,
                print_conv: SerialPrintConv::None,
                groups: TagGroups::NONE,
            }],
        },
    ],
};
pub static ALL_SERIAL_TABLES: &[&SerialTable] = &[
    &SERIAL_CANON_AFINFO,
    &SERIAL_CANON_AFINFO2,
    &SERIAL_REAL_AUDIOV3,
    &SERIAL_REAL_AUDIOV4,
    &SERIAL_REAL_AUDIOV5,
    &SERIAL_REAL_CONTENTDESCR,
    &SERIAL_REAL_MEDIAPROPS,
    &SERIAL_REAL_PROPERTIES,
];
pub static OMITTED_SERIAL_NATIVE_ROWS: &[OmittedSerialNativeRow] = &[
    OmittedSerialNativeRow {
        module: "Real",
        table: "MediaProps",
        serial_index: 1,
        variant: false,
        alternative: 0,
        name: Some("StreamMaxBitrate"),
        reasons: &["serial_print_conv_expr"],
    },
    OmittedSerialNativeRow {
        module: "Real",
        table: "MediaProps",
        serial_index: 2,
        variant: false,
        alternative: 0,
        name: Some("StreamAvgBitrate"),
        reasons: &["serial_print_conv_expr"],
    },
    OmittedSerialNativeRow {
        module: "Real",
        table: "MediaProps",
        serial_index: 6,
        variant: false,
        alternative: 0,
        name: Some("StreamPreroll"),
        reasons: &["serial_print_conv_expr", "serial_value_conv"],
    },
    OmittedSerialNativeRow {
        module: "Real",
        table: "MediaProps",
        serial_index: 7,
        variant: false,
        alternative: 0,
        name: Some("StreamDuration"),
        reasons: &["serial_print_conv_expr", "serial_value_conv"],
    },
    OmittedSerialNativeRow {
        module: "Real",
        table: "MediaProps",
        serial_index: 21,
        variant: false,
        alternative: 0,
        name: Some("FileInfoProperties"),
        reasons: &["serial_emitter_format", "serial_row_shape"],
    },
    OmittedSerialNativeRow {
        module: "Real",
        table: "Properties",
        serial_index: 0,
        variant: false,
        alternative: 0,
        name: Some("MaxBitrate"),
        reasons: &["serial_print_conv_expr"],
    },
    OmittedSerialNativeRow {
        module: "Real",
        table: "Properties",
        serial_index: 1,
        variant: false,
        alternative: 0,
        name: Some("AvgBitrate"),
        reasons: &["serial_print_conv_expr"],
    },
    OmittedSerialNativeRow {
        module: "Real",
        table: "Properties",
        serial_index: 5,
        variant: false,
        alternative: 0,
        name: Some("Duration"),
        reasons: &["serial_print_conv_expr", "serial_value_conv"],
    },
    OmittedSerialNativeRow {
        module: "Real",
        table: "Properties",
        serial_index: 6,
        variant: false,
        alternative: 0,
        name: Some("Preroll"),
        reasons: &["serial_print_conv_expr", "serial_value_conv"],
    },
    OmittedSerialNativeRow {
        module: "Real",
        table: "Properties",
        serial_index: 10,
        variant: false,
        alternative: 0,
        name: Some("Flags"),
        reasons: &["serial_print_conv"],
    },
];
pub static OMITTED_SERIAL_NATIVE_TABLES: &[OmittedSerialNativeTable] = &[];
