//! `%Image::ExifTool::CanonVRD::Ver1` -- VRD version 1 edit data.
//!
//! Transcribed from CanonVRD.pm 1.41 lines 186-472 by script, not by hand, so
//! that no offset, tag name or PrintConv label is retyped. `%noYes` (line 42)
//! is inlined as `PC_NO_YES`.
//!
//! Entries carry no `Format` in the Perl source only when they take
//! `ProcessBinaryData`'s default of `int8u` (`ToneCurveMode` at 0x113 and
//! `ToneCurveInterpolation` at 0x159); the script fills that default in.

use super::{Conv, Format, Ver1Entry};

const PC_WHITE_BALANCE_ADJ: &[(i64, &str)] = &[
    (0, "Auto"),
    (1, "Daylight"),
    (2, "Cloudy"),
    (3, "Tungsten"),
    (4, "Fluorescent"),
    (5, "Flash"),
    (8, "Shade"),
    (9, "Kelvin"),
    (30, "Manual (Click)"),
    (31, "Shot Settings"),
];

const PC_NO_YES: &[(i64, &str)] = &[(0, "No"), (1, "Yes")];

const PC_RAW_COLOR_ADJ: &[(i64, &str)] = &[(0, "Shot Settings"), (1, "Faithful"), (2, "Custom")];

const PC_TONE_CURVE_PROPERTY: &[(i64, &str)] = &[
    (0, "Shot Settings"),
    (1, "Linear"),
    (2, "Custom 1"),
    (3, "Custom 2"),
    (4, "Custom 3"),
    (5, "Custom 4"),
    (6, "Custom 5"),
];

const PC_TONE_CURVE_MODE: &[(i64, &str)] = &[(0, "RGB"), (1, "Luminance")];

const PC_TONE_CURVE_INTERPOLATION: &[(i64, &str)] = &[(0, "Curve"), (1, "Straight")];

const PC_CROP_ASPECT_RATIO: &[(i64, &str)] = &[
    (0, "Free"),
    (1, "3:2"),
    (2, "2:3"),
    (3, "4:3"),
    (4, "3:4"),
    (5, "A-size Landscape"),
    (6, "A-size Portrait"),
    (7, "Letter-size Landscape"),
    (8, "Letter-size Portrait"),
    (9, "4:5"),
    (10, "5:4"),
    (11, "1:1"),
    (12, "Circle"),
    (65535, "Custom"),
];

const PC_CHECK_MARK: &[(i64, &str)] = &[(0, "Clear"), (1, "1"), (2, "2"), (3, "3")];

const PC_ROTATION: &[(i64, &str)] = &[(0, "0"), (1, "90"), (2, "180"), (3, "270")];

const PC_WORK_COLOR_SPACE: &[(i64, &str)] = &[
    (0, "sRGB"),
    (1, "Adobe RGB"),
    (2, "Wide Gamut RGB"),
    (3, "Apple RGB"),
    (4, "ColorMatch RGB"),
];

pub(super) const VER1: &[Ver1Entry] = &[
    Ver1Entry {
        offset: 0x002,
        name: "VRDVersion",
        format: Format::Int16u,
        count: 1,
        conv: Conv::VrdVersion,
        scale: None,
    },
    Ver1Entry {
        offset: 0x006,
        name: "WBAdjRGGBLevels",
        format: Format::Int16u,
        count: 4,
        conv: Conv::None,
        scale: None,
    },
    Ver1Entry {
        offset: 0x018,
        name: "WhiteBalanceAdj",
        format: Format::Int16u,
        count: 1,
        conv: Conv::Map(PC_WHITE_BALANCE_ADJ),
        scale: None,
    },
    Ver1Entry {
        offset: 0x01a,
        name: "WBAdjColorTemp",
        format: Format::Int16u,
        count: 1,
        conv: Conv::None,
        scale: None,
    },
    Ver1Entry {
        offset: 0x024,
        name: "WBFineTuneActive",
        format: Format::Int16u,
        count: 1,
        conv: Conv::Map(PC_NO_YES),
        scale: None,
    },
    Ver1Entry {
        offset: 0x028,
        name: "WBFineTuneSaturation",
        format: Format::Int16u,
        count: 1,
        conv: Conv::None,
        scale: None,
    },
    Ver1Entry {
        offset: 0x02c,
        name: "WBFineTuneTone",
        format: Format::Int16u,
        count: 1,
        conv: Conv::None,
        scale: None,
    },
    Ver1Entry {
        offset: 0x02e,
        name: "RawColorAdj",
        format: Format::Int16u,
        count: 1,
        conv: Conv::Map(PC_RAW_COLOR_ADJ),
        scale: None,
    },
    Ver1Entry {
        offset: 0x030,
        name: "RawCustomSaturation",
        format: Format::Int32s,
        count: 1,
        conv: Conv::None,
        scale: None,
    },
    Ver1Entry {
        offset: 0x034,
        name: "RawCustomTone",
        format: Format::Int32s,
        count: 1,
        conv: Conv::None,
        scale: None,
    },
    Ver1Entry {
        offset: 0x038,
        name: "RawBrightnessAdj",
        format: Format::Int32s,
        count: 1,
        conv: Conv::Sprintf2f,
        scale: Some(6000.0),
    },
    Ver1Entry {
        offset: 0x03c,
        name: "ToneCurveProperty",
        format: Format::Int16u,
        count: 1,
        conv: Conv::Map(PC_TONE_CURVE_PROPERTY),
        scale: None,
    },
    Ver1Entry {
        offset: 0x07a,
        name: "DynamicRangeMin",
        format: Format::Int16u,
        count: 1,
        conv: Conv::None,
        scale: None,
    },
    Ver1Entry {
        offset: 0x07c,
        name: "DynamicRangeMax",
        format: Format::Int16u,
        count: 1,
        conv: Conv::None,
        scale: None,
    },
    Ver1Entry {
        offset: 0x110,
        name: "ToneCurveActive",
        format: Format::Int16u,
        count: 1,
        conv: Conv::Map(PC_NO_YES),
        scale: None,
    },
    Ver1Entry {
        offset: 0x113,
        name: "ToneCurveMode",
        format: Format::Int8u,
        count: 1,
        conv: Conv::Map(PC_TONE_CURVE_MODE),
        scale: None,
    },
    Ver1Entry {
        offset: 0x114,
        name: "BrightnessAdj",
        format: Format::Int8s,
        count: 1,
        conv: Conv::None,
        scale: None,
    },
    Ver1Entry {
        offset: 0x115,
        name: "ContrastAdj",
        format: Format::Int8s,
        count: 1,
        conv: Conv::None,
        scale: None,
    },
    Ver1Entry {
        offset: 0x116,
        name: "SaturationAdj",
        format: Format::Int16s,
        count: 1,
        conv: Conv::None,
        scale: None,
    },
    Ver1Entry {
        offset: 0x11e,
        name: "ColorToneAdj",
        format: Format::Int32s,
        count: 1,
        conv: Conv::None,
        scale: None,
    },
    Ver1Entry {
        offset: 0x126,
        name: "LuminanceCurvePoints",
        format: Format::Int16u,
        count: 21,
        conv: Conv::ToneCurve,
        scale: None,
    },
    Ver1Entry {
        offset: 0x150,
        name: "LuminanceCurveLimits",
        format: Format::Int16u,
        count: 4,
        conv: Conv::None,
        scale: None,
    },
    Ver1Entry {
        offset: 0x159,
        name: "ToneCurveInterpolation",
        format: Format::Int8u,
        count: 1,
        conv: Conv::Map(PC_TONE_CURVE_INTERPOLATION),
        scale: None,
    },
    Ver1Entry {
        offset: 0x160,
        name: "RedCurvePoints",
        format: Format::Int16u,
        count: 21,
        conv: Conv::ToneCurve,
        scale: None,
    },
    Ver1Entry {
        offset: 0x18a,
        name: "RedCurveLimits",
        format: Format::Int16u,
        count: 4,
        conv: Conv::None,
        scale: None,
    },
    Ver1Entry {
        offset: 0x19a,
        name: "GreenCurvePoints",
        format: Format::Int16u,
        count: 21,
        conv: Conv::ToneCurve,
        scale: None,
    },
    Ver1Entry {
        offset: 0x1c4,
        name: "GreenCurveLimits",
        format: Format::Int16u,
        count: 4,
        conv: Conv::None,
        scale: None,
    },
    Ver1Entry {
        offset: 0x1d4,
        name: "BlueCurvePoints",
        format: Format::Int16u,
        count: 21,
        conv: Conv::ToneCurve,
        scale: None,
    },
    Ver1Entry {
        offset: 0x1fe,
        name: "BlueCurveLimits",
        format: Format::Int16u,
        count: 4,
        conv: Conv::None,
        scale: None,
    },
    Ver1Entry {
        offset: 0x20e,
        name: "RGBCurvePoints",
        format: Format::Int16u,
        count: 21,
        conv: Conv::ToneCurve,
        scale: None,
    },
    Ver1Entry {
        offset: 0x238,
        name: "RGBCurveLimits",
        format: Format::Int16u,
        count: 4,
        conv: Conv::None,
        scale: None,
    },
    Ver1Entry {
        offset: 0x244,
        name: "CropActive",
        format: Format::Int16u,
        count: 1,
        conv: Conv::Map(PC_NO_YES),
        scale: None,
    },
    Ver1Entry {
        offset: 0x246,
        name: "CropLeft",
        format: Format::Int16u,
        count: 1,
        conv: Conv::None,
        scale: None,
    },
    Ver1Entry {
        offset: 0x248,
        name: "CropTop",
        format: Format::Int16u,
        count: 1,
        conv: Conv::None,
        scale: None,
    },
    Ver1Entry {
        offset: 0x24a,
        name: "CropWidth",
        format: Format::Int16u,
        count: 1,
        conv: Conv::None,
        scale: None,
    },
    Ver1Entry {
        offset: 0x24c,
        name: "CropHeight",
        format: Format::Int16u,
        count: 1,
        conv: Conv::None,
        scale: None,
    },
    Ver1Entry {
        offset: 0x25a,
        name: "SharpnessAdj",
        format: Format::Int16u,
        count: 1,
        conv: Conv::None,
        scale: None,
    },
    Ver1Entry {
        offset: 0x260,
        name: "CropAspectRatio",
        format: Format::Int16u,
        count: 1,
        conv: Conv::Map(PC_CROP_ASPECT_RATIO),
        scale: None,
    },
    Ver1Entry {
        offset: 0x262,
        name: "ConstrainedCropWidth",
        format: Format::Float,
        count: 1,
        conv: Conv::Sprintf7g,
        scale: None,
    },
    Ver1Entry {
        offset: 0x266,
        name: "ConstrainedCropHeight",
        format: Format::Float,
        count: 1,
        conv: Conv::Sprintf7g,
        scale: None,
    },
    Ver1Entry {
        offset: 0x26a,
        name: "CheckMark",
        format: Format::Int16u,
        count: 1,
        conv: Conv::Map(PC_CHECK_MARK),
        scale: None,
    },
    Ver1Entry {
        offset: 0x26e,
        name: "Rotation",
        format: Format::Int16u,
        count: 1,
        conv: Conv::Map(PC_ROTATION),
        scale: None,
    },
    Ver1Entry {
        offset: 0x270,
        name: "WorkColorSpace",
        format: Format::Int16u,
        count: 1,
        conv: Conv::Map(PC_WORK_COLOR_SPACE),
        scale: None,
    },
];
