// GENERATED by scripts/gen_canon_custom_functions2.pl from ExifTool's
// Image::ExifTool::CanonCustom::Functions2 table. Do not edit by hand.
//
// The generator hard-errors on any Condition, ValueConv or PrintConv construct
// it has not seen, so an entry here either mirrors ExifTool exactly or the
// generator refused to run.
use super::custom_functions2::{Cf2Arm, Cf2Cond, Cf2Entry, Cf2Print, Cf2PrintConv, Cf2ValueConv};

/// All 100 `%CanonCustom::Functions2` tag ids, in ExifTool's key order.
///
/// Each entry holds its `Condition` arms in ExifTool's own order; the first arm
/// whose condition passes wins, and an arm with no condition always passes.
pub(super) static CUSTOM_FUNCTIONS2: &[Cf2Entry] = &[
    Cf2Entry {
        tag: 0x0101,
        arms: &[
            Cf2Arm {
                name: "ExposureLevelIncrements",
                cond: Cf2Cond::Model(&["1D", "1Ds"]),
                value_convs: &[],
                print_conv: Cf2Print::Scalar(Cf2PrintConv::Map(&[
                    ("0", "1/3-stop set, 1/3-stop comp."),
                    ("1", "1-stop set, 1/3-stop comp."),
                    ("2", "1/2-stop set, 1/2-stop comp."),
                ])),
            },
            Cf2Arm {
                name: "ExposureLevelIncrements",
                cond: Cf2Cond::Always,
                value_convs: &[],
                print_conv: Cf2Print::Scalar(Cf2PrintConv::Map(&[
                    ("0", "1/3 Stop"),
                    ("1", "1/2 Stop"),
                ])),
            },
        ],
    },
    Cf2Entry {
        tag: 0x0102,
        arms: &[Cf2Arm {
            name: "ISOSpeedIncrements",
            cond: Cf2Cond::Always,
            value_convs: &[],
            print_conv: Cf2Print::Scalar(Cf2PrintConv::Map(&[("0", "1/3 Stop"), ("1", "1 Stop")])),
        }],
    },
    Cf2Entry {
        tag: 0x0103,
        arms: &[
            Cf2Arm {
                name: "ISOSpeedRange",
                cond: Cf2Cond::ModelPrefix("1D"),
                value_convs: &[Cf2ValueConv::None, Cf2ValueConv::Iso, Cf2ValueConv::Iso],
                print_conv: Cf2Print::List(&[
                    Cf2PrintConv::Map(&[("0", "Disable"), ("1", "Enable")]),
                    Cf2PrintConv::Round0("Max "),
                    Cf2PrintConv::Round0("Min "),
                ]),
            },
            Cf2Arm {
                name: "ISOExpansion",
                cond: Cf2Cond::Always,
                value_convs: &[],
                print_conv: Cf2Print::Scalar(Cf2PrintConv::Map(&[("0", "Off"), ("1", "On")])),
            },
        ],
    },
    Cf2Entry {
        tag: 0x0104,
        arms: &[Cf2Arm {
            name: "AEBAutoCancel",
            cond: Cf2Cond::Always,
            value_convs: &[],
            print_conv: Cf2Print::Scalar(Cf2PrintConv::Map(&[("0", "On"), ("1", "Off")])),
        }],
    },
    Cf2Entry {
        tag: 0x0105,
        arms: &[Cf2Arm {
            name: "AEBSequence",
            cond: Cf2Cond::Always,
            value_convs: &[],
            print_conv: Cf2Print::Scalar(Cf2PrintConv::Map(&[
                ("0", "0,-,+"),
                ("1", "-,0,+"),
                ("2", "+,0,-"),
            ])),
        }],
    },
    Cf2Entry {
        tag: 0x0106,
        arms: &[
            Cf2Arm {
                name: "AEBShotCount",
                cond: Cf2Cond::Model(&["90D"]),
                value_convs: &[],
                print_conv: Cf2Print::Scalar(Cf2PrintConv::Map(&[
                    ("2", "2 shots"),
                    ("3", "3 shots"),
                    ("5", "5 shots"),
                    ("7", "7 shots"),
                ])),
            },
            Cf2Arm {
                name: "AEBShotCount",
                cond: Cf2Cond::Count(1),
                value_convs: &[],
                print_conv: Cf2Print::Scalar(Cf2PrintConv::Map(&[
                    ("0", "3 shots"),
                    ("1", "2 shots"),
                    ("2", "5 shots"),
                    ("3", "7 shots"),
                ])),
            },
            Cf2Arm {
                name: "AEBShotCount",
                cond: Cf2Cond::Always,
                value_convs: &[],
                print_conv: Cf2Print::Scalar(Cf2PrintConv::Map(&[
                    ("2 1", "2 shots"),
                    ("3 0", "3 shots"),
                    ("5 2", "5 shots"),
                    ("7 3", "7 shots"),
                ])),
            },
        ],
    },
    Cf2Entry {
        tag: 0x0107,
        arms: &[Cf2Arm {
            name: "SpotMeterLinkToAFPoint",
            cond: Cf2Cond::Always,
            value_convs: &[],
            print_conv: Cf2Print::Scalar(Cf2PrintConv::Map(&[
                ("0", "Disable (use center AF point)"),
                ("1", "Enable (use active AF point)"),
            ])),
        }],
    },
    Cf2Entry {
        tag: 0x0108,
        arms: &[Cf2Arm {
            name: "SafetyShift",
            cond: Cf2Cond::Always,
            value_convs: &[],
            print_conv: Cf2Print::Scalar(Cf2PrintConv::Map(&[
                ("0", "Disable"),
                ("1", "Enable (Tv/Av)"),
                ("2", "Enable (ISO speed)"),
            ])),
        }],
    },
    Cf2Entry {
        tag: 0x0109,
        arms: &[
            Cf2Arm {
                name: "UsableShootingModes",
                cond: Cf2Cond::Count(1),
                value_convs: &[],
                print_conv: Cf2Print::Scalar(Cf2PrintConv::Flags),
            },
            Cf2Arm {
                name: "UsableShootingModes",
                cond: Cf2Cond::Always,
                value_convs: &[],
                print_conv: Cf2Print::List(&[
                    Cf2PrintConv::Map(&[("0", "Disable"), ("1", "Enable")]),
                    Cf2PrintConv::Flags,
                ]),
            },
        ],
    },
    Cf2Entry {
        tag: 0x010a,
        arms: &[
            Cf2Arm {
                name: "UsableMeteringModes",
                cond: Cf2Cond::Count(1),
                value_convs: &[],
                print_conv: Cf2Print::Scalar(Cf2PrintConv::Flags),
            },
            Cf2Arm {
                name: "UsableMeteringModes",
                cond: Cf2Cond::Always,
                value_convs: &[],
                print_conv: Cf2Print::List(&[
                    Cf2PrintConv::Map(&[("0", "Disable"), ("1", "Enable")]),
                    Cf2PrintConv::Flags,
                ]),
            },
        ],
    },
    Cf2Entry {
        tag: 0x010b,
        arms: &[Cf2Arm {
            name: "ExposureModeInManual",
            cond: Cf2Cond::Always,
            value_convs: &[],
            print_conv: Cf2Print::Scalar(Cf2PrintConv::Map(&[
                ("0", "Specified metering mode"),
                ("1", "Evaluative metering"),
                ("2", "Partial metering"),
                ("3", "Spot metering"),
                ("4", "Center-weighted average"),
            ])),
        }],
    },
    Cf2Entry {
        tag: 0x010c,
        arms: &[
            Cf2Arm {
                name: "ShutterSpeedRange",
                cond: Cf2Cond::Count(3),
                value_convs: &[
                    Cf2ValueConv::None,
                    Cf2ValueConv::ShutterSpeedStops,
                    Cf2ValueConv::ShutterSpeedStops,
                ],
                print_conv: Cf2Print::List(&[
                    Cf2PrintConv::Map(&[("0", "Disable"), ("1", "Enable")]),
                    Cf2PrintConv::ExposureTime("Hi "),
                    Cf2PrintConv::ExposureTime("Lo "),
                ]),
            },
            Cf2Arm {
                name: "ShutterSpeedRange",
                cond: Cf2Cond::Count(4),
                value_convs: &[
                    Cf2ValueConv::ShutterSpeedLinear,
                    Cf2ValueConv::ShutterSpeedLinear,
                    Cf2ValueConv::ShutterSpeedLinear,
                    Cf2ValueConv::ShutterSpeedLinear,
                ],
                print_conv: Cf2Print::List(&[
                    Cf2PrintConv::ExposureTime("Manual: Hi "),
                    Cf2PrintConv::ExposureTime("Lo "),
                    Cf2PrintConv::ExposureTime("Auto: Hi "),
                    Cf2PrintConv::ExposureTime("Lo "),
                ]),
            },
        ],
    },
    Cf2Entry {
        tag: 0x010d,
        arms: &[
            Cf2Arm {
                name: "ApertureRange",
                cond: Cf2Cond::Count(3),
                value_convs: &[
                    Cf2ValueConv::None,
                    Cf2ValueConv::ApertureStops,
                    Cf2ValueConv::ApertureStops,
                ],
                print_conv: Cf2Print::List(&[
                    Cf2PrintConv::Map(&[("0", "Disable"), ("1", "Enable")]),
                    Cf2PrintConv::TwoSigFigs("Closed "),
                    Cf2PrintConv::TwoSigFigs("Open "),
                ]),
            },
            Cf2Arm {
                name: "ApertureRange",
                cond: Cf2Cond::Count(4),
                value_convs: &[
                    Cf2ValueConv::ApertureLinear,
                    Cf2ValueConv::ApertureLinear,
                    Cf2ValueConv::ApertureLinear,
                    Cf2ValueConv::ApertureLinear,
                ],
                print_conv: Cf2Print::List(&[
                    Cf2PrintConv::TwoSigFigs("Manual: Closed "),
                    Cf2PrintConv::TwoSigFigs("Open "),
                    Cf2PrintConv::TwoSigFigs("Auto: Closed "),
                    Cf2PrintConv::TwoSigFigs("Open "),
                ]),
            },
        ],
    },
    Cf2Entry {
        tag: 0x010e,
        arms: &[Cf2Arm {
            name: "ApplyShootingMeteringMode",
            cond: Cf2Cond::Always,
            value_convs: &[],
            print_conv: Cf2Print::List(&[Cf2PrintConv::Map(&[("0", "Disable"), ("1", "Enable")])]),
        }],
    },
    Cf2Entry {
        tag: 0x010f,
        arms: &[
            Cf2Arm {
                name: "FlashSyncSpeedAv",
                cond: Cf2Cond::Model(&["40D", "1Ds Mark III"]),
                value_convs: &[],
                print_conv: Cf2Print::Scalar(Cf2PrintConv::Map(&[
                    ("0", "Auto"),
                    ("1", "1/250 Fixed"),
                ])),
            },
            Cf2Arm {
                name: "FlashSyncSpeedAv",
                cond: Cf2Cond::Model(&["50D", "60D", "7D"]),
                value_convs: &[],
                print_conv: Cf2Print::Scalar(Cf2PrintConv::Map(&[
                    ("0", "Auto"),
                    ("1", "1/250-1/60 Auto"),
                    ("2", "1/250 Fixed"),
                ])),
            },
            Cf2Arm {
                name: "FlashSyncSpeedAv",
                cond: Cf2Cond::Model(&["450D", "XSi", "Kiss X2", "1000D", "XS", "Kiss F"]),
                value_convs: &[],
                print_conv: Cf2Print::Scalar(Cf2PrintConv::Map(&[
                    ("0", "Auto"),
                    ("1", "1/200 Fixed"),
                ])),
            },
            Cf2Arm {
                name: "FlashSyncSpeedAv",
                cond: Cf2Cond::Model(&["EOS-1D Mark III", "EOS-1Ds Mark III"]),
                value_convs: &[],
                print_conv: Cf2Print::Scalar(Cf2PrintConv::Map(&[
                    ("0", "Auto"),
                    ("1", "1/300 Fixed"),
                ])),
            },
            Cf2Arm {
                name: "FlashSyncSpeedAv",
                cond: Cf2Cond::Model(&["EOS-1D Mark IV"]),
                value_convs: &[],
                print_conv: Cf2Print::Scalar(Cf2PrintConv::Map(&[
                    ("0", "Auto"),
                    ("1", "1/300-1/60 Auto"),
                    ("2", "1/300 Fixed"),
                ])),
            },
            Cf2Arm {
                name: "FlashSyncSpeedAv",
                cond: Cf2Cond::Always,
                value_convs: &[],
                print_conv: Cf2Print::Scalar(Cf2PrintConv::Map(&[
                    ("0", "Auto"),
                    ("1", "1/200-1/60 Auto"),
                    ("2", "1/200 Fixed"),
                ])),
            },
        ],
    },
    Cf2Entry {
        tag: 0x0110,
        arms: &[Cf2Arm {
            name: "AEMicroadjustment",
            cond: Cf2Cond::Always,
            value_convs: &[],
            print_conv: Cf2Print::List(&[Cf2PrintConv::Map(&[("0", "Disable"), ("1", "Enable")])]),
        }],
    },
    Cf2Entry {
        tag: 0x0111,
        arms: &[Cf2Arm {
            name: "FEMicroadjustment",
            cond: Cf2Cond::Always,
            value_convs: &[],
            print_conv: Cf2Print::List(&[Cf2PrintConv::Map(&[("0", "Disable"), ("1", "Enable")])]),
        }],
    },
    Cf2Entry {
        tag: 0x0112,
        arms: &[
            Cf2Arm {
                name: "SameExposureForNewAperture",
                cond: Cf2Cond::Always,
                value_convs: &[],
                print_conv: Cf2Print::Scalar(Cf2PrintConv::Map(&[
                    ("0", "Disable"),
                    ("1", "ISO Speed"),
                    ("2", "Shutter Speed"),
                ])),
            },
            Cf2Arm {
                name: "SameExposureForNewAperture",
                cond: Cf2Cond::Always,
                value_convs: &[],
                print_conv: Cf2Print::Scalar(Cf2PrintConv::Map(&[
                    ("0", "Disable"),
                    ("1", "ISO Speed"),
                    ("2", "ISO Speed/Shutter Speed"),
                    ("3", "Shutter Speed"),
                ])),
            },
        ],
    },
    Cf2Entry {
        tag: 0x0113,
        arms: &[Cf2Arm {
            name: "ExposureCompAutoCancel",
            cond: Cf2Cond::Always,
            value_convs: &[],
            print_conv: Cf2Print::Scalar(Cf2PrintConv::Map(&[("0", "Enable"), ("1", "Disable")])),
        }],
    },
    Cf2Entry {
        tag: 0x0114,
        arms: &[Cf2Arm {
            name: "AELockMeterModeAfterFocus",
            cond: Cf2Cond::Always,
            value_convs: &[],
            print_conv: Cf2Print::Scalar(Cf2PrintConv::Bitmask(&[
                (0, "Evaluative"),
                (1, "Partial"),
                (2, "Spot"),
                (3, "Center-weighted"),
            ])),
        }],
    },
    Cf2Entry {
        tag: 0x0201,
        arms: &[Cf2Arm {
            name: "LongExposureNoiseReduction",
            cond: Cf2Cond::Always,
            value_convs: &[],
            print_conv: Cf2Print::Scalar(Cf2PrintConv::Map(&[
                ("0", "Off"),
                ("1", "Auto"),
                ("2", "On"),
            ])),
        }],
    },
    Cf2Entry {
        tag: 0x0202,
        arms: &[
            Cf2Arm {
                name: "HighISONoiseReduction",
                cond: Cf2Cond::Model(&[
                    "50D",
                    "60D",
                    "5D Mark II",
                    "7D",
                    "500D",
                    "T1i",
                    "Kiss X3",
                    "550D",
                    "T2i",
                    "Kiss X4",
                    "600D",
                    "T3i",
                    "Kiss X5",
                    "1100D",
                    "T3",
                    "Kiss X50",
                ]),
                value_convs: &[],
                print_conv: Cf2Print::Scalar(Cf2PrintConv::Map(&[
                    ("0", "Standard"),
                    ("1", "Low"),
                    ("2", "Strong"),
                    ("3", "Off"),
                ])),
            },
            Cf2Arm {
                name: "HighISONoiseReduction",
                cond: Cf2Cond::Always,
                value_convs: &[],
                print_conv: Cf2Print::Scalar(Cf2PrintConv::Map(&[("0", "Off"), ("1", "On")])),
            },
        ],
    },
    Cf2Entry {
        tag: 0x0203,
        arms: &[Cf2Arm {
            name: "HighlightTonePriority",
            cond: Cf2Cond::Always,
            value_convs: &[],
            print_conv: Cf2Print::Scalar(Cf2PrintConv::Map(&[("0", "Disable"), ("1", "Enable")])),
        }],
    },
    Cf2Entry {
        tag: 0x0204,
        arms: &[
            Cf2Arm {
                name: "AutoLightingOptimizer",
                cond: Cf2Cond::Model(&[
                    "50D",
                    "5D Mark II",
                    "500D",
                    "T1i",
                    "Kiss X3",
                    "1D Mark IV",
                ]),
                value_convs: &[],
                print_conv: Cf2Print::Scalar(Cf2PrintConv::Map(&[
                    ("0", "Standard"),
                    ("1", "Low"),
                    ("2", "Strong"),
                    ("3", "Disable"),
                ])),
            },
            Cf2Arm {
                name: "AutoLightingOptimizer",
                cond: Cf2Cond::Always,
                value_convs: &[],
                print_conv: Cf2Print::Scalar(Cf2PrintConv::Map(&[
                    ("0", "Enable"),
                    ("1", "Disable"),
                ])),
            },
        ],
    },
    Cf2Entry {
        tag: 0x0304,
        arms: &[Cf2Arm {
            name: "ETTLII",
            cond: Cf2Cond::Always,
            value_convs: &[],
            print_conv: Cf2Print::Scalar(Cf2PrintConv::Map(&[
                ("0", "Evaluative"),
                ("1", "Average"),
            ])),
        }],
    },
    Cf2Entry {
        tag: 0x0305,
        arms: &[Cf2Arm {
            name: "ShutterCurtainSync",
            cond: Cf2Cond::Always,
            value_convs: &[],
            print_conv: Cf2Print::Scalar(Cf2PrintConv::Map(&[
                ("0", "1st-curtain sync"),
                ("1", "2nd-curtain sync"),
            ])),
        }],
    },
    Cf2Entry {
        tag: 0x0306,
        arms: &[Cf2Arm {
            name: "FlashFiring",
            cond: Cf2Cond::Always,
            value_convs: &[],
            print_conv: Cf2Print::Scalar(Cf2PrintConv::Map(&[
                ("0", "Fires"),
                ("1", "Does not fire"),
            ])),
        }],
    },
    Cf2Entry {
        tag: 0x0407,
        arms: &[Cf2Arm {
            name: "ViewInfoDuringExposure",
            cond: Cf2Cond::Always,
            value_convs: &[],
            print_conv: Cf2Print::Scalar(Cf2PrintConv::Map(&[("0", "Disable"), ("1", "Enable")])),
        }],
    },
    Cf2Entry {
        tag: 0x0408,
        arms: &[Cf2Arm {
            name: "LCDIlluminationDuringBulb",
            cond: Cf2Cond::Always,
            value_convs: &[],
            print_conv: Cf2Print::Scalar(Cf2PrintConv::Map(&[("0", "Off"), ("1", "On")])),
        }],
    },
    Cf2Entry {
        tag: 0x0409,
        arms: &[
            Cf2Arm {
                name: "InfoButtonWhenShooting",
                cond: Cf2Cond::Model(&["1D Mark III", "1Ds Mark III"]),
                value_convs: &[],
                print_conv: Cf2Print::Scalar(Cf2PrintConv::Map(&[
                    ("0", "Displays camera settings"),
                    ("1", "Displays shooting functions"),
                ])),
            },
            Cf2Arm {
                name: "InfoButtonWhenShooting",
                cond: Cf2Cond::Always,
                value_convs: &[],
                print_conv: Cf2Print::Scalar(Cf2PrintConv::Map(&[
                    ("0", "Displays shooting functions"),
                    ("1", "Displays camera settings"),
                ])),
            },
        ],
    },
    Cf2Entry {
        tag: 0x040a,
        arms: &[Cf2Arm {
            name: "ViewfinderWarnings",
            cond: Cf2Cond::Always,
            value_convs: &[],
            print_conv: Cf2Print::Scalar(Cf2PrintConv::Bitmask(&[
                (0, "Monochrome"),
                (1, "WB corrected"),
                (2, "One-touch image quality"),
                (3, "ISO expansion"),
                (4, "Spot metering"),
                (6, "Noise reduction"),
                (7, "HDR"),
            ])),
        }],
    },
    Cf2Entry {
        tag: 0x040b,
        arms: &[Cf2Arm {
            name: "LVShootingAreaDisplay",
            cond: Cf2Cond::Always,
            value_convs: &[],
            print_conv: Cf2Print::Scalar(Cf2PrintConv::Map(&[("0", "Masked"), ("1", "Outlined")])),
        }],
    },
    Cf2Entry {
        tag: 0x040c,
        arms: &[Cf2Arm {
            name: "LVShootingAreaDisplay",
            cond: Cf2Cond::Always,
            value_convs: &[],
            print_conv: Cf2Print::Scalar(Cf2PrintConv::Map(&[("0", "Masked"), ("1", "Outlined")])),
        }],
    },
    Cf2Entry {
        tag: 0x0501,
        arms: &[Cf2Arm {
            name: "USMLensElectronicMF",
            cond: Cf2Cond::Always,
            value_convs: &[],
            print_conv: Cf2Print::Scalar(Cf2PrintConv::Map(&[
                ("0", "Enable after one-shot AF"),
                ("1", "Disable after one-shot AF"),
                ("2", "Disable in AF mode"),
            ])),
        }],
    },
    Cf2Entry {
        tag: 0x0502,
        arms: &[Cf2Arm {
            name: "AIServoTrackingSensitivity",
            cond: Cf2Cond::Always,
            value_convs: &[],
            print_conv: Cf2Print::Scalar(Cf2PrintConv::Map(&[
                ("-2", "Slow"),
                ("-1", "Medium Slow"),
                ("0", "Standard"),
                ("1", "Medium Fast"),
                ("2", "Fast"),
            ])),
        }],
    },
    Cf2Entry {
        tag: 0x0503,
        arms: &[Cf2Arm {
            name: "AIServoImagePriority",
            cond: Cf2Cond::Always,
            value_convs: &[],
            print_conv: Cf2Print::Scalar(Cf2PrintConv::Map(&[
                ("0", "1: AF, 2: Tracking"),
                ("1", "1: AF, 2: Drive speed"),
                ("2", "1: Release, 2: Drive speed"),
                ("3", "1: Release, 2: Tracking"),
            ])),
        }],
    },
    Cf2Entry {
        tag: 0x0504,
        arms: &[Cf2Arm {
            name: "AIServoTrackingMethod",
            cond: Cf2Cond::Always,
            value_convs: &[],
            print_conv: Cf2Print::Scalar(Cf2PrintConv::Map(&[
                ("0", "Main focus point priority"),
                ("1", "Continuous AF track priority"),
            ])),
        }],
    },
    Cf2Entry {
        tag: 0x0505,
        arms: &[Cf2Arm {
            name: "LensDriveNoAF",
            cond: Cf2Cond::Always,
            value_convs: &[],
            print_conv: Cf2Print::Scalar(Cf2PrintConv::Map(&[
                ("0", "Focus search on"),
                ("1", "Focus search off"),
            ])),
        }],
    },
    Cf2Entry {
        tag: 0x0506,
        arms: &[Cf2Arm {
            name: "LensAFStopButton",
            cond: Cf2Cond::Always,
            value_convs: &[],
            print_conv: Cf2Print::Scalar(Cf2PrintConv::Map(&[
                ("0", "AF stop"),
                ("1", "AF start"),
                ("2", "AE lock"),
                ("3", "AF point: M->Auto/Auto->ctr"),
                ("4", "One Shot <-> AI servo"),
                ("5", "IS start"),
                ("6", "Switch to registered AF point"),
                ("7", "Spot AF"),
            ])),
        }],
    },
    Cf2Entry {
        tag: 0x0507,
        arms: &[Cf2Arm {
            name: "AFMicroadjustment",
            cond: Cf2Cond::Always,
            value_convs: &[],
            print_conv: Cf2Print::List(&[Cf2PrintConv::Map(&[
                ("0", "Disable"),
                ("1", "Adjust all by same amount"),
                ("2", "Adjust by lens"),
            ])]),
        }],
    },
    Cf2Entry {
        tag: 0x0508,
        arms: &[
            Cf2Arm {
                name: "AFPointAreaExpansion",
                cond: Cf2Cond::Model(&["5D Mark II"]),
                value_convs: &[],
                print_conv: Cf2Print::Scalar(Cf2PrintConv::Map(&[
                    ("0", "Disable"),
                    ("1", "Enable"),
                ])),
            },
            Cf2Arm {
                name: "AFPointAreaExpansion",
                cond: Cf2Cond::Model(&["1Ds Mark III"]),
                value_convs: &[],
                print_conv: Cf2Print::Scalar(Cf2PrintConv::Map(&[
                    ("0", "Disable"),
                    ("1", "Enable (left/right Assist AF points)"),
                    ("2", "Enable (surrounding Assist AF points)"),
                ])),
            },
            Cf2Arm {
                name: "AFPointAreaExpansion",
                cond: Cf2Cond::Always,
                value_convs: &[],
                print_conv: Cf2Print::Scalar(Cf2PrintConv::Map(&[
                    ("0", "Disable"),
                    ("1", "Left/right AF points"),
                    ("2", "Surrounding AF points"),
                    ("3", "All 45 points area"),
                ])),
            },
        ],
    },
    Cf2Entry {
        tag: 0x0509,
        arms: &[
            Cf2Arm {
                name: "SelectableAFPoint",
                cond: Cf2Cond::Model(&["1D Mark IV"]),
                value_convs: &[],
                print_conv: Cf2Print::Scalar(Cf2PrintConv::Map(&[
                    ("0", "45 points"),
                    ("1", "19 points"),
                    ("2", "11 points"),
                    ("3", "Inner 9 points"),
                    ("4", "Outer 9 points"),
                ])),
            },
            Cf2Arm {
                name: "SelectableAFPoint",
                cond: Cf2Cond::Always,
                value_convs: &[],
                print_conv: Cf2Print::Scalar(Cf2PrintConv::Map(&[
                    ("0", "19 points"),
                    ("1", "Inner 9 points"),
                    ("2", "Outer 9 points"),
                    ("3", "19 Points, Multi-controller selectable"),
                    ("4", "Inner 9 Points, Multi-controller selectable"),
                    ("5", "Outer 9 Points, Multi-controller selectable"),
                ])),
            },
        ],
    },
    Cf2Entry {
        tag: 0x050a,
        arms: &[
            Cf2Arm {
                name: "SwitchToRegisteredAFPoint",
                cond: Cf2Cond::Model(&["1D Mark IV"]),
                value_convs: &[],
                print_conv: Cf2Print::Scalar(Cf2PrintConv::Map(&[
                    ("0", "Disable"),
                    ("1", "Switch with multi-controller"),
                    ("2", "Only while AEL is pressed"),
                ])),
            },
            Cf2Arm {
                name: "SwitchToRegisteredAFPoint",
                cond: Cf2Cond::Always,
                value_convs: &[],
                print_conv: Cf2Print::Scalar(Cf2PrintConv::Map(&[
                    ("0", "Disable"),
                    ("1", "Enable"),
                ])),
            },
        ],
    },
    Cf2Entry {
        tag: 0x050b,
        arms: &[Cf2Arm {
            name: "AFPointAutoSelection",
            cond: Cf2Cond::Always,
            value_convs: &[],
            print_conv: Cf2Print::Scalar(Cf2PrintConv::Map(&[
                ("0", "Control-direct:disable/Main:enable"),
                ("1", "Control-direct:disable/Main:disable"),
                ("2", "Control-direct:enable/Main:enable"),
            ])),
        }],
    },
    Cf2Entry {
        tag: 0x050c,
        arms: &[
            Cf2Arm {
                name: "AFPointDisplayDuringFocus",
                cond: Cf2Cond::Model(&["1D"]),
                value_convs: &[],
                print_conv: Cf2Print::Scalar(Cf2PrintConv::Map(&[
                    ("0", "On"),
                    ("1", "Off"),
                    ("2", "On (when focus achieved)"),
                ])),
            },
            Cf2Arm {
                name: "AFPointDisplayDuringFocus",
                cond: Cf2Cond::Always,
                value_convs: &[],
                print_conv: Cf2Print::Scalar(Cf2PrintConv::Map(&[
                    ("0", "Selected (constant)"),
                    ("1", "All (constant)"),
                    ("2", "Selected (pre-AF, focused)"),
                    ("3", "Selected (focused)"),
                    ("4", "Disable display"),
                ])),
            },
        ],
    },
    Cf2Entry {
        tag: 0x050d,
        arms: &[Cf2Arm {
            name: "AFPointBrightness",
            cond: Cf2Cond::Always,
            value_convs: &[],
            print_conv: Cf2Print::Scalar(Cf2PrintConv::Map(&[("0", "Normal"), ("1", "Brighter")])),
        }],
    },
    Cf2Entry {
        tag: 0x050e,
        arms: &[
            Cf2Arm {
                name: "AFAssistBeam",
                cond: Cf2Cond::Model(&["1D Mark IV", "6D"]),
                value_convs: &[],
                print_conv: Cf2Print::Scalar(Cf2PrintConv::Map(&[
                    ("0", "Emits"),
                    ("1", "Does not emit"),
                    ("2", "IR AF assist beam only"),
                ])),
            },
            Cf2Arm {
                name: "AFAssistBeam",
                cond: Cf2Cond::Always,
                value_convs: &[],
                print_conv: Cf2Print::Scalar(Cf2PrintConv::Map(&[
                    ("0", "Emits"),
                    ("1", "Does not emit"),
                    ("2", "Only ext. flash emits"),
                    ("3", "IR AF assist beam only"),
                ])),
            },
        ],
    },
    Cf2Entry {
        tag: 0x050f,
        arms: &[
            Cf2Arm {
                name: "AFPointSelectionMethod",
                cond: Cf2Cond::ModelNot(&["60D"]),
                value_convs: &[],
                print_conv: Cf2Print::Scalar(Cf2PrintConv::Map(&[
                    ("0", "Normal"),
                    ("1", "Multi-controller direct"),
                    ("2", "Quick Control Dial direct"),
                ])),
            },
            Cf2Arm {
                name: "AFPointSelectionMethod",
                cond: Cf2Cond::Always,
                value_convs: &[],
                print_conv: Cf2Print::Scalar(Cf2PrintConv::Map(&[
                    (
                        "0",
                        "AF point button: Activate AF Sel; Rear dial: Select AF points",
                    ),
                    (
                        "1",
                        "AF point button: Auto selection; Rear dial: Manual selection",
                    ),
                ])),
            },
        ],
    },
    Cf2Entry {
        tag: 0x0510,
        arms: &[
            Cf2Arm {
                name: "VFDisplayIllumination",
                cond: Cf2Cond::Model(&["7D"]),
                value_convs: &[],
                print_conv: Cf2Print::Scalar(Cf2PrintConv::Map(&[
                    ("0", "Auto"),
                    ("1", "Enable"),
                    ("2", "Disable"),
                ])),
            },
            Cf2Arm {
                name: "SuperimposedDisplay",
                cond: Cf2Cond::Always,
                value_convs: &[],
                print_conv: Cf2Print::Scalar(Cf2PrintConv::Map(&[("0", "On"), ("1", "Off")])),
            },
        ],
    },
    Cf2Entry {
        tag: 0x0511,
        arms: &[
            Cf2Arm {
                name: "AFDuringLiveView",
                cond: Cf2Cond::Model(&["40D"]),
                value_convs: &[],
                print_conv: Cf2Print::Scalar(Cf2PrintConv::Map(&[
                    ("0", "Disable"),
                    ("1", "Enable"),
                ])),
            },
            Cf2Arm {
                name: "AFDuringLiveView",
                cond: Cf2Cond::Always,
                value_convs: &[],
                print_conv: Cf2Print::Scalar(Cf2PrintConv::Map(&[
                    ("0", "Disable"),
                    ("1", "Quick mode"),
                    ("2", "Live mode"),
                ])),
            },
        ],
    },
    Cf2Entry {
        tag: 0x0512,
        arms: &[Cf2Arm {
            name: "SelectAFAreaSelectMode",
            cond: Cf2Cond::Always,
            value_convs: &[],
            print_conv: Cf2Print::List(&[
                Cf2PrintConv::Map(&[
                    ("0", "Disable"),
                    ("1", "Enable"),
                    ("2", "Register"),
                    ("3", "Select AF-modes"),
                ]),
                Cf2PrintConv::Flags,
            ]),
        }],
    },
    Cf2Entry {
        tag: 0x0513,
        arms: &[Cf2Arm {
            name: "ManualAFPointSelectPattern",
            cond: Cf2Cond::Always,
            value_convs: &[],
            print_conv: Cf2Print::Scalar(Cf2PrintConv::Map(&[
                ("0", "Stops at AF area edges"),
                ("1", "Continuous"),
            ])),
        }],
    },
    Cf2Entry {
        tag: 0x0514,
        arms: &[Cf2Arm {
            name: "DisplayAllAFPoints",
            cond: Cf2Cond::Always,
            value_convs: &[],
            print_conv: Cf2Print::Scalar(Cf2PrintConv::Map(&[("0", "Enable"), ("1", "Disable")])),
        }],
    },
    Cf2Entry {
        tag: 0x0515,
        arms: &[Cf2Arm {
            name: "FocusDisplayAIServoAndMF",
            cond: Cf2Cond::Always,
            value_convs: &[],
            print_conv: Cf2Print::Scalar(Cf2PrintConv::Map(&[("0", "Enable"), ("1", "Disable")])),
        }],
    },
    Cf2Entry {
        tag: 0x0516,
        arms: &[Cf2Arm {
            name: "OrientationLinkedAFPoint",
            cond: Cf2Cond::Always,
            value_convs: &[],
            print_conv: Cf2Print::Scalar(Cf2PrintConv::Map(&[
                ("0", "Same for vertical and horizontal"),
                ("1", "Select different AF points"),
            ])),
        }],
    },
    Cf2Entry {
        tag: 0x0517,
        arms: &[Cf2Arm {
            name: "MultiControllerWhileMetering",
            cond: Cf2Cond::Always,
            value_convs: &[],
            print_conv: Cf2Print::Scalar(Cf2PrintConv::Map(&[
                ("0", "Off"),
                ("1", "AF point selection"),
            ])),
        }],
    },
    Cf2Entry {
        tag: 0x0518,
        arms: &[Cf2Arm {
            name: "AccelerationTracking",
            cond: Cf2Cond::Always,
            value_convs: &[],
            print_conv: Cf2Print::None,
        }],
    },
    Cf2Entry {
        tag: 0x0519,
        arms: &[Cf2Arm {
            name: "AIServoFirstImagePriority",
            cond: Cf2Cond::Always,
            value_convs: &[],
            print_conv: Cf2Print::Scalar(Cf2PrintConv::Map(&[
                ("-1", "Release priority"),
                ("0", "Equal priority"),
                ("1", "Focus priority"),
            ])),
        }],
    },
    Cf2Entry {
        tag: 0x051a,
        arms: &[Cf2Arm {
            name: "AIServoSecondImagePriority",
            cond: Cf2Cond::Always,
            value_convs: &[],
            print_conv: Cf2Print::Scalar(Cf2PrintConv::Map(&[
                ("-1", "Shooting speed priority"),
                ("0", "Equal priority"),
                ("1", "Focus priority"),
            ])),
        }],
    },
    Cf2Entry {
        tag: 0x051b,
        arms: &[Cf2Arm {
            name: "AFAreaSelectMethod",
            cond: Cf2Cond::Always,
            value_convs: &[],
            print_conv: Cf2Print::Scalar(Cf2PrintConv::Map(&[
                ("0", "AF area selection button"),
                ("1", "Main dial"),
            ])),
        }],
    },
    Cf2Entry {
        tag: 0x051c,
        arms: &[Cf2Arm {
            name: "AutoAFPointColorTracking",
            cond: Cf2Cond::Always,
            value_convs: &[],
            print_conv: Cf2Print::Scalar(Cf2PrintConv::Map(&[
                ("0", "On-Shot AF only"),
                ("1", "Disable"),
            ])),
        }],
    },
    Cf2Entry {
        tag: 0x051d,
        arms: &[Cf2Arm {
            name: "VFDisplayIllumination",
            cond: Cf2Cond::Always,
            value_convs: &[],
            print_conv: Cf2Print::List(&[
                Cf2PrintConv::Map(&[("0", "Auto"), ("1", "Enable"), ("2", "Disable")]),
                Cf2PrintConv::Map(&[("0", "Non-illuminated"), ("1", "Illuminated")]),
            ]),
        }],
    },
    Cf2Entry {
        tag: 0x051e,
        arms: &[Cf2Arm {
            name: "InitialAFPointAIServoAF",
            cond: Cf2Cond::Always,
            value_convs: &[],
            print_conv: Cf2Print::Scalar(Cf2PrintConv::Map(&[
                ("0", "Auto"),
                ("1", "Initial AF point selected"),
                ("2", "Manual AF point"),
            ])),
        }],
    },
    Cf2Entry {
        tag: 0x060f,
        arms: &[Cf2Arm {
            name: "MirrorLockup",
            cond: Cf2Cond::Always,
            value_convs: &[],
            print_conv: Cf2Print::Scalar(Cf2PrintConv::Map(&[
                ("0", "Disable"),
                ("1", "Enable"),
                ("2", "Enable: Down with Set"),
            ])),
        }],
    },
    Cf2Entry {
        tag: 0x0610,
        arms: &[
            Cf2Arm {
                name: "ContinuousShootingSpeed",
                cond: Cf2Cond::Count(6),
                value_convs: &[],
                print_conv: Cf2Print::List(&[
                    Cf2PrintConv::Map(&[("0", "Disable"), ("1", "Enable")]),
                    Cf2PrintConv::Interpolate("Hi ", ""),
                    Cf2PrintConv::Interpolate("Cont ", ""),
                    Cf2PrintConv::Interpolate("Lo ", ""),
                    Cf2PrintConv::Interpolate("Soft ", ""),
                    Cf2PrintConv::Interpolate("Soft LS ", ""),
                ]),
            },
            Cf2Arm {
                name: "ContinuousShootingSpeed",
                cond: Cf2Cond::Count(5),
                value_convs: &[],
                print_conv: Cf2Print::List(&[
                    Cf2PrintConv::Interpolate("Hi ", ""),
                    Cf2PrintConv::Interpolate("Cont ", ""),
                    Cf2PrintConv::Interpolate("Lo ", ""),
                    Cf2PrintConv::Interpolate("Soft ", ""),
                    Cf2PrintConv::Interpolate("Soft LS ", ""),
                ]),
            },
            Cf2Arm {
                name: "ContinuousShootingSpeed",
                cond: Cf2Cond::Always,
                value_convs: &[],
                print_conv: Cf2Print::List(&[
                    Cf2PrintConv::Map(&[("0", "Disable"), ("1", "Enable")]),
                    Cf2PrintConv::Interpolate("Hi ", ""),
                    Cf2PrintConv::Interpolate("Lo ", ""),
                ]),
            },
        ],
    },
    Cf2Entry {
        tag: 0x0611,
        arms: &[Cf2Arm {
            name: "ContinuousShotLimit",
            cond: Cf2Cond::Always,
            value_convs: &[],
            print_conv: Cf2Print::List(&[
                Cf2PrintConv::Map(&[("0", "Disable"), ("1", "Enable")]),
                Cf2PrintConv::Interpolate("", " shots"),
            ]),
        }],
    },
    Cf2Entry {
        tag: 0x0612,
        arms: &[
            Cf2Arm {
                name: "RestrictDriveModes",
                cond: Cf2Cond::Count(1),
                value_convs: &[],
                print_conv: Cf2Print::Scalar(Cf2PrintConv::Flags),
            },
            Cf2Arm {
                name: "RestrictDriveModes",
                cond: Cf2Cond::Always,
                value_convs: &[],
                print_conv: Cf2Print::List(&[
                    Cf2PrintConv::Map(&[("0", "Disable"), ("1", "Enable")]),
                    Cf2PrintConv::Flags,
                ]),
            },
        ],
    },
    Cf2Entry {
        tag: 0x0701,
        arms: &[
            Cf2Arm {
                name: "Shutter-AELock",
                cond: Cf2Cond::Model(&[
                    "1000D", "XS", "Kiss F", "500D", "T1i", "Kiss X3", "550D", "T2i", "Kiss X4",
                    "600D", "T3i", "Kiss X5", "1100D", "T3", "Kiss X50",
                ]),
                value_convs: &[],
                print_conv: Cf2Print::Scalar(Cf2PrintConv::Map(&[
                    ("0", "AF/AE lock"),
                    ("1", "AE lock/AF"),
                    ("2", "AF/AF lock, No AE lock"),
                    ("3", "AE/AF, No AE lock"),
                ])),
            },
            Cf2Arm {
                name: "Shutter-AELock",
                cond: Cf2Cond::Count(2),
                value_convs: &[],
                print_conv: Cf2Print::Scalar(Cf2PrintConv::Map(&[
                    ("0 0", "AF/AE lock"),
                    ("1 0", "AE lock/AF"),
                    ("2 0", "AF/AF lock, No AE lock"),
                    ("3 0", "AE/AF, No AE lock"),
                ])),
            },
            Cf2Arm {
                name: "AFAndMeteringButtons",
                cond: Cf2Cond::Model(&["60D"]),
                value_convs: &[],
                print_conv: Cf2Print::Scalar(Cf2PrintConv::Map(&[
                    ("0", "Metering start"),
                    ("1", "Metering + AF start"),
                    ("2", "AE lock"),
                    ("3", "AF stop"),
                    ("4", "No function"),
                ])),
            },
            Cf2Arm {
                name: "ShutterButtonAFOnButton",
                cond: Cf2Cond::Always,
                value_convs: &[],
                print_conv: Cf2Print::Scalar(Cf2PrintConv::Map(&[
                    ("0", "Metering + AF start"),
                    ("1", "Metering + AF start/AF stop"),
                    ("2", "Metering start/Meter + AF start"),
                    ("3", "AE lock/Metering + AF start"),
                    ("4", "Metering + AF start/disable"),
                ])),
            },
        ],
    },
    Cf2Entry {
        tag: 0x0702,
        arms: &[Cf2Arm {
            name: "AFOnAELockButtonSwitch",
            cond: Cf2Cond::Always,
            value_convs: &[],
            print_conv: Cf2Print::Scalar(Cf2PrintConv::Map(&[("0", "Disable"), ("1", "Enable")])),
        }],
    },
    Cf2Entry {
        tag: 0x0703,
        arms: &[Cf2Arm {
            name: "QuickControlDialInMeter",
            cond: Cf2Cond::Always,
            value_convs: &[],
            print_conv: Cf2Print::Scalar(Cf2PrintConv::Map(&[
                ("0", "Exposure comp/Aperture"),
                ("1", "AF point selection"),
                ("2", "ISO speed"),
                ("3", "AF point selection swapped with Exposure comp"),
                ("4", "ISO speed swapped with Exposure comp"),
            ])),
        }],
    },
    Cf2Entry {
        tag: 0x0704,
        arms: &[
            Cf2Arm {
                name: "SetButtonWhenShooting",
                cond: Cf2Cond::Model(&["40D", "50D", "5D Mark II"]),
                value_convs: &[],
                print_conv: Cf2Print::Scalar(Cf2PrintConv::Map(&[
                    ("0", "Normal (disabled)"),
                    ("1", "Image quality"),
                    ("2", "Picture style"),
                    ("3", "Menu display"),
                    ("4", "Image playback"),
                    ("5", "Quick control screen"),
                    ("6", "Record movie (Live View)"),
                ])),
            },
            Cf2Arm {
                name: "SetButtonWhenShooting",
                cond: Cf2Cond::Model(&["60D"]),
                value_convs: &[],
                print_conv: Cf2Print::Scalar(Cf2PrintConv::Map(&[
                    ("0", "Normal (disabled)"),
                    ("1", "Image quality"),
                    ("2", "Picture style"),
                    ("3", "White balance"),
                    ("4", "Flash exposure compensation"),
                    ("5", "Viewfinder leveling gauge"),
                ])),
            },
            Cf2Arm {
                name: "SetButtonWhenShooting",
                cond: Cf2Cond::Model(&[
                    "450D", "XSi", "Kiss X2", "550D", "T2i", "Kiss X4", "600D", "T3i", "Kiss X5",
                ]),
                value_convs: &[],
                print_conv: Cf2Print::Scalar(Cf2PrintConv::Map(&[
                    ("0", "Normal (disabled)"),
                    ("1", "Image quality"),
                    ("2", "Flash exposure compensation"),
                    ("3", "LCD monitor On/Off"),
                    ("4", "Menu display"),
                    ("5", "ISO speed"),
                ])),
            },
            Cf2Arm {
                name: "SetButtonWhenShooting",
                cond: Cf2Cond::Model(&["1100D", "T3", "Kiss X50"]),
                value_convs: &[],
                print_conv: Cf2Print::Scalar(Cf2PrintConv::Map(&[
                    ("0", "Normal (disabled)"),
                    ("1", "Image quality"),
                    ("2", "Flash exposure compensation"),
                    ("3", "LCD monitor On/Off"),
                    ("4", "Menu display"),
                    ("5", "Depth-of-field preview"),
                ])),
            },
            Cf2Arm {
                name: "SetButtonWhenShooting",
                cond: Cf2Cond::Model(&["1000D", "XS", "Kiss F"]),
                value_convs: &[],
                print_conv: Cf2Print::Scalar(Cf2PrintConv::Map(&[
                    ("0", "LCD monitor On/Off"),
                    ("1", "Image quality"),
                    ("2", "Flash exposure compensation"),
                    ("3", "Menu display"),
                    ("4", "Disabled"),
                ])),
            },
            Cf2Arm {
                name: "SetButtonWhenShooting",
                cond: Cf2Cond::Model(&["500D", "T1i", "Kiss X3"]),
                value_convs: &[],
                print_conv: Cf2Print::Scalar(Cf2PrintConv::Map(&[
                    ("0", "Quick control screen"),
                    ("1", "Image quality"),
                    ("2", "Flash exposure compensation"),
                    ("3", "LCD monitor On/Off"),
                    ("4", "Menu display"),
                    ("5", "Disabled"),
                ])),
            },
            Cf2Arm {
                name: "SetButtonWhenShooting",
                cond: Cf2Cond::Count(2),
                value_convs: &[],
                print_conv: Cf2Print::Scalar(Cf2PrintConv::Map(&[])),
            },
            Cf2Arm {
                name: "SetButtonWhenShooting",
                cond: Cf2Cond::Always,
                value_convs: &[],
                print_conv: Cf2Print::Scalar(Cf2PrintConv::Map(&[
                    ("0", "Normal (disabled)"),
                    ("1", "White balance"),
                    ("2", "Image size"),
                    ("3", "ISO speed"),
                    ("4", "Picture style"),
                    ("5", "Record func. + media/folder"),
                    ("6", "Menu display"),
                    ("7", "Image playback"),
                ])),
            },
        ],
    },
    Cf2Entry {
        tag: 0x0705,
        arms: &[Cf2Arm {
            name: "ManualTv",
            cond: Cf2Cond::Always,
            value_convs: &[],
            print_conv: Cf2Print::Scalar(Cf2PrintConv::Map(&[
                ("0", "Tv=Main/Av=Control"),
                ("1", "Tv=Control/Av=Main"),
            ])),
        }],
    },
    Cf2Entry {
        tag: 0x0706,
        arms: &[Cf2Arm {
            name: "DialDirectionTvAv",
            cond: Cf2Cond::Always,
            value_convs: &[],
            print_conv: Cf2Print::Scalar(Cf2PrintConv::Map(&[("0", "Normal"), ("1", "Reversed")])),
        }],
    },
    Cf2Entry {
        tag: 0x0707,
        arms: &[Cf2Arm {
            name: "AvSettingWithoutLens",
            cond: Cf2Cond::Always,
            value_convs: &[],
            print_conv: Cf2Print::Scalar(Cf2PrintConv::Map(&[("0", "Disable"), ("1", "Enable")])),
        }],
    },
    Cf2Entry {
        tag: 0x0708,
        arms: &[Cf2Arm {
            name: "WBMediaImageSizeSetting",
            cond: Cf2Cond::Always,
            value_convs: &[],
            print_conv: Cf2Print::Scalar(Cf2PrintConv::Map(&[
                ("0", "Rear LCD panel"),
                ("1", "LCD monitor"),
                ("2", "Off (disable button)"),
            ])),
        }],
    },
    Cf2Entry {
        tag: 0x0709,
        arms: &[Cf2Arm {
            name: "LockMicrophoneButton",
            cond: Cf2Cond::Always,
            value_convs: &[],
            print_conv: Cf2Print::List(&[Cf2PrintConv::Map(&[
                ("0", "Protect (hold:record memo)"),
                ("1", "Record memo (protect:disable)"),
                ("2", "Play memo (hold:record memo)"),
                ("3", "Rating (protect/memo:disable)"),
            ])]),
        }],
    },
    Cf2Entry {
        tag: 0x070a,
        arms: &[Cf2Arm {
            name: "ButtonFunctionControlOff",
            cond: Cf2Cond::Always,
            value_convs: &[],
            print_conv: Cf2Print::Scalar(Cf2PrintConv::Map(&[
                ("0", "Normal (enable)"),
                ("1", "Disable main, Control, Multi-control"),
            ])),
        }],
    },
    Cf2Entry {
        tag: 0x070b,
        arms: &[Cf2Arm {
            name: "AssignFuncButton",
            cond: Cf2Cond::Always,
            value_convs: &[],
            print_conv: Cf2Print::Scalar(Cf2PrintConv::Map(&[
                ("0", "LCD brightness"),
                ("1", "Image quality"),
                ("2", "Exposure comp./AEB setting"),
                ("3", "Image jump with main dial"),
                ("4", "Live view function settings"),
            ])),
        }],
    },
    Cf2Entry {
        tag: 0x070c,
        arms: &[Cf2Arm {
            name: "CustomControls",
            cond: Cf2Cond::Always,
            value_convs: &[],
            print_conv: Cf2Print::None,
        }],
    },
    Cf2Entry {
        tag: 0x070d,
        arms: &[Cf2Arm {
            name: "StartMovieShooting",
            cond: Cf2Cond::Always,
            value_convs: &[],
            print_conv: Cf2Print::Scalar(Cf2PrintConv::Map(&[
                ("0", "Default (from LV)"),
                ("1", "Quick start (FEL button)"),
            ])),
        }],
    },
    Cf2Entry {
        tag: 0x070e,
        arms: &[Cf2Arm {
            name: "FlashButtonFunction",
            cond: Cf2Cond::Always,
            value_convs: &[],
            print_conv: Cf2Print::Scalar(Cf2PrintConv::Map(&[
                ("0", "Raise built-in flash"),
                ("1", "ISO speed"),
            ])),
        }],
    },
    Cf2Entry {
        tag: 0x070f,
        arms: &[Cf2Arm {
            name: "MultiFunctionLock",
            cond: Cf2Cond::Always,
            value_convs: &[],
            print_conv: Cf2Print::List(&[
                Cf2PrintConv::Map(&[
                    ("0", "Off"),
                    ("1", "On"),
                    ("2", "On (quick control dial)"),
                    ("3", "On (main dial and quick control dial)"),
                ]),
                Cf2PrintConv::Bitmask(&[
                    (0, "Main dial"),
                    (1, "Quick control dial"),
                    (2, "Multi-controller"),
                ]),
            ]),
        }],
    },
    Cf2Entry {
        tag: 0x0710,
        arms: &[Cf2Arm {
            name: "TrashButtonFunction",
            cond: Cf2Cond::Always,
            value_convs: &[],
            print_conv: Cf2Print::Scalar(Cf2PrintConv::Map(&[
                ("0", "Normal (set center AF point)"),
                ("1", "Depth-of-field preview"),
            ])),
        }],
    },
    Cf2Entry {
        tag: 0x0711,
        arms: &[Cf2Arm {
            name: "ShutterReleaseWithoutLens",
            cond: Cf2Cond::Always,
            value_convs: &[],
            print_conv: Cf2Print::Scalar(Cf2PrintConv::Map(&[("0", "Disable"), ("1", "Enable")])),
        }],
    },
    Cf2Entry {
        tag: 0x0712,
        arms: &[Cf2Arm {
            name: "ControlRingRotation",
            cond: Cf2Cond::Always,
            value_convs: &[],
            print_conv: Cf2Print::Scalar(Cf2PrintConv::Map(&[("0", "Normal"), ("1", "Reversed")])),
        }],
    },
    Cf2Entry {
        tag: 0x0713,
        arms: &[Cf2Arm {
            name: "FocusRingRotation",
            cond: Cf2Cond::Always,
            value_convs: &[],
            print_conv: Cf2Print::Scalar(Cf2PrintConv::Map(&[("0", "Normal"), ("1", "Reversed")])),
        }],
    },
    Cf2Entry {
        tag: 0x0714,
        arms: &[Cf2Arm {
            name: "RFLensMFFocusRingSensitivity",
            cond: Cf2Cond::Always,
            value_convs: &[],
            print_conv: Cf2Print::Scalar(Cf2PrintConv::Map(&[
                ("0", "Varies With Rotation Speed"),
                ("1", "Linked To Rotation Angle"),
            ])),
        }],
    },
    Cf2Entry {
        tag: 0x0715,
        arms: &[Cf2Arm {
            name: "CustomizeDials",
            cond: Cf2Cond::Always,
            value_convs: &[],
            print_conv: Cf2Print::None,
        }],
    },
    Cf2Entry {
        tag: 0x080b,
        arms: &[
            Cf2Arm {
                name: "FocusingScreen",
                cond: Cf2Cond::Model(&["40D", "50D", "60D"]),
                value_convs: &[],
                print_conv: Cf2Print::Scalar(Cf2PrintConv::Map(&[
                    ("0", "Ef-A"),
                    ("1", "Ef-D"),
                    ("2", "Ef-S"),
                ])),
            },
            Cf2Arm {
                name: "FocusingScreen",
                cond: Cf2Cond::Model(&["5D Mark II"]),
                value_convs: &[],
                print_conv: Cf2Print::Scalar(Cf2PrintConv::Map(&[
                    ("0", "Eg-A"),
                    ("1", "Eg-D"),
                    ("2", "Eg-S"),
                ])),
            },
            Cf2Arm {
                name: "FocusingScreen",
                cond: Cf2Cond::Model(&["6D"]),
                value_convs: &[],
                print_conv: Cf2Print::Scalar(Cf2PrintConv::Map(&[
                    ("0", "Eg-A II"),
                    ("1", "Eg-D"),
                    ("2", "Eg-S"),
                ])),
            },
            Cf2Arm {
                name: "FocusingScreen",
                cond: Cf2Cond::Model(&["7D Mark II"]),
                value_convs: &[],
                print_conv: Cf2Print::Scalar(Cf2PrintConv::Map(&[("0", "Eh-A"), ("1", "Eh-S")])),
            },
            Cf2Arm {
                name: "FocusingScreen",
                cond: Cf2Cond::Model(&["1D X"]),
                value_convs: &[],
                print_conv: Cf2Print::Scalar(Cf2PrintConv::Map(&[
                    ("0", "Ec-CV"),
                    ("1", "Ec-A,B,D,H,I,L"),
                ])),
            },
            Cf2Arm {
                name: "FocusingScreen",
                cond: Cf2Cond::Always,
                value_convs: &[],
                print_conv: Cf2Print::Scalar(Cf2PrintConv::Map(&[
                    ("0", "Ec-CIV"),
                    ("1", "Ec-A,B,C,CII,CIII,D,H,I,L"),
                    ("2", "Ec-S"),
                    ("3", "Ec-N,R"),
                ])),
            },
        ],
    },
    Cf2Entry {
        tag: 0x080c,
        arms: &[
            Cf2Arm {
                name: "TimerLength",
                cond: Cf2Cond::Count(3),
                value_convs: &[],
                print_conv: Cf2Print::List(&[
                    Cf2PrintConv::Interpolate("6 s: ", ""),
                    Cf2PrintConv::Interpolate("16 s: ", ""),
                    Cf2PrintConv::Interpolate("After release: ", ""),
                ]),
            },
            Cf2Arm {
                name: "TimerLength",
                cond: Cf2Cond::Always,
                value_convs: &[],
                print_conv: Cf2Print::List(&[
                    Cf2PrintConv::Map(&[("0", "Disable"), ("1", "Enable")]),
                    Cf2PrintConv::Interpolate("6 s: ", ""),
                    Cf2PrintConv::Interpolate("16 s: ", ""),
                    Cf2PrintConv::Interpolate("After release: ", ""),
                ]),
            },
        ],
    },
    Cf2Entry {
        tag: 0x080d,
        arms: &[Cf2Arm {
            name: "ShortReleaseTimeLag",
            cond: Cf2Cond::Always,
            value_convs: &[],
            print_conv: Cf2Print::Scalar(Cf2PrintConv::Map(&[("0", "Disable"), ("1", "Enable")])),
        }],
    },
    Cf2Entry {
        tag: 0x080e,
        arms: &[Cf2Arm {
            name: "AddAspectRatioInfo",
            cond: Cf2Cond::Always,
            value_convs: &[],
            print_conv: Cf2Print::Scalar(Cf2PrintConv::Map(&[
                ("0", "Off"),
                ("1", "6:6"),
                ("2", "3:4"),
                ("3", "4:5"),
                ("4", "6:7"),
                ("5", "10:12"),
                ("6", "5:7"),
            ])),
        }],
    },
    Cf2Entry {
        tag: 0x080f,
        arms: &[Cf2Arm {
            name: "AddOriginalDecisionData",
            cond: Cf2Cond::Always,
            value_convs: &[],
            print_conv: Cf2Print::Scalar(Cf2PrintConv::Map(&[("0", "Off"), ("1", "On")])),
        }],
    },
    Cf2Entry {
        tag: 0x0810,
        arms: &[Cf2Arm {
            name: "LiveViewExposureSimulation",
            cond: Cf2Cond::Always,
            value_convs: &[],
            print_conv: Cf2Print::Scalar(Cf2PrintConv::Map(&[
                ("0", "Disable (LCD auto adjust)"),
                ("1", "Enable (simulates exposure)"),
            ])),
        }],
    },
    Cf2Entry {
        tag: 0x0811,
        arms: &[Cf2Arm {
            name: "LCDDisplayAtPowerOn",
            cond: Cf2Cond::Always,
            value_convs: &[],
            print_conv: Cf2Print::Scalar(Cf2PrintConv::Map(&[
                ("0", "Display"),
                ("1", "Retain power off status"),
            ])),
        }],
    },
    Cf2Entry {
        tag: 0x0812,
        arms: &[Cf2Arm {
            name: "MemoAudioQuality",
            cond: Cf2Cond::Always,
            value_convs: &[],
            print_conv: Cf2Print::Scalar(Cf2PrintConv::Map(&[
                ("0", "High (48 kHz)"),
                ("1", "Low (8 kHz)"),
            ])),
        }],
    },
    Cf2Entry {
        tag: 0x0813,
        arms: &[Cf2Arm {
            name: "DefaultEraseOption",
            cond: Cf2Cond::Always,
            value_convs: &[],
            print_conv: Cf2Print::Scalar(Cf2PrintConv::Map(&[
                ("0", "Cancel selected"),
                ("1", "Erase selected"),
                ("2", "Erase RAW selected"),
                ("3", "Erase non-RAW selected"),
            ])),
        }],
    },
    Cf2Entry {
        tag: 0x0814,
        arms: &[Cf2Arm {
            name: "RetractLensOnPowerOff",
            cond: Cf2Cond::Always,
            value_convs: &[],
            print_conv: Cf2Print::Scalar(Cf2PrintConv::Map(&[("0", "Enable"), ("1", "Disable")])),
        }],
    },
    Cf2Entry {
        tag: 0x0815,
        arms: &[Cf2Arm {
            name: "AddIPTCInformation",
            cond: Cf2Cond::Always,
            value_convs: &[],
            print_conv: Cf2Print::Scalar(Cf2PrintConv::Map(&[("0", "Disable"), ("1", "Enable")])),
        }],
    },
    Cf2Entry {
        tag: 0x0816,
        arms: &[Cf2Arm {
            name: "AudioCompression",
            cond: Cf2Cond::Always,
            value_convs: &[],
            print_conv: Cf2Print::Scalar(Cf2PrintConv::Map(&[("0", "Enable"), ("1", "Disable")])),
        }],
    },
];
