"""Emit inactive Rust CheckExif recipes from closed source recipes."""
from dataclasses import asdict
import json
from pathlib import Path
from typing import Any

from checkexif_recipes import RecipeMalformed, RecipeRefused, compile_recipes
from checkvalue_recipes import compile_scalar_check
from scalar_helper_codegen import _check_fields, rust_string


_SOURCES = {"tag": "Tag", "table": "Table", "tag.Groups": "TagGroup"}


def _selector(selector) -> str:
    try:
        source = _SOURCES[selector.source]
    except KeyError as error:
        raise RecipeRefused("CheckExif selector has no Rust source") from error
    return "Selector { source: SelectorSource::" + source + ", property: " + rust_string(selector.property) + " }"


def _tables(tables) -> str:
    values = ["SourceTable { module: %s, table: %s, full_name: %s }" % tuple(map(rust_string, table)) for table in tables]
    return "&[" + ", ".join(values) + "]"


def _scalar(recipe) -> str:
    fields = _check_fields(recipe)
    return "ScalarCheckRecipe { " + ", ".join(name + ": " + value for name, value in fields.items()) + " }"


def _recipe(recipe, scalar) -> str:
    selectors = "&[" + ", ".join(_selector(selector) for selector in recipe.format_selectors) + "]"
    missing = recipe.missing_format
    return """CheckExifRecipe {
    source_tables: %s,
    format_selectors: %s,
    missing_format: MissingFormat { equals_literal: %s, group_source: %s, maker_notes_literal: %s, other_error: %s },
    count_selector: %s,
    check_value: %s,
}""" % (_tables(recipe.source_tables), selectors, rust_string(missing.equals_literal),
         _selector(missing.group_source), rust_string(missing.maker_notes_literal),
         rust_string(missing.other_return), _selector(recipe.count_operand), _scalar(scalar))


def generate(document: dict[str, Any]) -> tuple[str, dict[str, Any]]:
    if not isinstance(document, dict):
        raise RecipeMalformed("document is not an object")
    recipes, report, omissions = compile_recipes(document)
    try:
        scalar = compile_scalar_check(document["native_write_helpers"]["check_value"])
        # Operand representability is part of admission, not a late rendering
        # error that would abort the whole source inventory.
        _check_fields(scalar)
    except RecipeRefused as error:
        omissions.extend({"module": module, "table": table, "full_name": full_name, "reason": "CheckValue scalar dependency: " + str(error)}
                         for recipe in recipes for module, table, full_name in recipe.source_tables)
        recipes = []
    else:
        retained = []
        for recipe in recipes:
            if asdict(recipe.check_value) != asdict(scalar.provenance):
                omissions.extend({"module": module, "table": table, "full_name": full_name, "reason": "CheckValue scalar dependency provenance differs"}
                                 for module, table, full_name in recipe.source_tables)
            else:
                retained.append(recipe)
        recipes = retained
    chunks = [
        "// @generated by tools/exiftool-tables/checkexif_rust_codegen.py.\n",
        "// Inactive source-derived CheckExif composition; no writer route.\n",
        "#![allow(dead_code, unused_imports)]\n",
        "use crate::writers::generated_checkexif::{CheckExifRecipe, MissingFormat, Selector, SelectorSource, SourceTable};\nuse crate::writers::generated_scalar::{Comparison, ScalarCheckRecipe};\n",
        "pub(crate) const CHECK_EXIF_RECIPES: &[CheckExifRecipe] = &[\n",
    ]
    chunks.extend(_recipe(recipe, scalar) + ",\n" for recipe in recipes)
    chunks.append("];\n")
    report = asdict(report)
    report["recipes_emitted"] = len(recipes)
    report["omitted_tables"] = len(omissions)
    report["omissions_by_reason"] = {
        reason: sum(item["reason"] == reason for item in omissions)
        for reason in sorted({item["reason"] for item in omissions})
    }
    return "".join(chunks), {"exiftool_version": document.get("exiftool_version"), "runtime_status": "inactive; direct helper composition only", "recipes": [asdict(recipe) for recipe in recipes], "report": report, "omitted_tables": omissions}


def main() -> None:
    import argparse
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("tables", type=Path)
    parser.add_argument("-o", "--output", type=Path, required=True)
    parser.add_argument("--report", type=Path, required=True)
    args = parser.parse_args()
    source, report = generate(json.loads(args.tables.read_text(encoding="utf-8")))
    args.output.write_text(source, encoding="utf-8")
    args.report.write_text(json.dumps(report, sort_keys=True, indent=2) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
