"""Emit the source-derived ConvInv scalar operands and omission ledger."""
from __future__ import annotations

from dataclasses import asdict
import json
from pathlib import Path
from typing import Any

from checkexif_recipes import RecipeMalformed, RecipeRefused
from convinv_recipes import _PROFILES, compile_convinv_profile
from scalar_helper_codegen import rust_string


def generate(document: dict[str, Any]) -> tuple[str, dict[str, Any]]:
    if not isinstance(document, dict):
        raise RecipeMalformed("ConvInv document is not an object")
    helpers = document.get("native_write_helpers", {})
    if not isinstance(helpers, dict):
        raise RecipeMalformed("native_write_helpers is not an object")
    header = ("// @generated by tools/exiftool-tables/convinv_rust_codegen.py.\n"
              "// Inactive helper; no public writer admission.\n"
              "#![allow(dead_code, unused_imports)]\n"
              "use crate::writers::generated_convinv::ConvInvRecipe;\n")
    report = {"exiftool_version": document.get("exiftool_version"),
              "runtime_status": "inactive source-derived ConvInv scalar helper",
              "emitted": False, "recipe": None,
              "unsupported_branches": ["active conversions", "List splitting", "RawJoin",
                                       "WriteCheck", "unmodeled conversion type"]}
    try:
        recipe, profile = compile_convinv_profile(helpers.get("conv_inv"))
    except RecipeRefused as error:
        report["reason"] = str(error)
        return header + "pub(crate) const CONV_INV_RECIPE: Option<ConvInvRecipe> = None;\n", report
    report.update(emitted=True, recipe=asdict(recipe), provenance=asdict(recipe.provenance),
                  error_separator=recipe.error_separator)
    # Only a body admitted by a non-pin profile is recorded, as
    # verify_exprs.py records a non-13.59 helper_semantics choice: the pin's
    # ledger keeps its exact shape, and a historical admission is never silent.
    if profile is not _PROFILES[0]:
        report["source_profile"] = {"template": profile.template,
                                    "captured_from": profile.captured_from,
                                    "operands": [name for name, _ in profile.operands],
                                    "equivalences": list(profile.equivalences)}
    source = (header + "pub(crate) const CONV_INV_RECIPE: Option<ConvInvRecipe> = Some(ConvInvRecipe {\n"
              f"    default_type: {rust_string(recipe.default_type)},\n"
              f"    error_separator: {rust_string(recipe.error_separator)},\n"
              "});\n")
    return source, report


def main() -> None:
    import argparse
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("tables", type=Path)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--report", type=Path, required=True)
    args = parser.parse_args()
    source, report = generate(json.loads(args.tables.read_text()))
    args.output.write_text(source)
    args.report.write_text(json.dumps(report, sort_keys=True, indent=2) + "\n")


if __name__ == "__main__":
    main()
