"""Emit the source-derived ConvInv scalar operands."""
from __future__ import annotations
from typing import Any
from convinv_recipes import compile_convinv, RecipeRefused
from scalar_helper_codegen import rust_string

def generate(document:dict[str,Any])->tuple[str,dict[str,Any]]:
 try: recipe=compile_convinv(document['native_write_helpers']['conv_inv'])
 except (KeyError,RecipeRefused) as error:
  return ('// @generated; ConvInv omitted: unsupported source.\n',{'emitted':False,'reason':str(error)})
 return ('// @generated by convinv_rust_codegen.py\nuse crate::writers::generated_convinv::ConvInvRecipe;\n'
  +'pub(crate) const CONV_INV_RECIPE:ConvInvRecipe=ConvInvRecipe{default_type:'+rust_string(recipe.default_type)+',error_separator:'+rust_string(recipe.error_separator)+'};\n',
  {'emitted':True,'provenance':recipe.provenance.__dict__,'error_separator':recipe.error_separator})
