#!/usr/bin/env python3
"""Generate src/writers/makernote_offset_pairs.rs from the pinned ExifTool.

The maker-note guard (`src/writers/makernote_guard.rs`) checks, after an EXIF
rewrite, that every offset/length pair a maker note decodes to still locates
the same bytes. Which tags are such pairs is not a hand list: it is every
tag the pinned ExifTool flags `IsOffset` (`IsOffset => ...` or
`Flags => 'IsOffset'`) in any table it loads, paired with the tag its
`OffsetPair` names -- or, where a ProcessBinaryData table has no OffsetPair,
the tag of the same table named <stem>Length / ByteCount / ByteCounts / Size
(Olympus/Samsung/Sanyo `Thumbnail`). IsOffset tags with no length at all are
listed apart (Canon `OriginalDecisionDataOffset`, whose block the guard reads
with the ODD reader instead). This is the source #943's pointer-refusal list
uses (`LoadAllTables`, `IsOffset`, `OffsetPair`), walked by
`makernote_offset_pairs.pl`.

usage:
  makernote_offset_pairs.py write  [--perl PERL] [--exiftool-dir DIR]
  makernote_offset_pairs.py check  [--perl PERL] [--exiftool-dir DIR]

DIR is the pinned ExifTool tree (the one holding `lib/`); defaults come from
$EXIFTOOL_PERL and $OXIDEX_PINNED_EXIFTOOL, else the pinned cache.
"""
from __future__ import annotations

import argparse
import os
import subprocess  # nosec B404 -- list-argv only
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]
OUTPUT = ROOT / "src/writers/makernote_offset_pairs.rs"
SCRIPT = HERE / "makernote_offset_pairs.pl"


def default_tree() -> Path | None:
    env = os.environ.get("OXIDEX_PINNED_EXIFTOOL")
    if env:
        return Path(env)
    sys.path.insert(0, str(ROOT / "scripts"))
    try:
        import exiftool_oracle  # noqa: E402

        return Path(exiftool_oracle.cache_dir()) / "exiftool"
    except Exception:  # pragma: no cover - resolution failure means "no tree"
        return None


def default_perl() -> str:
    return os.environ.get("EXIFTOOL_PERL") or "perl"


def inventory(perl: str, tree: Path) -> list[tuple[str, str, str, str]]:
    env = {k: v for k, v in os.environ.items() if k not in ("PERL5LIB", "PERLLIB", "PERL5OPT")}
    out = subprocess.run(  # nosec B603
        [perl, f"-I{tree / 'lib'}", str(SCRIPT)], capture_output=True, text=True, env=env, check=True
    ).stdout
    rows = []
    for line in out.splitlines():
        kind, offset, length, tables = line.split("\t")
        rows.append((kind, offset, length, tables))
    if not any(r[0] == "offsetpair" and r[1] == "PreviewImageStart" for r in rows):
        raise SystemExit(f"❌ {tree}: no PreviewImageStart pair found -- not a loadable ExifTool tree")
    return rows


def release(tree: Path) -> str:
    text = (tree / "lib/Image/ExifTool.pm").read_text(errors="replace")
    for line in text.splitlines():
        if line.startswith("$VERSION"):
            return line.split("'")[1]
    return "unknown"


def render(rows: list[tuple[str, str, str, str]], version: str) -> str:
    pairs = sorted({(o, length) for kind, o, length, _ in rows if kind == "offsetpair"})
    unpaired = sorted({o for kind, o, _, _ in rows if kind == "unpaired"})
    tables = {}
    for kind, o, length, t in rows:
        if kind == "offsetpair":
            tables.setdefault((o, length), set()).update(t.split(","))
    lines = [
        "// GENERATED by tools/exiftool-tables/makernote_offset_pairs.py from pinned",
        f"// ExifTool {version}: every `IsOffset` tag of every loaded table with the length",
        "// tag it pairs with. Do not edit; re-run the generator (`write`), and",
        "// `test_makernote_offset_pairs.py` checks it against the pinned tree.",
        "",
        "/// `(offset tag, length tag)` names: an `IsOffset` tag and its `OffsetPair`",
        "/// (or, in a ProcessBinaryData table without one, the same table's",
        "/// `<stem>Length`/`ByteCount`/`ByteCounts`/`Size`).",
        "pub(crate) const OFFSET_PAIRS: &[(&str, &str)] = &[",
    ]
    for o, length in pairs:
        lines.append(f"    // {', '.join(sorted(tables[(o, length)]))}")
        lines.append(f'    ("{o}", "{length}"),')
    lines += [
        "];",
        "",
        "/// `IsOffset` tags with no length tag at all.",
        "pub(crate) const UNPAIRED_OFFSETS: &[&str] = &[",
    ]
    lines += [f'    "{o}",' for o in unpaired]
    lines += ["];", ""]
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("command", choices=("write", "check"))
    ap.add_argument("--perl", default=default_perl())
    ap.add_argument("--exiftool-dir", type=Path, default=default_tree())
    args = ap.parse_args()
    if args.exiftool_dir is None or not (args.exiftool_dir / "lib/Image/ExifTool.pm").is_file():
        sys.exit(f"❌ no pinned ExifTool tree at {args.exiftool_dir}")
    text = render(inventory(args.perl, args.exiftool_dir), release(args.exiftool_dir))
    if args.command == "write":
        OUTPUT.write_text(text)
        print(f"wrote {OUTPUT.relative_to(ROOT)}")
        return 0
    if OUTPUT.read_text() != text:
        print(f"❌ {OUTPUT.relative_to(ROOT)} is stale: re-run makernote_offset_pairs.py write", file=sys.stderr)
        return 1
    print(f"{OUTPUT.relative_to(ROOT)} matches ExifTool {release(args.exiftool_dir)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
