"""Render a source-authenticated, inactive mandatory-defaults Rust operand.

This producer is intentionally not registered in artifacts.py: official
regen.sh has no same-transaction mandatory sidecar yet.  Callers must supply a
fresh capture made by capture_exif_mandatory_fact.pl, and may additionally join
it to dump_tables.pl's writer facts with --writer-tables.
"""
from __future__ import annotations
from dataclasses import asdict
import argparse, json
from pathlib import Path
from typing import Any, Mapping
from mandatory_defaults import MandatoryRecipe, MandatoryRefused, compile_mandatory, compile_mandatory_joined, recipe_json
from scalar_helper_codegen import rust_string

HEADER = "// @generated by mandatory_defaults_codegen.py; pending official regeneration integration.\nuse crate::writers::mandatory_defaults_runtime::{JfifAssignment, MandatoryDefault, MandatoryDirectory, MandatoryRecipe, MandatoryValue};\n"
def _integer(value: int) -> str:
    if not -(1 << 63) <= value < (1 << 63): raise MandatoryRefused("mandatory integer is outside Rust i64")
    return str(value)
def _value(kind: str, value: str | int) -> str:
    return f"MandatoryValue::Integer({_integer(value)})" if kind == "Integer" else f"MandatoryValue::Text({rust_string(value)})"
def evaluate(recipe: MandatoryRecipe, directory: str, no_mandatory: bool, num_entries: int, jfif: tuple[int, int, int] | None = None) -> tuple[tuple[int, str | int], ...]:
    """Python oracle for the same closed, source-derived branch as Rust."""
    if num_entries != 0 or (recipe.selection.disabled_when == "noMandatory" and no_mandatory):
        return ()
    defaults = next((item.defaults for item in recipe.directories if item.directory == directory), None)
    if defaults is None: raise MandatoryRefused("directory has no generated mandatory defaults")
    values = {item.tag_id: item.value for item in defaults}
    if directory == recipe.jfif_override.directory and jfif is not None:
        source = {"JFIFXResolution": jfif[0], "JFIFYResolution": jfif[1], "JFIFResolutionUnit": jfif[2]}
        for tag, prop, adjustment in recipe.jfif_override.assignments:
            if prop not in source: raise MandatoryRefused("JFIF operands are unresolved")
            values[tag] = source[prop] + adjustment
    return tuple(sorted(values.items()))

def render(recipe: MandatoryRecipe) -> str:
    lines=[HEADER]
    for n,directory in enumerate(recipe.directories):
        lines.append(f"const DIRECTORY_{n}: &[MandatoryDefault] = &[\n")
        lines.extend(f"MandatoryDefault {{ tag_id: 0x{item.tag_id:04x}, value: {_value(item.kind,item.value)} }},\n" for item in directory.defaults)
        lines.append("];\n")
    lines.append("const DIRECTORIES: &[MandatoryDirectory] = &[\n")
    lines.extend(f"MandatoryDirectory {{ directory: {rust_string(d.directory)}, defaults: DIRECTORY_{n} }},\n" for n,d in enumerate(recipe.directories))
    lines.append("];\nconst JFIF_ASSIGNMENTS: &[JfifAssignment] = &[\n")
    lines.extend(f"JfifAssignment {{ tag_id: 0x{tag:04x}, property: {rust_string(prop)}, adjustment: {_integer(adjust)} }},\n" for tag,prop,adjust in recipe.jfif_override.assignments)
    guard="true" if recipe.selection.disabled_when == "noMandatory" else "false"
    lines.append("];\n")
    lines.append("pub(crate) const MANDATORY_DEFAULTS: MandatoryRecipe = MandatoryRecipe { "
                 f"writer_source_file: {rust_string(recipe.writer_source_file)}, writer_source_sha256: {rust_string(recipe.writer_source_sha256)}, "
                 f"perl_version: {rust_string('')}, no_mandatory_guard: {guard}, directories: DIRECTORIES, jfif_directory: {rust_string(recipe.jfif_override.directory)}, jfif_probe: {rust_string(recipe.jfif_override.probe)}, jfif_assignments: JFIF_ASSIGNMENTS }};\n")
    return ''.join(lines)
def generate(fact: Mapping[str, Any], writer_document: Mapping[str, Any] | None = None) -> tuple[str, dict[str, Any]]:
    recipe = compile_mandatory_joined(fact, writer_document) if writer_document is not None else compile_mandatory(fact)
    native = fact['native_identity']
    source = render(recipe).replace('perl_version: ""', f"perl_version: {rust_string(native['perl_version'])}")
    report={"status":"pending official regeneration integration; no public writer", "recipe":recipe_json(recipe), "native_identity":native,
            "writer_tables_joined": writer_document is not None, "artifact_registration":"pending: regen.sh has no mandatory-sidecar input"}
    return source,report
def main() -> None:
    p=argparse.ArgumentParser(description=__doc__); p.add_argument('fact',type=Path); p.add_argument('-o','--output',type=Path,required=True); p.add_argument('--report',type=Path,required=True); p.add_argument('--writer-tables',type=Path); a=p.parse_args()
    fact=json.loads(a.fact.read_text()); tables=json.loads(a.writer_tables.read_text()) if a.writer_tables else None
    source,report=generate(fact,tables); a.output.write_text(source); a.report.write_text(json.dumps(report,sort_keys=True,indent=2)+'\n')
if __name__ == '__main__': main()
