"""Render a source-authenticated, inactive mandatory-defaults Rust operand.

The official tier-1 transaction captures this sidecar with its selected Perl
and library, then joins it to the same dump_tables.pl document before rendering.
It emits only portable source facts: no interpreter or source paths enter the
committed ledger.
"""
from __future__ import annotations
from dataclasses import asdict
import argparse, json
import shutil
from pathlib import Path
from typing import Any, Mapping
from mandatory_defaults import MandatoryRecipe, MandatoryRefused, compile_mandatory, compile_mandatory_joined, recipe_json
from scalar_helper_codegen import rust_string

HEADER = "// @generated by mandatory_defaults_codegen.py; source-captured in the tier-1 regeneration transaction.\nuse crate::writers::mandatory_defaults_runtime::{DefaultEncoding, JfifAssignment, MandatoryDefault, MandatoryDirectory, MandatoryRecipe, MandatoryValue};\n"
def _integer(value: int) -> str:
    if not -(1 << 63) <= value < (1 << 63): raise MandatoryRefused("mandatory integer is outside Rust i64")
    return str(value)
def _value(kind: str, value: str | int) -> str:
    return f"MandatoryValue::Integer({_integer(value)})" if kind == "Integer" else f"MandatoryValue::Text({rust_string(value)})"
def evaluate(recipe: MandatoryRecipe, directory: str, no_mandatory: bool, num_entries: int, jfif: tuple[int, int, int] | None = None) -> tuple[tuple[int, str | int], ...]:
    """Python oracle for the same closed, source-derived branch as Rust."""
    if num_entries != 0 or (recipe.selection.disabled_when == "noMandatory" and no_mandatory):
        return ()
    defaults = next((item.defaults for item in recipe.directories if item.directory == directory), None)
    if defaults is None: raise MandatoryRefused("directory has no generated mandatory defaults")
    values = {item.tag_id: item.value for item in defaults}
    if directory == recipe.jfif_override.directory and jfif is not None:
        source = {"JFIFXResolution": jfif[0], "JFIFYResolution": jfif[1], "JFIFResolutionUnit": jfif[2]}
        for tag, prop, adjustment in recipe.jfif_override.assignments:
            if prop not in source: raise MandatoryRefused("JFIF operands are unresolved")
            values[tag] = source[prop] + adjustment
    return tuple(sorted(values.items()))

def render(recipe: MandatoryRecipe) -> str:
    lines=[HEADER]
    for n,directory in enumerate(recipe.directories):
        lines.append(f"const DIRECTORY_{n}: &[MandatoryDefault] = &[\n")
        lines.extend(f"MandatoryDefault {{ tag_id: 0x{item.tag_id:04x}, value: {_value(item.kind,item.value)} }},\n" for item in directory.defaults)
        lines.append("];\n")
    lines.append("const DIRECTORIES: &[MandatoryDirectory] = &[\n")
    lines.extend(f"MandatoryDirectory {{ directory: {rust_string(d.directory)}, defaults: DIRECTORY_{n} }},\n" for n,d in enumerate(recipe.directories))
    lines.append("];\nconst JFIF_ASSIGNMENTS: &[JfifAssignment] = &[\n")
    lines.extend(f"JfifAssignment {{ tag_id: 0x{tag:04x}, property: {rust_string(prop)}, adjustment: {_integer(adjust)} }},\n" for tag,prop,adjust in recipe.jfif_override.assignments)
    guard="true" if recipe.selection.disabled_when == "noMandatory" else "false"
    lines.append("];\nconst ENCODINGS: &[DefaultEncoding] = &[\n")
    lines.extend(f"DefaultEncoding {{ tag_id: 0x{item.tag_id:04x}, format_name: {rust_string(item.format_name)} }},\n" for item in recipe.encodings)
    lines.append("];\n")
    lines.append("pub(crate) const MANDATORY_DEFAULTS: MandatoryRecipe = MandatoryRecipe { "
                 f"writer_source_file: {rust_string(recipe.writer_source_file)}, writer_source_sha256: {rust_string(recipe.writer_source_sha256)}, "
                 f"perl_version: {rust_string('')}, no_mandatory_guard: {guard}, directories: DIRECTORIES, jfif_directory: {rust_string(recipe.jfif_override.directory)}, jfif_probe: {rust_string(recipe.jfif_override.probe)}, jfif_assignments: JFIF_ASSIGNMENTS, encodings: ENCODINGS }};\n")
    return ''.join(lines)
def _selected_perl(fact: Mapping[str, Any], selected_perl: str | None) -> None:
    if selected_perl is None:
        return
    native = fact["native_identity"]
    actual = Path(str(native["perl"])).expanduser().resolve()
    supplied = shutil.which(selected_perl) if "/" not in selected_perl else selected_perl
    supplied_path = Path(supplied or selected_perl).expanduser().resolve()
    if actual != supplied_path:
        raise MandatoryRefused("mandatory capture Perl differs from selected regeneration Perl")

def generate(fact: Mapping[str, Any], writer_document: Mapping[str, Any] | None = None,
             selected_perl: str | None = None) -> tuple[str, dict[str, Any]]:
    _selected_perl(fact, selected_perl)
    recipe = compile_mandatory_joined(fact, writer_document) if writer_document is not None else compile_mandatory(fact)
    native = fact['native_identity']
    source = render(recipe).replace('perl_version: ""', f"perl_version: {rust_string(native['perl_version'])}")
    report={"status":"inactive source-derived defaults; no public writer", "recipe":recipe_json(recipe),
            "native_identity":{"exiftool_version":native["exiftool_version"], "perl_version":native["perl_version"]},
            "writer_tables_joined": writer_document is not None,
            "artifact_registration":"tier-1 mandatory sidecar captured and joined in regen.sh"}
    return source,report
def main() -> None:
    p=argparse.ArgumentParser(description=__doc__); p.add_argument('fact',type=Path); p.add_argument('-o','--output',type=Path,required=True); p.add_argument('--report',type=Path,required=True); p.add_argument('--writer-tables',type=Path,required=True); p.add_argument('--selected-perl',required=True); a=p.parse_args()
    fact=json.loads(a.fact.read_text()); tables=json.loads(a.writer_tables.read_text())
    source,report=generate(fact,tables,a.selected_perl); a.output.write_text(source); a.report.write_text(json.dumps(report,sort_keys=True,indent=2)+'\n')
if __name__ == '__main__': main()
