"""Emit source-selected Sanitize operands after native primitive validation."""
from dataclasses import asdict
import json
from pathlib import Path

from checkexif_recipes import RecipeRefused, RecipeMalformed
from sanitize_recipes import compile_sanitize
from utf8_primitive_contract import validate_join, join_sanitize_bindings, perl_version


def generate(document):
    if not isinstance(document, dict):
        raise RecipeMalformed("Sanitize document is not an object")
    for key in ("native_write_helpers", "native_runtime_contracts"):
        if key in document and not isinstance(document[key], dict):
            raise RecipeMalformed("Sanitize " + key + " is not an object")
    report = {"exiftool_version": document.get("exiftool_version"),
              "status": "inactive source-derived helper; no public writer",
              "recipe": None, "omissions": [],
              "unsupported_branches": ["EncodeHangs/manual packing", "Encode load/evaluation failure",
                                       "XML unescape", "HTML unescape", "non-SCALAR references",
                                       "non-Unicode Perl character values"]}
    header = ("// @generated by tools/exiftool-tables/sanitize_rust_codegen.py.\n"
              "// Inactive helper; capability validation occurs during generation.\n"
              "#![allow(dead_code, unused_imports)]\n"
              "use crate::writers::generated_sanitize::{SanitizeRecipe, EncodingPrimitive};\n")
    try:
        helper = document.get("native_write_helpers", {}).get("sanitize")
        recipe = compile_sanitize(helper)
        contract = document.get("native_runtime_contracts", {}).get("utf8")
        final = validate_join(contract)
        join_sanitize_bindings(recipe.raw_dependencies, final)
        version = perl_version(final["perl_version"])
        if not all(0 <= guard < 2**64 for guard in
                   (recipe.downgrade_at_or_after, recipe.manual_pack_before)):
            raise RecipeRefused("Sanitize version guard is outside u64")
    except RecipeRefused as error:
        report["omissions"].append(str(error))
        return header + "pub(crate) const SANITIZE_RECIPE: Option<SanitizeRecipe> = None;\n", report
    report["recipe"] = asdict(recipe)
    report["primitive_contract"] = contract
    report["perl_version"] = version
    source = (header + "pub(crate) const SANITIZE_RECIPE: Option<SanitizeRecipe> = Some(SanitizeRecipe {\n"
              f"    perl_version: {version},\n"
              f"    downgrade_at_or_after: {recipe.downgrade_at_or_after},\n"
              f"    manual_pack_before: {recipe.manual_pack_before},\n"
              f"    encode_hangs_guard: {str(recipe.encode_hangs_guard).lower()},\n"
              "    encoding: EncodingPrimitive::Utf8,\n});\n")
    return source, report


def main():
    import argparse
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("tables", type=Path)
    parser.add_argument("-o", "--output", type=Path, required=True)
    parser.add_argument("--report", type=Path, required=True)
    args = parser.parse_args()
    source, report = generate(json.loads(args.tables.read_text()))
    args.output.write_text(source)
    args.report.write_text(json.dumps(report, sort_keys=True, indent=2) + "\n")


if __name__ == "__main__":
    main()
