"""Emit the inactive source-selected SetNewValue ConvInv-result operand."""
from __future__ import annotations

from dataclasses import asdict
from typing import Any

from setnewvalue_convinv_recipes import (
    RUNTIME_STATUS,
    RecipeRefused,
    compile_setnewvalue_convinv,
)


def generate(document: dict[str, Any]) -> tuple[str, dict[str, Any]]:
    prelude = (
        "// @generated by setnewvalue_convinv_rust_codegen.py; inactive.\n"
        "#[derive(Clone, Copy, Debug, Eq, PartialEq)]\n"
        "pub(crate) enum ConvInvErrorResult { Continue, SkipTag, Refuse }\n"
        "pub(crate) struct SetNewValueConvInvRecipe {\n"
        "    pub undefined_error: ConvInvErrorResult,\n"
        "    pub defined_false_error: ConvInvErrorResult,\n"
        "    pub truthy_error: ConvInvErrorResult,\n"
        "}\n"
    )
    try:
        recipe = compile_setnewvalue_convinv(document["native_write_helpers"]["set_new_value"])
    except (KeyError, RecipeRefused) as error:
        return (
            prelude
            + "// SetNewValue ConvInv caller omitted: unsupported source.\n"
            "pub(crate) const SET_NEW_VALUE_CONV_INV: Option<SetNewValueConvInvRecipe> = None;\n",
            {"emitted": False, "reason": str(error), "runtime_status": RUNTIME_STATUS},
        )
    return (
        prelude + "pub(crate) const SET_NEW_VALUE_CONV_INV: Option<SetNewValueConvInvRecipe> = Some(\n"
        "    SetNewValueConvInvRecipe {\n"
        "        undefined_error: ConvInvErrorResult::Continue,\n"
        "        defined_false_error: ConvInvErrorResult::SkipTag,\n"
        "        truthy_error: ConvInvErrorResult::Refuse,\n"
        "    },\n"
        ");\n",
        {"emitted": True, "provenance": asdict(recipe.provenance),
         "undefined_error": recipe.undefined_error,
         "defined_false_error": recipe.defined_false_error,
         "truthy_error": recipe.truthy_error,
         "runtime_status": RUNTIME_STATUS},
    )
