"""Emit inactive, source-selected SetNewValue EXIF addressing operands."""
from __future__ import annotations

from typing import Any, Mapping

from checkexif_recipes import RecipeMalformed, RecipeRefused
from scalar_helper_codegen import rust_string
from setnewvalue_addressing import (RUNTIME_STATUS, Addressing, _owned_names,
                                    compile_addressing, _observed_candidates)


def _opt_text(value: Any) -> str:
    return "Some(" + rust_string(value) + ")" if isinstance(value, str) else "None"


def _row(index: int, row: Any) -> str:
    values = (row.module, row.table, row.full_name, row.raw_id, row.name,
              row.group0, row.group1, row.write_group)
    return "StaticSetNewValueAddress { index: %d, module: %s, table: %s, full_name: %s, raw_id: %s, name: %s, group0: %s, group1: %s, write_group: %s }" % ((index,) + tuple(rust_string(item) for item in values))


def _owned_names_const(names: set[str] | frozenset[str]) -> str:
    return ("pub(crate) const SET_NEW_VALUE_OWNED_NAMES: &[&str] = &[" +
            ", ".join(rust_string(name) for name in sorted(names)) + "];\n")


def generate(document: Mapping[str, Any], observations: Mapping[str, Any]) -> tuple[str, dict[str, Any]]:
    prelude = (
        "// @generated by setnewvalue_address_rust_codegen.py; inactive.\n"
        "pub(crate) struct StaticSetNewValueAddress { pub index: usize, pub module: &'static str, pub table: &'static str, pub full_name: &'static str, pub raw_id: &'static str, pub name: &'static str, pub group0: &'static str, pub group1: &'static str, pub write_group: &'static str }\n"
        "pub(crate) struct StaticNativeLookupCandidate { pub name: &'static str, pub row_index: Option<usize>, pub group0: Option<&'static str>, pub group1: Option<&'static str> }\n"
    )
    try:
        addressing, report = compile_addressing(document)
        by_identity = {row.identity: index for index, row in enumerate(addressing.rows)}
        lookup = []
        for name in sorted(addressing.owned_names):
            # Requiring the observation now means a missing native lookup is an
            # owned omission, never an invitation to call an older writer.
            candidates = _observed_candidates(addressing, observations, name)
            if candidates is None:
                raise RecipeRefused(f"native lookup observation is unavailable for {name}")
            for candidate in candidates:
                identity = tuple(candidate.get(key) for key in ("module", "table", "full_name", "raw_id", "name"))
                index = by_identity.get(identity)
                groups = candidate.get("groups")
                if not isinstance(groups, Mapping):
                    raise RecipeMalformed("native lookup candidate lacks groups")
                lookup.append((name, index, groups.get("0"), groups.get("1")))
    except (KeyError, RecipeMalformed, RecipeRefused) as error:
        # Even when the execution recipe is unavailable, current source rows
        # remain owned.  This preserves the terminal router classification
        # without keeping a hand-maintained historical tag-name list.
        try:
            owned_names = _owned_names(document)
        except (RecipeMalformed, RecipeRefused):
            owned_names = set()
        return (
            prelude + "// SetNewValue addressing omitted: unsupported source.\n"
            + _owned_names_const(owned_names) +
            "pub(crate) const SET_NEW_VALUE_ADDRESSING: Option<&[StaticSetNewValueAddress]> = None;\n",
            {"emitted": False, "reason": str(error), "runtime_status": RUNTIME_STATUS,
             "owned_names": len(owned_names)},
        )
    chunks = [
        prelude,
        "pub(crate) const SET_NEW_VALUE_ADDRESS_ROWS: &[StaticSetNewValueAddress] = &[\n",
    ]
    chunks.extend("    " + _row(index, row) + ",\n" for index, row in enumerate(addressing.rows))
    chunks.append("];\n")
    chunks.append("pub(crate) const SET_NEW_VALUE_LOOKUP: &[StaticNativeLookupCandidate] = &[\n")
    chunks.extend(
        "    StaticNativeLookupCandidate { name: %s, row_index: %s, group0: %s, group1: %s },\n" % (
            rust_string(name), "Some(%d)" % index if index is not None else "None",
            _opt_text(group0), _opt_text(group1))
        for name, index, group0, group1 in lookup)
    chunks.append("];\n")
    chunks.append(_owned_names_const(addressing.owned_names))
    chunks.append("pub(crate) const SET_NEW_VALUE_ADDRESSING: Option<&[StaticSetNewValueAddress]> = Some(SET_NEW_VALUE_ADDRESS_ROWS);\n")
    return "".join(chunks), {
        "emitted": True, "runtime_status": RUNTIME_STATUS,
        "rows": len(addressing.rows), "owned_names": len(addressing.owned_names),
        "lookup_candidates": len(lookup), "source_report": report,
    }


def main() -> None:
    import argparse
    import json
    from pathlib import Path
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("tables", type=Path)
    parser.add_argument("observations", type=Path)
    parser.add_argument("-o", "--output", type=Path, required=True)
    parser.add_argument("--report", type=Path, required=True)
    args = parser.parse_args()
    source, report = generate(json.loads(args.tables.read_text(encoding="utf-8")),
                              json.loads(args.observations.read_text(encoding="utf-8")))
    args.output.write_text(source, encoding="utf-8")
    args.report.write_text(json.dumps(report, sort_keys=True, indent=2) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
