//! FujiFilm MakerNote binary sub-directory tables.
//!
//! GENERATED by `tools/exiftool-tables/codegen_subdirs.py` from ExifTool
//! 13.59's in-memory tag tables. Do not edit by hand.
//!
//! The generator refuses any construct it has not been taught and names it, so
//! a field that is here was reproduced exactly and a field that is missing was
//! reported as missing -- neither is a guess.

use crate::parsers::tiff::makernotes::shared::binary_subdir::{
    BinaryTable, Cond, Field, Fmt, PrintConv, ValueConv,
};

const FUJIFILM_CONV1: &[(i64, &str)] = &[(1, "Release"), (2, "Focus")];
const FUJIFILM_CONV2: &[(i64, &str)] = &[(0, "AF-M"), (1, "AF-S"), (2, "AF-C")];
const FUJIFILM_CONV3: &[(i64, &str)] = &[(0, "Off"), (1, "On")];
const FUJIFILM_CONV4: &[(i64, &str)] = &[(0, "Single Point"), (1, "Zone"), (2, "Wide/Tracking")];
const FUJIFILM_CONV5: &[(i64, &str)] = &[(0, "n/a")];
const FUJIFILM_CONV6: &[(i64, &str)] = &[
    (16, "Set 4 (suddenly appearing subject)"),
    (258, "Set 1 (multi-purpose)"),
    (290, "Set 3 (accelerating subject)"),
    (291, "Set 5 (erratic motion)"),
    (515, "Set 2 (ignore obstacles)"),
];
const FUJIFILM_CONV7: &[(i64, &str)] = &[(0, "Front"), (1, "Auto"), (2, "Center")];
const FUJIFILM_CONV8: &[(i64, &str)] =
    &[(0, "Single"), (1, "Continuous Low"), (2, "Continuous High")];

/// `Image::ExifTool::FujiFilm::PrioritySettings` -- 2 fields, FORMAT `int16u`.
///
/// Transcribed from ExifTool's in-memory tag table by
/// `tools/exiftool-tables/codegen_subdirs.py`. Do not edit by hand.
pub(crate) static FUJIFILM_PRIORITYSETTINGS: BinaryTable = BinaryTable {
    name: "PrioritySettings",
    default_format: Fmt::U16,
    first_entry: 0,
    fields: &[
        Field {
            key: "0.1",
            index: 0,
            cond: Cond::Always,
            name: "AF-SPriority",
            format: None,
            count: 1,
            set_member: None,
            gate: None,
            mask: Some(15),
            value_conv: ValueConv::None,
            print_conv: PrintConv::Map(FUJIFILM_CONV1),
        },
        Field {
            key: "0.2",
            index: 0,
            cond: Cond::Always,
            name: "AF-CPriority",
            format: None,
            count: 1,
            set_member: None,
            gate: None,
            mask: Some(240),
            value_conv: ValueConv::None,
            print_conv: PrintConv::Map(FUJIFILM_CONV1),
        },
    ],
};

/// `Image::ExifTool::FujiFilm::FocusSettings` -- 5 fields, FORMAT `int32u`.
///
/// Transcribed from ExifTool's in-memory tag table by
/// `tools/exiftool-tables/codegen_subdirs.py`. Do not edit by hand.
pub(crate) static FUJIFILM_FOCUSSETTINGS: BinaryTable = BinaryTable {
    name: "FocusSettings",
    default_format: Fmt::U32,
    first_entry: 0,
    fields: &[
        Field {
            key: "0.1",
            index: 0,
            cond: Cond::Always,
            name: "FocusMode2",
            format: None,
            count: 1,
            set_member: None,
            gate: None,
            mask: Some(15),
            value_conv: ValueConv::None,
            print_conv: PrintConv::Map(FUJIFILM_CONV2),
        },
        Field {
            key: "0.2",
            index: 0,
            cond: Cond::Always,
            name: "PreAF",
            format: None,
            count: 1,
            set_member: None,
            gate: None,
            mask: Some(240),
            value_conv: ValueConv::None,
            print_conv: PrintConv::Map(FUJIFILM_CONV3),
        },
        Field {
            key: "0.3",
            index: 0,
            cond: Cond::Always,
            name: "AFAreaMode",
            format: None,
            count: 1,
            set_member: None,
            gate: None,
            mask: Some(3840),
            value_conv: ValueConv::None,
            print_conv: PrintConv::Map(FUJIFILM_CONV4),
        },
        Field {
            key: "0.4",
            index: 0,
            cond: Cond::Always,
            name: "AFAreaPointSize",
            format: None,
            count: 1,
            set_member: None,
            gate: None,
            mask: Some(61440),
            value_conv: ValueConv::None,
            print_conv: PrintConv::MapOr(FUJIFILM_CONV5, super::print_conv::identity),
        },
        Field {
            key: "0.5",
            index: 0,
            cond: Cond::Always,
            name: "AFAreaZoneSize",
            format: None,
            count: 1,
            set_member: None,
            gate: None,
            mask: Some(16711680),
            value_conv: ValueConv::None,
            print_conv: PrintConv::MapOr(FUJIFILM_CONV5, super::print_conv::zone_size),
        },
    ],
};

/// `Image::ExifTool::FujiFilm::AFCSettings` -- 4 fields, FORMAT `int32u`.
///
/// Transcribed from ExifTool's in-memory tag table by
/// `tools/exiftool-tables/codegen_subdirs.py`. Do not edit by hand.
pub(crate) static FUJIFILM_AFCSETTINGS: BinaryTable = BinaryTable {
    name: "AFCSettings",
    default_format: Fmt::U32,
    first_entry: 0,
    fields: &[
        Field {
            key: "0",
            index: 0,
            cond: Cond::Always,
            name: "AF-CSetting",
            format: None,
            count: 1,
            set_member: None,
            gate: None,
            mask: None,
            value_conv: ValueConv::None,
            print_conv: PrintConv::MapOr(FUJIFILM_CONV6, super::print_conv::custom_afc_set),
        },
        Field {
            key: "0.1",
            index: 0,
            cond: Cond::Always,
            name: "AF-CTrackingSensitivity",
            format: None,
            count: 1,
            set_member: None,
            gate: None,
            mask: Some(15),
            value_conv: ValueConv::None,
            print_conv: PrintConv::None,
        },
        Field {
            key: "0.2",
            index: 0,
            cond: Cond::Always,
            name: "AF-CSpeedTrackingSensitivity",
            format: None,
            count: 1,
            set_member: None,
            gate: None,
            mask: Some(240),
            value_conv: ValueConv::None,
            print_conv: PrintConv::None,
        },
        Field {
            key: "0.3",
            index: 0,
            cond: Cond::Always,
            name: "AF-CZoneAreaSwitching",
            format: None,
            count: 1,
            set_member: None,
            gate: None,
            mask: Some(3840),
            value_conv: ValueConv::None,
            print_conv: PrintConv::Map(FUJIFILM_CONV7),
        },
    ],
};

/// `Image::ExifTool::FujiFilm::DriveSettings` -- 2 fields, FORMAT `int32u`.
///
/// Transcribed from ExifTool's in-memory tag table by
/// `tools/exiftool-tables/codegen_subdirs.py`. Do not edit by hand.
pub(crate) static FUJIFILM_DRIVESETTINGS: BinaryTable = BinaryTable {
    name: "DriveSettings",
    default_format: Fmt::U32,
    first_entry: 0,
    fields: &[
        Field {
            key: "0.1",
            index: 0,
            cond: Cond::Always,
            name: "DriveMode",
            format: None,
            count: 1,
            set_member: None,
            gate: None,
            mask: Some(255),
            value_conv: ValueConv::None,
            print_conv: PrintConv::Map(FUJIFILM_CONV8),
        },
        Field {
            key: "0.2",
            index: 0,
            cond: Cond::Always,
            name: "DriveSpeed",
            format: None,
            count: 1,
            set_member: None,
            gate: None,
            mask: Some(4278190080),
            value_conv: ValueConv::None,
            print_conv: PrintConv::MapOr(FUJIFILM_CONV5, super::print_conv::fps),
        },
    ],
};
