import { defineConfig } from 'vitepress'
import fs from 'node:fs'
import path from 'node:path'

// Dynamically generate sidebar items for comparison formats.
//
// docs/reference/comparison/ is gitignored and produced by
// `just compare-exiftool-full-update` (see scripts/ensure-comparison-stub.mjs),
// so on a fresh clone it may hold nothing but the generated stub. Returning an
// empty list keeps a cold `npm run docs:build` working instead of throwing
// ENOENT while the config is still loading.
function getComparisonFormats() {
  const comparisonDir = path.resolve(__dirname, '../reference/comparison')
  if (!fs.existsSync(comparisonDir)) {
    return []
  }
  const files = fs.readdirSync(comparisonDir)

  return files
    .filter(file => file.endsWith('.md') && file !== 'index.md')
    .map(file => {
      const name = file.replace('.md', '')
      const displayName = name.toUpperCase()
      return { text: displayName, link: `/reference/comparison/${name}` }
    })
    .sort((a, b) => a.text.localeCompare(b.text))
}

export default defineConfig({
  title: 'OxiDex',
  description: 'A Rust reimplementation of ExifTool, generated from and measured against the pinned ExifTool 13.59',
  lang: 'en-US',
  base: '/', // Custom domain (oxidex.net) serves from root
  outDir: '.vitepress/dist',
  cleanUrls: true,
  lastUpdated: true,

  themeConfig: {
    logo: '/logo.svg',
    siteTitle: 'OxiDex',

    nav: [
      { text: 'Guide', link: '/guide/' },
      { text: 'Reference', link: '/reference/' },
      { text: 'Architecture', link: '/architecture/' },
      { text: 'Performance', link: '/performance/' },
      // Generated by tools/docs/render_status.py (#837).
      { text: 'Status', link: '/status/' },
      {
        text: 'v2.0.0-beta.1',
        items: [
          {
            text: 'This release (beta)',
            items: [
              { text: 'Changelog', link: '/changelog' },
              { text: 'Migrating from 1.x to 2.0', link: '/guide/migrating-from-1x' },
              { text: 'Contributing', link: '/contributing/' }
            ]
          },
          {
            text: 'Previous stable',
            items: [
              { text: 'v1.2.1 release', link: 'https://github.com/swack-tools/oxidex/releases/tag/v1.2.1' },
              { text: 'v1.2.1 docs (source)', link: 'https://github.com/swack-tools/oxidex/tree/v1.2.1/docs' }
            ]
          }
        ]
      }
    ],

    sidebar: {
      '/guide/': [
        {
          text: 'Getting started',
          items: [
            { text: 'Introduction', link: '/guide/' },
            { text: 'Installation', link: '/guide/getting-started' },
            { text: 'Migrating from 1.x to 2.0', link: '/guide/migrating-from-1x' }
          ]
        },
        {
          text: 'Using OxiDex',
          items: [
            { text: 'Command line', link: '/guide/cli-usage' },
            { text: 'Rust library', link: '/guide/library-api' },
            { text: 'Writing metadata', link: '/guide/writing' },
            { text: 'MCP server', link: '/guide/mcp-integration' },
            { text: 'Troubleshooting', link: '/guide/troubleshooting' }
          ]
        },
        {
          text: 'Parity',
          items: [
            { text: 'ExifTool parity', link: '/guide/exiftool-parity' },
            { text: 'Supported formats', link: '/reference/formats/' },
            { text: 'Status', link: '/status/' }
          ]
        }
      ],
      '/reference/': [
        {
          text: 'Reference',
          items: [
            { text: 'Overview', link: '/reference/' },
            { text: 'Supported formats', link: '/reference/formats/' },
            { text: 'Rust API', link: '/reference/api-reference' },
            { text: 'C API', link: '/reference/ffi-api' },
            { text: 'MakerNotes', link: '/reference/makernotes' },
            { text: 'Camera RAW', link: '/reference/formats/camera-raw' },
            { text: 'Executables', link: '/reference/formats/pe-executable' },
            { text: 'Tag domains', link: '/tag-domains/' },
            { text: 'Packaging', link: '/reference/packaging/' }
          ]
        },
        {
          text: 'Parity reports (generated)',
          collapsed: false,
          items: [
            { text: 'ExifTool comparison', link: '/reference/comparison/' },
            { text: 'ExifTool coverage', link: '/reference/tag-coverage-analysis' },
            { text: 'Corpus read observations', link: '/reference/catalog-corpus-observed' },
            { text: 'Read and write observations', link: '/reference/catalog-hydrated-observed' },
            { text: 'JPEG tag support', link: '/reference/jpeg-tag-support' },
            { text: 'JPEG tag matrix', link: '/reference/jpeg-tag-matrix' },
            { text: 'Source catalog baseline', link: '/reference/catalog-baseline' },
            { text: 'Catalog to source ledger', link: '/reference/catalog-hydrated-join' },
            { text: 'Hydrated reader source', link: '/reference/hydrated-reader-layout-baseline' }
          ]
        },
        {
          text: 'Per-format comparison',
          collapsed: true,
          items: getComparisonFormats()
        },
        {
          text: 'Records',
          collapsed: true,
          items: [
            { text: 'All records and checkpoints', link: '/reference/#records-and-checkpoints' },
            { text: 'Upgrade rehearsal 11.78 / 12.64', link: '/reference/upgrade-rehearsal-11.78-12.64' },
            { text: 'Bump 13.55 → 13.59', link: '/reference/bump-reports/13.55-to-13.59' },
            { text: 'Bump 13.58 → 13.59', link: '/reference/bump-reports/13.58-to-13.59' },
            { text: 'BinaryData engine (Step 28)', link: '/reference/binary-data-engine' },
            { text: 'Metadata parity resume guide', link: '/reference/metadata-parity-resume' }
          ]
        }
      ],
      '/architecture/': [
        {
          text: 'Architecture',
          items: [
            { text: 'Overview', link: '/architecture/' },
            { text: 'Tag database', link: '/architecture/tag-database' },
            { text: 'oxidex-tags-shared', link: '/architecture/oxidex-tags-shared' },
            { text: 'Parser shared infrastructure', link: '/architecture/parser-shared-infrastructure' },
            { text: 'Parser migration guide', link: '/architecture/parser-migration-guide' }
          ]
        },
        {
          text: 'Generation',
          items: [
            { text: 'Transcription', link: '/TRANSCRIPTION' },
            { text: 'Autogeneration plan', link: '/AUTOGENERATION-PLAN' },
            { text: 'Autogeneration v2 design', link: '/AUTOGENERATION-V2-DESIGN' },
            { text: 'Autogeneration progress', link: '/AUTOGENERATION-PROGRESS' },
            { text: 'Upgrade rehearsal 11.78 / 12.64', link: '/reference/upgrade-rehearsal-11.78-12.64' },
            { text: 'Tag machinery status', link: '/TAG_MACHINERY_STATUS' }
          ]
        }
      ],
      '/performance/': [
        {
          text: 'Performance',
          items: [
            { text: 'Measured results', link: '/performance/' },
            { text: 'Benchmarks', link: '/performance/benchmarks' },
            { text: 'Profiling', link: '/performance/profiling' }
          ]
        }
      ],
      '/contributing/': [
        {
          text: 'Contributing',
          items: [
            { text: 'How work lands', link: '/contributing/' },
            { text: 'Measuring coverage', link: '/contributing/measuring-coverage' },
            { text: 'Docs site: build and deploy', link: '/contributing/docs-site' },
            { text: 'Release checklist', link: '/contributing/release-checklist' }
          ]
        },
        {
          text: 'Testing',
          items: [
            { text: 'Testing', link: '/contributing/testing/' },
            { text: 'Test failure triage', link: '/contributing/testing/TEST_FAILURE_TRIAGE' }
          ]
        },
        {
          text: 'Code',
          items: [
            { text: 'Code quality patterns', link: '/contributing/development/code-quality-patterns' },
            { text: 'TagRegistry refactoring', link: '/contributing/development/tagregistry-refactoring' }
          ]
        },
        {
          text: 'Direction',
          items: [
            { text: 'Autogeneration plan', link: '/AUTOGENERATION-PLAN' },
            { text: 'Autogeneration v2 design', link: '/AUTOGENERATION-V2-DESIGN' },
            { text: 'Autogeneration progress', link: '/AUTOGENERATION-PROGRESS' },
            { text: 'Transcription', link: '/TRANSCRIPTION' }
          ]
        }
      ],
      '/status/': [
        {
          text: 'Status',
          items: [
            { text: 'Autogeneration status', link: '/status/' },
            { text: 'Autogeneration plan', link: '/AUTOGENERATION-PLAN' },
            { text: 'Autogeneration progress', link: '/AUTOGENERATION-PROGRESS' },
            { text: 'Upgrade rehearsal 11.78 / 12.64', link: '/reference/upgrade-rehearsal-11.78-12.64' }
          ]
        }
      ],
      '/tag-domains/': [
        {
          text: 'Tag Domains',
          items: [
            { text: 'Overview', link: '/tag-domains/' },
            { text: 'Core', link: '/tag-domains/core' },
            { text: 'Camera', link: '/tag-domains/camera' },
            { text: 'Image', link: '/tag-domains/image' },
            { text: 'Media', link: '/tag-domains/media' },
            { text: 'Document', link: '/tag-domains/document' },
            { text: 'Specialty', link: '/tag-domains/specialty' }
          ]
        }
      ]
    },

    socialLinks: [
      { icon: 'github', link: 'https://github.com/swack-tools/oxidex' }
    ],

    footer: {
      message: 'Released under the GPL-3.0 License. OxiDex is an independent reimplementation of <a href="https://exiftool.org/">ExifTool</a> by Phil Harvey and is not affiliated with or endorsed by the ExifTool project.',
      copyright: 'Copyright © 2025-2026 OxiDex Contributors'
    },

    editLink: {
      pattern: 'https://github.com/swack-tools/oxidex/edit/main/docs/:path',
      text: 'Edit this page on GitHub'
    },

    search: {
      provider: 'local'
    },

    outline: [2, 3]
  },

  head: [
    ['link', { rel: 'icon', type: 'image/svg+xml', href: '/logo.svg' }],
    ['meta', { name: 'theme-color', content: '#dd7732' }],
    ['meta', { name: 'og:type', content: 'website' }],
    ['meta', { name: 'og:locale', content: 'en' }],
    ['meta', { name: 'og:site_name', content: 'OxiDex' }]
  ],

  markdown: {
    theme: {
      light: 'github-light',
      dark: 'github-dark'
    },
    lineNumbers: true,
    languageAlias: {
      'rust,ignore': 'rust',
      'rust,no_run': 'rust'
    }
  },

  ignoreDeadLinks: [
    // Benchmark reports - deployed separately by CI
    /^\/benchmarks\//
  ]
})
