#!/usr/bin/env perl
# Emit Rust source for the two big Olympus PrintConv hashes (CameraType2 and
# Equipment LensType) straight from ExifTool's own tables, so the Rust copy
# cannot drift from the Perl one through transcription.
use strict;
use warnings;
use lib '/tmp/oxidex-exiftool-cache/exiftool/lib';
use Image::ExifTool::Olympus;

sub esc {
    my $s = shift;
    $s =~ s/\\/\\\\/g;
    $s =~ s/"/\\"/g;
    return $s;
}

sub emit_str_map {
    my ($rust_name, $doc, $pc) = @_;
    my @keys = sort keys %$pc;
    printf("/// %s\n", $doc);
    printf("pub static %s: &[(&str, &str)] = &[\n", $rust_name);
    foreach my $k (@keys) {
        next if $k =~ /^(OTHER|BITMASK|Notes)$/;
        my $v = $pc->{$k};
        next if ref $v;
        printf("    (\"%s\", \"%s\"),\n", esc($k), esc($v));
    }
    print "];\n\n";
}

print "// GENERATED by scripts/gen_olympus_lookups.pl from ExifTool's\n";
print "// Image::ExifTool::Olympus tables. Do not edit by hand.\n\n";

my $eq = \%Image::ExifTool::Olympus::Equipment;
emit_str_map('CAMERA_TYPE2',
    'Olympus::Equipment 0x0100 CameraType2 PrintConv (keyed by the ASCII body code).',
    $eq->{0x100}{PrintConv});
emit_str_map('EQUIPMENT_LENS_TYPE',
    "Olympus::Equipment 0x0201 LensType PrintConv, keyed by ExifTool's\n/// `sprintf(\"%x %.2x %.2x\", \@bytes[0,2,3])` value conversion.",
    $eq->{0x201}{PrintConv});
emit_str_map('EQUIPMENT_EXTENDER',
    "Olympus::Equipment 0x0301 Extender PrintConv, keyed by ExifTool's\n/// `sprintf(\"%x %.2x\", \@bytes[0,2])` value conversion.",
    $eq->{0x301}{PrintConv});
