#!/usr/bin/env perl
# Emit Rust source for Samsung::Type2's two large PrintConv hashes straight
# from ExifTool's own table.
use strict;
use warnings;
use FindBin;
use lib "$FindBin::Bin/lib";
use ExiftoolPin;

# Resolves the pinned ExifTool tree via ExiftoolPin (never a PATH or Homebrew
# fallback -- see scripts/lib/ExiftoolPin.pm).
my $EXIFTOOL_LIB = ExiftoolPin::resolve();
eval "use lib '$EXIFTOOL_LIB'; use Image::ExifTool::Samsung; 1" or die $@;

sub esc { my $s = shift; $s =~ s/\\/\\\\/g; $s =~ s/"/\\"/g; return $s }

print "// GENERATED by scripts/gen_samsung_lookups.pl from ExifTool's\n";
print "// Image::ExifTool::Samsung::Type2 table. Do not edit by hand.\n\n";

my $t = \%Image::ExifTool::Samsung::Type2;
foreach my $spec (['DEVICE_TYPE', 0x0002, 'Samsung::Type2 0x0002 DeviceType PrintConv.'],
                  ['SAMSUNG_MODEL_ID', 0x0003, 'Samsung::Type2 0x0003 SamsungModelID PrintConv.']) {
    my ($name, $id, $doc) = @$spec;
    my $pc = $t->{$id}{PrintConv};
    printf("/// %s\npub static %s: &[(i64, &str)] = &[\n", $doc, $name);
    foreach my $k (sort { $a <=> $b } keys %$pc) {
        next if $k =~ /^(OTHER|BITMASK|Notes)$/;
        printf("    (%s, \"%s\"),\n", $k, esc($pc->{$k}));
    }
    print "];\n\n";
}
