//! ExifTool `Apple` IFD-style tables, generated from ExifTool
//! 13.59's own Perl hashes -- one file per module; `mod.rs` beside this
//! file is the hub that declares and re-exports it.
//!
//! DO NOT EDIT. Regenerate with `just regen-tables` (see `mod.rs`).

#![allow(clippy::unreadable_literal, clippy::too_many_lines, unused_parens)]

// Everything a table literal names -- the `ifd_schema` types, `ExprId`, the
// `cond`/`subdir`/`validation` imports -- is in scope in the hub, and a glob
// import of the parent module brings its private imports along (RFC 1560).
#[allow(unused_imports)]
use super::*;

/// `Image::ExifTool::Apple::Composite` -- 0 tags,
/// 0 `_variants` groups (IFD-style: PROCESS_PROC absent).
/// Generated from ExifTool's in-memory tag table. Do not edit by hand.
pub static IFD_APPLE_COMPOSITE: IfdTable = IfdTable {
    module: "Apple",
    table: "Composite",
    group0: "Composite",
    group1: "Composite",
    group2: "Camera",
    set_group1: None,
    priority: None,
    gate_a: GateA {
        blocked_by: &[("ifd_tag_id_unrepresentable", 1)],
    },
    tags: &[],
    variants: &[],
};

/// `Image::ExifTool::Apple::Main` -- 42 tags,
/// 0 `_variants` groups (IFD-style: PROCESS_PROC absent).
/// Generated from ExifTool's in-memory tag table. Do not edit by hand.
pub static IFD_APPLE_MAIN: IfdTable = IfdTable {
    module: "Apple",
    table: "Main",
    group0: "MakerNotes",
    group1: "Apple",
    group2: "Image",
    set_group1: None,
    priority: None,
    gate_a: GateA { blocked_by: &[] },
    tags: &[
        IfdTag {
            id: 0x0001,
            name: "MakerNoteVersion",
            format: None,
            count: None,
            writable: Some("int32s"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x0002,
            name: "AEMatrix",
            format: None,
            count: None,
            writable: None,
            groups: TagGroups::NONE,
            flags: IfdFlags {
                unknown: true,
                binary: false,
                list: false,
                protected: false,
                avoid: false,
                priority: None,
            },
            condition: None,
            omitted: Omitted {
                value_conv: true,
                raw_conv: false,
                condition: false,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x0003,
            name: "RunTime",
            format: None,
            count: None,
            writable: None,
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: false,
                condition: false,
                hook: false,
                subdirectory: true,
                print_conv: false,
            },
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: Some(IfdSubdirEdge {
                module: "Apple",
                table: "RunTime",
                start: IfdStart::ValuePtr(0),
                base: None,
                byte_order: IfdByteOrder::Inherit,
                fix_format: None,
                sub_ifd: false,
                max_subdirs: None,
                dir_name: None,
                validate: false,
                validation: None,
                processor: IfdSubdirProcessor::Native,
                unwalked: None,
            }),
        },
        IfdTag {
            id: 0x0004,
            name: "AEStable",
            format: None,
            count: None,
            writable: Some("int32s"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[(0, "No"), (1, "Yes")]),
            subdir: None,
        },
        IfdTag {
            id: 0x0005,
            name: "AETarget",
            format: None,
            count: None,
            writable: Some("int32s"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x0006,
            name: "AEAverage",
            format: None,
            count: None,
            writable: Some("int32s"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x0007,
            name: "AFStable",
            format: None,
            count: None,
            writable: Some("int32s"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[(0, "No"), (1, "Yes")]),
            subdir: None,
        },
        IfdTag {
            id: 0x0008,
            name: "AccelerationVector",
            format: None,
            count: Some(3),
            writable: Some("rational64s"),
            groups: TagGroups {
                g0: None,
                g1: None,
                g2: Some("Camera"),
            },
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x000a,
            name: "HDRImageType",
            format: None,
            count: None,
            writable: Some("int32s"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[(3, "HDR Image"), (4, "Original Image")]),
            subdir: None,
        },
        IfdTag {
            id: 0x000b,
            name: "BurstUUID",
            format: None,
            count: None,
            writable: Some("string"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x000c,
            name: "FocusDistanceRange",
            format: None,
            count: Some(2),
            writable: Some("rational64s"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: false,
                condition: false,
                hook: false,
                subdirectory: false,
                print_conv: true,
            },
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x000f,
            name: "OISMode",
            format: None,
            count: None,
            writable: Some("int32s"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x0011,
            name: "ContentIdentifier",
            format: None,
            count: None,
            writable: Some("string"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x0014,
            name: "ImageCaptureType",
            format: None,
            count: None,
            writable: Some("int32s"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[
                (1, "ProRAW"),
                (2, "Portrait"),
                (10, "Photo"),
                (11, "Manual Focus"),
                (12, "Scene"),
            ]),
            subdir: None,
        },
        IfdTag {
            id: 0x0015,
            name: "ImageUniqueID",
            format: None,
            count: None,
            writable: Some("string"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x0017,
            name: "LivePhotoVideoIndex",
            format: None,
            count: None,
            writable: None,
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x0019,
            name: "ImageProcessingFlags",
            format: None,
            count: None,
            writable: Some("int32s"),
            groups: TagGroups::NONE,
            flags: IfdFlags {
                unknown: true,
                binary: false,
                list: false,
                protected: false,
                avoid: false,
                priority: None,
            },
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::Bitmask {
                exact: &[],
                bits: &[],
            },
            subdir: None,
        },
        IfdTag {
            id: 0x001a,
            name: "QualityHint",
            format: None,
            count: None,
            writable: Some("string"),
            groups: TagGroups::NONE,
            flags: IfdFlags {
                unknown: true,
                binary: false,
                list: false,
                protected: false,
                avoid: false,
                priority: None,
            },
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x001d,
            name: "LuminanceNoiseAmplitude",
            format: None,
            count: None,
            writable: Some("rational64s"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x001f,
            name: "PhotosAppFeatureFlags",
            format: None,
            count: None,
            writable: Some("int32s"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x0020,
            name: "ImageCaptureRequestID",
            format: None,
            count: None,
            writable: Some("string"),
            groups: TagGroups::NONE,
            flags: IfdFlags {
                unknown: true,
                binary: false,
                list: false,
                protected: false,
                avoid: false,
                priority: None,
            },
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x0021,
            name: "HDRHeadroom",
            format: None,
            count: None,
            writable: Some("rational64s"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x0023,
            name: "AFPerformance",
            format: None,
            count: Some(2),
            writable: Some("int32s"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::Expr(ExprId::MyASplitValSprintfDDDA0A128A10xfffffff094C2B),
            subdir: None,
        },
        IfdTag {
            id: 0x0025,
            name: "SceneFlags",
            format: None,
            count: None,
            writable: Some("int32s"),
            groups: TagGroups::NONE,
            flags: IfdFlags {
                unknown: true,
                binary: false,
                list: false,
                protected: false,
                avoid: false,
                priority: None,
            },
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::Bitmask {
                exact: &[],
                bits: &[],
            },
            subdir: None,
        },
        IfdTag {
            id: 0x0026,
            name: "SignalToNoiseRatioType",
            format: None,
            count: None,
            writable: Some("int32s"),
            groups: TagGroups::NONE,
            flags: IfdFlags {
                unknown: true,
                binary: false,
                list: false,
                protected: false,
                avoid: false,
                priority: None,
            },
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x0027,
            name: "SignalToNoiseRatio",
            format: None,
            count: None,
            writable: Some("rational64s"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x002b,
            name: "PhotoIdentifier",
            format: None,
            count: None,
            writable: Some("string"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x002d,
            name: "ColorTemperature",
            format: None,
            count: None,
            writable: Some("int32s"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x002e,
            name: "CameraType",
            format: None,
            count: None,
            writable: Some("int32s"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[
                (0, "Back Wide Angle"),
                (1, "Back Normal"),
                (6, "Front"),
            ]),
            subdir: None,
        },
        IfdTag {
            id: 0x002f,
            name: "FocusPosition",
            format: None,
            count: None,
            writable: Some("int32s"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x0030,
            name: "HDRGain",
            format: None,
            count: None,
            writable: Some("rational64s"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x0038,
            name: "AFMeasuredDepth",
            format: None,
            count: None,
            writable: Some("int32s"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x003d,
            name: "AFConfidence",
            format: None,
            count: None,
            writable: Some("int32s"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x003e,
            name: "ColorCorrectionMatrix",
            format: None,
            count: None,
            writable: None,
            groups: TagGroups::NONE,
            flags: IfdFlags {
                unknown: true,
                binary: false,
                list: false,
                protected: false,
                avoid: false,
                priority: None,
            },
            condition: None,
            omitted: Omitted {
                value_conv: true,
                raw_conv: false,
                condition: false,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x003f,
            name: "GreenGhostMitigationStatus",
            format: None,
            count: None,
            writable: Some("int32s"),
            groups: TagGroups::NONE,
            flags: IfdFlags {
                unknown: true,
                binary: false,
                list: false,
                protected: false,
                avoid: false,
                priority: None,
            },
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x0040,
            name: "SemanticStyle",
            format: None,
            count: None,
            writable: None,
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted {
                value_conv: true,
                raw_conv: false,
                condition: false,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x0041,
            name: "SemanticStyleRenderingVer",
            format: None,
            count: None,
            writable: None,
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted {
                value_conv: true,
                raw_conv: false,
                condition: false,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x0042,
            name: "SemanticStylePreset",
            format: None,
            count: None,
            writable: None,
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted {
                value_conv: true,
                raw_conv: false,
                condition: false,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x004e,
            name: "Apple_0x004e",
            format: None,
            count: None,
            writable: None,
            groups: TagGroups::NONE,
            flags: IfdFlags {
                unknown: true,
                binary: false,
                list: false,
                protected: false,
                avoid: false,
                priority: None,
            },
            condition: None,
            omitted: Omitted {
                value_conv: true,
                raw_conv: false,
                condition: false,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x004f,
            name: "Apple_0x004f",
            format: None,
            count: None,
            writable: None,
            groups: TagGroups::NONE,
            flags: IfdFlags {
                unknown: true,
                binary: false,
                list: false,
                protected: false,
                avoid: false,
                priority: None,
            },
            condition: None,
            omitted: Omitted {
                value_conv: true,
                raw_conv: false,
                condition: false,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x0054,
            name: "Apple_0x0054",
            format: None,
            count: None,
            writable: None,
            groups: TagGroups::NONE,
            flags: IfdFlags {
                unknown: true,
                binary: false,
                list: false,
                protected: false,
                avoid: false,
                priority: None,
            },
            condition: None,
            omitted: Omitted {
                value_conv: true,
                raw_conv: false,
                condition: false,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x005a,
            name: "Apple_0x005a",
            format: None,
            count: None,
            writable: None,
            groups: TagGroups::NONE,
            flags: IfdFlags {
                unknown: true,
                binary: false,
                list: false,
                protected: false,
                avoid: false,
                priority: None,
            },
            condition: None,
            omitted: Omitted {
                value_conv: true,
                raw_conv: false,
                condition: false,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
    ],
    variants: &[],
};
