//! ExifTool `Casio` IFD-style tables, generated from ExifTool
//! 13.59's own Perl hashes -- one file per module; `mod.rs` beside this
//! file is the hub that declares and re-exports it.
//!
//! DO NOT EDIT. Regenerate with `just regen-tables` (see `mod.rs`).

#![allow(clippy::unreadable_literal, clippy::too_many_lines, unused_parens)]

// Everything a table literal names -- the `ifd_schema` types, `ExprId`, the
// `cond`/`subdir`/`validation` imports -- is in scope in the hub, and a glob
// import of the parent module brings its private imports along (RFC 1560).
#[allow(unused_imports)]
use super::*;

/// `Image::ExifTool::Casio::Main` -- 17 tags,
/// 1 `_variants` groups (IFD-style: PROCESS_PROC absent).
/// Generated from ExifTool's in-memory tag table. Do not edit by hand.
pub static IFD_CASIO_MAIN: IfdTable = IfdTable {
    module: "Casio",
    table: "Main",
    group0: "MakerNotes",
    group1: "Casio",
    group2: "Camera",
    set_group1: None,
    priority: None,
    gate_a: GateA { blocked_by: &[] },
    tags: &[
        IfdTag {
            id: 0x0001,
            name: "RecordingMode",
            format: None,
            count: None,
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[
                (1, "Single Shutter"),
                (2, "Panorama"),
                (3, "Night Scene"),
                (4, "Portrait"),
                (5, "Landscape"),
                (7, "Panorama"),
                (10, "Night Scene"),
                (15, "Portrait"),
                (16, "Landscape"),
            ]),
            subdir: None,
        },
        IfdTag {
            id: 0x0002,
            name: "Quality",
            format: None,
            count: None,
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[(1, "Economy"), (2, "Normal"), (3, "Fine")]),
            subdir: None,
        },
        IfdTag {
            id: 0x0003,
            name: "FocusMode",
            format: None,
            count: None,
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[
                (2, "Macro"),
                (3, "Auto"),
                (4, "Manual"),
                (5, "Infinity"),
                (7, "Spot AF"),
            ]),
            subdir: None,
        },
        IfdTag {
            id: 0x0005,
            name: "FlashIntensity",
            format: None,
            count: None,
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[
                (11, "Weak"),
                (12, "Low"),
                (13, "Normal"),
                (14, "High"),
                (15, "Strong"),
            ]),
            subdir: None,
        },
        IfdTag {
            id: 0x0006,
            name: "ObjectDistance",
            format: None,
            count: None,
            writable: Some("int32u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: Some(ExprId::Val1000F42638),
            print_conv: PrintConv::Expr(ExprId::ValM5C5F88),
            subdir: None,
        },
        IfdTag {
            id: 0x0007,
            name: "WhiteBalance",
            format: None,
            count: None,
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[
                (1, "Auto"),
                (2, "Tungsten"),
                (3, "Daylight"),
                (4, "Fluorescent"),
                (5, "Shade"),
                (129, "Manual"),
            ]),
            subdir: None,
        },
        IfdTag {
            id: 0x000a,
            name: "DigitalZoom",
            format: None,
            count: None,
            writable: Some("int32u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::PartialEnumInt {
                exact: &[
                    (65536, "Off"),
                    (65537, "2x"),
                    (104857, "1.6x"),
                    (131072, "2x"),
                    (209715, "3.2x"),
                    (262144, "4x"),
                ],
                other: None,
                print_hex: true,
            },
            subdir: None,
        },
        IfdTag {
            id: 0x000b,
            name: "Sharpness",
            format: None,
            count: None,
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[
                (0, "Normal"),
                (1, "Soft"),
                (2, "Hard"),
                (16, "Normal"),
                (17, "+1"),
                (18, "-1"),
            ]),
            subdir: None,
        },
        IfdTag {
            id: 0x000c,
            name: "Contrast",
            format: None,
            count: None,
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[
                (0, "Normal"),
                (1, "Low"),
                (2, "High"),
                (16, "Normal"),
                (17, "+1"),
                (18, "-1"),
            ]),
            subdir: None,
        },
        IfdTag {
            id: 0x000d,
            name: "Saturation",
            format: None,
            count: None,
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[
                (0, "Normal"),
                (1, "Low"),
                (2, "High"),
                (16, "Normal"),
                (17, "+1"),
                (18, "-1"),
            ]),
            subdir: None,
        },
        IfdTag {
            id: 0x0014,
            name: "ISO",
            format: None,
            count: None,
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags {
                unknown: false,
                binary: false,
                list: false,
                protected: false,
                avoid: false,
                priority: Some(0),
            },
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x0015,
            name: "FirmwareDate",
            format: Some(Fmt::Undef(0)),
            count: Some(18),
            writable: Some("string"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: false,
                condition: false,
                hook: false,
                subdirectory: false,
                print_conv: true,
            },
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x0016,
            name: "Enhancement",
            format: None,
            count: None,
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[
                (1, "Off"),
                (2, "Red"),
                (3, "Green"),
                (4, "Blue"),
                (5, "Flesh Tones"),
            ]),
            subdir: None,
        },
        IfdTag {
            id: 0x0017,
            name: "ColorFilter",
            format: None,
            count: None,
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[
                (1, "Off"),
                (2, "Black & White"),
                (3, "Sepia"),
                (4, "Red"),
                (5, "Green"),
                (6, "Blue"),
                (7, "Yellow"),
                (8, "Pink"),
                (9, "Purple"),
            ]),
            subdir: None,
        },
        IfdTag {
            id: 0x0018,
            name: "AFPoint",
            format: None,
            count: None,
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[
                (1, "Center"),
                (2, "Upper Left"),
                (3, "Upper Right"),
                (4, "Near Left/Right of Center"),
                (5, "Far Left/Right of Center"),
                (6, "Far Left/Right of Center/Bottom"),
                (7, "Top Near-left"),
                (8, "Near Upper/Left"),
                (9, "Top Near-right"),
                (10, "Top Left"),
                (11, "Top Center"),
                (12, "Top Right"),
                (13, "Center Left"),
                (14, "Center Right"),
                (15, "Bottom Left"),
                (16, "Bottom Center"),
                (17, "Bottom Right"),
            ]),
            subdir: None,
        },
        IfdTag {
            id: 0x0019,
            name: "FlashIntensity",
            format: None,
            count: None,
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[(1, "Normal"), (2, "Weak"), (3, "Strong")]),
            subdir: None,
        },
        IfdTag {
            id: 0x0e00,
            name: "PrintIM",
            format: None,
            count: None,
            writable: None,
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: false,
                condition: false,
                hook: false,
                subdirectory: true,
                print_conv: false,
            },
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: Some(IfdSubdirEdge {
                module: "PrintIM",
                table: "Main",
                start: IfdStart::ValuePtr(0),
                base: None,
                byte_order: IfdByteOrder::Inherit,
                fix_format: None,
                sub_ifd: false,
                max_subdirs: None,
                dir_name: None,
                validate: false,
                validation: None,
                processor: IfdSubdirProcessor::Native,
                unwalked: None,
            }),
        },
    ],
    variants: &[IfdVariantGroup {
        id: 0x0004,
        alternatives: &[
            (
                Cond::MemberRegex {
                    member: "Model",
                    pattern: "^QV-(3500EX|8000SX)",
                    ignore_case: false,
                    negate: false,
                },
                IfdTag {
                    id: 0x0004,
                    name: "FlashMode",
                    format: None,
                    count: None,
                    writable: Some("int16u"),
                    groups: TagGroups::NONE,
                    flags: IfdFlags::NONE,
                    condition: None,
                    omitted: Omitted::NONE,
                    raw_conv: None,
                    value_conv: None,
                    print_conv: PrintConv::IntEnum(&[
                        (1, "Auto"),
                        (2, "On"),
                        (3, "Off"),
                        (4, "Off"),
                        (5, "Red-eye Reduction"),
                    ]),
                    subdir: None,
                },
            ),
            (
                Cond::Always,
                IfdTag {
                    id: 0x0004,
                    name: "FlashMode",
                    format: None,
                    count: None,
                    writable: Some("int16u"),
                    groups: TagGroups::NONE,
                    flags: IfdFlags::NONE,
                    condition: None,
                    omitted: Omitted::NONE,
                    raw_conv: None,
                    value_conv: None,
                    print_conv: PrintConv::IntEnum(&[
                        (1, "Auto"),
                        (2, "On"),
                        (3, "Off"),
                        (4, "Red-eye Reduction"),
                    ]),
                    subdir: None,
                },
            ),
        ],
    }],
};

/// `Image::ExifTool::Casio::Type2` -- 45 tags,
/// 1 `_variants` groups (IFD-style: PROCESS_PROC absent).
/// Generated from ExifTool's in-memory tag table. Do not edit by hand.
pub static IFD_CASIO_TYPE2: IfdTable = IfdTable {
    module: "Casio",
    table: "Type2",
    group0: "MakerNotes",
    group1: "Casio",
    group2: "Camera",
    set_group1: None,
    priority: None,
    gate_a: GateA {
        blocked_by: &[
            ("tag_variant_cond_unsupported", 1),
            ("tag_variant_skipped", 1),
        ],
    },
    tags: &[
        IfdTag {
            id: 0x0002,
            name: "PreviewImageSize",
            format: None,
            count: Some(2),
            writable: Some("int16u"),
            groups: TagGroups {
                g0: None,
                g1: None,
                g2: Some("Image"),
            },
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: false,
                condition: false,
                hook: false,
                subdirectory: false,
                print_conv: true,
            },
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x0008,
            name: "QualityMode",
            format: None,
            count: None,
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[(0, "Economy"), (1, "Normal"), (2, "Fine")]),
            subdir: None,
        },
        IfdTag {
            id: 0x0009,
            name: "CasioImageSize",
            format: None,
            count: None,
            writable: Some("int16u"),
            groups: TagGroups {
                g0: None,
                g1: None,
                g2: Some("Image"),
            },
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[
                (0, "640x480"),
                (4, "1600x1200"),
                (5, "2048x1536"),
                (20, "2288x1712"),
                (21, "2592x1944"),
                (22, "2304x1728"),
                (36, "3008x2008"),
            ]),
            subdir: None,
        },
        IfdTag {
            id: 0x000d,
            name: "FocusMode",
            format: None,
            count: None,
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[(0, "Normal"), (1, "Macro")]),
            subdir: None,
        },
        IfdTag {
            id: 0x0014,
            name: "ISO",
            format: None,
            count: None,
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags {
                unknown: false,
                binary: false,
                list: false,
                protected: false,
                avoid: false,
                priority: Some(0),
            },
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[(3, "50"), (4, "64"), (6, "100"), (9, "200")]),
            subdir: None,
        },
        IfdTag {
            id: 0x0019,
            name: "WhiteBalance",
            format: None,
            count: None,
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[
                (0, "Auto"),
                (1, "Daylight"),
                (2, "Shade"),
                (3, "Tungsten"),
                (4, "Fluorescent"),
                (5, "Manual"),
            ]),
            subdir: None,
        },
        IfdTag {
            id: 0x001d,
            name: "FocalLength",
            format: None,
            count: None,
            writable: Some("rational64u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::Expr(ExprId::Sprintf1fMmVal03B2CA),
            subdir: None,
        },
        IfdTag {
            id: 0x001f,
            name: "Saturation",
            format: None,
            count: None,
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[(0, "Low"), (1, "Normal"), (2, "High")]),
            subdir: None,
        },
        IfdTag {
            id: 0x0020,
            name: "Contrast",
            format: None,
            count: None,
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[(0, "Low"), (1, "Normal"), (2, "High")]),
            subdir: None,
        },
        IfdTag {
            id: 0x0021,
            name: "Sharpness",
            format: None,
            count: None,
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[(0, "Soft"), (1, "Normal"), (2, "Hard")]),
            subdir: None,
        },
        IfdTag {
            id: 0x0e00,
            name: "PrintIM",
            format: None,
            count: None,
            writable: None,
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: false,
                condition: false,
                hook: false,
                subdirectory: true,
                print_conv: false,
            },
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: Some(IfdSubdirEdge {
                module: "PrintIM",
                table: "Main",
                start: IfdStart::ValuePtr(0),
                base: None,
                byte_order: IfdByteOrder::Inherit,
                fix_format: None,
                sub_ifd: false,
                max_subdirs: None,
                dir_name: None,
                validate: false,
                validation: None,
                processor: IfdSubdirProcessor::Native,
                unwalked: None,
            }),
        },
        IfdTag {
            id: 0x2001,
            name: "FirmwareDate",
            format: Some(Fmt::Undef(0)),
            count: Some(18),
            writable: Some("string"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: false,
                condition: false,
                hook: false,
                subdirectory: false,
                print_conv: true,
            },
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x2011,
            name: "WhiteBalanceBias",
            format: None,
            count: Some(2),
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x2012,
            name: "WhiteBalance",
            format: None,
            count: None,
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[
                (0, "Manual"),
                (1, "Daylight"),
                (2, "Cloudy"),
                (3, "Shade"),
                (4, "Flash?"),
                (6, "Fluorescent"),
                (9, "Tungsten?"),
                (10, "Tungsten"),
                (12, "Flash"),
            ]),
            subdir: None,
        },
        IfdTag {
            id: 0x2021,
            name: "AFPointPosition",
            format: None,
            count: Some(4),
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: false,
                condition: false,
                hook: false,
                subdirectory: false,
                print_conv: true,
            },
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x2022,
            name: "ObjectDistance",
            format: None,
            count: None,
            writable: Some("int32u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: false,
                condition: false,
                hook: false,
                subdirectory: false,
                print_conv: true,
            },
            raw_conv: None,
            value_conv: Some(ExprId::Val0x20000000InfVal1000E52085),
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x2034,
            name: "FlashDistance",
            format: None,
            count: None,
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x2076,
            name: "SpecialEffectMode",
            format: None,
            count: Some(3),
            writable: Some("int8u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::StrEnum(&[
                ("0 0 0", "Off"),
                ("1 0 0", "Makeup"),
                ("2 0 0", "Mist Removal"),
                ("3 0 0", "Vivid Landscape"),
            ]),
            subdir: None,
        },
        IfdTag {
            id: 0x211c,
            name: "FacesDetected",
            format: Some(Fmt::Int8u),
            count: None,
            writable: None,
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x3000,
            name: "RecordMode",
            format: None,
            count: None,
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::StrEnum(&[
                ("17", "Movie"),
                ("19", "Movie (19)"),
                ("2", "Program AE"),
                ("2 0", "Program AE"),
                ("20", "YouTube Movie"),
                ("3", "Shutter Priority"),
                ("3 0", "Shutter Priority"),
                ("4", "Aperture Priority"),
                ("4 0", "Aperture Priority"),
                ("5", "Manual"),
                ("5 0", "Manual"),
                ("6", "Best Shot"),
                ("6 0", "Best Shot"),
            ]),
            subdir: None,
        },
        IfdTag {
            id: 0x3001,
            name: "ReleaseMode",
            format: None,
            count: None,
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[
                (1, "Normal"),
                (3, "AE Bracketing"),
                (11, "WB Bracketing"),
                (13, "Contrast Bracketing"),
                (19, "High Speed Burst"),
            ]),
            subdir: None,
        },
        IfdTag {
            id: 0x3002,
            name: "Quality",
            format: None,
            count: None,
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[(1, "Economy"), (2, "Normal"), (3, "Fine")]),
            subdir: None,
        },
        IfdTag {
            id: 0x3003,
            name: "FocusMode",
            format: None,
            count: None,
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[
                (0, "Manual"),
                (1, "Focus Lock"),
                (2, "Macro"),
                (3, "Single-Area Auto Focus"),
                (5, "Infinity"),
                (6, "Multi-Area Auto Focus"),
                (8, "Super Macro"),
            ]),
            subdir: None,
        },
        IfdTag {
            id: 0x3006,
            name: "HometownCity",
            format: None,
            count: None,
            writable: Some("string"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x3008,
            name: "AutoISO",
            format: None,
            count: None,
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[
                (1, "On"),
                (2, "Off"),
                (7, "On (high sensitivity)"),
                (8, "On (anti-shake)"),
                (10, "High Speed"),
            ]),
            subdir: None,
        },
        IfdTag {
            id: 0x3009,
            name: "AFMode",
            format: None,
            count: None,
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[
                (0, "Off"),
                (1, "Spot"),
                (2, "Multi"),
                (3, "Face Detection"),
                (4, "Tracking"),
                (5, "Intelligent"),
            ]),
            subdir: None,
        },
        IfdTag {
            id: 0x3011,
            name: "Sharpness",
            format: Some(Fmt::Int16s),
            count: None,
            writable: Some("undef"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x3012,
            name: "Contrast",
            format: Some(Fmt::Int16s),
            count: None,
            writable: Some("undef"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x3013,
            name: "Saturation",
            format: Some(Fmt::Int16s),
            count: None,
            writable: Some("undef"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x3014,
            name: "ISO",
            format: None,
            count: None,
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags {
                unknown: false,
                binary: false,
                list: false,
                protected: false,
                avoid: false,
                priority: Some(0),
            },
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x3015,
            name: "ColorMode",
            format: None,
            count: None,
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[(0, "Off"), (2, "Black & White"), (3, "Sepia")]),
            subdir: None,
        },
        IfdTag {
            id: 0x3016,
            name: "Enhancement",
            format: None,
            count: None,
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[
                (0, "Off"),
                (1, "Scenery"),
                (3, "Green"),
                (5, "Underwater"),
                (9, "Flesh Tones"),
            ]),
            subdir: None,
        },
        IfdTag {
            id: 0x3017,
            name: "ColorFilter",
            format: None,
            count: None,
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[
                (0, "Off"),
                (1, "Blue"),
                (3, "Green"),
                (4, "Yellow"),
                (5, "Red"),
                (6, "Purple"),
                (7, "Pink"),
            ]),
            subdir: None,
        },
        IfdTag {
            id: 0x301b,
            name: "ArtMode",
            format: None,
            count: None,
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[
                (0, "Normal"),
                (8, "Silent Movie"),
                (39, "HDR"),
                (45, "Premium Auto"),
                (47, "Painting"),
                (49, "Crayon Drawing"),
                (51, "Panorama"),
                (52, "Art HDR"),
                (62, "High Speed Night Shot"),
                (64, "Monochrome"),
                (67, "Toy Camera"),
                (68, "Pop Art"),
                (69, "Light Tone"),
            ]),
            subdir: None,
        },
        IfdTag {
            id: 0x301c,
            name: "SequenceNumber",
            format: None,
            count: None,
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x301d,
            name: "BracketSequence",
            format: None,
            count: Some(2),
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x3020,
            name: "ImageStabilization",
            format: None,
            count: None,
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::StrEnum(&[
                ("0", "Off"),
                ("0 0", "Off"),
                ("0 1", "Off (1)"),
                ("0 3", "CCD Shift"),
                ("1", "On"),
                ("16 0", "Slow Shutter"),
                ("18 0", "Anti-Shake"),
                ("2", "Best Shot"),
                ("2 1", "High Sensitivity"),
                ("2 3", "CCD Shift + High Sensitivity"),
                ("20 0", "High Sensitivity"),
                ("3", "Movie Anti-Shake"),
            ]),
            subdir: None,
        },
        IfdTag {
            id: 0x302a,
            name: "LightingMode",
            format: None,
            count: None,
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[
                (0, "Off"),
                (1, "High Dynamic Range"),
                (5, "Shadow Enhance Low"),
                (6, "Shadow Enhance High"),
            ]),
            subdir: None,
        },
        IfdTag {
            id: 0x302b,
            name: "PortraitRefiner",
            format: None,
            count: None,
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[(0, "Off"), (1, "+1"), (2, "+2")]),
            subdir: None,
        },
        IfdTag {
            id: 0x3030,
            name: "SpecialEffectLevel",
            format: None,
            count: None,
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x3031,
            name: "SpecialEffectSetting",
            format: None,
            count: None,
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[
                (0, "Off"),
                (1, "Makeup"),
                (2, "Mist Removal"),
                (3, "Vivid Landscape"),
                (16, "Art Shot"),
            ]),
            subdir: None,
        },
        IfdTag {
            id: 0x3103,
            name: "DriveMode",
            format: None,
            count: None,
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: false,
                condition: false,
                hook: false,
                subdirectory: false,
                print_conv: true,
            },
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x310b,
            name: "ArtModeParameters",
            format: None,
            count: Some(3),
            writable: Some("int8u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x4001,
            name: "CaptureFrameRate",
            format: None,
            count: None,
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted {
                value_conv: true,
                raw_conv: false,
                condition: false,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x4003,
            name: "VideoQuality",
            format: None,
            count: None,
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[
                (1, "Standard"),
                (3, "HD (720p)"),
                (4, "Full HD (1080p)"),
                (5, "Low"),
            ]),
            subdir: None,
        },
    ],
    variants: &[IfdVariantGroup {
        id: 0x3007,
        alternatives: &[
            (
                Cond::MemberStrEq {
                    member: "Model",
                    value: "EX-FC100",
                    negate: false,
                },
                IfdTag {
                    id: 0x3007,
                    name: "BestShotMode",
                    format: None,
                    count: None,
                    writable: Some("int16u"),
                    groups: TagGroups::NONE,
                    flags: IfdFlags::NONE,
                    condition: None,
                    omitted: Omitted::NONE,
                    raw_conv: None,
                    value_conv: None,
                    print_conv: PrintConv::IntEnum(&[
                        (0, "Off"),
                        (1, "Auto"),
                        (2, "Portrait"),
                        (3, "Scenery"),
                        (4, "Portrait with Scenery"),
                        (5, "Children"),
                        (6, "Sports"),
                        (7, "Pet"),
                        (8, "Flower"),
                        (9, "Natural Green"),
                        (10, "Autumn Leaves"),
                        (11, "Sundown"),
                        (12, "High Speed Night Scene"),
                        (13, "Night Scene Portrait"),
                        (14, "Fireworks"),
                        (15, "High Speed Anti Shake"),
                        (16, "Multi-motion Image"),
                        (17, "High Speed Best Selection"),
                        (18, "Move Out CS"),
                        (19, "Move In CS"),
                        (20, "Pre-record Movie"),
                        (21, "For YouTube"),
                    ]),
                    subdir: None,
                },
            ),
            (
                Cond::MemberStrEq {
                    member: "Model",
                    value: "EX-FC150",
                    negate: false,
                },
                IfdTag {
                    id: 0x3007,
                    name: "BestShotMode",
                    format: None,
                    count: None,
                    writable: Some("int16u"),
                    groups: TagGroups::NONE,
                    flags: IfdFlags::NONE,
                    condition: None,
                    omitted: Omitted::NONE,
                    raw_conv: None,
                    value_conv: None,
                    print_conv: PrintConv::IntEnum(&[
                        (0, "Off"),
                        (1, "Auto"),
                        (2, "Expression CS"),
                        (3, "Baby CS"),
                        (4, "Child CS"),
                        (5, "Pet CS"),
                        (6, "Sports CS"),
                        (7, "Child High Speed Movie"),
                        (8, "Pet High Speed Movie"),
                        (9, "Sports High Speed Movie"),
                        (10, "Lag Correction"),
                        (11, "High Speed Lighting"),
                        (12, "High Speed Night Scene"),
                        (13, "High Speed Night Scene and Portrait"),
                        (14, "High Speed Anti Shake"),
                        (15, "High Speed Best Selection"),
                        (16, "Portrait"),
                        (17, "Scenery"),
                        (18, "Portrait with Scenery"),
                        (19, "Flower"),
                        (20, "Natural Green"),
                        (21, "Autumn Leaves"),
                        (22, "Sundown"),
                        (23, "Fireworks"),
                        (24, "Multi-motion Image"),
                        (25, "Move Out CS"),
                        (26, "Move In CS"),
                        (27, "Pre-record Movie"),
                        (28, "For YouTube"),
                    ]),
                    subdir: None,
                },
            ),
            (
                Cond::MemberStrEq {
                    member: "Model",
                    value: "EX-FC200S",
                    negate: false,
                },
                IfdTag {
                    id: 0x3007,
                    name: "BestShotMode",
                    format: None,
                    count: None,
                    writable: Some("int16u"),
                    groups: TagGroups::NONE,
                    flags: IfdFlags::NONE,
                    condition: None,
                    omitted: Omitted::NONE,
                    raw_conv: None,
                    value_conv: None,
                    print_conv: PrintConv::IntEnum(&[
                        (0, "Off"),
                        (1, "Slow Motion Swing (behind)"),
                        (2, "Slow Motion Swing (front)"),
                        (3, "Self Slow Motion (behind)"),
                        (4, "Self Slow Motion (front)"),
                        (5, "Swing Burst"),
                        (6, "HDR"),
                        (7, "HDR Art"),
                        (8, "High Speed Night Scene"),
                        (9, "High Speed Night Scene and Portrait"),
                        (10, "High Speed Anti Shake"),
                        (11, "Multi SR Zoom"),
                        (12, "Blurred Background"),
                        (13, "Wide Shot"),
                        (14, "Slide Panorama"),
                        (15, "High Speed Best Selection"),
                        (16, "Lag Correction"),
                        (17, "High Speed CS"),
                        (18, "Child CS"),
                        (19, "Pet CS"),
                        (20, "Sports CS"),
                        (21, "Child High Speed Movie"),
                        (22, "Pet High Speed Movie"),
                        (23, "Sports High Speed Movie"),
                        (24, "Portrait"),
                        (25, "Scenery"),
                        (26, "Portrait with Scenery"),
                        (27, "Children"),
                        (28, "Sports"),
                        (29, "Candlelight Portrait"),
                        (30, "Party"),
                        (31, "Pet"),
                        (32, "Flower"),
                        (33, "Natural Green"),
                        (34, "Autumn Leaves"),
                        (35, "Soft Flowing Water"),
                        (36, "Splashing Water"),
                        (37, "Sundown"),
                        (38, "Fireworks"),
                        (39, "Food"),
                        (40, "Text"),
                        (41, "Collection"),
                        (42, "Auction"),
                        (43, "Pre-record Movie"),
                        (44, "For YouTube"),
                    ]),
                    subdir: None,
                },
            ),
            (
                Cond::MemberStrEq {
                    member: "Model",
                    value: "EX-FH100",
                    negate: false,
                },
                IfdTag {
                    id: 0x3007,
                    name: "BestShotMode",
                    format: None,
                    count: None,
                    writable: Some("int16u"),
                    groups: TagGroups::NONE,
                    flags: IfdFlags::NONE,
                    condition: None,
                    omitted: Omitted::NONE,
                    raw_conv: None,
                    value_conv: None,
                    print_conv: PrintConv::IntEnum(&[
                        (0, "Off"),
                        (1, "Expression CS"),
                        (2, "Baby CS"),
                        (3, "Child CS"),
                        (4, "Pet CS"),
                        (5, "Sports CS"),
                        (6, "Child High Speed Movie"),
                        (7, "Pet High Speed Movie"),
                        (8, "Sports High Speed Movie"),
                        (9, "Lag Correction"),
                        (10, "High Speed Lighting"),
                        (11, "High Speed Night Scene"),
                        (12, "High Speed Night Scene and Portrait"),
                        (13, "High Speed Anti Shake"),
                        (14, "High Speed Best Selection"),
                        (15, "Portrait"),
                        (16, "Scenery"),
                        (17, "Portrait with Scenery"),
                        (18, "Flower"),
                        (19, "Natural Green"),
                        (20, "Autumn Leaves"),
                        (21, "Sundown"),
                        (22, "Fireworks"),
                        (23, "Multi-motion Image"),
                        (24, "Move Out CS"),
                        (25, "Move In CS"),
                        (26, "Pre-record Movie"),
                        (27, "For YouTube"),
                    ]),
                    subdir: None,
                },
            ),
            (
                Cond::MemberStrEq {
                    member: "Model",
                    value: "EX-G1",
                    negate: false,
                },
                IfdTag {
                    id: 0x3007,
                    name: "BestShotMode",
                    format: None,
                    count: None,
                    writable: Some("int16u"),
                    groups: TagGroups::NONE,
                    flags: IfdFlags::NONE,
                    condition: None,
                    omitted: Omitted::NONE,
                    raw_conv: None,
                    value_conv: None,
                    print_conv: PrintConv::IntEnum(&[
                        (0, "Off"),
                        (1, "Auto"),
                        (2, "Auto Best Shot"),
                        (3, "Dynamic Photo"),
                        (4, "Interval Snapshot"),
                        (5, "Interval Movie"),
                        (6, "Portrait"),
                        (7, "Scenery"),
                        (8, "Portrait with Scenery"),
                        (9, "Underwater"),
                        (10, "Beach"),
                        (11, "Snow"),
                        (12, "Children"),
                        (13, "Sports"),
                        (14, "Pet"),
                        (15, "Flower"),
                        (16, "Sundown"),
                        (17, "Night Scene"),
                        (18, "Night Scene Portrait"),
                        (19, "Fireworks"),
                        (20, "Food"),
                        (21, "For eBay"),
                        (22, "Multi-motion Image"),
                        (23, "Pre-record Movie"),
                        (24, "For YouTube"),
                        (25, "Voice Recording"),
                    ]),
                    subdir: None,
                },
            ),
            (
                Cond::MemberStrEq {
                    member: "Model",
                    value: "EX-S10",
                    negate: false,
                },
                IfdTag {
                    id: 0x3007,
                    name: "BestShotMode",
                    format: None,
                    count: None,
                    writable: Some("int16u"),
                    groups: TagGroups::NONE,
                    flags: IfdFlags::NONE,
                    condition: None,
                    omitted: Omitted::NONE,
                    raw_conv: None,
                    value_conv: None,
                    print_conv: PrintConv::IntEnum(&[
                        (0, "Off"),
                        (1, "Auto"),
                        (2, "Portrait"),
                        (3, "Scenery"),
                        (4, "Portrait with Scenery"),
                        (5, "Self-portrait (1 person)"),
                        (6, "Self-portrait (2 people)"),
                        (7, "Children"),
                        (8, "Sports"),
                        (9, "Candlelight Portrait"),
                        (10, "Party"),
                        (11, "Pet"),
                        (12, "Flower"),
                        (13, "Natural Green"),
                        (14, "Autumn Leaves"),
                        (15, "Soft Flowing Water"),
                        (16, "Splashing Water"),
                        (17, "Sundown"),
                        (18, "Night Scene"),
                        (19, "Night Scene Portrait"),
                        (20, "Fireworks"),
                        (21, "Food"),
                        (22, "Text"),
                        (23, "Collection"),
                        (24, "Auction"),
                        (25, "Backlight"),
                        (26, "Anti Shake"),
                        (27, "High Sensitivity"),
                        (28, "Underwater"),
                        (29, "Monochrome"),
                        (30, "Retro"),
                        (31, "Business Cards"),
                        (32, "White Board"),
                        (33, "Silent"),
                        (34, "Pre-record Movie"),
                        (35, "For YouTube"),
                        (36, "Voice Recording"),
                    ]),
                    subdir: None,
                },
            ),
            (
                Cond::MemberStrEq {
                    member: "Model",
                    value: "EX-S880",
                    negate: false,
                },
                IfdTag {
                    id: 0x3007,
                    name: "BestShotMode",
                    format: None,
                    count: None,
                    writable: Some("int16u"),
                    groups: TagGroups::NONE,
                    flags: IfdFlags::NONE,
                    condition: None,
                    omitted: Omitted::NONE,
                    raw_conv: None,
                    value_conv: None,
                    print_conv: PrintConv::IntEnum(&[
                        (0, "Off"),
                        (1, "Auto"),
                        (2, "Portrait"),
                        (3, "Scenery"),
                        (4, "Portrait with Scenery"),
                        (5, "Children"),
                        (6, "Sports"),
                        (7, "Candlelight Portrait"),
                        (8, "Party"),
                        (9, "Pet"),
                        (10, "Flower"),
                        (11, "Natural Green"),
                        (12, "Autumn Leaves"),
                        (13, "Soft Flowing Water"),
                        (14, "Splashing Water"),
                        (15, "Sundown"),
                        (16, "Night Scene"),
                        (17, "Night Scene Portrait"),
                        (18, "Fireworks"),
                        (19, "Food"),
                        (20, "Text"),
                        (21, "Collection"),
                        (22, "Auction"),
                        (23, "Backlight"),
                        (24, "Anti Shake"),
                        (25, "High Sensitivity"),
                        (26, "Monochrome"),
                        (27, "Retro"),
                        (28, "Twilight"),
                        (29, "Layout (2 images)"),
                        (30, "Layout (3 images)"),
                        (31, "Auto Framing"),
                        (32, "Old Photo"),
                        (33, "Business Cards"),
                        (34, "White Board"),
                        (35, "Silent"),
                        (36, "Short Movie"),
                        (37, "Past Movie"),
                        (38, "For YouTube"),
                        (39, "Voice Recording"),
                    ]),
                    subdir: None,
                },
            ),
            (
                Cond::MemberStrEq {
                    member: "Model",
                    value: "EX-Z16",
                    negate: false,
                },
                IfdTag {
                    id: 0x3007,
                    name: "BestShotMode",
                    format: None,
                    count: None,
                    writable: Some("int16u"),
                    groups: TagGroups::NONE,
                    flags: IfdFlags::NONE,
                    condition: None,
                    omitted: Omitted::NONE,
                    raw_conv: None,
                    value_conv: None,
                    print_conv: PrintConv::IntEnum(&[
                        (0, "Off"),
                        (1, "Auto"),
                        (2, "Portrait"),
                        (3, "Scenery"),
                        (4, "Portrait with Scenery"),
                        (5, "Children"),
                        (6, "Sports"),
                        (7, "Candlelight Portrait"),
                        (8, "Party"),
                        (9, "Pet"),
                        (10, "Flower"),
                        (11, "Soft Flowing Water"),
                        (12, "Sundown"),
                        (13, "Night Scene"),
                        (14, "Night Scene Portrait"),
                        (15, "Fireworks"),
                        (16, "Food"),
                        (17, "Text"),
                        (18, "For eBay"),
                        (19, "Backlight"),
                        (20, "Anti Shake"),
                        (21, "High Sensitivity"),
                        (22, "For YouTube"),
                        (23, "Voice Recording"),
                    ]),
                    subdir: None,
                },
            ),
            (
                Cond::MemberStrEq {
                    member: "Model",
                    value: "EX-Z9",
                    negate: false,
                },
                IfdTag {
                    id: 0x3007,
                    name: "BestShotMode",
                    format: None,
                    count: None,
                    writable: Some("int16u"),
                    groups: TagGroups::NONE,
                    flags: IfdFlags::NONE,
                    condition: None,
                    omitted: Omitted::NONE,
                    raw_conv: None,
                    value_conv: None,
                    print_conv: PrintConv::IntEnum(&[
                        (0, "Off"),
                        (1, "Auto"),
                        (2, "Movie"),
                        (3, "Portrait"),
                        (4, "Scenery"),
                        (5, "Children"),
                        (6, "Sports"),
                        (7, "Candlelight Portrait"),
                        (8, "Party"),
                        (9, "Pet"),
                        (10, "Flower"),
                        (11, "Soft Flowing Water"),
                        (12, "Sundown"),
                        (13, "Night Scene"),
                        (14, "Night Scene Portrait"),
                        (15, "Fireworks"),
                        (16, "Food"),
                        (17, "Text"),
                        (18, "Auction"),
                        (19, "Backlight"),
                        (20, "Anti Shake"),
                        (21, "High Sensitivity"),
                        (22, "For YouTube"),
                        (23, "Voice Recording"),
                    ]),
                    subdir: None,
                },
            ),
            (
                Cond::MemberStrEq {
                    member: "Model",
                    value: "EX-Z80",
                    negate: false,
                },
                IfdTag {
                    id: 0x3007,
                    name: "BestShotMode",
                    format: None,
                    count: None,
                    writable: Some("int16u"),
                    groups: TagGroups::NONE,
                    flags: IfdFlags::NONE,
                    condition: None,
                    omitted: Omitted::NONE,
                    raw_conv: None,
                    value_conv: None,
                    print_conv: PrintConv::IntEnum(&[
                        (0, "Off"),
                        (1, "Auto"),
                        (2, "Portrait"),
                        (3, "Scenery"),
                        (4, "Portrait with Scenery"),
                        (5, "Pet"),
                        (6, "Self-portrait (1 person)"),
                        (7, "Self-portrait (2 people)"),
                        (8, "Flower"),
                        (9, "Food"),
                        (10, "Fashion Accessories"),
                        (11, "Magazine"),
                        (12, "Monochrome"),
                        (13, "Retro"),
                        (14, "Cross Filter"),
                        (15, "Pastel"),
                        (16, "Night Scene"),
                        (17, "Night Scene Portrait"),
                        (18, "Party"),
                        (19, "Sports"),
                        (20, "Children"),
                        (21, "Sundown"),
                        (22, "Fireworks"),
                        (23, "Underwater"),
                        (24, "Backlight"),
                        (25, "High Sensitivity"),
                        (26, "Auction"),
                        (27, "White Board"),
                        (28, "Pre-record Movie"),
                        (29, "For YouTube"),
                        (30, "Voice Recording"),
                    ]),
                    subdir: None,
                },
            ),
            (
                Cond::MemberRegex {
                    member: "Model",
                    pattern: "^EX-Z(100|200)$",
                    ignore_case: false,
                    negate: false,
                },
                IfdTag {
                    id: 0x3007,
                    name: "BestShotMode",
                    format: None,
                    count: None,
                    writable: Some("int16u"),
                    groups: TagGroups::NONE,
                    flags: IfdFlags::NONE,
                    condition: None,
                    omitted: Omitted::NONE,
                    raw_conv: None,
                    value_conv: None,
                    print_conv: PrintConv::IntEnum(&[
                        (0, "Off"),
                        (1, "Auto"),
                        (2, "Auto Best Shot"),
                        (3, "Portrait"),
                        (4, "Scenery"),
                        (5, "Portrait with Scenery"),
                        (6, "Self-portrait (1 person)"),
                        (7, "Self-portrait (2 people)"),
                        (8, "Children"),
                        (9, "Sports"),
                        (10, "Candlelight Portrait"),
                        (11, "Party"),
                        (12, "Pet"),
                        (13, "Flower"),
                        (14, "Natural Green"),
                        (15, "Autumn Leaves"),
                        (16, "Soft Flowing Water"),
                        (17, "Splashing Water"),
                        (18, "Sundown"),
                        (19, "Night Scene"),
                        (20, "Night Scene Portrait"),
                        (21, "Fireworks"),
                        (22, "Food"),
                        (23, "Text"),
                        (24, "Collection"),
                        (25, "Auction"),
                        (26, "Backlight"),
                        (27, "Anti Shake"),
                        (28, "High Sensitivity"),
                        (29, "Underwater"),
                        (30, "Monochrome"),
                        (31, "Retro"),
                        (32, "Twilight"),
                        (33, "ID Photo"),
                        (34, "Business Cards"),
                        (35, "White Board"),
                        (36, "Silent"),
                        (37, "Pre-record Movie"),
                        (38, "For YouTube"),
                        (39, "Voice Recording"),
                    ]),
                    subdir: None,
                },
            ),
            (
                Cond::And(
                    &Cond::MemberStrEq {
                        member: "Model",
                        value: "EX-Z750",
                        negate: false,
                    },
                    &Cond::MemberStrEq {
                        member: "FILE_TYPE",
                        value: "JPEG",
                        negate: false,
                    },
                ),
                IfdTag {
                    id: 0x3007,
                    name: "BestShotMode",
                    format: None,
                    count: None,
                    writable: Some("int16u"),
                    groups: TagGroups::NONE,
                    flags: IfdFlags::NONE,
                    condition: None,
                    omitted: Omitted::NONE,
                    raw_conv: None,
                    value_conv: None,
                    print_conv: PrintConv::IntEnum(&[
                        (0, "Off"),
                        (1, "Portrait"),
                        (2, "Scenery"),
                        (3, "Portrait with Scenery"),
                        (4, "Children"),
                        (5, "Sports"),
                        (6, "Candlelight Portrait"),
                        (7, "Party"),
                        (8, "Pet"),
                        (9, "Flower"),
                        (10, "Natural Green"),
                        (11, "Soft Flowing Water"),
                        (12, "Splashing Water"),
                        (13, "Sundown"),
                        (14, "Night Scene"),
                        (15, "Night Scene Portrait"),
                        (16, "Fireworks"),
                        (17, "Food"),
                        (18, "Text"),
                        (19, "Collection"),
                        (20, "Backlight"),
                        (21, "Anti Shake"),
                        (22, "Pastel"),
                        (23, "Illustration"),
                        (24, "Cross Filter"),
                        (25, "Monochrome"),
                        (26, "Retro"),
                        (27, "Twilight"),
                        (28, "Old Photo"),
                        (29, "ID Photo"),
                        (30, "Business Cards"),
                        (31, "White Board"),
                    ]),
                    subdir: None,
                },
            ),
            (
                Cond::And(
                    &Cond::MemberStrEq {
                        member: "Model",
                        value: "EX-Z750",
                        negate: false,
                    },
                    &Cond::MemberRegex {
                        member: "FILE_TYPE",
                        pattern: "^(MOV|AVI)$",
                        ignore_case: false,
                        negate: false,
                    },
                ),
                IfdTag {
                    id: 0x3007,
                    name: "BestShotMode",
                    format: None,
                    count: None,
                    writable: Some("int16u"),
                    groups: TagGroups::NONE,
                    flags: IfdFlags::NONE,
                    condition: None,
                    omitted: Omitted::NONE,
                    raw_conv: None,
                    value_conv: None,
                    print_conv: PrintConv::IntEnum(&[
                        (0, "Off"),
                        (1, "Portrait"),
                        (2, "Scenery"),
                        (3, "Night Scene"),
                        (4, "Fireworks"),
                        (5, "Backlight"),
                        (6, "Silent"),
                    ]),
                    subdir: None,
                },
            ),
            (
                Cond::And(
                    &Cond::MemberStrEq {
                        member: "Model",
                        value: "EX-Z850",
                        negate: false,
                    },
                    &Cond::MemberStrEq {
                        member: "FILE_TYPE",
                        value: "JPEG",
                        negate: false,
                    },
                ),
                IfdTag {
                    id: 0x3007,
                    name: "BestShotMode",
                    format: None,
                    count: None,
                    writable: Some("int16u"),
                    groups: TagGroups::NONE,
                    flags: IfdFlags::NONE,
                    condition: None,
                    omitted: Omitted::NONE,
                    raw_conv: None,
                    value_conv: None,
                    print_conv: PrintConv::IntEnum(&[
                        (0, "Off"),
                        (1, "Portrait"),
                        (2, "Scenery"),
                        (3, "Portrait with Scenery"),
                        (4, "Children"),
                        (5, "Sports"),
                        (6, "Candlelight Portrait"),
                        (7, "Party"),
                        (8, "Pet"),
                        (9, "Flower"),
                        (10, "Natural Green"),
                        (11, "Autumn Leaves"),
                        (12, "Soft Flowing Water"),
                        (13, "Splashing Water"),
                        (14, "Sundown"),
                        (15, "Night Scene"),
                        (16, "Night Scene Portrait"),
                        (17, "Fireworks"),
                        (18, "Food"),
                        (19, "Text"),
                        (20, "Collection"),
                        (21, "For eBay"),
                        (22, "Backlight"),
                        (23, "Anti Shake"),
                        (24, "High Sensitivity"),
                        (25, "Pastel"),
                        (26, "Illustration"),
                        (27, "Cross Filter"),
                        (28, "Monochrome"),
                        (29, "Retro"),
                        (30, "Twilight"),
                        (31, "ID Photo"),
                        (32, "Old Photo"),
                        (33, "Business Cards"),
                        (34, "White Board"),
                    ]),
                    subdir: None,
                },
            ),
            (
                Cond::And(
                    &Cond::MemberStrEq {
                        member: "Model",
                        value: "EX-Z850",
                        negate: false,
                    },
                    &Cond::MemberRegex {
                        member: "FILE_TYPE",
                        pattern: "^(MOV|AVI)$",
                        ignore_case: false,
                        negate: false,
                    },
                ),
                IfdTag {
                    id: 0x3007,
                    name: "BestShotMode",
                    format: None,
                    count: None,
                    writable: Some("int16u"),
                    groups: TagGroups::NONE,
                    flags: IfdFlags::NONE,
                    condition: None,
                    omitted: Omitted::NONE,
                    raw_conv: None,
                    value_conv: None,
                    print_conv: PrintConv::IntEnum(&[
                        (0, "Off"),
                        (1, "Portrait"),
                        (2, "Scenery"),
                        (3, "Night Scene"),
                        (4, "Fireworks"),
                        (5, "Backlight"),
                        (6, "High Sensitivity"),
                        (7, "Silent"),
                        (8, "Short Movie"),
                        (9, "Past Movie"),
                    ]),
                    subdir: None,
                },
            ),
            (
                Cond::MemberStrEq {
                    member: "Model",
                    value: "EX-Z1050",
                    negate: false,
                },
                IfdTag {
                    id: 0x3007,
                    name: "BestShotMode",
                    format: None,
                    count: None,
                    writable: Some("int16u"),
                    groups: TagGroups::NONE,
                    flags: IfdFlags::NONE,
                    condition: None,
                    omitted: Omitted::NONE,
                    raw_conv: None,
                    value_conv: None,
                    print_conv: PrintConv::IntEnum(&[
                        (0, "Off"),
                        (1, "Auto"),
                        (2, "Movie"),
                        (3, "Portrait"),
                        (4, "Scenery"),
                        (5, "Portrait with Scenery"),
                        (6, "Children"),
                        (7, "Sports"),
                        (8, "Candlelight Portrait"),
                        (9, "Party"),
                        (10, "Pet"),
                        (11, "Flower"),
                        (12, "Natural Green"),
                        (13, "Autumn Leaves"),
                        (14, "Soft Flowing Water"),
                        (15, "Splashing Water"),
                        (16, "Sundown"),
                        (17, "Night Scene"),
                        (18, "Night Scene Portrait"),
                        (19, "Fireworks"),
                        (20, "Food"),
                        (21, "Text"),
                        (22, "Collection"),
                        (23, "For eBay"),
                        (24, "Backlight"),
                        (25, "Anti Shake"),
                        (26, "High Sensitivity"),
                        (27, "Underwater"),
                        (28, "Monochrome"),
                        (29, "Retro"),
                        (30, "Twilight"),
                        (31, "Layout (2 images)"),
                        (32, "Layout (3 images)"),
                        (33, "Auto Framing"),
                        (34, "ID Photo"),
                        (35, "Old Photo"),
                        (36, "Business Cards"),
                        (37, "White Board"),
                        (38, "Voice Recording"),
                    ]),
                    subdir: None,
                },
            ),
            (
                Cond::MemberStrEq {
                    member: "Model",
                    value: "EX-Z1080",
                    negate: false,
                },
                IfdTag {
                    id: 0x3007,
                    name: "BestShotMode",
                    format: None,
                    count: None,
                    writable: Some("int16u"),
                    groups: TagGroups::NONE,
                    flags: IfdFlags::NONE,
                    condition: None,
                    omitted: Omitted::NONE,
                    raw_conv: None,
                    value_conv: None,
                    print_conv: PrintConv::IntEnum(&[
                        (0, "Off"),
                        (1, "Auto"),
                        (2, "Movie"),
                        (3, "Portrait"),
                        (4, "Scenery"),
                        (5, "Portrait with Scenery"),
                        (6, "Children"),
                        (7, "Sports"),
                        (8, "Candlelight Portrait"),
                        (9, "Party"),
                        (10, "Pet"),
                        (11, "Flower"),
                        (12, "Natural Green"),
                        (13, "Autumn Leaves"),
                        (14, "Soft Flowing Water"),
                        (15, "Splashing Water"),
                        (16, "Sundown"),
                        (17, "Night Scene"),
                        (18, "Night Scene Portrait"),
                        (19, "Fireworks"),
                        (20, "Food"),
                        (21, "Text"),
                        (22, "Collection"),
                        (23, "For eBay"),
                        (24, "Backlight"),
                        (25, "Anti Shake"),
                        (26, "High Sensitivity"),
                        (27, "Underwater"),
                        (28, "Monochrome"),
                        (29, "Retro"),
                        (30, "Twilight"),
                        (31, "Layout (2 images)"),
                        (32, "Layout (3 images)"),
                        (33, "Auto Framing"),
                        (34, "ID Photo"),
                        (35, "Old Photo"),
                        (36, "Business Cards"),
                        (37, "White Board"),
                        (38, "Short Movie"),
                        (39, "Past Movie"),
                        (40, "For YouTube"),
                        (41, "Voice Recording"),
                    ]),
                    subdir: None,
                },
            ),
            (
                Cond::And(
                    &Cond::MemberStrEq {
                        member: "Model",
                        value: "EX-Z1200",
                        negate: false,
                    },
                    &Cond::MemberStrEq {
                        member: "FILE_TYPE",
                        value: "JPEG",
                        negate: false,
                    },
                ),
                IfdTag {
                    id: 0x3007,
                    name: "BestShotMode",
                    format: None,
                    count: None,
                    writable: Some("int16u"),
                    groups: TagGroups::NONE,
                    flags: IfdFlags::NONE,
                    condition: None,
                    omitted: Omitted::NONE,
                    raw_conv: None,
                    value_conv: None,
                    print_conv: PrintConv::IntEnum(&[
                        (0, "Off"),
                        (1, "Portrait"),
                        (2, "Scenery"),
                        (3, "Portrait with Scenery"),
                        (4, "Children"),
                        (5, "Sports"),
                        (6, "Candlelight Portrait"),
                        (7, "Party"),
                        (8, "Pet"),
                        (9, "Flower"),
                        (10, "Natural Green"),
                        (11, "Autumn Leaves"),
                        (12, "Soft Flowing Water"),
                        (13, "Splashing Water"),
                        (14, "Sundown"),
                        (15, "Night Scene"),
                        (16, "Night Scene Portrait"),
                        (17, "Fireworks"),
                        (18, "Food"),
                        (19, "Text"),
                        (20, "Collection"),
                        (21, "Auction"),
                        (22, "Backlight"),
                        (23, "High Sensitivity"),
                        (24, "Underwater"),
                        (25, "Monochrome"),
                        (26, "Retro"),
                        (27, "Twilight"),
                        (28, "Layout (2 images)"),
                        (29, "Layout (3 images)"),
                        (30, "Auto Framing"),
                        (31, "ID Photo"),
                        (32, "Old Photo"),
                        (33, "Business Cards"),
                        (34, "White Board"),
                    ]),
                    subdir: None,
                },
            ),
            (
                Cond::And(
                    &Cond::MemberStrEq {
                        member: "Model",
                        value: "EX-Z1200",
                        negate: false,
                    },
                    &Cond::MemberRegex {
                        member: "FILE_TYPE",
                        pattern: "^(MOV|AVI)$",
                        ignore_case: false,
                        negate: false,
                    },
                ),
                IfdTag {
                    id: 0x3007,
                    name: "BestShotMode",
                    format: None,
                    count: None,
                    writable: Some("int16u"),
                    groups: TagGroups::NONE,
                    flags: IfdFlags::NONE,
                    condition: None,
                    omitted: Omitted::NONE,
                    raw_conv: None,
                    value_conv: None,
                    print_conv: PrintConv::IntEnum(&[
                        (0, "Off"),
                        (1, "Portrait"),
                        (2, "Scenery"),
                        (3, "Night Scene"),
                        (4, "Fireworks"),
                        (5, "Backlight"),
                        (6, "High Sensitivity"),
                        (7, "Silent"),
                        (8, "Short Movie"),
                        (9, "Past Movie"),
                    ]),
                    subdir: None,
                },
            ),
            (
                Cond::MemberStrEq {
                    member: "Model",
                    value: "EX-Z2000",
                    negate: false,
                },
                IfdTag {
                    id: 0x3007,
                    name: "BestShotMode",
                    format: None,
                    count: None,
                    writable: Some("int16u"),
                    groups: TagGroups::NONE,
                    flags: IfdFlags::NONE,
                    condition: None,
                    omitted: Omitted::NONE,
                    raw_conv: None,
                    value_conv: None,
                    print_conv: PrintConv::IntEnum(&[
                        (0, "Off"),
                        (1, "Auto"),
                        (2, "Premium Auto"),
                        (3, "Dynamic Photo"),
                        (4, "Portrait"),
                        (5, "Scenery"),
                        (6, "Portrait with Scenery"),
                        (7, "Children"),
                        (8, "Sports"),
                        (9, "Candlelight Portrait"),
                        (10, "Party"),
                        (11, "Pet"),
                        (12, "Flower"),
                        (13, "Natural Green"),
                        (14, "Autumn Leaves"),
                        (15, "Soft Flowing Water"),
                        (16, "Splashing Water"),
                        (17, "Sundown"),
                        (18, "Night Scene"),
                        (19, "Night Scene Portrait"),
                        (20, "Fireworks"),
                        (21, "Food"),
                        (22, "Text"),
                        (23, "Collection"),
                        (24, "For eBay"),
                        (25, "Backlight"),
                        (26, "High Sensitivity"),
                        (27, "Oil Painting"),
                        (28, "Crayon"),
                        (29, "Water Color"),
                        (30, "Monochrome"),
                        (31, "Retro"),
                        (32, "Twilight"),
                        (33, "Multi-motion Image"),
                        (34, "ID Photo"),
                        (35, "Business Cards"),
                        (36, "White Board"),
                        (37, "Silent"),
                        (38, "Pre-record Movie"),
                        (39, "For YouTube"),
                        (40, "Voice Recording"),
                    ]),
                    subdir: None,
                },
            ),
            (
                Cond::MemberStrEq {
                    member: "Model",
                    value: "EX-Z2300",
                    negate: false,
                },
                IfdTag {
                    id: 0x3007,
                    name: "BestShotMode",
                    format: None,
                    count: None,
                    writable: Some("int16u"),
                    groups: TagGroups::NONE,
                    flags: IfdFlags::NONE,
                    condition: None,
                    omitted: Omitted::NONE,
                    raw_conv: None,
                    value_conv: None,
                    print_conv: PrintConv::IntEnum(&[
                        (0, "Off"),
                        (1, "Auto"),
                        (2, "Premium Auto"),
                        (3, "Dynamic Photo"),
                        (4, "Portrait"),
                        (5, "Scenery"),
                        (6, "Portrait with Scenery"),
                        (7, "Children"),
                        (8, "Sports"),
                        (9, "Candlelight Portrait"),
                        (10, "Party"),
                        (11, "Pet"),
                        (12, "Flower"),
                        (13, "Natural Green"),
                        (14, "Autumn Leaves"),
                        (15, "Soft Flowing Water"),
                        (16, "Splashing Water"),
                        (17, "Sundown"),
                        (18, "Night Scene"),
                        (19, "Night Scene Portrait"),
                        (20, "Fireworks"),
                        (21, "Food"),
                        (22, "Text"),
                        (23, "Collection"),
                        (24, "Auction"),
                        (25, "Backlight"),
                        (26, "High Sensitivity"),
                        (27, "Oil Painting"),
                        (28, "Crayon"),
                        (29, "Water Color"),
                        (30, "Monochrome"),
                        (31, "Retro"),
                        (32, "Twilight"),
                        (33, "Multi-motion Image"),
                        (34, "ID Photo"),
                        (35, "Business Cards"),
                        (36, "White Board"),
                        (37, "Silent"),
                        (38, "Pre-record Movie"),
                        (39, "For YouTube"),
                        (40, "Voice Recording"),
                    ]),
                    subdir: None,
                },
            ),
            (
                Cond::MemberStrEq {
                    member: "Model",
                    value: "EX-Z3000",
                    negate: false,
                },
                IfdTag {
                    id: 0x3007,
                    name: "BestShotMode",
                    format: None,
                    count: None,
                    writable: Some("int16u"),
                    groups: TagGroups::NONE,
                    flags: IfdFlags::NONE,
                    condition: None,
                    omitted: Omitted::NONE,
                    raw_conv: None,
                    value_conv: None,
                    print_conv: PrintConv::IntEnum(&[
                        (0, "Off"),
                        (1, "Portrait"),
                        (2, "Scenery"),
                        (3, "Portrait with Scenery"),
                        (4, "Children"),
                        (5, "Sports"),
                        (6, "Night Scene"),
                    ]),
                    subdir: None,
                },
            ),
            (
                Cond::MemberStrEq {
                    member: "Model",
                    value: "EX-ZR100",
                    negate: false,
                },
                IfdTag {
                    id: 0x3007,
                    name: "BestShotMode",
                    format: None,
                    count: None,
                    writable: Some("int16u"),
                    groups: TagGroups::NONE,
                    flags: IfdFlags::NONE,
                    condition: None,
                    omitted: Omitted::NONE,
                    raw_conv: None,
                    value_conv: None,
                    print_conv: PrintConv::IntEnum(&[
                        (0, "Off"),
                        (1, "Child CS"),
                        (2, "Pet CS"),
                        (3, "Sports CS"),
                        (4, "Child High Speed Movie"),
                        (5, "Pet High Speed Movie"),
                        (6, "Sports High Speed Movie"),
                        (7, "Multi SR Zoom"),
                        (8, "Lag Correction"),
                        (9, "High Speed Night Scene"),
                        (10, "High Speed Night Scene and Portrait"),
                        (11, "High Speed Anti Shake"),
                        (12, "Portrait"),
                        (13, "Scenery"),
                        (14, "Portrait with Scenery"),
                        (15, "Children"),
                        (16, "Sports"),
                        (17, "Candlelight Portrait"),
                        (18, "Party"),
                        (19, "Pet"),
                        (20, "Flower"),
                        (21, "Natural Green"),
                        (22, "Autumn Leaves"),
                        (23, "Soft Flowing Water"),
                        (24, "Splashing Water"),
                        (25, "Sundown"),
                        (26, "Fireworks"),
                        (27, "Food"),
                        (28, "Text"),
                        (29, "Collection"),
                        (30, "For eBay"),
                        (31, "Pre-record Movie"),
                        (32, "For YouTube"),
                    ]),
                    subdir: None,
                },
            ),
            (
                Cond::MemberStrEq {
                    member: "Model",
                    value: "EX-ZR200",
                    negate: false,
                },
                IfdTag {
                    id: 0x3007,
                    name: "BestShotMode",
                    format: None,
                    count: None,
                    writable: Some("int16u"),
                    groups: TagGroups::NONE,
                    flags: IfdFlags::NONE,
                    condition: None,
                    omitted: Omitted::NONE,
                    raw_conv: None,
                    value_conv: None,
                    print_conv: PrintConv::IntEnum(&[
                        (0, "Off"),
                        (1, "High Speed Night Scene"),
                        (2, "High Speed Night Scene and Portrait"),
                        (3, "High Speed Anti Shake"),
                        (4, "Blurred Background"),
                        (5, "Wide Shot"),
                        (6, "High Speed Best Selection"),
                        (7, "Lag Correction"),
                        (8, "Child CS"),
                        (9, "Pet CS"),
                        (10, "Sports CS"),
                        (11, "Child High Speed Movie"),
                        (12, "Pet High Speed Movie"),
                        (13, "Sports High Speed Movie"),
                        (14, "Portrait"),
                        (15, "Scenery"),
                        (16, "Portrait with Scenery"),
                        (17, "Children"),
                        (18, "Sports"),
                        (19, "Candlelight Portrait"),
                        (20, "Party"),
                        (21, "Pet"),
                        (22, "Flower"),
                        (23, "Natural Green"),
                        (24, "Autumn Leaves"),
                        (25, "Soft Flowing Water"),
                        (26, "Splashing Water"),
                        (27, "Sundown"),
                        (28, "Fireworks"),
                        (29, "Food"),
                        (30, "Text"),
                        (31, "Collection"),
                        (32, "Auction"),
                        (33, "Pre-record Movie"),
                        (34, "For YouTube"),
                    ]),
                    subdir: None,
                },
            ),
            (
                Cond::MemberStrEq {
                    member: "Model",
                    value: "QV-4000",
                    negate: false,
                },
                IfdTag {
                    id: 0x3007,
                    name: "BestShotMode",
                    format: None,
                    count: None,
                    writable: Some("int16u"),
                    groups: TagGroups::NONE,
                    flags: IfdFlags::NONE,
                    condition: None,
                    omitted: Omitted::NONE,
                    raw_conv: None,
                    value_conv: None,
                    print_conv: PrintConv::IntEnum(&[
                        (0, "Off"),
                        (1, "People"),
                        (2, "Scenery"),
                        (3, "Flower"),
                        (4, "Night Scene"),
                        (5, "Soft Focus"),
                    ]),
                    subdir: None,
                },
            ),
            (
                Cond::MemberStrEq {
                    member: "Model",
                    value: "EX-ZR300",
                    negate: false,
                },
                IfdTag {
                    id: 0x3007,
                    name: "BestShotMode",
                    format: None,
                    count: None,
                    writable: Some("int16u"),
                    groups: TagGroups::NONE,
                    flags: IfdFlags::NONE,
                    condition: None,
                    omitted: Omitted::NONE,
                    raw_conv: None,
                    value_conv: None,
                    print_conv: PrintConv::IntEnum(&[
                        (1, "High Speed Night Shot"),
                        (2, "Blurred Background"),
                        (3, "Toy Camera"),
                        (4, "Soft Focus"),
                        (5, "Light Tone"),
                        (6, "Pop"),
                        (7, "Sepia"),
                        (8, "Monochrome"),
                        (9, "Miniature"),
                        (10, "Wide Shot"),
                        (11, "High Speed Best Selection"),
                        (12, "Lag Correction"),
                        (13, "High Speed Night Scene"),
                        (14, "High Speed Night Scene and Portrait"),
                        (15, "High Speed Anti Shake"),
                        (16, "Portrait"),
                        (17, "Scenery"),
                        (18, "Portrait with Scenery"),
                        (19, "Children"),
                        (20, "Sports"),
                        (21, "Candlelight Portrait"),
                        (22, "Party"),
                        (23, "Pet"),
                        (24, "Flower"),
                        (25, "Natural Green"),
                        (26, "Autumn Leaves"),
                        (27, "Soft Flowing Water"),
                        (28, "Splashing Water"),
                        (29, "Sundown"),
                        (30, "Fireworks"),
                        (31, "Food"),
                        (32, "Text"),
                        (33, "Collection"),
                        (34, "Auction"),
                        (35, "Prerecord (Movie)"),
                        (36, "For YouTube"),
                    ]),
                    subdir: None,
                },
            ),
            (
                Cond::Always,
                IfdTag {
                    id: 0x3007,
                    name: "BestShotMode",
                    format: None,
                    count: None,
                    writable: Some("int16u"),
                    groups: TagGroups::NONE,
                    flags: IfdFlags::NONE,
                    condition: None,
                    omitted: Omitted::NONE,
                    raw_conv: None,
                    value_conv: None,
                    print_conv: PrintConv::Expr(ExprId::ValValOff65C593),
                    subdir: None,
                },
            ),
        ],
    }],
};
