//! ExifTool `DJI` IFD-style tables, generated from ExifTool
//! 13.59's own Perl hashes -- one file per module; `mod.rs` beside this
//! file is the hub that declares and re-exports it.
//!
//! DO NOT EDIT. Regenerate with `just regen-tables` (see `mod.rs`).

#![allow(clippy::unreadable_literal, clippy::too_many_lines, unused_parens)]

// Everything a table literal names -- the `ifd_schema` types, `ExprId`, the
// `cond`/`subdir`/`validation` imports -- is in scope in the hub, and a glob
// import of the parent module brings its private imports along (RFC 1560).
#[allow(unused_imports)]
use super::*;

/// `Image::ExifTool::DJI::Main` -- 10 tags,
/// 0 `_variants` groups (IFD-style: PROCESS_PROC absent).
/// Generated from ExifTool's in-memory tag table. Do not edit by hand.
pub static IFD_DJI_MAIN: IfdTable = IfdTable {
    module: "DJI",
    table: "Main",
    group0: "MakerNotes",
    group1: "DJI",
    group2: "Camera",
    set_group1: None,
    priority: None,
    gate_a: GateA { blocked_by: &[] },
    tags: &[
        IfdTag {
            id: 0x0001,
            name: "Make",
            format: None,
            count: None,
            writable: Some("string"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x0003,
            name: "SpeedX",
            format: None,
            count: None,
            writable: Some("float"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::Expr(ExprId::Sprintf2fVal8B5E04),
            subdir: None,
        },
        IfdTag {
            id: 0x0004,
            name: "SpeedY",
            format: None,
            count: None,
            writable: Some("float"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::Expr(ExprId::Sprintf2fVal8B5E04),
            subdir: None,
        },
        IfdTag {
            id: 0x0005,
            name: "SpeedZ",
            format: None,
            count: None,
            writable: Some("float"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::Expr(ExprId::Sprintf2fVal8B5E04),
            subdir: None,
        },
        IfdTag {
            id: 0x0006,
            name: "Pitch",
            format: None,
            count: None,
            writable: Some("float"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::Expr(ExprId::Sprintf2fVal8B5E04),
            subdir: None,
        },
        IfdTag {
            id: 0x0007,
            name: "Yaw",
            format: None,
            count: None,
            writable: Some("float"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::Expr(ExprId::Sprintf2fVal8B5E04),
            subdir: None,
        },
        IfdTag {
            id: 0x0008,
            name: "Roll",
            format: None,
            count: None,
            writable: Some("float"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::Expr(ExprId::Sprintf2fVal8B5E04),
            subdir: None,
        },
        IfdTag {
            id: 0x0009,
            name: "CameraPitch",
            format: None,
            count: None,
            writable: Some("float"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::Expr(ExprId::Sprintf2fVal8B5E04),
            subdir: None,
        },
        IfdTag {
            id: 0x000a,
            name: "CameraYaw",
            format: None,
            count: None,
            writable: Some("float"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::Expr(ExprId::Sprintf2fVal8B5E04),
            subdir: None,
        },
        IfdTag {
            id: 0x000b,
            name: "CameraRoll",
            format: None,
            count: None,
            writable: Some("float"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::Expr(ExprId::Sprintf2fVal8B5E04),
            subdir: None,
        },
    ],
    variants: &[],
};

/// `Image::ExifTool::DJI::XMP` -- 0 tags,
/// 0 `_variants` groups (IFD-style: PROCESS_PROC absent).
/// Generated from ExifTool's in-memory tag table. Do not edit by hand.
pub static IFD_DJI_XMP: IfdTable = IfdTable {
    module: "DJI",
    table: "XMP",
    group0: "XMP",
    group1: "XMP-drone-dji",
    group2: "Location",
    set_group1: None,
    priority: None,
    gate_a: GateA {
        blocked_by: &[("ifd_tag_id_unrepresentable", 29)],
    },
    tags: &[],
    variants: &[],
};
