//! ExifTool `EXE` IFD-style tables, generated from ExifTool
//! 13.59's own Perl hashes -- one file per module; `mod.rs` beside this
//! file is the hub that declares and re-exports it.
//!
//! DO NOT EDIT. Regenerate with `just regen-tables` (see `mod.rs`).

#![allow(clippy::unreadable_literal, clippy::too_many_lines, unused_parens)]

// Everything a table literal names -- the `ifd_schema` types, `ExprId`, the
// `cond`/`subdir`/`validation` imports -- is in scope in the hub, and a glob
// import of the parent module brings its private imports along (RFC 1560).
#[allow(unused_imports)]
use super::*;

/// `Image::ExifTool::EXE::MachO` -- 7 tags,
/// 0 `_variants` groups (IFD-style: PROCESS_PROC absent).
/// Generated from ExifTool's in-memory tag table. Do not edit by hand.
pub static IFD_EXE_MACHO: IfdTable = IfdTable {
    module: "EXE",
    table: "MachO",
    group0: "EXE",
    group1: "EXE",
    group2: "Other",
    set_group1: None,
    priority: None,
    gate_a: GateA { blocked_by: &[] },
    tags: &[
        IfdTag {
            id: 0x0000,
            name: "CPUArchitecture",
            format: None,
            count: None,
            writable: None,
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x0001,
            name: "CPUByteOrder",
            format: None,
            count: None,
            writable: None,
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x0002,
            name: "CPUCount",
            format: None,
            count: None,
            writable: None,
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x0003,
            name: "CPUType",
            format: None,
            count: None,
            writable: None,
            groups: TagGroups::NONE,
            flags: IfdFlags {
                unknown: false,
                binary: false,
                list: true,
                protected: false,
                avoid: false,
                priority: None,
            },
            condition: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: false,
                condition: false,
                hook: false,
                subdirectory: false,
                print_conv: true,
            },
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x0004,
            name: "CPUSubtype",
            format: None,
            count: None,
            writable: None,
            groups: TagGroups::NONE,
            flags: IfdFlags {
                unknown: false,
                binary: false,
                list: true,
                protected: false,
                avoid: false,
                priority: None,
            },
            condition: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: false,
                condition: false,
                hook: false,
                subdirectory: false,
                print_conv: true,
            },
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x0005,
            name: "ObjectFileType",
            format: None,
            count: None,
            writable: None,
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::PartialEnumInt {
                exact: &[
                    (-1, "Static library"),
                    (1, "Relocatable object"),
                    (2, "Demand paged executable"),
                    (3, "Fixed VM shared library"),
                    (4, "Core"),
                    (5, "Preloaded executable"),
                    (6, "Dynamically bound shared library"),
                    (7, "Dynamic link editor"),
                    (8, "Dynamically bound bundle"),
                    (9, "Shared library stub for static linking"),
                    (10, "Debug information"),
                    (11, "x86_64 kexts"),
                ],
                other: None,
                print_hex: true,
            },
            subdir: None,
        },
        IfdTag {
            id: 0x0006,
            name: "ObjectFlags",
            format: None,
            count: None,
            writable: None,
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::Bitmask {
                exact: &[],
                bits: &[
                    (0, "No undefs"),
                    (1, "Incrementa link"),
                    (2, "Dyld link"),
                    (3, "Bind at load"),
                    (4, "Prebound"),
                    (5, "Split segs"),
                    (6, "Lazy init"),
                    (7, "Two level"),
                    (8, "Force flat"),
                    (9, "No multi defs"),
                    (10, "No fix prebinding"),
                    (11, "Prebindable"),
                    (12, "All mods bound"),
                    (13, "Subsections via symbols"),
                    (14, "Canonical"),
                    (15, "Weak defines"),
                    (16, "Binds to weak"),
                    (17, "Allow stack execution"),
                    (18, "Dead strippable dylib"),
                    (19, "Root safe"),
                    (20, "No reexported dylibs"),
                    (21, "Random address"),
                ],
            },
            subdir: None,
        },
    ],
    variants: &[],
};

/// `Image::ExifTool::EXE::Misc` -- 1 tags,
/// 0 `_variants` groups (IFD-style: PROCESS_PROC absent).
/// Generated from ExifTool's in-memory tag table. Do not edit by hand.
pub static IFD_EXE_MISC: IfdTable = IfdTable {
    module: "EXE",
    table: "Misc",
    group0: "EXE",
    group1: "EXE",
    group2: "Other",
    set_group1: None,
    priority: None,
    gate_a: GateA { blocked_by: &[] },
    tags: &[IfdTag {
        id: 0x000c,
        name: "EXEFileName",
        format: None,
        count: None,
        writable: None,
        groups: TagGroups::NONE,
        flags: IfdFlags::NONE,
        condition: None,
        omitted: Omitted::NONE,
        raw_conv: None,
        value_conv: None,
        print_conv: PrintConv::None,
        subdir: None,
    }],
    variants: &[],
};

/// `Image::ExifTool::EXE::PEString` -- 0 tags,
/// 0 `_variants` groups (IFD-style: PROCESS_PROC absent).
/// Generated from ExifTool's in-memory tag table. Do not edit by hand.
pub static IFD_EXE_PESTRING: IfdTable = IfdTable {
    module: "EXE",
    table: "PEString",
    group0: "EXE",
    group1: "EXE",
    group2: "Other",
    set_group1: None,
    priority: None,
    gate_a: GateA {
        blocked_by: &[("ifd_tag_id_unrepresentable", 17)],
    },
    tags: &[],
    variants: &[],
};
