//! ExifTool `FujiFilm` IFD-style tables, generated from ExifTool
//! 13.59's own Perl hashes -- one file per module; `mod.rs` beside this
//! file is the hub that declares and re-exports it.
//!
//! DO NOT EDIT. Regenerate with `just regen-tables` (see `mod.rs`).

#![allow(clippy::unreadable_literal, clippy::too_many_lines, unused_parens)]

// Everything a table literal names -- the `ifd_schema` types, `ExprId`, the
// `cond`/`subdir`/`validation` imports -- is in scope in the hub, and a glob
// import of the parent module brings its private imports along (RFC 1560).
#[allow(unused_imports)]
use super::*;

/// `Image::ExifTool::FujiFilm::IFD` -- 11 tags,
/// 0 `_variants` groups (IFD-style: PROCESS_PROC Exif::ProcessExif).
/// Generated from ExifTool's in-memory tag table. Do not edit by hand.
pub static IFD_FUJIFILM_IFD: IfdTable = IfdTable {
    module: "FujiFilm",
    table: "IFD",
    group0: "RAF",
    group1: "FujiIFD",
    group2: "Image",
    set_group1: None,
    priority: None,
    gate_a: GateA { blocked_by: &[] },
    tags: &[
        IfdTag {
            id: 0xf000,
            name: "FujiIFD",
            format: None,
            count: None,
            writable: None,
            groups: TagGroups {
                g0: None,
                g1: Some("FujiIFD"),
                g2: None,
            },
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: false,
                condition: false,
                hook: false,
                subdirectory: true,
                print_conv: false,
            },
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: Some(IfdSubdirEdge {
                module: "FujiFilm",
                table: "IFD",
                start: IfdStart::Val(0),
                base: None,
                byte_order: IfdByteOrder::Inherit,
                fix_format: None,
                sub_ifd: true,
                max_subdirs: None,
                dir_name: Some("FujiSubIFD"),
                validate: false,
                validation: None,
                processor: IfdSubdirProcessor::Native,
                unwalked: None,
            }),
        },
        IfdTag {
            id: 0xf001,
            name: "RawImageFullWidth",
            format: None,
            count: None,
            writable: None,
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0xf002,
            name: "RawImageFullHeight",
            format: None,
            count: None,
            writable: None,
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0xf003,
            name: "BitsPerSample",
            format: None,
            count: None,
            writable: None,
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0xf00a,
            name: "BlackLevel",
            format: None,
            count: None,
            writable: None,
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0xf00b,
            name: "GeometricDistortionParams",
            format: None,
            count: None,
            writable: None,
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0xf00c,
            name: "WB_GRBLevelsStandard",
            format: None,
            count: None,
            writable: None,
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0xf00d,
            name: "WB_GRBLevelsAuto",
            format: None,
            count: None,
            writable: None,
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0xf00e,
            name: "WB_GRBLevels",
            format: None,
            count: None,
            writable: None,
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0xf00f,
            name: "ChromaticAberrationParams",
            format: None,
            count: None,
            writable: None,
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0xf010,
            name: "VignettingParams",
            format: None,
            count: None,
            writable: None,
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
    ],
    variants: &[],
};

/// `Image::ExifTool::FujiFilm::Main` -- 101 tags,
/// 1 `_variants` groups (IFD-style: PROCESS_PROC absent).
/// Generated from ExifTool's in-memory tag table. Do not edit by hand.
pub static IFD_FUJIFILM_MAIN: IfdTable = IfdTable {
    module: "FujiFilm",
    table: "Main",
    group0: "MakerNotes",
    group1: "FujiFilm",
    group2: "Camera",
    set_group1: None,
    priority: None,
    gate_a: GateA { blocked_by: &[] },
    tags: &[
        IfdTag {
            id: 0x0000,
            name: "Version",
            format: None,
            count: None,
            writable: Some("undef"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x0010,
            name: "InternalSerialNumber",
            format: None,
            count: None,
            writable: Some("string"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: false,
                condition: false,
                hook: false,
                subdirectory: false,
                print_conv: true,
            },
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x1000,
            name: "Quality",
            format: None,
            count: None,
            writable: Some("string"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x1001,
            name: "Sharpness",
            format: None,
            count: None,
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::PartialEnumInt {
                exact: &[
                    (0, "-4 (softest)"),
                    (1, "-3 (very soft)"),
                    (2, "-2 (soft)"),
                    (3, "0 (normal)"),
                    (4, "+2 (hard)"),
                    (5, "+3 (very hard)"),
                    (6, "+4 (hardest)"),
                    (130, "-1 (medium soft)"),
                    (132, "+1 (medium hard)"),
                    (32768, "Film Simulation"),
                    (65535, "n/a"),
                ],
                other: None,
                print_hex: true,
            },
            subdir: None,
        },
        IfdTag {
            id: 0x1002,
            name: "WhiteBalance",
            format: None,
            count: None,
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::PartialEnumInt {
                exact: &[
                    (0, "Auto"),
                    (1, "Auto (white priority)"),
                    (2, "Auto (ambiance priority)"),
                    (256, "Daylight"),
                    (512, "Cloudy"),
                    (768, "Daylight Fluorescent"),
                    (769, "Day White Fluorescent"),
                    (770, "White Fluorescent"),
                    (771, "Warm White Fluorescent"),
                    (772, "Living Room Warm White Fluorescent"),
                    (1024, "Incandescent"),
                    (1280, "Flash"),
                    (1536, "Underwater"),
                    (3840, "Custom"),
                    (3841, "Custom2"),
                    (3842, "Custom3"),
                    (3843, "Custom4"),
                    (3844, "Custom5"),
                    (4080, "Kelvin"),
                ],
                other: None,
                print_hex: true,
            },
            subdir: None,
        },
        IfdTag {
            id: 0x1003,
            name: "Saturation",
            format: None,
            count: None,
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::PartialEnumInt {
                exact: &[
                    (0, "0 (normal)"),
                    (128, "+1 (medium high)"),
                    (192, "+3 (very high)"),
                    (224, "+4 (highest)"),
                    (256, "+2 (high)"),
                    (384, "-1 (medium low)"),
                    (512, "Low"),
                    (768, "None (B&W)"),
                    (769, "B&W Red Filter"),
                    (770, "B&W Yellow Filter"),
                    (771, "B&W Green Filter"),
                    (784, "B&W Sepia"),
                    (1024, "-2 (low)"),
                    (1216, "-3 (very low)"),
                    (1248, "-4 (lowest)"),
                    (1280, "Acros"),
                    (1281, "Acros Red Filter"),
                    (1282, "Acros Yellow Filter"),
                    (1283, "Acros Green Filter"),
                    (32768, "Film Simulation"),
                ],
                other: None,
                print_hex: true,
            },
            subdir: None,
        },
        IfdTag {
            id: 0x1004,
            name: "Contrast",
            format: None,
            count: None,
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::PartialEnumInt {
                exact: &[
                    (0, "Normal"),
                    (128, "Medium High"),
                    (256, "High"),
                    (384, "Medium Low"),
                    (512, "Low"),
                    (32768, "Film Simulation"),
                ],
                other: None,
                print_hex: true,
            },
            subdir: None,
        },
        IfdTag {
            id: 0x1005,
            name: "ColorTemperature",
            format: None,
            count: None,
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x1006,
            name: "Contrast",
            format: None,
            count: None,
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::PartialEnumInt {
                exact: &[(0, "Normal"), (256, "High"), (768, "Low")],
                other: None,
                print_hex: true,
            },
            subdir: None,
        },
        IfdTag {
            id: 0x100a,
            name: "WhiteBalanceFineTune",
            format: None,
            count: Some(2),
            writable: Some("int32s"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::Expr(ExprId::SprintfRedDBlueDSplitVal6767DD),
            subdir: None,
        },
        IfdTag {
            id: 0x100b,
            name: "NoiseReduction",
            format: None,
            count: None,
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: true,
                condition: false,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::PartialEnumInt {
                exact: &[(64, "Low"), (128, "Normal"), (256, "n/a")],
                other: None,
                print_hex: true,
            },
            subdir: None,
        },
        IfdTag {
            id: 0x100e,
            name: "NoiseReduction",
            format: None,
            count: None,
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::PartialEnumInt {
                exact: &[
                    (0, "0 (normal)"),
                    (256, "+2 (strong)"),
                    (384, "+1 (medium strong)"),
                    (448, "+3 (very strong)"),
                    (480, "+4 (strongest)"),
                    (512, "-2 (weak)"),
                    (640, "-1 (medium weak)"),
                    (704, "-3 (very weak)"),
                    (736, "-4 (weakest)"),
                ],
                other: None,
                print_hex: true,
            },
            subdir: None,
        },
        IfdTag {
            id: 0x100f,
            name: "Clarity",
            format: None,
            count: None,
            writable: Some("int32s"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[
                (-5000, "-5"),
                (-4000, "-4"),
                (-3000, "-3"),
                (-2000, "-2"),
                (-1000, "-1"),
                (0, "0"),
                (1000, "1"),
                (2000, "2"),
                (3000, "3"),
                (4000, "4"),
                (5000, "5"),
            ]),
            subdir: None,
        },
        IfdTag {
            id: 0x1010,
            name: "FujiFlashMode",
            format: None,
            count: None,
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::PartialEnumInt {
                exact: &[
                    (0, "Auto"),
                    (1, "On"),
                    (2, "Off"),
                    (3, "Red-eye reduction"),
                    (4, "External"),
                    (16, "Commander"),
                    (32768, "Not Attached"),
                    (33056, "TTL"),
                    (33568, "TTL Auto - Did not fire"),
                    (38976, "Manual"),
                    (39008, "Flash Commander"),
                    (39040, "Multi-flash"),
                    (43296, "1st Curtain (front)"),
                    (43552, "TTL Slow - 1st Curtain (front)"),
                    (43808, "TTL Auto - 1st Curtain (front)"),
                    (44320, "TTL - Red-eye Flash - 1st Curtain (front)"),
                    (44576, "TTL Slow - Red-eye Flash - 1st Curtain (front)"),
                    (44832, "TTL Auto - Red-eye Flash - 1st Curtain (front)"),
                    (51488, "2nd Curtain (rear)"),
                    (51744, "TTL Slow - 2nd Curtain (rear)"),
                    (52000, "TTL Auto - 2nd Curtain (rear)"),
                    (52512, "TTL - Red-eye Flash - 2nd Curtain (rear)"),
                    (52768, "TTL Slow - Red-eye Flash - 2nd Curtain (rear)"),
                    (53024, "TTL Auto - Red-eye Flash - 2nd Curtain (rear)"),
                    (59680, "High Speed Sync (HSS)"),
                ],
                other: None,
                print_hex: true,
            },
            subdir: None,
        },
        IfdTag {
            id: 0x1011,
            name: "FlashExposureComp",
            format: None,
            count: None,
            writable: Some("rational64s"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x1020,
            name: "Macro",
            format: None,
            count: None,
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[(0, "Off"), (1, "On")]),
            subdir: None,
        },
        IfdTag {
            id: 0x1021,
            name: "FocusMode",
            format: None,
            count: None,
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[(0, "Auto"), (1, "Manual"), (65535, "Movie")]),
            subdir: None,
        },
        IfdTag {
            id: 0x1022,
            name: "AFMode",
            format: None,
            count: None,
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[
                (0, "No"),
                (1, "Single Point"),
                (256, "Zone"),
                (512, "Wide/Tracking"),
            ]),
            subdir: None,
        },
        IfdTag {
            id: 0x1023,
            name: "FocusPixel",
            format: None,
            count: Some(2),
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x102b,
            name: "PrioritySettings",
            format: None,
            count: None,
            writable: None,
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: false,
                condition: false,
                hook: false,
                subdirectory: true,
                print_conv: false,
            },
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: Some(IfdSubdirEdge {
                module: "FujiFilm",
                table: "PrioritySettings",
                start: IfdStart::ValuePtr(0),
                base: None,
                byte_order: IfdByteOrder::Inherit,
                fix_format: None,
                sub_ifd: false,
                max_subdirs: None,
                dir_name: None,
                validate: false,
                validation: None,
                processor: IfdSubdirProcessor::Native,
                unwalked: None,
            }),
        },
        IfdTag {
            id: 0x102d,
            name: "FocusSettings",
            format: None,
            count: None,
            writable: None,
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: false,
                condition: false,
                hook: false,
                subdirectory: true,
                print_conv: false,
            },
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: Some(IfdSubdirEdge {
                module: "FujiFilm",
                table: "FocusSettings",
                start: IfdStart::ValuePtr(0),
                base: None,
                byte_order: IfdByteOrder::Inherit,
                fix_format: None,
                sub_ifd: false,
                max_subdirs: None,
                dir_name: None,
                validate: false,
                validation: None,
                processor: IfdSubdirProcessor::Native,
                unwalked: None,
            }),
        },
        IfdTag {
            id: 0x102e,
            name: "AFCSettings",
            format: None,
            count: None,
            writable: None,
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: false,
                condition: false,
                hook: false,
                subdirectory: true,
                print_conv: false,
            },
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: Some(IfdSubdirEdge {
                module: "FujiFilm",
                table: "AFCSettings",
                start: IfdStart::ValuePtr(0),
                base: None,
                byte_order: IfdByteOrder::Inherit,
                fix_format: None,
                sub_ifd: false,
                max_subdirs: None,
                dir_name: None,
                validate: false,
                validation: None,
                processor: IfdSubdirProcessor::Native,
                unwalked: None,
            }),
        },
        IfdTag {
            id: 0x1030,
            name: "SlowSync",
            format: None,
            count: None,
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[(0, "Off"), (1, "On")]),
            subdir: None,
        },
        IfdTag {
            id: 0x1031,
            name: "PictureMode",
            format: None,
            count: None,
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::PartialEnumInt {
                exact: &[
                    (0, "Auto"),
                    (1, "Portrait"),
                    (2, "Landscape"),
                    (3, "Macro"),
                    (4, "Sports"),
                    (5, "Night Scene"),
                    (6, "Program AE"),
                    (7, "Natural Light"),
                    (8, "Anti-blur"),
                    (9, "Beach & Snow"),
                    (10, "Sunset"),
                    (11, "Museum"),
                    (12, "Party"),
                    (13, "Flower"),
                    (14, "Text"),
                    (15, "Natural Light & Flash"),
                    (16, "Beach"),
                    (17, "Snow"),
                    (18, "Fireworks"),
                    (19, "Underwater"),
                    (20, "Portrait with Skin Correction"),
                    (22, "Panorama"),
                    (23, "Night (tripod)"),
                    (24, "Pro Low-light"),
                    (25, "Pro Focus"),
                    (26, "Portrait 2"),
                    (27, "Dog Face Detection"),
                    (28, "Cat Face Detection"),
                    (48, "HDR"),
                    (64, "Advanced Filter"),
                    (256, "Aperture-priority AE"),
                    (512, "Shutter speed priority AE"),
                    (768, "Manual"),
                ],
                other: None,
                print_hex: true,
            },
            subdir: None,
        },
        IfdTag {
            id: 0x1032,
            name: "ExposureCount",
            format: None,
            count: None,
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x1033,
            name: "EXRAuto",
            format: None,
            count: None,
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[(0, "Auto"), (1, "Manual")]),
            subdir: None,
        },
        IfdTag {
            id: 0x1034,
            name: "EXRMode",
            format: None,
            count: None,
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::PartialEnumInt {
                exact: &[
                    (256, "HR (High Resolution)"),
                    (512, "SN (Signal to Noise priority)"),
                    (768, "DR (Dynamic Range priority)"),
                ],
                other: None,
                print_hex: true,
            },
            subdir: None,
        },
        IfdTag {
            id: 0x1037,
            name: "MultipleExposure",
            format: None,
            count: None,
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[
                (1, "Additive"),
                (2, "Average"),
                (3, "Light"),
                (4, "Dark"),
            ]),
            subdir: None,
        },
        IfdTag {
            id: 0x1040,
            name: "ShadowTone",
            format: None,
            count: None,
            writable: Some("int32s"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: false,
                condition: false,
                hook: false,
                subdirectory: false,
                print_conv: true,
            },
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x1041,
            name: "HighlightTone",
            format: None,
            count: None,
            writable: Some("int32s"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: false,
                condition: false,
                hook: false,
                subdirectory: false,
                print_conv: true,
            },
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x1044,
            name: "DigitalZoom",
            format: None,
            count: None,
            writable: Some("int32u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: Some(ExprId::Val8E052C9),
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x1045,
            name: "LensModulationOptimizer",
            format: None,
            count: None,
            writable: Some("int32u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[(0, "Off"), (1, "On")]),
            subdir: None,
        },
        IfdTag {
            id: 0x1047,
            name: "GrainEffectRoughness",
            format: None,
            count: None,
            writable: Some("int32s"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[(0, "Off"), (32, "Weak"), (64, "Strong")]),
            subdir: None,
        },
        IfdTag {
            id: 0x1048,
            name: "ColorChromeEffect",
            format: None,
            count: None,
            writable: Some("int32s"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[(0, "Off"), (32, "Weak"), (64, "Strong")]),
            subdir: None,
        },
        IfdTag {
            id: 0x1049,
            name: "BWAdjustment",
            format: Some(Fmt::Int8s),
            count: None,
            writable: None,
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::Expr(ExprId::Val0ValValFADF1F),
            subdir: None,
        },
        IfdTag {
            id: 0x104b,
            name: "BWMagentaGreen",
            format: Some(Fmt::Int8s),
            count: None,
            writable: None,
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::Expr(ExprId::Val0ValValFADF1F),
            subdir: None,
        },
        IfdTag {
            id: 0x104c,
            name: "GrainEffectSize",
            format: None,
            count: None,
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[(0, "Off"), (16, "Small"), (32, "Large")]),
            subdir: None,
        },
        IfdTag {
            id: 0x104d,
            name: "CropMode",
            format: None,
            count: None,
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[
                (0, "n/a"),
                (1, "Full-frame on GFX"),
                (2, "Sports Finder Mode"),
                (4, "Electronic Shutter 1.25x Crop"),
                (8, "Digital Tele-Conv"),
            ]),
            subdir: None,
        },
        IfdTag {
            id: 0x104e,
            name: "ColorChromeFXBlue",
            format: None,
            count: None,
            writable: Some("int32s"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[(0, "Off"), (32, "Weak"), (64, "Strong")]),
            subdir: None,
        },
        IfdTag {
            id: 0x1050,
            name: "ShutterType",
            format: None,
            count: None,
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[
                (0, "Mechanical"),
                (1, "Electronic"),
                (2, "Electronic (long shutter speed)"),
                (3, "Electronic Front Curtain"),
            ]),
            subdir: None,
        },
        IfdTag {
            id: 0x1051,
            name: "CropFlag",
            format: None,
            count: None,
            writable: Some("int8u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x1052,
            name: "CropTopLeft",
            format: None,
            count: None,
            writable: Some("int32u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x1053,
            name: "CropSize",
            format: None,
            count: None,
            writable: Some("int32u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x1101,
            name: "SequenceNumber",
            format: None,
            count: None,
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x1102,
            name: "WhiteBalanceBracketing",
            format: None,
            count: None,
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::PartialEnumInt {
                exact: &[(511, "+/- 1"), (767, "+/- 2"), (1023, "+/- 3")],
                other: None,
                print_hex: true,
            },
            subdir: None,
        },
        IfdTag {
            id: 0x1103,
            name: "DriveSettings",
            format: None,
            count: None,
            writable: None,
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: false,
                condition: false,
                hook: false,
                subdirectory: true,
                print_conv: false,
            },
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: Some(IfdSubdirEdge {
                module: "FujiFilm",
                table: "DriveSettings",
                start: IfdStart::ValuePtr(0),
                base: None,
                byte_order: IfdByteOrder::Inherit,
                fix_format: None,
                sub_ifd: false,
                max_subdirs: None,
                dir_name: None,
                validate: false,
                validation: None,
                processor: IfdSubdirProcessor::Native,
                unwalked: None,
            }),
        },
        IfdTag {
            id: 0x1105,
            name: "PixelShiftShots",
            format: None,
            count: None,
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x1106,
            name: "PixelShiftOffset",
            format: None,
            count: Some(2),
            writable: Some("rational64s"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x1150,
            name: "CompositeImageMode",
            format: None,
            count: None,
            writable: Some("int32u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[
                (0, "n/a"),
                (1, "Pro Low-light"),
                (2, "Pro Focus"),
                (32, "Panorama"),
                (128, "HDR"),
                (1024, "Multi-exposure"),
            ]),
            subdir: None,
        },
        IfdTag {
            id: 0x1151,
            name: "CompositeImageCount1",
            format: None,
            count: None,
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x1152,
            name: "CompositeImageCount2",
            format: None,
            count: None,
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x1153,
            name: "PanoramaAngle",
            format: None,
            count: None,
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x1154,
            name: "PanoramaDirection",
            format: None,
            count: None,
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[(1, "Right"), (2, "Left"), (3, "Up"), (4, "Down")]),
            subdir: None,
        },
        IfdTag {
            id: 0x1201,
            name: "AdvancedFilter",
            format: None,
            count: None,
            writable: Some("int32u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::PartialEnumInt {
                exact: &[
                    (65536, "Pop Color"),
                    (131072, "Hi Key"),
                    (196608, "Toy Camera"),
                    (262144, "Miniature"),
                    (327680, "Dynamic Tone"),
                    (393217, "Partial Color Red"),
                    (393218, "Partial Color Yellow"),
                    (393219, "Partial Color Green"),
                    (393220, "Partial Color Blue"),
                    (393221, "Partial Color Orange"),
                    (393222, "Partial Color Purple"),
                    (458752, "Soft Focus"),
                    (589824, "Low Key"),
                    (1048576, "Light Leak"),
                    (1245184, "Expired Film Green"),
                    (1245185, "Expired Film Red"),
                    (1245186, "Expired Film Neutral"),
                ],
                other: None,
                print_hex: true,
            },
            subdir: None,
        },
        IfdTag {
            id: 0x1210,
            name: "ColorMode",
            format: None,
            count: None,
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::PartialEnumInt {
                exact: &[(0, "Standard"), (16, "Chrome"), (48, "B & W")],
                other: None,
                print_hex: true,
            },
            subdir: None,
        },
        IfdTag {
            id: 0x1300,
            name: "BlurWarning",
            format: None,
            count: None,
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[(0, "None"), (1, "Blur Warning")]),
            subdir: None,
        },
        IfdTag {
            id: 0x1301,
            name: "FocusWarning",
            format: None,
            count: None,
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[(0, "Good"), (1, "Out of focus")]),
            subdir: None,
        },
        IfdTag {
            id: 0x1302,
            name: "ExposureWarning",
            format: None,
            count: None,
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[(0, "Good"), (1, "Bad exposure")]),
            subdir: None,
        },
        IfdTag {
            id: 0x1304,
            name: "GEImageSize",
            format: None,
            count: None,
            writable: Some("string"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: Some(Cond::MemberRegex {
                member: "Make",
                pattern: "^GENERAL IMAGING",
                ignore_case: false,
                negate: false,
            }),
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x1400,
            name: "DynamicRange",
            format: None,
            count: None,
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[(1, "Standard"), (3, "Wide")]),
            subdir: None,
        },
        IfdTag {
            id: 0x1401,
            name: "FilmMode",
            format: None,
            count: None,
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::PartialEnumInt {
                exact: &[
                    (0, "F0/Standard (Provia)"),
                    (256, "F1/Studio Portrait"),
                    (272, "F1a/Studio Portrait Enhanced Saturation"),
                    (288, "F1b/Studio Portrait Smooth Skin Tone (Astia)"),
                    (304, "F1c/Studio Portrait Increased Sharpness"),
                    (512, "F2/Fujichrome (Velvia)"),
                    (768, "F3/Studio Portrait Ex"),
                    (1024, "F4/Velvia"),
                    (1280, "Pro Neg. Std"),
                    (1281, "Pro Neg. Hi"),
                    (1536, "Classic Chrome"),
                    (1792, "Eterna"),
                    (2048, "Classic Negative"),
                    (2304, "Bleach Bypass"),
                    (2560, "Nostalgic Neg"),
                    (2816, "Reala ACE"),
                ],
                other: None,
                print_hex: true,
            },
            subdir: None,
        },
        IfdTag {
            id: 0x1402,
            name: "DynamicRangeSetting",
            format: None,
            count: None,
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::PartialEnumInt {
                exact: &[
                    (0, "Auto"),
                    (1, "Manual"),
                    (256, "Standard (100%)"),
                    (512, "Wide1 (230%)"),
                    (513, "Wide2 (400%)"),
                    (32768, "Film Simulation"),
                ],
                other: None,
                print_hex: true,
            },
            subdir: None,
        },
        IfdTag {
            id: 0x1403,
            name: "DevelopmentDynamicRange",
            format: None,
            count: None,
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x1404,
            name: "MinFocalLength",
            format: None,
            count: None,
            writable: Some("rational64s"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x1405,
            name: "MaxFocalLength",
            format: None,
            count: None,
            writable: Some("rational64s"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x1406,
            name: "MaxApertureAtMinFocal",
            format: None,
            count: None,
            writable: Some("rational64s"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x1407,
            name: "MaxApertureAtMaxFocal",
            format: None,
            count: None,
            writable: Some("rational64s"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x140b,
            name: "AutoDynamicRange",
            format: None,
            count: None,
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::Expr(ExprId::Val81464B),
            subdir: None,
        },
        IfdTag {
            id: 0x1422,
            name: "ImageStabilization",
            format: None,
            count: Some(3),
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: false,
                condition: false,
                hook: false,
                subdirectory: false,
                print_conv: true,
            },
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x1425,
            name: "SceneRecognition",
            format: None,
            count: None,
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::PartialEnumInt {
                exact: &[
                    (0, "Unrecognized"),
                    (256, "Portrait Image"),
                    (259, "Night Portrait"),
                    (261, "Backlit Portrait"),
                    (512, "Landscape Image"),
                    (768, "Night Scene"),
                    (1024, "Macro"),
                ],
                other: None,
                print_hex: true,
            },
            subdir: None,
        },
        IfdTag {
            id: 0x1431,
            name: "Rating",
            format: None,
            count: None,
            writable: Some("int32u"),
            groups: TagGroups {
                g0: None,
                g1: None,
                g2: Some("Image"),
            },
            flags: IfdFlags {
                unknown: false,
                binary: false,
                list: false,
                protected: false,
                avoid: false,
                priority: Some(0),
            },
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x1436,
            name: "ImageGeneration",
            format: None,
            count: None,
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[(0, "Original Image"), (1, "Re-developed from RAW")]),
            subdir: None,
        },
        IfdTag {
            id: 0x1438,
            name: "ImageCount",
            format: None,
            count: None,
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: Some(ExprId::Val0x7fff1D3C54),
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x1443,
            name: "DRangePriority",
            format: None,
            count: None,
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[(0, "Auto"), (1, "Fixed")]),
            subdir: None,
        },
        IfdTag {
            id: 0x1444,
            name: "DRangePriorityAuto",
            format: None,
            count: None,
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[(1, "Weak"), (2, "Strong"), (3, "Plus")]),
            subdir: None,
        },
        IfdTag {
            id: 0x1445,
            name: "DRangePriorityFixed",
            format: None,
            count: None,
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[(1, "Weak"), (2, "Strong")]),
            subdir: None,
        },
        IfdTag {
            id: 0x1446,
            name: "FlickerReduction",
            format: None,
            count: None,
            writable: Some("int32u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: false,
                condition: false,
                hook: false,
                subdirectory: false,
                print_conv: true,
            },
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x1447,
            name: "FujiModel",
            format: None,
            count: None,
            writable: Some("string"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x1448,
            name: "FujiModel2",
            format: None,
            count: None,
            writable: Some("string"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x144a,
            name: "WBRed",
            format: None,
            count: None,
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x144b,
            name: "WBGreen",
            format: None,
            count: None,
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x144c,
            name: "WBBlue",
            format: None,
            count: None,
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x144d,
            name: "RollAngle",
            format: None,
            count: None,
            writable: Some("rational64s"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x3803,
            name: "VideoRecordingMode",
            format: None,
            count: None,
            writable: Some("int32u"),
            groups: TagGroups {
                g0: None,
                g1: None,
                g2: Some("Video"),
            },
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::PartialEnumInt {
                exact: &[(0, "Normal"), (16, "F-log"), (32, "HLG"), (48, "F-log2")],
                other: None,
                print_hex: true,
            },
            subdir: None,
        },
        IfdTag {
            id: 0x3804,
            name: "PeripheralLighting",
            format: None,
            count: None,
            writable: Some("int16u"),
            groups: TagGroups {
                g0: None,
                g1: None,
                g2: Some("Video"),
            },
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[(0, "Off"), (1, "On")]),
            subdir: None,
        },
        IfdTag {
            id: 0x3806,
            name: "VideoCompression",
            format: None,
            count: None,
            writable: Some("int16u"),
            groups: TagGroups {
                g0: None,
                g1: None,
                g2: Some("Video"),
            },
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[(1, "Log GOP"), (2, "All Intra")]),
            subdir: None,
        },
        IfdTag {
            id: 0x3820,
            name: "FrameRate",
            format: None,
            count: None,
            writable: Some("int16u"),
            groups: TagGroups {
                g0: None,
                g1: None,
                g2: Some("Video"),
            },
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x3821,
            name: "FrameWidth",
            format: None,
            count: None,
            writable: Some("int16u"),
            groups: TagGroups {
                g0: None,
                g1: None,
                g2: Some("Video"),
            },
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x3822,
            name: "FrameHeight",
            format: None,
            count: None,
            writable: Some("int16u"),
            groups: TagGroups {
                g0: None,
                g1: None,
                g2: Some("Video"),
            },
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x3824,
            name: "FullHDHighSpeedRec",
            format: None,
            count: None,
            writable: Some("int32u"),
            groups: TagGroups {
                g0: None,
                g1: None,
                g2: Some("Video"),
            },
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[(1, "Off"), (2, "On")]),
            subdir: None,
        },
        IfdTag {
            id: 0x4005,
            name: "FaceElementSelected",
            format: None,
            count: Some(4),
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x4100,
            name: "FacesDetected",
            format: None,
            count: None,
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x4103,
            name: "FacePositions",
            format: None,
            count: None,
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x4200,
            name: "NumFaceElements",
            format: None,
            count: None,
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x4201,
            name: "FaceElementTypes",
            format: None,
            count: None,
            writable: Some("int8u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: false,
                condition: false,
                hook: false,
                subdirectory: false,
                print_conv: true,
            },
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x4203,
            name: "FaceElementPositions",
            format: None,
            count: None,
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x4282,
            name: "FaceRecInfo",
            format: None,
            count: None,
            writable: None,
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: false,
                condition: false,
                hook: false,
                subdirectory: true,
                print_conv: false,
            },
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: Some(IfdSubdirEdge {
                module: "FujiFilm",
                table: "FaceRecInfo",
                start: IfdStart::ValuePtr(0),
                base: None,
                byte_order: IfdByteOrder::Inherit,
                fix_format: None,
                sub_ifd: false,
                max_subdirs: None,
                dir_name: None,
                validate: false,
                validation: None,
                processor: IfdSubdirProcessor::Native,
                unwalked: None,
            }),
        },
        IfdTag {
            id: 0x8000,
            name: "FileSource",
            format: None,
            count: None,
            writable: Some("string"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x8002,
            name: "OrderNumber",
            format: None,
            count: None,
            writable: Some("int32u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x8003,
            name: "FrameNumber",
            format: None,
            count: None,
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0xb211,
            name: "Parallax",
            format: None,
            count: None,
            writable: Some("rational64s"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
    ],
    variants: &[IfdVariantGroup {
        id: 0x1100,
        alternatives: &[
            (
                Cond::MemberStrEq {
                    member: "Model",
                    value: "X-T3",
                    negate: false,
                },
                IfdTag {
                    id: 0x1100,
                    name: "AutoBracketing",
                    format: None,
                    count: None,
                    writable: Some("int16u"),
                    groups: TagGroups::NONE,
                    flags: IfdFlags::NONE,
                    condition: None,
                    omitted: Omitted::NONE,
                    raw_conv: None,
                    value_conv: None,
                    print_conv: PrintConv::IntEnum(&[(0, "Off"), (1, "On"), (2, "Pre-shot")]),
                    subdir: None,
                },
            ),
            (
                Cond::Always,
                IfdTag {
                    id: 0x1100,
                    name: "AutoBracketing",
                    format: None,
                    count: None,
                    writable: Some("int16u"),
                    groups: TagGroups::NONE,
                    flags: IfdFlags::NONE,
                    condition: None,
                    omitted: Omitted::NONE,
                    raw_conv: None,
                    value_conv: None,
                    print_conv: PrintConv::IntEnum(&[
                        (0, "Off"),
                        (1, "On"),
                        (2, "No flash & flash"),
                        (6, "Pixel Shift"),
                    ]),
                    subdir: None,
                },
            ),
        ],
    }],
};
