//! ExifTool `IPTC` IFD-style tables, generated from ExifTool
//! 13.59's own Perl hashes -- one file per module; `mod.rs` beside this
//! file is the hub that declares and re-exports it.
//!
//! DO NOT EDIT. Regenerate with `just regen-tables` (see `mod.rs`).

#![allow(clippy::unreadable_literal, clippy::too_many_lines, unused_parens)]

// Everything a table literal names -- the `ifd_schema` types, `ExprId`, the
// `cond`/`subdir`/`validation` imports -- is in scope in the hub, and a glob
// import of the parent module brings its private imports along (RFC 1560).
#[allow(unused_imports)]
use super::*;

/// `Image::ExifTool::IPTC::ApplicationRecord` -- 14 tags,
/// 0 `_variants` groups (IFD-style: PROCESS_PROC absent).
/// Generated from ExifTool's in-memory tag table. Do not edit by hand.
pub static IFD_IPTC_APPLICATIONRECORD: IfdTable = IfdTable {
    module: "IPTC",
    table: "ApplicationRecord",
    group0: "IPTC",
    group1: "IPTC",
    group2: "Other",
    set_group1: None,
    priority: None,
    gate_a: GateA {
        blocked_by: &[("ifd_format_unsupported", 56)],
    },
    tags: &[
        IfdTag {
            id: 0x0000,
            name: "ApplicationRecordVersion",
            format: Some(Fmt::Int16u),
            count: None,
            writable: None,
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x001a,
            name: "ContentLocationCode",
            format: Some(Fmt::Str(3)),
            count: Some(3),
            writable: None,
            groups: TagGroups {
                g0: None,
                g1: None,
                g2: Some("Location"),
            },
            flags: IfdFlags {
                unknown: false,
                binary: false,
                list: true,
                protected: false,
                avoid: false,
                priority: None,
            },
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x0023,
            name: "ReleaseTime",
            format: Some(Fmt::Str(11)),
            count: Some(11),
            writable: None,
            groups: TagGroups {
                g0: None,
                g1: None,
                g2: Some("Time"),
            },
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted {
                value_conv: true,
                raw_conv: false,
                condition: false,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x0026,
            name: "ExpirationTime",
            format: Some(Fmt::Str(11)),
            count: Some(11),
            writable: None,
            groups: TagGroups {
                g0: None,
                g1: None,
                g2: Some("Time"),
            },
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted {
                value_conv: true,
                raw_conv: false,
                condition: false,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x003c,
            name: "TimeCreated",
            format: Some(Fmt::Str(11)),
            count: Some(11),
            writable: None,
            groups: TagGroups {
                g0: None,
                g1: None,
                g2: Some("Time"),
            },
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted {
                value_conv: true,
                raw_conv: false,
                condition: false,
                hook: false,
                subdirectory: false,
                print_conv: true,
            },
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x003f,
            name: "DigitalCreationTime",
            format: Some(Fmt::Str(11)),
            count: Some(11),
            writable: None,
            groups: TagGroups {
                g0: None,
                g1: None,
                g2: Some("Time"),
            },
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted {
                value_conv: true,
                raw_conv: false,
                condition: false,
                hook: false,
                subdirectory: false,
                print_conv: true,
            },
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x004b,
            name: "ObjectCycle",
            format: Some(Fmt::Str(1)),
            count: Some(1),
            writable: None,
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::StrEnum(&[
                ("a", "Morning"),
                ("b", "Both Morning and Evening"),
                ("p", "Evening"),
            ]),
            subdir: None,
        },
        IfdTag {
            id: 0x0064,
            name: "Country-PrimaryLocationCode",
            format: Some(Fmt::Str(3)),
            count: Some(3),
            writable: None,
            groups: TagGroups {
                g0: None,
                g1: None,
                g2: Some("Location"),
            },
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x007d,
            name: "RasterizedCaption",
            format: Some(Fmt::Undef(7360)),
            count: Some(7360),
            writable: None,
            groups: TagGroups::NONE,
            flags: IfdFlags {
                unknown: false,
                binary: true,
                list: false,
                protected: false,
                avoid: false,
                priority: None,
            },
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x0082,
            name: "ImageType",
            format: Some(Fmt::Str(2)),
            count: Some(2),
            writable: None,
            groups: TagGroups {
                g0: None,
                g1: None,
                g2: Some("Image"),
            },
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x0083,
            name: "ImageOrientation",
            format: Some(Fmt::Str(1)),
            count: Some(1),
            writable: None,
            groups: TagGroups {
                g0: None,
                g1: None,
                g2: Some("Image"),
            },
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::StrEnum(&[
                ("L", "Landscape"),
                ("P", "Portrait"),
                ("S", "Square"),
            ]),
            subdir: None,
        },
        IfdTag {
            id: 0x0096,
            name: "AudioType",
            format: Some(Fmt::Str(2)),
            count: Some(2),
            writable: None,
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::StrEnum(&[
                ("0T", "Text Only"),
                ("1A", "Mono Actuality"),
                ("1C", "Mono Question and Answer Session"),
                ("1M", "Mono Music"),
                ("1Q", "Mono Response to a Question"),
                ("1R", "Mono Raw Sound"),
                ("1S", "Mono Scener"),
                ("1V", "Mono Voicer"),
                ("1W", "Mono Wrap"),
                ("2A", "Stereo Actuality"),
                ("2C", "Stereo Question and Answer Session"),
                ("2M", "Stereo Music"),
                ("2Q", "Stereo Response to a Question"),
                ("2R", "Stereo Raw Sound"),
                ("2S", "Stereo Scener"),
                ("2V", "Stereo Voicer"),
                ("2W", "Stereo Wrap"),
            ]),
            subdir: None,
        },
        IfdTag {
            id: 0x00c8,
            name: "ObjectPreviewFileFormat",
            format: Some(Fmt::Int16u),
            count: None,
            writable: None,
            groups: TagGroups {
                g0: None,
                g1: None,
                g2: Some("Image"),
            },
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[
                (0, "No ObjectData"),
                (1, "IPTC-NAA Digital Newsphoto Parameter Record"),
                (2, "IPTC7901 Recommended Message Format"),
                (3, "Tagged Image File Format (Adobe/Aldus Image data)"),
                (4, "Illustrator (Adobe Graphics data)"),
                (5, "AppleSingle (Apple Computer Inc)"),
                (6, "NAA 89-3 (ANPA 1312)"),
                (7, "MacBinary II"),
                (
                    8,
                    "IPTC Unstructured Character Oriented File Format (UCOFF)",
                ),
                (9, "United Press International ANPA 1312 variant"),
                (10, "United Press International Down-Load Message"),
                (11, "JPEG File Interchange (JFIF)"),
                (12, "Photo-CD Image-Pac (Eastman Kodak)"),
                (13, "Bit Mapped Graphics File [.BMP] (Microsoft)"),
                (14, "Digital Audio File [.WAV] (Microsoft & Creative Labs)"),
                (15, "Audio plus Moving Video [.AVI] (Microsoft)"),
                (16, "PC DOS/Windows Executable Files [.COM][.EXE]"),
                (17, "Compressed Binary File [.ZIP] (PKWare Inc)"),
                (
                    18,
                    "Audio Interchange File Format AIFF (Apple Computer Inc)",
                ),
                (19, "RIFF Wave (Microsoft Corporation)"),
                (20, "Freehand (Macromedia/Aldus)"),
                (
                    21,
                    "Hypertext Markup Language [.HTML] (The Internet Society)",
                ),
                (22, "MPEG 2 Audio Layer 2 (Musicom), ISO/IEC"),
                (23, "MPEG 2 Audio Layer 3, ISO/IEC"),
                (24, "Portable Document File [.PDF] Adobe"),
                (25, "News Industry Text Format (NITF)"),
                (26, "Tape Archive [.TAR]"),
                (27, "Tidningarnas Telegrambyra NITF version (TTNITF DTD)"),
                (28, "Ritzaus Bureau NITF version (RBNITF DTD)"),
                (29, "Corel Draw [.CDR]"),
            ]),
            subdir: None,
        },
        IfdTag {
            id: 0x00c9,
            name: "ObjectPreviewFileVersion",
            format: Some(Fmt::Int16u),
            count: None,
            writable: None,
            groups: TagGroups {
                g0: None,
                g1: None,
                g2: Some("Image"),
            },
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
    ],
    variants: &[],
};

/// `Image::ExifTool::IPTC::Composite` -- 0 tags,
/// 0 `_variants` groups (IFD-style: PROCESS_PROC absent).
/// Generated from ExifTool's in-memory tag table. Do not edit by hand.
pub static IFD_IPTC_COMPOSITE: IfdTable = IfdTable {
    module: "IPTC",
    table: "Composite",
    group0: "Composite",
    group1: "Composite",
    group2: "Image",
    set_group1: None,
    priority: None,
    gate_a: GateA {
        blocked_by: &[("ifd_tag_id_unrepresentable", 2)],
    },
    tags: &[],
    variants: &[],
};

/// `Image::ExifTool::IPTC::EnvelopeRecord` -- 6 tags,
/// 0 `_variants` groups (IFD-style: PROCESS_PROC absent).
/// Generated from ExifTool's in-memory tag table. Do not edit by hand.
pub static IFD_IPTC_ENVELOPERECORD: IfdTable = IfdTable {
    module: "IPTC",
    table: "EnvelopeRecord",
    group0: "IPTC",
    group1: "IPTC",
    group2: "Other",
    set_group1: None,
    priority: None,
    gate_a: GateA {
        blocked_by: &[("ifd_format_unsupported", 8)],
    },
    tags: &[
        IfdTag {
            id: 0x0000,
            name: "EnvelopeRecordVersion",
            format: Some(Fmt::Int16u),
            count: None,
            writable: None,
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x0014,
            name: "FileFormat",
            format: Some(Fmt::Int16u),
            count: None,
            writable: None,
            groups: TagGroups {
                g0: None,
                g1: None,
                g2: Some("Image"),
            },
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[
                (0, "No ObjectData"),
                (1, "IPTC-NAA Digital Newsphoto Parameter Record"),
                (2, "IPTC7901 Recommended Message Format"),
                (3, "Tagged Image File Format (Adobe/Aldus Image data)"),
                (4, "Illustrator (Adobe Graphics data)"),
                (5, "AppleSingle (Apple Computer Inc)"),
                (6, "NAA 89-3 (ANPA 1312)"),
                (7, "MacBinary II"),
                (
                    8,
                    "IPTC Unstructured Character Oriented File Format (UCOFF)",
                ),
                (9, "United Press International ANPA 1312 variant"),
                (10, "United Press International Down-Load Message"),
                (11, "JPEG File Interchange (JFIF)"),
                (12, "Photo-CD Image-Pac (Eastman Kodak)"),
                (13, "Bit Mapped Graphics File [.BMP] (Microsoft)"),
                (14, "Digital Audio File [.WAV] (Microsoft & Creative Labs)"),
                (15, "Audio plus Moving Video [.AVI] (Microsoft)"),
                (16, "PC DOS/Windows Executable Files [.COM][.EXE]"),
                (17, "Compressed Binary File [.ZIP] (PKWare Inc)"),
                (
                    18,
                    "Audio Interchange File Format AIFF (Apple Computer Inc)",
                ),
                (19, "RIFF Wave (Microsoft Corporation)"),
                (20, "Freehand (Macromedia/Aldus)"),
                (
                    21,
                    "Hypertext Markup Language [.HTML] (The Internet Society)",
                ),
                (22, "MPEG 2 Audio Layer 2 (Musicom), ISO/IEC"),
                (23, "MPEG 2 Audio Layer 3, ISO/IEC"),
                (24, "Portable Document File [.PDF] Adobe"),
                (25, "News Industry Text Format (NITF)"),
                (26, "Tape Archive [.TAR]"),
                (27, "Tidningarnas Telegrambyra NITF version (TTNITF DTD)"),
                (28, "Ritzaus Bureau NITF version (RBNITF DTD)"),
                (29, "Corel Draw [.CDR]"),
            ]),
            subdir: None,
        },
        IfdTag {
            id: 0x0016,
            name: "FileVersion",
            format: Some(Fmt::Int16u),
            count: None,
            writable: None,
            groups: TagGroups {
                g0: None,
                g1: None,
                g2: Some("Image"),
            },
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x0050,
            name: "TimeSent",
            format: Some(Fmt::Str(11)),
            count: Some(11),
            writable: None,
            groups: TagGroups {
                g0: None,
                g1: None,
                g2: Some("Time"),
            },
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted {
                value_conv: true,
                raw_conv: false,
                condition: false,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x0078,
            name: "ARMIdentifier",
            format: Some(Fmt::Int16u),
            count: None,
            writable: None,
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x007a,
            name: "ARMVersion",
            format: Some(Fmt::Int16u),
            count: None,
            writable: None,
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
    ],
    variants: &[],
};

/// `Image::ExifTool::IPTC::FotoStation` -- 0 tags,
/// 0 `_variants` groups (IFD-style: PROCESS_PROC absent).
/// Generated from ExifTool's in-memory tag table. Do not edit by hand.
pub static IFD_IPTC_FOTOSTATION: IfdTable = IfdTable {
    module: "IPTC",
    table: "FotoStation",
    group0: "IPTC",
    group1: "IPTC",
    group2: "Other",
    set_group1: None,
    priority: None,
    gate_a: GateA { blocked_by: &[] },
    tags: &[],
    variants: &[],
};

/// `Image::ExifTool::IPTC::NewsPhoto` -- 26 tags,
/// 0 `_variants` groups (IFD-style: PROCESS_PROC absent).
/// Generated from ExifTool's in-memory tag table. Do not edit by hand.
pub static IFD_IPTC_NEWSPHOTO: IfdTable = IfdTable {
    module: "IPTC",
    table: "NewsPhoto",
    group0: "IPTC",
    group1: "IPTC",
    group2: "Image",
    set_group1: None,
    priority: None,
    gate_a: GateA { blocked_by: &[] },
    tags: &[
        IfdTag {
            id: 0x0000,
            name: "NewsPhotoVersion",
            format: Some(Fmt::Int16u),
            count: None,
            writable: None,
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x000a,
            name: "IPTCPictureNumber",
            format: Some(Fmt::Str(16)),
            count: Some(16),
            writable: None,
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: false,
                condition: false,
                hook: false,
                subdirectory: false,
                print_conv: true,
            },
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x0014,
            name: "IPTCImageWidth",
            format: Some(Fmt::Int16u),
            count: None,
            writable: None,
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x001e,
            name: "IPTCImageHeight",
            format: Some(Fmt::Int16u),
            count: None,
            writable: None,
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x0028,
            name: "IPTCPixelWidth",
            format: Some(Fmt::Int16u),
            count: None,
            writable: None,
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x0032,
            name: "IPTCPixelHeight",
            format: Some(Fmt::Int16u),
            count: None,
            writable: None,
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x0037,
            name: "SupplementalType",
            format: Some(Fmt::Int8u),
            count: None,
            writable: None,
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[
                (0, "Main Image"),
                (1, "Reduced Resolution Image"),
                (2, "Logo"),
                (3, "Rasterized Caption"),
            ]),
            subdir: None,
        },
        IfdTag {
            id: 0x003c,
            name: "ColorRepresentation",
            format: Some(Fmt::Int16u),
            count: None,
            writable: None,
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::PartialEnumInt {
                exact: &[
                    (0, "No Image, Single Frame"),
                    (256, "Monochrome, Single Frame"),
                    (768, "3 Components, Single Frame"),
                    (769, "3 Components, Frame Sequential in Multiple Objects"),
                    (770, "3 Components, Frame Sequential in One Object"),
                    (771, "3 Components, Line Sequential"),
                    (772, "3 Components, Pixel Sequential"),
                    (773, "3 Components, Special Interleaving"),
                    (1024, "4 Components, Single Frame"),
                    (1025, "4 Components, Frame Sequential in Multiple Objects"),
                    (1026, "4 Components, Frame Sequential in One Object"),
                    (1027, "4 Components, Line Sequential"),
                    (1028, "4 Components, Pixel Sequential"),
                    (1029, "4 Components, Special Interleaving"),
                ],
                other: None,
                print_hex: true,
            },
            subdir: None,
        },
        IfdTag {
            id: 0x0040,
            name: "InterchangeColorSpace",
            format: Some(Fmt::Int8u),
            count: None,
            writable: None,
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[
                (1, "X,Y,Z CIE"),
                (2, "RGB SMPTE"),
                (3, "Y,U,V (K) (D65)"),
                (4, "RGB Device Dependent"),
                (5, "CMY (K) Device Dependent"),
                (6, "Lab (K) CIE"),
                (7, "YCbCr"),
                (8, "sRGB"),
            ]),
            subdir: None,
        },
        IfdTag {
            id: 0x0041,
            name: "ColorSequence",
            format: Some(Fmt::Int8u),
            count: None,
            writable: None,
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x0042,
            name: "ICC_Profile",
            format: None,
            count: None,
            writable: None,
            groups: TagGroups::NONE,
            flags: IfdFlags {
                unknown: false,
                binary: true,
                list: false,
                protected: false,
                avoid: false,
                priority: None,
            },
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x0046,
            name: "ColorCalibrationMatrix",
            format: None,
            count: None,
            writable: None,
            groups: TagGroups::NONE,
            flags: IfdFlags {
                unknown: false,
                binary: true,
                list: false,
                protected: false,
                avoid: false,
                priority: None,
            },
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x0050,
            name: "LookupTable",
            format: None,
            count: None,
            writable: None,
            groups: TagGroups::NONE,
            flags: IfdFlags {
                unknown: false,
                binary: true,
                list: false,
                protected: false,
                avoid: false,
                priority: None,
            },
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x0054,
            name: "NumIndexEntries",
            format: Some(Fmt::Int16u),
            count: None,
            writable: None,
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x0055,
            name: "ColorPalette",
            format: None,
            count: None,
            writable: None,
            groups: TagGroups::NONE,
            flags: IfdFlags {
                unknown: false,
                binary: true,
                list: false,
                protected: false,
                avoid: false,
                priority: None,
            },
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x0056,
            name: "IPTCBitsPerSample",
            format: Some(Fmt::Int8u),
            count: None,
            writable: None,
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x005a,
            name: "SampleStructure",
            format: Some(Fmt::Int8u),
            count: None,
            writable: None,
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[
                (0, "OrthogonalConstangSampling"),
                (1, "Orthogonal4-2-2Sampling"),
                (2, "CompressionDependent"),
            ]),
            subdir: None,
        },
        IfdTag {
            id: 0x0064,
            name: "ScanningDirection",
            format: Some(Fmt::Int8u),
            count: None,
            writable: None,
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[
                (0, "L-R, Top-Bottom"),
                (1, "R-L, Top-Bottom"),
                (2, "L-R, Bottom-Top"),
                (3, "R-L, Bottom-Top"),
                (4, "Top-Bottom, L-R"),
                (5, "Bottom-Top, L-R"),
                (6, "Top-Bottom, R-L"),
                (7, "Bottom-Top, R-L"),
            ]),
            subdir: None,
        },
        IfdTag {
            id: 0x0066,
            name: "IPTCImageRotation",
            format: Some(Fmt::Int8u),
            count: None,
            writable: None,
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[(0, "0"), (1, "90"), (2, "180"), (3, "270")]),
            subdir: None,
        },
        IfdTag {
            id: 0x006e,
            name: "DataCompressionMethod",
            format: Some(Fmt::Int32u),
            count: None,
            writable: None,
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x0078,
            name: "QuantizationMethod",
            format: Some(Fmt::Int8u),
            count: None,
            writable: None,
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[
                (0, "Linear Reflectance/Transmittance"),
                (1, "Linear Density"),
                (2, "IPTC Ref B"),
                (3, "Linear Dot Percent"),
                (4, "AP Domestic Analogue"),
                (5, "Compression Method Specific"),
                (6, "Color Space Specific"),
                (7, "Gamma Compensated"),
            ]),
            subdir: None,
        },
        IfdTag {
            id: 0x007d,
            name: "EndPoints",
            format: None,
            count: None,
            writable: None,
            groups: TagGroups::NONE,
            flags: IfdFlags {
                unknown: false,
                binary: true,
                list: false,
                protected: false,
                avoid: false,
                priority: None,
            },
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x0082,
            name: "ExcursionTolerance",
            format: Some(Fmt::Int8u),
            count: None,
            writable: None,
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[(0, "Not Allowed"), (1, "Allowed")]),
            subdir: None,
        },
        IfdTag {
            id: 0x0087,
            name: "BitsPerComponent",
            format: Some(Fmt::Int8u),
            count: None,
            writable: None,
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x008c,
            name: "MaximumDensityRange",
            format: Some(Fmt::Int16u),
            count: None,
            writable: None,
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x0091,
            name: "GammaCompensatedValue",
            format: Some(Fmt::Int16u),
            count: None,
            writable: None,
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
    ],
    variants: &[],
};

/// `Image::ExifTool::IPTC::ObjectData` -- 1 tags,
/// 0 `_variants` groups (IFD-style: PROCESS_PROC absent).
/// Generated from ExifTool's in-memory tag table. Do not edit by hand.
pub static IFD_IPTC_OBJECTDATA: IfdTable = IfdTable {
    module: "IPTC",
    table: "ObjectData",
    group0: "IPTC",
    group1: "IPTC",
    group2: "Other",
    set_group1: None,
    priority: None,
    gate_a: GateA { blocked_by: &[] },
    tags: &[IfdTag {
        id: 0x000a,
        name: "SubFile",
        format: None,
        count: None,
        writable: None,
        groups: TagGroups::NONE,
        flags: IfdFlags {
            unknown: false,
            binary: true,
            list: true,
            protected: false,
            avoid: false,
            priority: None,
        },
        condition: None,
        omitted: Omitted::NONE,
        raw_conv: None,
        value_conv: None,
        print_conv: PrintConv::None,
        subdir: None,
    }],
    variants: &[],
};

/// `Image::ExifTool::IPTC::PostObjectData` -- 1 tags,
/// 0 `_variants` groups (IFD-style: PROCESS_PROC absent).
/// Generated from ExifTool's in-memory tag table. Do not edit by hand.
pub static IFD_IPTC_POSTOBJECTDATA: IfdTable = IfdTable {
    module: "IPTC",
    table: "PostObjectData",
    group0: "IPTC",
    group1: "IPTC",
    group2: "Other",
    set_group1: None,
    priority: None,
    gate_a: GateA { blocked_by: &[] },
    tags: &[IfdTag {
        id: 0x000a,
        name: "ConfirmedObjectSize",
        format: Some(Fmt::Int32u),
        count: None,
        writable: None,
        groups: TagGroups::NONE,
        flags: IfdFlags::NONE,
        condition: None,
        omitted: Omitted::NONE,
        raw_conv: None,
        value_conv: None,
        print_conv: PrintConv::None,
        subdir: None,
    }],
    variants: &[],
};

/// `Image::ExifTool::IPTC::PreObjectData` -- 4 tags,
/// 0 `_variants` groups (IFD-style: PROCESS_PROC absent).
/// Generated from ExifTool's in-memory tag table. Do not edit by hand.
pub static IFD_IPTC_PREOBJECTDATA: IfdTable = IfdTable {
    module: "IPTC",
    table: "PreObjectData",
    group0: "IPTC",
    group1: "IPTC",
    group2: "Other",
    set_group1: None,
    priority: None,
    gate_a: GateA { blocked_by: &[] },
    tags: &[
        IfdTag {
            id: 0x000a,
            name: "SizeMode",
            format: Some(Fmt::Int8u),
            count: None,
            writable: None,
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[(0, "Size Not Known"), (1, "Size Known")]),
            subdir: None,
        },
        IfdTag {
            id: 0x0014,
            name: "MaxSubfileSize",
            format: Some(Fmt::Int32u),
            count: None,
            writable: None,
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x005a,
            name: "ObjectSizeAnnounced",
            format: Some(Fmt::Int32u),
            count: None,
            writable: None,
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x005f,
            name: "MaximumObjectSize",
            format: Some(Fmt::Int32u),
            count: None,
            writable: None,
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
    ],
    variants: &[],
};
