//! ExifTool `Nikon` IFD-style tables, generated from ExifTool
//! 13.59's own Perl hashes -- one file per module; `mod.rs` beside this
//! file is the hub that declares and re-exports it.
//!
//! DO NOT EDIT. Regenerate with `just regen-tables` (see `mod.rs`).

#![allow(clippy::unreadable_literal, clippy::too_many_lines, unused_parens)]

// Everything a table literal names -- the `ifd_schema` types, `ExprId`, the
// `cond`/`subdir`/`validation` imports -- is in scope in the hub, and a glob
// import of the parent module brings its private imports along (RFC 1560).
#[allow(unused_imports)]
use super::*;

/// `Image::ExifTool::Nikon::AVI` -- 0 tags,
/// 0 `_variants` groups (IFD-style: PROCESS_PROC absent).
/// Generated from ExifTool's in-memory tag table. Do not edit by hand.
pub static IFD_NIKON_AVI: IfdTable = IfdTable {
    module: "Nikon",
    table: "AVI",
    group0: "MakerNotes",
    group1: "Nikon",
    group2: "Video",
    set_group1: None,
    priority: None,
    gate_a: GateA {
        blocked_by: &[("ifd_tag_id_unrepresentable", 4)],
    },
    tags: &[],
    variants: &[],
};

/// `Image::ExifTool::Nikon::Composite` -- 0 tags,
/// 0 `_variants` groups (IFD-style: PROCESS_PROC absent).
/// Generated from ExifTool's in-memory tag table. Do not edit by hand.
pub static IFD_NIKON_COMPOSITE: IfdTable = IfdTable {
    module: "Nikon",
    table: "Composite",
    group0: "Composite",
    group1: "Composite",
    group2: "Camera",
    set_group1: None,
    priority: None,
    gate_a: GateA {
        blocked_by: &[("ifd_tag_id_unrepresentable", 5)],
    },
    tags: &[],
    variants: &[],
};

/// `Image::ExifTool::Nikon::NCDB` -- 0 tags,
/// 0 `_variants` groups (IFD-style: PROCESS_PROC absent).
/// Generated from ExifTool's in-memory tag table. Do not edit by hand.
pub static IFD_NIKON_NCDB: IfdTable = IfdTable {
    module: "Nikon",
    table: "NCDB",
    group0: "MakerNotes",
    group1: "Nikon",
    group2: "Video",
    set_group1: None,
    priority: None,
    gate_a: GateA { blocked_by: &[] },
    tags: &[],
    variants: &[],
};

/// `Image::ExifTool::Nikon::NCDT` -- 0 tags,
/// 0 `_variants` groups (IFD-style: PROCESS_PROC absent).
/// Generated from ExifTool's in-memory tag table. Do not edit by hand.
pub static IFD_NIKON_NCDT: IfdTable = IfdTable {
    module: "Nikon",
    table: "NCDT",
    group0: "MakerNotes",
    group1: "Nikon",
    group2: "Video",
    set_group1: None,
    priority: None,
    gate_a: GateA {
        blocked_by: &[("ifd_tag_id_unrepresentable", 7)],
    },
    tags: &[],
    variants: &[],
};

/// `Image::ExifTool::Nikon::NEFInfo` -- 2 tags,
/// 0 `_variants` groups (IFD-style: PROCESS_PROC absent).
/// Generated from ExifTool's in-memory tag table. Do not edit by hand.
pub static IFD_NIKON_NEFINFO: IfdTable = IfdTable {
    module: "Nikon",
    table: "NEFInfo",
    group0: "MakerNotes",
    group1: "Nikon",
    group2: "Camera",
    set_group1: None,
    priority: None,
    gate_a: GateA { blocked_by: &[] },
    tags: &[
        IfdTag {
            id: 0x0005,
            name: "DistortionInfo",
            format: None,
            count: None,
            writable: None,
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: false,
                condition: false,
                hook: false,
                subdirectory: true,
                print_conv: false,
            },
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: Some(IfdSubdirEdge {
                module: "Nikon",
                table: "DistortionInfo",
                start: IfdStart::ValuePtr(0),
                base: None,
                byte_order: IfdByteOrder::Inherit,
                fix_format: None,
                sub_ifd: false,
                max_subdirs: None,
                dir_name: None,
                validate: false,
                validation: None,
                processor: IfdSubdirProcessor::Native,
                unwalked: None,
            }),
        },
        IfdTag {
            id: 0x0006,
            name: "VignetteInfo",
            format: None,
            count: None,
            writable: None,
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: false,
                condition: false,
                hook: false,
                subdirectory: true,
                print_conv: false,
            },
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: Some(IfdSubdirEdge {
                module: "Nikon",
                table: "VignetteInfo",
                start: IfdStart::ValuePtr(0),
                base: None,
                byte_order: IfdByteOrder::Inherit,
                fix_format: None,
                sub_ifd: false,
                max_subdirs: None,
                dir_name: None,
                validate: false,
                validation: None,
                processor: IfdSubdirProcessor::Native,
                unwalked: None,
            }),
        },
    ],
    variants: &[],
};

/// `Image::ExifTool::Nikon::PreviewIFD` -- 6 tags,
/// 0 `_variants` groups (IFD-style: PROCESS_PROC absent).
/// Generated from ExifTool's in-memory tag table. Do not edit by hand.
pub static IFD_NIKON_PREVIEWIFD: IfdTable = IfdTable {
    module: "Nikon",
    table: "PreviewIFD",
    group0: "MakerNotes",
    group1: "PreviewIFD",
    group2: "Image",
    set_group1: None,
    priority: None,
    gate_a: GateA { blocked_by: &[] },
    tags: &[
        IfdTag {
            id: 0x00fe,
            name: "SubfileType",
            format: None,
            count: None,
            writable: None,
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: Some(RawConvEffect::SetMember {
                member: "SubfileType",
            }),
            value_conv: None,
            print_conv: PrintConv::Bitmask {
                exact: &[
                    (0, "Full-resolution image"),
                    (1, "Reduced-resolution image"),
                    (2, "Single page of multi-page image"),
                    (3, "Single page of multi-page reduced-resolution image"),
                    (4, "Transparency mask"),
                    (5, "Transparency mask of reduced-resolution image"),
                    (6, "Transparency mask of multi-page image"),
                    (
                        7,
                        "Transparency mask of reduced-resolution multi-page image",
                    ),
                    (8, "Depth map"),
                    (9, "Depth map of reduced-resolution image"),
                    (16, "Enhanced image data"),
                    (65537, "Alternate reduced-resolution image"),
                    (65540, "Semantic Mask"),
                    (4294967295, "invalid"),
                ],
                bits: &[
                    (0, "Reduced resolution"),
                    (1, "Single page"),
                    (2, "Transparency mask"),
                    (3, "TIFF/IT final page"),
                    (4, "TIFF-FX mixed raster content"),
                ],
            },
            subdir: None,
        },
        IfdTag {
            id: 0x0103,
            name: "Compression",
            format: None,
            count: None,
            writable: None,
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[
                (1, "Uncompressed"),
                (2, "CCITT 1D"),
                (3, "T4/Group 3 Fax"),
                (4, "T6/Group 4 Fax"),
                (5, "LZW"),
                (6, "JPEG (old-style)"),
                (7, "JPEG"),
                (8, "Adobe Deflate"),
                (9, "JBIG B&W or VC-5"),
                (10, "JBIG Color"),
                (99, "JPEG"),
                (262, "Kodak 262"),
                (32766, "NeXt or Sony ARW Compressed 2"),
                (32767, "Sony ARW Compressed"),
                (32769, "Packed RAW"),
                (32770, "Samsung SRW Compressed"),
                (32771, "CCIRLEW"),
                (32772, "Samsung SRW Compressed 2"),
                (32773, "PackBits"),
                (32809, "Thunderscan"),
                (32867, "Kodak KDC Compressed"),
                (32895, "IT8CTPAD"),
                (32896, "IT8LW"),
                (32897, "IT8MP"),
                (32898, "IT8BL"),
                (32908, "PixarFilm"),
                (32909, "PixarLog"),
                (32946, "Deflate"),
                (32947, "DCS"),
                (33003, "Aperio JPEG 2000 YCbCr"),
                (33005, "Aperio JPEG 2000 RGB"),
                (34661, "JBIG"),
                (34676, "SGILog"),
                (34677, "SGILog24"),
                (34712, "JPEG 2000"),
                (34713, "Nikon NEF Compressed"),
                (34715, "JBIG2 TIFF FX"),
                (34718, "Microsoft Document Imaging (MDI) Binary Level Codec"),
                (
                    34719,
                    "Microsoft Document Imaging (MDI) Progressive Transform Codec",
                ),
                (34720, "Microsoft Document Imaging (MDI) Vector"),
                (34887, "ESRI Lerc"),
                (34892, "Lossy JPEG"),
                (34925, "LZMA2"),
                (34926, "Zstd (old)"),
                (34927, "WebP (old)"),
                (34933, "PNG"),
                (34934, "JPEG XR"),
                (50000, "Zstd"),
                (50001, "WebP"),
                (50002, "JPEG XL (old)"),
                (52546, "JPEG XL"),
                (65000, "Kodak DCR Compressed"),
                (65535, "Pentax PEF Compressed"),
            ]),
            subdir: None,
        },
        IfdTag {
            id: 0x011a,
            name: "XResolution",
            format: None,
            count: None,
            writable: None,
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x011b,
            name: "YResolution",
            format: None,
            count: None,
            writable: None,
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x0128,
            name: "ResolutionUnit",
            format: None,
            count: None,
            writable: None,
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[(1, "None"), (2, "inches"), (3, "cm")]),
            subdir: None,
        },
        IfdTag {
            id: 0x0213,
            name: "YCbCrPositioning",
            format: None,
            count: None,
            writable: None,
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[(1, "Centered"), (2, "Co-sited")]),
            subdir: None,
        },
    ],
    variants: &[],
};

/// `Image::ExifTool::Nikon::Scan` -- 12 tags,
/// 0 `_variants` groups (IFD-style: PROCESS_PROC absent).
/// Generated from ExifTool's in-memory tag table. Do not edit by hand.
pub static IFD_NIKON_SCAN: IfdTable = IfdTable {
    module: "Nikon",
    table: "Scan",
    group0: "MakerNotes",
    group1: "NikonScan",
    group2: "Image",
    set_group1: None,
    priority: None,
    gate_a: GateA { blocked_by: &[] },
    tags: &[
        IfdTag {
            id: 0x0002,
            name: "FilmType",
            format: None,
            count: None,
            writable: Some("string"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x0040,
            name: "MultiSample",
            format: None,
            count: None,
            writable: Some("string"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x0041,
            name: "BitDepth",
            format: None,
            count: None,
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x0050,
            name: "MasterGain",
            format: None,
            count: None,
            writable: Some("rational64s"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::Expr(ExprId::Sprintf2fVal67A3D4),
            subdir: None,
        },
        IfdTag {
            id: 0x0051,
            name: "ColorGain",
            format: None,
            count: Some(3),
            writable: Some("rational64s"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::Expr(ExprId::Sprintf2f2f2fSplitVal3D873C),
            subdir: None,
        },
        IfdTag {
            id: 0x0060,
            name: "ScanImageEnhancer",
            format: None,
            count: None,
            writable: Some("int32u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[(0, "Off"), (1, "On")]),
            subdir: None,
        },
        IfdTag {
            id: 0x0100,
            name: "DigitalICE",
            format: None,
            count: None,
            writable: Some("string"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x0110,
            name: "ROCInfo",
            format: None,
            count: None,
            writable: None,
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: false,
                condition: false,
                hook: false,
                subdirectory: true,
                print_conv: false,
            },
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: Some(IfdSubdirEdge {
                module: "Nikon",
                table: "ROC",
                start: IfdStart::ValuePtr(0),
                base: None,
                byte_order: IfdByteOrder::Inherit,
                fix_format: None,
                sub_ifd: false,
                max_subdirs: None,
                dir_name: None,
                validate: false,
                validation: None,
                processor: IfdSubdirProcessor::Native,
                unwalked: None,
            }),
        },
        IfdTag {
            id: 0x0120,
            name: "GEMInfo",
            format: None,
            count: None,
            writable: None,
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: false,
                condition: false,
                hook: false,
                subdirectory: true,
                print_conv: false,
            },
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: Some(IfdSubdirEdge {
                module: "Nikon",
                table: "GEM",
                start: IfdStart::ValuePtr(0),
                base: None,
                byte_order: IfdByteOrder::Inherit,
                fix_format: None,
                sub_ifd: false,
                max_subdirs: None,
                dir_name: None,
                validate: false,
                validation: None,
                processor: IfdSubdirProcessor::Native,
                unwalked: None,
            }),
        },
        IfdTag {
            id: 0x0200,
            name: "DigitalDEEShadowAdj",
            format: None,
            count: None,
            writable: Some("int32u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x0201,
            name: "DigitalDEEThreshold",
            format: None,
            count: None,
            writable: Some("int32u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x0202,
            name: "DigitalDEEHighlightAdj",
            format: None,
            count: None,
            writable: Some("int32u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
    ],
    variants: &[],
};

/// `Image::ExifTool::Nikon::Type2` -- 8 tags,
/// 0 `_variants` groups (IFD-style: PROCESS_PROC absent).
/// Generated from ExifTool's in-memory tag table. Do not edit by hand.
pub static IFD_NIKON_TYPE2: IfdTable = IfdTable {
    module: "Nikon",
    table: "Type2",
    group0: "MakerNotes",
    group1: "Nikon",
    group2: "Camera",
    set_group1: None,
    priority: None,
    gate_a: GateA { blocked_by: &[] },
    tags: &[
        IfdTag {
            id: 0x0003,
            name: "Quality",
            format: None,
            count: None,
            writable: None,
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x0004,
            name: "ColorMode",
            format: None,
            count: None,
            writable: None,
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x0005,
            name: "ImageAdjustment",
            format: None,
            count: None,
            writable: None,
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x0006,
            name: "CCDSensitivity",
            format: None,
            count: None,
            writable: None,
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x0007,
            name: "WhiteBalance",
            format: None,
            count: None,
            writable: None,
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x0008,
            name: "Focus",
            format: None,
            count: None,
            writable: None,
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x000a,
            name: "DigitalZoom",
            format: None,
            count: None,
            writable: None,
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x000b,
            name: "Converter",
            format: None,
            count: None,
            writable: None,
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
    ],
    variants: &[],
};

/// `Image::ExifTool::Nikon::buttonsZ8` -- 0 tags,
/// 0 `_variants` groups (IFD-style: PROCESS_PROC absent).
/// Generated from ExifTool's in-memory tag table. Do not edit by hand.
pub static IFD_NIKON_BUTTONSZ8: IfdTable = IfdTable {
    module: "Nikon",
    table: "buttonsZ8",
    group0: "Nikon",
    group1: "Nikon",
    group2: "Other",
    set_group1: None,
    priority: None,
    gate_a: GateA {
        blocked_by: &[("ifd_tag_id_unrepresentable", 2)],
    },
    tags: &[],
    variants: &[],
};

/// `Image::ExifTool::Nikon::buttonsZ9` -- 0 tags,
/// 0 `_variants` groups (IFD-style: PROCESS_PROC absent).
/// Generated from ExifTool's in-memory tag table. Do not edit by hand.
pub static IFD_NIKON_BUTTONSZ9: IfdTable = IfdTable {
    module: "Nikon",
    table: "buttonsZ9",
    group0: "Nikon",
    group1: "Nikon",
    group2: "Other",
    set_group1: None,
    priority: None,
    gate_a: GateA {
        blocked_by: &[("ifd_tag_id_unrepresentable", 2)],
    },
    tags: &[],
    variants: &[],
};

/// `Image::ExifTool::Nikon::nikonLensIDs` -- 0 tags,
/// 0 `_variants` groups (IFD-style: PROCESS_PROC absent).
/// Generated from ExifTool's in-memory tag table. Do not edit by hand.
pub static IFD_NIKON_NIKONLENSIDS: IfdTable = IfdTable {
    module: "Nikon",
    table: "nikonLensIDs",
    group0: "Nikon",
    group1: "Nikon",
    group2: "Other",
    set_group1: None,
    priority: None,
    gate_a: GateA {
        blocked_by: &[("ifd_tag_id_unrepresentable", 620)],
    },
    tags: &[],
    variants: &[],
};
