//! ExifTool `Ricoh` IFD-style tables, generated from ExifTool
//! 13.59's own Perl hashes -- one file per module; `mod.rs` beside this
//! file is the hub that declares and re-exports it.
//!
//! DO NOT EDIT. Regenerate with `just regen-tables` (see `mod.rs`).

#![allow(clippy::unreadable_literal, clippy::too_many_lines, unused_parens)]

// Everything a table literal names -- the `ifd_schema` types, `ExprId`, the
// `cond`/`subdir`/`validation` imports -- is in scope in the hub, and a glob
// import of the parent module brings its private imports along (RFC 1560).
#[allow(unused_imports)]
use super::*;

/// `Image::ExifTool::Ricoh::AVI` -- 0 tags,
/// 0 `_variants` groups (IFD-style: PROCESS_PROC absent).
/// Generated from ExifTool's in-memory tag table. Do not edit by hand.
pub static IFD_RICOH_AVI: IfdTable = IfdTable {
    module: "Ricoh",
    table: "AVI",
    group0: "MakerNotes",
    group1: "Ricoh",
    group2: "Video",
    set_group1: None,
    priority: None,
    gate_a: GateA {
        blocked_by: &[("ifd_tag_id_unrepresentable", 4)],
    },
    tags: &[],
    variants: &[],
};

/// `Image::ExifTool::Ricoh::Composite` -- 0 tags,
/// 0 `_variants` groups (IFD-style: PROCESS_PROC absent).
/// Generated from ExifTool's in-memory tag table. Do not edit by hand.
pub static IFD_RICOH_COMPOSITE: IfdTable = IfdTable {
    module: "Ricoh",
    table: "Composite",
    group0: "Composite",
    group1: "Composite",
    group2: "Camera",
    set_group1: None,
    priority: None,
    gate_a: GateA {
        blocked_by: &[("ifd_tag_id_unrepresentable", 3)],
    },
    tags: &[],
    variants: &[],
};

/// `Image::ExifTool::Ricoh::Main` -- 40 tags,
/// 2 `_variants` groups (IFD-style: PROCESS_PROC absent).
/// Generated from ExifTool's in-memory tag table. Do not edit by hand.
pub static IFD_RICOH_MAIN: IfdTable = IfdTable {
    module: "Ricoh",
    table: "Main",
    group0: "MakerNotes",
    group1: "Ricoh",
    group2: "Camera",
    set_group1: None,
    priority: None,
    gate_a: GateA {
        blocked_by: &[
            ("tag_variant_cond_unsupported", 2),
            ("tag_variant_skipped", 2),
        ],
    },
    tags: &[
        IfdTag {
            id: 0x0001,
            name: "MakerNoteType",
            format: None,
            count: None,
            writable: Some("string"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x0002,
            name: "FirmwareVersion",
            format: None,
            count: None,
            writable: Some("string"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: false,
                condition: false,
                hook: false,
                subdirectory: false,
                print_conv: true,
            },
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x0e00,
            name: "PrintIM",
            format: None,
            count: None,
            writable: None,
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: false,
                condition: false,
                hook: false,
                subdirectory: true,
                print_conv: false,
            },
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: Some(IfdSubdirEdge {
                module: "PrintIM",
                table: "Main",
                start: IfdStart::ValuePtr(0),
                base: None,
                byte_order: IfdByteOrder::Inherit,
                fix_format: None,
                sub_ifd: false,
                max_subdirs: None,
                dir_name: None,
                validate: false,
                validation: None,
                processor: IfdSubdirProcessor::Native,
                unwalked: None,
            }),
        },
        IfdTag {
            id: 0x1000,
            name: "RecordingFormat",
            format: None,
            count: None,
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[(2, "JPEG"), (3, "DNG")]),
            subdir: None,
        },
        IfdTag {
            id: 0x1002,
            name: "DriveMode",
            format: None,
            count: None,
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: Some(Cond::FormatEq {
                value: "int16u",
                negate: false,
            }),
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[
                (0, "Single-frame"),
                (1, "Continuous"),
                (8, "AF-priority Continuous"),
            ]),
            subdir: None,
        },
        IfdTag {
            id: 0x1004,
            name: "WhiteBalanceFineTune",
            format: Some(Fmt::Int16s),
            count: None,
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: Some(Cond::FormatEq {
                value: "int16u",
                negate: false,
            }),
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x1006,
            name: "FocusMode",
            format: None,
            count: None,
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[
                (1, "Manual"),
                (2, "Multi AF"),
                (3, "Spot AF"),
                (4, "Snap"),
                (5, "Infinity"),
                (7, "Face Detect"),
                (8, "Subject Tracking"),
                (9, "Pinpoint AF"),
                (10, "Movie"),
            ]),
            subdir: None,
        },
        IfdTag {
            id: 0x1007,
            name: "AutoBracketing",
            format: None,
            count: None,
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[
                (0, "Off"),
                (9, "AE"),
                (11, "WB"),
                (16, "DR"),
                (17, "Contrast"),
                (18, "WB2"),
                (19, "Effect"),
            ]),
            subdir: None,
        },
        IfdTag {
            id: 0x1009,
            name: "MacroMode",
            format: None,
            count: None,
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[(0, "Off"), (1, "On")]),
            subdir: None,
        },
        IfdTag {
            id: 0x100a,
            name: "FlashMode",
            format: None,
            count: None,
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[
                (0, "Off"),
                (1, "Auto, Fired"),
                (2, "On"),
                (3, "Auto, Fired, Red-eye reduction"),
                (4, "Slow Sync"),
                (5, "Manual"),
                (6, "On, Red-eye reduction"),
                (7, "Synchro, Red-eye reduction"),
                (8, "Auto, Did not fire"),
            ]),
            subdir: None,
        },
        IfdTag {
            id: 0x100b,
            name: "FlashExposureComp",
            format: None,
            count: None,
            writable: Some("rational64s"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::Expr(ExprId::ValSprintf1fVal00A047C),
            subdir: None,
        },
        IfdTag {
            id: 0x100c,
            name: "ManualFlashOutput",
            format: None,
            count: None,
            writable: Some("rational64s"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[
                (-288, "1/64"),
                (-240, "1/32"),
                (-216, "1/22"),
                (-192, "1/16"),
                (-168, "1/11"),
                (-144, "1/8"),
                (-120, "1/5.6"),
                (-96, "1/4"),
                (-72, "1/2.8"),
                (-48, "1/2"),
                (-24, "1/1.4"),
                (0, "Full"),
            ]),
            subdir: None,
        },
        IfdTag {
            id: 0x100d,
            name: "FullPressSnap",
            format: None,
            count: None,
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[(0, "Off"), (1, "On")]),
            subdir: None,
        },
        IfdTag {
            id: 0x100e,
            name: "DynamicRangeExpansion",
            format: None,
            count: None,
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[
                (0, "Off"),
                (3, "Weak"),
                (4, "Medium"),
                (5, "Strong"),
            ]),
            subdir: None,
        },
        IfdTag {
            id: 0x100f,
            name: "NoiseReduction",
            format: None,
            count: None,
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[
                (0, "Off"),
                (1, "Weak"),
                (2, "Medium"),
                (3, "Strong"),
            ]),
            subdir: None,
        },
        IfdTag {
            id: 0x1010,
            name: "ImageEffects",
            format: None,
            count: None,
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[
                (0, "Standard"),
                (1, "Vivid"),
                (3, "Black & White"),
                (5, "B&W Toning Effect"),
                (6, "Setting 1"),
                (7, "Setting 2"),
                (9, "High-contrast B&W"),
                (10, "Cross Process"),
                (11, "Positive Film"),
                (12, "Bleach Bypass"),
                (13, "Retro"),
                (15, "Miniature"),
                (17, "High Key"),
            ]),
            subdir: None,
        },
        IfdTag {
            id: 0x1011,
            name: "Vignetting",
            format: None,
            count: None,
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[(0, "Off"), (1, "Low"), (2, "Medium"), (3, "High")]),
            subdir: None,
        },
        IfdTag {
            id: 0x1012,
            name: "Contrast",
            format: Some(Fmt::Int32s),
            count: None,
            writable: Some("int32u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: false,
                condition: false,
                hook: false,
                subdirectory: false,
                print_conv: true,
            },
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x1013,
            name: "Saturation",
            format: None,
            count: None,
            writable: Some("int32u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x1014,
            name: "Sharpness",
            format: None,
            count: None,
            writable: Some("int32u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x1015,
            name: "ToningEffect",
            format: None,
            count: None,
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[
                (0, "Off"),
                (1, "Sepia"),
                (2, "Red"),
                (3, "Green"),
                (4, "Blue"),
                (5, "Purple"),
                (6, "B&W"),
                (7, "Color"),
            ]),
            subdir: None,
        },
        IfdTag {
            id: 0x1016,
            name: "HueAdjust",
            format: None,
            count: None,
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[
                (0, "Off"),
                (1, "Basic"),
                (2, "Magenta"),
                (3, "Yellow"),
                (4, "Normal"),
                (5, "Warm"),
                (6, "Cool"),
            ]),
            subdir: None,
        },
        IfdTag {
            id: 0x1017,
            name: "WideAdapter",
            format: None,
            count: None,
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[(0, "Not Attached"), (2, "Attached")]),
            subdir: None,
        },
        IfdTag {
            id: 0x1018,
            name: "CropMode",
            format: None,
            count: None,
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[(0, "Off"), (1, "On (35mm)"), (2, "On (47mm)")]),
            subdir: None,
        },
        IfdTag {
            id: 0x1019,
            name: "NDFilter",
            format: None,
            count: None,
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[(0, "Off"), (1, "On")]),
            subdir: None,
        },
        IfdTag {
            id: 0x101a,
            name: "WBBracketShotNumber",
            format: None,
            count: None,
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x1200,
            name: "AFStatus",
            format: None,
            count: None,
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[(0, "Out of Focus"), (1, "In Focus")]),
            subdir: None,
        },
        IfdTag {
            id: 0x1201,
            name: "AFAreaXPosition1",
            format: None,
            count: None,
            writable: Some("int32u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x1202,
            name: "AFAreaYPosition1",
            format: None,
            count: None,
            writable: Some("int32u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x1203,
            name: "AFAreaXPosition",
            format: None,
            count: None,
            writable: Some("int32u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x1204,
            name: "AFAreaYPosition",
            format: None,
            count: None,
            writable: Some("int32u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x1205,
            name: "AFAreaMode",
            format: None,
            count: None,
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[(0, "Auto"), (2, "Manual")]),
            subdir: None,
        },
        IfdTag {
            id: 0x1307,
            name: "ColorTempKelvin",
            format: None,
            count: None,
            writable: Some("int32u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x1308,
            name: "ColorTemperature",
            format: None,
            count: None,
            writable: Some("int32u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x1500,
            name: "FocalLength",
            format: None,
            count: None,
            writable: Some("rational64u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::Expr(ExprId::Sprintf1fMmVal03B2CA),
            subdir: None,
        },
        IfdTag {
            id: 0x1601,
            name: "SensorWidth",
            format: None,
            count: None,
            writable: Some("int32u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x1602,
            name: "SensorHeight",
            format: None,
            count: None,
            writable: Some("int32u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x1603,
            name: "CroppedImageWidth",
            format: None,
            count: None,
            writable: Some("int32u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x1604,
            name: "CroppedImageHeight",
            format: None,
            count: None,
            writable: Some("int32u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x4001,
            name: "ThetaSubdir",
            format: None,
            count: None,
            writable: None,
            groups: TagGroups {
                g0: None,
                g1: Some("MakerNotes"),
                g2: None,
            },
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: false,
                condition: false,
                hook: false,
                subdirectory: true,
                print_conv: false,
            },
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: Some(IfdSubdirEdge {
                module: "Ricoh",
                table: "ThetaSubdir",
                start: IfdStart::Val(0),
                base: None,
                byte_order: IfdByteOrder::Inherit,
                fix_format: None,
                sub_ifd: true,
                max_subdirs: None,
                dir_name: None,
                validate: false,
                validation: None,
                processor: IfdSubdirProcessor::Native,
                unwalked: None,
            }),
        },
    ],
    variants: &[
        IfdVariantGroup {
            id: 0x1001,
            alternatives: &[
                (
                    Cond::FormatEq {
                        value: "int16u",
                        negate: true,
                    },
                    IfdTag {
                        id: 0x1001,
                        name: "ImageInfo",
                        format: None,
                        count: None,
                        writable: None,
                        groups: TagGroups::NONE,
                        flags: IfdFlags::NONE,
                        condition: None,
                        omitted: Omitted {
                            value_conv: false,
                            raw_conv: false,
                            condition: false,
                            hook: false,
                            subdirectory: true,
                            print_conv: false,
                        },
                        raw_conv: None,
                        value_conv: None,
                        print_conv: PrintConv::None,
                        subdir: Some(IfdSubdirEdge {
                            module: "Ricoh",
                            table: "ImageInfo",
                            start: IfdStart::ValuePtr(0),
                            base: None,
                            byte_order: IfdByteOrder::Inherit,
                            fix_format: None,
                            sub_ifd: false,
                            max_subdirs: None,
                            dir_name: None,
                            validate: false,
                            validation: None,
                            processor: IfdSubdirProcessor::Native,
                            unwalked: None,
                        }),
                    },
                ),
                (
                    Cond::Always,
                    IfdTag {
                        id: 0x1001,
                        name: "ExposureProgram",
                        format: None,
                        count: None,
                        writable: Some("int16u"),
                        groups: TagGroups::NONE,
                        flags: IfdFlags::NONE,
                        condition: None,
                        omitted: Omitted::NONE,
                        raw_conv: None,
                        value_conv: None,
                        print_conv: PrintConv::IntEnum(&[
                            (1, "Auto"),
                            (2, "Program AE"),
                            (3, "Aperture-priority AE"),
                            (4, "Shutter speed priority AE"),
                            (5, "Shutter/aperture priority AE"),
                            (6, "Manual"),
                            (7, "Movie"),
                        ]),
                        subdir: None,
                    },
                ),
            ],
        },
        IfdVariantGroup {
            id: 0x1003,
            alternatives: &[
                (
                    Cond::FormatEq {
                        value: "int16u",
                        negate: true,
                    },
                    IfdTag {
                        id: 0x1003,
                        name: "Sharpness",
                        format: None,
                        count: None,
                        writable: Some("int32u"),
                        groups: TagGroups::NONE,
                        flags: IfdFlags::NONE,
                        condition: None,
                        omitted: Omitted::NONE,
                        raw_conv: None,
                        value_conv: None,
                        print_conv: PrintConv::IntEnum(&[(0, "Sharp"), (1, "Normal"), (2, "Soft")]),
                        subdir: None,
                    },
                ),
                (
                    Cond::Always,
                    IfdTag {
                        id: 0x1003,
                        name: "WhiteBalance",
                        format: None,
                        count: None,
                        writable: Some("int16u"),
                        groups: TagGroups::NONE,
                        flags: IfdFlags::NONE,
                        condition: None,
                        omitted: Omitted::NONE,
                        raw_conv: None,
                        value_conv: None,
                        print_conv: PrintConv::IntEnum(&[
                            (0, "Auto"),
                            (1, "Multi-P Auto"),
                            (2, "Daylight"),
                            (3, "Cloudy"),
                            (4, "Incandescent 1"),
                            (5, "Incandescent 2"),
                            (6, "Daylight Fluorescent"),
                            (7, "Neutral White Fluorescent"),
                            (8, "Cool White Fluorescent"),
                            (9, "Warm White Fluorescent"),
                            (10, "Manual"),
                            (11, "Kelvin"),
                            (12, "Shade"),
                        ]),
                        subdir: None,
                    },
                ),
            ],
        },
    ],
};

/// `Image::ExifTool::Ricoh::RDTL` -- 4 tags,
/// 0 `_variants` groups (IFD-style: PROCESS_PROC absent).
/// Generated from ExifTool's in-memory tag table. Do not edit by hand.
pub static IFD_RICOH_RDTL: IfdTable = IfdTable {
    module: "Ricoh",
    table: "RDTL",
    group0: "MakerNotes",
    group1: "Ricoh",
    group2: "Location",
    set_group1: None,
    priority: None,
    gate_a: GateA { blocked_by: &[] },
    tags: &[
        IfdTag {
            id: 0x0000,
            name: "GPSDateTime",
            format: Some(Fmt::Double),
            count: None,
            writable: None,
            groups: TagGroups {
                g0: None,
                g1: None,
                g2: Some("Time"),
            },
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted {
                value_conv: true,
                raw_conv: false,
                condition: false,
                hook: false,
                subdirectory: false,
                print_conv: true,
            },
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x0008,
            name: "GPSLatitude",
            format: Some(Fmt::Double),
            count: None,
            writable: None,
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::Expr(ExprId::ImageExifToolGPSToDMSSelfVal15C3C42),
            subdir: None,
        },
        IfdTag {
            id: 0x0010,
            name: "GPSLongitude",
            format: Some(Fmt::Double),
            count: None,
            writable: None,
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::Expr(ExprId::ImageExifToolGPSToDMSSelfVal15C3C42),
            subdir: None,
        },
        IfdTag {
            id: 0x0018,
            name: "GPSAltitude",
            format: Some(Fmt::Double),
            count: None,
            writable: None,
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: false,
                condition: false,
                hook: false,
                subdirectory: false,
                print_conv: true,
            },
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
    ],
    variants: &[],
};

/// `Image::ExifTool::Ricoh::Subdir` -- 6 tags,
/// 0 `_variants` groups (IFD-style: PROCESS_PROC absent).
/// Generated from ExifTool's in-memory tag table. Do not edit by hand.
pub static IFD_RICOH_SUBDIR: IfdTable = IfdTable {
    module: "Ricoh",
    table: "Subdir",
    group0: "MakerNotes",
    group1: "Ricoh",
    group2: "Camera",
    set_group1: None,
    priority: None,
    gate_a: GateA { blocked_by: &[] },
    tags: &[
        IfdTag {
            id: 0x0004,
            name: "ManufactureDate1",
            format: None,
            count: Some(20),
            writable: Some("string"),
            groups: TagGroups {
                g0: None,
                g1: None,
                g2: Some("Time"),
            },
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x0005,
            name: "ManufactureDate2",
            format: None,
            count: Some(20),
            writable: Some("string"),
            groups: TagGroups {
                g0: None,
                g1: None,
                g2: Some("Time"),
            },
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x001a,
            name: "FaceInfo",
            format: None,
            count: None,
            writable: None,
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: false,
                condition: false,
                hook: false,
                subdirectory: true,
                print_conv: false,
            },
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: Some(IfdSubdirEdge {
                module: "Ricoh",
                table: "FaceInfo",
                start: IfdStart::ValuePtr(0),
                base: None,
                byte_order: IfdByteOrder::Inherit,
                fix_format: None,
                sub_ifd: false,
                max_subdirs: None,
                dir_name: None,
                validate: false,
                validation: None,
                processor: IfdSubdirProcessor::Native,
                unwalked: None,
            }),
        },
        IfdTag {
            id: 0x0029,
            name: "FirmwareInfo",
            format: None,
            count: None,
            writable: None,
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: false,
                condition: false,
                hook: false,
                subdirectory: true,
                print_conv: false,
            },
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: Some(IfdSubdirEdge {
                module: "Ricoh",
                table: "FirmwareInfo",
                start: IfdStart::ValuePtr(0),
                base: None,
                byte_order: IfdByteOrder::Inherit,
                fix_format: None,
                sub_ifd: false,
                max_subdirs: None,
                dir_name: None,
                validate: false,
                validation: None,
                processor: IfdSubdirProcessor::Native,
                unwalked: None,
            }),
        },
        IfdTag {
            id: 0x002a,
            name: "NoiseReduction",
            format: None,
            count: None,
            writable: Some("int32u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[(0, "Off"), (1, "Weak"), (2, "Strong"), (3, "Max")]),
            subdir: None,
        },
        IfdTag {
            id: 0x002c,
            name: "SerialInfo",
            format: None,
            count: None,
            writable: None,
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: false,
                condition: false,
                hook: false,
                subdirectory: true,
                print_conv: false,
            },
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: Some(IfdSubdirEdge {
                module: "Ricoh",
                table: "SerialInfo",
                start: IfdStart::ValuePtr(0),
                base: None,
                byte_order: IfdByteOrder::Inherit,
                fix_format: None,
                sub_ifd: false,
                max_subdirs: None,
                dir_name: None,
                validate: false,
                validation: None,
                processor: IfdSubdirProcessor::Native,
                unwalked: None,
            }),
        },
    ],
    variants: &[],
};

/// `Image::ExifTool::Ricoh::ThetaSubdir` -- 3 tags,
/// 0 `_variants` groups (IFD-style: PROCESS_PROC absent).
/// Generated from ExifTool's in-memory tag table. Do not edit by hand.
pub static IFD_RICOH_THETASUBDIR: IfdTable = IfdTable {
    module: "Ricoh",
    table: "ThetaSubdir",
    group0: "MakerNotes",
    group1: "Ricoh",
    group2: "Camera",
    set_group1: None,
    priority: None,
    gate_a: GateA { blocked_by: &[] },
    tags: &[
        IfdTag {
            id: 0x0003,
            name: "Accelerometer",
            format: None,
            count: Some(2),
            writable: Some("rational64s"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x0004,
            name: "Compass",
            format: None,
            count: None,
            writable: Some("rational64u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x000a,
            name: "TimeZone",
            format: None,
            count: None,
            writable: Some("string"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
    ],
    variants: &[],
};

/// `Image::ExifTool::Ricoh::Type2` -- 2 tags,
/// 0 `_variants` groups (IFD-style: PROCESS_PROC absent).
/// Generated from ExifTool's in-memory tag table. Do not edit by hand.
pub static IFD_RICOH_TYPE2: IfdTable = IfdTable {
    module: "Ricoh",
    table: "Type2",
    group0: "MakerNotes",
    group1: "Ricoh",
    group2: "Camera",
    set_group1: None,
    priority: None,
    gate_a: GateA { blocked_by: &[] },
    tags: &[
        IfdTag {
            id: 0x0207,
            name: "RicohModel",
            format: None,
            count: None,
            writable: Some("string"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x0300,
            name: "RicohMake",
            format: None,
            count: None,
            writable: Some("undef"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted {
                value_conv: true,
                raw_conv: false,
                condition: false,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
    ],
    variants: &[],
};
