//! ExifTool `Samsung` IFD-style tables, generated from ExifTool
//! 13.59's own Perl hashes -- one file per module; `mod.rs` beside this
//! file is the hub that declares and re-exports it.
//!
//! DO NOT EDIT. Regenerate with `just regen-tables` (see `mod.rs`).

#![allow(clippy::unreadable_literal, clippy::too_many_lines, unused_parens)]

// Everything a table literal names -- the `ifd_schema` types, `ExprId`, the
// `cond`/`subdir`/`validation` imports -- is in scope in the hub, and a glob
// import of the parent module brings its private imports along (RFC 1560).
#[allow(unused_imports)]
use super::*;

/// `Image::ExifTool::Samsung::APP5` -- 0 tags,
/// 0 `_variants` groups (IFD-style: PROCESS_PROC absent).
/// Generated from ExifTool's in-memory tag table. Do not edit by hand.
pub static IFD_SAMSUNG_APP5: IfdTable = IfdTable {
    module: "Samsung",
    table: "APP5",
    group0: "MakerNotes",
    group1: "Samsung",
    group2: "Camera",
    set_group1: None,
    priority: None,
    gate_a: GateA {
        blocked_by: &[("ifd_tag_id_unrepresentable", 1)],
    },
    tags: &[],
    variants: &[],
};

/// `Image::ExifTool::Samsung::Composite` -- 0 tags,
/// 0 `_variants` groups (IFD-style: PROCESS_PROC absent).
/// Generated from ExifTool's in-memory tag table. Do not edit by hand.
pub static IFD_SAMSUNG_COMPOSITE: IfdTable = IfdTable {
    module: "Samsung",
    table: "Composite",
    group0: "Composite",
    group1: "Composite",
    group2: "Image",
    set_group1: None,
    priority: None,
    gate_a: GateA {
        blocked_by: &[("ifd_tag_id_unrepresentable", 3)],
    },
    tags: &[],
    variants: &[],
};

/// `Image::ExifTool::Samsung::Type2` -- 54 tags,
/// 1 `_variants` groups (IFD-style: PROCESS_PROC absent).
/// Generated from ExifTool's in-memory tag table. Do not edit by hand.
pub static IFD_SAMSUNG_TYPE2: IfdTable = IfdTable {
    module: "Samsung",
    table: "Type2",
    group0: "MakerNotes",
    group1: "Samsung",
    group2: "Image",
    set_group1: None,
    priority: None,
    gate_a: GateA {
        blocked_by: &[
            ("tag_variant_cond_unsupported", 1),
            ("tag_variant_skipped", 1),
        ],
    },
    tags: &[
        IfdTag {
            id: 0x0001,
            name: "MakerNoteVersion",
            format: None,
            count: Some(4),
            writable: Some("undef"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x0002,
            name: "DeviceType",
            format: None,
            count: None,
            writable: Some("int32u"),
            groups: TagGroups {
                g0: None,
                g1: None,
                g2: Some("Camera"),
            },
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::PartialEnumInt {
                exact: &[
                    (4096, "Compact Digital Camera"),
                    (8192, "High-end NX Camera"),
                    (12288, "HXM Video Camera"),
                    (73728, "Cell Phone"),
                    (3145728, "SMX Video Camera"),
                ],
                other: None,
                print_hex: true,
            },
            subdir: None,
        },
        IfdTag {
            id: 0x0003,
            name: "SamsungModelID",
            format: None,
            count: None,
            writable: Some("int32u"),
            groups: TagGroups {
                g0: None,
                g1: None,
                g2: Some("Camera"),
            },
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::PartialEnumInt {
                exact: &[
                    (16781340, "NX10"),
                    (16781862, "HMX-S15BP"),
                    (16781875, "HMX-Q10"),
                    (16781876, "HMX-H304"),
                    (16782092, "NX100"),
                    (16782119, "NX11"),
                    (24121419, "ES65, ES67 / VLUU ES65, ES67 / SL50"),
                    (24121422, "ES70, ES71 / VLUU ES70, ES71 / SL600"),
                    (24121426, "ES73 / VLUU ES73 / SL605"),
                    (24121429, "ES25, ES27 / VLUU ES25, ES27 / SL45"),
                    (24122112, "ES28 / VLUU ES28"),
                    (24122115, "ES74,ES75,ES78 / VLUU ES75,ES78"),
                    (33558598, "PL150 / VLUU PL150 / TL210 / PL151"),
                    (33558600, "PL100 / TL205 / VLUU PL100 / PL101"),
                    (33559313, "PL120,PL121 / VLUU PL120,PL121"),
                    (33559317, "PL170,PL171 / VLUUPL170,PL171"),
                    (33559326, "PL210, PL211 / VLUU PL210, PL211"),
                    (40899351, "PL20,PL21 / VLUU PL20,PL21"),
                    (44040219, "WP10 / VLUU WP10 / AQ100"),
                    (50331648, "Various Models (0x3000000)"),
                    (60817432, "Various Models (0x3a00018)"),
                    (67112991, "ST1000 / ST1100 / VLUU ST1000 / CL65"),
                    (67112994, "ST550 / VLUU ST550 / TL225"),
                    (67112997, "Various Models (0x4001025)"),
                    (67113022, "VLUU ST5500, ST5500, CL80"),
                    (67113025, "VLUU ST5000, ST5000, TL240"),
                    (67113027, "ST70 / VLUU ST70 / ST71"),
                    (67113738, "Various Models (0x400130a)"),
                    (67113742, "ST90,ST91 / VLUU ST90,ST91"),
                    (67113747, "VLUU ST95, ST95"),
                    (77594645, "VLUU ST60"),
                    (77599579, "ST30, ST65 / VLUU ST65 / ST67"),
                    (83886080, "Various Models (0x5000000)"),
                    (83890232, "Various Models (0x5001038)"),
                    (83890234, "WB650 / VLUU WB650 / WB660"),
                    (83890236, "WB600 / VLUU WB600 / WB610"),
                    (83891006, "WB150 / WB150F / WB152 / WB152F / WB151"),
                    (94371855, "WB5000 / HZ25W"),
                    (94371870, "WB5500 / VLUU WB5500 / HZ50W"),
                    (100667446, "EX1"),
                    (117445404, "VLUU SH100, SH100"),
                    (655519746, "SMX-C20N"),
                ],
                other: None,
                print_hex: true,
            },
            subdir: None,
        },
        IfdTag {
            id: 0x0011,
            name: "OrientationInfo",
            format: None,
            count: None,
            writable: None,
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: false,
                condition: false,
                hook: false,
                subdirectory: true,
                print_conv: false,
            },
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: Some(IfdSubdirEdge {
                module: "Samsung",
                table: "OrientationInfo",
                start: IfdStart::ValuePtr(0),
                base: None,
                byte_order: IfdByteOrder::Inherit,
                fix_format: None,
                sub_ifd: false,
                max_subdirs: None,
                dir_name: None,
                validate: false,
                validation: None,
                processor: IfdSubdirProcessor::Native,
                unwalked: None,
            }),
        },
        IfdTag {
            id: 0x0021,
            name: "PictureWizard",
            format: None,
            count: None,
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: false,
                condition: false,
                hook: false,
                subdirectory: true,
                print_conv: false,
            },
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: Some(IfdSubdirEdge {
                module: "Samsung",
                table: "PictureWizard",
                start: IfdStart::ValuePtr(0),
                base: None,
                byte_order: IfdByteOrder::Inherit,
                fix_format: None,
                sub_ifd: false,
                max_subdirs: None,
                dir_name: None,
                validate: false,
                validation: None,
                processor: IfdSubdirProcessor::Native,
                unwalked: None,
            }),
        },
        IfdTag {
            id: 0x0030,
            name: "LocalLocationName",
            format: Some(Fmt::Undef(0)),
            count: None,
            writable: Some("string"),
            groups: TagGroups {
                g0: None,
                g1: None,
                g2: Some("Location"),
            },
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted {
                value_conv: true,
                raw_conv: false,
                condition: false,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x0031,
            name: "LocationName",
            format: None,
            count: None,
            writable: Some("string"),
            groups: TagGroups {
                g0: None,
                g1: None,
                g2: Some("Location"),
            },
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x0040,
            name: "RawDataByteOrder",
            format: None,
            count: None,
            writable: None,
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[
                (0, "Little-endian (Intel, II)"),
                (1, "Big-endian (Motorola, MM)"),
            ]),
            subdir: None,
        },
        IfdTag {
            id: 0x0041,
            name: "WhiteBalanceSetup",
            format: None,
            count: None,
            writable: Some("int32u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[(0, "Auto"), (1, "Manual")]),
            subdir: None,
        },
        IfdTag {
            id: 0x0043,
            name: "CameraTemperature",
            format: None,
            count: None,
            writable: Some("rational64s"),
            groups: TagGroups {
                g0: None,
                g1: None,
                g2: Some("Camera"),
            },
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: false,
                condition: false,
                hook: false,
                subdirectory: false,
                print_conv: true,
            },
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x0050,
            name: "RawDataCFAPattern",
            format: None,
            count: None,
            writable: None,
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[(0, "Unchanged"), (1, "Swap"), (65535, "Roll")]),
            subdir: None,
        },
        IfdTag {
            id: 0x0100,
            name: "FaceDetect",
            format: None,
            count: None,
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[(0, "Off"), (1, "On")]),
            subdir: None,
        },
        IfdTag {
            id: 0x0120,
            name: "FaceRecognition",
            format: None,
            count: None,
            writable: Some("int32u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[(0, "Off"), (1, "On")]),
            subdir: None,
        },
        IfdTag {
            id: 0x0123,
            name: "FaceName",
            format: None,
            count: None,
            writable: Some("string"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0xa001,
            name: "FirmwareName",
            format: None,
            count: None,
            writable: Some("string"),
            groups: TagGroups {
                g0: None,
                g1: None,
                g2: Some("Camera"),
            },
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0xa002,
            name: "SerialNumber",
            format: None,
            count: None,
            writable: Some("string"),
            groups: TagGroups {
                g0: None,
                g1: None,
                g2: Some("Camera"),
            },
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: false,
                condition: true,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0xa003,
            name: "LensType",
            format: None,
            count: None,
            writable: Some("int16u"),
            groups: TagGroups {
                g0: None,
                g1: None,
                g2: Some("Camera"),
            },
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: false,
                condition: false,
                hook: false,
                subdirectory: false,
                print_conv: true,
            },
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0xa004,
            name: "LensFirmware",
            format: None,
            count: None,
            writable: Some("string"),
            groups: TagGroups {
                g0: None,
                g1: None,
                g2: Some("Camera"),
            },
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0xa005,
            name: "InternalLensSerialNumber",
            format: None,
            count: None,
            writable: Some("string"),
            groups: TagGroups {
                g0: None,
                g1: None,
                g2: Some("Camera"),
            },
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0xa010,
            name: "SensorAreas",
            format: None,
            count: Some(8),
            writable: Some("int32u"),
            groups: TagGroups {
                g0: None,
                g1: None,
                g2: Some("Camera"),
            },
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0xa011,
            name: "ColorSpace",
            format: None,
            count: None,
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[(0, "sRGB"), (1, "Adobe RGB")]),
            subdir: None,
        },
        IfdTag {
            id: 0xa012,
            name: "SmartRange",
            format: None,
            count: None,
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[(0, "Off"), (1, "On")]),
            subdir: None,
        },
        IfdTag {
            id: 0xa013,
            name: "ExposureCompensation",
            format: None,
            count: None,
            writable: Some("rational64s"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0xa014,
            name: "ISO",
            format: None,
            count: None,
            writable: Some("int32u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0xa018,
            name: "ExposureTime",
            format: None,
            count: None,
            writable: Some("rational64u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted {
                value_conv: true,
                raw_conv: false,
                condition: false,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::Expr(ExprId::ImageExifToolExifPrintExposureTimeVal6037F3),
            subdir: None,
        },
        IfdTag {
            id: 0xa019,
            name: "FNumber",
            format: None,
            count: None,
            writable: Some("rational64u"),
            groups: TagGroups::NONE,
            flags: IfdFlags {
                unknown: false,
                binary: false,
                list: false,
                protected: false,
                avoid: false,
                priority: Some(0),
            },
            condition: None,
            omitted: Omitted {
                value_conv: true,
                raw_conv: false,
                condition: false,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::Expr(ExprId::Sprintf1fVal2C65CD),
            subdir: None,
        },
        IfdTag {
            id: 0xa01a,
            name: "FocalLengthIn35mmFormat",
            format: Some(Fmt::Int32u),
            count: None,
            writable: None,
            groups: TagGroups {
                g0: None,
                g1: None,
                g2: Some("Camera"),
            },
            flags: IfdFlags {
                unknown: false,
                binary: false,
                list: false,
                protected: false,
                avoid: false,
                priority: Some(0),
            },
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: Some(ExprId::Val100C7AB9),
            print_conv: PrintConv::Expr(ExprId::ValMm18ABDF),
            subdir: None,
        },
        IfdTag {
            id: 0xa020,
            name: "EncryptionKey",
            format: None,
            count: Some(11),
            writable: Some("int32u"),
            groups: TagGroups::NONE,
            flags: IfdFlags {
                unknown: false,
                binary: false,
                list: false,
                protected: true,
                avoid: false,
                priority: None,
            },
            condition: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: true,
                condition: false,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0xa021,
            name: "WB_RGGBLevelsUncorrected",
            format: None,
            count: Some(4),
            writable: Some("int32u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: true,
                condition: false,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0xa022,
            name: "WB_RGGBLevelsAuto",
            format: None,
            count: Some(4),
            writable: Some("int32u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: true,
                condition: false,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0xa023,
            name: "WB_RGGBLevelsIlluminator1",
            format: None,
            count: Some(4),
            writable: Some("int32u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: true,
                condition: false,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0xa024,
            name: "WB_RGGBLevelsIlluminator2",
            format: None,
            count: Some(4),
            writable: Some("int32u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: true,
                condition: false,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0xa025,
            name: "HighlightLinearityLimit",
            format: None,
            count: None,
            writable: Some("int32u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0xa028,
            name: "WB_RGGBLevelsBlack",
            format: None,
            count: Some(4),
            writable: Some("int32s"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: true,
                condition: false,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0xa030,
            name: "ColorMatrix",
            format: None,
            count: Some(9),
            writable: Some("int32s"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: true,
                condition: false,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0xa031,
            name: "ColorMatrixSRGB",
            format: None,
            count: Some(9),
            writable: Some("int32s"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: true,
                condition: false,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0xa032,
            name: "ColorMatrixAdobeRGB",
            format: None,
            count: Some(9),
            writable: Some("int32s"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: true,
                condition: false,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0xa033,
            name: "CbCrMatrixDefault",
            format: None,
            count: Some(4),
            writable: Some("int32s"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: true,
                condition: false,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0xa034,
            name: "CbCrMatrix",
            format: None,
            count: Some(4),
            writable: Some("int32s"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: true,
                condition: false,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0xa035,
            name: "CbCrGainDefault",
            format: None,
            count: Some(2),
            writable: Some("int32u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: true,
                condition: false,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0xa036,
            name: "CbCrGain",
            format: None,
            count: Some(2),
            writable: Some("int32u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: true,
                condition: false,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0xa040,
            name: "ToneCurveSRGBDefault",
            format: None,
            count: Some(23),
            writable: Some("int32u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: true,
                condition: false,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0xa041,
            name: "ToneCurveAdobeRGBDefault",
            format: None,
            count: Some(23),
            writable: Some("int32u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: true,
                condition: false,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0xa042,
            name: "ToneCurveSRGB",
            format: None,
            count: Some(23),
            writable: Some("int32u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: true,
                condition: false,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0xa043,
            name: "ToneCurveAdobeRGB",
            format: None,
            count: Some(23),
            writable: Some("int32u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: true,
                condition: false,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0xa048,
            name: "RawData",
            format: None,
            count: Some(12),
            writable: Some("int32s"),
            groups: TagGroups::NONE,
            flags: IfdFlags {
                unknown: true,
                binary: false,
                list: false,
                protected: false,
                avoid: false,
                priority: None,
            },
            condition: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: true,
                condition: false,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0xa050,
            name: "Distortion",
            format: None,
            count: Some(8),
            writable: Some("int32s"),
            groups: TagGroups::NONE,
            flags: IfdFlags {
                unknown: true,
                binary: false,
                list: false,
                protected: false,
                avoid: false,
                priority: None,
            },
            condition: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: true,
                condition: false,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0xa051,
            name: "ChromaticAberration",
            format: None,
            count: Some(22),
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags {
                unknown: true,
                binary: false,
                list: false,
                protected: false,
                avoid: false,
                priority: None,
            },
            condition: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: true,
                condition: false,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0xa052,
            name: "Vignetting",
            format: None,
            count: Some(15),
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags {
                unknown: true,
                binary: false,
                list: false,
                protected: false,
                avoid: false,
                priority: None,
            },
            condition: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: true,
                condition: false,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0xa053,
            name: "VignettingCorrection",
            format: None,
            count: Some(15),
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags {
                unknown: true,
                binary: false,
                list: false,
                protected: false,
                avoid: false,
                priority: None,
            },
            condition: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: true,
                condition: false,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0xa054,
            name: "VignettingSetting",
            format: None,
            count: Some(15),
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags {
                unknown: true,
                binary: false,
                list: false,
                protected: false,
                avoid: false,
                priority: None,
            },
            condition: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: true,
                condition: false,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0xa055,
            name: "Samsung_Type2_0xa055",
            format: None,
            count: Some(8),
            writable: Some("int32s"),
            groups: TagGroups::NONE,
            flags: IfdFlags {
                unknown: true,
                binary: false,
                list: false,
                protected: false,
                avoid: false,
                priority: None,
            },
            condition: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: true,
                condition: false,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0xa056,
            name: "Samsung_Type2_0xa056",
            format: None,
            count: Some(8),
            writable: Some("int32s"),
            groups: TagGroups::NONE,
            flags: IfdFlags {
                unknown: true,
                binary: false,
                list: false,
                protected: false,
                avoid: false,
                priority: None,
            },
            condition: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: true,
                condition: false,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0xa057,
            name: "Samsung_Type2_0xa057",
            format: None,
            count: Some(8),
            writable: Some("int32s"),
            groups: TagGroups::NONE,
            flags: IfdFlags {
                unknown: true,
                binary: false,
                list: false,
                protected: false,
                avoid: false,
                priority: None,
            },
            condition: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: true,
                condition: false,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
    ],
    variants: &[IfdVariantGroup {
        id: 0x0035,
        alternatives: &[
            (
                Cond::And(
                    &Cond::MemberStrEq {
                        member: "TIFF_TYPE",
                        value: "SRW",
                        negate: false,
                    },
                    &Cond::MemberStrEq {
                        member: "Model",
                        value: "EK-GN120",
                        negate: true,
                    },
                ),
                IfdTag {
                    id: 0x0035,
                    name: "PreviewIFD",
                    format: None,
                    count: None,
                    writable: None,
                    groups: TagGroups {
                        g0: None,
                        g1: Some("PreviewIFD"),
                        g2: None,
                    },
                    flags: IfdFlags::NONE,
                    condition: None,
                    omitted: Omitted {
                        value_conv: false,
                        raw_conv: false,
                        condition: false,
                        hook: false,
                        subdirectory: true,
                        print_conv: false,
                    },
                    raw_conv: None,
                    value_conv: None,
                    print_conv: PrintConv::None,
                    subdir: Some(IfdSubdirEdge {
                        module: "Nikon",
                        table: "PreviewIFD",
                        start: IfdStart::Val(0),
                        base: None,
                        byte_order: IfdByteOrder::Unknown,
                        fix_format: None,
                        sub_ifd: true,
                        max_subdirs: None,
                        dir_name: None,
                        validate: false,
                        validation: None,
                        processor: IfdSubdirProcessor::Native,
                        unwalked: None,
                    }),
                },
            ),
            (
                Cond::MemberStrEq {
                    member: "TIFF_TYPE",
                    value: "SRW",
                    negate: false,
                },
                IfdTag {
                    id: 0x0035,
                    name: "PreviewIFD",
                    format: None,
                    count: None,
                    writable: None,
                    groups: TagGroups {
                        g0: None,
                        g1: Some("PreviewIFD"),
                        g2: None,
                    },
                    flags: IfdFlags::NONE,
                    condition: None,
                    omitted: Omitted {
                        value_conv: false,
                        raw_conv: false,
                        condition: false,
                        hook: false,
                        subdirectory: true,
                        print_conv: false,
                    },
                    raw_conv: None,
                    value_conv: None,
                    print_conv: PrintConv::None,
                    subdir: Some(IfdSubdirEdge {
                        module: "Nikon",
                        table: "PreviewIFD",
                        start: IfdStart::Val(-36),
                        base: None,
                        byte_order: IfdByteOrder::Unknown,
                        fix_format: None,
                        sub_ifd: true,
                        max_subdirs: None,
                        dir_name: None,
                        validate: false,
                        validation: None,
                        processor: IfdSubdirProcessor::Native,
                        unwalked: None,
                    }),
                },
            ),
        ],
    }],
};

/// `Image::ExifTool::Samsung::smta` -- 0 tags,
/// 0 `_variants` groups (IFD-style: PROCESS_PROC absent).
/// Generated from ExifTool's in-memory tag table. Do not edit by hand.
pub static IFD_SAMSUNG_SMTA: IfdTable = IfdTable {
    module: "Samsung",
    table: "smta",
    group0: "MakerNotes",
    group1: "Samsung",
    group2: "Video",
    set_group1: None,
    priority: None,
    gate_a: GateA {
        blocked_by: &[("ifd_tag_id_unrepresentable", 2)],
    },
    tags: &[],
    variants: &[],
};

/// `Image::ExifTool::Samsung::svss` -- 0 tags,
/// 0 `_variants` groups (IFD-style: PROCESS_PROC absent).
/// Generated from ExifTool's in-memory tag table. Do not edit by hand.
pub static IFD_SAMSUNG_SVSS: IfdTable = IfdTable {
    module: "Samsung",
    table: "svss",
    group0: "MakerNotes",
    group1: "Samsung",
    group2: "Video",
    set_group1: None,
    priority: None,
    gate_a: GateA { blocked_by: &[] },
    tags: &[],
    variants: &[],
};
