//! ExifTool `Sanyo` IFD-style tables, generated from ExifTool
//! 13.59's own Perl hashes -- one file per module; `mod.rs` beside this
//! file is the hub that declares and re-exports it.
//!
//! DO NOT EDIT. Regenerate with `just regen-tables` (see `mod.rs`).

#![allow(clippy::unreadable_literal, clippy::too_many_lines, unused_parens)]

// Everything a table literal names -- the `ifd_schema` types, `ExprId`, the
// `cond`/`subdir`/`validation` imports -- is in scope in the hub, and a glob
// import of the parent module brings its private imports along (RFC 1560).
#[allow(unused_imports)]
use super::*;

/// `Image::ExifTool::Sanyo::Main` -- 26 tags,
/// 1 `_variants` groups (IFD-style: PROCESS_PROC absent).
/// Generated from ExifTool's in-memory tag table. Do not edit by hand.
pub static IFD_SANYO_MAIN: IfdTable = IfdTable {
    module: "Sanyo",
    table: "Main",
    group0: "MakerNotes",
    group1: "Sanyo",
    group2: "Camera",
    set_group1: None,
    priority: None,
    gate_a: GateA { blocked_by: &[] },
    tags: &[
        IfdTag {
            id: 0x00ff,
            name: "MakerNoteOffset",
            format: None,
            count: None,
            writable: Some("int32u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x0100,
            name: "SanyoThumbnail",
            format: None,
            count: None,
            writable: Some("undef"),
            groups: TagGroups {
                g0: None,
                g1: None,
                g2: Some("Preview"),
            },
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: true,
                condition: false,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x0200,
            name: "SpecialMode",
            format: None,
            count: Some(3),
            writable: Some("int32u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x0201,
            name: "SanyoQuality",
            format: None,
            count: None,
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::PartialEnumInt {
                exact: &[
                    (0, "Normal/Very Low"),
                    (1, "Normal/Low"),
                    (2, "Normal/Medium Low"),
                    (3, "Normal/Medium"),
                    (4, "Normal/Medium High"),
                    (5, "Normal/High"),
                    (6, "Normal/Very High"),
                    (7, "Normal/Super High"),
                    (256, "Fine/Very Low"),
                    (257, "Fine/Low"),
                    (258, "Fine/Medium Low"),
                    (259, "Fine/Medium"),
                    (260, "Fine/Medium High"),
                    (261, "Fine/High"),
                    (262, "Fine/Very High"),
                    (263, "Fine/Super High"),
                    (512, "Super Fine/Very Low"),
                    (513, "Super Fine/Low"),
                    (514, "Super Fine/Medium Low"),
                    (515, "Super Fine/Medium"),
                    (516, "Super Fine/Medium High"),
                    (517, "Super Fine/High"),
                    (518, "Super Fine/Very High"),
                    (519, "Super Fine/Super High"),
                ],
                other: None,
                print_hex: true,
            },
            subdir: None,
        },
        IfdTag {
            id: 0x0202,
            name: "Macro",
            format: None,
            count: None,
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[
                (0, "Normal"),
                (1, "Macro"),
                (2, "View"),
                (3, "Manual"),
            ]),
            subdir: None,
        },
        IfdTag {
            id: 0x0204,
            name: "DigitalZoom",
            format: None,
            count: None,
            writable: Some("rational64u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x0207,
            name: "SoftwareVersion",
            format: None,
            count: None,
            writable: None,
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x0208,
            name: "PictInfo",
            format: None,
            count: None,
            writable: None,
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x0209,
            name: "CameraID",
            format: None,
            count: None,
            writable: None,
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x020e,
            name: "SequentialShot",
            format: None,
            count: None,
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[
                (0, "None"),
                (1, "Standard"),
                (2, "Best"),
                (3, "Adjust Exposure"),
            ]),
            subdir: None,
        },
        IfdTag {
            id: 0x020f,
            name: "WideRange",
            format: None,
            count: None,
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[(0, "Off"), (1, "On")]),
            subdir: None,
        },
        IfdTag {
            id: 0x0210,
            name: "ColorAdjustmentMode",
            format: None,
            count: None,
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[(0, "Off"), (1, "On")]),
            subdir: None,
        },
        IfdTag {
            id: 0x0213,
            name: "QuickShot",
            format: None,
            count: None,
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[(0, "Off"), (1, "On")]),
            subdir: None,
        },
        IfdTag {
            id: 0x0214,
            name: "SelfTimer",
            format: None,
            count: None,
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[(0, "Off"), (1, "On")]),
            subdir: None,
        },
        IfdTag {
            id: 0x0216,
            name: "VoiceMemo",
            format: None,
            count: None,
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[(0, "Off"), (1, "On")]),
            subdir: None,
        },
        IfdTag {
            id: 0x0217,
            name: "RecordShutterRelease",
            format: None,
            count: None,
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[
                (0, "Record while down"),
                (1, "Press start, press stop"),
            ]),
            subdir: None,
        },
        IfdTag {
            id: 0x0218,
            name: "FlickerReduce",
            format: None,
            count: None,
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[(0, "Off"), (1, "On")]),
            subdir: None,
        },
        IfdTag {
            id: 0x0219,
            name: "OpticalZoomOn",
            format: None,
            count: None,
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[(0, "Off"), (1, "On")]),
            subdir: None,
        },
        IfdTag {
            id: 0x021b,
            name: "DigitalZoomOn",
            format: None,
            count: None,
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[(0, "Off"), (1, "On")]),
            subdir: None,
        },
        IfdTag {
            id: 0x021d,
            name: "LightSourceSpecial",
            format: None,
            count: None,
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[(0, "Off"), (1, "On")]),
            subdir: None,
        },
        IfdTag {
            id: 0x021e,
            name: "Resaved",
            format: None,
            count: None,
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[(0, "No"), (1, "Yes")]),
            subdir: None,
        },
        IfdTag {
            id: 0x021f,
            name: "SceneSelect",
            format: None,
            count: None,
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[
                (0, "Off"),
                (1, "Sport"),
                (2, "TV"),
                (3, "Night"),
                (4, "User 1"),
                (5, "User 2"),
                (6, "Lamp"),
            ]),
            subdir: None,
        },
        IfdTag {
            id: 0x0224,
            name: "SequenceShotInterval",
            format: None,
            count: None,
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[
                (0, "5 frames/s"),
                (1, "10 frames/s"),
                (2, "15 frames/s"),
                (3, "20 frames/s"),
            ]),
            subdir: None,
        },
        IfdTag {
            id: 0x0225,
            name: "FlashMode",
            format: None,
            count: None,
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[
                (0, "Auto"),
                (1, "Force"),
                (2, "Disabled"),
                (3, "Red eye"),
            ]),
            subdir: None,
        },
        IfdTag {
            id: 0x0e00,
            name: "PrintIM",
            format: None,
            count: None,
            writable: None,
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: false,
                condition: false,
                hook: false,
                subdirectory: true,
                print_conv: false,
            },
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: Some(IfdSubdirEdge {
                module: "PrintIM",
                table: "Main",
                start: IfdStart::ValuePtr(0),
                base: None,
                byte_order: IfdByteOrder::Inherit,
                fix_format: None,
                sub_ifd: false,
                max_subdirs: None,
                dir_name: None,
                validate: false,
                validation: None,
                processor: IfdSubdirProcessor::Native,
                unwalked: None,
            }),
        },
        IfdTag {
            id: 0x0f00,
            name: "DataDump",
            format: None,
            count: None,
            writable: None,
            groups: TagGroups::NONE,
            flags: IfdFlags {
                unknown: false,
                binary: true,
                list: false,
                protected: false,
                avoid: false,
                priority: None,
            },
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
    ],
    variants: &[IfdVariantGroup {
        id: 0x0223,
        alternatives: &[
            (
                Cond::FormatEq {
                    value: "rational64u",
                    negate: false,
                },
                IfdTag {
                    id: 0x0223,
                    name: "ManualFocusDistance",
                    format: None,
                    count: None,
                    writable: Some("rational64u"),
                    groups: TagGroups::NONE,
                    flags: IfdFlags::NONE,
                    condition: None,
                    omitted: Omitted::NONE,
                    raw_conv: None,
                    value_conv: None,
                    print_conv: PrintConv::None,
                    subdir: None,
                },
            ),
            (
                Cond::Always,
                IfdTag {
                    id: 0x0223,
                    name: "FaceInfo",
                    format: None,
                    count: None,
                    writable: None,
                    groups: TagGroups::NONE,
                    flags: IfdFlags::NONE,
                    condition: None,
                    omitted: Omitted {
                        value_conv: false,
                        raw_conv: false,
                        condition: false,
                        hook: false,
                        subdirectory: true,
                        print_conv: false,
                    },
                    raw_conv: None,
                    value_conv: None,
                    print_conv: PrintConv::None,
                    subdir: Some(IfdSubdirEdge {
                        module: "Sanyo",
                        table: "FaceInfo",
                        start: IfdStart::ValuePtr(0),
                        base: None,
                        byte_order: IfdByteOrder::Inherit,
                        fix_format: None,
                        sub_ifd: false,
                        max_subdirs: None,
                        dir_name: None,
                        validate: false,
                        validation: None,
                        processor: IfdSubdirProcessor::Native,
                        unwalked: None,
                    }),
                },
            ),
        ],
    }],
};
