//! ExifTool `Sigma` IFD-style tables, generated from ExifTool
//! 13.59's own Perl hashes -- one file per module; `mod.rs` beside this
//! file is the hub that declares and re-exports it.
//!
//! DO NOT EDIT. Regenerate with `just regen-tables` (see `mod.rs`).

#![allow(clippy::unreadable_literal, clippy::too_many_lines, unused_parens)]

// Everything a table literal names -- the `ifd_schema` types, `ExprId`, the
// `cond`/`subdir`/`validation` imports -- is in scope in the hub, and a glob
// import of the parent module brings its private imports along (RFC 1560).
#[allow(unused_imports)]
use super::*;

/// `Image::ExifTool::Sigma::Main` -- 53 tags,
/// 11 `_variants` groups (IFD-style: PROCESS_PROC absent).
/// Generated from ExifTool's in-memory tag table. Do not edit by hand.
pub static IFD_SIGMA_MAIN: IfdTable = IfdTable {
    module: "Sigma",
    table: "Main",
    group0: "MakerNotes",
    group1: "Sigma",
    group2: "Camera",
    set_group1: None,
    priority: None,
    gate_a: GateA {
        blocked_by: &[
            ("tag_variant_cond_unsupported", 1),
            ("tag_variant_field_unsupported", 4),
            ("tag_variant_skipped", 5),
        ],
    },
    tags: &[
        IfdTag {
            id: 0x0002,
            name: "SerialNumber",
            format: None,
            count: None,
            writable: None,
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x0003,
            name: "DriveMode",
            format: None,
            count: None,
            writable: None,
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x0004,
            name: "ResolutionMode",
            format: None,
            count: None,
            writable: None,
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x0005,
            name: "AFMode",
            format: None,
            count: None,
            writable: None,
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x0006,
            name: "FocusSetting",
            format: None,
            count: None,
            writable: None,
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x0007,
            name: "WhiteBalance",
            format: None,
            count: None,
            writable: None,
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x0008,
            name: "ExposureMode",
            format: None,
            count: None,
            writable: None,
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::StrEnum(&[
                ("A", "Aperture-priority AE"),
                ("M", "Manual"),
                ("P", "Program AE"),
                ("S", "Shutter speed priority AE"),
            ]),
            subdir: None,
        },
        IfdTag {
            id: 0x0009,
            name: "MeteringMode",
            format: None,
            count: None,
            writable: None,
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::StrEnum(&[
                ("8", "Multi-segment"),
                ("A", "Average"),
                ("C", "Center-weighted average"),
            ]),
            subdir: None,
        },
        IfdTag {
            id: 0x000a,
            name: "LensFocalRange",
            format: None,
            count: None,
            writable: None,
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x000b,
            name: "ColorSpace",
            format: None,
            count: None,
            writable: None,
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x0015,
            name: "AdjustmentMode",
            format: None,
            count: None,
            writable: None,
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x0016,
            name: "Quality",
            format: None,
            count: None,
            writable: None,
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted {
                value_conv: true,
                raw_conv: false,
                condition: false,
                hook: false,
                subdirectory: false,
                print_conv: false,
            },
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x0017,
            name: "Firmware",
            format: None,
            count: None,
            writable: None,
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x0018,
            name: "Software",
            format: None,
            count: None,
            writable: None,
            groups: TagGroups::NONE,
            flags: IfdFlags {
                unknown: false,
                binary: false,
                list: false,
                protected: false,
                avoid: false,
                priority: Some(0),
            },
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x0019,
            name: "AutoBracket",
            format: None,
            count: None,
            writable: None,
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: false,
                condition: false,
                hook: false,
                subdirectory: false,
                print_conv: true,
            },
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x001e,
            name: "PreviewImageSize",
            format: None,
            count: Some(2),
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: Some(Cond::MemberCmp {
                member: "MakerNoteSigmaVer",
                op: CmpOp::Ge,
                value: 3,
            }),
            omitted: Omitted {
                value_conv: false,
                raw_conv: false,
                condition: false,
                hook: false,
                subdirectory: false,
                print_conv: true,
            },
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x0022,
            name: "FileFormat",
            format: None,
            count: None,
            writable: None,
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: Some(Cond::MemberCmp {
                member: "MakerNoteSigmaVer",
                op: CmpOp::Lt,
                value: 3,
            }),
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x0024,
            name: "Calibration",
            format: None,
            count: None,
            writable: None,
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: Some(Cond::MemberCmp {
                member: "MakerNoteSigmaVer",
                op: CmpOp::Lt,
                value: 3,
            }),
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x0026,
            name: "FileFormat",
            format: None,
            count: None,
            writable: None,
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: Some(Cond::MemberCmp {
                member: "MakerNoteSigmaVer",
                op: CmpOp::Ge,
                value: 3,
            }),
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x002a,
            name: "LensFocalRange",
            format: None,
            count: Some(2),
            writable: Some("rational64u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: Some(Cond::MemberCmp {
                member: "MakerNoteSigmaVer",
                op: CmpOp::Ge,
                value: 3,
            }),
            omitted: Omitted {
                value_conv: false,
                raw_conv: false,
                condition: false,
                hook: false,
                subdirectory: false,
                print_conv: true,
            },
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x002b,
            name: "LensMaxApertureRange",
            format: None,
            count: Some(2),
            writable: Some("rational64u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: Some(Cond::MemberCmp {
                member: "MakerNoteSigmaVer",
                op: CmpOp::Ge,
                value: 3,
            }),
            omitted: Omitted {
                value_conv: false,
                raw_conv: false,
                condition: false,
                hook: false,
                subdirectory: false,
                print_conv: true,
            },
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x002c,
            name: "ColorMode",
            format: None,
            count: None,
            writable: Some("int32u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: Some(Cond::FormatEq {
                value: "int32u",
                negate: false,
            }),
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[
                (0, "n/a"),
                (1, "Sepia"),
                (2, "B&W"),
                (3, "Standard"),
                (4, "Vivid"),
                (5, "Neutral"),
                (6, "Portrait"),
                (7, "Landscape"),
                (8, "FOV Classic Blue"),
            ]),
            subdir: None,
        },
        IfdTag {
            id: 0x0031,
            name: "FNumber",
            format: None,
            count: None,
            writable: Some("rational64u"),
            groups: TagGroups::NONE,
            flags: IfdFlags {
                unknown: false,
                binary: false,
                list: false,
                protected: false,
                avoid: false,
                priority: Some(0),
            },
            condition: Some(Cond::MemberCmp {
                member: "MakerNoteSigmaVer",
                op: CmpOp::Lt,
                value: 3,
            }),
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::Expr(ExprId::Sprintf1fVal2C65CD),
            subdir: None,
        },
        IfdTag {
            id: 0x0032,
            name: "ExposureTime",
            format: None,
            count: None,
            writable: Some("rational64u"),
            groups: TagGroups::NONE,
            flags: IfdFlags {
                unknown: false,
                binary: false,
                list: false,
                protected: false,
                avoid: false,
                priority: Some(0),
            },
            condition: Some(Cond::MemberCmp {
                member: "MakerNoteSigmaVer",
                op: CmpOp::Lt,
                value: 3,
            }),
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::Expr(ExprId::ImageExifToolExifPrintExposureTimeVal6037F3),
            subdir: None,
        },
        IfdTag {
            id: 0x0033,
            name: "ExposureTime2",
            format: None,
            count: None,
            writable: None,
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: Some(Cond::And(
                &Cond::MemberRegex {
                    member: "Model",
                    pattern: " (SD1|SD9|SD15|Merrill|Quattro|fp)$",
                    ignore_case: false,
                    negate: true,
                },
                &Cond::MemberCmp {
                    member: "MakerNoteSigmaVer",
                    op: CmpOp::Lt,
                    value: 4,
                },
            )),
            omitted: Omitted {
                value_conv: true,
                raw_conv: false,
                condition: false,
                hook: false,
                subdirectory: false,
                print_conv: true,
            },
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x0034,
            name: "BurstShot",
            format: None,
            count: None,
            writable: Some("int32u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: Some(Cond::MemberCmp {
                member: "MakerNoteSigmaVer",
                op: CmpOp::Lt,
                value: 3,
            }),
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x0035,
            name: "ExposureCompensation",
            format: None,
            count: None,
            writable: Some("rational64s"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: Some(Cond::MemberCmp {
                member: "MakerNoteSigmaVer",
                op: CmpOp::Lt,
                value: 3,
            }),
            omitted: Omitted {
                value_conv: false,
                raw_conv: false,
                condition: false,
                hook: false,
                subdirectory: false,
                print_conv: true,
            },
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x0039,
            name: "SensorTemperature",
            format: None,
            count: None,
            writable: None,
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: Some(Cond::MemberCmp {
                member: "MakerNoteSigmaVer",
                op: CmpOp::Lt,
                value: 3,
            }),
            omitted: Omitted {
                value_conv: false,
                raw_conv: false,
                condition: false,
                hook: false,
                subdirectory: false,
                print_conv: true,
            },
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x003a,
            name: "FlashExposureComp",
            format: None,
            count: None,
            writable: Some("rational64s"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: Some(Cond::MemberCmp {
                member: "MakerNoteSigmaVer",
                op: CmpOp::Lt,
                value: 3,
            }),
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x003b,
            name: "Firmware",
            format: None,
            count: None,
            writable: None,
            groups: TagGroups::NONE,
            flags: IfdFlags {
                unknown: false,
                binary: false,
                list: false,
                protected: false,
                avoid: false,
                priority: Some(0),
            },
            condition: Some(Cond::MemberCmp {
                member: "MakerNoteSigmaVer",
                op: CmpOp::Lt,
                value: 3,
            }),
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x003c,
            name: "WhiteBalance",
            format: None,
            count: None,
            writable: None,
            groups: TagGroups::NONE,
            flags: IfdFlags {
                unknown: false,
                binary: false,
                list: false,
                protected: false,
                avoid: false,
                priority: Some(0),
            },
            condition: Some(Cond::MemberCmp {
                member: "MakerNoteSigmaVer",
                op: CmpOp::Lt,
                value: 3,
            }),
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x003d,
            name: "PictureMode",
            format: None,
            count: None,
            writable: None,
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x0047,
            name: "ExposureCompensation",
            format: None,
            count: None,
            writable: Some("rational64s"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: false,
                condition: false,
                hook: false,
                subdirectory: false,
                print_conv: true,
            },
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x0048,
            name: "LensApertureRange",
            format: None,
            count: None,
            writable: None,
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: Some(Cond::MemberCmp {
                member: "MakerNoteSigmaVer",
                op: CmpOp::Ge,
                value: 3,
            }),
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x0049,
            name: "FNumber",
            format: None,
            count: None,
            writable: Some("rational64u"),
            groups: TagGroups::NONE,
            flags: IfdFlags {
                unknown: false,
                binary: false,
                list: false,
                protected: false,
                avoid: false,
                priority: Some(0),
            },
            condition: Some(Cond::MemberCmp {
                member: "MakerNoteSigmaVer",
                op: CmpOp::Ge,
                value: 3,
            }),
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::Expr(ExprId::Sprintf1fVal2C65CD),
            subdir: None,
        },
        IfdTag {
            id: 0x004a,
            name: "ExposureTime",
            format: None,
            count: None,
            writable: Some("rational64u"),
            groups: TagGroups::NONE,
            flags: IfdFlags {
                unknown: false,
                binary: false,
                list: false,
                protected: false,
                avoid: false,
                priority: Some(0),
            },
            condition: Some(Cond::MemberCmp {
                member: "MakerNoteSigmaVer",
                op: CmpOp::Ge,
                value: 3,
            }),
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::Expr(ExprId::ImageExifToolExifPrintExposureTimeVal6037F3),
            subdir: None,
        },
        IfdTag {
            id: 0x004d,
            name: "ExposureCompensation",
            format: None,
            count: None,
            writable: Some("rational64s"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: Some(Cond::MemberCmp {
                member: "MakerNoteSigmaVer",
                op: CmpOp::Ge,
                value: 3,
            }),
            omitted: Omitted {
                value_conv: false,
                raw_conv: false,
                condition: false,
                hook: false,
                subdirectory: false,
                print_conv: true,
            },
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x0055,
            name: "SensorTemperature",
            format: None,
            count: None,
            writable: None,
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: Some(Cond::MemberCmp {
                member: "MakerNoteSigmaVer",
                op: CmpOp::Ge,
                value: 3,
            }),
            omitted: Omitted {
                value_conv: false,
                raw_conv: false,
                condition: false,
                hook: false,
                subdirectory: false,
                print_conv: true,
            },
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x0056,
            name: "FlashExposureComp",
            format: None,
            count: None,
            writable: Some("rational64s"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: Some(Cond::MemberCmp {
                member: "MakerNoteSigmaVer",
                op: CmpOp::Ge,
                value: 3,
            }),
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x0057,
            name: "Firmware2",
            format: None,
            count: None,
            writable: None,
            groups: TagGroups::NONE,
            flags: IfdFlags {
                unknown: false,
                binary: false,
                list: false,
                protected: false,
                avoid: false,
                priority: Some(0),
            },
            condition: Some(Cond::FormatEq {
                value: "string",
                negate: false,
            }),
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x0058,
            name: "WhiteBalance",
            format: None,
            count: None,
            writable: None,
            groups: TagGroups::NONE,
            flags: IfdFlags {
                unknown: false,
                binary: false,
                list: false,
                protected: false,
                avoid: false,
                priority: Some(0),
            },
            condition: Some(Cond::MemberCmp {
                member: "MakerNoteSigmaVer",
                op: CmpOp::Ge,
                value: 3,
            }),
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x0059,
            name: "DigitalFilter",
            format: None,
            count: None,
            writable: None,
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: Some(Cond::MemberCmp {
                member: "MakerNoteSigmaVer",
                op: CmpOp::Ge,
                value: 3,
            }),
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x0084,
            name: "Model",
            format: None,
            count: None,
            writable: None,
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x0086,
            name: "ISO",
            format: None,
            count: None,
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x0087,
            name: "ResolutionMode",
            format: None,
            count: None,
            writable: None,
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x0088,
            name: "WhiteBalance",
            format: None,
            count: None,
            writable: None,
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x008c,
            name: "Firmware",
            format: None,
            count: None,
            writable: None,
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x0113,
            name: "PictureModeStrength",
            format: None,
            count: None,
            writable: Some("int32s"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x011f,
            name: "CameraCalibration",
            format: None,
            count: Some(9),
            writable: Some("float"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x0120,
            name: "WBSettings",
            format: None,
            count: None,
            writable: None,
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: false,
                condition: false,
                hook: false,
                subdirectory: true,
                print_conv: false,
            },
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: Some(IfdSubdirEdge {
                module: "Sigma",
                table: "WBSettings",
                start: IfdStart::ValuePtr(0),
                base: None,
                byte_order: IfdByteOrder::Inherit,
                fix_format: None,
                sub_ifd: false,
                max_subdirs: None,
                dir_name: None,
                validate: false,
                validation: None,
                processor: IfdSubdirProcessor::Native,
                unwalked: None,
            }),
        },
        IfdTag {
            id: 0x0121,
            name: "WBSettings2",
            format: None,
            count: None,
            writable: None,
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: false,
                condition: false,
                hook: false,
                subdirectory: true,
                print_conv: false,
            },
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: Some(IfdSubdirEdge {
                module: "Sigma",
                table: "WBSettings2",
                start: IfdStart::ValuePtr(0),
                base: None,
                byte_order: IfdByteOrder::Inherit,
                fix_format: None,
                sub_ifd: false,
                max_subdirs: None,
                dir_name: None,
                validate: false,
                validation: None,
                processor: IfdSubdirProcessor::Native,
                unwalked: None,
            }),
        },
        IfdTag {
            id: 0x0138,
            name: "Fade",
            format: None,
            count: None,
            writable: Some("rational64u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x0139,
            name: "Vignette",
            format: None,
            count: None,
            writable: Some("rational64u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
    ],
    variants: &[
        IfdVariantGroup {
            id: 0x000c,
            alternatives: &[
                (
                    Cond::FormatEq {
                        value: "string",
                        negate: false,
                    },
                    IfdTag {
                        id: 0x000c,
                        name: "ExposureCompensation",
                        format: None,
                        count: None,
                        writable: None,
                        groups: TagGroups::NONE,
                        flags: IfdFlags::NONE,
                        condition: None,
                        omitted: Omitted {
                            value_conv: true,
                            raw_conv: false,
                            condition: false,
                            hook: false,
                            subdirectory: false,
                            print_conv: false,
                        },
                        raw_conv: None,
                        value_conv: None,
                        print_conv: PrintConv::None,
                        subdir: None,
                    },
                ),
                (
                    Cond::Always,
                    IfdTag {
                        id: 0x000c,
                        name: "ExposureAdjust",
                        format: None,
                        count: None,
                        writable: Some("rational64s"),
                        groups: TagGroups::NONE,
                        flags: IfdFlags {
                            unknown: true,
                            binary: false,
                            list: false,
                            protected: false,
                            avoid: false,
                            priority: None,
                        },
                        condition: None,
                        omitted: Omitted::NONE,
                        raw_conv: None,
                        value_conv: None,
                        print_conv: PrintConv::None,
                        subdir: None,
                    },
                ),
            ],
        },
        IfdVariantGroup {
            id: 0x000d,
            alternatives: &[
                (
                    Cond::FormatEq {
                        value: "string",
                        negate: false,
                    },
                    IfdTag {
                        id: 0x000d,
                        name: "Contrast",
                        format: None,
                        count: None,
                        writable: None,
                        groups: TagGroups::NONE,
                        flags: IfdFlags::NONE,
                        condition: None,
                        omitted: Omitted {
                            value_conv: true,
                            raw_conv: false,
                            condition: false,
                            hook: false,
                            subdirectory: false,
                            print_conv: false,
                        },
                        raw_conv: None,
                        value_conv: None,
                        print_conv: PrintConv::None,
                        subdir: None,
                    },
                ),
                (
                    Cond::Always,
                    IfdTag {
                        id: 0x000d,
                        name: "Contrast",
                        format: None,
                        count: None,
                        writable: Some("rational64s"),
                        groups: TagGroups::NONE,
                        flags: IfdFlags {
                            unknown: false,
                            binary: false,
                            list: false,
                            protected: false,
                            avoid: false,
                            priority: Some(0),
                        },
                        condition: None,
                        omitted: Omitted::NONE,
                        raw_conv: None,
                        value_conv: None,
                        print_conv: PrintConv::None,
                        subdir: None,
                    },
                ),
            ],
        },
        IfdVariantGroup {
            id: 0x000e,
            alternatives: &[
                (
                    Cond::FormatEq {
                        value: "string",
                        negate: false,
                    },
                    IfdTag {
                        id: 0x000e,
                        name: "Shadow",
                        format: None,
                        count: None,
                        writable: None,
                        groups: TagGroups::NONE,
                        flags: IfdFlags::NONE,
                        condition: None,
                        omitted: Omitted {
                            value_conv: true,
                            raw_conv: false,
                            condition: false,
                            hook: false,
                            subdirectory: false,
                            print_conv: false,
                        },
                        raw_conv: None,
                        value_conv: None,
                        print_conv: PrintConv::None,
                        subdir: None,
                    },
                ),
                (
                    Cond::Always,
                    IfdTag {
                        id: 0x000e,
                        name: "Shadow",
                        format: None,
                        count: None,
                        writable: Some("rational64s"),
                        groups: TagGroups::NONE,
                        flags: IfdFlags {
                            unknown: false,
                            binary: false,
                            list: false,
                            protected: false,
                            avoid: false,
                            priority: Some(0),
                        },
                        condition: None,
                        omitted: Omitted::NONE,
                        raw_conv: None,
                        value_conv: None,
                        print_conv: PrintConv::None,
                        subdir: None,
                    },
                ),
            ],
        },
        IfdVariantGroup {
            id: 0x000f,
            alternatives: &[
                (
                    Cond::FormatEq {
                        value: "string",
                        negate: false,
                    },
                    IfdTag {
                        id: 0x000f,
                        name: "Highlight",
                        format: None,
                        count: None,
                        writable: None,
                        groups: TagGroups::NONE,
                        flags: IfdFlags::NONE,
                        condition: None,
                        omitted: Omitted {
                            value_conv: true,
                            raw_conv: false,
                            condition: false,
                            hook: false,
                            subdirectory: false,
                            print_conv: false,
                        },
                        raw_conv: None,
                        value_conv: None,
                        print_conv: PrintConv::None,
                        subdir: None,
                    },
                ),
                (
                    Cond::Always,
                    IfdTag {
                        id: 0x000f,
                        name: "Highlight",
                        format: None,
                        count: None,
                        writable: Some("rational64s"),
                        groups: TagGroups::NONE,
                        flags: IfdFlags {
                            unknown: false,
                            binary: false,
                            list: false,
                            protected: false,
                            avoid: false,
                            priority: Some(0),
                        },
                        condition: None,
                        omitted: Omitted::NONE,
                        raw_conv: None,
                        value_conv: None,
                        print_conv: PrintConv::None,
                        subdir: None,
                    },
                ),
            ],
        },
        IfdVariantGroup {
            id: 0x0010,
            alternatives: &[
                (
                    Cond::FormatEq {
                        value: "string",
                        negate: false,
                    },
                    IfdTag {
                        id: 0x0010,
                        name: "Saturation",
                        format: None,
                        count: None,
                        writable: None,
                        groups: TagGroups::NONE,
                        flags: IfdFlags::NONE,
                        condition: None,
                        omitted: Omitted {
                            value_conv: true,
                            raw_conv: false,
                            condition: false,
                            hook: false,
                            subdirectory: false,
                            print_conv: false,
                        },
                        raw_conv: None,
                        value_conv: None,
                        print_conv: PrintConv::None,
                        subdir: None,
                    },
                ),
                (
                    Cond::Always,
                    IfdTag {
                        id: 0x0010,
                        name: "Saturation",
                        format: None,
                        count: None,
                        writable: Some("rational64s"),
                        groups: TagGroups::NONE,
                        flags: IfdFlags {
                            unknown: false,
                            binary: false,
                            list: false,
                            protected: false,
                            avoid: false,
                            priority: Some(0),
                        },
                        condition: None,
                        omitted: Omitted::NONE,
                        raw_conv: None,
                        value_conv: None,
                        print_conv: PrintConv::None,
                        subdir: None,
                    },
                ),
            ],
        },
        IfdVariantGroup {
            id: 0x0011,
            alternatives: &[
                (
                    Cond::FormatEq {
                        value: "string",
                        negate: false,
                    },
                    IfdTag {
                        id: 0x0011,
                        name: "Sharpness",
                        format: None,
                        count: None,
                        writable: None,
                        groups: TagGroups::NONE,
                        flags: IfdFlags::NONE,
                        condition: None,
                        omitted: Omitted {
                            value_conv: true,
                            raw_conv: false,
                            condition: false,
                            hook: false,
                            subdirectory: false,
                            print_conv: false,
                        },
                        raw_conv: None,
                        value_conv: None,
                        print_conv: PrintConv::None,
                        subdir: None,
                    },
                ),
                (
                    Cond::Always,
                    IfdTag {
                        id: 0x0011,
                        name: "Sharpness",
                        format: None,
                        count: None,
                        writable: Some("rational64s"),
                        groups: TagGroups::NONE,
                        flags: IfdFlags {
                            unknown: false,
                            binary: false,
                            list: false,
                            protected: false,
                            avoid: false,
                            priority: Some(0),
                        },
                        condition: None,
                        omitted: Omitted::NONE,
                        raw_conv: None,
                        value_conv: None,
                        print_conv: PrintConv::None,
                        subdir: None,
                    },
                ),
            ],
        },
        IfdVariantGroup {
            id: 0x0012,
            alternatives: &[
                (
                    Cond::FormatEq {
                        value: "string",
                        negate: false,
                    },
                    IfdTag {
                        id: 0x0012,
                        name: "X3FillLight",
                        format: None,
                        count: None,
                        writable: None,
                        groups: TagGroups::NONE,
                        flags: IfdFlags::NONE,
                        condition: None,
                        omitted: Omitted {
                            value_conv: true,
                            raw_conv: false,
                            condition: false,
                            hook: false,
                            subdirectory: false,
                            print_conv: false,
                        },
                        raw_conv: None,
                        value_conv: None,
                        print_conv: PrintConv::None,
                        subdir: None,
                    },
                ),
                (
                    Cond::Always,
                    IfdTag {
                        id: 0x0012,
                        name: "X3FillLight",
                        format: None,
                        count: None,
                        writable: Some("rational64s"),
                        groups: TagGroups::NONE,
                        flags: IfdFlags::NONE,
                        condition: None,
                        omitted: Omitted::NONE,
                        raw_conv: None,
                        value_conv: None,
                        print_conv: PrintConv::None,
                        subdir: None,
                    },
                ),
            ],
        },
        IfdVariantGroup {
            id: 0x0014,
            alternatives: &[
                (
                    Cond::FormatEq {
                        value: "string",
                        negate: false,
                    },
                    IfdTag {
                        id: 0x0014,
                        name: "ColorAdjustment",
                        format: None,
                        count: None,
                        writable: None,
                        groups: TagGroups::NONE,
                        flags: IfdFlags::NONE,
                        condition: None,
                        omitted: Omitted {
                            value_conv: true,
                            raw_conv: false,
                            condition: false,
                            hook: false,
                            subdirectory: false,
                            print_conv: false,
                        },
                        raw_conv: None,
                        value_conv: None,
                        print_conv: PrintConv::None,
                        subdir: None,
                    },
                ),
                (
                    Cond::Always,
                    IfdTag {
                        id: 0x0014,
                        name: "ColorAdjustment",
                        format: None,
                        count: Some(3),
                        writable: Some("rational64s"),
                        groups: TagGroups::NONE,
                        flags: IfdFlags::NONE,
                        condition: None,
                        omitted: Omitted::NONE,
                        raw_conv: None,
                        value_conv: None,
                        print_conv: PrintConv::None,
                        subdir: None,
                    },
                ),
            ],
        },
        IfdVariantGroup {
            id: 0x001f,
            alternatives: &[
                (
                    Cond::MemberCmp {
                        member: "MakerNoteSigmaVer",
                        op: CmpOp::Lt,
                        value: 3,
                    },
                    IfdTag {
                        id: 0x001f,
                        name: "AFPoint",
                        format: None,
                        count: None,
                        writable: None,
                        groups: TagGroups::NONE,
                        flags: IfdFlags::NONE,
                        condition: None,
                        omitted: Omitted::NONE,
                        raw_conv: None,
                        value_conv: None,
                        print_conv: PrintConv::None,
                        subdir: None,
                    },
                ),
                (
                    Cond::Always,
                    IfdTag {
                        id: 0x001f,
                        name: "MakerNoteVersion",
                        format: None,
                        count: None,
                        writable: Some("undef"),
                        groups: TagGroups::NONE,
                        flags: IfdFlags::NONE,
                        condition: None,
                        omitted: Omitted::NONE,
                        raw_conv: None,
                        value_conv: None,
                        print_conv: PrintConv::None,
                        subdir: None,
                    },
                ),
            ],
        },
        IfdVariantGroup {
            id: 0x0027,
            alternatives: &[
                (
                    Cond::And(
                        &Cond::MemberCmp {
                            member: "MakerNoteSigmaVer",
                            op: CmpOp::Ge,
                            value: 3,
                        },
                        &Cond::FormatEq {
                            value: "string",
                            negate: false,
                        },
                    ),
                    IfdTag {
                        id: 0x0027,
                        name: "LensType",
                        format: None,
                        count: None,
                        writable: None,
                        groups: TagGroups::NONE,
                        flags: IfdFlags::NONE,
                        condition: None,
                        omitted: Omitted {
                            value_conv: true,
                            raw_conv: false,
                            condition: false,
                            hook: false,
                            subdirectory: false,
                            print_conv: true,
                        },
                        raw_conv: None,
                        value_conv: None,
                        print_conv: PrintConv::None,
                        subdir: None,
                    },
                ),
                (
                    Cond::MemberCmp {
                        member: "MakerNoteSigmaVer",
                        op: CmpOp::Ge,
                        value: 3,
                    },
                    IfdTag {
                        id: 0x0027,
                        name: "LensType",
                        format: None,
                        count: None,
                        writable: Some("int16u"),
                        groups: TagGroups::NONE,
                        flags: IfdFlags::NONE,
                        condition: None,
                        omitted: Omitted {
                            value_conv: false,
                            raw_conv: false,
                            condition: false,
                            hook: false,
                            subdirectory: false,
                            print_conv: true,
                        },
                        raw_conv: None,
                        value_conv: None,
                        print_conv: PrintConv::None,
                        subdir: None,
                    },
                ),
            ],
        },
        IfdVariantGroup {
            id: 0x0030,
            alternatives: &[
                (
                    Cond::MemberCmp {
                        member: "MakerNoteSigmaVer",
                        op: CmpOp::Lt,
                        value: 3,
                    },
                    IfdTag {
                        id: 0x0030,
                        name: "LensApertureRange",
                        format: None,
                        count: None,
                        writable: None,
                        groups: TagGroups::NONE,
                        flags: IfdFlags::NONE,
                        condition: None,
                        omitted: Omitted::NONE,
                        raw_conv: None,
                        value_conv: None,
                        print_conv: PrintConv::None,
                        subdir: None,
                    },
                ),
                (
                    Cond::Always,
                    IfdTag {
                        id: 0x0030,
                        name: "Calibration",
                        format: None,
                        count: None,
                        writable: None,
                        groups: TagGroups::NONE,
                        flags: IfdFlags::NONE,
                        condition: None,
                        omitted: Omitted::NONE,
                        raw_conv: None,
                        value_conv: None,
                        print_conv: PrintConv::None,
                        subdir: None,
                    },
                ),
            ],
        },
    ],
};
