//! ExifTool `SonyIDC` IFD-style tables, generated from ExifTool
//! 13.59's own Perl hashes -- one file per module; `mod.rs` beside this
//! file is the hub that declares and re-exports it.
//!
//! DO NOT EDIT. Regenerate with `just regen-tables` (see `mod.rs`).

#![allow(clippy::unreadable_literal, clippy::too_many_lines, unused_parens)]

// Everything a table literal names -- the `ifd_schema` types, `ExprId`, the
// `cond`/`subdir`/`validation` imports -- is in scope in the hub, and a glob
// import of the parent module brings its private imports along (RFC 1560).
#[allow(unused_imports)]
use super::*;

/// `Image::ExifTool::SonyIDC::Composite` -- 0 tags,
/// 0 `_variants` groups (IFD-style: PROCESS_PROC absent).
/// Generated from ExifTool's in-memory tag table. Do not edit by hand.
pub static IFD_SONYIDC_COMPOSITE: IfdTable = IfdTable {
    module: "SonyIDC",
    table: "Composite",
    group0: "Composite",
    group1: "Composite",
    group2: "Image",
    set_group1: None,
    priority: None,
    gate_a: GateA {
        blocked_by: &[("ifd_tag_id_unrepresentable", 1)],
    },
    tags: &[],
    variants: &[],
};

/// `Image::ExifTool::SonyIDC::Main` -- 52 tags,
/// 0 `_variants` groups (IFD-style: PROCESS_PROC absent).
/// `SET_GROUP1` declared (Exif.pm:7183: group 1 is the directory name the
/// walk was given, not a static string) -- see codegen.py `gen_ifd_table`.
/// Generated from ExifTool's in-memory tag table. Do not edit by hand.
pub static IFD_SONYIDC_MAIN: IfdTable = IfdTable {
    module: "SonyIDC",
    table: "Main",
    group0: "MakerNotes",
    group1: "SonyIDC",
    group2: "Image",
    set_group1: Some("1"),
    priority: None,
    gate_a: GateA {
        blocked_by: &[("ifd_subdir_refused_unmodeled_key", 1)],
    },
    tags: &[
        IfdTag {
            id: 0x8000,
            name: "IDCCreativeStyle",
            format: None,
            count: None,
            writable: Some("int32u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[
                (1, "Camera Setting"),
                (2, "Standard"),
                (3, "Real"),
                (4, "Vivid"),
                (5, "Adobe RGB"),
                (6, "A100 Standard"),
                (7, "Neutral"),
                (8, "Portrait"),
                (9, "Landscape"),
                (10, "Clear"),
                (11, "Deep"),
                (12, "Light"),
                (13, "Sunset"),
                (14, "Night View"),
                (15, "Autumn Leaves"),
                (16, "B&W"),
                (17, "Sepia"),
            ]),
            subdir: None,
        },
        IfdTag {
            id: 0x8001,
            name: "CreativeStyleWasChanged",
            format: None,
            count: None,
            writable: Some("int32u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[(0, "No"), (1, "Yes")]),
            subdir: None,
        },
        IfdTag {
            id: 0x8002,
            name: "PresetWhiteBalance",
            format: None,
            count: None,
            writable: Some("int32u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[
                (1, "Camera Setting"),
                (2, "Color Temperature"),
                (3, "Specify Gray Point"),
                (4, "Daylight"),
                (5, "Cloudy"),
                (6, "Shade"),
                (7, "Cool White Fluorescent"),
                (8, "Day Light Fluorescent"),
                (9, "Day White Fluorescent"),
                (10, "Warm White Fluorescent"),
                (11, "Tungsten"),
                (12, "Flash"),
                (13, "Auto"),
            ]),
            subdir: None,
        },
        IfdTag {
            id: 0x8013,
            name: "ColorTemperatureAdj",
            format: None,
            count: None,
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x8014,
            name: "PresetWhiteBalanceAdj",
            format: None,
            count: None,
            writable: Some("int32s"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x8015,
            name: "ColorCorrection",
            format: None,
            count: None,
            writable: Some("int32s"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x8016,
            name: "SaturationAdj",
            format: None,
            count: None,
            writable: Some("int32s"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x8017,
            name: "ContrastAdj",
            format: None,
            count: None,
            writable: Some("int32s"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x8018,
            name: "BrightnessAdj",
            format: None,
            count: None,
            writable: Some("int32s"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::Expr(ExprId::Sprintf2fVal3008AA7F7),
            subdir: None,
        },
        IfdTag {
            id: 0x8019,
            name: "HueAdj",
            format: None,
            count: None,
            writable: Some("int32s"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x801a,
            name: "SharpnessAdj",
            format: None,
            count: None,
            writable: Some("int32s"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x801b,
            name: "SharpnessOvershoot",
            format: None,
            count: None,
            writable: Some("int32s"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x801c,
            name: "SharpnessUndershoot",
            format: None,
            count: None,
            writable: Some("int32s"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x801d,
            name: "SharpnessThreshold",
            format: None,
            count: None,
            writable: Some("int32s"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x801e,
            name: "NoiseReductionMode",
            format: None,
            count: None,
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[(0, "Off"), (1, "On")]),
            subdir: None,
        },
        IfdTag {
            id: 0x8021,
            name: "GrayPoint",
            format: None,
            count: Some(4),
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x8022,
            name: "D-RangeOptimizerMode",
            format: None,
            count: None,
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[(0, "Off"), (1, "Auto"), (2, "Manual")]),
            subdir: None,
        },
        IfdTag {
            id: 0x8023,
            name: "D-RangeOptimizerValue",
            format: None,
            count: None,
            writable: Some("int32s"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x8024,
            name: "D-RangeOptimizerHighlight",
            format: None,
            count: None,
            writable: Some("int32s"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x8026,
            name: "HighlightColorDistortReduct",
            format: None,
            count: None,
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[(0, "Standard"), (1, "Advanced")]),
            subdir: None,
        },
        IfdTag {
            id: 0x8027,
            name: "NoiseReductionValue",
            format: None,
            count: None,
            writable: Some("int32s"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: Some(ExprId::Val10022E6025),
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x8028,
            name: "EdgeNoiseReduction",
            format: None,
            count: None,
            writable: Some("int32s"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: Some(ExprId::Val10022E6025),
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x8029,
            name: "ColorNoiseReduction",
            format: None,
            count: None,
            writable: Some("int32s"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: Some(ExprId::Val10022E6025),
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x802d,
            name: "D-RangeOptimizerShadow",
            format: None,
            count: None,
            writable: Some("int32s"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x8030,
            name: "PeripheralIllumCentralRadius",
            format: None,
            count: None,
            writable: Some("int32s"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x8031,
            name: "PeripheralIllumCentralValue",
            format: None,
            count: None,
            writable: Some("int32s"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x8032,
            name: "PeripheralIllumPeriphValue",
            format: None,
            count: None,
            writable: Some("int32s"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x8040,
            name: "DistortionCompensation",
            format: None,
            count: None,
            writable: Some("int32s"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[(-1, "n/a"), (1, "On"), (2, "Off")]),
            subdir: None,
        },
        IfdTag {
            id: 0x9000,
            name: "ToneCurveBrightnessX",
            format: None,
            count: None,
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x9001,
            name: "ToneCurveRedX",
            format: None,
            count: None,
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x9002,
            name: "ToneCurveGreenX",
            format: None,
            count: None,
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x9003,
            name: "ToneCurveBlueX",
            format: None,
            count: None,
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x9004,
            name: "ToneCurveBrightnessY",
            format: None,
            count: None,
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x9005,
            name: "ToneCurveRedY",
            format: None,
            count: None,
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x9006,
            name: "ToneCurveGreenY",
            format: None,
            count: None,
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x9007,
            name: "ToneCurveBlueY",
            format: None,
            count: None,
            writable: Some("int16u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x900d,
            name: "ChromaticAberrationCorrection",
            format: None,
            count: None,
            writable: Some("int32s"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[(1, "On"), (2, "Off")]),
            subdir: None,
        },
        IfdTag {
            id: 0x900e,
            name: "InclinationCorrection",
            format: None,
            count: None,
            writable: Some("int32u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[(0, "Off"), (1, "On")]),
            subdir: None,
        },
        IfdTag {
            id: 0x900f,
            name: "InclinationAngle",
            format: None,
            count: None,
            writable: Some("int32s"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::Expr(ExprId::Sprintf1fDegVal10005376E8),
            subdir: None,
        },
        IfdTag {
            id: 0x9010,
            name: "Cropping",
            format: None,
            count: None,
            writable: Some("int32u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[(0, "Off"), (1, "On")]),
            subdir: None,
        },
        IfdTag {
            id: 0x9011,
            name: "CropArea",
            format: None,
            count: Some(4),
            writable: Some("int32u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x9012,
            name: "PreviewImageSize",
            format: None,
            count: Some(2),
            writable: Some("int32u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x9013,
            name: "PxShiftPeriphEdgeNR",
            format: None,
            count: None,
            writable: Some("int32s"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::IntEnum(&[(0, "Off"), (1, "On")]),
            subdir: None,
        },
        IfdTag {
            id: 0x9014,
            name: "PxShiftPeriphEdgeNRValue",
            format: None,
            count: None,
            writable: Some("int32s"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::Expr(ExprId::Sprintf1fVal10E6E57B),
            subdir: None,
        },
        IfdTag {
            id: 0x9017,
            name: "WhitesAdj",
            format: None,
            count: None,
            writable: Some("int32s"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x9018,
            name: "BlacksAdj",
            format: None,
            count: None,
            writable: Some("int32s"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x9019,
            name: "HighlightsAdj",
            format: None,
            count: None,
            writable: Some("int32s"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0x901a,
            name: "ShadowsAdj",
            format: None,
            count: None,
            writable: Some("int32s"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0xd000,
            name: "CurrentVersion",
            format: None,
            count: None,
            writable: Some("int32u"),
            groups: TagGroups::NONE,
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0xd001,
            name: "VersionIFD",
            format: None,
            count: None,
            writable: None,
            groups: TagGroups {
                g0: None,
                g1: Some("Version0"),
                g2: None,
            },
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted {
                value_conv: false,
                raw_conv: false,
                condition: false,
                hook: false,
                subdirectory: true,
                print_conv: false,
            },
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::None,
            subdir: None,
        },
        IfdTag {
            id: 0xd100,
            name: "VersionCreateDate",
            format: None,
            count: None,
            writable: Some("string"),
            groups: TagGroups {
                g0: None,
                g1: None,
                g2: Some("Time"),
            },
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::Expr(ExprId::SelfConvertDateTimeVal7455B8),
            subdir: None,
        },
        IfdTag {
            id: 0xd101,
            name: "VersionModifyDate",
            format: None,
            count: None,
            writable: Some("string"),
            groups: TagGroups {
                g0: None,
                g1: None,
                g2: Some("Time"),
            },
            flags: IfdFlags::NONE,
            condition: None,
            omitted: Omitted::NONE,
            raw_conv: None,
            value_conv: None,
            print_conv: PrintConv::Expr(ExprId::SelfConvertDateTimeVal7455B8),
            subdir: None,
        },
    ],
    variants: &[],
};
