//! Panasonic MakerNote binary sub-directory tables.
//!
//! GENERATED by `tools/exiftool-tables/codegen_subdirs.py` from ExifTool
//! 13.55's in-memory tag tables. Do not edit by hand.
//!
//! The generator refuses any construct it has not been taught and names it, so
//! a field that is here was reproduced exactly and a field that is missing was
//! reported as missing -- neither is a guess.

use crate::parsers::tiff::makernotes::shared::binary_subdir::{
    BinaryTable, Field, Fmt, PrintConv, ValueConv,
};

/// `Image::ExifTool::Panasonic::FaceDetInfo` -- 6 fields, FORMAT `int16u`.
///
/// Transcribed from ExifTool's in-memory tag table by
/// `tools/exiftool-tables/codegen_subdirs.py`. Do not edit by hand.
pub(crate) static PANASONIC_FACEDETINFO: BinaryTable = BinaryTable {
    name: "FaceDetInfo",
    default_format: Fmt::U16,
    first_entry: 0,
    fields: &[
        Field {
            index: 0,
            name: "NumFacePositions",
            format: Some(Fmt::U16),
            count: 1,
            set_member: Some("NumFacePositions"),
            gate: None,
            mask: None,
            value_conv: ValueConv::None,
            print_conv: PrintConv::None,
        },
        Field {
            index: 1,
            name: "Face1Position",
            format: Some(Fmt::U16),
            count: 4,
            set_member: None,
            gate: Some(("NumFacePositions", 1)),
            mask: None,
            value_conv: ValueConv::None,
            print_conv: PrintConv::None,
        },
        Field {
            index: 5,
            name: "Face2Position",
            format: Some(Fmt::U16),
            count: 4,
            set_member: None,
            gate: Some(("NumFacePositions", 2)),
            mask: None,
            value_conv: ValueConv::None,
            print_conv: PrintConv::None,
        },
        Field {
            index: 9,
            name: "Face3Position",
            format: Some(Fmt::U16),
            count: 4,
            set_member: None,
            gate: Some(("NumFacePositions", 3)),
            mask: None,
            value_conv: ValueConv::None,
            print_conv: PrintConv::None,
        },
        Field {
            index: 13,
            name: "Face4Position",
            format: Some(Fmt::U16),
            count: 4,
            set_member: None,
            gate: Some(("NumFacePositions", 4)),
            mask: None,
            value_conv: ValueConv::None,
            print_conv: PrintConv::None,
        },
        Field {
            index: 17,
            name: "Face5Position",
            format: Some(Fmt::U16),
            count: 4,
            set_member: None,
            gate: Some(("NumFacePositions", 5)),
            mask: None,
            value_conv: ValueConv::None,
            print_conv: PrintConv::None,
        },
    ],
};

/// `Image::ExifTool::Panasonic::FaceRecInfo` -- 10 fields, FORMAT `int8u`.
///
/// Transcribed from ExifTool's in-memory tag table by
/// `tools/exiftool-tables/codegen_subdirs.py`. Do not edit by hand.
pub(crate) static PANASONIC_FACERECINFO: BinaryTable = BinaryTable {
    name: "FaceRecInfo",
    default_format: Fmt::U8,
    first_entry: 0,
    fields: &[
        Field {
            index: 0,
            name: "FacesRecognized",
            format: Some(Fmt::U16),
            count: 1,
            set_member: Some("FacesRecognized"),
            gate: None,
            mask: None,
            value_conv: ValueConv::None,
            print_conv: PrintConv::None,
        },
        Field {
            index: 4,
            name: "RecognizedFace1Name",
            format: Some(Fmt::Str(20)),
            count: 1,
            set_member: None,
            gate: Some(("FacesRecognized", 1)),
            mask: None,
            value_conv: ValueConv::None,
            print_conv: PrintConv::None,
        },
        Field {
            index: 24,
            name: "RecognizedFace1Position",
            format: Some(Fmt::U16),
            count: 4,
            set_member: None,
            gate: Some(("FacesRecognized", 1)),
            mask: None,
            value_conv: ValueConv::None,
            print_conv: PrintConv::None,
        },
        Field {
            index: 32,
            name: "RecognizedFace1Age",
            format: Some(Fmt::Str(20)),
            count: 1,
            set_member: None,
            gate: Some(("FacesRecognized", 1)),
            mask: None,
            value_conv: ValueConv::None,
            print_conv: PrintConv::None,
        },
        Field {
            index: 52,
            name: "RecognizedFace2Name",
            format: Some(Fmt::Str(20)),
            count: 1,
            set_member: None,
            gate: Some(("FacesRecognized", 2)),
            mask: None,
            value_conv: ValueConv::None,
            print_conv: PrintConv::None,
        },
        Field {
            index: 72,
            name: "RecognizedFace2Position",
            format: Some(Fmt::U16),
            count: 4,
            set_member: None,
            gate: Some(("FacesRecognized", 2)),
            mask: None,
            value_conv: ValueConv::None,
            print_conv: PrintConv::None,
        },
        Field {
            index: 80,
            name: "RecognizedFace2Age",
            format: Some(Fmt::Str(20)),
            count: 1,
            set_member: None,
            gate: Some(("FacesRecognized", 2)),
            mask: None,
            value_conv: ValueConv::None,
            print_conv: PrintConv::None,
        },
        Field {
            index: 100,
            name: "RecognizedFace3Name",
            format: Some(Fmt::Str(20)),
            count: 1,
            set_member: None,
            gate: Some(("FacesRecognized", 3)),
            mask: None,
            value_conv: ValueConv::None,
            print_conv: PrintConv::None,
        },
        Field {
            index: 120,
            name: "RecognizedFace3Position",
            format: Some(Fmt::U16),
            count: 4,
            set_member: None,
            gate: Some(("FacesRecognized", 3)),
            mask: None,
            value_conv: ValueConv::None,
            print_conv: PrintConv::None,
        },
        Field {
            index: 128,
            name: "RecognizedFace3Age",
            format: Some(Fmt::Str(20)),
            count: 1,
            set_member: None,
            gate: Some(("FacesRecognized", 3)),
            mask: None,
            value_conv: ValueConv::None,
            print_conv: PrintConv::None,
        },
    ],
};
